-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("High Warlord Naj'entus", {
	[39837] = {"blue","red"},
	[39872] = {"green","red","yellow"},
})

BigWigs:AddSounds("High Warlord Naj'entus", {
	[39837] = "warning",
	[39872] = "alert",
})

BigWigs:AddColors("Supremus", {
	[40126] = "yellow",
	[40265] = "blue",
	["fixate"] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Supremus", {
	[40265] = "alert",
	["fixate"] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("Shade of Akama", {
	[42023] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shade of Akama", {
	[42023] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Teron Gorefiend", {
	[40243] = {"blue","orange"},
	[40251] = {"blue","red"},
})

BigWigs:AddSounds("Teron Gorefiend", {
	[40243] = "alert",
	[40251] = "warning",
})

BigWigs:AddColors("Gurtogg Bloodboil", {
	[40481] = {"blue","green"},
	[40491] = {"blue","green"},
	[40508] = {"blue","red"},
	[40604] = {"blue","cyan","orange"},
	[42005] = "yellow",
})

BigWigs:AddSounds("Gurtogg Bloodboil", {
	[40481] = "alarm",
	[40491] = "alert",
	[40508] = "alert",
	[40604] = {"info","warning"},
	[42005] = "info",
})

BigWigs:AddColors("Reliquary of Souls", {
	[41294] = {"blue","red"},
	[41303] = {"blue","yellow"},
	[41305] = {"green","orange"},
	[41376] = {"blue","red"},
	[41410] = "red",
	[41426] = {"blue","yellow"},
	[41431] = "orange",
	["zero_mana"] = "cyan",
})

BigWigs:AddSounds("Reliquary of Souls", {
	[41294] = "warning",
	[41303] = "alert",
	[41305] = "info",
	[41376] = "alert",
	[41410] = "info",
	[41426] = "alarm",
	[41431] = "warning",
})

BigWigs:AddColors("Mother Shahraz", {
	[40880] = "yellow",
	[40882] = "yellow",
	[40883] = "yellow",
	[40891] = "yellow",
	[40896] = "yellow",
	[40897] = "yellow",
	[41001] = {"blue","orange"},
})

BigWigs:AddSounds("Mother Shahraz", {
	[40880] = "info",
	[40882] = "info",
	[40883] = "info",
	[40891] = "info",
	[40896] = "info",
	[40897] = "info",
	[41001] = "alert",
})

BigWigs:AddColors("The Illidari Council", {
	[41450] = "red",
	[41451] = "red",
	[41453] = {"green","yellow"},
	[41455] = "orange",
	[41475] = {"green","red"},
	[41476] = {"green","yellow"},
	[41481] = "blue",
	[41482] = "blue",
	[41485] = {"blue","red"},
})

BigWigs:AddSounds("The Illidari Council", {
	[41450] = "info",
	[41451] = "info",
	[41455] = "warning",
	[41475] = "long",
	[41476] = "alert",
	[41481] = "alarm",
	[41482] = "alarm",
	[41485] = "alarm",
})

BigWigs:AddColors("Illidan Stormrage", {
	[39869] = "orange",
	[40018] = {"blue","yellow"},
	[40506] = {"green","red"},
	[40585] = {"blue","red"},
	[40611] = "blue",
	[40683] = "orange",
	[40695] = {"green","red"},
	[40841] = "blue",
	[40932] = {"blue","red"},
	[41032] = {"blue","red"},
	[41117] = "red",
	[41126] = "red",
	[41917] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Illidan Stormrage", {
	[39869] = "warning",
	[40018] = {"alert","info"},
	[40506] = "alarm",
	[40585] = "alert",
	[40611] = "alert",
	[40683] = "long",
	[40695] = {"info","warning"},
	[40841] = "alert",
	[40932] = "alert",
	[41032] = "alert",
	[41117] = "alert",
	[41126] = "alert",
	[41917] = "long",
	["stages"] = "alarm",
})
