-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Wrathion", {
	[305978] = {"blue","purple","yellow"},
	[306163] = {"blue","yellow"},
	[306289] = "red",
	[306735] = "red",
	[307013] = "red",
	[313250] = {"blue","green"},
	[313255] = {"blue","green"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Wrathion", {
	[305978] = {"alert","warning"},
	[306163] = "warning",
	[306289] = "alarm",
	[306735] = "alert",
	[307013] = "warning",
	[313250] = "info",
	[313255] = {"info","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Maut", {
	[305663] = "orange",
	[305722] = "cyan",
	[307586] = {"blue","green"},
	[307806] = "blue",
	[308044] = "red",
	[308872] = "purple",
	[308903] = "yellow",
	[310129] = {"blue","purple"},
	[314337] = {"green","red"},
	[314993] = "blue",
})

BigWigs:AddSounds("Maut", {
	[305663] = "alert",
	[305722] = "long",
	[307586] = "warning",
	[307806] = "warning",
	[308044] = "long",
	[308872] = "alarm",
	[308903] = "alarm",
	[310129] = "alarm",
	[314337] = {"info","warning"},
	[314993] = "warning",
})

BigWigs:AddColors("The Prophet Skitra", {
	[307725] = {"blue","green"},
	[307950] = {"blue","orange"},
	[308059] = {"blue","purple"},
	[313239] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("The Prophet Skitra", {
	[307725] = "long",
	[307950] = "warning",
	[308059] = {"alarm","warning"},
	[313239] = "alert",
})

BigWigs:AddColors("Dark Inquisitor Xanesh", {
	[305575] = "blue",
	[306208] = "yellow",
	[306319] = {"blue","yellow"},
	[311551] = {"blue","purple"},
	[312336] = "red",
	[312406] = {"blue","cyan"},
	[313264] = {"blue","red"},
})

BigWigs:AddSounds("Dark Inquisitor Xanesh", {
	[305575] = "alarm",
	[306208] = "long",
	[306319] = {"alarm","alert"},
	[311551] = {"alarm","alert"},
	[312336] = "warning",
	[312406] = "alarm",
	[313264] = "warning",
})

BigWigs:AddColors("The Hivemind", {
	[307201] = "orange",
	[307213] = "orange",
	[307232] = "orange",
	[307569] = "red",
	[307637] = "yellow",
	[307968] = "yellow",
	[310340] = "orange",
	[313652] = "yellow",
	[313672] = "blue",
	[314583] = "red",
})

BigWigs:AddSounds("The Hivemind", {
	[307201] = "long",
	[307213] = "long",
	[307232] = "warning",
	[307569] = "info",
	[307637] = "alert",
	[307968] = "alert",
	[310340] = "info",
	[313652] = "long",
	[313672] = "alarm",
	[314583] = "warning",
})

BigWigs:AddColors("Shad'har the Insatiable", {
	[306448] = "orange",
	[306928] = "red",
	[306929] = "red",
	[306930] = "red",
	[306942] = "cyan",
	[306953] = {"blue","yellow"},
	[307471] = {"blue","cyan","purple"},
	[307472] = {"blue","cyan","purple"},
	[312099] = {"blue","green"},
	[312328] = "orange",
	[314736] = "blue",
	[318078] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shad'har the Insatiable", {
	[306448] = "alarm",
	[306928] = "alert",
	[306929] = "alert",
	[306930] = "alert",
	[306942] = "info",
	[306953] = "info",
	[307471] = {"alarm","info"},
	[307472] = {"alarm","info"},
	[312099] = {"info","long"},
	[312328] = "alarm",
	[314736] = "alarm",
	[318078] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Drest'agath", {
	[308377] = "green",
	[308941] = {"cyan","orange"},
	[310246] = "red",
	[310277] = {"blue","purple"},
	[310329] = "yellow",
	[310358] = {"blue","yellow"},
	[310390] = "orange",
	[310580] = "blue",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Drest'agath", {
	[308377] = "warning",
	[308941] = {"info","long"},
	[310246] = "alarm",
	[310277] = "alarm",
	[310329] = "alert",
	[310358] = "warning",
	[310390] = "alert",
	[310580] = "alarm",
	["adds"] = "info",
})

BigWigs:AddColors("Vexiona", {
	[307020] = "orange",
	[307057] = "cyan",
	[307116] = "cyan",
	[307314] = {"blue","yellow"},
	[307343] = "blue",
	[307359] = {"blue","red"},
	[307403] = "yellow",
	[307639] = "red",
	[307729] = "orange",
	[310323] = {"blue","yellow"},
	[315762] = "red",
	[315932] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Vexiona", {
	[307020] = "alarm",
	[307057] = "info",
	[307116] = "info",
	[307314] = "warning",
	[307343] = "alarm",
	[307359] = "warning",
	[307403] = "alert",
	[307639] = "alert",
	[307729] = "long",
	[310323] = "warning",
	[315762] = "warning",
	[315932] = "alarm",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Ra-den the Despoiled", {
	[306273] = {"blue","cyan"},
	[306603] = "orange",
	[306732] = "cyan",
	[306733] = "cyan",
	[306819] = {"blue","purple"},
	[306865] = "yellow",
	[306866] = "yellow",
	[306881] = {"blue","red"},
	[310003] = "yellow",
	[310019] = {"blue","cyan","green"},
	[312996] = "cyan",
	[313077] = {"blue","red"},
	[313213] = {"blue","purple","red"},
	[314484] = "yellow",
	[315252] = "blue",
	[316065] = {"blue","cyan"},
	["essences"] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ra-den the Despoiled", {
	[306273] = "warning",
	[306603] = "alarm",
	[306732] = "info",
	[306733] = "info",
	[306819] = "alarm",
	[306865] = "alert",
	[306866] = "alert",
	[306881] = "alarm",
	[310003] = "alert",
	[310019] = {"info","warning"},
	[312996] = "info",
	[313077] = "warning",
	[313213] = {"alarm","alert"},
	[314484] = "alert",
	[315252] = "alarm",
	[316065] = "warning",
	["essences"] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Il'gynoth, Corruption Reborn", {
	[309961] = "purple",
	[310322] = "blue",
	[310433] = "orange",
	[311401] = "yellow",
	[313759] = {"blue","yellow"},
	[318383] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Il'gynoth, Corruption Reborn", {
	[309961] = "warning",
	[310322] = "alarm",
	[310433] = "long",
	[311401] = "long",
	[313759] = "warning",
	[318383] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Carapace of N'Zoth", {
	[-21069] = "red",
	[-20565] = "red",
	[-20560] = "red",
	[306973] = {"blue","yellow"},
	[306984] = "yellow",
	[306988] = "orange",
	[307011] = "blue",
	[307064] = "green",
	[307079] = {"blue","green"},
	[307092] = "red",
	[307809] = "yellow",
	[313039] = "red",
	[315947] = "orange",
	[315954] = {"blue","purple"},
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Carapace of N'Zoth", {
	[-21069] = "alert",
	[-20565] = "alert",
	[-20560] = "info",
	[306973] = "warning",
	[306984] = "warning",
	[306988] = "alarm",
	[307011] = "info",
	[307064] = "long",
	[307092] = "alarm",
	[307809] = "alert",
	[315954] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("N'Zoth, the Corruptor", {
	[-21491] = "yellow",
	[-21286] = "yellow",
	[309698] = "purple",
	[309991] = "blue",
	[310042] = "red",
	[310184] = "yellow",
	[312155] = "green",
	[312866] = "orange",
	[313184] = {"blue","green"},
	[313400] = {"blue","orange","red"},
	[313609] = {"blue","yellow"},
	[313960] = "cyan",
	[315772] = "yellow",
	[315927] = {"blue","green","orange"},
	[316463] = "green",
	[316711] = {"blue","purple","red"},
	[316970] = "yellow",
	[317066] = "orange",
	[317102] = "red",
	[318091] = "cyan",
	[318196] = {"blue","orange"},
	[318449] = "yellow",
	[318459] = {"blue","orange"},
	[318971] = "orange",
	[318976] = "yellow",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("N'Zoth, the Corruptor", {
	[-21491] = "info",
	[-21286] = "long",
	[309698] = "alert",
	[309991] = "alarm",
	[310042] = "warning",
	[310184] = "alarm",
	[312155] = "long",
	[312866] = "warning",
	[313184] = "info",
	[313400] = {"alarm","alert"},
	[313609] = "warning",
	[313960] = "alert",
	[315772] = "long",
	[315927] = {"info","warning"},
	[316463] = "long",
	[316711] = {"alarm","warning"},
	[316970] = "alert",
	[317066] = "alarm",
	[317102] = "warning",
	[318091] = "long",
	[318196] = "warning",
	[318449] = "alert",
	[318459] = "warning",
	[318971] = "alarm",
	[318976] = "long",
	["stages"] = {"info","long"},
})
