-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Beth'tilac", {
	[99052] = {"green","red","yellow"},
	[99497] = "green",
	[99506] = {"blue","orange"},
	[99559] = {"blue","yellow"},
	[99990] = {"blue","red"},
	["drone"] = "yellow",
	["spinner"] = "green",
})

BigWigs:AddSounds("Beth'tilac", {
	[99052] = "long",
	[99497] = "alarm",
	[99506] = "info",
	[99559] = "alarm",
	[99990] = "alert",
	["drone"] = "info",
})

BigWigs:AddColors("Lord Rhyolith", {
	[-2537] = "green",
	[97225] = "red",
	[97282] = "orange",
	[98136] = "yellow",
	[98255] = {"red","yellow"},
	[98493] = "yellow",
	[98552] = "red",
	["armor"] = "green",
})

BigWigs:AddSounds("Lord Rhyolith", {
	[-2537] = "info",
	[97225] = "alarm",
	[97282] = "alert",
	[98136] = "info",
	[98255] = "alarm",
	[98493] = "info",
	[98552] = "alarm",
})

BigWigs:AddColors("Alysrazor", {
	[97128] = "blue",
	[99362] = "red",
	[99432] = "green",
	[99464] = "green",
	[99816] = {"red","yellow"},
	[99844] = {"blue","orange"},
	[99925] = {"green","orange","yellow"},
	[100024] = "blue",
	[100744] = "orange",
	["eggs"] = "green",
	["meteor"] = "yellow",
})

BigWigs:AddSounds("Alysrazor", {
	[99432] = "alert",
	[99816] = "alarm",
	[99844] = "info",
	[99925] = "alert",
	[100744] = "alert",
	["meteor"] = "alarm",
})

BigWigs:AddColors("Shannox", {
	[100002] = "yellow",
	[100129] = {"blue","green","red"},
	["crystal"] = {"blue","orange"},
	["immolation"] = "yellow",
	["immolationyou"] = "blue",
})

BigWigs:AddSounds("Shannox", {
	[100002] = "info",
	[100129] = "alert",
	["crystal"] = "alarm",
	["immolationyou"] = "alarm",
})

BigWigs:AddColors("Baleroc", {
	[-2598] = "yellow",
	[99259] = "orange",
	[99516] = {"blue","red"},
	["torment"] = "blue",
})

BigWigs:AddSounds("Baleroc", {
	[99259] = "alert",
	[99516] = "alarm",
	["torment"] = "info",
})

BigWigs:AddColors("Majordomo Staghelm", {
	[97238] = "yellow",
	[98374] = "red",
	[98379] = "red",
	[98450] = "blue",
	[98476] = {"blue","orange"},
})

BigWigs:AddSounds("Majordomo Staghelm", {
	[98374] = "alert",
	[98379] = "alert",
	[98450] = "warning",
	[98476] = "long",
})

BigWigs:AddColors("Ragnaros", {
	[98498] = "orange",
	[98710] = "yellow",
	[98953] = "green",
	[99172] = "red",
	[99317] = "yellow",
	[99399] = {"blue","orange"},
	[99849] = "blue",
	[100171] = "red",
	[100460] = {"blue","yellow"},
	[100479] = "green",
	[100604] = "orange",
	[100646] = "green",
	[100675] = "red",
	[100714] = "green",
})

BigWigs:AddSounds("Ragnaros", {
	[98498] = "alarm",
	[98710] = "info",
	[98953] = "long",
	[99172] = "alert",
	[99399] = "info",
	[99849] = "long",
	[100171] = "alert",
	[100460] = "info",
	[100675] = "alarm",
})
