----- AUTO GENERATED - DO NOT EDIT

local L = BtWQuests.L
L["ESTABLISHING_AXEFALL_THE_ANTIDOTE"] = "Establishing Axefall: The Antidote"
L["ESTABLISHING_AXEFALL_VEIL_ZEKK"] = "Establishing Axefall: Veil Zekk"
L["HEARTHFIRE_TAVERN_BUILT"] = "Hearthfire Tavern Built"
L["HIGHPASS_LOGGING_CAMP_BUILT"] = "Highpass Logging Camp Built"
L["HIGHPASS_SPARRING_RING_BUILT"] = "Highpass Sparring Ring Built"
L["IN_THE_LAND_OF_GIANTS_HIGHPASS_LOGGING_CAMP"] = "In the Land of Giants: Highpass Logging Camp"
L["IN_THE_LAND_OF_GIANTS_HIGHPASS_SPARRING_RING"] = "In the Land of Giants: Highpass Sparring Ring"
L["IN_THE_LAND_OF_GIANTS_LOWLANDS_LUMBER_YARD"] = "In the Land of Giants: Lowlands Lumber Yard"
L["IN_THE_LAND_OF_GIANTS_SAVAGE_FIGHT_CLUB"] = "In the Land of Giants: Savage Fight Club"
L["LOWLANDS_LUMBER_YARD_BUILT"] = "Lowlands Lumber Yard Built"
L["SAVAGE_FIGHT_CLUB_BUILT"] = "Savage Fight Club Built"
L["SECURING_SOUTHPORT_THE_ANTIDOTE"] = "Securing Southport: The Antidote"
L["SECURING_SOUTHPORT_VEIL_ZEKK"] = "Securing Southport: Veil Zekk"
L["SMUGGLERS_DEN_BUILT"] = "Smuggler's Den Built"
L["STOKTRON_BREWERY_BUILT"] = "Stoktron Brewery Built"
L["SUPPORTING_YOUR_GARRISON_HIGHPASS_LOGGING_CAMP"] = "Supporting Your Garrison: Highpass Logging Camp"
L["SUPPORTING_YOUR_GARRISON_HIGHPASS_SPARRING_RING"] = "Supporting Your Garrison: Highpass Sparring Ring"
L["SUPPORTING_YOUR_GARRISON_LOWLANDS_LUMBER_YARD"] = "Supporting Your Garrison: Lowlands Lumber Yard"
L["SUPPORTING_YOUR_GARRISON_SAVAGE_FIGHT_CLUB"] = "Supporting Your Garrison: Savage Fight Club"
L["THE_IRON_APPROACH_HIGHPASS_LOGGING_CAMP"] = "The Iron Approach: Highpass Logging Camp"
L["THE_IRON_APPROACH_HIGHPASS_SPARRING_RING"] = "The Iron Approach: Highpass Sparring Ring"
L["THE_IRON_APPROACH_LOWLANDS_LUMBER_YARD"] = "The Iron Approach: Lowlands Lumber Yard"
L["THE_IRON_APPROACH_SAVAGE_FIGHT_CLUB"] = "The Iron Approach: Savage Fight Club"
