-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Nythendra", {
	[202977] = "orange",
	[203045] = "blue",
	[203096] = {"blue","red"},
	[203552] = "cyan",
	[204463] = {"blue","orange"},
	[204504] = "blue",
	[225943] = {"blue","yellow"},
})

BigWigs:AddSounds("Nythendra", {
	[202977] = "alarm",
	[203045] = "alert",
	[203096] = "warning",
	[203552] = "info",
	[204463] = "warning",
	[204504] = "warning",
	[225943] = "long",
})

BigWigs:AddColors("Il'gynoth", {
	[208689] = "blue",
	[208697] = {"cyan","yellow"},
	[208929] = {"blue","cyan","orange"},
	[209469] = {"blue","red"},
	[210099] = {"blue","yellow"},
	[210984] = {"blue","red"},
	[212886] = "blue",
	[215128] = {"blue","yellow"},
	[215234] = "orange",
	[218415] = {"green","orange"},
	[223121] = "cyan",
	["nightmare_horror"] = "red",
	["shriveled_eyestalk"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Il'gynoth", {
	[208689] = "alarm",
	[208697] = "info",
	[208929] = {"alert","info"},
	[210099] = "info",
	[210984] = "warning",
	[212886] = "alert",
	[215128] = {"alert","warning"},
	[218415] = {"alarm","long"},
	[223121] = "info",
	["nightmare_horror"] = "info",
	["shriveled_eyestalk"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Elerethe Renferal", {
	[210547] = "red",
	[210864] = {"blue","orange"},
	[210948] = "cyan",
	[212364] = "red",
	[212707] = "yellow",
	[213124] = "blue",
	[214348] = "yellow",
	[215300] = {"blue","yellow"},
	[215443] = {"blue","orange"},
	[215582] = "yellow",
	[218124] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Elerethe Renferal", {
	[210547] = "alarm",
	[210864] = {"long","warning"},
	[210948] = "info",
	[212364] = "info",
	[212707] = "long",
	[213124] = "alert",
	[214348] = "alarm",
	[215300] = "warning",
	[215443] = {"long","warning"},
	[215582] = "long",
	[218124] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Ursoc", {
	[197943] = {"blue","red"},
	[197969] = "orange",
	[198006] = {"blue","red"},
	[198388] = {"cyan","orange"},
	[204859] = {"blue","yellow"},
	[205611] = "blue",
})

BigWigs:AddSounds("Ursoc", {
	[197943] = {"alarm","warning"},
	[197969] = "alarm",
	[198006] = "warning",
	[198388] = {"info","long"},
	[204859] = {"info","warning"},
	[205611] = "alert",
})

BigWigs:AddColors("Dragons of Nightmare", {
	[-13460] = "cyan",
	[-12809] = {"blue","green","red"},
	[203028] = "orange",
	[203147] = "red",
	[203770] = {"blue","yellow"},
	[203787] = {"blue","yellow"},
	[203888] = "red",
	[204040] = "blue",
	[204078] = "red",
	[204100] = "orange",
	[204245] = "yellow",
	[204767] = "yellow",
	[205298] = "yellow",
	[205300] = "yellow",
	[205341] = "orange",
	[207573] = "red",
})

BigWigs:AddSounds("Dragons of Nightmare", {
	[-13460] = "long",
	[-12809] = {"info","warning"},
	[203028] = "info",
	[203147] = "alert",
	[203770] = {"alarm","alert"},
	[203787] = "alert",
	[203888] = "alert",
	[204040] = "warning",
	[204078] = "alarm",
	[204100] = "long",
	[204245] = "alarm",
	[204767] = "long",
	[205298] = "long",
	[205300] = "info",
	[205341] = "alarm",
})

BigWigs:AddColors("Cenarius", {
	[210279] = {"blue","green","orange"},
	[210290] = "orange",
	[210346] = {"blue","green","orange"},
	[211192] = {"blue","yellow"},
	[211368] = {"blue","orange","red"},
	[211471] = {"blue","red"},
	[211989] = "blue",
	[212681] = "green",
	[212726] = {"cyan","orange"},
	[213162] = "orange",
	[214505] = {"blue","orange"},
	[214529] = {"blue","orange"},
	[214876] = "red",
	[214884] = "yellow",
	[226821] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Cenarius", {
	[210279] = {"info","warning"},
	[210290] = "alarm",
	[210346] = {"alarm","info"},
	[211192] = "alert",
	[211368] = "alarm",
	[211471] = "alert",
	[211989] = "alert",
	[212681] = "alert",
	[212726] = "info",
	[213162] = "alert",
	[214505] = "alarm",
	[214529] = "warning",
	[214876] = "alert",
	[214884] = "info",
	[226821] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Xavius", {
	[205588] = "yellow",
	[205741] = "blue",
	[205771] = "blue",
	[205843] = "green",
	[206005] = "blue",
	[206651] = {"blue","orange"},
	[207409] = {"blue","red"},
	[207830] = "yellow",
	[208431] = "blue",
	[209034] = {"blue","red"},
	[209158] = {"blue","orange"},
	[209443] = {"blue","orange"},
	[210264] = "yellow",
	[211634] = "blue",
	[211802] = {"blue","red"},
	[224508] = {"blue","yellow"},
	[226194] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Xavius", {
	[205588] = "info",
	[205741] = "alert",
	[205771] = "long",
	[205843] = "long",
	[206005] = "info",
	[206651] = "warning",
	[207409] = "alarm",
	[208431] = "alarm",
	[209034] = {"alert","warning"},
	[209158] = "warning",
	[209443] = "alarm",
	[210264] = "info",
	[211634] = "alert",
	[211802] = "alert",
	[224508] = "info",
	[226194] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Emerald Nightmare Trash", {
	[221028] = "blue",
	[221059] = "orange",
	[222719] = {"blue","green"},
	["totem"] = "red",
})

BigWigs:AddSounds("Emerald Nightmare Trash", {
	[221028] = "warning",
	[221059] = "info",
	[222719] = "alert",
	["totem"] = "long",
})
