-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Onyxia", {
	[17086] = "red",
	[18392] = {"blue","yellow"},
	[18431] = "yellow",
	[18435] = "orange",
	[18958] = {"blue","purple"},
	[364849] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Onyxia", {
	[17086] = "warning",
	[18392] = "alarm",
	[18431] = "info",
	[18435] = "alert",
	[364849] = "alert",
	["stages"] = "long",
})
