-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Atal'alarion Discovery", {
	[437503] = "yellow",
	[437597] = "red",
})

BigWigs:AddSounds("Atal'alarion Discovery", {
	[437503] = "info",
	[437597] = "warning",
})

BigWigs:AddColors("Festering Rotslime Discovery", {
	[438136] = "blue",
	[438142] = {"green","yellow"},
})

BigWigs:AddSounds("Festering Rotslime Discovery", {
	[438136] = "underyou",
	[438142] = "alert",
})

BigWigs:AddColors("Atal'ai Defenders Discovery", {
	[23511] = "red",
	[438294] = "orange",
	[438335] = "red",
	[438341] = {"green","red"},
	[438350] = "red",
	[445284] = {"blue","yellow"},
	[445289] = "orange",
	[446338] = "red",
	[446360] = "orange",
	[446364] = {"green","yellow"},
	[446372] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Atal'ai Defenders Discovery", {
	[23511] = "warning",
	[438335] = "alert",
	[438341] = "warning",
	[438350] = "warning",
	[445289] = "alarm",
	[446338] = "warning",
	[446360] = "alarm",
	[446364] = "alert",
	[446372] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Dreamscythe and Weaver Discovery", {
	[442622] = {"blue","purple"},
	[443766] = "yellow",
	[443856] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Dreamscythe and Weaver Discovery", {
	[442622] = "alert",
	[443766] = "info",
	[443856] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("Jammal'an and Ogom Discovery", {
	[437809] = "yellow",
	[437817] = "red",
	[437847] = {"blue","orange"},
	[437868] = {"green","red"},
	[437921] = "orange",
	[437927] = "red",
	[437928] = "yellow",
	[437930] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Jammal'an and Ogom Discovery", {
	[437809] = "alarm",
	[437817] = "warning",
	[437847] = "info",
	[437868] = "alert",
	[437921] = "alert",
	[437927] = "alarm",
	[437928] = "long",
	[437930] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Morphaz and Hazzas Discovery", {
	[446468] = "orange",
	[446487] = {"blue","purple"},
	[446489] = "red",
	[446661] = "cyan",
})

BigWigs:AddSounds("Morphaz and Hazzas Discovery", {
	[446468] = "alert",
	[446487] = "alert",
	[446489] = "alarm",
	[446661] = "info",
})

BigWigs:AddColors("Shade of Eranikus Discovery", {
	[3391] = "purple",
	[437301] = "cyan",
	[437324] = {"blue","green"},
	[437353] = {"blue","purple"},
	[437390] = {"blue","green","yellow"},
	[437398] = "orange",
	[437416] = "cyan",
	[445498] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Shade of Eranikus Discovery", {
	[3391] = "info",
	[437301] = "info",
	[437324] = {"alarm","info"},
	[437353] = {"alarm","alert"},
	[437390] = {"alarm","alert","info"},
	[437398] = "warning",
	[437416] = "long",
	[445498] = "warning",
})

BigWigs:AddColors("Avatar of Hakkar Discovery", {
	[443953] = "blue",
	[443990] = {"green","red"},
	[444039] = {"blue","red"},
	[444046] = {"green","orange"},
	[444132] = "yellow",
	[444255] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Avatar of Hakkar Discovery", {
	[443953] = "underyou",
	[443990] = "warning",
	[444039] = "warning",
	[444046] = "alarm",
	[444132] = "long",
	[444255] = "alarm",
	["stages"] = "info",
})
