-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Balnazzar Scarlet Enclave", {
	[1231837] = {"blue","red"},
	[1231844] = {"blue","red"},
	[1231901] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Balnazzar Scarlet Enclave", {
	[1231837] = "alert",
	[1231844] = "warning",
	[1231901] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("High Commander Beatrix", {
	[1231873] = "blue",
	[1232389] = {"blue","purple"},
	[1232390] = {"blue","red"},
	[1232637] = {"blue","red"},
	[1237324] = "blue",
	["arrows"] = "yellow",
	["bombing"] = "yellow",
	["meteor"] = "orange",
	["stages"] = "cyan",
	["waves"] = "yellow",
})

BigWigs:AddSounds("High Commander Beatrix", {
	[1231873] = "warning",
	[1232389] = "alarm",
	[1232637] = "warning",
	[1237324] = "underyou",
	["arrows"] = "info",
	["bombing"] = "info",
	["meteor"] = "alert",
	["stages"] = "long",
	["waves"] = "info",
})

BigWigs:AddColors("Solistrasza", {
	[1227696] = "red",
	[1228063] = {"blue","yellow"},
	[1231993] = {"blue","purple"},
	[1232097] = {"blue","orange"},
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Solistrasza", {
	[1227696] = "alarm",
	[1228063] = {"underyou","warning"},
	[1231993] = "alert",
	[1232097] = "warning",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Alexei the Beastlord", {
	[1228295] = "red",
	[1230105] = "yellow",
	[1230200] = "blue",
	[1230242] = "blue",
	[1230899] = "orange",
})

BigWigs:AddSounds("Alexei the Beastlord", {
	[1228295] = "alert",
	[1230105] = "warning",
	[1230200] = "info",
	[1230242] = "info",
	[1230899] = "long",
})

BigWigs:AddColors("Mason the Echo", {
	[1229005] = {"blue","purple"},
	[1231585] = {"cyan","red"},
	[1231592] = {"green","orange"},
	[1234347] = {"green","yellow"},
})

BigWigs:AddSounds("Mason the Echo", {
	[1229005] = "alarm",
	[1231585] = "long",
	[1231592] = "alert",
	[1234347] = "info",
})

BigWigs:AddColors("Reborn Council", {
	[1231095] = {"green","orange"},
	[1231264] = "yellow",
	[1231282] = "cyan",
	[1231383] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Reborn Council", {
	[1231095] = "info",
	[1231264] = "warning",
	[1231282] = "long",
	[1231383] = "alarm",
})

BigWigs:AddColors("Lillian Voss", {
	[1232192] = {"blue","purple"},
	[1233847] = "red",
	[1233849] = "blue",
	[1233883] = {"blue","green"},
	[1233901] = "blue",
	[1234540] = "yellow",
})

BigWigs:AddSounds("Lillian Voss", {
	[1233847] = "long",
	[1233849] = "alert",
	[1233883] = "warning",
	[1233901] = "alarm",
	[1234540] = "info",
})

BigWigs:AddColors("Grand Crusader Caldoran", {
	[1229114] = "yellow",
	[1229272] = {"blue","yellow"},
	[1229503] = {"blue","purple"},
	[1229714] = "red",
	[1230697] = "cyan",
	[1231027] = "yellow",
	[1231618] = "orange",
	[1231651] = "orange",
	[1231654] = "orange",
	["run"] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Grand Crusader Caldoran", {
	[1229114] = "alert",
	[1229272] = "alarm",
	[1229503] = "info",
	[1229714] = "warning",
	[1230697] = "alarm",
	[1231027] = "long",
	[1231618] = "alert",
	[1231651] = "alert",
	[1231654] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Scarlet Enclave Trash", {
	["stages"] = "cyan",
})

BigWigs:AddSounds("Scarlet Enclave Trash", {
})
