---@class Private
local Private = select(2, ...)

local L = Private.L

L["Difficulty-1"] = "L"
L["Difficulty-3"] = "N"
L["Difficulty-4"] = "H"
L["Difficulty-5"] = "M"
L["DifficultyName-1"] = "LFR"
L["DifficultyName-3"] = "Normal"
L["DifficultyName-4"] = "Heroic"
L["DifficultyName-5"] = "Mythic"
L["AllStars"] = "All Stars"
L["Rank"] = "Rank"
L["Kills"] = "Kills"
L["Unknown"] = [[Unknown]]
L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
L["CopyProfileURL"] = [[Copy WCL URL]]
L["Subscriber"] = [[Subscriber]]
L["ShiftToExpand"] = [[<Shift> to Expand]]
L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
L["Main"] = [[Main]]
L["ClickToOpenSettings"] = [[Click to open Settings]]
L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
L["ShowRank"] = [[Show Rank]]
L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
L["ShowAsp"] = [[Show All Stars]]
L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
L["ShowShiftHint"] = [[Show Shift Hint]]
L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
L["MenuIntegration"] = [[Extend Menu Options]]
L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
L["SettingsLookupNoData"] = [[No data found.]]
L["SettingsLookupDataFor"] = [[%s for %s - %s]]
L["SettingsAvailableCommands"] = [[Available commands:]]
L["SettingsOpenSettingsLabel"] = [[opens the settings]]
L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

if Private.IsRetail then
    L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
    L["Encounter-3129"] = [[Plexus Sentinel]]
    L["Encounter-3131"] = [[Loom'ithar]]
    L["Encounter-3130"] = [[Soulbinder Naazindhri]]
    L["Encounter-3132"] = [[Forgeweaver Araz]]
    L["Encounter-3122"] = [[The Soul Hunters]]
    L["Encounter-3133"] = [[Fractillus]]
    L["Encounter-3134"] = [[Nexus-King Salhadaar]]
    L["Encounter-3135"] = [[Dimensius, the All-Devouring]]
elseif Private.IsMists then
    L["addon.parse-gate-description"] = "Parses shown after 25H kills"
    L["Encounter-1507"] = [[Imperial Vizier Zor'lok]]
    L["Encounter-1504"] = [[Blade Lord Ta'yak]]
    L["Encounter-1463"] = [[Garalon]]
    L["Encounter-1498"] = [[Wind Lord Mel'jarak]]
    L["Encounter-1499"] = [[Amber-Shaper Un'sok]]
    L["Encounter-1501"] = [[Grand Empress Shek'zeer]]
    L["Encounter-1409"] = [[Protectors of the Endless]]
    L["Encounter-1505"] = [[Tsulong]]
    L["Encounter-1506"] = [[Lei Shi]]
    L["Encounter-1431"] = [[Sha of Fear]]
elseif Private.IsCata then
    L["addon.parse-gate-description"] = "Parses shown after 20H kills"
    L["Encounter-51292"] = [[Morchok]]
    L["Encounter-51294"] = [[Warlord Zon'ozz]]
    L["Encounter-51295"] = [[Yor'sahj the Unsleeping]]
    L["Encounter-51296"] = [[Hagara the Stormbinder]]
    L["Encounter-51297"] = [[Ultraxion]]
    L["Encounter-51298"] = [[Warmaster Blackhorn]]
    L["Encounter-51291"] = [[Spine of Deathwing]]
    L["Encounter-51299"] = [[Madness of Deathwing]]
elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
    L["addon.parse-gate-description"] = ""
    L["Encounter-3185"] = [[Balnazzar]]
    L["Encounter-3187"] = [[Beatrix]]
    L["Encounter-3186"] = [[Solistrasza]]
    L["Encounter-3197"] = [[Mason]]
    L["Encounter-3196"] = [[Beastmaster]]
    L["Encounter-3188"] = [[Reborn Council]]
    L["Encounter-3190"] = [[Lillian Voss]]
    L["Encounter-3189"] = [[Caldoran]]
elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
    L["addon.parse-gate-description"] = "Parses shown after 20H kills"
    L["Encounter-251118"] = [[Patchwerk]]
    L["Encounter-251111"] = [[Grobbulus]]
    L["Encounter-251108"] = [[Gluth]]
    L["Encounter-251120"] = [[Thaddius]]
    L["Encounter-251117"] = [[Noth the Plaguebringer]]
    L["Encounter-251112"] = [[Heigan the Unclean]]
    L["Encounter-251115"] = [[Loatheb]]
    L["Encounter-251107"] = [[Anub'Rekhan]]
    L["Encounter-251110"] = [[Grand Widow Faerlina]]
    L["Encounter-251116"] = [[Maexxna]]
    L["Encounter-251113"] = [[Instructor Razuvious]]
    L["Encounter-251109"] = [[Gothik the Harvester]]
    L["Encounter-251121"] = [[The Four Horsemen]]
    L["Encounter-251119"] = [[Sapphiron]]
    L["Encounter-251114"] = [[Kel'Thuzad]]
end

local locale = GAME_LOCALE or GetLocale()

if locale == "deDE" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "Schlachtzugsbrowser"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroisch"
    L["DifficultyName-5"] = "Mythisch"
    L["AllStars"] = "Bestplatzierte"
    L["Rank"] = "Rang"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unbekannt]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Abonnent]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[Keine Daten gefunden]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3129"] = [[Plexuswache]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Seelenbinderin Naazindhri]]
        L["Encounter-3132"] = [[Schmiedeweber Araz]]
        L["Encounter-3122"] = [[Die Seelenjäger]]
        L["Encounter-3133"] = [[Fraktillus]]
        L["Encounter-3134"] = [[Nexuskönig Salhadaar]]
        L["Encounter-3135"] = [[Dimensius der alles Verschlingende]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 25H kills"
        L["Encounter-1507"] = [[Kaiserlicher Wesir Zor'lok]]
        L["Encounter-1504"] = [[Klingenfürst Ta'yak]]
        L["Encounter-1463"] = [[Garalon]]
        L["Encounter-1498"] = [[Windfürst Mel'jarak]]
        L["Encounter-1499"] = [[Bernformer Un'sok]]
        L["Encounter-1501"] = [[Großkaiserin Shek'zeer]]
        L["Encounter-1409"] = [[Beschützer des Endlosen]]
        L["Encounter-1505"] = [[Tsulong]]
        L["Encounter-1506"] = [[Lei Shi]]
        L["Encounter-1431"] = [[Sha der Angst]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-51292"] = [[Morchok]]
        L["Encounter-51294"] = [[Kriegsherr Zon'ozz]]
        L["Encounter-51295"] = [[Yor'sahj der Unermüdliche]]
        L["Encounter-51296"] = [[Hagara die Sturmbinderin]]
        L["Encounter-51297"] = [[Ultraxion]]
        L["Encounter-51298"] = [[Kriegsmeister Schwarzhorn]]
        L["Encounter-51291"] = [[Todesschwinges Rückgrat]]
        L["Encounter-51299"] = [[Todesschwinges Wahnsinn]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Bestienmeister]]
        L["Encounter-3188"] = [[Wiedergeborener Rat]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-251118"] = [[Flickwerk]]
        L["Encounter-251111"] = [[Grobbulus]]
        L["Encounter-251108"] = [[Gluth]]
        L["Encounter-251120"] = [[Thaddius]]
        L["Encounter-251117"] = [[Noth der Seuchenfürst]]
        L["Encounter-251112"] = [[Heigan der Unreine]]
        L["Encounter-251115"] = [[Loatheb]]
        L["Encounter-251107"] = [[Anub'Rekhan]]
        L["Encounter-251110"] = [[Großwitwe Faerlina]]
        L["Encounter-251116"] = [[Maexxna]]
        L["Encounter-251113"] = [[Instrukteur Razuvious]]
        L["Encounter-251109"] = [[Gothik der Ernter]]
        L["Encounter-251121"] = [[Die Vier Reiter]]
        L["Encounter-251119"] = [[Saphiron]]
        L["Encounter-251114"] = [[Kel'Thuzad]]
    end
elseif locale == "esES" or locale == "esMX" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "BDB"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Los Mejores"
    L["Rank"] = "Rango"
    L["Kills"] = "Asesinatos"
    L["Unknown"] = [[Desconocido]]
    L["UnknownRealm"] = [[[%s] El reino '%s' (id %d) no está en la base de datos. Por favor, informa al equipo de Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copiar URL de WCL]]
    L["Subscriber"] = [[Suscriptor ]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Falta la base de datos de '%s' (%s). Puede que hayas iniciado sesión en el juego mientras el addon se estaba actualizando. Comprueba en la aplicación de escritorio si la actualización ha terminado y, después, ejecuta '/reload' para intentarlo de nuevo.]]
    L["DBLoadError"] = [[[%s] No se ha podido cargar la base de datos de '%s'. Motivo: %s ]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Haz clic para abrir la configuración]]
    L["ShowTooltipInCombat"] = [[Mostrar Tips de herramientas en Combate]]
    L["ShowTooltipInCombatDescription"] = [[Si extender los consejos de herramienta en combate también. Está desactivado de manera predeterminada como optimización]]
    L["AllowShiftExpansionInCombat"] = [[Mostrar extensión de shift en combate
]]
    L["AllowShiftExpansionInCombatDescription"] = [[Si cargar datos extendidos en combate también. Activa la configuración de arriba]]
    L["ShowRank"] = [[Mostrar rango]]
    L["ShowRankDescription"] = [[Activa o desactiva la inclusión del rango en la información emergente.]]
    L["ShowAsp"] = [[Mostrar todas las estrellas]]
    L["ShowAspDescription"] = [[Activa o desactiva la inclusión de los puntos de Todas las Estrellas en el tooltip.]]
    L["ShowShiftHint"] = [[Mostrar tips de Shift]]
    L["ShowShiftHintDescription"] = [[Activa o desactiva la sugerencia de mantener Shift para ampliar la información.]]
    L["MenuIntegration"] = [[Opciones de menú extendidas]]
    L["MenuIntegrationDescription"] = [[Si extender los menús con una opción para copiar el URL del perfil del personaje]]
    L["SettingsLookupUsage"] = [[Uso /%s buscar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Datos no encontrados]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponibles:]]
    L["SettingsOpenSettingsLabel"] = [[Abre la configuración]]
    L["SettingsLookupLabel"] = [[buscar perfil por nombre y región]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses mostrados después de muertes en 20H o 5M"
        L["Encounter-3129"] = [[Centinela del plexo]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Vinculadora de almas Naazindhri]]
        L["Encounter-3132"] = [[Tejeforjas Araz]]
        L["Encounter-3122"] = [[Los cazaalmas]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Rey-nexo Salhadaar]]
        L["Encounter-3135"] = [[Dimensius el Devoratodo]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses mostrados tras 25H muertes"
        L["Encounter-1507"] = [[Visir imperial Zor'lok]]
        L["Encounter-1504"] = [[Señor de las espadas Ta'yak]]
        L["Encounter-1463"] = [[Garalon]]
        L["Encounter-1498"] = [[Señor del viento Mel'jarak]]
        L["Encounter-1499"] = [[Formador de ámbar Un'sok]]
        L["Encounter-1501"] = [[Gran emperatriz Shek'zeer]]
        L["Encounter-1409"] = [[Protectores de la Eternidad]]
        L["Encounter-1505"] = [[Tsulong]]
        L["Encounter-1506"] = [[Lei Shi]]
        L["Encounter-1431"] = [[Sha del miedo]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses mostrados tras 20H muertes"
        L["Encounter-51292"] = [[Morchok]]
        L["Encounter-51294"] = [[Señor de la guerra Zon'ozz]]
        L["Encounter-51295"] = [[Yor'sahj el Velador]]
        L["Encounter-51296"] = [[Hagara la Vinculatormentas]]
        L["Encounter-51297"] = [[Ultraxion]]
        L["Encounter-51298"] = [[Maestro de guerra Cuerno Negro]]
        L["Encounter-51291"] = [[Espinazo de Alamuerte]]
        L["Encounter-51299"] = [[Locura de Alamuerte]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Maestro de bestias]]
        L["Encounter-3188"] = [[Consejo renacido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses mostrados tras 20H muertes"
        L["Encounter-251118"] = [[Remendejo]]
        L["Encounter-251111"] = [[Grobbulus]]
        L["Encounter-251108"] = [[Gluth]]
        L["Encounter-251120"] = [[Thaddius]]
        L["Encounter-251117"] = [[Noth el Pesteador]]
        L["Encounter-251112"] = [[Heigan el Impuro]]
        L["Encounter-251115"] = [[Loatheb]]
        L["Encounter-251107"] = [[Anub'Rekhan]]
        L["Encounter-251110"] = [[Gran Viuda Faerlina]]
        L["Encounter-251116"] = [[Maexxna]]
        L["Encounter-251113"] = [[Instructor Razuvious]]
        L["Encounter-251109"] = [[Gothik el Cosechador]]
        L["Encounter-251121"] = [[Los Cuatro Jinetes]]
        L["Encounter-251119"] = [[Sapphiron]]
        L["Encounter-251114"] = [[Kel'Thuzad]]
    end
elseif locale == "frFR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Héroïque"
    L["DifficultyName-5"] = "Mythique"
    L["AllStars"] = "All Stars"
    L["Rank"] = "Rang"
    L["Kills"] = "kills"
    L["Unknown"] = [[Inconnu]]
    L["UnknownRealm"] = [[[%s] Le royaume '%s' (identifiant %d) n'est pas dans la base de données. Merci de contacter l'équipe de Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copier l'URL WarcraftLogs]]
    L["Subscriber"] = [[Abonné]]
    L["ShiftToExpand"] = [[<Maj> pour déplier]]
    L["SubAddonMissing"] = [[[%s] La base de données pour '%s' (%s) est manquante. Peut-être que vous vous êtes connecté au jeu pendant que l'addon était pleine mise à jour. Vérifiez l'application du bureau pour voir si la mise à jour est terminée, puis faites un '/reload' pour réessayer.]]
    L["DBLoadError"] = [[[%s] Impossible de charger la base de données de '%s'. Raison : %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Cliquez pour ouvrir les Paramètres]]
    L["ShowTooltipInCombat"] = [[Afficher l'Infobulle en Combat]]
    L["ShowTooltipInCombatDescription"] = [[Choisir si l'infobulle doit également être affichée en combat. Désactivé par défaut pour des raisons de performance.]]
    L["AllowShiftExpansionInCombat"] = [[Autoriser l'extension avec Shift en combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Choisir si les données étendues doivent également être affichées en combat. Active le paramètre ci-dessus.]]
    L["ShowRank"] = [[Afficher le rang]]
    L["ShowRankDescription"] = [[Active/Désactive l'ajout du rang à l'infobulle.]]
    L["ShowAsp"] = [[Montrer les All Stars]]
    L["ShowAspDescription"] = [[Active/Désactive l'ajout des points All Stars à l'infobulle.]]
    L["ShowShiftHint"] = [[Afficher l'astuce avec Shift]]
    L["ShowShiftHintDescription"] = [[Active/Désactive l'ajout de l'astuce pour étendre l'info en maintenant Shift.]]
    L["MenuIntegration"] = [[Étendre les options du menu]]
    L["MenuIntegrationDescription"] = [[Choisir si les menus doivent être étendus avec l'option de copier l'URL de profil du personnage.]]
    L["SettingsLookupUsage"] = [[Utilisation: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[Aucune donnée trouvée.]]
    L["SettingsLookupDataFor"] = [[%s pour %s - %s]]
    L["SettingsAvailableCommands"] = [[Commandes disponibles : ]]
    L["SettingsOpenSettingsLabel"] = [[ouvre les paramètres]]
    L["SettingsLookupLabel"] = [[rechercher un profil par nom  et royaume]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Les parses seront affichés après 20H ou 5M boss tués"
        L["Encounter-3129"] = [[Sentinelle du Plexus]]
        L["Encounter-3131"] = [[Rou’ethar]]
        L["Encounter-3130"] = [[Lieuse d’âme Naazindhri]]
        L["Encounter-3132"] = [[Tisseforge Araz]]
        L["Encounter-3122"] = [[Chasseurs d’âmes]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Roi-nexus Salhadaar]]
        L["Encounter-3135"] = [[Dimensius l’Omni-dévoreur]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 25H kills"
        L["Encounter-1507"] = [[Vizir impérial Zor’lok]]
        L["Encounter-1504"] = [[Seigneur des lames Ta’yak]]
        L["Encounter-1463"] = [[Garalon]]
        L["Encounter-1498"] = [[Seigneur du Vent Mel’jarak]]
        L["Encounter-1499"] = [[Sculpte-ambre Un’sok]]
        L["Encounter-1501"] = [[Grande impératrice Shek’zeer]]
        L["Encounter-1409"] = [[Protecteurs de l’Éternel]]
        L["Encounter-1505"] = [[Tsulong]]
        L["Encounter-1506"] = [[Lei Shi]]
        L["Encounter-1431"] = [[Sha de la peur]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-51292"] = [[Morchok]]
        L["Encounter-51294"] = [[Seigneur de guerre Zon’ozz]]
        L["Encounter-51295"] = [[Yor'sahj l’Insomniaque]]
        L["Encounter-51296"] = [[Hagara la Lieuse des tempêtes]]
        L["Encounter-51297"] = [[Ultraxion]]
        L["Encounter-51298"] = [[Maître de guerre Corne-Noire]]
        L["Encounter-51291"] = [[Échine d’Aile de mort]]
        L["Encounter-51299"] = [[Folie d’Aile de mort]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Maçon]]
        L["Encounter-3196"] = [[Belluaire]]
        L["Encounter-3188"] = [[Le conseil ressuscité]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-251118"] = [[Le Recousu]]
        L["Encounter-251111"] = [[Grobbulus]]
        L["Encounter-251108"] = [[Gluth]]
        L["Encounter-251120"] = [[Thaddius]]
        L["Encounter-251117"] = [[Noth le Porte-Peste]]
        L["Encounter-251112"] = [[Heigan l'Impur]]
        L["Encounter-251115"] = [[Horreb]]
        L["Encounter-251107"] = [[Anub'Rekhan]]
        L["Encounter-251110"] = [[Grande veuve Faerlina]]
        L["Encounter-251116"] = [[Maexxna]]
        L["Encounter-251113"] = [[Instructeur Razuvious]]
        L["Encounter-251109"] = [[Gothik le Moissonneur]]
        L["Encounter-251121"] = [[Les quatre cavaliers]]
        L["Encounter-251119"] = [[Saphiron]]
        L["Encounter-251114"] = [[Kel'Thuzad]]
    end
elseif locale == "itIT" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "H"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "LFR"
    L["DifficultyName-3"] = "Normale"
    L["DifficultyName-4"] = "Eroico"
    L["DifficultyName-5"] = "Mitico"
    L["AllStars"] = "Classificazione All-Stars"
    L["Rank"] = "Rango"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3129"] = [[Sentinella del Plesso]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Vincolatrice d'Anime Naazindhri]]
        L["Encounter-3132"] = [[Tessiforgia Araz]]
        L["Encounter-3122"] = [[I Cacciatori d'Anime]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Re del Nexus Salhadaar]]
        L["Encounter-3135"] = [[Dimensius il Divoratore]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 25H kills"
        L["Encounter-1507"] = [[Visir Imperiale Zor'lok]]
        L["Encounter-1504"] = [[Signore delle Lame Ta'yak]]
        L["Encounter-1463"] = [[Garalon]]
        L["Encounter-1498"] = [[Signore del Vento Mel'jarak]]
        L["Encounter-1499"] = [[Un'sok il Plasmatore d'Ambra]]
        L["Encounter-1501"] = [[Grande Imperatrice Shek'zeer]]
        L["Encounter-1409"] = [[Protettori dell'Eterno]]
        L["Encounter-1505"] = [[Tsulong]]
        L["Encounter-1506"] = [[Lei Shi]]
        L["Encounter-1431"] = [[Sha della Paura]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-51292"] = [[Morchok]]
        L["Encounter-51294"] = [[Zon'ozz il Signore della Guerra]]
        L["Encounter-51295"] = [[Yor'sahj il Senza Sonno]]
        L["Encounter-51296"] = [[Hagara la Tempestosa]]
        L["Encounter-51297"] = [[Ultraxion]]
        L["Encounter-51298"] = [[Maestro di Guerra Corno Nero]]
        L["Encounter-51291"] = [[Spina Dorsale di Alamorte]]
        L["Encounter-51299"] = [[Follia di Alamorte]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lillian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-251118"] = [[Pezzacarne]]
        L["Encounter-251111"] = [[Grobbulus]]
        L["Encounter-251108"] = [[Gluth]]
        L["Encounter-251120"] = [[Thaddius]]
        L["Encounter-251117"] = [[Noth l'Araldo della Piaga]]
        L["Encounter-251112"] = [[Heigan l'Impuro]]
        L["Encounter-251115"] = [[Loatheb]]
        L["Encounter-251107"] = [[Anub'rekhan]]
        L["Encounter-251110"] = [[Faerlina la Vedova Nera]]
        L["Encounter-251116"] = [[Maexxna]]
        L["Encounter-251113"] = [[Istruttore Razuvious]]
        L["Encounter-251109"] = [[Gothik il Falciatore]]
        L["Encounter-251121"] = [[Cavalieri dell'Apocalisse]]
        L["Encounter-251119"] = [[Zaffirion]]
        L["Encounter-251114"] = [[Kel'Thuzad]]
    end
elseif locale == "koKO" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "일반"
    L["Difficulty-4"] = "영웅"
    L["Difficulty-5"] = "신화"
    L["DifficultyName-1"] = "공격대 찾기"
    L["DifficultyName-3"] = "일반"
    L["DifficultyName-4"] = "영웅"
    L["DifficultyName-5"] = "신화"
    L["AllStars"] = "올스타"
    L["Rank"] = "등급"
    L["Kills"] = "Kills"
    L["Unknown"] = [[Unknown]]
    L["UnknownRealm"] = [[[%s] Realm '%s' (id %d) not in database. Please report to the Warcraft Logs team.]]
    L["CopyProfileURL"] = [[Copy WCL URL]]
    L["Subscriber"] = [[Subscriber]]
    L["ShiftToExpand"] = [[<Shift> to Expand]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] Could not load database for '%s'. Reason: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[Click to open Settings]]
    L["ShowTooltipInCombat"] = [[Show Tooltip in Combat]]
    L["ShowTooltipInCombatDescription"] = [[Whether to extend the tooltip in combat too. Disabled by default as performance measure.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Whether to render extended data in combat too. Enables the setting above.]]
    L["ShowRank"] = [[Show Rank]]
    L["ShowRankDescription"] = [[Toggles adding the rank to the tooltip.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Toggles appending the hint to expand the info when holding Shift.]]
    L["MenuIntegration"] = [[Extend Menu Options]]
    L["MenuIntegrationDescription"] = [[Whether to extend menus with an option to copy the characters profile URL.]]
    L["SettingsLookupUsage"] = [[Usage: /%s lookup <name> <realm>]]
    L["SettingsLookupNoData"] = [[No data found.]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[Available commands:]]
    L["SettingsOpenSettingsLabel"] = [[opens the settings]]
    L["SettingsLookupLabel"] = [[lookup a profile by name and realm]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Parses shown after 20H or 5M kills"
        L["Encounter-3129"] = [[흐름망 파수꾼]]
        L["Encounter-3131"] = [[룸이타르]]
        L["Encounter-3130"] = [[영혼술사 나진드리]]
        L["Encounter-3132"] = [[제련직공 아라즈]]
        L["Encounter-3122"] = [[영혼 사냥꾼]]
        L["Encounter-3133"] = [[프랙틸루스]]
        L["Encounter-3134"] = [[연합왕 살라다르]]
        L["Encounter-3135"] = [[만물의 포식자 디멘시우스]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 25H kills"
        L["Encounter-1507"] = [[황실 장로 조르로크]]
        L["Encounter-1504"] = [[칼날군주 타야크]]
        L["Encounter-1463"] = [[가랄론]]
        L["Encounter-1498"] = [[바람군주 멜자라크]]
        L["Encounter-1499"] = [[호박석구체자 운속]]
        L["Encounter-1501"] = [[위대한 여제 셰크지르]]
        L["Encounter-1409"] = [[영원의 수호병]]
        L["Encounter-1505"] = [[출롱]]
        L["Encounter-1506"] = [[레이 스]]
        L["Encounter-1431"] = [[공포의 샤]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-51292"] = [[모르초크]]
        L["Encounter-51294"] = [[장군 존오즈]]
        L["Encounter-51295"] = [[잠들지 않는 요르사지]]
        L["Encounter-51296"] = [[하가라]]
        L["Encounter-51297"] = [[울트락시온]]
        L["Encounter-51298"] = [[전투대장 블랙혼]]
        L["Encounter-51291"] = [[데스윙의 등]]
        L["Encounter-51299"] = [[데스윙의 광기]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[발나자르]]
        L["Encounter-3187"] = [[베아트릭스]]
        L["Encounter-3186"] = [[솔리스트라자]]
        L["Encounter-3197"] = [[석공]]
        L["Encounter-3196"] = [[야수조련사]]
        L["Encounter-3188"] = [[부활의 의회]]
        L["Encounter-3190"] = [[릴리안 보스]]
        L["Encounter-3189"] = [[칼도란]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-251118"] = [[패치워크]]
        L["Encounter-251111"] = [[그라불루스]]
        L["Encounter-251108"] = [[글루스]]
        L["Encounter-251120"] = [[타디우스]]
        L["Encounter-251117"] = [[역병술사 노스]]
        L["Encounter-251112"] = [[부정의 헤이건]]
        L["Encounter-251115"] = [[로데브]]
        L["Encounter-251107"] = [[아눕레칸]]
        L["Encounter-251110"] = [[귀부인 팰리나]]
        L["Encounter-251116"] = [[맥스나]]
        L["Encounter-251113"] = [[훈련교관 라주비어스]]
        L["Encounter-251109"] = [[영혼 착취자 고딕]]
        L["Encounter-251121"] = [[4인 기사단]]
        L["Encounter-251119"] = [[사피론]]
        L["Encounter-251114"] = [[켈투자드]]
    end
elseif locale == "ptBR" then
    L["Difficulty-1"] = "L"
    L["Difficulty-3"] = "N"
    L["Difficulty-4"] = "D"
    L["Difficulty-5"] = "M"
    L["DifficultyName-1"] = "PPR"
    L["DifficultyName-3"] = "Normal"
    L["DifficultyName-4"] = "Heroico"
    L["DifficultyName-5"] = "Mítico"
    L["AllStars"] = "Maiores Estrelas"
    L["Rank"] = "Ranque"
    L["Kills"] = "Abates"
    L["Unknown"] = [[Desconhecido]]
    L["UnknownRealm"] = [[[%s] Domínio '%s' (id %d) não está no banco de dados. Por favor, reporte-se à equipe do Warcraft Logs.]]
    L["CopyProfileURL"] = [[Copiar URL do WCL]]
    L["Subscriber"] = [[Assinante]]
    L["ShiftToExpand"] = [[<Shift> para expandir]]
    L["SubAddonMissing"] = [[[%s] Base de dados para '%s' (%s) está ausente. Pode ser que você tenha entrado no jogo enquanto o 'addon' estava no meio de uma atualização. Verifique o aplicativo no 'desktop' para ver se a atualização foi concluída, e então execute '/reload' para tentar novamente.]]
    L["DBLoadError"] = [[[%s] Não foi possível carregar a base de dados '%s'. Motivo: %s]]
    L["Main"] = [[Principal]]
    L["ClickToOpenSettings"] = [[Clique para abrir as Configurações]]
    L["ShowTooltipInCombat"] = [[Mostrar Dicas de Ferramenta durante o combate]]
    L["ShowTooltipInCombatDescription"] = [[Escolha de ampliar as dicas de ferramenta também durante o combate. Desativado por padrão como medida de desempenho.]]
    L["AllowShiftExpansionInCombat"] = [[Permitir expansão de Shift durante o combate]]
    L["AllowShiftExpansionInCombatDescription"] = [[Escolha de processar os dados ampliados também durante o combate. Habilita a opção acima.]]
    L["ShowRank"] = [[Mostrar Grau]]
    L["ShowRankDescription"] = [[Ativar/desativas mostrar o grau às dicas de ferramenta.]]
    L["ShowAsp"] = [[Mostrar All Stars]]
    L["ShowAspDescription"] = [[Ativar/desativar mostrar os Pontos All Star às dicas de ferramenta.]]
    L["ShowShiftHint"] = [[Mostrar Dica de Shift]]
    L["ShowShiftHintDescription"] = [[Ativar/desativar a dica para expandir informações enquanto pressionar a tecla Shift.]]
    L["MenuIntegration"] = [[Ampliar Opções de Menu]]
    L["MenuIntegrationDescription"] = [[Escolha de ampliar os menus com uma opção de copiar a URL do perfil de um personagem.]]
    L["SettingsLookupUsage"] = [[Uso: /%s procurar <name> <realm>]]
    L["SettingsLookupNoData"] = [[Nenhum dado encontrado.]]
    L["SettingsLookupDataFor"] = [[%s para %s - %s]]
    L["SettingsAvailableCommands"] = [[Comandos disponíveis:]]
    L["SettingsOpenSettingsLabel"] = [[abre as configurações]]
    L["SettingsLookupLabel"] = [[procurar um perfil por nome e reino]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Análises apresentadas após 20H ou 5M mortes"
        L["Encounter-3129"] = [[Sentinela do Plexo]]
        L["Encounter-3131"] = [[Fian'dhar]]
        L["Encounter-3130"] = [[Atalmas Naazindhri]]
        L["Encounter-3132"] = [[Tece-forja Araz]]
        L["Encounter-3122"] = [[Os Caça-almas]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Rei do Nexus Salhadaar]]
        L["Encounter-3135"] = [[Dimensius, que Tudo Devora]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-1507"] = [[Vizir Imperial Zor'lok]]
        L["Encounter-1504"] = [[Senhor das Lâminas Ta'yak]]
        L["Encounter-1463"] = [[Garalon]]
        L["Encounter-1498"] = [[Senhor do Vento Mel'jarak]]
        L["Encounter-1499"] = [[Molda-âmbar Un'sok]]
        L["Encounter-1501"] = [[Grã-imperatriz Shek'zeer]]
        L["Encounter-1409"] = [[Protetores do Infinito]]
        L["Encounter-1505"] = [[Tsulong]]
        L["Encounter-1506"] = [[Lei Shi]]
        L["Encounter-1431"] = [[Sha do Medo]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-51292"] = [[Morchok]]
        L["Encounter-51294"] = [[Senhor da Guerra Zon'ozz]]
        L["Encounter-51295"] = [[Yor'sahj, o Vígil]]
        L["Encounter-51296"] = [[Hagara, a Tempestigadora]]
        L["Encounter-51297"] = [[Ultraxion]]
        L["Encounter-51298"] = [[Mestre Guerreiro Chifre Negro]]
        L["Encounter-51291"] = [[Espinhaço do Asa da Morte]]
        L["Encounter-51299"] = [[Loucura do Asa da Morte]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Alvano]]
        L["Encounter-3196"] = [[Senhor das Feras]]
        L["Encounter-3188"] = [[Conselho Renascido]]
        L["Encounter-3190"] = [[Lilian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Análises apresentadas após: mortes por limiar "
        L["Encounter-251118"] = [[Retalhoso]]
        L["Encounter-251111"] = [[Grobbulus]]
        L["Encounter-251108"] = [[Gluth]]
        L["Encounter-251120"] = [[Thaddius]]
        L["Encounter-251117"] = [[Noth, o Pestífero]]
        L["Encounter-251112"] = [[Heigan, o Sujo]]
        L["Encounter-251115"] = [[Repugnaz]]
        L["Encounter-251107"] = [[Anub'Rekhan]]
        L["Encounter-251110"] = [[Grã-viúva Faerlina]]
        L["Encounter-251116"] = [[Maexxna]]
        L["Encounter-251113"] = [[Instrutor Razúvio]]
        L["Encounter-251109"] = [[Gothik, o Ceifador]]
        L["Encounter-251121"] = [[Os Quatro Cavaleiros]]
        L["Encounter-251119"] = [[Sapphiron]]
        L["Encounter-251114"] = [[Kel'Thuzad]]
    end
elseif locale == "ruRU" then
    L["Difficulty-1"] = "ПР"
    L["Difficulty-3"] = "Н"
    L["Difficulty-4"] = "Г"
    L["Difficulty-5"] = "Э"
    L["DifficultyName-1"] = "СПР"
    L["DifficultyName-3"] = "Обычный"
    L["DifficultyName-4"] = "Героический"
    L["DifficultyName-5"] = "Эпохальный"
    L["AllStars"] = "Все звезды"
    L["Rank"] = "Ранг"
    L["Kills"] = "Убийств"
    L["Unknown"] = [[Неизвестно]]
    L["UnknownRealm"] = [[[%s] Реалм '%s' (id %d) отсутствует в базе данных. Пожалуйста, сообщите об этом команде Warcraft Logs.]]
    L["CopyProfileURL"] = [[Скопировать WCL URL]]
    L["Subscriber"] = [[Подписчик]]
    L["ShiftToExpand"] = [[<Shift> чтобы расширить]]
    L["SubAddonMissing"] = [[[%s] База данных для '%s' (%s) отсутствует. Возможно, вы вошли в игру, когда аддон находился в процессе обновления. Проверьте в настольном приложении, завершилось ли обновление, а затем выполните команду '/reload', чтобы повторить попытку.]]
    L["DBLoadError"] = [[[%s] Не удалось загрузить базу данных для '%s'. Причина: %s]]
    L["Main"] = [[Главная]]
    L["ClickToOpenSettings"] = [[Нажмите, чтобы открыть Настройки]]
    L["ShowTooltipInCombat"] = [[Показывать тултип в бою]]
    L["ShowTooltipInCombatDescription"] = [[Нужно ли расширять всплывающую подсказку и в бою. По умолчанию отключено в качестве меры производительности.]]
    L["AllowShiftExpansionInCombat"] = [[Allow Shift Expansion in Combat]]
    L["AllowShiftExpansionInCombatDescription"] = [[Нужно ли отображать расширенные данные и в бою. Включает настройку выше.]]
    L["ShowRank"] = [[Показать ранг]]
    L["ShowRankDescription"] = [[Переключает добавление ранга во всплывающую подсказку.]]
    L["ShowAsp"] = [[Show All Stars]]
    L["ShowAspDescription"] = [[Toggles adding All Stars Points to the tooltip.]]
    L["ShowShiftHint"] = [[Show Shift Hint]]
    L["ShowShiftHintDescription"] = [[Переключает добавление подсказки для раскрытия информации при удержании Shift.]]
    L["MenuIntegration"] = [[Расширение опций меню]]
    L["MenuIntegrationDescription"] = [[Нужно ли расширять меню опцией копирования URL-адреса профиля персонажа.]]
    L["SettingsLookupUsage"] = [[Использование: /%s lookup <имя> <реалм>]]
    L["SettingsLookupNoData"] = [[Данные не найдены.]]
    L["SettingsLookupDataFor"] = [[%s для %s - %s]]
    L["SettingsAvailableCommands"] = [[Доступные команды:]]
    L["SettingsOpenSettingsLabel"] = [[открывает настройки]]
    L["SettingsLookupLabel"] = [[поиск профиля по имени и региону]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "Парсы показываются после 20Г или 5M убийств"
        L["Encounter-3129"] = [[Сплетенный страж]]
        L["Encounter-3131"] = [[Ткан'итар]]
        L["Encounter-3130"] = [[Стражница душ Наазиндри]]
        L["Encounter-3132"] = [[Ткач горна Араз]]
        L["Encounter-3122"] = [[Ловцы душ]]
        L["Encounter-3133"] = [[Разломий]]
        L["Encounter-3134"] = [[Соправитель Салхадаар]]
        L["Encounter-3135"] = [[Пространствус Всепоглощающий]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "Parses shown after 25H kills"
        L["Encounter-1507"] = [[Императорский визирь Зор'лок]]
        L["Encounter-1504"] = [[Повелитель клинков Та'як]]
        L["Encounter-1463"] = [[Гаралон]]
        L["Encounter-1498"] = [[Повелитель ветров Мел'джарак]]
        L["Encounter-1499"] = [[Ваятель янтаря Ун'сок]]
        L["Encounter-1501"] = [[Великая императрица Шек'зир]]
        L["Encounter-1409"] = [[Вечные защитники]]
        L["Encounter-1505"] = [[Цулон]]
        L["Encounter-1506"] = [[Лэй Ши]]
        L["Encounter-1431"] = [[Ша Страха]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-51292"] = [[Морхок]]
        L["Encounter-51294"] = [[Полководец Зон'озз]]
        L["Encounter-51295"] = [[Йор'садж Неспящий]]
        L["Encounter-51296"] = [[Хагара Владычица Штормов]]
        L["Encounter-51297"] = [[Ультраксион]]
        L["Encounter-51298"] = [[Воевода Черный Рог]]
        L["Encounter-51291"] = [[Хребет Смертокрыла]]
        L["Encounter-51299"] = [[Безумие Смертокрыла]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Балназзар]]
        L["Encounter-3187"] = [[Беатриса]]
        L["Encounter-3186"] = [[Солистраза]]
        L["Encounter-3197"] = [[Мейсон]]
        L["Encounter-3196"] = [[Повелитель зверей]]
        L["Encounter-3188"] = [[Возрожденный совет]]
        L["Encounter-3190"] = [[Лилиан Восс]]
        L["Encounter-3189"] = [[Калдоран]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "Parses shown after 20H kills"
        L["Encounter-251118"] = [[Лоскутик]]
        L["Encounter-251111"] = [[Гроббулус]]
        L["Encounter-251108"] = [[Глут]]
        L["Encounter-251120"] = [[Таддиус]]
        L["Encounter-251117"] = [[Нот Чумной]]
        L["Encounter-251112"] = [[Хейган Нечестивый]]
        L["Encounter-251115"] = [[Лотхиб]]
        L["Encounter-251107"] = [[Ануб'Рекан]]
        L["Encounter-251110"] = [[Великая вдова Фарлина]]
        L["Encounter-251116"] = [[Мексна]]
        L["Encounter-251113"] = [[Инструктор Разувий]]
        L["Encounter-251109"] = [[Готик Жнец]]
        L["Encounter-251121"] = [[Четыре всадника]]
        L["Encounter-251119"] = [[Сапфирон]]
        L["Encounter-251114"] = [[Кел'Тузад]]
    end
elseif locale == "zhCN" then
    L["Difficulty-1"] = "随机"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "史诗"
    L["DifficultyName-1"] = "团队查找器"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄级"
    L["DifficultyName-5"] = "史诗级"
    L["AllStars"] = "全明星分"
    L["Rank"] = "排名"
    L["Kills"] = "击杀"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 服务器 '%s' (id %d) 不在数据库中。请报告给WCL团队。]]
    L["CopyProfileURL"] = [[复制 WCL 链接]]
    L["Subscriber"] = [[WCL会员]]
    L["ShiftToExpand"] = [[按住 <Shift> 展开]]
    L["SubAddonMissing"] = [[[%s] '%s' (%s) 的数据库缺失。可能是因为您在插件更新过程中登录了游戏。请检查WCL客户端以确认更新是否已完成，然后运行 '/reload' 再次尝试。]]
    L["DBLoadError"] = [[[%s] 无法加载 '%s' 的数据库。原因：%s]]
    L["Main"] = [[大号]]
    L["ClickToOpenSettings"] = [[点击打开设置]]
    L["ShowTooltipInCombat"] = [[在战斗中显示插件]]
    L["ShowTooltipInCombatDescription"] = [[是否在战斗中也显示插件。默认禁用以提高性能。]]
    L["AllowShiftExpansionInCombat"] = [[允许在战斗中按 Shift 扩展]]
    L["AllowShiftExpansionInCombatDescription"] = [[是否在战斗中也渲染扩展数据。需要先启用上述设置]]
    L["ShowRank"] = [[显示排名]]
    L["ShowRankDescription"] = [[切换在工具提示中添加排名的选项。]]
    L["ShowAsp"] = [[显示全明星分]]
    L["ShowAspDescription"] = [[切换在工具提示中添加全明星积分的选项。]]
    L["ShowShiftHint"] = [[显示 Shift 提示]]
    L["ShowShiftHintDescription"] = [[切换在按住Shift键时附加提示以展开信息的选项。]]
    L["MenuIntegration"] = [[扩展菜单选项]]
    L["MenuIntegrationDescription"] = [[是否扩展菜单以添加复制角色信息链接的选项。]]
    L["SettingsLookupUsage"] = [[用法: /%s 查找 <名字> <服务器>]]
    L["SettingsLookupNoData"] = [[没有找到数据]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[可用命令：]]
    L["SettingsOpenSettingsLabel"] = [[打开设置]]
    L["SettingsLookupLabel"] = [[按角色名和服务器查找资料]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "分数在20次H或5次M击杀后显示"
        L["Encounter-3129"] = [[集能哨兵]]
        L["Encounter-3131"] = [[卢米萨尔]]
        L["Encounter-3130"] = [[缚魂者娜欣达利]]
        L["Encounter-3132"] = [[熔炉编织者阿拉兹]]
        L["Encounter-3122"] = [[狩魂猎手]]
        L["Encounter-3133"] = [[弗兰克提鲁斯]]
        L["Encounter-3134"] = [[节点之王萨哈达尔]]
        L["Encounter-3135"] = [[诸界吞噬者迪门修斯]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "分数在 25H 击杀后显示"
        L["Encounter-1507"] = [[皇家宰相佐尔洛克]]
        L["Encounter-1504"] = [[刀锋领主塔亚克]]
        L["Encounter-1463"] = [[加拉隆]]
        L["Encounter-1498"] = [[风领主梅尔加拉克]]
        L["Encounter-1499"] = [[琥珀塑形者昂舒克]]
        L["Encounter-1501"] = [[大女皇夏柯希尔]]
        L["Encounter-1409"] = [[无尽守护者]]
        L["Encounter-1505"] = [[烛龙]]
        L["Encounter-1506"] = [[雷施]]
        L["Encounter-1431"] = [[惧之煞]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "分数在 20H 击杀后显示"
        L["Encounter-51292"] = [[莫卓克]]
        L["Encounter-51294"] = [[督军佐诺兹]]
        L["Encounter-51295"] = [[不眠的约萨希]]
        L["Encounter-51296"] = [[缚风者哈格拉]]
        L["Encounter-51297"] = [[奥卓克希昂]]
        L["Encounter-51298"] = [[战争大师黑角]]
        L["Encounter-51291"] = [[死亡之翼的背脊]]
        L["Encounter-51299"] = [[疯狂的死亡之翼]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[巴纳扎尔]]
        L["Encounter-3187"] = [[碧阿崔克丝]]
        L["Encounter-3186"] = [[瑟莉斯塔萨]]
        L["Encounter-3197"] = [[梅森]]
        L["Encounter-3196"] = [[兽王]]
        L["Encounter-3188"] = [[复生议会]]
        L["Encounter-3190"] = [[莉莉安·沃斯]]
        L["Encounter-3189"] = [[凯尔多兰]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "分数在 20H 击杀后显示"
        L["Encounter-251118"] = [[帕奇维克]]
        L["Encounter-251111"] = [[格罗布鲁斯]]
        L["Encounter-251108"] = [[格拉斯]]
        L["Encounter-251120"] = [[塔迪乌斯]]
        L["Encounter-251117"] = [[药剂师诺斯]]
        L["Encounter-251112"] = [[肮脏的希尔盖]]
        L["Encounter-251115"] = [[洛欧塞布]]
        L["Encounter-251107"] = [[阿努布雷坎]]
        L["Encounter-251110"] = [[黑女巫法琳娜]]
        L["Encounter-251116"] = [[迈克斯纳]]
        L["Encounter-251113"] = [[教官拉苏维奥斯]]
        L["Encounter-251109"] = [[收割者戈提克]]
        L["Encounter-251121"] = [[天启四骑士]]
        L["Encounter-251119"] = [[萨菲隆]]
        L["Encounter-251114"] = [[克尔苏加德]]
    end
elseif locale == "zhTW" then
    L["Difficulty-1"] = "隨團"
    L["Difficulty-3"] = "普通"
    L["Difficulty-4"] = "英雄"
    L["Difficulty-5"] = "傳奇"
    L["DifficultyName-1"] = "隨機團隊"
    L["DifficultyName-3"] = "普通"
    L["DifficultyName-4"] = "英雄"
    L["DifficultyName-5"] = "傳奇"
    L["AllStars"] = "全明星"
    L["Rank"] = "階級"
    L["Kills"] = "Kills"
    L["Unknown"] = [[未知]]
    L["UnknownRealm"] = [[[%s] 伺服器『%s』(ID %d) 不存在於資料庫，請向戰鬥紀錄團隊回報]]
    L["CopyProfileURL"] = [[複製WCL網址]]
    L["Subscriber"] = [[訂閱者]]
    L["ShiftToExpand"] = [[按住 <Shift> 展開]]
    L["SubAddonMissing"] = [[[%s] Database for '%s' (%s) is missing. It may be that you logged in to the game while the addon was in the middle of an update. Check the desktop app to see if the update has finished, and then run '/reload' to try again.]]
    L["DBLoadError"] = [[[%s] 無法載入資料庫 '%s'。原因: %s]]
    L["Main"] = [[Main]]
    L["ClickToOpenSettings"] = [[點擊開啟設定]]
    L["ShowTooltipInCombat"] = [[戰鬥中顯示工具提示]]
    L["ShowTooltipInCombatDescription"] = [[是否在戰鬥中延伸工具提示。預設停用以提升效能。]]
    L["AllowShiftExpansionInCombat"] = [[允許戰鬥中使用Shift擴展]]
    L["AllowShiftExpansionInCombatDescription"] = [[是否在戰鬥中渲染延伸資料。啟用上方設定。]]
    L["ShowRank"] = [[顯示排名]]
    L["ShowRankDescription"] = [[切換在工具提示中顯示排名]]
    L["ShowAsp"] = [[顯示所有星數]]
    L["ShowAspDescription"] = [[切換在工具提示中顯示所有星數點數]]
    L["ShowShiftHint"] = [[顯示Shift提示]]
    L["ShowShiftHintDescription"] = [[切換按住Shift時附加提示擴展資訊]]
    L["MenuIntegration"] = [[延伸選單選項]]
    L["MenuIntegrationDescription"] = [[是否延伸選單以複製角色個人檔案URL選項]]
    L["SettingsLookupUsage"] = [[使用方式：/%s 查詢 <名稱> <伺服器>]]
    L["SettingsLookupNoData"] = [[找不到資料]]
    L["SettingsLookupDataFor"] = [[%s for %s - %s]]
    L["SettingsAvailableCommands"] = [[可用指令：]]
    L["SettingsOpenSettingsLabel"] = [[開啟設定]]
    L["SettingsLookupLabel"] = [[依據名稱與伺服器查詢角色個人檔案]]

    if Private.IsRetail then
        L["addon.parse-gate-description"] = "戰績解鎖條件：累積20小時或500萬擊殺"
        L["Encounter-3129"] = [[Plexus Sentinel]]
        L["Encounter-3131"] = [[Loom'ithar]]
        L["Encounter-3130"] = [[Soulbinder Naazindhri]]
        L["Encounter-3132"] = [[Forgeweaver Araz]]
        L["Encounter-3122"] = [[The Soul Hunters]]
        L["Encounter-3133"] = [[Fractillus]]
        L["Encounter-3134"] = [[Nexus-King Salhadaar]]
        L["Encounter-3135"] = [[Dimensius, the All-Devouring]]
    elseif Private.IsMists then
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-1507"] = [[Imperial Vizier Zor'lok]]
        L["Encounter-1504"] = [[Blade Lord Ta'yak]]
        L["Encounter-1463"] = [[Garalon]]
        L["Encounter-1498"] = [[Wind Lord Mel'jarak]]
        L["Encounter-1499"] = [[Amber-Shaper Un'sok]]
        L["Encounter-1501"] = [[Grand Empress Shek'zeer]]
        L["Encounter-1409"] = [[Protectors of the Endless]]
        L["Encounter-1505"] = [[Tsulong]]
        L["Encounter-1506"] = [[Lei Shi]]
        L["Encounter-1431"] = [[Sha of Fear]]
    elseif Private.IsCata then
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-51292"] = [[Morchok]]
        L["Encounter-51294"] = [[Warlord Zon'ozz]]
        L["Encounter-51295"] = [[Yor'sahj the Unsleeping]]
        L["Encounter-51296"] = [[Hagara the Stormbinder]]
        L["Encounter-51297"] = [[Ultraxion]]
        L["Encounter-51298"] = [[Warmaster Blackhorn]]
        L["Encounter-51291"] = [[Spine of Deathwing]]
        L["Encounter-51299"] = [[Madness of Deathwing]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.SeasonOfDiscovery then
        L["addon.parse-gate-description"] = ""
        L["Encounter-3185"] = [[Balnazzar]]
        L["Encounter-3187"] = [[Beatrix]]
        L["Encounter-3186"] = [[Solistrasza]]
        L["Encounter-3197"] = [[Mason]]
        L["Encounter-3196"] = [[Beastmaster]]
        L["Encounter-3188"] = [[Reborn Council]]
        L["Encounter-3190"] = [[Lillian Voss]]
        L["Encounter-3189"] = [[Caldoran]]
    elseif Private.IsClassicEra and C_Seasons.GetActiveSeason() == Enum.SeasonID.Fresh then
        L["addon.parse-gate-description"] = "擊殺數達 後顯示解析數據"
        L["Encounter-251118"] = [[Patchwerk]]
        L["Encounter-251111"] = [[Grobbulus]]
        L["Encounter-251108"] = [[Gluth]]
        L["Encounter-251120"] = [[Thaddius]]
        L["Encounter-251117"] = [[Noth the Plaguebringer]]
        L["Encounter-251112"] = [[Heigan the Unclean]]
        L["Encounter-251115"] = [[Loatheb]]
        L["Encounter-251107"] = [[Anub'Rekhan]]
        L["Encounter-251110"] = [[Grand Widow Faerlina]]
        L["Encounter-251116"] = [[Maexxna]]
        L["Encounter-251113"] = [[Instructor Razuvious]]
        L["Encounter-251109"] = [[Gothik the Harvester]]
        L["Encounter-251121"] = [[The Four Horsemen]]
        L["Encounter-251119"] = [[Sapphiron]]
        L["Encounter-251114"] = [[Kel'Thuzad]]
    end
end
