-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Argaloth", {
	[88942] = "red",
	[88954] = {"green","yellow"},
	[88972] = {"cyan","orange"},
	[89000] = "blue",
})

BigWigs:AddSounds("Argaloth", {
	[88942] = {"alarm","warning"},
	[88954] = "alert",
	[88972] = {"info","long"},
	[89000] = "underyou",
})

BigWigs:AddColors("Occu'thar", {
	[96884] = "yellow",
	[96913] = {"blue","red"},
	[96920] = "orange",
})

BigWigs:AddSounds("Occu'thar", {
	[96920] = "alert",
})

BigWigs:AddColors("Alizabal", {
	[104936] = {"blue","yellow"},
	[105067] = {"blue","red"},
	[105784] = "orange",
})

BigWigs:AddSounds("Alizabal", {
	[105784] = "info",
})
