----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "itIT" then
    return
end

local L = BtWQuests.L
L["AFFLICTION_ULTHALESH_THE_DEADWIND_HARVESTER"] = "Afflizione: Ulthalesh, Mietitrice di Ventomorto"
L["ARCANE_ALUNETH"] = "Arcano: Aluneth"
L["ARMS_STROMKAR_THE_WARBREAKER"] = "Armi: Strom'kar, la Spezzaguerra"
L["ASSASSINATION_THE_KINGSLAYERS"] = "Assassinio: Lame Sterminatrici di Re"
L["BALANCE_SCYTHE_OF_ELUNE"] = "Equilibrio: Falce di Elune"
L["BEAST_MASTERY_TITANSTRIKE"] = "Affinità Animale: Titanassalto"
L["BLOOD_MAW_OF_THE_DAMNED"] = "Sangue: Morso del Dannato"
L["BREWMASTER_FU_ZAN_THE_WANDERERS_COMPANION"] = "Mastro Birraio: Fu Zan, Compagno del Viandante"
L["BTWQUESTS_AID_OF_THE_ILLIDARI"] = "Aiuto degli Illidari"
L["BTWQUESTS_ARTIFACT"] = "Artefatto"
L["BTWQUESTS_FATE_OF_THE_TIDESKORN"] = "Il destino degli Abiskorn"
L["BTWQUESTS_RUMBLINGS_NEAR_FELTOTEM"] = "Tumulti vicino a Totem Vile"
L["BTWQUESTS_THE_BRADENSBROOK_INVESTIGATION"] = "Le indagini a Rivofosco"
L["BTWQUESTS_THE_FOLLY_OF_LEVIA_LAURENCE"] = "La follia di Levia Laurence"
L["BTWQUESTS_THE_THIEVING_APPRENTICE"] = "L'apprendista ladro"
L["BTWQUESTS_THE_TWISTED_TWINS"] = "Il gemello corrotto"
L["DEMONOLOGY_SKULL_OF_THE_MANARI"] = "Demonologia: Teschio dei Man'ari"
L["DESTRUCTION_SCEPTER_OF_SARGERAS"] = "Distruzione: Scettro di Sargeras"
L["DISCIPLINE_LIGHTS_WRATH"] = "Disciplina: Ira della Luce"
L["ELEMENTAL_THE_FIST_OF_RADEN"] = "Elementale: Pugno di Ra-Den"
L["ENHANCEMENT_DOOMHAMMER"] = "Potenziamento: Martelfato"
L["FERAL_FANGS_OF_ASHAMANE"] = "Aggressore Ferino: Zanne di Grigiomanto"
L["FIRE_FELOMELORN"] = "Fuoco: Felo'melorn"
L["FROST_BLADES_OF_THE_FALLEN_PRINCE"] = "Gelo: Lame del Principe Caduto"
L["FROST_EBONCHILL"] = "Gelo: Gelonero"
L["FURY_WARSWORDS_OF_THE_VALARJAR"] = "Furia: Spadoni dei Valarjar"
L["GUARDIAN_CLAWS_OF_URSOC"] = "Guardiano Ferino: Artigli di Ursoc"
L["HAVOC_TWINBLADES_OF_THE_DECEIVER"] = "Rovina: Lame Gemelle dell'Ingannatore"
L["HIGHMOUNTAIN TAUREN"] = "Tauren di Alto Monte"
L["HOLY_THE_SILVER_HAND"] = "Sacro: Mano d'Argento"
L["HOLY_TUURE_BEACON_OF_THE_NAARU"] = "Sacro: T'uure, Faro dei Naaru"
L["LIGHTFORGED_DRAENEI"] = "Draenei Forgialuce"
L["LOST_MAIL"] = "Posta Perduta"
L["MARKSMANSHIP_THASDORAH_LEGACY_OF_THE_WINDRUNNERS"] = "Precisione di Tiro: Thas'dorah, Eredità dei Ventolesto"
L["MISTWEAVER_SHEILUN_STAFF_OF_THE_MISTS"] = "Misticismo: Sheilun, Bastone delle Nebbie"
L["NIGHTBORNE"] = "Nobile Oscuro"
L["OUTLAW_THE_DREADBLADES"] = "Fuorilegge: Lame dell'Oscurità"
L["PROTECTION_SCALE_OF_THE_EARTH_WARDER"] = "Protezione: Scaglia del Custode della Terra"
L["PROTECTION_TRUTHGUARD"] = "Protezione: Scudo della Verità"
L["RESTORATION_GHANIR_THE_MOTHER_TREE"] = "Rigenerazione: G'hanir, l'Albero Madre"
L["RESTORATION_SHARASDAL_SCEPTER_OF_TIDES"] = "Rigenerazione: Sharas'dal, Scettro delle Maree"
L["RETRIBUTION_ASHBRINGER"] = "Castigo: Brandicenere"
L["SHADOW_XALATATH_BLADE_OF_THE_BLACK_EMPIRE"] = "Ombra: Xal'atath, Lama dell'Impero Nero"
L["SUBTLETY_FANGS_OF_THE_DEVOURER"] = "Scaltrezza: Zanne del Divoratore"
L["SURVIVAL_TALONCLAW"] = "Sopravvivenza: Grinfiartiglio"
L["UNHOLY_APOCALYPSE"] = "Empietà: Apocalisse"
L["VENGEANCE_ALDRACHI_WARBLADES"] = "Vendetta: Lame da Guerra degli Aldrachi"
L["VOID_ELF"] = "Elfo del Vuoto"
L["WINDWALKER_FISTS_OF_THE_HEAVENS"] = "Impeto: Pugni del Cielo"
