-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Razorgore the Untamed", {
	[14515] = {"blue","red"},
	[23023] = {"blue","orange"},
	[366909] = "blue",
	[367740] = "blue",
	[367873] = "blue",
	["adds"] = "cyan",
	["eggs"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Razorgore the Untamed", {
	[14515] = "alert",
	[23023] = "info",
	[366909] = "underyou",
	[367740] = "alarm",
	[367873] = "underyou",
	["adds"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Vaelastrasz the Corrupt", {
	[18173] = {"blue","yellow"},
	[23620] = {"blue","purple"},
})

BigWigs:AddSounds("Vaelastrasz the Corrupt", {
	[18173] = "warning",
	[23620] = {"long","warning"},
})

BigWigs:AddColors("Broodlord Lashlayer", {
	[18670] = {"blue","yellow"},
	[23331] = "orange",
	[24573] = {"blue","purple"},
	[367369] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Broodlord Lashlayer", {
	[18670] = "alert",
	[23331] = "info",
	[24573] = "alarm",
	[367369] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Firemaw", {
	[22539] = "red",
	[23339] = "yellow",
	[23341] = "blue",
	[366305] = "blue",
})

BigWigs:AddSounds("Firemaw", {
	[22539] = "long",
	[23339] = "info",
	[23341] = "warning",
	[366305] = "warning",
})

BigWigs:AddColors("Ebonroc", {
	[22539] = "red",
	[23339] = "yellow",
	[23340] = {"blue","purple"},
	[368515] = "blue",
})

BigWigs:AddSounds("Ebonroc", {
	[22539] = "long",
	[23339] = "info",
	[23340] = "alarm",
	[368515] = "alert",
})

BigWigs:AddColors("Flamegor", {
	[22539] = "red",
	[23339] = "yellow",
	[23342] = {"green","orange"},
	[368521] = "blue",
	[467732] = "blue",
	[467764] = "blue",
})

BigWigs:AddSounds("Flamegor", {
	[22539] = "long",
	[23339] = "info",
	[23342] = "alarm",
	[368521] = "alert",
	[467732] = "warning",
	[467764] = "warning",
})

BigWigs:AddColors("Chromaggus", {
	[23128] = {"green","orange"},
	[23170] = "blue",
	[23174] = "red",
	[23537] = "red",
	[468195] = "cyan",
	["breath"] = "yellow",
	["vulnerability"] = {"green","red"},
})

BigWigs:AddSounds("Chromaggus", {
	[23128] = "alarm",
	[23174] = "warning",
	[468195] = "long",
	["breath"] = "long",
	["vulnerability"] = {"info","warning"},
})

BigWigs:AddColors("Nefarian Classic", {
	[22539] = "yellow",
	[22667] = {"blue","yellow"},
	[22686] = "red",
	[22687] = {"blue","green","yellow"},
	["add"] = "green",
	["classcall"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nefarian Classic", {
	[22539] = "alarm",
	[22667] = "warning",
	[22686] = "alert",
	[22687] = "warning",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Blackwing Lair Trash", {
	[19717] = "blue",
	[22291] = {"blue","orange"},
	[369330] = "blue",
	[466357] = {"blue","orange"},
	[466435] = {"blue","orange"},
	["target_vulnerability"] = {"red","yellow"},
})

BigWigs:AddSounds("Blackwing Lair Trash", {
	[19717] = "underyou",
	[22291] = "warning",
	[369330] = "underyou",
	[466357] = "warning",
	[466435] = "warning",
})
