-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Halion", {
	[74525] = "orange",
	[74562] = {"blue","yellow"},
	[74630] = "blue",
	[74648] = {"blue","red"},
	[74769] = "red",
	[74792] = {"blue","yellow"},
	[74802] = "blue",
	[74806] = "orange",
	[74826] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Halion", {
	[74562] = "warning",
	[74630] = "underyou",
	[74648] = {"long","underyou"},
	[74769] = "alert",
	[74792] = "warning",
	[74802] = "underyou",
	[74826] = "warning",
	["stages"] = "info",
})

BigWigs:AddColors("The Ruby Sanctum Trash", {
	[40504] = "yellow",
	[74367] = {"blue","purple"},
	[74384] = "yellow",
	[74403] = "red",
	[74453] = {"blue","yellow"},
	[74502] = {"blue","orange"},
	[74509] = "orange",
	[75125] = "red",
	[78722] = {"green","orange"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("The Ruby Sanctum Trash", {
	[40504] = "alert",
	[74367] = "alarm",
	[74384] = "alert",
	[74403] = "info",
	[74453] = "warning",
	[74502] = "warning",
	[74509] = "long",
	[75125] = "info",
	[78722] = "alarm",
	["adds"] = "long",
})
