-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Morchok", {
	[103846] = "green",
	[103851] = "blue",
	[109017] = "green",
	["crush"] = {"blue","orange"},
	["crystal_add"] = "orange",
	["crystal_boss"] = "orange",
	["stomp_add"] = "red",
	["stomp_boss"] = "red",
})

BigWigs:AddSounds("Morchok", {
	[103851] = "long",
	["crush"] = "info",
	["crystal_add"] = "alarm",
	["crystal_boss"] = "alarm",
})

BigWigs:AddColors("Warlord Zon'ozz", {
	[103434] = {"blue","yellow"},
	["ball"] = "orange",
	["bounce"] = "red",
	["darkness"] = "red",
	["drain"] = "orange",
})

BigWigs:AddSounds("Warlord Zon'ozz", {
	[103434] = "alert",
	["ball"] = "alarm",
	["darkness"] = "info",
})

BigWigs:AddColors("Yor'sahj the Unsleeping", {
	[-4321] = "blue",
	["blobs"] = "orange",
	["bolt"] = {"blue","orange"},
})

BigWigs:AddSounds("Yor'sahj the Unsleeping", {
	[-4321] = "alert",
	["blobs"] = "alarm",
	["bolt"] = "info",
})

BigWigs:AddColors("Hagara the Stormbinder", {
	[-4159] = "orange",
	[104448] = {"blue","red","yellow"},
	[105256] = "yellow",
	[105316] = {"blue","orange"},
	[105409] = "yellow",
	[108934] = "yellow",
	[109325] = "blue",
})

BigWigs:AddSounds("Hagara the Stormbinder", {
	[105316] = "info",
	[109325] = "long",
})

BigWigs:AddColors("Ultraxion", {
	[105925] = {"blue","yellow"},
	[106371] = "red",
	["crystal"] = "green",
	["lighttank"] = {"blue","yellow"},
})

BigWigs:AddSounds("Ultraxion", {
	[105925] = "alarm",
	[106371] = "alert",
	["crystal"] = "info",
	["lighttank"] = "alarm",
})

BigWigs:AddColors("Warmaster Blackhorn", {
	[107588] = "orange",
	[108044] = "green",
	[108046] = {"blue","yellow"},
	[108076] = "blue",
	["sapper"] = "red",
	["sunder"] = {"blue","orange"},
	["warmup"] = "green",
})

BigWigs:AddSounds("Warmaster Blackhorn", {
	[107588] = "alarm",
	[108044] = "alert",
	[108046] = "alarm",
	[108076] = "long",
	["sapper"] = "info",
	["sunder"] = "info",
})

BigWigs:AddColors("Spine of Deathwing", {
	[105248] = {"orange","red"},
	[105490] = {"blue","orange"},
	[105845] = "red",
	[105848] = "red",
	["residue"] = "yellow",
	["roll"] = {"blue","green","yellow"},
})

BigWigs:AddSounds("Spine of Deathwing", {
	[105845] = "info",
	["roll"] = {"alert","long"},
})

BigWigs:AddColors("Madness of Deathwing", {
	[-4351] = "green",
	[-4347] = {"blue","orange"},
	[105651] = "red",
	[106523] = "yellow",
	[106794] = "red",
	["bigtentacle"] = "orange",
	["fragment"] = "orange",
	["hemorrhage"] = "orange",
	["impale"] = "orange",
	["last_phase"] = "yellow",
	["smalltentacles"] = "orange",
	["terror"] = "red",
})

BigWigs:AddSounds("Madness of Deathwing", {
	[-4351] = "info",
	[105651] = "long",
	[106794] = "long",
	["bigtentacle"] = "alert",
	["fragment"] = "alarm",
	["hemorrhage"] = "alarm",
	["impale"] = "alarm",
	["smalltentacles"] = "alarm",
})
