-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Jin'rokh the Breaker", {
	[-7741] = {"blue","green"},
	[137162] = "yellow",
	[137175] = {"blue","red"},
	[137313] = "red",
	[138006] = "blue",
	[138349] = {"blue","orange"},
	[138732] = {"green","red"},
	[139467] = "blue",
})

BigWigs:AddSounds("Jin'rokh the Breaker", {
	[-7741] = "alarm",
	[137175] = "warning",
	[137313] = "long",
	[138006] = "info",
	[138349] = "alert",
	[138732] = {"info","long"},
	[139467] = "info",
})

BigWigs:AddColors("Horridon", {
	[-7868] = "blue",
	[-7125] = {"blue","red"},
	[-7120] = {"blue","orange"},
	[-7119] = "red",
	[-7109] = "red",
	[-7092] = "green",
	[-7090] = {"green","red"},
	[-7086] = "cyan",
	[-7080] = {"blue","yellow"},
	[-7078] = {"blue","orange"},
	[136490] = "blue",
	[136573] = "blue",
	[136646] = "blue",
	[136723] = "blue",
	[136741] = "orange",
	[136821] = "red",
	[137240] = "green",
	[137458] = "orange",
	["adds"] = "cyan",
	["chain_lightning"] = "blue",
	["fireball"] = "blue",
	["venom_bolt_volley"] = {"blue","red"},
})

BigWigs:AddSounds("Horridon", {
	[-7868] = "info",
	[-7125] = "alarm",
	[-7119] = "alarm",
	[-7109] = "alarm",
	[-7090] = "long",
	[-7080] = "warning",
	[136490] = "info",
	[136573] = "info",
	[136646] = "info",
	[136723] = "info",
	[136741] = "long",
	[136821] = "long",
	["adds"] = "info",
	["chain_lightning"] = "alert",
	["fireball"] = "alert",
	["venom_bolt_volley"] = {"alarm","alert"},
})

BigWigs:AddColors("Council of Elders", {
	[-7062] = "blue",
	[-7054] = {"blue","orange","red","yellow"},
	[136442] = {"cyan","orange","red","yellow"},
	[136857] = {"blue","yellow"},
	[136878] = "yellow",
	[136894] = "orange",
	[136990] = {"blue","green"},
	[136992] = {"blue","orange"},
	[137085] = "blue",
	[137122] = "blue",
	[137203] = "yellow",
	[137350] = {"blue","orange"},
	[137650] = "blue",
	["priestess_adds"] = "red",
})

BigWigs:AddSounds("Council of Elders", {
	[-7062] = "info",
	[-7054] = {"info","warning"},
	[136442] = {"alert","long"},
	[136857] = "info",
	[136894] = "alert",
	[136990] = "info",
	[136992] = "alert",
	[137085] = "info",
	[137122] = "info",
	[137350] = "alert",
	[137650] = "info",
	["priestess_adds"] = "alarm",
})

BigWigs:AddColors("Tortos", {
	[-7134] = "green",
	[133939] = "red",
	[134920] = "red",
	[135251] = "yellow",
	[136010] = "red",
	[136294] = "orange",
	[137633] = "blue",
	["bats"] = "orange",
	["kick"] = "yellow",
})

BigWigs:AddSounds("Tortos", {
	[-7134] = "info",
	[133939] = "long",
	[134920] = "alert",
	[135251] = "warning",
	[136010] = "alarm",
	[137633] = {"alarm","info"},
	["bats"] = "warning",
})

BigWigs:AddColors("Megaera", {
	[139458] = {"green","red","yellow"},
	[139822] = {"blue","red"},
	[139843] = {"blue","orange"},
	[139866] = {"blue","orange"},
	[139909] = "blue",
	[140138] = "orange",
	[140179] = {"blue","orange"},
	["breaths"] = {"blue","yellow"},
})

BigWigs:AddSounds("Megaera", {
	[139458] = "long",
	[139822] = {"alert","info"},
	[139843] = "warning",
	[139866] = "info",
	[139909] = "info",
	[140138] = "alarm",
	["breaths"] = "info",
})

BigWigs:AddColors("Ji-Kun", {
	[-7360] = "blue",
	[134366] = {"blue","orange"},
	[134370] = "red",
	[134380] = "red",
	[137528] = "green",
	[138923] = "yellow",
	[140092] = {"blue","yellow"},
	[140741] = "green",
	["nest"] = {"orange","yellow"},
})

BigWigs:AddSounds("Ji-Kun", {
	[-7360] = "info",
	[134366] = "info",
	[134370] = "long",
	[134380] = "warning",
	[137528] = "info",
	["nest"] = "alert",
})

BigWigs:AddColors("Durumu the Forgotten", {
	[-6905] = {"blue","yellow"},
	[-6891] = {"blue","cyan"},
	[-6889] = "orange",
	[-6882] = "yellow",
	[133597] = "blue",
	[133767] = {"blue","yellow"},
	[133768] = {"blue","orange"},
	[133798] = {"blue","green","red"},
	[134626] = "orange",
	[140502] = "blue",
	["adds"] = {"green","orange","yellow"},
	["initial_life_drain"] = {"blue","orange"},
})

BigWigs:AddSounds("Durumu the Forgotten", {
	[-6905] = "long",
	[-6891] = "warning",
	[133597] = "info",
	[133767] = "info",
	[133768] = "alarm",
	[133798] = "alert",
	[134626] = "alarm",
	[140502] = "info",
	["adds"] = {"info","warning"},
	["initial_life_drain"] = "long",
})

BigWigs:AddColors("Primordius", {
	[-7830] = "blue",
	[-6969] = "yellow",
	[-6960] = "blue",
	[136037] = "yellow",
	[136050] = {"blue","yellow"},
	[136216] = "orange",
	[136218] = {"green","red"},
	[136228] = {"blue","green","orange","red"},
	[136245] = "yellow",
	[136246] = "yellow",
})

BigWigs:AddSounds("Primordius", {
	[-7830] = "info",
	[-6960] = "info",
	[136050] = "warning",
	[136218] = {"alert","long"},
	[136228] = {"alarm","alert","long"},
})

BigWigs:AddColors("Dark Animus", {
	[-7770] = {"blue","orange"},
	[136954] = "red",
	[138485] = {"blue","green","orange"},
	[138609] = {"blue","red"},
	[138644] = "cyan",
	[138691] = {"blue","orange"},
	[138729] = "red",
	[138763] = {"blue","yellow"},
	[138780] = "yellow",
	["matterswap"] = "blue",
})

BigWigs:AddSounds("Dark Animus", {
	[-7770] = "info",
	[136954] = "alert",
	[138485] = {"alarm","info"},
	[138609] = {"alarm","info"},
	[138644] = {"info","warning"},
	[138691] = "alarm",
	[138729] = "long",
	[138763] = "long",
	["matterswap"] = "info",
})

BigWigs:AddColors("Iron Qon", {
	[-6917] = "orange",
	[-6914] = "yellow",
	[-6877] = {"green","yellow"},
	[-6871] = "red",
	[77333] = "yellow",
	[134691] = {"blue","green"},
	[134926] = {"blue","orange"},
	[136192] = {"blue","orange"},
	[136193] = {"blue","green"},
	[136520] = "blue",
	[137221] = "red",
	[137668] = "blue",
	[137669] = "blue",
	[139180] = "yellow",
	["molten_energy"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Iron Qon", {
	[-6917] = "alarm",
	[-6871] = "warning",
	[134691] = "warning",
	[134926] = "alarm",
	[136193] = "alert",
	[136520] = "info",
	[137668] = "info",
	[137669] = "info",
	["molten_energy"] = "long",
})

BigWigs:AddColors("Twin Consorts", {
	[-7649] = "green",
	[-7643] = "yellow",
	[-7638] = "blue",
	[-7634] = {"blue","yellow"},
	[-7631] = "orange",
	[137408] = {"blue","orange"},
	[137440] = "blue",
	[137491] = {"green","red"},
	[137531] = "orange",
	[138300] = "green",
	[138306] = "green",
	[138318] = "green",
	[138855] = "green",
	["stages"] = "green",
})

BigWigs:AddSounds("Twin Consorts", {
	[-7643] = "warning",
	[-7638] = "info",
	[-7634] = "info",
	[-7631] = "alarm",
	[137408] = "info",
	[137440] = "info",
	[137491] = "alert",
	[137531] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Lei Shen", {
	[134912] = "blue",
	[135095] = "yellow",
	[135150] = {"blue","yellow"},
	[135695] = {"blue","green"},
	[135991] = {"blue","red"},
	[136295] = {"blue","green","orange"},
	[136366] = "red",
	[136478] = "red",
	[136543] = "yellow",
	[136850] = {"blue","orange","red"},
	[136889] = "red",
	[136914] = {"blue","red"},
	[139011] = {"blue","orange"},
	["stages"] = {"cyan","green","yellow"},
})

BigWigs:AddSounds("Lei Shen", {
	[134912] = "warning",
	[135095] = "alert",
	[135150] = "info",
	[135695] = "info",
	[135991] = "warning",
	[136295] = "alarm",
	[136366] = "long",
	[136478] = "warning",
	[136850] = {"alert","info","warning"},
	[136889] = "long",
	[136914] = "warning",
	[139011] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Ra-den", {
	[138288] = {"blue","yellow"},
	[138297] = "blue",
	[138333] = "yellow",
	[138334] = {"blue","cyan"},
	[138339] = "yellow",
	[138372] = "blue",
	["balls"] = "orange",
	["corruptedballs"] = "red",
	["stages"] = "cyan",
	["unstablevitajumptarget"] = "blue",
	["worm"] = "orange",
})

BigWigs:AddSounds("Ra-den", {
	[138297] = "info",
	[138372] = "info",
	["balls"] = "warning",
	["corruptedballs"] = "alarm",
	["stages"] = "info",
	["unstablevitajumptarget"] = {"info","long"},
})

BigWigs:AddColors("Throne of Thunder Trash", {
	[139322] = {"blue","orange"},
	[139899] = "orange",
	[139900] = {"blue","orange"},
	[140296] = "yellow",
	[140673] = "yellow",
})

BigWigs:AddSounds("Throne of Thunder Trash", {
	[139322] = "alert",
	[139899] = "long",
	[139900] = "alert",
	[140296] = "info",
	[140673] = "long",
})
