-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Omnotron Defense System", {
	[78740] = {"blue","cyan"},
	[79023] = "red",
	[79501] = {"blue","yellow"},
	[79624] = "orange",
	[79710] = "red",
	[79735] = "orange",
	[79888] = {"blue","yellow"},
	[80053] = "red",
	[80094] = "blue",
	[80157] = "blue",
	[80161] = "blue",
	[91849] = "orange",
	[91879] = {"blue","orange"},
	[92023] = {"blue","orange"},
	[92048] = {"blue","orange"},
	[92053] = "blue",
})

BigWigs:AddSounds("Omnotron Defense System", {
	[78740] = "long",
	[79023] = "alert",
	[79501] = "warning",
	[79624] = "info",
	[79710] = "alert",
	[79735] = "info",
	[79888] = "warning",
	[80053] = "info",
	[80094] = "alarm",
	[80161] = "underyou",
	[91879] = {"underyou","warning"},
	[92048] = "warning",
	[92053] = "warning",
})

BigWigs:AddColors("Magmaw", {
	[77690] = "yellow",
	[78006] = "orange",
	[78199] = {"blue","purple"},
	[78403] = {"blue","purple"},
	[78941] = "blue",
	[79011] = "green",
	[88253] = "red",
	[89773] = {"blue","purple"},
	[92134] = "blue",
	[92177] = "red",
	["adds"] = "cyan",
	["slump"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Magmaw", {
	[78006] = "alert",
	[78941] = "warning",
	[79011] = "long",
	[88253] = "info",
	[89773] = "info",
	[92134] = "underyou",
	[92177] = "alarm",
	["adds"] = "info",
})

BigWigs:AddColors("Atramedes", {
	[77611] = "cyan",
	[77612] = "orange",
	[77840] = "yellow",
	[78023] = "blue",
	[78075] = {"blue","red"},
	[92685] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Atramedes", {
	[77611] = "info",
	[77612] = "alert",
	[77840] = "warning",
	[78023] = "underyou",
	[78075] = "warning",
	[92685] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Chimaeron", {
	[82848] = "yellow",
	[82881] = {"blue","purple"},
	[88826] = {"green","purple"},
	[88853] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Chimaeron", {
	[82848] = "info",
	[88826] = "alert",
	[88853] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Maloriak", {
	[77569] = {"cyan","green"},
	[77679] = "purple",
	[77699] = {"blue","yellow"},
	[77760] = {"blue","orange"},
	[77786] = {"blue","red"},
	[77896] = "red",
	[77912] = "red",
	[77987] = "purple",
	[78124] = "blue",
	[78194] = "orange",
	[78223] = "yellow",
	[78225] = "red",
	[78895] = "cyan",
	[78896] = "cyan",
	[92716] = "cyan",
	[92754] = {"green","purple"},
	[92917] = "cyan",
	[92930] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Maloriak", {
	[77569] = "info",
	[77679] = "alarm",
	[77699] = "warning",
	[77760] = "alarm",
	[77786] = "warning",
	[77896] = "alert",
	[77912] = "info",
	[78124] = "underyou",
	[78225] = "alarm",
	[92754] = "info",
	[92930] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("Nefarian", {
	[77826] = "orange",
	[77939] = "yellow",
	[78620] = "purple",
	[78999] = "red",
	[79318] = {"blue","yellow"},
	[79339] = {"blue","orange"},
	[80734] = "orange",
	[81007] = "blue",
	[81031] = "red",
	[81272] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nefarian", {
	[77826] = "info",
	[79318] = "warning",
	[79339] = "warning",
	[80734] = "alert",
	[81007] = "underyou",
	[81031] = "alarm",
	[81272] = "alert",
	["stages"] = "long",
})
