-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Sha of Anger", {
	[119488] = "yellow",
	[119610] = "blue",
	[119622] = "blue",
	[119626] = {"blue","red"},
})

BigWigs:AddSounds("Sha of Anger", {
	[119610] = "underyou",
	[119622] = "warning",
})

BigWigs:AddColors("Salyis's Warband", {
	[121600] = "orange",
	[121787] = "red",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Salyis's Warband", {
	[121600] = "long",
	[121787] = "alarm",
	["adds"] = "info",
})

BigWigs:AddColors("Nalak", {
	[136338] = "red",
	[136339] = "blue",
	[136340] = {"blue","yellow"},
})

BigWigs:AddSounds("Nalak", {
	[136338] = "alarm",
	[136339] = "alert",
	[136340] = {"alert","info"},
})

BigWigs:AddColors("Oondasta", {
	[137457] = "yellow",
	[137504] = {"blue","orange"},
	[137505] = "red",
})

BigWigs:AddSounds("Oondasta", {
	[137457] = "long",
	[137504] = "info",
	[137505] = "alert",
})

BigWigs:AddColors("Ordos", {
	[144688] = "orange",
	[144689] = {"blue","orange"},
	[144692] = {"blue","yellow"},
	[144695] = {"blue","yellow"},
})

BigWigs:AddSounds("Ordos", {
	[144689] = "alert",
	[144692] = {"alarm","info"},
	[144695] = "info",
})
