-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kargath Bladefist", {
	[-9396] = "cyan",
	[158986] = {"blue","red"},
	[159113] = {"blue","orange"},
	[159250] = "yellow",
	[159311] = "blue",
	[159413] = "blue",
	[159947] = {"blue","orange","yellow"},
	[160521] = "yellow",
	[162497] = {"blue","red"},
	["arena_sweeper"] = "orange",
})

BigWigs:AddSounds("Kargath Bladefist", {
	[158986] = "long",
	[159113] = "warning",
	[159311] = "info",
	[159413] = "info",
	[159947] = "alert",
	[160521] = "alarm",
	[162497] = "alarm",
	["arena_sweeper"] = "info",
})

BigWigs:AddColors("The Butcher", {
	[-10228] = "yellow",
	[156151] = {"blue","orange"},
	[156152] = "blue",
	[156157] = "yellow",
	[156197] = "orange",
	[163046] = "blue",
	["frenzy"] = {"cyan","red"},
})

BigWigs:AddSounds("The Butcher", {
	[156151] = "warning",
	[156152] = "alarm",
	[156197] = "alert",
	[163046] = "alarm",
	["frenzy"] = "alarm",
})

BigWigs:AddColors("Tectus", {
	[162288] = "yellow",
	[162346] = {"blue","green"},
	[162475] = "green",
	[162518] = "red",
	[162892] = {"blue","orange"},
	[162894] = "orange",
	[162968] = {"blue","yellow"},
	[163312] = "orange",
	["adds"] = "yellow",
})

BigWigs:AddSounds("Tectus", {
	[162346] = "alarm",
	[162475] = "long",
	[162518] = "warning",
	[162892] = "warning",
	[162894] = "alert",
	[162968] = {"alarm","alert"},
	["adds"] = "info",
})

BigWigs:AddColors("Brackenspore", {
	[159219] = "orange",
	[159996] = "red",
	[160013] = "blue",
	[163241] = {"blue","yellow"},
	[163755] = "orange",
	[163794] = "orange",
	[164125] = "red",
	["flesh_eater"] = "orange",
	["living_mushroom"] = "green",
	["mind_fungus"] = "yellow",
	["rejuvenating_mushroom"] = "green",
	["spore_shooter"] = "yellow",
})

BigWigs:AddSounds("Brackenspore", {
	[159219] = "warning",
	[159996] = "alarm",
	[160013] = "alert",
	[163241] = "warning",
	[163755] = "alarm",
	[164125] = "info",
	["flesh_eater"] = "long",
	["living_mushroom"] = "long",
	["mind_fungus"] = "long",
	["rejuvenating_mushroom"] = "info",
	["spore_shooter"] = "info",
})

BigWigs:AddColors("Twin Ogron", {
	[143834] = "orange",
	[157943] = "yellow",
	[158057] = "yellow",
	[158093] = "orange",
	[158134] = "orange",
	[158200] = "yellow",
	[158241] = "blue",
	[158385] = "orange",
	[158521] = "yellow",
	[163297] = {"blue","cyan"},
	[163372] = "cyan",
	[167200] = {"blue","cyan"},
	["volatility_self"] = "blue",
})

BigWigs:AddSounds("Twin Ogron", {
	[157943] = "alert",
	[158057] = "alert",
	[158093] = "long",
	[158134] = "alarm",
	[158200] = "alert",
	[158241] = "info",
	[158385] = {"alarm","info"},
	["volatility_self"] = "warning",
})

BigWigs:AddColors("Ko'ragh", {
	[160734] = {"cyan","green"},
	[161242] = {"blue","green"},
	[161328] = {"blue","yellow"},
	[161612] = "green",
	[162184] = "yellow",
	[162185] = "red",
	[162186] = {"blue","orange"},
	[172747] = {"blue","cyan"},
	[172895] = {"blue","yellow"},
	["volatile_anomaly"] = "yellow",
})

BigWigs:AddSounds("Ko'ragh", {
	[160734] = {"info","long"},
	[161328] = "alarm",
	[161612] = "warning",
	[162184] = "alert",
	[162185] = "alarm",
	[162186] = "warning",
	[172747] = "alarm",
	[172895] = {"alert","info"},
	["volatile_anomaly"] = "info",
})

BigWigs:AddColors("Imperator Mar'gok", {
	[-9921] = "cyan",
	[156225] = {"blue","yellow"},
	[156238] = "orange",
	[156467] = "red",
	[156471] = "yellow",
	[157349] = "orange",
	[157763] = "blue",
	[157801] = {"blue","red","yellow"},
	[158553] = {"blue","yellow"},
	[158563] = "orange",
	[158605] = {"blue","orange"},
	[159515] = {"blue","yellow"},
	[165102] = {"blue","yellow"},
	[165116] = "green",
	[165243] = "yellow",
	[165595] = "blue",
	[165876] = "red",
	[176533] = "blue",
	[176537] = "blue",
	[178468] = "orange",
	[178607] = "orange",
	["adds"] = "yellow",
	["stages"] = "cyan",
	["volatile_anomaly"] = "yellow",
})

BigWigs:AddSounds("Imperator Mar'gok", {
	[-9921] = "info",
	[156238] = "alert",
	[156467] = "warning",
	[156471] = "info",
	[157763] = "alarm",
	[157801] = "alert",
	[158553] = "alarm",
	[158563] = "warning",
	[158605] = "alarm",
	[159515] = "warning",
	[165102] = "alert",
	[165243] = "info",
	[165595] = "warning",
	[165876] = {"info","long"},
	[176533] = "info",
	[176537] = "alarm",
	[178468] = "alert",
	[178607] = "alarm",
	["adds"] = "info",
	["stages"] = {"info","long"},
	["volatile_anomaly"] = "info",
})

BigWigs:AddColors("Highmaul Trash", {
	[166200] = "blue",
	[172066] = "blue",
	[173827] = "blue",
	[174404] = "blue",
	[175636] = "blue",
	[175654] = "blue",
})

BigWigs:AddSounds("Highmaul Trash", {
	[166200] = "alarm",
	[172066] = "alarm",
	[173827] = "alert",
	[174404] = "alarm",
	[175636] = "alarm",
	[175654] = "alert",
})
