local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes_Valdrakken", "esES", false, true)

if not L then return end
-- Spanish localization by S0NSHINE_ ( https://www.curseforge.com/members/S0NSHINE_ )
-- and Irakua ( https://www.curseforge.com/members/Irakua )
if L then
L["Blizzard"] = true
L["Both"] = "Ambos"
L["config_auctioneer"] = "Subastador"
L["config_auctioneer_desc"] = "Muestra la ubicación del subastador."
L["config_banker"] = "Banco"
L["config_banker_desc"] = "Muestra las ubicaciones de los banqueros."
L["config_barber"] = "Peluquería"
L["config_barber_desc"] = "Muestra la ubicación del peluquero."
L["config_easy_waypoints"] = "Puntos de ruta fáciles"
L["config_easy_waypoints_desc"] = "Activa la creación de puntos de ruta simplificada. Te permite establecer un punto de ruta haciendo clic derecho y acceder a más opciones con CTRL + clic derecho."
L["config_fmaster_waypoint"] = "Punto de Maestro de Vuelo"
L["config_fmaster_waypoint_desc"] = "Establece un punto de ruta automáticamente hasta el Maestro de Vuelo si entras en el Círculo de Transferencias."
L["config_guildvault"] = "Cámara de la hermandad"
L["config_guildvault_desc"] = "Muestra la ubicación de la cámara de la hermandad."
L["config_icon_alpha"] = "Transparencia de Icono"
L["config_icon_alpha_desc"] = "Transparencia alfa de los iconos"
L["config_icon_scale"] = "Escala de Icono"
L["config_icon_scale_desc"] = "La escala de los iconos-"
L["config_innkeeper"] = "Tabernero"
L["config_innkeeper_desc"] = "Muestra la ubicación del tabernero."
L["config_mail"] = "Buzón"
L["config_mail_desc"] = "Muestra las ubicaciones de los buzones."
L["config_onlymytrainers"] = "Mostrar sólo los instructores y vendedores para mis profesiones."
L["config_onlymytrainers_desc"] = [[
Sólo afecta al instructor y vendedor de las profesiones principales.

|cFFFF0000NOTE: Sólo afecta al instructor y vendedor de las profesiones principales.|r
]]
L["config_others"] = "Otros"
L["config_others_desc"] = "Muestra el resto de Puntos de Interés."
L["config_picons"] = "Mostrar iconos de profesión para:"
L["config_picons_trainer_desc"] = "Muestra iconos de profesión para instructores en lugar de los iconos de instructor."
L["config_picons_vendor_desc"] = "Muestra iconos de profesión para vendedores en lugar de los iconos de vendedor."
L["config_plugin_desc"] = "Muestra la ubicación de PNJ y puntos de interés de Valdrakken en el mapa de mundo y minimapa."
L["config_plugin_name"] = "Valdrakken"
L["config_portal"] = "Portal"
L["config_portal_desc"] = "Muestra la ubicación del portal."
L["config_portaltrainer"] = "Instructor de portal"
L["config_portaltrainer_desc"] = "Muestra la ubicación del instructor de portales para magos."
L["config_reforge"] = "Potenciador de armaduras"
L["config_reforge_desc"] = "Muestra la ubicación del potenciador de armaduras."
L["config_restore_nodes"] = "Restaurar puntos ocultos."
L["config_restore_nodes_desc"] = "Restaurar todos los nodos que estaban ocultos a través del menú contextual."
L["config_restore_nodes_print"] = "Todos los puntos han sido restaurados."
L["config_stablemaster"] = "Maestro de establos"
L["config_stablemaster_desc"] = "Muestra la ubicación del maestro de establos."
L["config_tab_general"] = "General"
L["config_tab_scale_alpha"] = "Escala / Transparencia"
L["config_tpplatform"] = "Plataforma de Teletransportes"
L["config_tpplatform_desc"] = "Muestra las ubicaciones de la plataforma de teletransporte."
L["config_trainer"] = "Instructor de profesión"
L["config_trainer_desc"] = "Muestra las ubicaciones de los instructores de profesiones."
L["config_transmogrifier"] = "Transfigurador"
L["config_transmogrifier_desc"] = "Muestra la ubicación del transfigurador."
L["config_travelguide_note"] = "|cFFFF0000*Ya activo a través de HandyNotes: TravelGuide.|r"
L["config_vendor"] = "Vendedor"
L["config_vendor_desc"] = "Muestra las ubicaciones de los vendedores."
L["config_void"] = "Almacenamiento del Vacío"
L["config_void_desc"] = "Muestra la ubicación del almacenamiento del Vacío."
L["config_waypoint_dropdown"] = "Elige"
L["config_waypoint_dropdown_desc"] = "Elije cómo se debe crear el punto de ruta."
L["config_what_to_display"] = "¿Qué mostrar?"
L["config_what_to_display_desc"] = "Estos ajustes controlan qué tipos de iconos se muestran."
L["dev_config_force_nodes"] = "Forzar Puntos"
L["dev_config_force_nodes_desc"] = "Fuerza la visualización de todos los puntos independientemente de la clase, facción o curia."
L["dev_config_show_prints"] = "Mostrar print()"
L["dev_config_show_prints_desc"] = "Muestra print() mensajes en la ventana de chat."
L["dev_config_tab"] = "DEV"
L["handler_context_menu_add_tomtom"] = "Añadir a TomTom"
L["handler_context_menu_addon_name"] = "HandyNotes: Valdrakken"
L["handler_context_menu_hide_node"] = "Oculta este punto"
L["handler_tooltip_data"] = "RECUPERANDO DATOS..."
L["handler_tooltip_quest"] = "Desbloqueado con la misión"
L["handler_tooltip_requires"] = "Necesita"
L["handler_tooltip_requires_level"] = "Necesita tener mínimo nivel"
L["Mailbox"] = "Buzón"
L["Portal to Dalaran"] = "Portal a Dalaran"
L["Portal to Jade Forest"] = "Portal al Bosque de Jade"
L["Portal to Orgrimmar"] = "Portal a Orgrimmar"
L["Portal to Stormwind"] = "Portal a Ventormenta"
L["TomTom"] = true
end