
if GetLocale() ~= "esMX" then return end
local _, sm = ...
local L = sm.L
L["1. Background"] = "Fondo"
L["2. Border"] = "Borde"
L["3. Artwork"] = "Obras de Arte" -- Needs review
L["4. Overlay"] = "Superponible"
L["5. Highlight"] = "Resaltar"
L["Add Blend (additive)"] = "Agregar Mezcla (additivo)"
L["Addon Buttons"] = "Botones del Addon"
L["Allow SexyMap to assume drag ownership for buttons attached to the minimap. Turn this off if you have another mod that you want to use to position your minimap buttons."] = "Permitir a SexyMap asumìr la propiedad de los botones agregados al minimapa. Desactive esta opción si tiene otro mod que quiera usar para posicionar sus botones del minimapa." -- Needs review
L["Alpha Key (1-bit alpha)"] = "Llave Alpha (1-bit alpha)"
L["Always"] = "Siempre"
L["Armored Man"] = "Hombre en armadura"
L["A static amount to rotate the texture by."] = [=[Una cantidad estática para rotar la textura 
Una cantidad estática para rotar la textura por
]=]
L["Auto Zoom-Out Delay"] = "Demora en el Zoom automático"
L["Backdrop Color"] = "Color de fondo" -- Needs review
L["Backdrop Insets"] = "inserciones telón" -- Needs review
L["Background Color"] = "Color de fondo"
L["Background/edge"] = "fondo / de borde" -- Needs review
L["Background Texture"] = "Textura de fondo" -- Needs review
L["Blend Mode"] = "Modo de mezcla" -- Needs review
L["Blend (normal)"] = "Mezcla" -- Needs review
L["Border Color"] = "Color del Contorno" -- Needs review
L["Border Edge Size"] = "Tamaño del borde fronterizo" -- Needs review
L["Borders"] = "Contornos" -- Needs review
L["Border Texture"] = "Textura del Contorno" -- Needs review
L["Boss Frames"] = "Marcos de los Jefes" -- Needs review
L["Buttons"] = "Botones" -- Needs review
L["Calendar"] = "Calendario" -- Needs review
L["Capture Bars"] = "Barras de captura (this is the noun form, pretty sure they meant the verb form of capture)" -- Needs review
L["Challenge Mode Button (When Available)"] = "Botón Modo Desafío (Cuando Esté Disponible)" -- Needs review
L["Circle"] = "Encerrar"
L["Clamp to screen"] = "sujetar a la pantalla" -- Needs review
L["Clear & start over"] = "Limpiar y recomenzar" -- Needs review
L["Clear the current borders and start fresh"] = "Limpiar el contorno actual y comenzar de cero" -- Needs review
L["Clock"] = "Relój" -- Needs review
L["Coordinates"] = "Coordenadas" -- Needs review
L["Create a new border"] = "Crear un nuevo contorno" -- Needs review
L["Current Borders"] = "fronteras actuales" -- Needs review
L["Delete"] = "Borrar" -- Needs review
L["Diamond"] = "Diamante" -- Needs review
L["Disable Rotation"] = "Desactivar rotacion" -- Needs review
L["Dungeon Difficulty Indicator (When Available)"] = "Indicador de dificultad de mazmorra (cuando este disponible)" -- Needs review
L["Dynamic Buttons"] = "Botones dinamicos" -- Needs review
L["Enable"] = "Activar" -- Needs review
L["Enable a HUD minimap. This is very useful for gathering resources, but for technical reasons, the HUD map and the normal minimap can't be shown at the same time. Showing the HUD map will turn off the normal minimap."] = "Activar un minimapa en el HUD. Esto es muy util cuando se recolectan recursos, pero por problemas tecnicos, el mapa HUD y el minimapa normal no pueden mostrarse al mismo tiempo. Mostrar el mapa de HUD va a apagar el minimapa normal." -- Needs review
L["Enable Coordinates"] = "Activar coordenadas" -- Needs review
L["Enable Hudmap"] = "Activar Hudmap" -- Needs review
L["Enable Minimap Fader"] = "Activar transparencia del minimapa" -- Needs review
L["Enter a name to create a new border. The name can be anything you like to help you identify that border."] = "Ingresá un nombre para crear un nuevo borde. El nombre puede ser cualquier cosa que pueda ayudarte a identificar ese borde." -- Needs review
L["Entry Options"] = "Opciones de entrada" -- Needs review
L["Font"] = "Letra" -- Needs review
L["Font Color"] = "Color de la letra" -- Needs review
L["Font Size"] = "Tamaño de la letra" -- Needs review
L["Guild Dungeon Difficulty Indicator (When Available)"] = "Indicador de la Dificultad de la Mazmorra de la Hermandad" -- Needs review
L["Heart"] = "Corazon" -- Needs review
L["Height"] = "Altura" -- Needs review
L["Hexagon"] = "Hexagón" -- Needs review
L["Hide default border"] = "Esconder el borde predeterminado" -- Needs review
L["Hide the default border on the minimap."] = "Esconder el borde predeterminado en el minimapa" -- Needs review
L["Horizontal Position"] = "Posicion Horizontal" -- Needs review
L["HUD Color"] = "Color del HUD" -- Needs review
L["Octagon"] = "octágono" -- Needs review


