-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Flame Leviathan", {
	[62374] = "blue",
	[62396] = "orange",
	[62475] = "green",
})

BigWigs:AddSounds("Flame Leviathan", {
	[62374] = "alarm",
	[62475] = "long",
})

BigWigs:AddColors("Ignis the Furnace Master", {
	[62382] = "green",
	[62488] = "red",
	[62717] = {"blue","red"},
	[63472] = "yellow",
	[63474] = {"blue","yellow"},
})

BigWigs:AddSounds("Ignis the Furnace Master", {
	[62382] = "info",
	[62488] = "warning",
	[62717] = "alert",
	[63472] = "long",
	[63474] = "alarm",
})

BigWigs:AddColors("Razorscale", {
	[64021] = "yellow",
	[64733] = "blue",
	[64771] = {"blue","orange"},
	["harpoon"] = "yellow",
	["stages"] = {"cyan","green","yellow"},
})

BigWigs:AddSounds("Razorscale", {
	[64021] = "warning",
	[64733] = "alarm",
	[64771] = "info",
	["harpoon"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("XT-002 Deconstructor", {
	[62776] = "yellow",
	[63849] = "yellow",
	[64193] = "orange",
	[64234] = {"blue","red"},
	[65121] = {"blue","red"},
})

BigWigs:AddSounds("XT-002 Deconstructor", {
	[62776] = "warning",
	[63849] = "long",
	[64193] = "info",
	[64234] = "alert",
	[65121] = "alert",
})

BigWigs:AddColors("The Iron Council", {
	[61869] = "yellow",
	[61887] = {"blue","yellow"},
	[61903] = "orange",
	[61974] = "green",
	[62269] = "blue",
	[62273] = "yellow",
	[62274] = "yellow",
	[63483] = "yellow",
	[64637] = "blue",
	["stages"] = "green",
})

BigWigs:AddSounds("The Iron Council", {
	[61869] = "long",
	[61887] = "alarm",
	[62269] = "alarm",
	[64637] = "alert",
})

BigWigs:AddColors("Kologarn", {
	[63355] = {"blue","purple"},
	[63983] = "orange",
	[64290] = {"blue","yellow"},
	["arm"] = "yellow",
	["eyebeam"] = {"blue","red"},
})

BigWigs:AddSounds("Kologarn", {
	[63355] = "info",
	[64290] = "alert",
	["eyebeam"] = "info",
})

BigWigs:AddColors("Algalon the Observer", {
	[64122] = "green",
	[64412] = {"blue","orange"},
	[64443] = {"red","yellow"},
	[64597] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("Algalon the Observer", {
	[64412] = "alert",
	[64443] = "alarm",
	[64597] = "info",
})

BigWigs:AddColors("Auriaya", {
	[64386] = {"orange","yellow"},
	[64396] = {"blue","yellow"},
	[64678] = "red",
	[64688] = "yellow",
	["defender"] = "yellow",
})

BigWigs:AddSounds("Auriaya", {
	[64386] = "info",
	[64396] = "alert",
	[64678] = "long",
	[64688] = "warning",
})

BigWigs:AddColors("Hodir", {
	[61968] = {"blue","orange","yellow"},
	[62039] = "blue",
	[63512] = "red",
	[65133] = {"blue","green"},
})

BigWigs:AddSounds("Hodir", {
	[61968] = {"alert","long"},
	[62039] = "alert",
	[65133] = "info",
})

BigWigs:AddColors("Thorim", {
	[62016] = "orange",
	[62017] = "blue",
	[62042] = {"blue","orange"},
	[62130] = {"blue","yellow"},
	[62279] = "yellow",
	[62331] = {"blue","red"},
	[62338] = "orange",
	[62526] = {"blue","red"},
	[62942] = "yellow",
	["hardmode"] = "cyan",
	["stages"] = "yellow",
})

BigWigs:AddSounds("Thorim", {
	[62017] = "info",
	[62338] = "alarm",
})

BigWigs:AddColors("Freya", {
	[62437] = {"blue","yellow"},
	[62589] = "blue",
	[62623] = {"blue","yellow"},
	[62861] = {"blue","yellow"},
	[62865] = {"blue","red"},
	["stages"] = "red",
	["tree"] = "orange",
	["wave"] = "green",
})

BigWigs:AddSounds("Freya", {
	[62437] = "long",
	[62589] = "alert",
	[62861] = "info",
	[62865] = "alarm",
	["tree"] = "alarm",
})

BigWigs:AddColors("Mimiron", {
	[63274] = {"blue","red"},
	[63631] = "red",
	[63811] = "red",
	[64444] = {"blue","green","red"},
	[64529] = {"red","yellow"},
	[64570] = "red",
	[64623] = "red",
	["phase"] = "yellow",
})

BigWigs:AddSounds("Mimiron", {
	[63274] = "long",
	[63811] = "alert",
	[64444] = "info",
})

BigWigs:AddColors("General Vezax", {
	[62660] = {"blue","orange"},
	[62661] = "yellow",
	[62662] = "red",
	[63276] = {"blue","orange"},
	["animus"] = "red",
	["vapor"] = "green",
	["vaporstack"] = "blue",
})

BigWigs:AddSounds("General Vezax", {
	[62660] = "alert",
	[62661] = "warning",
	[62662] = "long",
	[63276] = "alert",
})

BigWigs:AddColors("Yogg-Saron", {
	[62979] = "green",
	[63050] = "blue",
	[63120] = {"blue","yellow"},
	[63138] = {"blue","orange"},
	[63802] = "blue",
	[63830] = {"blue","yellow"},
	[64059] = "orange",
	[64126] = {"blue","green"},
	[64163] = "red",
	[64189] = "yellow",
	[64465] = {"green","red"},
	["portal"] = "green",
	["small_tentacles"] = "red",
	["stages"] = {"red","yellow"},
	["tentacle"] = "red",
	["weakened"] = "green",
})

BigWigs:AddSounds("Yogg-Saron", {
	[63138] = "alert",
	[63802] = "warning",
	[63830] = "alert",
	[64059] = "warning",
	[64163] = "warning",
	["stages"] = "alarm",
	["weakened"] = "long",
})
