-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Mortanis", {
	[338846] = "purple",
	[338847] = "orange",
	[338848] = "yellow",
	[338849] = "yellow",
	[338850] = "red",
	[338851] = {"blue","red"},
})

BigWigs:AddSounds("Mortanis", {
	[338846] = "info",
	[338847] = "alert",
	[338849] = "alarm",
	[338850] = "long",
	[338851] = "warning",
})

BigWigs:AddColors("Oranomonos the Everbranching", {
	[338852] = {"blue","purple"},
	[338853] = {"blue","yellow"},
	[338855] = "red",
	[338856] = "red",
	[338857] = "orange",
})

BigWigs:AddSounds("Oranomonos the Everbranching", {
	[338853] = "alarm",
	[338855] = "warning",
	[338856] = "long",
	[338857] = "alert",
})

BigWigs:AddColors("Nurgash Muckformed", {
	[338858] = "purple",
	[338863] = "red",
	[338864] = "yellow",
	[338867] = "orange",
	[338868] = "red",
})

BigWigs:AddSounds("Nurgash Muckformed", {
	[338858] = "alarm",
	[338863] = "alarm",
	[338864] = "info",
	[338867] = "warning",
	[338868] = "long",
})

BigWigs:AddColors("Valinor", {
	[327246] = "red",
	[327255] = {"blue","purple"},
	[327262] = {"blue","orange"},
	[327274] = "yellow",
	[327280] = "cyan",
})

BigWigs:AddSounds("Valinor", {
	[327246] = "alert",
	[327262] = "alarm",
	[327274] = "warning",
	[327280] = "long",
})
