-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Halfus Wyrmbreaker", {
	[83589] = "cyan",
	[83703] = "yellow",
	[83706] = "red",
	[83707] = "red",
	[83710] = {"cyan","orange"},
	[83908] = {"blue","purple"},
	[84030] = "yellow",
})

BigWigs:AddSounds("Halfus Wyrmbreaker", {
	[83703] = "alert",
	[83706] = "alarm",
	[83707] = "warning",
	[83710] = "info",
	[84030] = "long",
})

BigWigs:AddColors("Valiona and Theralion", {
	[86059] = "red",
	[86369] = "blue",
	[86408] = "red",
	[86505] = "blue",
	[86622] = {"blue","orange"},
	[86788] = {"blue","yellow"},
	[86840] = "red",
	[88518] = "blue",
	[93051] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Valiona and Theralion", {
	[86059] = "alarm",
	[86369] = "warning",
	[86408] = "alarm",
	[86505] = "underyou",
	[86622] = "alarm",
	[86788] = {"alert","warning"},
	[86840] = "alert",
	[88518] = "long",
})

BigWigs:AddColors("Ascendant Council", {
	[82631] = "red",
	[82660] = {"blue","red"},
	[82665] = {"blue","red"},
	[82746] = "yellow",
	[82762] = "blue",
	[82860] = "blue",
	[83067] = {"blue","red"},
	[83099] = {"blue","red"},
	[83565] = {"blue","red"},
	[83718] = "orange",
	[84913] = "orange",
	[84915] = "blue",
	[84948] = {"blue","red"},
	[92067] = {"blue","yellow"},
	[92075] = {"blue","yellow"},
	[92307] = {"blue","yellow"},
	["switch"] = "yellow",
})

BigWigs:AddSounds("Ascendant Council", {
	[82631] = "alert",
	[82746] = "alert",
	[82762] = "warning",
	[82860] = "underyou",
	[83067] = {"alarm","info"},
	[83099] = "warning",
	[83565] = {"alarm","info"},
	[83718] = "info",
	[84915] = "underyou",
	[84948] = "warning",
	[92067] = "warning",
	[92075] = "warning",
	[92307] = {"alarm","warning"},
	["switch"] = "info",
})

BigWigs:AddColors("Cho'gall", {
	[81538] = "blue",
	[81628] = "red",
	[81685] = {"blue","orange"},
	[82235] = "blue",
	[82299] = "yellow",
	[82414] = "orange",
	[82524] = "yellow",
	[82630] = {"green","yellow"},
	[91303] = {"blue","red"},
	["orders"] = "orange",
})

BigWigs:AddSounds("Cho'gall", {
	[81538] = "info",
	[81685] = "long",
	[82235] = "long",
	[82299] = "alert",
	[82630] = "info",
	[91303] = "alarm",
})

BigWigs:AddColors("Sinestra", {
	[87654] = "red",
	[90045] = "orange",
	[90125] = "orange",
	[92852] = {"blue","yellow"},
	["phase"] = "green",
	["whelps"] = "red",
})

BigWigs:AddSounds("Sinestra", {
	[87654] = "alert",
	[90045] = "info",
	[92852] = "warning",
	["phase"] = "info",
})
