-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Conclave of Wind", {
	[84645] = "blue",
	[85422] = "orange",
	[86082] = "orange",
	[86193] = "red",
	[86205] = "orange",
	[86281] = "orange",
	[86307] = "red",
	[93059] = "orange",
	["full_power"] = "yellow",
})

BigWigs:AddSounds("Conclave of Wind", {
	[84645] = "alarm",
	[86307] = "long",
})

BigWigs:AddColors("Al'Akir", {
	[87770] = {"red","yellow"},
	[87904] = "green",
	[88301] = "yellow",
	[88427] = {"blue","red"},
	[89588] = {"blue","red"},
	[89668] = {"blue","red"},
	["stages"] = "green",
	["stormling"] = "red",
})

BigWigs:AddSounds("Al'Akir", {
	[87770] = "alert",
	[89588] = {"alarm","info"},
	[89668] = "long",
	["stages"] = "info",
})
