-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Protectors of the Endless", {
	[117052] = "yellow",
	[117227] = "yellow",
	[117309] = {"orange","red","yellow"},
	[117436] = {"blue","red"},
	[117975] = "orange",
	[117986] = "blue",
	[118077] = "orange",
})

BigWigs:AddSounds("Protectors of the Endless", {
	[117052] = "info",
	[117309] = {"alert","info"},
	[117436] = "alert",
	[117986] = "info",
	[118077] = "alarm",
})

BigWigs:AddColors("Tsulong", {
	[-6550] = "orange",
	[122752] = "orange",
	[122768] = "blue",
	[122777] = {"blue","red","yellow"},
	[122789] = "green",
	[122855] = "orange",
	[123011] = "red",
	["embodied_terror"] = "yellow",
	["phases"] = {"green","yellow"},
	["unstable_sha"] = "red",
})

BigWigs:AddSounds("Tsulong", {
	[-6550] = "alarm",
	[122768] = "info",
	[122777] = "alert",
	[123011] = "alert",
	["phases"] = "alert",
	["unstable_sha"] = "alert",
})

BigWigs:AddColors("Lei Shi", {
	[123121] = {"blue","orange"},
	[123244] = "yellow",
	[123250] = {"green","red"},
	[123461] = {"green","red"},
	[123705] = {"blue","yellow"},
	["special"] = "yellow",
})

BigWigs:AddSounds("Lei Shi", {
	[123121] = "info",
	[123250] = "alarm",
	[123461] = "alarm",
})

BigWigs:AddColors("Sha of Fear", {
	[-6700] = "red",
	[-6699] = {"orange","red"},
	[-6109] = "blue",
	[-6107] = "green",
	[118977] = "yellow",
	[119414] = "yellow",
	[119519] = "orange",
	[119888] = {"red","yellow"},
	[120268] = {"blue","green"},
	[120455] = "yellow",
	[120519] = {"blue","orange"},
	[120629] = {"blue","red"},
	[120669] = {"blue","orange","red"},
	[120672] = "yellow",
	[129147] = {"blue","orange"},
	[129378] = "green",
	["berserk"] = "yellow",
	["swing"] = "green",
})

BigWigs:AddSounds("Sha of Fear", {
	[-6700] = "alarm",
	[-6109] = "long",
	[119414] = "long",
	[119519] = "alarm",
	[119888] = "alert",
	[120268] = "long",
	[120519] = "info",
	[120629] = "alert",
	[120669] = "info",
	[120672] = "alarm",
	[129378] = "long",
})
