-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Attumen the Huntsman Raid", {
	[29833] = {"blue","yellow"},
	["phase"] = "red",
})

BigWigs:AddSounds("Attumen the Huntsman Raid", {
})

BigWigs:AddColors("Hyakiss the Lurker", {
	[29896] = {"blue","orange"},
})

BigWigs:AddSounds("Hyakiss the Lurker", {
})

BigWigs:AddColors("Moroes Raid", {
	[29448] = {"orange","yellow"},
	[37023] = {"green","red"},
	[37066] = {"blue","yellow"},
})

BigWigs:AddSounds("Moroes Raid", {
	[29448] = "alert",
	[37023] = {"alarm","info"},
})

BigWigs:AddColors("Maiden of Virtue Raid", {
	[29511] = {"orange","red","yellow"},
	[29522] = {"blue","red"},
})

BigWigs:AddSounds("Maiden of Virtue Raid", {
	[29511] = "alarm",
})

BigWigs:AddColors("Romulo & Julianne", {
	["buff"] = "yellow",
	["heal"] = "orange",
	["phase"] = "green",
	["poison"] = {"blue","red"},
})

BigWigs:AddSounds("Romulo & Julianne", {
})

BigWigs:AddColors("The Big Bad Wolf", {
	[30753] = {"blue","yellow"},
})

BigWigs:AddSounds("The Big Bad Wolf", {
	[30753] = "long",
})

BigWigs:AddColors("The Crone", {
	[32337] = "orange",
	["spawns"] = "yellow",
})

BigWigs:AddSounds("The Crone", {
})

BigWigs:AddColors("The Curator Raid", {
	[30254] = {"green","orange","red","yellow"},
	[30403] = {"green","red"},
})

BigWigs:AddSounds("The Curator Raid", {
	[30254] = "alarm",
})

BigWigs:AddColors("Terestian Illhoof", {
	[30115] = {"blue","orange","yellow"},
	["weak"] = {"red","yellow"},
})

BigWigs:AddSounds("Terestian Illhoof", {
	["weak"] = {"alarm","info"},
})

BigWigs:AddColors("Shade of Aran", {
	[30004] = {"blue","red"},
	["adds"] = {"orange","red"},
	["blizzard"] = "yellow",
	["drink"] = {"green","orange"},
	["pull"] = "yellow",
})

BigWigs:AddSounds("Shade of Aran", {
	[30004] = {"alarm","long"},
	["adds"] = "alert",
	["drink"] = "alert",
})

BigWigs:AddColors("Netherspite", {
	[37063] = "yellow",
	[38523] = "orange",
	["phase"] = "red",
})

BigWigs:AddSounds("Netherspite", {
})

BigWigs:AddColors("Prince Malchezaar", {
	[30843] = {"blue","orange","red","yellow"},
	[30852] = {"red","yellow"},
	["infernal"] = {"orange","red"},
	["phase"] = "cyan",
})

BigWigs:AddSounds("Prince Malchezaar", {
	[30843] = "warning",
	[30852] = "alarm",
	["infernal"] = {"alert","info"},
})

BigWigs:AddColors("Nightbane Raid", {
	[30129] = "blue",
	[36922] = "green",
	[37098] = "orange",
	["phase"] = {"red","yellow"},
})

BigWigs:AddSounds("Nightbane Raid", {
	[30129] = "alarm",
	["phase"] = {"info","long"},
})
