local ADDON_NAME, ns = ...
local L = LibStub("AceLocale-3.0"):GetLocale(ADDON_NAME)

function ns.LoadSpecialLocations(self)
local db = ns.Addon.db.profile
local nodes = ns.nodes
local minimap = ns.minimap
local raceName, raceFile, raceID = UnitRace("player")
local DarkIronDwarf = C_CreatureInfo.GetRaceInfo(34).raceName
ns._currentSourceFile = "RetailSpecialLocations.lua"

    if not db.activate.HideMapNote then

        if raceFile == "DarkIronDwarf" then

            -- Capitals
            if db.activate.Capitals then
                
                if self.db.profile.showCapitalsRaces then
                    if db.activate.showRacesIconsDiscovered then nodes[84][63333734] = { mnID = 84, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = true, showOnMinimap = false } end
                end

            end

            -- MinimapCapitals
            if db.activate.MiniMapCapitals then
                
                if self.db.profile.showMiniMapCapitalsRaces then
                    if db.activate.showRacesIconsDiscovered then minimap[84][63333734] = { mnID = 84, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = false, showOnMinimap = true } end
                end

            end

            -- Zonemap
            if db.activate.ZoneMap then
                if self.db.profile.showZoneRaces then
                  
                    if self.db.profile.showZoneEasternKingdom then
                        if db.activate.showRacesIconsDiscovered then nodes[27][61293718] = { mnID = 27, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered then nodes[1186][61442435] = { name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53568) then nodes[27][61293718] = { mnID = 27, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = true, showOnMinimap = false } nodes[1186][61442435] = { name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53594) then nodes[17][61971280] = { mnID = 17, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")" .. "\n\n" .. L["If you don't see this icon, it's probably in a different phase. \nChange the phase on Zidormi"], questID = 53594, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53585) then nodes[26][13534680] = { mnID = 26, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53585, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then
                            nodes[35][33302480] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false }
                            nodes[33][43474334] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false }
                            nodes[32][34088561] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false }
                            nodes[36][20513029] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false }
                        end
                    end

                    if self.db.profile.showZoneKalimdor then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53591) then nodes[78][52885576] = { mnID = 78, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53591, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53601) then nodes[198][57187711] = { mnID = 198, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53601, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53600) then
                            nodes[10][30225472]  = { mnID = 199, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53600, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false }
                            nodes[199][39110930] = { mnID = 199, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", questID = 53600, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false }
                        end
                    end
                                    
                    if self.db.profile.showZoneOutland then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53592) then nodes[100][53156489] = { mnID = 100, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53592, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53599) then nodes[104][50773530] = { mnID = 104, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53599, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53597) then nodes[105][72421764] = { mnID = 105, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53597, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneNorthrend then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53586) then nodes[118][76971866] = { mnID = 118, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53586, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53596) then nodes[115][45354992] = { mnID = 115, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53596, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZonePandaria then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53595) then nodes[379][57686281] = { mnID = 379, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53595, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53598) then nodes[376][31517359] = { mnID = 376, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53598, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneDraenor then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53588) then nodes[543][46693876] = { mnID = 543, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53588, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53590) then nodes[550][65750825] = { mnID = 550, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53590, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneBrokenIsles then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53593) then nodes[650][44667290] = { mnID = 650, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53593, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53589) then nodes[646][71694799] = { mnID = 646, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53589, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneZandalar then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80099) then nodes[863][34344515] = { mnID = 863, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80099, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80100) then nodes[862][38247238] = { mnID = 862, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80100, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneKulTiras then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80101) then nodes[895][88227153] = { mnID = 895, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80101, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80102) then nodes[942][64212944] = { mnID = 942, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80102, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneShadowlands then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80103) then nodes[1536][53495979] = { mnID = 1536, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80103, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80104) then nodes[1525][19923879] = { mnID = 1525, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80104, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80105) then nodes[1533][51751314] = { mnID = 1533, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80105, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80106) then nodes[1565][66475055] = { mnID = 1565, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80106, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end

                    if self.db.profile.showZoneDragonIsles then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80107) then nodes[2022][32365490] = { mnID = 2022, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80107, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80108) then nodes[2024][80093896] = { mnID = 2024, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80108, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80109) then nodes[2133][52732767] = { mnID = 2133, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80109, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80109) then nodes[1978][87367740] = { mnID = 2133, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80109, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true, showOnMinimap = false } end
                    end
                end
            end

            -- Minimap
            if db.activate.MiniMap then

                if self.db.profile.showMiniMapRaces then

                    if self.db.profile.showMiniMapEasternKingdom then
                        if db.activate.showRacesIconsDiscovered then minimap[27][61293718] = { mnID = 27, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered then minimap[1186][61442435] = { name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "(" .. LFG_LIST_REQUIRE .. " " .. RACE .. " " .. DarkIronDwarf .. ")", showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53594) then minimap[17][61971280] = { mnID = 17, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53594, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53585) then minimap[26][13534680] = { mnID = 26, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53585, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then minimap[35][33302480] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then minimap[33][43474334] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then minimap[32][34088561] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then minimap[36][20513029] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapKalimdor then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53591) then minimap[78][52885576] = { mnID = 78, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53591, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53601) then minimap[198][57187711] = { mnID = 198, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53601, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53600) then minimap[10][30225472] = { mnID = 199, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53600, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53600) then minimap[199][39110930] = { mnID = 199, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53600, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapOutland then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53592) then minimap[100][53156489] = { mnID = 100, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53592, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53599) then minimap[104][50773530] = { mnID = 104, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53599, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53597) then minimap[105][72421764] = { mnID = 105, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53597, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapNorthrend then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53586) then minimap[118][76971866] = { mnID = 118, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53586, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53596) then minimap[115][45354992] = { mnID = 115, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53596, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapPandaria then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53595) then minimap[379][57686281] = { mnID = 379, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53595, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53598) then minimap[376][31517359] = { mnID = 376, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53598, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapDraenor then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53588) then minimap[543][46693876] = { mnID = 543, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53588, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53590) then minimap[550][65750825] = { mnID = 550, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53590, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapBrokenIsles then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53593) then minimap[650][44667290] = { mnID = 650, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53593, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53589) then minimap[646][71694799] = { mnID = 646, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53589, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapZandalar then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80099) then minimap[863][34344515] = { mnID = 863, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80099, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80100) then minimap[862][38247238] = { mnID = 862, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80100, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapKulTiras then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80101) then minimap[895][88227153] = { mnID = 895, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80101, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80102) then minimap[942][64212944] = { mnID = 942, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80102, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapShadowlands then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80103) then minimap[1536][53495979] = { mnID = 1536, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80103, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80104) then minimap[1525][19923879] = { mnID = 1525, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80104, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80105) then minimap[1533][51751314] = { mnID = 1533, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80105, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80106) then minimap[1565][66475055] = { mnID = 1565, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80106, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end
                    
                    if self.db.profile.showMiniMapDragonIsles then
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80107) then minimap[2022][32365490] = { mnID = 2022, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80107, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80108) then minimap[2024][80093896] = { mnID = 2024, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80108, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80109) then minimap[2133][52732767] = { mnID = 2133, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80109, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                        if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80109) then minimap[1978][87367740] = { mnID = 2133, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80109, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = false, showOnMinimap = true } end
                    end

                end
            end

            -- Continent Map
            if db.activate.Continent then

                if self.db.profile.showContinentEasternKingdom then
                    if db.activate.showRacesIconsDiscovered then nodes[13][46656008] = { mnID = 27, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered then nodes[13][43097191] = { mnID = 84, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered then nodes[1186][61442435] = { name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53594) then nodes[13][53148130] = { mnID = 17, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53594, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53585) then nodes[13][49784019] = { mnID = 26, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53585, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then nodes[13][47316924] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentKalimdor then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53591) then nodes[12][50167999] = { mnID = 78, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53591, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53601) then nodes[12][55493360] = { mnID = 198, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53601, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53600) then nodes[12][50635103] = { mnID = 199, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53600, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentOutland then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53592) then nodes[101][58485621] = { mnID = 100, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53592, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53599) then nodes[101][66177787] = { mnID = 104, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53599, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53597) then nodes[101][46391736] = { mnID = 105, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53597, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentNorthrend then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53586) then nodes[113][48571945] = { mnID = 118, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53586, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53596) then nodes[113][46085903] = { mnID = 115, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53596, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentPandaria then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53595) then nodes[424][48433542] = { mnID = 379, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53595, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53598) then nodes[424][46867238] = { mnID = 376, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53598, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentDraenor then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53588) then nodes[572][48422449] = { mnID = 543, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53588, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53590) then nodes[572][29324349] = { mnID = 550, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53590, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentBrokenIsles then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53593) then nodes[619][45452953] = { mnID = 650, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53593, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53589) then nodes[619][58006767] = { mnID = 646, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53589, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentZandalar then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80099) then nodes[875][51732835] = { mnID = 863, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80099, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80100) then nodes[875][45767991] = { mnID = 862, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80100, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentKulTiras then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80101) then nodes[876][69317685] = { mnID = 895, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80101, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80102) then nodes[876][59731634] = { mnID = 942, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80102, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentShadowlands then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80103) then nodes[1550][63342497] = { mnID = 1536, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80103, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80104) then nodes[1550][17675032] = { mnID = 1525, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80104, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80105) then nodes[1550][72134797] = { mnID = 1533, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80105, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80106) then nodes[1550][53778116] = { mnID = 1565, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80106, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

                if self.db.profile.showContinentDragonIsles then
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80107) then nodes[1978][44513478] = { mnID = 2022, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80107, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80108) then nodes[1978][65077127] = { mnID = 2024, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80108, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80109) then nodes[1978][87367740] = { mnID = 2133, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80109, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showOnContinent = true } end
                end

            end

            -- Azeroth Map                
            if db.activate.Azeroth then
                if self.db.profile.showAzerothRaces then
                    if db.activate.showRacesIconsDiscovered then nodes[947][86285685] = { mnID = 27, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", showInZone = true } end
                    if db.activate.showRacesIconsDiscovered then nodes[947][84516347] = { mnID = 84, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53587) then nodes[947][86796183] = { mnID = 35, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53587, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53594) then nodes[947][89856822] = { mnID = 17, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53594, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53585) then nodes[947][88084622] = { mnID = 26, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53585, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53591) then nodes[947][17676774] = { mnID = 78, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53591, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53601) then nodes[947][20184585] = { mnID = 198, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53601, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53600) then nodes[947][17825409] = { mnID = 199, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53600, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53586) then nodes[947][49370700] = { mnID = 118, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53586, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53596) then nodes[947][48901689] = { mnID = 115, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53596, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53595) then nodes[947][47647716] = { mnID = 379, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53595, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53598) then nodes[947][47178564] = { mnID = 376, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53598, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53593) then nodes[947][58633761] = { mnID = 650, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53593, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(53589) then nodes[947][61304608] = { mnID = 646, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 53589, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80099) then nodes[947][54715903] = { mnID = 863, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80099, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80100) then nodes[947][53306798] = { mnID = 862, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80100, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80101) then nodes[947][74965284] = { mnID = 895, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80101, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80102) then nodes[947][73234248] = { mnID = 942, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80102, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80107) then nodes[947][75581752] = { mnID = 2022, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80107, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80108) then nodes[947][80142576] = { mnID = 2024, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80108, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                    if db.activate.showRacesIconsDiscovered or not C_QuestLog.IsQuestFlaggedCompleted(80109) then nodes[947][84402766] = { mnID = 2133, name = L["Mole Machine"], type = "MoleMachineDwarf", dnID = "("..LFG_LIST_REQUIRE.." "..RACE.." "..DarkIronDwarf..")", questID = 80109, wwwLink = L["Travel to this point and click on the mole machine on site to unlock it"], showWWW = true, hideLink = true, showInZone = true } end
                end
            end
        end

    end

end