-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kurinnaxx", {
	[25646] = {"blue","purple"},
	[25648] = {"blue","orange"},
	[26527] = {"green","red"},
})

BigWigs:AddSounds("Kurinnaxx", {
	[25646] = "warning",
	[25648] = "alert",
	[26527] = "long",
})

BigWigs:AddColors("General Rajaxx", {
	[8269] = "red",
	[25462] = {"green","orange"},
	[25471] = {"blue","yellow"},
	[25599] = "orange",
	[26550] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("General Rajaxx", {
	[8269] = "long",
	[25462] = "alarm",
	[25471] = "warning",
	[25599] = "alert",
	[26550] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("Moam", {
	[25685] = {"red","yellow"},
})

BigWigs:AddSounds("Moam", {
	[25685] = "long",
})

BigWigs:AddColors("Buru the Gorger", {
	["fixate"] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Buru the Gorger", {
	["fixate"] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Ayamiss the Hunter", {
	[8269] = {"green","red"},
	[17742] = "blue",
	[25725] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ayamiss the Hunter", {
	[17742] = "underyou",
	[25725] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Ossirian the Unscarred", {
	[25176] = "red",
	[25177] = "yellow",
	[25178] = "yellow",
	[25180] = "yellow",
	[25181] = "yellow",
	[25183] = "yellow",
	[25188] = "orange",
	[25189] = {"blue","red"},
	[25195] = "orange",
})

BigWigs:AddSounds("Ossirian the Unscarred", {
	[25176] = "alert",
	[25177] = "info",
	[25178] = "info",
	[25180] = "info",
	[25181] = "info",
	[25183] = "info",
	[25189] = "warning",
	[25195] = "long",
})

BigWigs:AddColors("Ruins of Ahn'Qiraj Trash", {
	[8269] = "red",
	[8732] = "orange",
	[14297] = "red",
	[17430] = "green",
	[17431] = "green",
	[22997] = {"blue","yellow"},
	[24340] = "red",
	[25698] = "orange",
	[1214956] = "yellow",
	[1215202] = "blue",
	[1215421] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ruins of Ahn'Qiraj Trash", {
	[8269] = "long",
	[8732] = "alert",
	[14297] = "alarm",
	[22997] = "warning",
	[24340] = "info",
	[25698] = "long",
	[1215202] = "warning",
	[1215421] = "underyou",
})
