-- THIS CONTENTS OF THIS FILE IS AUTO-GENERATED BY THE WOWACE PACKAGER
-- Please use the Localization App on WoWAce to update this
-- at http://www.wowace.com/addons/handynotes/localization/

local L = LibStub("AceLocale-3.0"):NewLocale("HandyNotes", "ruRU")
if not L then return end

L[ [=[
Alt+Right Click To Add a HandyNote]=] ] = "Alt+[ПКМ], чтобы добавить HandyNote"
L["(No Title)"] = "(без названия)"
L["|cFF00FF00Hint: |cffeda55fCtrl+Shift+LeftDrag|cFF00FF00 to move a note"] = "|cFF00FF00Подсказка: |cffeda55fCtrl+Shift+[ЛКМ]|cFF00FF00, чтобы переместить заметку"
L["Add Handy Note"] = "Добавить заметку"
L["Add this location to TomTom waypoints"] = "Добавить это местоположение в качестве путевой точки TomTom"
L["Configuration for each individual plugin database."] = "Конфигурация базы данных каждого отдельного плагина"
L["Delete Handy Note"] = "Удалить заметку"
L["Description/Notes:"] = "Описание/заметки:"
L["Edit Handy Note"] = "Редактировать заметку"
L["Enable HandyNotes"] = "Включить HandyNotes"
L["Enable or disable HandyNotes"] = "Включить/выключить HandyNotes"
L["ERROR_CREATE_NOTE1"] = "HandyNotes не может создать заметку, поскольку не удаётся определить ваше текущее местоположение. Обычно причиной этого является отсутствие карты у местности, в которой вы находитесь."
L["HandyNotes"] = "HandyNotes"
L["Icon Alpha"] = "Прозрачность значков"
L["Icon Scale"] = "Размер значков"
L["Minimap Icon Alpha"] = "Прозрачность значков миникарты"
L["Minimap Icon Scale"] = "Размер значков миникарты"
L["Overall settings"] = "Общие настройки"
L["Overall settings that affect every database"] = "Общие настройки действуют на все базы данных"
L["Plugin databases"] = "Базы данных плагинов"
L["Plugins"] = "Плагины"
L["Portal"] = "Портал"
L["Show on continent map"] = "Показывать на карте континента"
L["Show the following plugins on the map"] = "Показывать выбранные плагины на карте"
L["Syntax:"] = "Синтаксис:"
L["The alpha transparency of the icons"] = "Прозрачность значков"
L["The overall alpha transparency of the icons on the Minimap"] = "Общая прозрачность значков на миникарте"
L["The overall alpha transparency of the icons on the World Map"] = "Общая прозрачность значков на карте мира"
L["The overall scale of the icons on the Minimap"] = "Общий размер значков на миникарте"
L["The overall scale of the icons on the World Map"] = "Общий размер значков на карте мира"
L["The scale of the icons"] = "Размер значков"
L["These settings control the look and feel of HandyNotes globally. The icon's scale and alpha here are multiplied with the plugin's scale and alpha."] = "Эти настройки управляют внешним видом HandyNotes глобально. Прозрачность и размер значков, указанные здесь, умножаются на прозрачность и размер из настроек плагинов."
L["These settings control the look and feel of the HandyNotes icons."] = "Эти настройки управляют внешним видом значков HandyNotes."
L["Title"] = "Название"
L["World Map Icon Alpha"] = "Прозрачность значков карты мира"
L["World Map Icon Scale"] = "Размер значков карты мира"

