-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Beastlord Darmac", {
	[154960] = {"blue","orange","red"},
	[154975] = "yellow",
	[154981] = {"blue","orange"},
	[154989] = {"blue","orange"},
	[155030] = {"blue","yellow"},
	[155061] = {"blue","orange","yellow"},
	[155198] = "red",
	[155222] = "yellow",
	[155236] = {"blue","yellow"},
	[155247] = "yellow",
	[155321] = "yellow",
	[155499] = {"blue","orange"},
	[155657] = "blue",
	[156823] = "blue",
	[156824] = "blue",
	[159043] = {"blue","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Beastlord Darmac", {
	[154960] = {"alarm","warning"},
	[154981] = "info",
	[154989] = "alert",
	[155030] = "warning",
	[155061] = "warning",
	[155198] = "alert",
	[155236] = "warning",
	[155499] = "alert",
	[155657] = "alarm",
	[156823] = "alarm",
	[156824] = "alarm",
	[159043] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Gruul", {
	[155078] = {"blue","yellow"},
	[155080] = "orange",
	[155301] = "yellow",
	[155326] = {"blue","orange"},
	[155539] = {"green","red"},
	[173192] = "blue",
})

BigWigs:AddSounds("Gruul", {
	[155080] = "warning",
	[155301] = "info",
	[155326] = {"alarm","alert"},
	[155539] = {"info","long"},
	[173192] = "alarm",
})

BigWigs:AddColors("Oregorger", {
	[155898] = "yellow",
	[156203] = {"blue","yellow"},
	[156240] = "red",
	[156390] = "orange",
	[156877] = "orange",
	[173471] = {"blue","yellow"},
	["berserk"] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Oregorger", {
	[156203] = "alarm",
	[156240] = "warning",
	[156390] = "alarm",
	[156877] = "alert",
	[173471] = "warning",
	["berserk"] = {"alarm","info"},
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Hans'gar and Franzok", {
	[153470] = "yellow",
	[155747] = {"blue","yellow"},
	[155818] = "blue",
	[156938] = {"blue","red"},
	[157139] = {"blue","yellow"},
	[160838] = "orange",
	[162124] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Hans'gar and Franzok", {
	[155747] = "alarm",
	[155818] = "alarm",
	[156938] = {"alarm","warning"},
	[160838] = "long",
	[162124] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Flamebender Ka'graz", {
	[-9352] = "yellow",
	[154932] = {"blue","green"},
	[154950] = {"blue","yellow"},
	[154952] = "blue",
	[155064] = {"blue","green"},
	[155074] = {"blue","yellow"},
	[155277] = {"blue","yellow"},
	[155318] = {"blue","orange"},
	[155493] = {"cyan","red"},
	[155776] = "red",
	[156018] = "yellow",
	[156040] = "yellow",
	[163284] = {"blue","yellow"},
})

BigWigs:AddSounds("Flamebender Ka'graz", {
	[154932] = "warning",
	[154950] = "info",
	[154952] = "alarm",
	[155064] = "warning",
	[155074] = "warning",
	[155277] = "alert",
	[155318] = "alarm",
	[155493] = {"info","long"},
	[155776] = "alarm",
	[163284] = "warning",
})

BigWigs:AddColors("Operator Thogar", {
	[155864] = {"blue","yellow"},
	[155921] = {"blue","yellow"},
	[159481] = {"blue","yellow"},
	[160140] = {"blue","red"},
	[163753] = "orange",
	["trains"] = "cyan",
})

BigWigs:AddSounds("Operator Thogar", {
	[155864] = "alarm",
	[155921] = "warning",
	[159481] = "warning",
	[160140] = "alert",
	["trains"] = "long",
})

BigWigs:AddColors("Kromog", {
	[-9702] = "yellow",
	[156704] = "orange",
	[156766] = {"blue","yellow"},
	[156852] = "orange",
	[156861] = {"cyan","red"},
	[157054] = "red",
	[157060] = "green",
	[157592] = "orange",
	[158217] = "red",
	[173917] = "yellow",
})

BigWigs:AddSounds("Kromog", {
	[156704] = "alarm",
	[156766] = "warning",
	[156861] = {"alarm","info"},
	[157060] = "info",
	[157592] = "alert",
})

BigWigs:AddColors("The Iron Maidens", {
	[155794] = {"blue","yellow"},
	[156109] = {"blue","orange"},
	[156601] = "red",
	[156631] = {"blue","orange"},
	[158010] = {"blue","orange"},
	[158315] = {"blue","yellow"},
	[158599] = "yellow",
	[158683] = "blue",
	[158692] = {"blue","orange"},
	[158708] = "orange",
	[159336] = {"cyan","red"},
	[159724] = {"blue","yellow"},
	[164271] = {"blue","red"},
	["bombardment"] = "cyan",
	["ship"] = "cyan",
})

BigWigs:AddSounds("The Iron Maidens", {
	[156109] = "info",
	[156631] = "alarm",
	[158010] = "alert",
	[158683] = "alarm",
	[158692] = "alert",
	[158708] = "alert",
	[159336] = "long",
	[159724] = "alert",
	[164271] = {"alarm","warning"},
	["ship"] = "info",
})

BigWigs:AddColors("The Blast Furnace", {
	[-10325] = "green",
	[-10324] = "blue",
	[155173] = {"blue","orange"},
	[155179] = "blue",
	[155186] = "orange",
	[155192] = "green",
	[155209] = "yellow",
	[155225] = "blue",
	[155242] = {"blue","yellow"},
	[156934] = {"blue","orange"},
	[156937] = "yellow",
	[163776] = "red",
	[174731] = {"green","red"},
	[175104] = {"blue","yellow"},
	[176121] = "blue",
	[176133] = "red",
	[176141] = "green",
	["engineer"] = "yellow",
	["firecaller"] = "yellow",
	["guard"] = "yellow",
	["operator"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Blast Furnace", {
	[-10325] = "info",
	[-10324] = "alarm",
	[155173] = "alert",
	[155179] = "alert",
	[155186] = "alert",
	[155192] = "alarm",
	[155225] = {"alarm","info"},
	[155242] = "warning",
	[156934] = {"alarm","info"},
	[163776] = "long",
	[174731] = "info",
	[176121] = "alarm",
	[176133] = "alarm",
	["engineer"] = "info",
	["firecaller"] = "info",
	["guard"] = "info",
	["operator"] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Blackhand", {
	[155992] = "orange",
	[156030] = "yellow",
	[156096] = {"blue","red","yellow"},
	[156401] = "blue",
	[156425] = "orange",
	[156653] = {"blue","yellow"},
	[156667] = "yellow",
	[156928] = "yellow",
	[157000] = {"blue","orange"},
	[158054] = "orange",
	[162585] = "red",
	[163008] = "orange",
	["siegemaker"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Blackhand", {
	[155992] = "warning",
	[156030] = "long",
	[156096] = "alarm",
	[156401] = "info",
	[156425] = "alert",
	[156653] = "alert",
	[156667] = "info",
	[157000] = "alert",
	[158054] = "warning",
	[162585] = "alarm",
	[163008] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Blackrock Foundry Trash", {
	[18501] = {"blue","orange","yellow"},
	[159632] = {"blue","green"},
	[160260] = "blue",
	[162663] = "blue",
	[163121] = {"blue","orange","yellow"},
	[171613] = "orange",
	[174773] = "blue",
	[175583] = {"blue","green"},
	[175594] = {"blue","green","orange"},
	[175624] = {"blue","green","orange"},
	[175643] = "blue",
	[175765] = {"blue","orange"},
	[175993] = {"blue","red"},
	[177806] = "green",
})

BigWigs:AddSounds("Blackrock Foundry Trash", {
	[18501] = "warning",
	[159632] = "alarm",
	[160260] = "alert",
	[162663] = "alert",
	[163121] = "warning",
	[171613] = "warning",
	[174773] = "alert",
	[175583] = "alarm",
	[175594] = "warning",
	[175624] = "warning",
	[175643] = "alert",
	[175765] = "warning",
	[175993] = "warning",
})
