local ADDON_NAME, ns = ...

ns.defaults = {

  profile = {

    -- Instance single Zone icon scale and alpha
      ZoneInstanceScale = 2,
      ZoneInstanceAlpha = 1,
      ZoneScaleRaids = 2,
      ZoneAlphaRaids = 1,
      ZoneScaleDungeons = 2,
      ZoneAlphaDungeons = 1,
      ZoneScalePassage = 2,
      ZoneAlphaPassage = 1,
      ZoneScaleMultiple = 2,
      ZoneAlphaMultiple = 1,
      ZoneScaleOldVanilla = 2,
      ZoneAlphaOldVanilla = 1,
      ZoneScaleLFR = 2,
      ZoneAlphaLFR = 1,
      -- Instance single MiniMap icon scale and alpha
      MiniMapInstanceScale = 2,
      MiniMapInstanceAlpha = 1,
      MiniMapScaleRaids = 2,
      MiniMapAlphaRaids = 1,
      MiniMapScaleDungeons = 2,
      MiniMapAlphaDungeons = 1,
      MiniMapScalePassage = 2,
      MiniMapAlphaPassage = 1,
      MiniMapScaleMultiple = 2,
      MiniMapAlphaMultiple = 1,
      MiniMapScaleOldVanilla = 2,
      MiniMapAlphaOldVanilla = 1,
      MiniMapScaleLFR = 2,
      MiniMapAlphaLFR = 1,

    -- Transport single Zone icon scale and alpha 
      ZoneTransportScale = 1.5,
      ZoneTransportAlpha = 1,
      ZoneScalePortals = 1.5,
      ZoneAlphaPortals = 1,
      ZoneScaleZeppelins = 1.5,
      ZoneAlphaZeppelins = 1,
      ZoneScaleShips = 1.5,
      ZoneAlphaShips = 1,
      ZoneScaleTransport = 1.5,
      ZoneAlphaTransport = 1,
      ZoneScaleOgreWaygate = 1.5,
      ZoneAlphaOgreWaygate = 1,
      ZoneScaleTeleporter = 1.5,
      ZoneAlphaTeleporter = 1,
      ZoneScaleMirror = 1.5,
      ZoneAlphaMirror = 1,
      ZoneScaleTravel = 1.5,
      ZoneAlphaTravel = 1,
      ZoneScaleDarkmoon = 1.5,
      ZoneAlphaDarkmoon = 1,
      -- Transport single MiniMap icon scale and alpha 
      MiniMapTransportScale = 1.5,
      MiniMapTransportAlpha = 1,
      MiniMapScalePortals = 1.5,
      MiniMapAlphaPortals = 1,
      MiniMapScaleZeppelins = 1.5,
      MiniMapAlphaZeppelins = 1,
      MiniMapScaleShips = 1.5,
      MiniMapAlphaShips = 1,
      MiniMapScaleTransport = 1.5,
      MiniMapAlphaTransport = 1,
      MiniMapScaleOgreWaygate = 1.5,
      MiniMapAlphaOgreWaygate = 1,
      MiniMapScaleTeleporter = 1.5,
      MiniMapAlphaTeleporter = 1,
      MiniMapScaleMirror = 1.5,
      MiniMapAlphaMirror = 1,
      MiniMapScaleTravel = 1.5,
      MiniMapAlphaTravel = 1,
      MiniMapScaleDarkmoon = 1.5,
      MiniMapAlphaDarkmoon = 1,

    -- General single Zone icon scale and alpha
      ZoneGeneralScale = 1.5,
      ZoneGeneralAlpha = 1,
      ZoneScaleMapNotesIcons = 1.5,
      ZoneAlphaMapNotesIcons = 1,
      ZoneScaleHordeAllyIcons = 1.5,
      ZoneAlphaHordeAllyIcons = 1,
      ZoneScaleInnkeeper = 1.5,
      ZoneAlphaInnkeeper = 1,
      ZoneScaleAuctioneer = 1.5,
      ZoneAlphaAuctioneer = 1,
      ZoneScaleBank = 1.5,
      ZoneAlphaBank = 1,
      ZoneScaleBarber = 1.5,
      ZoneAlphaBarber = 1,
      ZoneScaleMailbox = 1.5,
      ZoneAlphaMailbox = 1,
      ZoneScalePvPVendor = 1.5,
      ZoneAlphaPvPVendor = 1,
      ZoneScalePvEVendor = 1.5,
      ZoneAlphaPvEVendor = 1,
      ZoneScaleStablemaster = 1.5,
      ZoneAlphaStablemaster = 1,
      ZoneScaleCatalyst = 1.5,
      ZoneAlphaCatalyst = 1,
      ZoneScaleZidormi = 1.5,
      ZoneAlphaZidormi = 1,
      ZoneScaleTransmogger = 1.5,
      ZoneAlphaTransmogger = 1,
      ZoneScaleItemUpgrade = 1.5,
      ZoneAlphaItemUpgrade = 1,
      ZoneScalePaths = 1.5,
      ZoneAlphaPaths = 1,

      -- General single MiniMap icon scale and alpha
      MiniMapGeneralScale = 1.5,
      MiniMapGeneralAlpha = 1,
      MiniMapScaleHordeAllyIcons = 1.5,
      MiniMapAlphaHordeAllyIcons = 1,
      MiniMapScaleInnkeeper = 1.5,
      MiniMapAlphaInnkeeper = 1,
      MiniMapScaleAuctioneer = 1.5,
      MiniMapAlphaAuctioneer = 1,
      MiniMapScaleBank = 1.5,
      MiniMapAlphaBank = 1,
      MiniMapScaleBarber = 1.5,
      MiniMapAlphaBarber = 1,
      MiniMapScaleMailbox = 1.5,
      MiniMapAlphaMailbox = 1,
      MiniMapScalePvPVendor = 1.5,
      MiniMapAlphaPvPVendor = 1,
      MiniMapScalePvEVendor = 1.5,
      MiniMapAlphaPvEVendor = 1,
      MiniMapScaleStablemaster = 1.5,
      MiniMapAlphaStablemaster = 1,
      MiniMapScaleCatalyst = 1.5,
      MiniMapAlphaCatalyst = 1,
      MiniMapScaleZidormi = 1.5,
      MiniMapAlphaZidormi = 1,
      MiniMapScaleTransmogger = 1.5,
      MiniMapAlphaTransmogger = 1,
      MiniMapScaleItemUpgrade = 1.5,
      MiniMapAlphaItemUpgrade = 1,
      MiniMapScalePaths = 1.5,
      MiniMapAlphaPaths = 1,

      -- Dungeon single icon scale and alpha
      dungeonScale = 2,
      dungeonAlpha = 1,
      DungeonMapScaleExit = 2,
      DungeonMapAlphaExit = 1,
      DungeonMapScalePortal = 2,
      DungeonMapAlphaPortal = 1,
      DungeonMapScalePassage = 2,
      DungeonMapAlphaPassage = 1,
      DungeonMapScaleTransport = 2,
      DungeonMapAlphaTransport = 1,
      DungeonMapScaleVendor = 2,
      DungeonMapAlphaVendor = 1,

    --0 General tab
      journal = true,
      tomtom = true,
      extraInformation = true,
      graySingleID = true,
      grayMultipleID = true,
      CoreChatMassage = true,
      MmbWmbChatMessage = true,
      ChatMassage = false,
      ZoneChanged = true,
      ZoneChangedDetail = false,
      TooltipInformations = true,
      DeleteIcons = false,
      CreateAndCopyLinks = true,
      RestoreAllIcons = false,
      RestoreZoneDeletedIcons = false,
      RestoreContinentDeletedIcons = false,
      RestoreAzerothDeletedIcons = false,
      RestoreDungeonDeletedIcons = false,
      RestoreCapitalsDeletedIcons = false,

    -- 2.0 MiniMap Classic
      minimapScale = 1,
      minimapAlpha = 1,
      zoneScale = 1,
      zoneAlpha = 1,
      instanceScale = 1,
      instanceAlpha = 1,

    --2.1 MiniMap tab
    -- MiniMap Continent
      showMiniMapKalimdor = true,
      showMiniMapEasternKingdom = true,
      showMiniMapOutland = true,
      showMiniMapNorthrend = true,
      showMiniMapPandaria = true,
      showMiniMapDraenor = true,
      showMiniMapBrokenIsles = true,
      showMiniMapZandalar = true,
      showMiniMapKulTiras = true,
      showMiniMapShadowlands = true,
      showMiniMapDragonIsles = true,
      showMiniMapKhazAlgar = true,
    -- MiniMap Instance
      showMiniMapRaids = true,
      showMiniMapDungeons = true,
      showMiniMapMultiple = true,      
      showMiniMapPassage = true,
      showMiniMapOldVanilla = true,
      showMiniMapLFR = true,
    -- MiniMap Transport
      showMiniMapPortals = true,
      showMiniMapZeppelins = true,
      showMiniMapShips = true,
      showMiniMapTransport = true,
      showMiniMapOgreWaygate = true,
      showMiniMapTeleporter = true,
      showMiniMapMirror = true,
      showMiniMapTravel = true,
      showMiniMapDarkmoon = true,
    -- MiniMap Professions
      MiniMapProfessionsScale = 1.5,
      MiniMapProfessionsAlpha = 1,
      showMiniMapProfessionDetection = false,
      showMiniMapProfessionOrders = true,
      showMiniMapAlchemy = true,
      showMiniMapEngineer = true,
      showMiniMapCooking = true,
      showMiniMapFishing = true,
      showMiniMapArchaeology = true,
      showMiniMapMining = true,
      showMiniMapJewelcrafting = true,
      showMiniMapBlacksmith = true,
      showMiniMapLeatherworking = true,
      showMiniMapSkinning = true,
      showMiniMapTailoring = true,
      showMiniMapHerbalism = true,
      showMiniMapInscription = true,
      showMiniMapEnchanting = true,
    -- MiniMap General
      showMiniMapFP = true, -- only Classic+
      showMiniMapGhost = true, -- only Classic+
      showMiniMapMapNotesIcons = false,
      showMiniMapHordeAllyIcons = true,
      showMiniMapInnkeeper = true,
      showMiniMapAuctioneer = true,
      showMiniMapBank = true,
      showMiniMapBarber = true,
      showMiniMapMailbox = true,
      showMiniMapPvPVendor = true,
      showMiniMapPvEVendor = true,
      showMiniMapTransmogger = true,
      showMiniMapStablemaster = true,
      showMiniMapItemUpgrade = true,
      showMiniMapCatalyst = true,
      showMiniMapZidormi = true,
    -- MiniMap Paths
      MiniMapPathsScale = 1.5,
      MiniMapPathsAlpha = 1,
      showMiniMapPaths = true,
      
    --2 Zone map tab
    -- Zone Continent
      showZoneKalimdor = true,
      showZoneEasternKingdom = true,
      showZoneOutland = true,
      showZoneNorthrend = true,
      showZonePandaria = true,
      showZoneDraenor = true,
      showZoneBrokenIsles = true,
      showZoneZandalar = true,
      showZoneKulTiras = true,
      showZoneShadowlands = true,
      showZoneDragonIsles = true,
      showZoneKhazAlgar = true,
    -- Zone Instance
      showZoneRaids = true,
      showZoneDungeons = true,
      showZoneMultiple = true,      
      showZonePassage = true,
      showZoneOldVanilla = true,
      showZoneLFR = true,
    -- Zone Transport

      showZonePortals = true,
      showZoneZeppelins = true,
      showZoneShips = true,
      showZoneTransport = true,
      showZoneOgreWaygate = true,
      showZoneTeleporter = true,
      showZoneMirror = true,
      showZoneTravel = true,
      showZoneDarkmoon = true,
      -- Zone Professions
      ZoneProfessionsScale = 1.5,
      ZoneProfessionsAlpha = 1,
      ZoneProfessionsMixed = true,
      showZoneProfessionDetection = false,
      showZoneProfessionOrders = true,
      showZoneAlchemy = true,
      showZoneEngineer = true,
      showZoneCooking = true,
      showZoneFishing = true,
      showZoneArchaeology = true,
      showZoneMining = true,
      showZoneJewelcrafting = true,
      showZoneBlacksmith = true,
      showZoneLeatherworking = true,
      showZoneSkinning = true,
      showZoneTailoring = true,
      showZoneHerbalism = true,
      showZoneInscription = true,
      showZoneEnchanting = true,
    -- Zone General
      showZoneFP = true, -- Classic+
      showZoneGhost = true, -- Classic+
      showZoneMapNotesIcons = false,
      showZoneHordeAllyIcons = true,
      showZoneInnkeeper = true,
      showZoneAuctioneer = true,
      showZoneBank = true,
      showZoneBarber = true,
      showZoneMailbox = true,
      showZonePvPVendor = true,
      showZonePvEVendor = true,
      showZoneTransmogger = true,
      showZoneStablemaster = true,
      showZoneItemUpgrade = true,
      showZoneCatalyst = true,
      showZoneZidormi = true,
      showZonePaths = true,
      
    --3 Continent map tab
      continentScale = 1.5,
      continentAlpha = 1,
      showContinentMapNotes = true,
      showContinentRaids = true,
      showContinentDungeons = true,
      showContinentPassage = true,
      showContinentMultiple = true,
      showContinentPortals = true,
      showContinentZeppelins = true,
      showContinentShips = true,
      showContinentTransport = true,
      showContinentOldVanilla = true,
      showContinentLFR = true,
      showContinentProfessions = true,
      showContinentDelves = true,
      showContinentPaths = true,
      showContinentFP = true, -- only Classic and Cataclym
      showContinentPvPandPvEVendor = true,
      showContinentKalimdor = true,
      showContinentEasternKingdom = true,
      showContinentOutland = true,
      showContinentNorthrend = true,
      showContinentPandaria = true,
      showContinentDraenor = true,
      showContinentBrokenIsles = true,
      showContinentZandalar = true,
      showContinentKulTiras = true,
      showContinentShadowlands = true,
      showContinentDragonIsles = true,
      showContinentKhazAlgar = true,

      --4 Azeroth map tab
      azerothScale = 1.5,
      azerothAlpha = 1,
      showAzerothMapNotes = true,
      showAzerothRaids = true,
      showAzerothDungeons = true,
      showAzerothPassage = true,
      showAzerothMultiple = true,
      showAzerothPortals = true,
      showAzerothZeppelins = true,
      showAzerothShips = true,
      showAzerothTransport = true,
      showAzerothOldVanilla = true,
      showAzerothLFR = true,
      showAzerothDelves = true,
      showAzerothFP = true, -- only classic +
      showAzerothKalimdor = true,
      showAzerothEasternKingdom = true,
      showAzerothNorthrend = true,
      showAzerothKulTiras = true,
      showAzerothPandaria = true,
      showAzerothBrokenIsles = true,
      showAzerothZandalar = true,
      showAzerothDragonIsles = true,
      showAzerothKhazAlgar = true,

    --5 Cosmos map tab
      cosmosScale = 1.5,
      cosmosAlpha = 1,
      showCosmosKalimdor = true,
      showCosmosEasternKingdom = true,
      showCosmosOutland = true,
      showCosmosNorthrend = true,
      showCosmosPandaria = true,
      showCosmosDraenor = true,
      showCosmosBrokenIsles = true,
      showCosmosZandalar = true,
      showCosmosKulTiras = true,
      showCosmosShadowlands = true,
      showCosmosDragonIsles = true,
      showCosmosKhazAlgar = true,

    --6 Inside Dungeon Map tab
      showDungeonExit = true,
      showDungeonPassage = true,
      showDungeonPortal = true,
      showDungeonTransport = true,
      showDungeonVendor = true,

    --6 Capitals tab
      showCapitals = true,
      showCapitalsOrgrimmar = true,
      showCapitalsThunderBluff = true,
      showCapitalsSilvermoon = true,
      showCapitalsUndercity = true,
      showCapitalsStormwind = true,
      showCapitalsIronforge = true,
      showCapitalsDarnassus = true,
      showCapitalsExodar = true,
      showCapitalsShattrath = true,
      showCapitalsDalaranNorthrend = true,
      showCapitalsDalaranLegion = true,
      showCapitalsSot2M = true,
      showCapitalsSot7S = true,
      showCapitalsStormshield = true,
      showCapitalsWarspear = true,
      showCapitalsDazarAlor = true,
      showCapitalsBoralus = true,
      showCapitalsOribos = true,
      showCapitalsValdrakken = true,
      showCapitalsDornogal = true,
      showCapitalsDarkmoon = true,

    --Capital Instances
      CapitalsInstanceScale = 2,
      CapitalsInstanceAlpha = 1,
      showCapitalsRaids = true,
      showCapitalsDungeons = true,
      showCapitalsInstancePassage = true,
      showCapitalsMultiple = true,

    --Capital Transport
      CapitalsTransportScale = 1.5,
      CapitalsTransportAlpha = 1,
      showCapitalsPortals = true,
      showCapitalsZeppelins = true,
      showCapitalsShips = true,
      showCapitalsTransport = true,
      showCapitalsOldVanilla = true,
      showCapitalsLFR = true,
      showCapitalsFP = true,

    -- Capital Professions
      CapitalsProfessionsScale = 1.5,
      CapitalsProfessionsAlpha = 1,
      showCapitalsProfessionDetection = false,
      showCapitalsProfessionsMixed = true,
      showCapitalsProfessionOrders = true,
      showCapitalsAlchemy = true,
      showCapitalsEngineer = true,
      showCapitalsCooking = true,
      showCapitalsFishing = true,
      showCapitalsArchaeology = true,
      showCapitalsMining = true,
      showCapitalsJewelcrafting = true,
      showCapitalsBlacksmith = true,
      showCapitalsLeatherworking = true,
      showCapitalsSkinning = true,
      showCapitalsTailoring = true,
      showCapitalsHerbalism = true,
      showCapitalsInscription = true,
      showCapitalsEnchanting = true,
      showCapitalsFirstAid = true,

    --Capital General
      CapitalsGeneralScale = 1.5,
      CapitalsGeneralAlpha = 1,
      showCapitalsMapNotes = true,
      showCapitalsInnkeeper = true,
      showCapitalsAuctioneer = true,
      showCapitalsPaths = true,
      showCapitalsBank = true,
      showCapitalsBarber = true,
      showCapitalsTransmogger = true,
      showCapitalsPvPVendor = true,
      showCapitalsPvEVendor = true,
      showCapitalsItemUpgrade = true,
      showCapitalsDragonFlyTransmog = true,
      showCapitalsCatalyst = true,
      showCapitalsMailbox = true,
      showCapitalsGhost = true,
      showCapitalsStablemaster = true,
      showCapitalsTradingPost = true,

    --7 Capitals Minimap
      showMinimapCapitals = true,
      showMinimapCapitalsOrgrimmar = true,
      showMinimapCapitalsThunderBluff = true,
      showMinimapCapitalsSilvermoon = true,
      showMinimapCapitalsUndercity = true,
      showMinimapCapitalsStormwind = true,
      showMinimapCapitalsIronforge = true,
      showMinimapCapitalsDarnassus = true,
      showMinimapCapitalsExodar = true,
      showMinimapCapitalsShattrath = true,
      showMinimapCapitalsDalaranNorthrend = true,
      showMinimapCapitalsDalaranLegion = true,
      showMinimapCapitalsSot2M = true,
      showMinimapCapitalsSot7S = true,
      showMinimapCapitalsStormshield = true,
      showMinimapCapitalsWarspear = true,
      showMinimapCapitalsDazarAlor = true,
      showMinimapCapitalsBoralus = true,
      showMinimapCapitalsOribos = true,
      showMinimapCapitalsValdrakken = true,
      showMinimapCapitalsDornogal = true,
      showMinimapCapitalsDarkmoon = true,

    --Capital Minimap Instances
      MinimapCapitalsInstanceScale = 1.5,
      MinimapCapitalsInstanceAlpha = 1,
      showMinimapCapitalsRaids = true,
      showMinimapCapitalsDungeons = true,
      showMinimapCapitalsInstancePassage = true,
      showMinimapCapitalsMultiple = true,

    --Capital Minimap Transport
      MinimapCapitalsTransportScale = 1.5,
      MinimapCapitalsTransportAlpha = 1,
      showMinimapCapitalsPortals = true,
      showMinimapCapitalsZeppelins = true,
      showMinimapCapitalsShips = true,
      showMinimapCapitalsTransport = true,
      showMinimapCapitalsOldVanilla = true,
      showMinimapCapitalsLFR = true,
      showMinimapCapitalsFP = true,

    -- Capital Minimap Professions
      MinimapCapitalsProfessionsScale = 1.5,
      MinimapCapitalsProfessionsAlpha = 1,
      showMinimapCapitalsProfessionDetection = false,
      showMinimapCapitalsProfessionsMixed = true,
      showMinimapCapitalsProfessionOrders = true,
      showMinimapCapitalsAlchemy = true,
      showMinimapCapitalsEngineer = true,
      showMinimapCapitalsCooking = true,
      showMinimapCapitalsFishing = true,
      showMinimapCapitalsArchaeology = true,
      showMinimapCapitalsMining = true,
      showMinimapCapitalsJewelcrafting = true,
      showMinimapCapitalsBlacksmith = true,
      showMinimapCapitalsLeatherworking = true,
      showMinimapCapitalsSkinning = true,
      showMinimapCapitalsTailoring = true,
      showMinimapCapitalsHerbalism = true,
      showMinimapCapitalsInscription = true,
      showMinimapCapitalsEnchanting = true,
      showMinimapCapitalsFirstAid = true,

    --Capital Minimap General
      MinimapCapitalsGeneralScale = 1.5,
      MinimapCapitalsGeneralAlpha = 1,   
      showMinimapCapitalsMapNotes = true,     
      showMinimapCapitalsInnkeeper = true,
      showMinimapCapitalsAuctioneer = true,
      showMinimapCapitalsPaths = true,
      showMinimapCapitalsBank = true,
      showMinimapCapitalsBarber = true,
      showMinimapCapitalsTransmogger = true,
      showMinimapCapitalsPvPVendor = true,
      showMinimapCapitalsPvEVendor = true,
      showMinimapCapitalsItemUpgrade = true,
      showMinimapCapitalsDragonFlyTransmog = true,
      showMinimapCapitalsCatalyst = true,
      showMinimapCapitalsMailbox = true,
      showMinimapCapitalsGhost = true,
      showMinimapCapitalsStablemaster = true,
      showMinimapCapitalsTradingPost = true,

    --10 ns.Addon.db.profile.activate.
      activate = {
        HideMapNote = false,
        HideMMB = false,
        EnemyFaction = true,
        ShiftWorld = false,
        ClassicIcons = false,
        ClassicPortals = true,
        ClassicShips = true,
        ClassicZeppelin = true,
        ClassicBank = true,
        ClassicProfession = false,
        ClassicClassicProfession = false,
        MapNotesIcons = true,
        RemoveBlizzPOIs = true,
        RemoveBlizzPOIsZidormi = true,
        RemoveBlizzInstances = true,
        ShowBlizzDelves = false,
        FogOfWar = true,
        MistOfTheUnexplored = true,
        FogOfWarAlphaReduce = false,
        SyncZoneAndMinimap = false,
        SyncCapitalsAndMinimap = false,
        ZoneInstanceSyncScaleAlpha = true,
        ZoneTransportSyncScaleAlpha = true,
        ZoneGeneralSyncScaleAlpha = true,
        MiniMapInstanceSyncScaleAlpha = true,        
        MiniMapTransportSyncScaleAlpha = true,
        MiniMapGeneralSyncScaleAlpha = true,
      --MiniMap
        MiniMapEnemyFaction = true,
        MiniMapInstances = true,
        MiniMapTransporting = true,
        MiniMapProfessions = true,
        MiniMapGeneral = true,
        MiniMapPaths = true,
      --Zones
        ZoneEnemyFaction = true,
        ZoneInstances = true,
        ZoneTransporting = true,
        ZoneProfessions = true,
        ZoneGeneral = true,
      --activate tab
        CosmosMap = true,
        Azeroth = true,
        Continent = true,
        ZoneMap = true,
        DungeonMap = true,
        MiniMap = true,
        Capitals = true,
        MinimapCapitals = true,
      --Capitals
        CapitalsEnemyFaction = true,
        CapitalsInstances = true,
        CapitalsTransporting = true,
        CapitalsProfessions = true,
        CapitalsGeneral = true,
      --Capitals Minimap
        MinimapCapitalsEnemyFaction = true,
        MinimapCapitalsInstances = true,
        MinimapCapitalsTransporting = true,
        MinimapCapitalsProfessions = true,
        MinimapCapitalsGeneral = true,
      },

    --11 deleted icons function
      deletedIcons = {

        AzerothDeletedIcons = {
          ['*'] = {},
        },
        ContinentDeletedIcons = {
          ['*'] = {},
        },
        ZoneDeletedIcons = {
          ['*'] = {},
        },
        MinimapZoneDeletedIcons = {
          ['*'] = {},
        },
        DungeonDeletedIcons = {
          ['*'] = {},
        },
        CapitalsDeletedIcons = {
          ['*'] = {},
        },
        MinimapCapitalsDeletedIcons = {
          ['*'] = {},
        },
      },

    --12 FogOfWarColor
      FogOfWarColor = {
        --FogOfWar
          colorR = 1,
          colorG = 1,
          colorB = 1,
          colorA = 1,
          FogOfWarColorR = 1,
          FogOfWarColorG = 0,
          FogOfWarColorB = 0,
          FogOfWarColorA = 1,
          colorR_Reduce = 0.65,
          colorG_Reduce = 0.65,
          colorB_Reduce = 0.65,
          colorA_Reduce = 0.65,
      }
  },
}