local ADDON_NAME, ns = ...

ns.defaults = {

  profile = {

    --0 General tab
      journal = true,
      tomtom = true,
      extraInformation = true,
      assignedgray = true,
      graymultipleID = true,
      CoreChatMassage = true,
      MmbWmbChatMessage = true,
      ChatMassage = false,
      ZoneChanged = true,
      ZoneChangedDetail = false,
      RestoreAllIcons = false,
      RestoreZoneDeletedIcons = false,
      RestoreContinentDeletedIcons = false,
      RestoreAzerothDeletedIcons = false,
      RestoreDungeonDeletedIcons = false,
      RestoreCapitalsDeletedIcons = false,

    -- 2.0 MiniMap Classic
      minimapScale = 1,
      minimapAlpha = 1,
      zoneScale = 1,
      zoneAlpha = 1,
      instanceScale = 1,
      instanceAlpha = 1,

    --2.1 MiniMap tab
    -- MiniMap Continent
      showMiniMapKalimdor = true,
      showMiniMapEasternKingdom = true,
      showMiniMapOutland = true,
      showMiniMapNorthrend = true,
      showMiniMapPandaria = true,
      showMiniMapDraenor = true,
      showMiniMapBrokenIsles = true,
      showMiniMapZandalar = true,
      showMiniMapKulTiras = true,
      showMiniMapShadowlands = true,
      showMiniMapDragonIsles = true,
      showMiniMapKhazAlgar = true,
    -- MiniMap Instance
      MiniMapInstanceScale = 2,
      MiniMapInstanceAlpha = 1,
      showMiniMapRaids = true,
      showMiniMapDungeons = true,
      showMiniMapMultiple = true,      
      showMiniMapPassage = true,
      showMiniMapOldVanilla = true,
      showMiniMapLFR = true,
    -- MiniMap Transport
      MiniMapTransportScale = 1.5,
      MiniMapTransportAlpha = 1,
      showMiniMapPortals = true,
      showMiniMapZeppelins = true,
      showMiniMapShips = true,
      showMiniMapTransport = true,
      showMiniMapOgreWaygate = true,
      showMiniMapTeleporter = true,
      showMiniMapToyTransport = true,
      showMiniMapTravel = true,
    -- MiniMap General
      MiniMapGeneralScale = 1.5,
      MiniMapGeneralAlpha = 1,
      showMiniMapFP = true, -- only Classic+
      showMiniMapGhost = true, -- only Classic+
      showMiniMapInnkeeper = true,
      showMiniMapAuctioneer = true,
      showMiniMapBank = true,
      showMiniMapBarber = true,
      showMiniMapMailbox = true,
      showMiniMapPvPVendor = true,
      showMiniMapPvEVendor = true,
      showMiniMapTransmogger = true,
      showMiniMapStablemaster = true,
      showMiniMapItemUpgrade = true,
      showMiniMapCatalyst = true,
    -- MiniMap Paths
      MiniMapPathsScale = 1.5,
      MiniMapPathsAlpha = 1,
      showMiniMapPaths = true,
      
    --2 Zone map tab
    -- Zone Continent
      showZoneKalimdor = true,
      showZoneEasternKingdom = true,
      showZoneOutland = true,
      showZoneNorthrend = true,
      showZonePandaria = true,
      showZoneDraenor = true,
      showZoneBrokenIsles = true,
      showZoneZandalar = true,
      showZoneKulTiras = true,
      showZoneShadowlands = true,
      showZoneDragonIsles = true,
      showZoneKhazAlgar = true,
    -- Zone Instance
      ZoneInstanceScale = 2,
      ZoneInstanceAlpha = 1,
      showZoneRaids = true,
      showZoneDungeons = true,
      showZoneMultiple = true,      
      showZonePassage = true,
      showZoneOldVanilla = true,
      showZoneLFR = true,
    -- Zone Transport
      ZoneTransportScale = 1.5,
      ZoneTransportAlpha = 1,
      showZonePortals = true,
      showZoneZeppelins = true,
      showZoneShips = true,
      showZoneTransport = true,
      showZoneOgreWaygate = true,
      showZoneTeleporter = true,
      showZoneToyTransport = true,
      showZoneTravel = true,
    -- Zone General
      ZonesGeneralScale = 1.5,
      ZonesGeneralAlpha = 1,
      showZoneFP = true, -- Classic+
      showZoneGhost = true, -- Classic+
      ZoneMapNotesIcons = false,
      showZoneInnkeeper = true,
      showZoneAuctioneer = true,
      showZoneBank = true,
      showZoneBarber = true,
      showZoneMailbox = true,
      showZonePvPVendor = true,
      showZonePvEVendor = true,
      showZoneTransmogger = true,
      showZoneStablemaster = true,
      showZoneItemUpgrade = true,
      showZoneCatalyst = true,
    -- Zone Path
      ZonesPathsScale = 1.5,
      ZonesPathsAlpha = 1,
      showZonePaths = true,
      
    --3 Continent map tab
      continentScale = 1.5,
      continentAlpha = 1,
      showContinentRaids = true,
      showContinentDungeons = true,
      showContinentPassage = true,
      showContinentMultiple = true,
      showContinentPortals = true,
      showContinentZeppelins = true,
      showContinentShips = true,
      showContinentTransport = true,
      showContinentOldVanilla = true,
      showContinentLFR = true,
      showContinentFP = true, -- only Classic and Cataclym
      showContinentPvPandPvEVendor = true,
      showContinentKalimdor = true,
      showContinentEasternKingdom = true,
      showContinentOutland = true,
      showContinentNorthrend = true,
      showContinentPandaria = true,
      showContinentDraenor = true,
      showContinentBrokenIsles = true,
      showContinentZandalar = true,
      showContinentKulTiras = true,
      showContinentShadowlands = true,
      showContinentDragonIsles = true,
      showContinentKhazAlgar = true,

      --4 Azeroth map tab
      azerothScale = 1.5,
      azerothAlpha = 1,
      showAzerothRaids = true,
      showAzerothDungeons = true,
      showAzerothPassage = true,
      showAzerothMultiple = true,
      showAzerothPortals = true,
      showAzerothZeppelins = true,
      showAzerothShips = true,
      showAzerothTransport = true,
      showAzerothOldVanilla = true,
      showAzerothLFR = true,
      showAzerothFP = true, -- only classic +
      showAzerothKalimdor = true,
      showAzerothEasternKingdom = true,
      showAzerothNorthrend = true,
      showAzerothKulTiras = true,
      showAzerothPandaria = true,
      showAzerothBrokenIsles = true,
      showAzerothZandalar = true,
      showAzerothDragonIsles = true,
      showAzerothKhazAlgar = true,

    --5 Cosmos map tab
      cosmosScale = 1.5,
      cosmosAlpha = 1,
      showCosmosKalimdor = true,
      showCosmosEasternKingdom = true,
      showCosmosOutland = true,
      showCosmosNorthrend = true,
      showCosmosPandaria = true,
      showCosmosDraenor = true,
      showCosmosBrokenIsles = true,
      showCosmosZandalar = true,
      showCosmosKulTiras = true,
      showCosmosShadowlands = true,
      showCosmosDragonIsles = true,
      showCosmosKhazAlgar = true,

    --6 Inside Dungeon Map tab
      dungeonScale = 2,
      dungeonAlpha = 1,
      showDungeonExit = true,
      showDungeonPassage = true,
      showDungeonPortal = true,
      showDungeonTransport = true,

    --6 Capitals tab
      showCapitals = true,
      showCapitalsOrgrimmar = true,
      showCapitalsThunderBluff = true,
      showCapitalsSilvermoon = true,
      showCapitalsUndercity = true,
      showCapitalsStormwind = true,
      showCapitalsIronforge = true,
      showCapitalsDarnassus = true,
      showCapitalsExodar = true,
      showCapitalsShattrath = true,
      showCapitalsDalaranNorthrend = true,
      showCapitalsDalaranLegion = true,
      showCapitalsSot2M = true,
      showCapitalsSot7S = true,
      showCapitalsStormshield = true,
      showCapitalsWarspear = true,
      showCapitalsDazarAlor = true,
      showCapitalsBoralus = true,
      showCapitalsOribos = true,
      showCapitalsValdrakken = true,
      showCapitalsDornogal = true,
      showCapitalsDarkmoon = true,

    --Capital Instances
      CapitalsInstanceScale = 2,
      CapitalsInstanceAlpha = 1,
      showCapitalsRaids = true,
      showCapitalsDungeons = true,
      showCapitalsInstancePassage = true,
      showCapitalsMultiple = true,

    --Capital Transport
      CapitalsTransportScale = 1.5,
      CapitalsTransportAlpha = 1,
      showCapitalsPortals = true,
      showCapitalsZeppelins = true,
      showCapitalsShips = true,
      showCapitalsTransport = true,
      showCapitalsOldVanilla = true,
      showCapitalsLFR = true,
      showCapitalsFP = true,

    -- Capital Professions
      CapitalsProfessionsScale = 1.5,
      CapitalsProfessionsAlpha = 1,
      showCapitalsProfessionOrders = true,
      showCapitalsAlchemy = true,
      showCapitalsEngineer = true,
      showCapitalsCooking = true,
      showCapitalsFishing = true,
      showCapitalsArchaeology = true,
      showCapitalsMining = true,
      showCapitalsJewelcrafting = true,
      showCapitalsBlacksmith = true,
      showCapitalsLeatherworking = true,
      showCapitalsSkinning = true,
      showCapitalsTailoring = true,
      showCapitalsHerbalism = true,
      showCapitalsInscription = true,
      showCapitalsEnchanting = true,

    --Capital General
      CapitalsGeneralScale = 1.5,
      CapitalsGeneralAlpha = 1,
      showCapitalsMapNotes = true,
      showCapitalsInnkeeper = true,
      showCapitalsAuctioneer = true,
      showCapitalsPaths = true,
      showCapitalsBank = true,
      showCapitalsBarber = true,
      showCapitalsTransmogger = true,
      showCapitalsPvPVendor = true,
      showCapitalsPvEVendor = true,
      showCapitalsItemUpgrade = true,
      showCapitalsDragonFlyTransmog = true,
      showCapitalsCatalyst = true,
      showCapitalsMailbox = true,
      showCapitalsGhost = true,
      showCapitalsStablemaster = true,
      showCapitalsTradingPost = true,

    --7 Capitals Minimap
      showMinimapCapitals = true,
      showMinimapCapitalsOrgrimmar = true,
      showMinimapCapitalsThunderBluff = true,
      showMinimapCapitalsSilvermoon = true,
      showMinimapCapitalsUndercity = true,
      showMinimapCapitalsStormwind = true,
      showMinimapCapitalsIronforge = true,
      showMinimapCapitalsDarnassus = true,
      showMinimapCapitalsExodar = true,
      showMinimapCapitalsShattrath = true,
      showMinimapCapitalsDalaranNorthrend = true,
      showMinimapCapitalsDalaranLegion = true,
      showMinimapCapitalsSot2M = true,
      showMinimapCapitalsSot7S = true,
      showMinimapCapitalsStormshield = true,
      showMinimapCapitalsWarspear = true,
      showMinimapCapitalsDazarAlor = true,
      showMinimapCapitalsBoralus = true,
      showMinimapCapitalsOribos = true,
      showMinimapCapitalsValdrakken = true,
      showMinimapCapitalsDornogal = true,
      showMinimapCapitalsDarkmoon = true,

    --Capital Minimap Instances
      MinimapCapitalsInstanceScale = 1.5,
      MinimapCapitalsInstanceAlpha = 1,
      showMinimapCapitalsRaids = true,
      showMinimapCapitalsDungeons = true,
      showMinimapCapitalsInstancePassage = true,
      showMinimapCapitalsMultiple = true,

    --Capital Minimap Transport
      MinimapCapitalsTransportScale = 1.5,
      MinimapCapitalsTransportAlpha = 1,
      showMinimapCapitalsPortals = true,
      showMinimapCapitalsZeppelins = true,
      showMinimapCapitalsShips = true,
      showMinimapCapitalsTransport = true,
      showMinimapCapitalsOldVanilla = true,
      showMinimapCapitalsLFR = true,
      showMinimapCapitalsFP = true,

    -- Capital Minimap Professions
      MinimapCapitalsProfessionsScale = 1.5,
      MinimapCapitalsProfessionsAlpha = 1,
      showMinimapCapitalsProfessionOrders = true,
      showMinimapCapitalsAlchemy = true,
      showMinimapCapitalsEngineer = true,
      showMinimapCapitalsCooking = true,
      showMinimapCapitalsFishing = true,
      showMinimapCapitalsArchaeology = true,
      showMinimapCapitalsMining = true,
      showMinimapCapitalsJewelcrafting = true,
      showMinimapCapitalsBlacksmith = true,
      showMinimapCapitalsLeatherworking = true,
      showMinimapCapitalsSkinning = true,
      showMinimapCapitalsTailoring = true,
      showMinimapCapitalsHerbalism = true,
      showMinimapCapitalsInscription = true,
      showMinimapCapitalsEnchanting = true,

    --Capital Minimap General
      MinimapCapitalsGeneralScale = 1.5,
      MinimapCapitalsGeneralAlpha = 1,   
      showMinimapCapitalsMapNotes = true,     
      showMinimapCapitalsInnkeeper = true,
      showMinimapCapitalsAuctioneer = true,
      showMinimapCapitalsPaths = true,
      showMinimapCapitalsBank = true,
      showMinimapCapitalsBarber = true,
      showMinimapCapitalsTransmogger = true,
      showMinimapCapitalsPvPVendor = true,
      showMinimapCapitalsPvEVendor = true,
      showMinimapCapitalsItemUpgrade = true,
      showMinimapCapitalsDragonFlyTransmog = true,
      showMinimapCapitalsCatalyst = true,
      showMinimapCapitalsMailbox = true,
      showMinimapCapitalsGhost = true,
      showMinimapCapitalsStablemaster = true,
      showMinimapCapitalsTradingPost = true,

    --10 ns.Addon.db.profile.activate.
      activate = {
        HideMapNote = false,
        HideMMB = false,
        EnemyFaction = true,
        ShiftWorld = false,
        ClassicIcons = false,
        ClassicPortals = true,
        ClassicShips = true,
        ClassicZeppelin = true,
        ClassicBank = true,
        ClassicProfession = false,
        ClassicClassicProfession = false,
        MapNotesIcons = true,
        RemoveBlizzPOIs = true,
        RemoveBlizzInstances = true,
        FogOfWar = true,
        MistOfTheUnexplored = true,
        FogOfWarAlphaReduce = false,
        SyncZoneAndMinimap = false,
        SyncCapitalsAndMinimap = false,
      --MiniMap
        MiniMapEnemyFaction = true,
        MiniMapInstances = true,
        MiniMapTransporting = true,
        MiniMapGeneral = true,
        MiniMapPaths = true,
      --Zones
        ZoneEnemyFaction = true,
        ZoneInstances = true,
        ZoneTransporting = true,
        ZoneGeneral = true,
        ZonePaths = true,
      --activate tab
        CosmosMap = true,
        Azeroth = true,
        Continent = true,
        ZoneMap = true,
        DungeonMap = true,
        MiniMap = true,
        Capitals = true,
        MinimapCapitals = true,
      --Capitals
        CapitalsEnemyFaction = true,
        CapitalsInstances = true,
        CapitalsTransporting = true,
        CapitalsProfessions = true,
        CapitalsGeneral = true,
      --Capitals Minimap
        MinimapCapitalsEnemyFaction = true,
        MinimapCapitalsInstances = true,
        MinimapCapitalsTransporting = true,
        MinimapCapitalsProfessions = true,
        MinimapCapitalsGeneral = true,
      },

    --11 deleted icons function
      deletedIcons = {

        AzerothDeletedIcons = {
          ['*'] = {},
        },
        ContinentDeletedIcons = {
          ['*'] = {},
        },
        ZoneDeletedIcons = {
          ['*'] = {},
        },
        MinimapZoneDeletedIcons = {
          ['*'] = {},
        },
        DungeonDeletedIcons = {
          ['*'] = {},
        },
        CapitalsDeletedIcons = {
          ['*'] = {},
        },
        MinimapCapitalsDeletedIcons = {
          ['*'] = {},
        },
      },

    --12 FogOfWarColor
      FogOfWarColor = {
        --FogOfWar
          colorR = 1,
          colorG = 1,
          colorB = 1,
          colorA = 1,
          FogOfWarColorR = 1,
          FogOfWarColorG = 0,
          FogOfWarColorB = 0,
          FogOfWarColorA = 1,
          colorR_Reduce = 0.65,
          colorG_Reduce = 0.65,
          colorB_Reduce = 0.65,
          colorA_Reduce = 0.65,
      }
  },

}