-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Strunraan, The Sky's Misery", {
	[383496] = "yellow",
	[385980] = "orange",
	[387199] = "green",
	[387216] = "blue",
	[387265] = "blue",
	[389951] = "red",
})

BigWigs:AddSounds("Strunraan, The Sky's Misery", {
	[383496] = "long",
	[385980] = "alarm",
	[387199] = "info",
	[387216] = "underyou",
	[387265] = "warning",
	[389951] = "alert",
})

BigWigs:AddColors("Basrikron, The Shale Wing", {
	[385137] = {"blue","purple"},
	[385270] = "orange",
	[386059] = "yellow",
	[386259] = "red",
})

BigWigs:AddSounds("Basrikron, The Shale Wing", {
	[385137] = {"alarm","alert","warning"},
	[385270] = "alarm",
	[386259] = "long",
})

BigWigs:AddColors("Bazual, The Dreaded Flame", {
	[389431] = "orange",
	[389514] = "red",
	[389725] = "yellow",
	[390635] = "orange",
	[391247] = "cyan",
})

BigWigs:AddSounds("Bazual, The Dreaded Flame", {
	[389431] = "alert",
	[389514] = "warning",
	[389725] = "alarm",
	[390635] = "alert",
	[391247] = "long",
})

BigWigs:AddColors("Liskanoth, The Futurebane", {
	[389960] = "blue",
	[391026] = {"red","yellow"},
})

BigWigs:AddSounds("Liskanoth, The Futurebane", {
	[389960] = "alert",
	[391026] = {"long","warning"},
})

BigWigs:AddColors("The Zaqali Elders", {
	[402793] = "purple",
	[402824] = "blue",
	[402983] = "orange",
	[402985] = "red",
	[403384] = "blue",
	[403772] = "purple",
	[403779] = "blue",
	[404171] = "red",
})

BigWigs:AddSounds("The Zaqali Elders", {
	[402793] = "alert",
	[402824] = "alarm",
	[402983] = "long",
	[402985] = "warning",
	[403384] = "underyou",
	[403772] = "alert",
	[403779] = "alarm",
	[404171] = "warning",
})

BigWigs:AddColors("Aurostor", {
	[420895] = {"blue","purple"},
	[420925] = "red",
	[421059] = "yellow",
	[421260] = {"blue","green"},
})

BigWigs:AddSounds("Aurostor", {
	[420895] = "warning",
	[420925] = "long",
	[421059] = "info",
	[421260] = "warning",
})
