-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("High Priestess Jeklik", {
	[12097] = {"blue","purple"},
	[16098] = {"green","red"},
	[23952] = {"blue","orange"},
	[23953] = {"green","yellow"},
	[23954] = {"green","red"},
	[23970] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Priestess Jeklik", {
	[16098] = "warning",
	[23953] = "alert",
	[23954] = "warning",
	[23970] = "underyou",
	["stages"] = "info",
})

BigWigs:AddColors("High Priest Venoxis", {
	[8269] = "orange",
	[23860] = "yellow",
	[23861] = {"blue","red"},
	[23865] = {"blue","yellow"},
	[23895] = {"green","orange"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("High Priest Venoxis", {
	[8269] = "long",
	[23861] = {"alarm","underyou"},
	[23895] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("High Priestess Mar'li", {
	[24083] = "yellow",
	[24099] = "yellow",
	[24300] = {"blue","orange"},
})

BigWigs:AddSounds("High Priestess Mar'li", {
	[24083] = "info",
	[24099] = "alarm",
	[24300] = "alert",
})

BigWigs:AddColors("High Priest Thekal", {
	[8269] = "red",
	[12540] = {"blue","purple"},
	[21060] = {"blue","purple"},
	[22666] = {"blue","yellow"},
	[22859] = {"blue","purple"},
	[24183] = "yellow",
	[24185] = "orange",
	[24189] = "orange",
	[24208] = "red",
})

BigWigs:AddSounds("High Priest Thekal", {
	[8269] = "alarm",
	[12540] = "warning",
	[21060] = "warning",
	[22666] = "alert",
	[22859] = "alarm",
	[24183] = "info",
	[24185] = "alert",
	[24208] = "alert",
})

BigWigs:AddColors("High Priestess Arlokk", {
	[12540] = {"blue","purple"},
	[24210] = {"blue","red"},
	[24212] = {"blue","orange"},
})

BigWigs:AddSounds("High Priestess Arlokk", {
	[12540] = "warning",
	[24210] = "alarm",
	[24212] = "alert",
})

BigWigs:AddColors("Hakkar", {
	[24324] = {"orange","red"},
	[24327] = {"blue","yellow"},
})

BigWigs:AddSounds("Hakkar", {
	[24324] = {"alarm","long"},
	[24327] = "info",
})

BigWigs:AddColors("Bloodlord Mandokir", {
	[16856] = {"blue","purple"},
	[24314] = {"blue","yellow"},
	[24318] = {"blue","red"},
})

BigWigs:AddSounds("Bloodlord Mandokir", {
	[16856] = "warning",
	[24314] = "info",
	[24318] = "alarm",
})

BigWigs:AddColors("Jin'do the Hexxer", {
	[17172] = {"blue","purple"},
	[24262] = "red",
	[24306] = {"blue","yellow"},
	[24309] = "orange",
	[24466] = {"blue","yellow"},
})

BigWigs:AddSounds("Jin'do the Hexxer", {
	[17172] = "alert",
	[24262] = "warning",
	[24306] = "alarm",
	[24309] = "info",
	[24466] = "long",
})

BigWigs:AddColors("Gahz'ranka", {
	[21099] = "yellow",
	[22421] = "orange",
})

BigWigs:AddSounds("Gahz'ranka", {
	[21099] = "info",
	[22421] = "alarm",
})

BigWigs:AddColors("Edge of Madness", {
	[24646] = "orange",
	[24699] = "orange",
	[24729] = "orange",
	[26550] = "yellow",
})

BigWigs:AddSounds("Edge of Madness", {
	[24646] = "alarm",
	[24699] = "alert",
	[24729] = "alarm",
	[26550] = "info",
})
