-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Matron Folnuna", {
	[247361] = {"blue","cyan"},
	[247379] = {"blue","orange"},
	[247443] = "red",
	[254147] = "yellow",
})

BigWigs:AddSounds("Matron Folnuna", {
	[247361] = "alarm",
	[247379] = {"long","warning"},
	[247443] = "alarm",
	[254147] = "alert",
})

BigWigs:AddColors("Mistress Alluradel", {
	[247517] = "blue",
	[247544] = {"blue","orange"},
	[247549] = "orange",
	[247604] = "yellow",
})

BigWigs:AddSounds("Mistress Alluradel", {
	[247517] = "info",
	[247544] = "alert",
	[247549] = "warning",
	[247604] = "alarm",
})

BigWigs:AddColors("Inquisitor Meto", {
	[247492] = {"blue","yellow"},
	[247495] = {"blue","yellow"},
	[247585] = {"green","orange"},
	[247632] = "blue",
})

BigWigs:AddSounds("Inquisitor Meto", {
	[247492] = {"alarm","alert"},
	[247495] = {"alert","warning"},
	[247585] = {"info","long"},
	[247632] = "alarm",
})

BigWigs:AddColors("Sothanar", {
	[247410] = {"blue","cyan","red"},
	[247416] = "yellow",
	[247437] = {"blue","orange"},
	[247698] = "yellow",
})

BigWigs:AddSounds("Sothanar", {
	[247410] = {"alarm","info","warning"},
	[247416] = "alert",
	[247437] = "warning",
	[247698] = "long",
})

BigWigs:AddColors("Occularus", {
	[247318] = {"blue","red"},
	[247320] = "orange",
	[247325] = "yellow",
	[247332] = {"blue","yellow"},
	[247393] = {"blue","cyan"},
})

BigWigs:AddSounds("Occularus", {
	[247318] = "alarm",
	[247320] = "warning",
	[247325] = "info",
	[247332] = {"alarm","alert"},
	[247393] = {"alarm","long"},
})

BigWigs:AddColors("Pit Lord Vilemus", {
	[247731] = "red",
	[247733] = "orange",
	[247739] = {"blue","cyan","yellow"},
})

BigWigs:AddSounds("Pit Lord Vilemus", {
	[247731] = "long",
	[247733] = "warning",
	[247739] = {"alarm","alert"},
})
