-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Al'ar", {
	[35181] = {"orange","red"},
	[35383] = "blue",
	[35410] = {"blue","red"},
})

BigWigs:AddSounds("Al'ar", {
	[35181] = "alert",
	[35383] = "alarm",
	[35410] = "long",
})

BigWigs:AddColors("Void Reaver", {
	[25778] = {"blue","green"},
	[34172] = {"blue","yellow"},
})

BigWigs:AddSounds("Void Reaver", {
	[25778] = "alarm",
	[34172] = "alert",
})

BigWigs:AddColors("High Astromancer Solarian", {
	[42783] = {"blue","yellow"},
	["phase"] = {"green","red"},
	["split"] = "red",
})

BigWigs:AddSounds("High Astromancer Solarian", {
})

BigWigs:AddColors("Kael'thas Sunstrider", {
	[37018] = {"blue","yellow"},
	[37027] = {"blue","yellow"},
	[44863] = {"orange","yellow"},
	["gaze"] = {"blue","red"},
	["mc"] = {"blue","red"},
	["phase"] = {"green","red","yellow"},
	["pyro"] = {"green","yellow"},
	["rebirth"] = {"orange","yellow"},
})

BigWigs:AddSounds("Kael'thas Sunstrider", {
	["mc"] = "alert",
})
