-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Azuregos", {
	[21097] = "orange",
	[21099] = "orange",
	[21147] = "yellow",
	[22067] = {"green","red"},
})

BigWigs:AddSounds("Azuregos", {
	[21097] = "alert",
	[21099] = "alert",
	[21147] = "alarm",
	[22067] = {"info","warning"},
})

BigWigs:AddColors("Lord Kazzak", {
	[21056] = {"blue","yellow"},
	[21063] = {"blue","orange"},
})

BigWigs:AddSounds("Lord Kazzak", {
	[21056] = "warning",
	[21063] = "alarm",
})

BigWigs:AddColors("Emeriss", {
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
	[24871] = "blue",
	[24910] = "red",
	[24928] = {"blue","orange"},
})

BigWigs:AddSounds("Emeriss", {
	[24814] = "info",
	[24818] = "warning",
	[24871] = "underyou",
	[24910] = {"alarm","long"},
	[24928] = "alert",
})

BigWigs:AddColors("Lethon", {
	[24811] = "red",
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
	[24821] = "yellow",
})

BigWigs:AddSounds("Lethon", {
	[24811] = "long",
	[24814] = "info",
	[24818] = "warning",
	[24821] = "alert",
})

BigWigs:AddColors("Taerar", {
	[22686] = "orange",
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
	[24841] = "cyan",
})

BigWigs:AddSounds("Taerar", {
	[24814] = "info",
	[24818] = "warning",
	[24841] = "long",
})

BigWigs:AddColors("Ysondre", {
	[24795] = "cyan",
	[24814] = "green",
	[24818] = {"blue","purple","yellow"},
})

BigWigs:AddSounds("Ysondre", {
	[24795] = "long",
	[24814] = "info",
	[24818] = "warning",
})
