-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Patchwerk", {
	[28131] = "orange",
})

BigWigs:AddSounds("Patchwerk", {
	[28131] = "long",
})

BigWigs:AddColors("Grobbulus", {
	[28169] = {"blue","red"},
	[28240] = "yellow",
	["adds"] = "orange",
})

BigWigs:AddSounds("Grobbulus", {
	[28169] = "warning",
	[28240] = "info",
	["adds"] = "long",
})

BigWigs:AddColors("Gluth", {
	[25646] = {"blue","purple"},
	[28371] = {"green","orange"},
	[28375] = "red",
	[29306] = "blue",
	[29685] = "yellow",
})

BigWigs:AddSounds("Gluth", {
	[25646] = "info",
	[28371] = "alert",
	[28375] = "warning",
	[29685] = "long",
})

BigWigs:AddColors("Thaddius", {
	[28059] = "blue",
	[28084] = "blue",
	[28089] = "orange",
	[28134] = "red",
	[28338] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Thaddius", {
	[28059] = "warning",
	[28084] = "warning",
	[28089] = "long",
	[28338] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Noth the Plaguebringer", {
	[29208] = "yellow",
	[29212] = "blue",
	[29213] = {"green","red"},
	[29214] = "red",
	["adds"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Noth the Plaguebringer", {
	[29208] = "alert",
	[29213] = "warning",
	[29214] = "alarm",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Heigan the Unclean", {
	[29998] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Heigan the Unclean", {
	[29998] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Loatheb", {
	[29184] = "blue",
	[29204] = "red",
	[29232] = "blue",
	[29234] = "red",
	[29865] = "yellow",
	[30281] = "orange",
	[1225419] = "blue",
})

BigWigs:AddSounds("Loatheb", {
	[29184] = "long",
	[29204] = "warning",
	[29234] = "info",
	[30281] = "alert",
	[1225419] = "long",
})

BigWigs:AddColors("Anub'Rekhan", {
	[28783] = {"blue","yellow"},
	[28785] = {"green","orange","red","yellow"},
})

BigWigs:AddSounds("Anub'Rekhan", {
	[28783] = {"alert","warning"},
	[28785] = {"info","long"},
})

BigWigs:AddColors("Grand Widow Faerlina", {
	[28732] = "yellow",
	[28794] = "blue",
	[28796] = "orange",
	[28798] = {"green","red"},
	[30225] = "blue",
})

BigWigs:AddSounds("Grand Widow Faerlina", {
	[28732] = "info",
	[28794] = "underyou",
	[28796] = "alert",
	[28798] = "warning",
})

BigWigs:AddColors("Maexxna", {
	[28622] = {"blue","yellow"},
	[28747] = "orange",
	[28776] = {"blue","green","purple"},
	[29484] = "red",
	["adds"] = "yellow",
})

BigWigs:AddSounds("Maexxna", {
	[28622] = "alert",
	[28747] = "warning",
	[28776] = "info",
	[29484] = "long",
})

BigWigs:AddColors("Instructor Razuvious", {
	[29060] = "orange",
	[29061] = "yellow",
	[29107] = "red",
})

BigWigs:AddSounds("Instructor Razuvious", {
	[29060] = "info",
	[29061] = "long",
	[29107] = "warning",
})

BigWigs:AddColors("Gothik the Harvester", {
	["add_death"] = "green",
	["adds"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Gothik the Harvester", {
	["stages"] = {"info","long"},
})

BigWigs:AddColors("The Four Horsemen", {
	[28863] = {"blue","orange"},
	[28883] = "yellow",
	[28884] = "red",
	[29061] = "yellow",
	["mark"] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Four Horsemen", {
	[28863] = {"alarm","underyou"},
	[28883] = "alert",
	[28884] = "info",
	[29061] = "long",
	["mark"] = "warning",
})

BigWigs:AddColors("Sapphiron", {
	[28522] = {"blue","yellow"},
	[28524] = "red",
	[28542] = {"green","orange"},
	[28547] = "blue",
	[1219728] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Sapphiron", {
	[28524] = "warning",
	[28542] = "alert",
	[28547] = "underyou",
	[1219728] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Kel'Thuzad", {
	[27808] = {"blue","yellow"},
	[27810] = {"blue","red"},
	[27819] = {"blue","yellow"},
	[28410] = {"blue","orange"},
	[28467] = {"blue","purple"},
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kel'Thuzad", {
	[27808] = "alert",
	[27810] = "warning",
	[27819] = "warning",
	[28410] = "long",
	["adds"] = "info",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Naxxramas Trash", {
	[1219235] = {"blue","yellow"},
})

BigWigs:AddSounds("Naxxramas Trash", {
	[1219235] = "warning",
})
