local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'DemonHunter-Devourer','Unknown-Unknown','Warrior-Fury','Warrior-Arms','Warrior-Protection','Mage-Frost','Druid-Balance','Monk-Mistweaver','Rogue-Subtlety','Shaman-Restoration','Priest-Shadow','Priest-Holy','DeathKnight-Unholy','DeathKnight-Blood','Evoker-Devastation','Shaman-Elemental','Warlock-Demonology','Warlock-Affliction','Hunter-Marksmanship','Hunter-BeastMastery','Warlock-Destruction','Rogue-Assassination','Priest-Discipline','Paladin-Holy','Druid-Feral','Druid-Restoration','Druid-Guardian','Paladin-Retribution','Evoker-Preservation','Evoker-Augmentation','DemonHunter-Havoc','Monk-Brewmaster','Paladin-Protection','Monk-Windwalker','Shaman-Enhancement','DeathKnight-Frost','Mage-Fire',}
local provider = {region='CN',realm='阿纳克洛斯',name='CN',type='weekly',zone=46,date='2026-04-25',data={Ai='Aiolos:BAAALgAECgcJCwAAAA==.',
Al='Alexty:BAABLgAECn8aAAIBAAcJ/SOMCQD9AQABAAcJ/SOMCQD9AQAAAA==.Altora:BAAALgAECgcJCgAAAA==.',
Ap='Apt:BAAALgAECgEJAQABLgAFFAIJBAACAAAAAA==.',
Ar='Art:BAAALgADCgEJAQAAAA==.',
As='Asuralaya:BAAALgAECgEJAQAAAA==.',
Ba='Bamberg:BAAALgAFFAEJAQAAAA==.',
Be='Beundake:BAAALgAFFAQJBAAAAA==.',
Bi='Biubiibiu:BAAALgAECgcJBwAAAA==.',
Bl='Bloodysaint:BAAALgAECgMJAwAAAA==.',
Bu='Bunedake:BAAALgAFFAIJBAAAAA==.',
Ch='Chb:BAABLgAECn8WAAQDAAgJkhKBLwDyAQADAAgJOxKBLwDyAQAEAAEJJQh+RAAvAAAFAAEJEgLcTQAiAAAAAA==.',
Co='Coffeemate:BAAALgAECgYJEAAAAA==.Contentment:BAAALgAECgQJBAAAAA==.',
Cr='Creasy:BAAALgAECgYJDQAAAA==.Creater:BAAALgAECgEJAQAAAA==.',
Da='Damonhunter:BAAALgAECgYJEgABLgAFFAQJBwAGAEsTAA==.Darklight:BAAALgAECgYJBgAAAA==.',
De='Devilnut:BAAALgAECgEJAQAAAA==.',
Dr='Draa:BAAALgAECgkJCQAAAA==.',
En='Endlessroad:BAABLgAFFH8MAAIHAAQJ/QwACwA7AQAHAAQJ/QwACwA7AQAAAA==.',
Ev='Eviles:BAAALgAECgMJAwAAAA==.',
Fa='Faceshoot:BAAALgAECgQJBAAAAA==.',
Fl='Flareup:BAAALgAFFAcJAQAAAA==.Flyingdoge:BAEALgAFFAQJBAABLgAFFAYJDAAIAAAlAA==.',
Fy='Fywoo:BAAALgAECgQJCQAAAA==.',
Fz='Fzz:BAACLgAFFH8MAAIJAAUJWxgRAgDkAQAJAAUJWxgRAgDkAQAuAAQKfxUAAgkACQmtGP8EAEUDAAkACQmtGP8EAEUDAAEuAAUUBgkJAAkAsxAA.',
Ga='Garychees:BAAALgAECgcJDQAAAA==.',
Gl='Glockiebae:BAAALgAFFAIJAwAAAA==.',
Gu='Gust:BAAALgAECgcJCAAAAA==.',
Ha='Halo:BAAALgADCgYJBgAAAA==.Hangao:BAAALgAECgIJAgAAAA==.',
He='Heloisea:BAACLgAFFH8bAAIKAAYJACYRAACaAgAKAAYJACYRAACaAgAuAAQKfyEAAgoACQkRJRwBAJADAAoACQkRJRwBAJADAAAA.Heloised:BAAALgAFFAEJAQAAAA==.',
Ii='Iiliiliil:BAAALgAFFAEJAQAAAA==.',
Il='Illusion:BAAALgAFFAEJAQAAAA==.Iloi:BAAALgAFFAEJAQAAAA==.',
In='Inochi:BAAALgADCgEJAQAAAA==.',
Is='Iskyl:BAAALgAECgYJCwAAAA==.',
Jz='Jzz:BAABLgAFFH8JAAIJAAUJKxgWAwDLAQAJAAUJKxgWAwDLAQABLgAFFAYJCQAJALMQAA==.',
Ki='Kirin:BAAALgAECgYJBgAAAA==.',
Ku='Kumo:BAAALgAFFAMJAwAAAA==.',
Ky='Kyper:BAAALgAECgcJBwAAAA==.',
Kz='Kzz:BAACLgAFFH8GAAIJAAQJ0A8pBABPAQAJAAQJ0A8pBABPAQAuAAQKfxgAAgkACQkeFx4PALACAAkACQkeFx4PALACAAEuAAUUBgkJAAkAsxAA.',
La='Laureg:BAAALgAECgUJBgAAAA==.Laverite:BAAALgAECgEJAQAAAA==.',
Lo='Lopezz:BAAALgAECgEJAQAAAA==.',
Lu='Lucisky:BAAALgAECgQJCQAAAA==.Lumosly:BAABLgAECn8VAAIGAAYJIx9PXQAiAgAGAAYJIx9PXQAiAgAAAA==.',
Lx='Lxyst:BAACLgAFFH8fAAILAAcJ7SEIAABwAgALAAcJ7SEIAABwAgAuAAQKfyAAAgsACQncJcAAANgDAAsACQncJcAAANgDAAAA.',
Ma='Manba:BAAALgAFFAEJAQAAAA==.Manxuefs:BAACLgAFFH8GAAIGAAMJyBaOFAAQAQAGAAMJyBaOFAAQAQAuAAQKfxgAAgYACAmZH5AmANgCAAYACAmZH5AmANgCAAAA.Manxuesm:BAAALgAECgQJBAAAAA==.Manxuews:BAAALgAECgIJAgAAAA==.',
Me='Mengmengdà:BAAALgAECgkJCQAAAA==.',
Mh='Mhyi:BAAALgAECgQJBwAAAA==.',
Mi='Michinen:BAAALgAECgIJAgAAAA==.Michines:BAAALgAECgQJBAAAAA==.Misskin:BAAALgAFFAMJAwAAAA==.',
Mo='Mollyz:BAAALgAECgYJBgAAAA==.',
Ms='Msmm:BAACLgAFFH8FAAIMAAIJxRXfBgCjAAAMAAIJxRXfBgCjAAAuAAQKfxYAAgwABwnOIkUJALcCAAwABwnOIkUJALcCAAAA.',
Mu='Muscularlee:BAAALgADCgYJAgAAAA==.',
Nt='Ntrslayer:BAACLgAFFH8OAAINAAQJWiURAwCCAQANAAQJWiURAwCCAQAuAAQKfyMAAg0ABwn8JJAZAOMCAA0ABwn8JJAZAOMCAAAA.',
Oc='Ocabbage:BAAALgADCgMJAwABLgAFFAIJBQAMAMUVAA==.Ocaptain:BAAALgAECgcJBwAAAA==.',
Or='Orlock:BAAALgAECgcJDQABLgAFFAEJAQACAAAAAA==.',
Oz='Ozoz:BAABLgAECn8WAAMNAAkJiiFWBgByAwANAAkJaSFWBgByAwAOAAcJdiA5EgDoAQAAAA==.Ozz:BAABLgAFFH8HAAIJAAUJ2hCfAwBcAQAJAAUJ2hCfAwBcAQABLgAFFAYJCQAJALMQAA==.',
Pe='Penelòpe:BAAALgAECgcJEwAAAA==.Perthx:BAABLgAECn8WAAIPAAcJMxh9DQACAgAPAAcJMxh9DQACAgAAAA==.',
Ph='Phoenix:BAAALgAFFAIJAgAAAA==.',
Pl='Playerzskfqt:BAAALgAECgcJCAAAAA==.',
Ra='Rangeer:BAAALgAECgQJBAAAAA==.',
Re='Resphoina:BAAALgAECgYJCQAAAA==.Resurgam:BAAALgAECgQJBAAAAA==.',
Rf='Rflens:BAAALgADCgEJAQAAAA==.',
Ro='Ros:BAAALgAECgIJAgAAAA==.',
Rz='Rzz:BAAALgAECgkJDwABLgAFFAYJCQAJALMQAA==.',
Sa='Sadgytty:BAACLgAFFH8dAAMEAAYJfyQeAABqAgAEAAYJWSQeAABqAgADAAUJ8x5dAQDzAQAuAAQKfxwAAwMACQnEJSkEAGgDAAMACAlcJikEAGgDAAQAAwlBJL0WAEcBAAAA.Samurai:BAABLgAECn8oAAMKAAgJhR8bAwB4AgAKAAgJhR8bAwB4AgAQAAcJGBzVGgA8AgAAAA==.Santaalter:BAAALgADCgcJBwAAAA==.',
Se='Sevencat:BAAALgAFFAMJAwAAAA==.Sevenpurple:BAAALgAECgQJBAAAAA==.Sevenqaq:BAABLgAFFH8HAAMRAAQJCyI8DAAvAQARAAMJWSI8DAAvAQASAAEJIyG6AgBkAAAAAA==.Seventtd:BAAALgAFFAQJBAAAAA==.Seventvt:BAAALgAFFAQJBAAAAA==.',
Sh='Shge:BAAALgAFFAMJBAAAAA==.Shiningbaby:BAAALgAECgIJAwAAAA==.',
Si='Siwei:BAAALgAECgcJDwAAAA==.',
So='Sooniy:BAAALgAECgYJCwAAAA==.',
Sp='Spiritdonk:BAABLgAECn8UAAIRAAYJLxCHhQBPAQARAAYJLxCHhQBPAQAAAA==.Spread:BAABLgAFFH8GAAMTAAMJcReLHACkAAATAAIJ9haLHACkAAAUAAEJZxgYIABhAAAAAA==.',
Su='Suar:BAAALgAECgcJBwAAAA==.Sugardemon:BAAALgAECgMJBgAAAA==.Sunchine:BAAALgADCgYJBgAAAA==.Superritter:BAAALgAECgcJAgAAAA==.Surgrey:BAAALgAECgcJCwAAAA==.',
Sv='Svene:BAAALgAECgEJAQAAAA==.',
Ta='Taltarlos:BAAALgAECgQJBAAAAA==.',
Tr='Trashspriest:BAABLgAECn8XAAMRAAgJEhRkSgDqAQARAAgJEhRkSgDqAQAVAAEJAABufwAXAAABLgAFFAcJHwALAO0hAA==.',
Us='Usazz:BAAALgAECgYJBgAAAA==.',
Uz='Uzz:BAABLgAFFH8MAAIJAAQJEBTYAgBqAQAJAAQJEBTYAgBqAQABLgAFFAYJCQAJALMQAA==.',
Vi='Vii:BAAALgAECgQJBAAAAA==.',
Vo='Voidbarrier:BAAALgAECgkJEAAAAA==.',
Wa='Waitinglx:BAAALgAECgEJAQAAAA==.',
Wi='Winnerlight:BAAALgAECgMJAwAAAA==.',
Xg='Xgdnmd:BAAALgAECgYJBgAAAA==.',
Ye='Yes:BAAALgAECgEJAQAAAA==.',
Ys='Yseult:BAAALgAECgMJAwAAAA==.',
Yz='Yzz:BAABLgAFFH8IAAIJAAQJlRW+AwBZAQAJAAQJlRW+AwBZAQABLgAFFAYJCQAJALMQAA==.',
Za='Zandalar:BAAALgAECgYJBwAAAA==.',
Ze='Zeroz:BAAALgAFFAEJAgAAAA==.',
Zh='Zhazha:BAAALgAFFAIJAwAAAA==.',
Zj='Zjxevoker:BAAALgAFFAEJAQAAAA==.',
['一串']='一串糖葫芦:BAAALgAECgYJCgAAAA==.',
['一只']='一只小灰兔:BAAALgAECgUJBQAAAA==.一只小红兔:BAACLgAFFH8WAAIKAAYJ/h8lAAAtAgAKAAYJ/h8lAAAtAgAuAAQKfxYAAgoACAkKJB8GABADAAoACAkKJB8GABADAAAA.一只小青兔:BAAALgADCgQJBAABLgAFFAYJFgAKAP4fAA==.',
['一处']='一处相思:BAACLgAFFH8aAAMWAAYJ8BoJAAACAgAWAAYJ8BoJAAACAgAJAAUJbgivBACiAQAuAAQKfxcAAxYACQmuF+QCALYCABYACQmuF+QCALYCAAkAAgkVF2NUAIcAAAAA.',
['一岁']='一岁就乖:BAAALgAECgcJCAAAAA==.',
['一把']='一把小铁锤:BAAALgAECgIJAgAAAA==.',
['一木']='一木易子一:BAAALgAFFAIJAgABLgAFFAUJAgACAAAAAA==.一木木子一:BAAALgADCgQJBAAAAA==.',
['一枪']='一枪兔:BAAALgADCgIJAgAAAA==.',
['一瓶']='一瓶三块五:BAAALgADCgcJBwAAAA==.',
['一群']='一群小骚猪丶:BAACLgAFFH8MAAIMAAQJShg7AwAfAQAMAAQJShg7AwAfAQAuAAQKfyAAAwwACQlfHzoEABEDAAwACQlfHzoEABEDABcAAgnGCnxNAFwAAAAA.',
['七只']='七只老瞎眼:BAABLgAFFH8IAAIBAAQJdBInEQBGAQABAAQJdBInEQBGAQAAAA==.',
['七夜']='七夜雪:BAAALgAECgQJBQAAAA==.',
['七月']='七月不再:BAAALgAFFAIJBAAAAA==.',
['三只']='三只老瞎眼:BAABLgAFFH8IAAIBAAQJARiiDQBjAQABAAQJARiiDQBjAQAAAA==.',
['三杯']='三杯酒酒仙:BAAALgAECgEJAQAAAA==.',
['三鹿']='三鹿供应商:BAAALgAECgEJAQAAAA==.三鹿开发商:BAAALgADCgUJBwAAAA==.三鹿毒奶丶:BAAALgAFFAEJAQAAAA==.',
['下炕']='下炕认识鞋丶:BAAALgADCgcJBwAAAA==.',
['下饭']='下饭且八碗:BAAALgAECgYJCgAAAA==.',
['不喝']='不喝冰美式:BAAALgAECgYJDwAAAA==.',
['不知']='不知年:BAABLgAFFH8FAAIYAAIJ9g+LFQCVAAAYAAIJ9g+LFQCVAAAAAA==.',
['不高']='不高兴丶烦恼:BAAALgAECgUJBgAAAA==.',
['丑时']='丑时做梦:BAAALgAECgYJCgAAAA==.',
['专家']='专家:BAAALgAECgQJCgAAAA==.',
['世界']='世界级松露:BAAALgAECgEJAwAAAA==.',
['两京']='两京十三省:BAAALgAECgYJBwAAAA==.',
['丨丶']='丨丶苏妲己:BAAALgAECgEJAQAAAA==.',
['丨伊']='丨伊利叨:BAAALgAECgYJEgAAAA==.',
['丨北']='丨北辰之月丶:BAAALgAECgQJBwAAAA==.',
['丨卡']='丨卡皮巴拉丨:BAAALgAECgEJAQAAAA==.',
['丨媚']='丨媚娘丨:BAAALgAECgYJAgAAAA==.',
['丨小']='丨小红手丨:BAAALgAECgEJAQAAAA==.',
['丨拉']='丨拉比克丨:BAAALgAFFAIJAwAAAA==.',
['丨掐']='丨掐指一算丨:BAAALgAECgEJAQAAAA==.',
['丨旋']='丨旋涡丨:BAAALgAECgEJAQAAAA==.',
['丨术']='丨术丝丨:BAAALgAECgUJBQAAAA==.',
['丨松']='丨松本乱菊丨:BAAALgAFFAIJAgAAAA==.',
['丨泠']='丨泠丶鸢灬:BAAALgAECgQJBAAAAA==.',
['丨玖']='丨玖玥丨:BAAALgAECgMJAwAAAA==.',
['丨生']='丨生如夏花:BAAALgAECgcJCgAAAA==.',
['丨鹑']='丨鹑火之影丨:BAAALgAECgIJAgAAAA==.',
['丨麻']='丨麻丨木丨:BAAALgAFFAEJAgAAAA==.',
['丶不']='丶不能说:BAAALgAECgMJBwAAAA==.',
['丶兮']='丶兮爷:BAAALgAECgUJCAAAAA==.',
['丶冷']='丶冷冰冰:BAAALgADCgIJAgAAAA==.',
['丶勾']='丶勾云缕:BAAALgAECgYJBgAAAA==.',
['丶大']='丶大板牙:BAABLgAECn8ZAAMUAAkJah/0AADxAgAUAAkJ7h30AADxAgATAAkJ3BroDQDSAgAAAA==.',
['丶天']='丶天佑聖靈丶:BAAALgAECgYJCwAAAA==.',
['丶寒']='丶寒凌:BAAALgAECgEJAQAAAA==.丶寒幻:BAAALgAECgUJBQAAAA==.丶寒戰:BAAALgAECgQJBAAAAA==.丶寒殇:BAAALgAECgYJDQAAAA==.丶寒雾:BAAALgADCgkJCQAAAA==.丶寒霜:BAAALgAECgMJAwAAAA==.',
['丶小']='丶小奶牛:BAAALgADCgcJBwAAAA==.',
['丶布']='丶布琳:BAAALgAECgQJBAAAAA==.',
['丶张']='丶张起灵:BAAALgAFFAIJAgAAAA==.',
['丶愤']='丶愤怒的胸毛:BAAALgADCgUJBQAAAA==.',
['丶擅']='丶擅解人衣:BAACLgAFFH8IAAIGAAMJ3xhVLAAFAQAGAAMJ3xhVLAAFAQAuAAQKfxwAAgYABwmmHCNIAF8CAAYABwmmHCNIAF8CAAAA.',
['丶无']='丶无聊啊:BAAALgADCgYJBgAAAA==.',
['丶昆']='丶昆凌:BAAALgADCgIJAgAAAA==.',
['丶昙']='丶昙花一现:BAAALgAFFAEJAQAAAA==.',
['丶盗']='丶盗跖:BAAALgAECgIJAwAAAA==.',
['丶紫']='丶紫霞仙子丶:BAABLgAFFH8HAAIYAAMJnx6PBwD8AAAYAAMJnx6PBwD8AAAAAA==.',
['丶聪']='丶聪聪:BAAALgAECgYJCwAAAA==.',
['丶虫']='丶虫子:BAAALgAFFAEJAQAAAA==.',
['丶靑']='丶靑:BAAALgAECgUJBQAAAA==.',
['丶黎']='丶黎明的曙光:BAAALgAECgEJAQAAAA==.',
['丸辣']='丸辣:BAABLgAECn8VAAIZAAcJDhoUDgDRAQAZAAcJDhoUDgDRAQAAAA==.',
['为之']='为之而战:BAAALgAECgYJBgAAAA==.',
['为了']='为了信仰:BAAALgAECgIJAgAAAA==.',
['为君']='为君拂青丝:BAAALgAECgIJAgAAAA==.',
['丿匿']='丿匿名用户丶:BAAALgAECgQJBAAAAA==.',
['丿鲨']='丿鲨鱼丨:BAAALgAECgEJAQAAAA==.',
['乃萨']='乃萨:BAAALgAFFAEJAQABLgAFFAQJBgAIAPkGAA==.',
['乄粑']='乄粑粑阳乄:BAAALgAECgUJBwAAAA==.',
['乄老']='乄老炮儿乄:BAAALgAECgcJDAAAAA==.',
['乐园']='乐园的审判:BAAALgAECgIJAgAAAA==.',
['乔伊']='乔伊:BAAALgAECgMJBAAAAA==.',
['乖乖']='乖乖的阳阳:BAAALgAECgYJBgAAAA==.',
['九只']='九只老瞎眼:BAABLgAFFH8JAAIBAAQJchIfEQBGAQABAAQJchIfEQBGAQAAAA==.',
['乾润']='乾润坎泽兑渊:BAAALgAECgEJAQAAAA==.',
['了个']='了个在:BAAALgADCgMJAwAAAA==.',
['二十']='二十三灬:BAAALgAECgEJAQAAAA==.',
['二等']='二等兵郝小饭:BAAALgAECgcJCgAAAA==.',
['二舅']='二舅姥爷:BAAALgAFFAIJAgAAAA==.',
['云亦']='云亦云:BAAALgAECgUJBgAAAA==.',
['云崖']='云崖孤鸿影:BAAALgAECgYJBgAAAA==.',
['云携']='云携浅梦:BAAALgAECgIJAgAAAA==.',
['五只']='五只老瞎眼:BAAALgAFFAQJBAAAAA==.',
['五月']='五月拾柒:BAAALgAECgEJAQAAAA==.',
['亚比']='亚比丶炯炯冏:BAAALgAECgYJBgAAAA==.',
['亡魂']='亡魂颤夜:BAAALgAECgQJBAAAAA==.',
['亮峰']='亮峰飞扬:BAAALgAECgcJBwABLgAFFAUJEQALAIwhAA==.',
['人生']='人生哥哥的药:BAAALgAECgYJCwAAAA==.',
['人贱']='人贱丶人爱:BAAALgAECgUJCwAAAA==.',
['亿万']='亿万呀:BAAALgADCgIJAgAAAA==.',
['从前']='从前:BAAALgAFFAMJAgAAAA==.',
['仙女']='仙女:BAAALgAECgcJBwAAAA==.',
['仟雪']='仟雪:BAAALgAECgYJBgAAAA==.',
['以尤']='以尤:BAAALgAECgUJCAAAAA==.',
['以德']='以德俘人:BAACLgAFFH8JAAIaAAMJEBRdEADmAAAaAAMJEBRdEADmAAAuAAQKfxsAAhoABgnhIHEkACgCABoABgnhIHEkACgCAAAA.',
['仰泳']='仰泳鲈鱼:BAACLgAFFH8NAAIaAAcJJB4hAACPAgAaAAcJJB4hAACPAgAuAAQKfxYAAxoACAlXHgUhADwCABoABwkOIAUhADwCAAcAAQlSC4J7ADoAAAAA.',
['伊利']='伊利萨娜:BAABLgAECn8aAAINAAgJLBv9NQBfAgANAAgJLBv9NQBfAgAAAA==.伊利达雷丶影:BAAALgAECgYJDAAAAA==.',
['伊尔']='伊尔之护:BAAALgAECgQJBAAAAA==.',
['伊师']='伊师塔:BAAALgADCgIJBAAAAA==.',
['伊菲']='伊菲尔塔尔丶:BAAALgAECgYJCAAAAA==.',
['众神']='众神的晨曦:BAAALgAECgEJAQAAAA==.',
['优珈']='优珈锦年:BAAALgAECgYJBgAAAA==.',
['会飞']='会飞的小糖豆:BAAALgAECgIJAgAAAA==.',
['伤心']='伤心小狗:BAAALgADCgEJAQAAAA==.',
['似太']='似太阳般温暖:BAAALgAECgUJBwAAAA==.',
['似梦']='似梦非梦:BAAALgAFFAEJAQAAAA==.',
['低语']='低语:BAABLgAECn8UAAIRAAcJkCGVIwCGAgARAAcJkCGVIwCGAgABLgAFFAcJFwARAN8bAA==.低语微风:BAAALgAECgEJAQAAAA==.',
['何方']='何方妖聂:BAAALgAECggJCAAAAA==.',
['何晚']='何晚风:BAAALgADCgYJCQAAAA==.',
['余大']='余大炮:BAABLgAFFH8FAAIbAAIJXwM6BgBLAAAbAAIJXwM6BgBLAAAAAA==.',
['余阿']='余阿姨:BAAALgADCgQJBAAAAA==.',
['佛爺']='佛爺丶:BAAALgAFFAMJAwAAAA==.',
['你丫']='你丫别跑:BAAALgAFFAEJAQAAAA==.',
['你好']='你好谷歌:BAABLgAFFH8IAAIGAAMJ9x1OHQDHAAAGAAMJ9x1OHQDHAAAAAA==.',
['你态']='你态度不好:BAAALgAECgEJAQAAAA==.',
['你的']='你的仙女教母:BAAALgAFFAEJAQAAAA==.',
['你要']='你要的全拿走:BAAALgADCgYJBgAAAA==.你要跳舞吗:BAAALgAFFAIJAgAAAA==.',
['你说']='你说这扯不扯:BAAALgAECgEJAwAAAA==.',
['佳洁']='佳洁士:BAAALgAECggJEwAAAA==.',
['依法']='依法治理联盟:BAAALgADCgYJBgAAAA==.',
['保安']='保安代长:BAAALgADCgUJBQAAAA==.',
['信仰']='信仰粉碎机:BAAALgAECgkJCwAAAA==.',
['倉木']='倉木:BAAALgAFFAQJBAAAAA==.',
['倚晴']='倚晴江山楼:BAABLgAFFH8IAAIYAAMJeiJABQA5AQAYAAMJeiJABQA5AQAAAA==.',
['倪达']='倪达也丶:BAACLgAFFH8QAAINAAQJjxqbDQBtAQANAAQJjxqbDQBtAQAuAAQKfx4AAg0ACAlMHEctAIMCAA0ACAlMHEctAIMCAAAA.',
['偏偏']='偏偏:BAABLgAFFH8IAAIGAAQJBRUkGQBlAQAGAAQJBRUkGQBlAQABLgAFFAYJDwAGAPgeAA==.',
['偶呦']='偶呦这个扽来:BAAALgAECgYJBgAAAA==.',
['偷猎']='偷猎贵族:BAAALgADCgUJAQAAAA==.',
['僖洋']='僖洋洋:BAABLgAFFH8IAAIKAAMJnxmACAD1AAAKAAMJnxmACAD1AAABLgAFFAQJBAACAAAAAA==.',
['僾戛']='僾戛捞:BAAALgADCgUJBQAAAA==.',
['元气']='元气满满的牛:BAAALgAECgQJBwAAAA==.',
['光之']='光之士:BAABLgAFFH8GAAIcAAIJDRtfIACtAAAcAAIJDRtfIACtAAAAAA==.',
['光头']='光头头:BAAALgAFFAQJBAAAAA==.',
['光燿']='光燿之殇:BAAALgAECgcJBQAAAA==.',
['全是']='全是猴:BAAALgAECgYJBgAAAA==.',
['八何']='八何事:BAAALgAECgkJDwABLgAFFAQJBgANAL0YAA==.',
['八只']='八只老瞎眼:BAABLgAFFH8FAAIBAAUJAR3vAwB3AQABAAUJAR3vAwB3AQAAAA==.',
['八极']='八极拳刘老师:BAAALgAECgQJCAAAAA==.',
['公子']='公子林:BAAALgADCgEJAQAAAA==.',
['六江']='六江白鹤:BAAALgAECgYJCQAAAA==.',
['兲霸']='兲霸动霸:BAAALgAECgkJCQAAAA==.',
['内河']='内河:BAAALgAECgEJAQAAAA==.',
['冖亼']='冖亼冖:BAAALgAECgEJAQAAAA==.',
['冥域']='冥域记忆:BAAALgAECgYJEgAAAA==.',
['冥昭']='冥昭无奏:BAAALgAECgIJAgAAAA==.',
['冥雾']='冥雾四爷:BAAALgADCgYJBgAAAA==.冥雾法神:BAAALgAECgQJCAAAAA==.',
['冬尼']='冬尼大牧:BAAALgAECgYJBgAAAA==.',
['冯宝']='冯宝宝:BAAALgAECgMJAwAAAA==.',
['冰冰']='冰冰涼:BAAALgADCgEJAQAAAA==.',
['冰封']='冰封的命运:BAAALgAECgMJAwAAAA==.',
['冰川']='冰川丶帝王:BAAALgAECgEJAQAAAA==.',
['冰淇']='冰淇淋珍珠:BAAALgADCgIJAgAAAA==.',
['冰雪']='冰雪无情:BAAALgAECgcJCQAAAA==.',
['冰霜']='冰霜圣族:BAAALgAECgMJAwAAAA==.',
['冰魄']='冰魄霜寒:BAAALgAECgEJAgAAAA==.',
['冰龙']='冰龙人:BAAALgAECgEJAQAAAA==.',
['冷家']='冷家赘婿:BAACLgAFFH8VAAIdAAgJwiIEAAA6AwAdAAgJwiIEAAA6AwAuAAQKfyAABB0ACQk0Ix0CAFcDAB0ACQk0Ix0CAFcDAA8ABQkeHOMYAHABAB4ABAn2FO02ABwBAAAA.',
['冷川']='冷川:BAABLgAFFH8LAAIGAAQJUSKXFgBvAQAGAAQJUSKXFgBvAQABLgAFFAYJDwAGAPgeAA==.',
['冷月']='冷月星辰:BAAALgAECgEJAgAAAA==.冷月栖星迟:BAAALgAECgEJAgAAAA==.冷月青茗:BAAALgAECgQJBgAAAA==.',
['冷风']='冷风吹过丶:BAAALgADCgEJAQAAAA==.',
['凌天']='凌天之翼:BAAALgAECgkJCwAAAA==.',
['凛冬']='凛冬镇长:BAAALgAFFAIJBAAAAA==.',
['凜冬']='凜冬將致:BAABLgAFFH8JAAIZAAQJwRdJAQB3AQAZAAQJwRdJAQB3AQAAAA==.',
['凝视']='凝视彡:BAABLgAFFH8GAAIBAAMJoQ3WEgDhAAABAAMJoQ3WEgDhAAAAAA==.',
['凝起']='凝起:BAAALgAECgYJCwAAAA==.',
['凶尸']='凶尸:BAAALgAECgIJAgAAAA==.',
['出招']='出招丶很疯狂:BAAALgAECgQJBQAAAA==.',
['出猪']='出猪车:BAAALgADCgIJAgAAAA==.',
['击靶']='击靶技巧一流:BAAALgAECgkJEQAAAA==.',
['刀锋']='刀锋入骨:BAAALgADCgUJBQAAAA==.',
['别丢']='别丢份小多子:BAABLgAFFH8IAAIMAAMJEhofCADmAAAMAAMJEhofCADmAAAAAA==.',
['别逼']='别逼我求你:BAAALgAECgYJCwAAAA==.',
['刮骨']='刮骨钢刀:BAAALgAECgEJAQAAAA==.',
['刹人']='刹人诛特:BAAALgADCgcJCgABLgAFFAcJBAACAAAAAA==.',
['前尘']='前尘丶往事:BAAALgAECgcJCQAAAA==.',
['剑指']='剑指星河:BAAALgAECgMJAwAAAA==.',
['功夫']='功夫盼达:BAAALgAECgYJBgAAAA==.',
['劣人']='劣人丶:BAAALgAECgEJAQAAAA==.',
['动物']='动物园长小久:BAAALgADCgEJAQAAAA==.',
['勇爷']='勇爷:BAAALgAECgUJCwABLgAFFAYJFgAQAMUZAA==.',
['包含']='包含违规内容:BAAALgAECgcJBwAAAA==.',
['北彼']='北彼迪尔:BAAALgAECgEJAQAAAA==.',
['匹夫']='匹夫受死:BAAALgADCgQJBQAAAA==.',
['十只']='十只老瞎眼:BAABLgAFFH8PAAIBAAUJexxHBgC/AQABAAUJexxHBgC/AQAAAA==.',
['千变']='千变小德:BAAALgAECgMJAwAAAA==.',
['千山']='千山有月:BAAALgADCgMJAwAAAA==.',
['半缘']='半缘丶:BAAALgAECgQJBgAAAA==.',
['半醒']='半醒的雨:BAAALgAECgUJBgAAAA==.',
['南宫']='南宫无影:BAABLgAFFH8MAAIGAAQJhwj4GgDqAAAGAAQJhwj4GgDqAAAAAA==.',
['南怀']='南怀瑾:BAAALgAECgcJDgABLgAECggJEAACAAAAAA==.',
['卡哇']='卡哇伊伊:BAAALgAECgEJAgAAAA==.',
['卡林']='卡林多:BAAALgAECgQJBAAAAA==.',
['卫宫']='卫宫士郎:BAAALgAECgYJBwAAAA==.',
['原初']='原初魔女:BAABLgAFFH8JAAMMAAMJ/xo7BAD3AAAMAAMJexc7BAD3AAAXAAMJ3Q8FDgDsAAAAAA==.',
['双蛋']='双蛋羊肉饭:BAAALgAECgMJAwAAAA==.',
['反骨']='反骨的仔:BAAALgAFFAIJAgAAAA==.',
['变身']='变身算我输:BAAALgAECgYJCAAAAA==.',
['口口']='口口:BAABLgAECn8WAAIaAAYJlwedegDpAAAaAAYJlwedegDpAAAAAA==.',
['古法']='古法催奶师:BAAALgAECgYJDwAAAA==.',
['古莫']='古莫雨浮萍:BAAALgADCgcJBwAAAA==.',
['叫我']='叫我皮特:BAAALgAECgQJAQAAAA==.叫我皮特哇:BAAALgADCgIJAgAAAA==.',
['可一']='可一可再:BAAALgAECgYJBgAAAA==.',
['可惜']='可惜:BAABLgAFFH8OAAIGAAUJ2BlcFAB5AQAGAAUJ2BlcFAB5AQABLgAFFAYJDwAGAPgeAA==.',
['可爱']='可爱的呆毛:BAAALgAECgYJCQAAAA==.',
['叶影']='叶影:BAAALgAECgYJBgABLgAECgkJCgACAAAAAA==.',
['吃我']='吃我一鞭:BAAALgAECgIJAgAAAA==.',
['后皇']='后皇家营法哥:BAAALgADCgEJAQAAAA==.',
['听雪']='听雪葉孜:BAAALgAECgcJCAAAAA==.',
['启明']='启明星呼唤:BAAALgAECgcJCwAAAA==.',
['启瑞']='启瑞:BAAALgAFFAEJAwAAAA==.',
['启酥']='启酥面包:BAAALgAECgMJAwAAAA==.',
['吱吱']='吱吱兹:BAAALgAFFAIJAgAAAA==.',
['吳克']='吳克大光頭:BAAALgAECggJCAAAAA==.',
['吴准']='吴准笑:BAAALgAECgIJAwABLgAFFAYJFgAQAMUZAA==.',
['呆呆']='呆呆老胖:BAAALgAECgEJAQAAAA==.',
['周之']='周之鹤:BAAALgAECgkJCwAAAA==.',
['命运']='命运的歧路:BAAALgADCgYJBgAAAA==.',
['咁露']='咁露寺蜜璃:BAAALgAECgYJBgAAAA==.',
['和谐']='和谐一点点:BAAALgAECgQJBgAAAA==.',
['咔滋']='咔滋脆鸡堡:BAACLgAFFH8hAAIFAAgJTiYCAAC6AgAFAAgJTiYCAAC6AgAuAAQKfyAAAgUACQnHJhEAAP4DAAUACQnHJhEAAP4DAAAA.',
['咬高']='咬高手:BAAALgAFFAMJBAAAAA==.',
['咿呀']='咿呀咿呀嘿呀:BAAALgADCgEJAQAAAA==.',
['哇噻']='哇噻你真矮:BAAALgADCgEJAQAAAA==.',
['哇灬']='哇灬丨圣歌丶:BAABLgAECn8ZAAMXAAcJpxlRHQCqAQAXAAUJGB5RHQCqAQAMAAcJVxIZKwCcAQAAAA==.',
['哈缪']='哈缪尔德:BAAALgAECgQJBQAAAA==.',
['哎呦']='哎呦哇灬:BAAALgAFFAUJAgAAAA==.',
['哥尓']='哥尓迪罗杰:BAAALgAECgQJBAAAAA==.',
['哥斯']='哥斯拉猎:BAAALgAECgQJBAAAAA==.',
['哩哩']='哩哩:BAAALgAECgEJAQAAAA==.',
['哪国']='哪国:BAAALgAECgEJAQAAAA==.',
['唐不']='唐不染丶:BAABLgAFFH8LAAIfAAYJUBYXAADLAQAfAAYJUBYXAADLAQAAAA==.',
['唯一']='唯一的雯雯:BAABLgAECn8VAAMQAAYJvxW6PwBLAQAQAAUJNBq6PwBLAQAKAAUJ0gUGbgDXAAAAAA==.',
['啵了']='啵了一个波:BAAALgAECgEJAQAAAA==.',
['喜多']='喜多川海梦丷:BAAALgAECgUJCQAAAA==.',
['喜欢']='喜欢濑西的你:BAAALgAECgQJCAAAAA==.',
['喝酒']='喝酒想喝醉:BAAALgAFFAIJBAAAAA==.',
['喵小']='喵小凉子:BAAALgAECgYJEAAAAA==.喵小鱼:BAABLgAFFH8GAAIcAAMJniOaBgBFAQAcAAMJniOaBgBFAQAAAA==.',
['喵灬']='喵灬喵丶:BAAALgAECgYJCgAAAA==.',
['喵萨']='喵萨拉:BAABLgAFFH8HAAINAAMJrxN0EwD2AAANAAMJrxN0EwD2AAAAAA==.',
['喵麟']='喵麟灬小鱼糕:BAAALgAECgQJCAAAAA==.',
['嗜血']='嗜血的精灵:BAAALgAECgYJCQAAAA==.',
['嗣祁']='嗣祁的牛:BAAALgAECgUJBQAAAA==.',
['嘶文']='嘶文尼:BAAALgAECgcJCwAAAA==.',
['噬魂']='噬魂:BAAALgADCgMJAwAAAA==.',
['嚣张']='嚣张的橘子:BAAALgAECgcJDQAAAA==.',
['四只']='四只老瞎眼:BAABLgAFFH8JAAIBAAUJxBU5BgBVAQABAAUJxBU5BgBVAQAAAA==.',
['囤于']='囤于厨房和爱:BAAALgAECgIJAgAAAA==.',
['囧囧']='囧囧尐螞蟻:BAAALgAECgcJBwAAAA==.',
['困惑']='困惑的浪漫:BAACLgAFFH8GAAIcAAMJ5SMgBwA8AQAcAAMJ5SMgBwA8AQAuAAQKfxQAAhwACAnnIqcQAAoDABwACAnnIqcQAAoDAAAA.',
['国宝']='国宝呀:BAAALgAECgEJAQAAAA==.',
['国服']='国服第二萌妹:BAAALgAECgcJBAAAAA==.',
['国足']='国足老二:BAAALgAECgEJAQAAAA==.',
['国际']='国际巨星:BAAALgAECgIJAgAAAA==.',
['土豪']='土豪的肥皂:BAAALgAECgMJAwAAAA==.',
['圣光']='圣光寒山:BAAALgAECgMJAwAAAA==.圣光束缚了你:BAAALgAECgEJAgAAAA==.圣光降智奶茶:BAAALgAECgQJBAAAAA==.',
['圣阳']='圣阳普照:BAAALgAECgMJAwAAAA==.',
['地狱']='地狱大王:BAAALgAECgQJAwAAAA==.地狱导游:BAACLgAFFH8GAAIRAAMJNRgXEgADAQARAAMJNRgXEgADAQAuAAQKfxkAAxEACAlFI7obAK4CABEABwlFI7obAK4CABUAAgk4FGVJAJIAAAEuAAUUBwkFABAA0RYA.',
['地獄']='地獄咆啸:BAABLgAECn8ZAAQEAAkJbR0gAgANAwAEAAkJexsgAgANAwAFAAkJYRcMCAClAgADAAcJbhyrIwA4AgABLgAFFAYJBwADAJ8WAA==.地獄的瘋:BAABLgAFFH8NAAIGAAQJyiFRDgCnAQAGAAQJyiFRDgCnAQAAAA==.',
['城北']='城北未北末北:BAABLgAECn8gAAMMAAkJdh1GHQD0AQAMAAkJdh1GHQD0AQALAAcJGgC8agAgAAAAAA==.',
['塔塔']='塔塔丶:BAACLgAFFH8XAAMTAAgJ4SA2AAAuAwATAAgJ4SA2AAAuAwAUAAEJmx0LGQBfAAAuAAQKfyAAAxMACQn2JcEAAM8DABMACQn2JcEAAM8DABQAAQn+EZq2AFYAAAAA.',
['塰王']='塰王:BAAALgADCgUJBQAAAA==.',
['墨染']='墨染飞舞:BAAALgAECgcJBgAAAA==.',
['声乐']='声乐系周卓屹:BAAALgAECgIJAgAAAA==.',
['壹法']='壹法:BAAALgADCgYJBgAAAA==.',
['夏华']='夏华骄阳:BAAALgAECgQJBAAAAA==.',
['夕阳']='夕阳老年人:BAAALgAECgcJDQAAAA==.',
['外皮']='外皮里丧:BAAALgADCgcJBwAAAA==.',
['多多']='多多吉吉:BAAALgAECgYJBgAAAA==.',
['多汁']='多汁的鲍鱼:BAAALgAECgYJDAAAAA==.',
['多糖']='多糖麻辣烫:BAAALgADCgcJCAAAAA==.',
['多肉']='多肉葡萄冰:BAAALgAECgMJAwAAAA==.',
['夜幕']='夜幕丶:BAAALgAFFAEJAQAAAA==.',
['夜雨']='夜雨的星空:BAAALgAECgIJAgAAAA==.',
['大佬']='大佬:BAAALgAECgEJAQAAAA==.',
['大傻']='大傻福:BAAALgAECgcJDQAAAA==.',
['大出']='大出息:BAAALgAFFAIJAgABLgAFFAIJAgACAAAAAA==.',
['大厨']='大厨咩咩:BAABLgAECn8ZAAIgAAkJ7hlXEACYAgAgAAkJ7hlXEACYAgAAAA==.',
['大叫']='大叫一声姐姐:BAABLgAECn8ZAAIYAAgJsR61EACNAgAYAAgJsR61EACNAgAAAA==.',
['大嘴']='大嘴的思念:BAAALgADCgcJBwAAAA==.',
['大好']='大好人:BAAALgAECgQJBAAAAA==.',
['大波']='大波:BAAALgAECgYJBgAAAA==.',
['大漠']='大漠情:BAAALgAECgEJAQAAAA==.',
['大瓶']='大瓶怡宝:BAAALgAECgEJAQAAAA==.',
['大白']='大白牛灬晓風:BAAALgAECgUJBQAAAA==.大白象:BAAALgAFFAIJAwAAAA==.',
['大红']='大红豆冰沙:BAAALgAECgEJAQAAAA==.',
['大胖']='大胖蜜蜂:BAAALgAFFAEJAQAAAA==.',
['大脸']='大脸盆:BAAALgAECgIJAgAAAA==.',
['大自']='大自然的混子:BAAALgAECgUJBQAAAA==.',
['大苹']='大苹果甜:BAAALgAECgQJBAAAAA==.',
['大螃']='大螃蟹:BAAALgAECgUJCAAAAA==.',
['大西']='大西王:BAAALgAECgYJAgAAAA==.',
['大连']='大连寺铃鹿丶:BAAALgAFFAEJAQAAAA==.',
['大青']='大青鱼:BAACLgAFFH8NAAILAAQJXhOAAwA7AQALAAQJXhOAAwA7AQAuAAQKfyQAAgsACAlJIFoIAP4CAAsACAlJIFoIAP4CAAAA.',
['大魔']='大魔导师吴来:BAAALgAECgEJAQAAAA==.',
['天乂']='天乂罡:BAAALgAECgQJBAAAAA==.',
['天使']='天使之怨:BAAALgAECgMJAwAAAA==.',
['天国']='天国呼啸:BAACLgAFFH8FAAIcAAMJvg3ZDQD2AAAcAAMJvg3ZDQD2AAAuAAQKfxUAAhwACAl4HPYxAFsCABwACAl4HPYxAFsCAAAA.',
['天堂']='天堂丨制造:BAAALgAECgQJAQAAAA==.',
['天念']='天念:BAABLgAFFH8HAAMUAAMJegiYDgDYAAAUAAMJegiYDgDYAAATAAEJXwAnLgAyAAAAAA==.',
['天思']='天思:BAAALgAECgYJCwAAAA==.',
['天戒']='天戒修罗:BAABLgAECn8XAAMTAAcJ+RixLQDAAQATAAcJGROxLQDAAQAUAAUJnxQFOACmAAAAAA==.天戒岚:BAABLgAFFH8HAAIJAAIJER7ICQC6AAAJAAIJER7ICQC6AAAAAA==.天戒御:BAAALgAECgMJAwABLgAECgcJGQAeAKIbAA==.天戒悅悅:BAABLgAECn8cAAMYAAcJfQvAWwAOAQAYAAYJQgjAWwAOAQAhAAYJ7wDaNQBtAAAAAA==.天戒撕票:BAAALgAECgIJAgABLgAECgcJGgAIACcdAA==.天戒狂热:BAABLgAECn8VAAITAAcJnhFLBAByAQATAAcJnhFLBAByAQAAAA==.天戒球球:BAABLgAECn8XAAIKAAcJCiQzDQCzAgAKAAcJCiQzDQCzAgAAAA==.天戒神裁:BAAALgAFFAEJAQAAAA==.天戒禅宁:BAABLgAECn8WAAMgAAcJ4Bq3IQDzAQAgAAcJqhe3IQDzAQAiAAYJ4RdbKQCQAQAAAA==.天戒翻车:BAAALgAECgEJAQAAAA==.天戒翼:BAABLgAECn8ZAAMeAAcJohteBgC3AQAeAAcJaBpeBgC3AQAPAAYJSxojGAB4AQAAAA==.天戒风尘:BAABLgAECn8cAAIOAAcJlRCoBgBgAQAOAAcJlRCoBgBgAQAAAA==.',
['天真']='天真无邪口牙:BAAALgAFFAMJAwAAAA==.',
['天紫']='天紫达人:BAAALgAECgYJBgAAAA==.',
['天级']='天级甜甜:BAAALgAECgUJBwAAAA==.',
['天谴']='天谴之子:BAACLgAFFH8FAAIYAAMJdRu6DQD9AAAYAAMJdRu6DQD9AAAuAAQKfxQAAhgACAlLDLA2AKABABgACAlLDLA2AKABAAAA.',
['天雨']='天雨流芳:BAABLgAFFH8LAAMKAAMJkRtYBwANAQAKAAMJkRtYBwANAQAQAAMJ/gatEQDdAAAAAA==.',
['天驱']='天驱镇魂:BAACLgAFFH8MAAIcAAQJERN/DABIAQAcAAQJERN/DABIAQAuAAQKfyEAAhwACAlqIEwcAMACABwACAlqIEwcAMACAAAA.',
['头很']='头很硬:BAAALgAECgQJBgAAAA==.',
['奇三']='奇三妹丶:BAAALgAECgYJBgAAAA==.',
['奇姆']='奇姆斯:BAAALgAFFAEJAQAAAA==.',
['奇迹']='奇迹行者:BAAALgAECgkJCQAAAA==.',
['奈亚']='奈亚冇喵:BAAALgADCgEJAQAAAA==.',
['奈尔']='奈尔不花:BAAALgAECgMJAwAAAA==.',
['奉天']='奉天爷们:BAAALgADCgYJBgAAAA==.',
['奥术']='奥术的使徒:BAABLgAFFH8JAAIGAAUJbAv1DAC0AQAGAAUJbAv1DAC0AQAAAA==.奥术红豆包:BAABLgAECn8dAAIGAAgJfxz3MwCjAgAGAAgJfxz3MwCjAgAAAA==.奥术茶茶:BAAALgAFFAIJAgAAAA==.',
['奥狸']='奥狸給:BAAALgADCgIJAgAAAA==.',
['奧蕾']='奧蕾莉婭:BAAALgAFFAIJBAAAAA==.',
['奶棋']='奶棋:BAABLgAFFH8GAAIIAAQJ+Qa7BgD5AAAIAAQJ+Qa7BgD5AAAAAA==.',
['奶油']='奶油团子:BAAALgAECgcJEgABLgAFFAUJCQAGAP0PAA==.',
['奶牛']='奶牛团子:BAAALgADCgQJBAAAAA==.',
['奶琦']='奶琦:BAAALgAFFAEJAQABLgAFFAQJBgAIAPkGAA==.',
['奶糖']='奶糖睡不醒:BAACLgAFFH8JAAIGAAUJ/Q+CHgBQAQAGAAUJ/Q+CHgBQAQAuAAQKfx4AAgYABwnQIkgzAKYCAAYABwnQIkgzAKYCAAAA.',
['奶龍']='奶龍:BAAALgAFFAEJAQABLgAFFAQJBgAIAPkGAA==.',
['她们']='她们叫我帅哥:BAAALgAECgcJBwAAAA==.',
['好了']='好了我知道了:BAABLgAFFH8FAAIRAAUJ7Bf3BQBlAQARAAUJ7Bf3BQBlAQAAAA==.',
['好好']='好好學习:BAAALgAECgIJAgAAAA==.',
['好气']='好气:BAABLgAFFH8WAAMeAAgJfQdXAQBoAgAeAAgJfQdXAQBoAgAPAAIJIQNFBwCWAAAAAA==.',
['如梦']='如梦丶乄:BAAALgAECgMJAwAAAA==.',
['妖小']='妖小月:BAAALgAECgEJAQAAAA==.妖小诗:BAAALgAFFAEJAQAAAA==.妖小颖:BAAALgAECgEJAQAAAA==.',
['妙才']='妙才:BAAALgAECgQJCgAAAA==.',
['威廉']='威廉丶:BAAALgAECgYJCgAAAA==.',
['娜哈']='娜哈特娜哈特:BAAALgADCgUJBQAAAA==.',
['婉丶']='婉丶清:BAAALgAECgIJAgAAAA==.',
['嬉笑']='嬉笑佬爺:BAAALgAECgYJDAABLgAECgcJAwACAAAAAA==.嬉笑少爷:BAAALgAECgcJAwAAAA==.嬉笑顽主:BAAALgAECgYJEAABLgAECgcJAwACAAAAAA==.',
['孤影']='孤影随行:BAAALgADCgcJBwAAAA==.',
['孤独']='孤独娛樂丶:BAAALgAECgQJBQAAAA==.',
['孤身']='孤身听晚风:BAAALgAECgYJBwAAAA==.',
['守望']='守望丶猎:BAAALgAECgkJDAAAAA==.',
['安啦']='安啦暖阳洋:BAAALgAECgEJAQAAAA==.',
['安静']='安静得美男子:BAAALgAECgUJCwAAAA==.',
['宋总']='宋总:BAAALgAECgIJBAAAAA==.',
['完美']='完美复出:BAAALgAFFAMJAwAAAA==.',
['宗旨']='宗旨:BAAALgAECgEJAQAAAA==.',
['定距']='定距三叶桨:BAAALgADCgYJBgAAAA==.',
['客官']='客官丶不可以:BAAALgAECgMJAwAAAA==.',
['害群']='害群德马:BAAALgAECgIJAgAAAA==.',
['寂兮']='寂兮寥兮丶:BAAALgAFFAIJBAAAAA==.',
['寂寞']='寂寞的小德:BAAALgAFFAEJAQAAAA==.寂寞节:BAAALgAECgIJAgAAAA==.',
['寂静']='寂静灵魂:BAABLgAECn8UAAIcAAcJmBS1YwC6AQAcAAcJmBS1YwC6AQAAAA==.',
['寅时']='寅时上炕:BAAALgAECgUJCwAAAA==.',
['富强']='富强丶:BAAALgAFFAMJAQAAAA==.',
['寒萧']='寒萧北诀:BAAALgAECgcJBwAAAA==.',
['对面']='对面蚂蚱没大:BAAALgAFFAIJAgAAAA==.',
['寻灬']='寻灬念:BAAALgAECgEJAQAAAA==.',
['封牧']='封牧:BAAALgAECgEJAQABLgAFFAMJCAAFAKwJAA==.',
['封龙']='封龙:BAAALgAECgYJBgAAAA==.',
['小八']='小八:BAAALgAECgcJDQAAAA==.',
['小出']='小出息:BAAALgAFFAIJAgAAAA==.',
['小唐']='小唐人:BAAALgAECgYJCQAAAA==.',
['小宫']='小宫有纱:BAAALgAECgcJCgAAAA==.',
['小小']='小小氺术:BAAALgAECgIJAgAAAA==.小小熙丶:BAAALgAECgIJAgAAAA==.小小的石头:BAAALgAECgQJBAAAAA==.小小防骑:BAAALgADCgYJBwAAAA==.',
['小幺']='小幺:BAAALgAECgYJBgAAAA==.',
['小德']='小德很酷:BAAALgADCgEJAQAAAA==.小德最萌啦:BAAALgAECgUJBQAAAA==.',
['小李']='小李喇叭:BAAALgAECgUJCgAAAA==.',
['小沙']='小沙士汽水:BAAALgAECgUJBQAAAA==.',
['小熊']='小熊小红手:BAAALgAECgIJAgAAAA==.',
['小爷']='小爷就是丑:BAABLgAFFH8GAAIRAAMJVAnwJADvAAARAAMJVAnwJADvAAAAAA==.小爷就是黑:BAACLgAFFH8FAAIGAAIJmwLSKQB1AAAGAAIJmwLSKQB1AAAuAAQKfxYAAgYABwmaFOd0AOgBAAYABwmaFOd0AOgBAAAA.',
['小牛']='小牛萌萌呀:BAAALgADCgUJBQAAAA==.',
['小特']='小特丶:BAAALgAECgkJEQAAAA==.',
['小狗']='小狗砸:BAAALgAECgcJDgAAAA==.',
['小狼']='小狼月:BAAALgAECgYJDAAAAA==.',
['小田']='小田同学:BAAALgAECgYJBgAAAA==.',
['小矬']='小矬霸子:BAAALgAFFAEJAQAAAA==.',
['小石']='小石同学:BAAALgAECgcJBwAAAA==.',
['小神']='小神棍德:BAACLgAFFH8RAAIaAAUJFhknAwCDAQAaAAUJFhknAwCDAQAuAAQKfxsAAhoACAlVHkQUAJQCABoACAlVHkQUAJQCAAAA.',
['小糯']='小糯米团子丶:BAACLgAFFH8dAAIIAAgJcA+SAACPAgAIAAgJcA+SAACPAgAuAAQKfyAAAggACQmnGm0NAH4CAAgACQmnGm0NAH4CAAAA.',
['小红']='小红果果丶:BAAALgAECgYJDgAAAA==.',
['小舞']='小舞:BAAALgAECgUJCgAAAA==.',
['小訫']='小訫恶魔:BAAALgAECgcJDAAAAA==.',
['小貔']='小貔貅:BAAALgAECgUJBQAAAA==.',
['小迪']='小迪:BAAALgAECgkJCgAAAA==.',
['小雨']='小雨的理想型:BAAALgADCgIJAgAAAA==.',
['小霸']='小霸气乐无穷:BAAALgAECgUJCAAAAA==.',
['尐丶']='尐丶乜:BAAALgAECgQJBAAAAA==.',
['尐飒']='尐飒:BAAALgAECgEJAQAAAA==.',
['少林']='少林:BAAALgAECgIJBAAAAA==.少林功夫好耶:BAABLgAECn8WAAIgAAgJZiQ3BABJAwAgAAgJZiQ3BABJAwAAAA==.',
['尘染']='尘染:BAAALgAECgUJBQAAAA==.',
['就你']='就你叫夏洛呀:BAAALgAFFAMJAgAAAA==.',
['就像']='就像风住了风:BAAALgADCgUJBQAAAA==.',
['就打']='就打他丶还小:BAAALgAECgMJAwAAAA==.',
['就是']='就是这么跳:BAAALgAECgEJAQAAAA==.',
['就算']='就算我已迷失:BAAALgADCgEJAQAAAA==.',
['尹工']='尹工你好:BAAALgAECgQJBQAAAA==.尹工辛苦:BAAALgAECgYJBQAAAA==.',
['尼克']='尼克真大王:BAAALgAECgMJAwAAAA==.',
['尼奥']='尼奥克斯:BAABLgAFFH8CAAIRAAIJCQp5IwCcAAARAAIJCQp5IwCcAAAAAA==.',
['尾巴']='尾巴软:BAAALgAFFAEJAgAAAA==.',
['山川']='山川:BAAALgAECgMJAwAAAA==.',
['崎玉']='崎玉老师:BAAALgAECgEJAQABLgAFFAIJBAACAAAAAA==.',
['崔斯']='崔斯特:BAAALgADCgEJAQAAAA==.',
['巡礼']='巡礼之年:BAAALgAECgQJBAAAAA==.',
['左手']='左手一只鸡:BAAALgADCgcJBwAAAA==.',
['巧思']='巧思不如构思:BAAALgAECgEJAQAAAA==.',
['差点']='差点伤害啊:BAAALgAECgQJAwAAAA==.',
['巴哈']='巴哈嘿:BAAALgADCgEJAQAAAA==.',
['巴尔']='巴尔蚀辉炉石:BAAALgAECgYJEQAAAA==.',
['巴郎']='巴郎子追风:BAAALgAECgQJBAAAAA==.',
['布丁']='布丁豆豆:BAAALgAECgMJAwAAAA==.',
['布偶']='布偶游乐场:BAAALgAECgQJBAAAAA==.',
['布朗']='布朗丶树心:BAABLgAFFH8GAAIaAAMJAhNCCgDhAAAaAAMJAhNCCgDhAAAAAA==.',
['布鲁']='布鲁拽根儿:BAABLgAECn8XAAMdAAcJGhdoFAD/AQAdAAcJGhdoFAD/AQAeAAYJuwmXOQANAQAAAA==.',
['帅叔']='帅叔叔:BAAALgAECgIJAgAAAA==.',
['帅气']='帅气的小德:BAAALgAECgYJBwAAAA==.',
['希尔']='希尔法纳斯:BAAALgAECgYJBgAAAA==.希尔瓦:BAAALgAECgEJAgAAAA==.希尔瓦斯娜:BAACLgAFFH8MAAIBAAQJ8yB8CQCSAQABAAQJ8yB8CQCSAQAuAAQKfx4AAgEACAkNIfIRAO8CAAEACAkNIfIRAO8CAAAA.',
['帕鲁']='帕鲁丶:BAAALgAFFAIJAgAAAA==.',
['帝岳']='帝岳:BAAALgAECgEJAQAAAA==.',
['帝溾']='帝溾蚩:BAAALgAECgkJCgAAAA==.',
['常夜']='常夜樱吹雪:BAABLgAECn8UAAIcAAkJ1iAnCQBJAwAcAAkJ1iAnCQBJAwAAAA==.',
['干完']='干完发型不乱:BAAALgAECgYJCgAAAA==.',
['干巴']='干巴廋不抗揍:BAAALgADCgEJAQAAAA==.',
['干馏']='干馏碗杂面:BAAALgAECgEJAgAAAA==.',
['平头']='平头哥:BAAALgAECgkJAgAAAA==.',
['年轻']='年轻的小母熊:BAAALgAECgUJBQAAAA==.',
['幸福']='幸福的烂菜叶:BAABLgAECn8jAAQHAAcJ4BmHHAAdAgAHAAcJ4BmHHAAdAgAaAAEJgA3zRQAxAAAbAAIJNgOyEgAoAAAAAA==.',
['幻丨']='幻丨潜行:BAAALgADCgEJAQAAAA==.',
['幽若']='幽若焱儿:BAAALgAECgcJBgAAAA==.',
['弃暗']='弃暗投明:BAAALgAECgUJBQAAAA==.',
['弑魂']='弑魂:BAAALgAECgcJDQAAAA==.',
['张家']='张家大少:BAAALgAFFAIJAwAAAA==.',
['张洺']='张洺赫:BAAALgAECgEJAQAAAA==.',
['张禄']='张禄堂:BAAALgAECgEJAQAAAA==.',
['弱不']='弱不禁風:BAAALgAECgcJBgAAAA==.',
['弹猫']='弹猫德蛋蛋:BAAALgADCgIJAgAAAA==.',
['弹蛋']='弹蛋蛋:BAAALgADCgEJAQAAAA==.',
['彡永']='彡永不为奴彡:BAAALgADCgMJAwAAAA==.',
['影分']='影分身:BAAALgADCgIJAgAAAA==.',
['影子']='影子一冷锋:BAAALgAFFAEJAQAAAA==.',
['彼岸']='彼岸丿晓灬風:BAAALgAECgMJBAAAAA==.',
['往如']='往如烟:BAAALgADCgMJAwAAAA==.',
['很息']='很息命:BAAALgAECgEJAQAAAA==.',
['徐日']='徐日天:BAAALgAECgIJAgAAAA==.',
['徒手']='徒手撕联盟:BAAALgAECgYJCQAAAA==.',
['微微']='微微辣:BAAALgAECgcJDAAAAA==.',
['微笑']='微笑光电:BAAALgAECgEJAQAAAA==.',
['德大']='德大叔:BAAALgAFFAcJBAAAAA==.',
['德柱']='德柱:BAAALgAECgQJBAAAAA==.',
['德米']='德米媞雅:BAAALgAECgEJAQAAAA==.',
['德过']='德过切过:BAABLgAECn8fAAMaAAYJWiNjGgBnAgAaAAYJWiNjGgBnAgAHAAUJNx3IJwDAAQAAAA==.',
['心流']='心流状态:BAAALgAECgcJBgAAAA==.',
['心落']='心落繁华:BAAALgAECgcJDwAAAA==.',
['忍忍']='忍忍:BAAALgAFFAIJAgAAAA==.',
['快给']='快给我加血:BAAALgADCgkJCQAAAA==.',
['怎么']='怎么唱情歌:BAAALgAECgUJBwAAAA==.',
['怪呢']='怪呢:BAABLgAFFH8cAAINAAcJIiAsAADdAgANAAcJIiAsAADdAgAAAA==.',
['恶魔']='恶魔七:BAABLgAFFH8FAAIMAAIJgR11CwCsAAAMAAIJgR11CwCsAAAAAA==.恶魔之心:BAAALgAECgUJBgAAAA==.恶魔天使丶:BAACLgAFFH8MAAIBAAQJtR1RDABxAQABAAQJtR1RDABxAQAuAAQKfyUAAgEACAm4IJQWAM8CAAEACAm4IJQWAM8CAAAA.',
['悠然']='悠然凌风:BAAALgAECgUJBgAAAA==.',
['悲伤']='悲伤的温暖:BAAALgAECgEJAQAAAA==.悲伤的落叶丶:BAAALgAECgYJBgABLgAFFAIJBQARAFcVAA==.',
['悲兔']='悲兔的狐:BAAALgAFFAEJAQAAAA==.',
['惊蛰']='惊蛰丶:BAAALgAFFAMJAwAAAA==.',
['惊鸿']='惊鸿照影来:BAAALgAECgcJCAAAAA==.',
['想着']='想着丶你:BAAALgAFFAQJBAAAAA==.',
['愚者']='愚者:BAAALgAECgYJCAAAAA==.',
['感染']='感染科姚主任:BAABLgAECn8jAAINAAcJyxWLGQBjAQANAAcJyxWLGQBjAQAAAA==.',
['愤怒']='愤怒大白兔:BAAALgADCgEJAQAAAA==.愤怒的香蕉糖:BAAALgADCgYJBgAAAA==.',
['愿圣']='愿圣光保护你:BAAALgAECgYJEQAAAA==.',
['慈悲']='慈悲渡魂落:BAAALgAECgEJAQAAAA==.',
['憔丶']='憔丶悴:BAAALgAECgYJBwAAAA==.',
['成歩']='成歩堂:BAABLgAECn8UAAMgAAcJpSGdIQD0AQAgAAYJGyKdIQD0AQAiAAUJvxXaNwA/AQAAAA==.',
['我列']='我列个丶去:BAAALgAECgEJAQAAAA==.',
['我即']='我即天灾:BAAALgAECgEJAQAAAA==.',
['我叫']='我叫小萌酱:BAAALgAECgYJBgAAAA==.',
['我向']='我向右:BAAALgAECgYJBwAAAA==.',
['我好']='我好了丶:BAAALgAECgMJAwAAAA==.',
['我就']='我就是杀戮:BAAALgAFFAIJAwAAAA==.',
['我手']='我手很忙:BAAALgAECgEJAQAAAA==.',
['我抽']='我抽芙蓉王:BAAALgAECgEJAQAAAA==.',
['我是']='我是龙巢之母:BAAALgADCgEJAQAAAA==.',
['我没']='我没低保不上:BAAALgAFFAIJAwAAAA==.',
['我爱']='我爱吃薯片:BAAALgAECgEJAQAAAA==.',
['我的']='我的雪地靴呢:BAAALgAFFAEJAgAAAA==.',
['我胸']='我胸毛贼多:BAAALgAECgkJCQAAAA==.',
['我要']='我要种太阳:BAAALgAECgEJAQAAAA==.',
['战吊']='战吊灬灭霸:BAAALgAFFAIJAwAAAA==.',
['战吼']='战吼工具人丶:BAAALgADCgEJAQAAAA==.',
['战斗']='战斗姬:BAAALgADCgYJBgAAAA==.',
['战貂']='战貂:BAAALgADCgcJBwAAAA==.',
['扎啤']='扎啤两块五:BAAALgAECgMJAwAAAA==.',
['打丶']='打丶炮波神:BAAALgAECgQJBAAAAA==.',
['打公']='打公仔:BAAALgAECgEJAQAAAA==.',
['打锤']='打锤子打:BAAALgAFFAMJAwAAAA==.',
['打饭']='打饭阿姨:BAAALgAECgkJAQAAAA==.',
['执剑']='执剑:BAAALgADCggJBAAAAA==.',
['执番']='执番碱么:BAAALgADCgIJAgAAAA==.',
['扭曲']='扭曲虚空之眼:BAAALgAFFAEJAgABLgAFFAMJAwACAAAAAA==.',
['抓住']='抓住那个小德:BAAALgAECgQJBAAAAA==.抓住钱钱:BAAALgAECgEJAgAAAA==.',
['抓宝']='抓宝宝的茶茶:BAAALgAECgEJAgAAAA==.',
['抓我']='抓我要狗待:BAAALgAFFAIJAgAAAA==.',
['折戟']='折戟沉沙:BAAALgAECgUJBQAAAA==.',
['抹茶']='抹茶味月饼:BAABLgAECn8ZAAIRAAgJVR8hDAAZAwARAAgJVR8hDAAZAwAAAA==.',
['抽烟']='抽烟的驴:BAABLgAECn8WAAIUAAcJshfoLAAAAgAUAAcJshfoLAAAAgAAAA==.',
['拈花']='拈花碳:BAAALgAECgMJAwAAAA==.',
['拉克']='拉克珊娜冕卫:BAAALgAFFAIJBAAAAA==.',
['拎着']='拎着斧头砍:BAAALgAECgMJAwAAAA==.',
['招财']='招财有道:BAAALgAECgYJBwAAAA==.',
['拼死']='拼死捡肥皂:BAABLgAFFH8LAAIMAAQJnRtFAwBkAQAMAAQJnRtFAwBkAQAAAA==.',
['指上']='指上瘫冰丶:BAAALgAECgkJCQABLgAFFAYJBgAGABIBAA==.',
['挚息']='挚息:BAABLgAFFH8FAAIiAAMJjgdsBQDZAAAiAAMJjgdsBQDZAAAAAA==.',
['挥霍']='挥霍歇斯底里:BAAALgAECgMJAwAAAA==.',
['挽风']='挽风轻舞:BAAALgAFFAEJAQAAAA==.',
['捣蛋']='捣蛋尐木子:BAAALgAECgYJCQAAAA==.',
['掰断']='掰断萝莉:BAAALgADCgcJBwAAAA==.',
['提里']='提里奥和弗丁:BAAALgAECgYJDwAAAA==.',
['插棍']='插棍儿少年:BAAALgAECgUJCQAAAA==.',
['搞哥']='搞哥神选:BAAALgAFFAIJBAAAAA==.',
['撒哈']='撒哈拉下暴雨:BAACLgAFFH8IAAMRAAQJRxctEQBZAQARAAQJRxctEQBZAQAVAAEJTwJnGgBFAAAuAAQKfxYAAhEABwnLGbI1ADUCABEABwnLGbI1ADUCAAAA.',
['敏宝']='敏宝儿:BAAALgAECgIJAgAAAA==.',
['敖五']='敖五:BAABLgAECn8HAAIcAAcJIxU5EwCsAQAcAAcJIxU5EwCsAQAAAA==.',
['文具']='文具盒:BAAALgADCgYJBgAAAA==.',
['文歌']='文歌:BAABLgAECn8YAAMJAAYJXR3XCgBMAQAJAAYJXR3XCgBMAQAWAAEJaBZECwBKAAAAAA==.',
['文泰']='文泰來:BAAALgAECgYJDAAAAA==.',
['斋森']='斋森美世:BAABLgAECn8XAAMdAAgJmBw0CwCBAgAdAAgJmBw0CwCBAgAeAAYJXRrOIgCnAQAAAA==.',
['斩心']='斩心绝:BAAALgAECgEJAQAAAA==.',
['斩星']='斩星辰丶:BAAALgAECgEJAQAAAA==.',
['斯坦']='斯坦:BAAALgADCgIJAgAAAA==.',
['斯汶']='斯汶泥:BAAALgAECgQJBAAAAA==.',
['新人']='新人君莫笑:BAAALgAECgQJBAAAAA==.',
['新岛']='新岛冴:BAAALgAECgUJCAAAAA==.',
['新西']='新西兰奶源:BAAALgAECgEJAgAAAA==.',
['旈歆']='旈歆:BAAALgAECgUJBQAAAA==.',
['旋风']='旋风酷酷熊:BAAALgAFFAQJBAAAAA==.',
['旋饭']='旋饭牛霸王:BAAALgAECgQJBwAAAA==.',
['无僧']='无僧不武:BAAALgAECggJBgAAAA==.',
['无双']='无双灬淚:BAAALgAECgMJAwAAAA==.',
['无尽']='无尽的笑:BAAALgADCgYJBgAAAA==.',
['无情']='无情铁手:BAAALgAECggJEAAAAA==.',
['无敌']='无敌大波浪:BAAALgAECgYJBQAAAA==.无敌脑瓜崩:BAABLgAECn8gAAINAAcJjx9qLQCDAgANAAcJjx9qLQCDAgAAAA==.',
['无畏']='无畏的亚当:BAAALgAECgcJBwAAAA==.',
['无良']='无良骑士:BAAALgAECgQJBgAAAA==.',
['无间']='无间共鸣:BAAALgAECgIJAgAAAA==.',
['无鞘']='无鞘之刃:BAAALgAECgkJEAAAAA==.',
['既然']='既然:BAABLgAFFH8PAAIGAAYJ+B7vAAD6AQAGAAYJ+B7vAAD6AQAAAA==.',
['时光']='时光之胡子:BAAALgAECgYJCAAAAA==.时光之阿胡:BAAALgAECgcJBwAAAA==.',
['昆凌']='昆凌丶丶:BAAALgAECgQJBAAAAA==.昆凌打不动了:BAAALgAECgQJAQAAAA==.',
['昆山']='昆山龙哥:BAAALgAECgcJDAAAAA==.',
['星光']='星光灿烂:BAAALgAECgcJCQAAAA==.',
['星期']='星期五不刷牙:BAAALgADCgEJAQAAAA==.星期五不那啥:BAAALgAECgkJCAAAAA==.',
['星河']='星河掠影:BAAALgAECgQJCAAAAA==.星河踏梦:BAAALgAECgEJAQAAAA==.',
['星空']='星空小小术:BAAALgAECgEJAQAAAA==.',
['星野']='星野丶梦美:BAAALgAECgEJAQAAAA==.',
['春哥']='春哥的蛋蛋:BAAALgAECgYJCgAAAA==.',
['春暖']='春暖花开:BAAALgAECgYJEAAAAA==.',
['春香']='春香:BAAALgAECgYJCgAAAA==.',
['晓灬']='晓灬尐姐:BAAALgAECgYJDQAAAA==.',
['晓美']='晓美焰:BAABLgAFFH8KAAIGAAQJXRsMJAAmAQAGAAQJXRsMJAAmAQAAAA==.',
['晚风']='晚风作酒:BAABLgAFFH8GAAINAAMJ7AqbFQDrAAANAAMJ7AqbFQDrAAAAAA==.',
['普拉']='普拉特尔:BAAALgAECgIJAgAAAA==.',
['景晓']='景晓顺灬:BAAALgAECgYJDQAAAA==.',
['景色']='景色小法:BAAALgAECgEJAgAAAA==.',
['晴空']='晴空:BAAALgAECgMJAwAAAA==.',
['暗夜']='暗夜丶冰藍:BAAALgADCgMJAwAAAA==.暗夜丶惩戒:BAAALgAECgEJAgAAAA==.暗夜帽:BAAALgAECgEJAQAAAA==.',
['暗杀']='暗杀麻雀天团:BAAALgAECgYJBgAAAA==.',
['暗羽']='暗羽夜枫:BAAALgAECgEJAgAAAA==.',
['暗血']='暗血之泣:BAAALgAECgcJBgAAAA==.暗血魂殇:BAAALgAECgcJBwAAAA==.',
['暴躁']='暴躁的小火柴:BAAALgADCgMJAwAAAA==.',
['暴露']='暴露狂:BAAALgAECgMJAwAAAA==.',
['曉雨']='曉雨點:BAAALgAECgkJCQAAAA==.',
['書包']='書包佬:BAAALgAECgEJAQAAAA==.',
['曹梦']='曹梦洁:BAABLgAFFH8HAAIgAAMJ8wTBDADEAAAgAAMJ8wTBDADEAAAAAA==.',
['曼珠']='曼珠沙華:BAAALgADCgUJBQAAAA==.',
['曼舞']='曼舞者丶:BAACLgAFFH8OAAMBAAYJSAlfCQA1AQABAAYJ+gVfCQA1AQAfAAMJPQpVBgDrAAAuAAQKfygAAx8ACQmaHasJAMcCAB8ABwmDIqsJAMcCAAEACQlyFGUsAEwCAAAA.曼舞者丷:BAAALgAECgYJCwAAAA==.曼舞者灬:BAAALgAECgQJBAAAAA==.',
['月下']='月下听风吟:BAAALgAECgYJDgAAAA==.',
['月傲']='月傲天:BAAALgAECgYJBwAAAA==.',
['月夜']='月夜寒星:BAAALgADCgQJAwABLgAECgQJBgACAAAAAA==.',
['月神']='月神煌:BAAALgAECgYJDAAAAA==.',
['月落']='月落星野:BAAALgAECgIJAgAAAA==.',
['月铭']='月铭:BAAALgAECgYJBAAAAA==.',
['有内']='有内涵的牛:BAAALgAFFAMJBAAAAA==.',
['有德']='有德儿必有尸:BAAALgAFFAIJBAAAAA==.',
['有点']='有点懵:BAAALgAECgUJDAAAAA==.',
['有素']='有素质的牛:BAAALgAECgIJAgAAAA==.',
['望山']='望山海人:BAAALgADCgYJBgAAAA==.',
['木乃']='木乃医:BAAALgAECgQJBwAAAA==.',
['未晞']='未晞丶:BAAALgAECgkJCAAAAA==.',
['未知']='未知目标中:BAAALgAECgQJBAAAAA==.',
['末世']='末世歌者:BAAALgAECgMJAwAAAA==.',
['本体']='本体没伤害:BAAALgAECgcJBAAAAA==.',
['朮学']='朮学家:BAAALgAECgEJAQAAAA==.',
['术丶']='术丶先森:BAAALgAECgYJBwAAAA==.',
['术式']='术式的姿势:BAAALgAFFAEJAQAAAA==.',
['术术']='术术你别摸了:BAAALgAECgcJAQAAAA==.',
['朱迪']='朱迪兔朱迪:BAAALgAECgEJAgAAAA==.',
['杀戮']='杀戮之雨:BAAALgAECgYJEAAAAA==.',
['杀生']='杀生丸:BAAALgAECgcJBwAAAA==.',
['村村']='村村的故事:BAAALgAFFAQJBAAAAA==.',
['杜隆']='杜隆丶坦:BAAALgADCgMJAwAAAA==.',
['来听']='来听雨轩:BAAALgAECgcJBwABLgAFFAQJDAAGAOgfAA==.',
['東尼']='東尼大牧:BAAALgAECgQJAgAAAA==.',
['東风']='東风谷早苗:BAAALgAECgcJDgAAAA==.',
['极品']='极品腿毛:BAABLgAFFH8HAAIRAAMJ8hQWEQAJAQARAAMJ8hQWEQAJAQAAAA==.',
['林城']='林城吴彦祖:BAAALgAECgEJAQAAAA==.',
['林芷']='林芷伊:BAAALgAECgcJDgAAAA==.',
['林阴']='林阴影:BAAALgAECgUJBQAAAA==.',
['枪炮']='枪炮玫瑰:BAAALgAECgUJBQAAAA==.',
['某同']='某同学:BAAALgAECgMJAwAAAA==.',
['柒千']='柒千忧伤丶:BAAALgAECgUJCQAAAA==.',
['柒柒']='柒柒宝贝:BAAALgADCgUJBQAAAA==.',
['染火']='染火沁霜:BAABLgAECn8VAAIGAAgJ1QRexQBcAQAGAAgJ1QRexQBcAQAAAA==.',
['染煞']='染煞提款机:BAAALgAECgMJAwAAAA==.',
['柯罗']='柯罗诺斯残影:BAAALgAECgQJBQAAAA==.',
['柳叶']='柳叶青:BAABLgAECn8cAAQVAAcJIx4nJAA5AQARAAUJZhrqZQCaAQAVAAQJjRsnJAA5AQASAAEJAACgMwA1AAAAAA==.',
['栗子']='栗子:BAAALgAECgEJAQAAAA==.',
['格兰']='格兰德玛:BAAALgAECgEJAQAAAA==.格兰摩兰吉:BAAALgAECgUJCwABLgAECgYJHwAaAFojAA==.',
['桂言']='桂言叶灬:BAABLgAFFH8FAAIKAAUJkRvoAADKAQAKAAUJkRvoAADKAQAAAA==.',
['桃笙']='桃笙丶娇花:BAAALgAECgMJAwAAAA==.桃笙丶安娜:BAAALgAECgEJAQAAAA==.桃笙丶黑骑:BAAALgAECgEJAQAAAA==.',
['桥豆']='桥豆麻袋丶:BAABLgAFFH8JAAIJAAUJBxbmAwC6AQAJAAUJBxbmAwC6AQABLgAFFAYJCQAJALMQAA==.',
['梅丨']='梅丨毒战:BAAALgAFFAIJAwAAAA==.',
['梦压']='梦压星河:BAAALgAECgYJDQAAAA==.',
['梦熊']='梦熊儿:BAAALgAECgUJBgAAAA==.',
['梦落']='梦落花:BAAALgADCgIJAgAAAA==.',
['森林']='森林都似树:BAAALgAECgYJDQAAAA==.',
['椎名']='椎名昔颜:BAAALgADCgcJBwABLgAFFAMJBwAdALEXAA==.椎名真白灬:BAABLgAFFH8FAAIKAAUJhxp/BACJAQAKAAUJhxp/BACJAQAAAA==.',
['楚清']='楚清瞳:BAAALgADCgQJBAAAAA==.',
['概率']='概率爆炸:BAAALgADCgEJAQAAAA==.',
['槊果']='槊果吃零食:BAAALgAECgEJAQAAAA==.槊果玩游戏:BAAALgAECgMJAwAAAA==.槊果看电影:BAAALgAECgEJAQAAAA==.',
['樱岛']='樱岛丶麻衣:BAACLgAFFH8XAAQVAAcJLRqVAAA3AgAVAAYJfhSVAAA3AgARAAUJUByrBADUAQASAAEJAADXBQBVAAAuAAQKfyYAAxEACQnaJgkAABMEABEACQnaJgkAABMEABUAAwlCHMkxAPIAAAAA.',
['樱语']='樱语橦:BAAALgAECgMJAwAAAA==.',
['橘子']='橘子汽水糖:BAABLgAFFH8FAAIcAAQJ/AjdEAAeAQAcAAQJ/AjdEAAeAQAAAA==.橘子的汽水:BAAALgAECgUJBQAAAA==.',
['橘柚']='橘柚:BAAALgAECgIJAgAAAA==.',
['橘的']='橘的猫:BAAALgAECgIJAgAAAA==.',
['橙味']='橙味:BAAALgAECgIJAgAAAA==.',
['欠一']='欠一杯奶茶:BAAALgAECgYJCAAAAA==.',
['次元']='次元衍射变体:BAAALgAECgQJBAAAAA==.',
['欧皇']='欧皇大少:BAAALgAFFAIJAgAAAA==.欧皇少爷:BAAALgAFFAIJAgAAAA==.欧皇的核桃:BAAALgADCgUJBQAAAA==.',
['欧阳']='欧阳富贵:BAAALgAECgQJBAAAAA==.',
['正义']='正义邪龙:BAAALgAECgUJCQAAAA==.',
['正道']='正道德光:BAAALgAECgYJCQAAAA==.',
['歲月']='歲月琉璃:BAAALgAECgQJBAAAAA==.',
['歸去']='歸去灬来兮:BAAALgAECgYJEgAAAA==.',
['死尸']='死尸丶:BAAALgAECgIJAQAAAA==.',
['死灬']='死灬灬尸:BAAALgAECgEJAQAAAA==.',
['死神']='死神灬凝视:BAAALgADCgcJBwAAAA==.',
['死骑']='死骑缱绻:BAAALgADCgIJAgAAAA==.',
['残念']='残念终成悔:BAAALgAECgYJCQAAAA==.',
['毁灭']='毁灭戦士:BAAALgAECgIJAgAAAA==.',
['毒瘤']='毒瘤丶呜喵王:BAAALgAECgUJBQAAAA==.',
['毛神']='毛神燃烬:BAAALgAFFAIJBAAAAA==.',
['毛脸']='毛脸雷公:BAAALgAECgYJBgAAAA==.',
['水墨']='水墨复读机:BAABLgAFFH8FAAIRAAIJxBWiMACxAAARAAIJxBWiMACxAAAAAA==.',
['水煮']='水煮鱼好好吃:BAAALgAECgEJAQAAAA==.',
['氵萨']='氵萨:BAAALgAECgQJBAAAAA==.',
['永不']='永不为奴丶:BAAALgAFFAEJAQAAAA==.',
['永贞']='永贞:BAAALgAECgEJAQAAAA==.',
['汈着']='汈着艿觜菗煙:BAABLgAFFH8GAAIDAAMJJQV8CQDYAAADAAMJJQV8CQDYAAAAAA==.',
['江山']='江山一片红:BAAALgADCgIJAgAAAA==.',
['江楠']='江楠:BAAALgADCgYJBgAAAA==.',
['没事']='没事卖包丶:BAAALgAECgQJCgAAAA==.',
['没出']='没出息:BAABLgAFFH8GAAIaAAIJPx8vFQC7AAAaAAIJPx8vFQC7AAAAAA==.',
['没头']='没头脑丶枕戈:BAAALgAECgQJBAAAAA==.',
['没正']='没正经:BAAALgAECgQJBwAAAA==.',
['没谱']='没谱:BAAALgAECgQJCAAAAA==.',
['沧海']='沧海伊术:BAAALgAECgQJBAAAAA==.',
['沧笙']='沧笙踏歌:BAAALgAFFAIJBAAAAA==.',
['沧雪']='沧雪:BAABLgAFFH8KAAIGAAYJtyFHAwCgAQAGAAYJtyFHAwCgAQABLgAFFAYJDwAGAPgeAA==.',
['沪上']='沪上王糖逸珺:BAAALgAECgkJCQAAAA==.',
['法力']='法力失控:BAAALgAECgQJBAAAAA==.',
['法术']='法术易伤:BAAALgAFFAIJAwAAAA==.',
['法狮']='法狮:BAAALgAECgYJCgAAAA==.',
['法神']='法神小雨:BAAALgAFFAIJAwAAAA==.法神龙海柱:BAAALgAECgEJAQAAAA==.',
['泠灬']='泠灬鸢丶:BAAALgAECgQJBwAAAA==.',
['泡泡']='泡泡龙图腾:BAAALgAECgUJBQAAAA==.',
['泰寿']='泰寿鸠毛:BAAALgAECgYJBgAAAA==.',
['洛贝']='洛贝利亚尼:BAABLgAFFH8KAAMTAAQJGwxHEwAIAQATAAQJlwRHEwAIAQAUAAEJRR96HgBlAAABLgAFFAcJCgAGAO4cAA==.',
['流水']='流水妄言:BAAALgAECgYJDAAAAA==.',
['流浪']='流浪的沙丁鱼:BAAALgAFFAEJAQAAAA==.',
['流萤']='流萤丶:BAAALgAECgIJAgAAAA==.',
['浪漫']='浪漫血液:BAAALgAFFAIJAgAAAA==.',
['浮生']='浮生一盏:BAAALgADCgYJBgABLgAECgQJBgACAAAAAA==.浮生为欢几何:BAAALgADCgQJCQAAAA==.',
['浴场']='浴场执事:BAAALgAECgEJAQAAAA==.',
['海公']='海公牛:BAAALgAECgMJBQAAAA==.',
['海棠']='海棠味棒棒糖:BAABLgAECn8WAAMKAAgJtwxaPACQAQAKAAgJtwxaPACQAQAQAAMJlweKcgB4AAAAAA==.',
['海鹞']='海鹞:BAAALgAFFAIJAgAAAA==.',
['淋疯']='淋疯:BAAALgAECgYJDAAAAA==.',
['淡淡']='淡淡紫灵丶:BAAALgAFFAQJBAAAAA==.',
['深入']='深入调查:BAAALgAECgQJBQAAAA==.',
['深渊']='深渊使徒:BAAALgAECgUJBQAAAA==.深渊流浪:BAAALgADCgQJBAAAAA==.深渊统御:BAAALgAECgYJCwAAAA==.',
['淺唱']='淺唱灬清风:BAACLgAFFH8OAAILAAUJVhrDAgDKAQALAAUJVhrDAgDKAQAuAAQKfxoAAwsABwnNHfoRAGsCAAsABwnNHfoRAGsCABcABglLFxwcALUBAAAA.',
['清纯']='清纯男高:BAAALgADCgEJAQAAAA==.',
['清风']='清风墨魂:BAAALgAECgEJAQAAAA==.',
['渊冰']='渊冰:BAABLgAFFH8JAAIGAAQJGBzHEwB8AQAGAAQJGBzHEwB8AQABLgAFFAYJDwAGAPgeAA==.',
['温柔']='温柔的爱丽丝:BAAALgAECgcJEQAAAA==.',
['温西']='温西尔丶:BAAALgAFFAIJAwAAAA==.',
['温雷']='温雷萨斯:BAAALgAECgkJEgAAAA==.',
['湮灭']='湮灭丶丶:BAAALgAFFAEJAgAAAA==.',
['溜得']='溜得快:BAAALgAECgEJAQAAAA==.',
['溜达']='溜达溜达:BAAALgAFFAMJAwAAAA==.',
['滚滚']='滚滚圆的阳阳:BAAALgADCgQJBAAAAA==.',
['满眼']='满眼丨星辰:BAAALgAECgQJCAAAAA==.',
['满肾']='满肾:BAABLgAFFH8IAAIJAAQJsxDGCABgAQAJAAQJsxDGCABgAQABLgAFFAYJCQAJALMQAA==.',
['澄虑']='澄虑:BAAALgAECgYJCQAAAA==.',
['澄貓']='澄貓:BAAALgAECgYJDAAAAA==.',
['灞气']='灞气威武:BAACLgAFFH8IAAIcAAMJdCPWDQA8AQAcAAMJdCPWDQA8AQAuAAQKfxQAAhwABwkmHcg1AEsCABwABwkmHcg1AEsCAAAA.',
['火树']='火树银花:BAAALgADCgQJBAAAAA==.',
['火灬']='火灬柴:BAAALgAECgcJBwAAAA==.',
['火爷']='火爷熏黑了风:BAABLgAFFH8IAAIjAAMJbSP9AAA/AQAjAAMJbSP9AAA/AQAAAA==.',
['灬不']='灬不堪重负灬:BAAALgAECgEJAgABLgAECgEJAgACAAAAAA==.',
['灬九']='灬九天应元灬:BAAALgAECgEJAgAAAA==.',
['灬劣']='灬劣人:BAAALgAECgIJAgAAAA==.',
['灬柒']='灬柒夜:BAAALgAECgEJAQAAAA==.',
['灬神']='灬神丶澈丨:BAAALgAECgQJBAAAAA==.',
['灬茉']='灬茉莉清茶灬:BAAALgAECgEJAQAAAA==.',
['灬逆']='灬逆碟灬:BAAALgAECgMJAwAAAA==.',
['灵丶']='灵丶法:BAAALgAFFAIJBAAAAA==.',
['灵巧']='灵巧的核桃:BAAALgAECgIJAgAAAA==.',
['灵焱']='灵焱邪神:BAAALgAECgEJAQAAAA==.',
['炎客']='炎客:BAAALgAECgcJBwAAAA==.',
['炫压']='炫压抑了:BAAALgADCgYJBgAAAA==.',
['炼狱']='炼狱镇长:BAAALgAFFAIJAgAAAA==.',
['炽焱']='炽焱丶:BAAALgAECgYJDQAAAA==.',
['炽翼']='炽翼丶天使:BAAALgADCgcJBwAAAA==.炽翼之殇:BAAALgAECgEJAQAAAA==.',
['烈咬']='烈咬陆鲨:BAAALgAFFAIJAgABLgAFFAUJEQAeAJEZAA==.',
['烈日']='烈日灼心:BAAALgAECgEJAQAAAA==.',
['烤冷']='烤冷面:BAAALgAECgYJBgAAAA==.',
['烤肉']='烤肉:BAAALgAECgEJAQABLgAECgQJBAACAAAAAA==.',
['烤肋']='烤肋条:BAAALgAECgQJBAAAAA==.',
['烽河']='烽河:BAABLgAFFH8MAAIGAAQJBRp0FAB4AQAGAAQJBRp0FAB4AQABLgAFFAYJDwAGAPgeAA==.',
['焖嘚']='焖嘚嘚:BAAALgAECgcJBgAAAA==.',
['無知']='無知:BAAALgAECgEJAQAAAA==.',
['無罪']='無罪的叹息:BAAALgAECgEJAgAAAA==.',
['焱焱']='焱焱大王:BAAALgAECgUJCAAAAA==.',
['煽情']='煽情的霊儿:BAAALgAECgMJAwAAAA==.',
['熊妮']='熊妮娜露:BAABLgAECn8bAAIGAAkJbSSMAQAOAwAGAAkJbSSMAQAOAwAAAA==.',
['熊猫']='熊猫也是喵:BAAALgAECgQJBwAAAA==.',
['熙渢']='熙渢:BAAALgAFFAEJAgAAAA==.',
['爆浆']='爆浆甜蛹:BAAALgADCgUJBwAAAA==.',
['爆炸']='爆炸吧核桃:BAAALgAECgQJBAAAAA==.',
['爱意']='爱意蒙蔽双眼:BAAALgAECgEJAQAAAA==.',
['爱我']='爱我苏联:BAACLgAFFH8KAAMiAAQJGRF7BQDXAAAiAAQJaQh7BQDXAAAgAAMJiBVIFADVAAAuAAQKfxsAAyIABwkRGOYbAP0BACIABwmTF+YbAP0BACAABgkbFGlIACABAAAA.',
['爱执']='爱执迷太好了:BAABLgAECn8ZAAMMAAkJDiAsAwAsAwAMAAkJax8sAwAsAwAXAAgJ7BvwCgCJAgAAAA==.',
['牛叉']='牛叉的牛:BAAALgAECgYJDAAAAA==.',
['牛大']='牛大辫:BAAALgADCgQJBAAAAA==.',
['牛蹄']='牛蹄筋好好吃:BAAALgAECgYJBgAAAA==.',
['牛顿']='牛顿真是牛:BAAALgAECgYJDQAAAA==.',
['牢和']='牢和队长:BAAALgAECgQJBAAAAA==.',
['牧笛']='牧笛轻扬:BAAALgAECgUJDQAAAA==.',
['特仑']='特仑苏射手:BAABLgAFFH8EAAMUAAIJGSS3DgDWAAAUAAIJGSS3DgDWAAATAAEJYwGULQA7AAAAAA==.',
['犇譱']='犇譱鱻:BAAALgAFFAEJAgAAAA==.',
['狂炫']='狂炫灬酷霸拽:BAAALgADCgQJBAAAAA==.',
['狐柒']='狐柒染:BAAALgAECgQJBAAAAA==.',
['狐狸']='狐狸眼:BAAALgAFFAQJBAAAAA==.',
['狗桑']='狗桑的小梨涡:BAAALgAECgUJDQAAAA==.',
['狗蛋']='狗蛋二世:BAAALgAECgEJAQAAAA==.',
['狩猎']='狩猎之王:BAAALgAECgMJAwAAAA==.',
['狮心']='狮心哈特:BAAALgAECgEJAQAAAA==.',
['狲悟']='狲悟空:BAAALgADCgEJAQAAAA==.',
['猎手']='猎手芒果:BAAALgAECgQJBAAAAA==.',
['猎魔']='猎魔灬精灵:BAAALgADCgQJBAAAAA==.',
['猛猛']='猛猛砸:BAABLgAFFH8GAAINAAIJlCFWGgC8AAANAAIJlCFWGgC8AAAAAA==.',
['猩红']='猩红薛迪凯:BAAALgADCgEJAQAAAA==.',
['猫洽']='猫洽洽:BAAALgAECgYJBgAAAA==.',
['猫爷']='猫爷德:BAABLgAECn8VAAIZAAgJlB0kCABgAgAZAAgJlB0kCABgAgAAAA==.',
['猫的']='猫的大姬:BAAALgAECgUJBQAAAA==.',
['献祭']='献祭之厅:BAAALgAECgQJBQAAAA==.献祭奈非天:BAAALgAECgEJAQAAAA==.',
['玄裳']='玄裳丶惑:BAAALgAECgcJBwAAAA==.',
['玉小']='玉小朵:BAAALgAECgMJBgABLgAECgYJBwACAAAAAA==.',
['王凯']='王凯丽:BAAALgAECgkJCgABLgAFFAcJCwAgAM0PAA==.',
['王孬']='王孬孬:BAAALgAECgUJDAABLgAFFAIJAgACAAAAAA==.',
['王尼']='王尼码:BAAALgAECgEJAQAAAA==.',
['王淼']='王淼淼:BAAALgAECgEJAQAAAA==.',
['王爱']='王爱玲:BAABLgAECn8UAAIRAAYJ4RjAXwCqAQARAAYJ4RjAXwCqAQAAAA==.',
['珞飒']='珞飒:BAAALgADCgEJAQAAAA==.',
['瑾小']='瑾小晴吖:BAAALgAECgUJAgAAAA==.',
['璇缥']='璇缥缈:BAAALgADCgYJBgAAAA==.',
['璟莲']='璟莲佰怒:BAAALgAECgcJDAAAAA==.璟莲百怒:BAAALgADCgEJAgAAAA==.',
['甸丶']='甸丶:BAABLgAFFH8NAAMMAAQJ2hl4BwD3AAAMAAMJiBd4BwD3AAAXAAMJQxjsBwD3AAAAAA==.',
['画圈']='画圈圈诅詋你:BAAALgAECgQJBAAAAA==.',
['疚梦']='疚梦丶:BAAALgAECgUJDAAAAA==.',
['疯狂']='疯狂划水:BAAALgADCgUJBQAAAA==.',
['疾旋']='疾旋鼬:BAAALgAECgkJDwAAAA==.',
['痛苦']='痛苦泡泡龙:BAAALgAECgEJAQAAAA==.',
['白桃']='白桃草莓冻糕:BAABLgAECn8VAAIcAAkJNyFAGgDMAgAcAAkJNyFAGgDMAgAAAA==.',
['白银']='白银圭丶:BAAALgAECgcJCAAAAA==.',
['白鲸']='白鲸丶:BAAALgAECggJDwABLgAFFAYJFAAcAHAeAA==.',
['白默']='白默曦:BAAALgAECgMJAwAAAA==.',
['百发']='百发百不中:BAAALgAECggJDgAAAA==.',
['皇家']='皇家恐怖卫士:BAAALgAECgYJCwAAAA==.',
['皮卡']='皮卡兵:BAAALgAECgYJCAAAAA==.皮卡卡超人:BAAALgAECgIJAQAAAA==.',
['皮套']='皮套儿:BAAALgAECgMJAwAAAA==.',
['皮皮']='皮皮撸:BAAALgAECgkJCQAAAA==.皮皮鳝:BAAALgAECgYJEQAAAA==.',
['盖亚']='盖亚大地:BAAALgAECgMJAwABLgAECgYJHwAaAFojAA==.',
['盾牌']='盾牌收集狂:BAAALgAECgYJCwAAAA==.',
['看你']='看你两边:BAAALgAECgYJCgAAAA==.',
['真叫']='真叫个色:BAAALgADCgQJBAAAAA==.',
['真的']='真的疼:BAAALgAECgIJAgAAAA==.',
['睡熊']='睡熊:BAAALgAFFAIJAwAAAA==.',
['睡眼']='睡眼惺忪:BAABLgAFFH8HAAMeAAMJ5QwrEACgAAAeAAIJPA0rEACgAAAdAAIJNRarEgCYAAAAAA==.',
['睿馨']='睿馨:BAAALgAECgcJCQABLgAFFAYJEAATAEkeAA==.',
['瞬萤']='瞬萤:BAAALgAFFAEJAgAAAA==.',
['知天']='知天易逆天难:BAAALgAECgYJBgAAAA==.',
['短笛']='短笛:BAAALgAECgMJAwAAAA==.',
['破丶']='破丶靈:BAAALgAFFAIJAgAAAA==.',
['硬就']='硬就行了:BAAALgAFFAMJBAAAAA==.',
['硬硬']='硬硬的皮蛋:BAABLgAECn8aAAMBAAkJ5B5MCwAnAwABAAkJ8R1MCwAnAwAfAAEJwCS4XgBmAAAAAA==.',
['碧圆']='碧圆:BAAALgAECgIJAgAAAA==.',
['神之']='神之破面:BAABLgAECn8WAAIDAAcJ1RdCJAA1AgADAAcJ1RdCJAA1AgAAAA==.',
['神圣']='神圣之印:BAAALgAECgEJAQAAAA==.',
['神怜']='神怜此恋:BAAALgAECgcJEAAAAA==.',
['神探']='神探威威猫:BAAALgAECgUJCAAAAA==.',
['神牛']='神牛哥:BAAALgAECgYJBwABLgAFFAUJAQACAAAAAA==.',
['神的']='神的宠儿:BAAALgADCgEJAQAAAA==.',
['神秘']='神秘天王:BAAALgAECgkJDwAAAA==.',
['神鬼']='神鬼二相性:BAAALgAECgUJBQAAAA==.',
['神龙']='神龙侠:BAAALgAECgIJBAAAAA==.',
['祥和']='祥和天下:BAAALgAECgEJAgAAAA==.',
['禽兽']='禽兽:BAAALgAECgQJBAAAAA==.',
['秀外']='秀外慧中丶:BAAALgADCgUJBQAAAA==.',
['秀气']='秀气胖胖:BAAALgAECgIJAgAAAA==.秀气邈邈:BAAALgAECgUJCAAAAA==.秀气霸霸:BAAALgAECgEJAQAAAA==.',
['秀灬']='秀灬儿:BAAALgAECgEJAQAAAA==.',
['秋凉']='秋凉若夜:BAAALgAECgEJAQABLgAECgQJBgACAAAAAA==.',
['秋高']='秋高看山:BAAALgADCgEJAQAAAA==.',
['秘奥']='秘奥义丶幻樱:BAACLgAFFH8RAAIGAAUJyhleCgBfAQAGAAUJyhleCgBfAQAuAAQKfx4AAgYACAlNIC4lAN4CAAYACAlNIC4lAN4CAAAA.',
['秘法']='秘法灵遥:BAAALgAECgQJBgAAAA==.',
['秦谷']='秦谷美铃:BAACLgAFFH8YAAIbAAgJWhsNAAD0AgAbAAgJWhsNAAD0AgAuAAQKfxwAAhsACQlMJTIAANsDABsACQlMJTIAANsDAAAA.',
['稍微']='稍微晚点:BAAALgAECgcJCAAAAA==.',
['空想']='空想家:BAAALgAFFAEJAQAAAA==.',
['空灵']='空灵圣殿:BAAALgAECgMJBQAAAA==.',
['突然']='突然地划水:BAAALgAECgYJDgAAAA==.',
['突突']='突突熊:BAAALgADCgYJBgAAAA==.',
['站我']='站我大雨里:BAAALgAFFAIJAgAAAA==.',
['章昕']='章昕湉:BAAALgAFFAEJAQAAAA==.',
['笑里']='笑里藏牙:BAAALgAECgIJAgAAAA==.',
['笨蛋']='笨蛋小狗:BAAALgAFFAIJAgAAAA==.',
['等过']='等过晚星丫:BAAALgAECgYJDAAAAA==.',
['筱丨']='筱丨柒:BAAALgAECgcJCgAAAA==.',
['箩落']='箩落萝博:BAAALgAECgUJBQAAAA==.',
['箭皇']='箭皇:BAAALgAECgMJAwAAAA==.',
['米修']='米修丶离开:BAAALgAECgQJEAAAAA==.米修丶蒹葭:BAAALgAECgYJDwAAAA==.',
['米兰']='米兰阳光:BAAALgAECgEJAQABLgAFFAYJBQATACQLAA==.',
['米津']='米津玄師丶:BAAALgAFFAIJAwAAAA==.',
['粥丨']='粥丨:BAAALgAECgEJAgAAAA==.',
['粥粥']='粥粥丨:BAAALgAECgQJBAAAAA==.粥粥灬:BAAALgADCggJCQAAAA==.',
['糖丷']='糖丷亓变:BAAALgAECgEJAgAAAA==.',
['糖块']='糖块儿:BAABLgAECn8hAAQRAAcJpxwDSgDsAQARAAcJshoDSgDsAQAVAAQJSB1tLgACAQASAAIJ/gypHQCEAAAAAA==.',
['糖灬']='糖灬狠甜:BAAALgAECgUJBQAAAA==.',
['糖门']='糖门大小丶姐:BAAALgADCgEJAQAAAA==.',
['素还']='素还眞:BAAALgAECgQJBQABLgAFFAcJDQAFAM4ZAA==.',
['紫惑']='紫惑天神:BAAALgAECgYJBwAAAA==.',
['紫薯']='紫薯地瓜球:BAAALgAFFAIJAgABLgAFFAMJBwAeAOUMAA==.',
['繁华']='繁华一梦:BAAALgAECgYJCwAAAA==.繁华终散尽:BAAALgADCgUJBQAAAA==.',
['红尘']='红尘三尺剑:BAABLgAFFH8FAAIIAAMJ+BjnCQATAQAIAAMJ+BjnCQATAQAAAA==.',
['红豆']='红豆霸霸奶茶:BAAALgAECgYJBwAAAA==.',
['红酥']='红酥手丶:BAAALgAECgMJAwAAAA==.',
['约德']='约德尔大王丶:BAAALgAECgUJBQAAAA==.',
['纯丨']='纯丨牛奶:BAAALgAECgIJBAAAAA==.',
['纯情']='纯情丶糯米糍:BAAALgADCgUJBQAAAA==.',
['纸飞']='纸飞鸡:BAABLgAFFH8FAAIKAAMJBCbQAwBVAQAKAAMJBCbQAwBVAQAAAA==.',
['组我']='组我必灭团:BAACLgAFFH8HAAIKAAQJbw6QCQA4AQAKAAQJbw6QCQA4AQAuAAQKfxQAAgoACQkIF/wVAGYCAAoACQkIF/wVAGYCAAAA.',
['终末']='终末日历:BAAALgAECgYJCAAAAA==.',
['终结']='终结屠一族:BAABLgAFFH8IAAIFAAMJrAkfCQDAAAAFAAMJrAkfCQDAAAAAAA==.',
['给德']='给德爷跪下:BAAALgAECgQJBAAAAA==.',
['给我']='给我热依扎:BAAALgAECgMJAQAAAA==.',
['绝尘']='绝尘狂煞:BAABLgAFFH8GAAIUAAIJIiW9DgDWAAAUAAIJIiW9DgDWAAAAAA==.',
['绝望']='绝望的叹息丶:BAAALgAECgcJCQAAAA==.',
['绽放']='绽放一夏:BAAALgAECgkJCQAAAA==.',
['绿鲤']='绿鲤驴与绿鱼:BAAALgAECgEJAQAAAA==.',
['缄默']='缄默:BAAALgAECgkJBQAAAA==.',
['缓缓']='缓缓归矣:BAAALgAFFAQJBAAAAA==.',
['缱绻']='缱绻:BAABLgAFFH8HAAIGAAUJ+R1uBACOAQAGAAUJ+R1uBACOAQABLgAFFAYJDwAGAPgeAA==.缱绻天蓝:BAAALgAECgEJAQAAAA==.缱绻小龙人:BAAALgAFFAEJAQAAAA==.',
['罟尔']='罟尔刐:BAAALgAFFAIJAwAAAA==.',
['羊丷']='羊丷丷:BAAALgAECgQJBAAAAA==.',
['美昱']='美昱欣:BAAALgAFFAQJAgAAAA==.',
['美曦']='美曦:BAAALgAECgYJDwAAAA==.',
['羲浑']='羲浑氏:BAACLgAFFH8HAAMdAAMJsRerCACxAAAdAAMJsRerCACxAAAeAAIJmwWYHACMAAAuAAQKfxYABB4ABwktDmMtAFYBAB4ABwktDmMtAFYBAA8ABgmMAmsrAMEAAB0ABQmOC8IOAHkAAAAA.',
['翌发']='翌发入魂:BAAALgAECgYJBwAAAA==.',
['翩若']='翩若惊鸿灬:BAACLgAFFH8OAAIgAAUJxyanAABGAgAgAAUJxyanAABGAgAuAAQKfyQAAiAACAnPJswBAIoDACAACAnPJswBAIoDAAAA.',
['耀世']='耀世之手:BAAALgAECgEJAQAAAA==.',
['老于']='老于死毒舌:BAAALgAECgUJCgAAAA==.',
['老傅']='老傅:BAABLgAECn8VAAIkAAcJGxjNAQCqAQAkAAcJGxjNAQCqAQAAAA==.',
['老曌']='老曌:BAAALgAECgEJAQAAAA==.',
['耄耋']='耄耋骚年:BAAALgAFFAIJAgAAAA==.',
['者使']='者使灵亡:BAAALgAECgUJBQAAAA==.',
['耳朵']='耳朵龙:BAAALgAFFAMJBAAAAA==.',
['聆听']='聆听我心:BAAALgAFFAEJAQAAAA==.',
['职业']='职业男人:BAAALgAECgYJCAAAAA==.职业萨满:BAAALgADCgEJAQAAAA==.',
['肉包']='肉包丨肉包:BAAALgADCgEJAQAAAA==.',
['肉啃']='肉啃肉:BAAALgADCgUJCgAAAA==.',
['肉隐']='肉隐肉现:BAAALgAECgYJBgAAAA==.',
['背叛']='背叛者丶之怒:BAAALgAECgIJAgAAAA==.',
['胖小']='胖小丷:BAAALgAECgYJCAAAAA==.',
['胡周']='胡周周:BAAALgAECgYJCAAAAA==.',
['胡桃']='胡桃夹子乄:BAABLgAFFH8IAAIJAAUJcxPUAgDQAQAJAAUJcxPUAgDQAQABLgAFFAYJCQAJALMQAA==.',
['胡萝']='胡萝卜温度计:BAAALgAECgEJAQAAAA==.',
['胶囊']='胶囊:BAAALgAECgcJBwAAAA==.',
['能兜']='能兜住史:BAAALgAECgcJBwAAAA==.',
['能量']='能量扭曲:BAAALgAECgYJBgAAAA==.',
['自由']='自由丶:BAAALgAFFAQJBAAAAA==.自由化身:BAAALgAECgMJAwAAAA==.',
['臭呆']='臭呆:BAAALgAECgQJBQAAAA==.',
['臭臭']='臭臭毛:BAAALgAECgYJBwAAAA==.',
['般若']='般若卿子:BAAALgAFFAQJBAABLgAFFAUJEQAQANoDAA==.',
['色孽']='色孽泠骨:BAAALgAECgEJAQAAAA==.',
['色家']='色家娇妻:BAABLgAFFH8FAAIaAAUJihueAgDKAQAaAAUJihueAgDKAQAAAA==.',
['艾莉']='艾莉媤灬:BAAALgAFFAEJAQAAAA==.',
['艾莫']='艾莫萘子:BAAALgAECgYJCwAAAA==.',
['艾露']='艾露玛灬:BAAALgAECgYJBgAAAA==.',
['芙兰']='芙兰朵璐:BAABLgAECn8jAAIGAAcJOB4pFADBAQAGAAcJOB4pFADBAQAAAA==.',
['芙莉']='芙莉莲洒玛:BAAALgAECgEJAQAAAA==.',
['花亊']='花亊了丶:BAAALgAECgMJAwAAAA==.',
['花傲']='花傲天:BAACLgAFFH8IAAMXAAMJjyXpCQBAAQAXAAMJ6CPpCQBAAQAMAAEJUCYACQB0AAAuAAQKfyoABBcABwlDJpIEABEDABcABwk/JpIEABEDAAwABgm7IioTAEYCAAsAAQlsB4lfADkAAAAA.',
['花灬']='花灬榜:BAAALgAECgMJBAAAAA==.',
['花自']='花自有期:BAAALgAECgUJCQAAAA==.',
['苏婆']='苏婆猫嘟:BAABLgAECn8WAAIRAAkJLyQxAQDEAwARAAkJLyQxAQDEAwAAAA==.',
['苏小']='苏小妹:BAAALgADCggJBgAAAA==.',
['苏晴']='苏晴:BAAALgAECgQJBgAAAA==.',
['若叶']='若叶睦:BAAALgAECgYJBgAAAA==.',
['若水']='若水有尘:BAAALgADCgEJAQAAAA==.',
['若氷']='若氷有尘:BAAALgADCgIJAgAAAA==.',
['若能']='若能绽放光芒:BAAALgAECgQJAgAAAA==.',
['苦橙']='苦橙:BAACLgAFFH8PAAIcAAQJdh2mBwB4AQAcAAQJdh2mBwB4AQAuAAQKfygAAhwACAkZJU4HAF0DABwACAkZJU4HAF0DAAEuAAUUBwkEAAIAAAAA.',
['英勇']='英勇的刘老师:BAAALgAECgYJCwAAAA==.',
['英雄']='英雄联盟丶:BAAALgAECgEJAQAAAA==.',
['茴香']='茴香柠檬茶:BAAALgAECgkJCQAAAA==.',
['草莓']='草莓灬宝贝:BAAALgADCgEJAQAAAA==.',
['荒歌']='荒歌:BAAALgADCgQJBAAAAA==.',
['荒野']='荒野飙客:BAACLgAFFH8IAAMNAAMJhxjvIAAVAQANAAMJhxjvIAAVAQAkAAIJdxA4AwCtAAAuAAQKfxUAAw0ACAmlGy82AF4CAA0ABwmYHC82AF4CACQAAQnuFf0JAEsAAAAA.',
['荖瞎']='荖瞎眼:BAAALgAFFAMJAwAAAA==.',
['莉娜']='莉娜乄:BAAALgAFFAIJAgAAAA==.',
['莉莉']='莉莉斯:BAABLgAECn8YAAMWAAcJ3BlgCADMAQAWAAYJ8xtgCADMAQAJAAYJbBD4NgBaAQAAAA==.',
['莫瓦']='莫瓦死神:BAAALgAECgcJDQAAAA==.',
['菜鸟']='菜鸟头头:BAAALgAECgIJAgAAAA==.',
['萌萌']='萌萌的小宝:BAAALgAECgcJDgABLgAFFAQJCAANAIwcAA==.萌萌的灰瞳酱:BAAALgAECgQJBQAAAA==.',
['萨兰']='萨兰淖尔:BAAALgADCgcJBwAAAA==.',
['萨安']='萨安德洒:BAAALgAECgYJCgAAAA==.',
['落花']='落花似水:BAAALgAFFAQJBAAAAA==.落花有意:BAAALgAECgUJBQAAAA==.',
['葡萄']='葡萄冰萃:BAAALgAECgYJBgAAAA==.葡萄套:BAABLgAECn8WAAINAAkJQBMETAAPAgANAAkJQBMETAAPAgAAAA==.葡萄芋圆冻冻:BAAALgADCgcJBwAAAA==.',
['葫芦']='葫芦里有药:BAAALgAECgEJAQAAAA==.',
['葬魂']='葬魂挽歌:BAAALgAECgYJEgAAAA==.',
['葱烧']='葱烧排骨面:BAACLgAFFH8IAAIRAAMJUyP4CQBDAQARAAMJUyP4CQBDAQAuAAQKfxYAAxEACAkgI5UhAJACABEABwkgI5UhAJACABUAAQkAAIdbAFwAAAAA.',
['蒜了']='蒜了算了:BAAALgADCgcJBwAAAA==.',
['蒸的']='蒸的油猫饼:BAAALgAFFAMJBAABLgAFFAYJCwAGAL0cAA==.',
['蒸蚌']='蒸蚌:BAABLgAECn8dAAIcAAkJuR/dDQAfAwAcAAkJuR/dDQAfAwAAAA==.',
['蓝晔']='蓝晔:BAACLgAFFH8QAAIGAAUJlyXOCwC/AQAGAAUJlyXOCwC/AQAuAAQKfxwAAwYACAn6JSkQAEcDAAYACAn6JSkQAEcDACUABAk5Fn0IAN8AAAAA.',
['蔷薇']='蔷薇再开:BAAALgAECgYJDAAAAA==.',
['蕓染']='蕓染霓裳:BAABLgAFFH8GAAIMAAMJUxUlBQDWAAAMAAMJUxUlBQDWAAAAAA==.',
['蕶灬']='蕶灬:BAAALgAECgYJDAAAAA==.',
['薄荷']='薄荷奶绿:BAAALgAECgYJBgAAAA==.',
['藤原']='藤原千花:BAAALgAECgMJBAAAAA==.',
['虎皮']='虎皮猫大人丶:BAABLgAFFH8KAAIcAAQJ1RwdBwB+AQAcAAQJ1RwdBwB+AQAAAA==.',
['虚空']='虚空头头:BAAALgADCgIJAgAAAA==.',
['虾扯']='虾扯蛋:BAAALgAECgQJBAAAAA==.',
['蛋挞']='蛋挞冲啊:BAAALgAECgEJAQAAAA==.',
['蛋蛋']='蛋蛋的微笑:BAAALgAECgYJCQAAAA==.',
['蜘蛛']='蜘蛛切:BAAALgAECgUJAwAAAA==.',
['蜜桃']='蜜桃乌龍:BAAALgAECgEJAQAAAA==.',
['蜻蜓']='蜻蜓大队长:BAAALgAECgYJBgAAAA==.',
['蝎子']='蝎子莱莱:BAAALgAECgYJBgAAAA==.',
['血手']='血手丶人屠:BAAALgAECgYJEQAAAA==.',
['血染']='血染双眸:BAAALgAECgUJBgAAAA==.',
['血祭']='血祭云鬼:BAAALgAECgQJBQAAAA==.',
['血色']='血色命运:BAAALgAECgEJAQAAAA==.血色死骑:BAAALgAFFAQJBAAAAA==.血色蔓延:BAAALgAECgQJBgAAAA==.',
['血蹄']='血蹄村小霸王:BAAALgAECgEJAQAAAA==.',
['行有']='行有余力:BAAALgADCgEJAQAAAA==.',
['街角']='街角的樱花:BAAALgAECggJDgAAAA==.',
['西尔']='西尔维娅:BAAALgAECgYJCQAAAA==.',
['西行']='西行亖幽幽子:BAACLgAFFH8TAAIOAAcJkxW/AACyAQAOAAcJkxW/AACyAQAuAAQKfx0AAg4ACQlpHUoIAKACAA4ACQlpHUoIAKACAAEuAAUUCAkYABsAWhsA.西行寺幽幽子:BAAALgAECgQJEAAAAA==.',
['要你']='要你命叄千:BAAALgAECgIJAgAAAA==.',
['讨厌']='讨厌你大坏蛋:BAAALgAECgUJCAAAAA==.',
['让我']='让我田里扫雪:BAAALgAECgUJBQAAAA==.',
['记忆']='记忆星幽:BAAALgAFFAIJAwAAAA==.',
['许丶']='许丶文强:BAAALgAECgUJBQAAAA==.',
['诚惠']='诚惠彳:BAAALgAFFAEJAgAAAA==.',
['诸天']='诸天之法:BAAALgAECgYJBgAAAA==.',
['诸葛']='诸葛撼野:BAAALgAECgQJBQAAAA==.',
['谷宝']='谷宝:BAAALgAECgYJCAABLgAFFAQJBwAGAEsTAA==.谷宝战:BAABLgAECn8WAAMDAAYJkBrJSQB9AQADAAYJ1hbJSQB9AQAEAAMJthzQHgD4AAABLgAFFAQJBwAGAEsTAA==.',
['象大']='象大的放奔:BAAALgAECgEJAQAAAA==.',
['贝加']='贝加庞克:BAAALgADCgQJBAAAAA==.',
['贝阿']='贝阿朵的幻蝶:BAAALgAECgYJCAAAAA==.',
['赛博']='赛博棒棒鸡:BAAALgAFFAIJAgAAAA==.',
['超长']='超长带鱼:BAAALgAECgYJCwAAAA==.',
['越玩']='越玩越没心:BAAALgAECgUJBQAAAA==.',
['路上']='路上的爱:BAAALgAECgMJBAAAAA==.',
['路丶']='路丶西法:BAAALgAECgQJBgAAAA==.',
['路在']='路在丶何方:BAAALgAFFAIJAwAAAA==.',
['路然']='路然轻:BAAALgAECgcJBgAAAA==.',
['路过']='路过的木木:BAAALgADCgcJBgAAAA==.',
['踏踏']='踏踏牛:BAAALgADCgEJAQAAAA==.',
['踏雪']='踏雪荨梅:BAAALgAECgUJBgAAAA==.',
['踏风']='踏风贼鸡强:BAAALgADCgMJAwAAAA==.',
['轩哥']='轩哥太狠了:BAAALgAECgYJDwABLgAFFAQJBwAGAEsTAA==.',
['转身']='转身就走:BAAALgADCgUJBQAAAA==.',
['轻梦']='轻梦星河:BAAALgAECgYJDAAAAA==.',
['轻狂']='轻狂彡龙爷:BAAALgAECgcJCAAAAA==.',
['辛德']='辛德拉苟薩:BAAALgAECgQJBAAAAA==.',
['辣个']='辣个咕咕:BAAALgAFFAEJAQAAAA==.',
['边渡']='边渡佑次子:BAAALgAECgUJCgAAAA==.',
['过不']='过不明白卒:BAAALgAFFAQJBAAAAA==.',
['过河']='过河卒:BAAALgAFFAIJAgAAAA==.过河卒卒啊:BAAALgAFFAMJAQAAAA==.',
['这啥']='这啥呀这是:BAACLgAFFH8HAAMTAAQJSREHEAAxAQATAAQJSREHEAAxAQAUAAEJ6gWxHgBQAAAuAAQKfxcAAhMACAnII7MJAAUDABMACAnII7MJAAUDAAAA.',
['这是']='这是个萨:BAAALgAECgEJAQAAAA==.',
['这波']='这波不亏:BAAALgAECgYJDAAAAA==.',
['进潜']='进潜进潜进潜:BAAALgAECgUJBQAAAA==.',
['迪丽']='迪丽大热芭:BAAALgAECgUJBQAAAA==.',
['迫不']='迫不德已:BAAALgAFFAIJAwAAAA==.',
['迷你']='迷你猪灬小白:BAAALgAECgcJBwAAAA==.',
['迷失']='迷失天使之痛:BAAALgAECgkJAQAAAA==.',
['送佛']='送佛送到南:BAAALgAECgMJBAAAAA==.',
['逐日']='逐日圣光:BAAALgAECgYJBgAAAA==.',
['逝水']='逝水留香:BAAALgAECgEJAQAAAA==.',
['逢赌']='逢赌必输:BAAALgAECgYJBwAAAA==.',
['道德']='道德泥石流:BAAALgADCgcJBwAAAA==.',
['道貌']='道貌岸然耶:BAAALgADCgEJAQAAAA==.',
['遥望']='遥望致远星:BAAALgAFFAIJAwAAAA==.',
['邂逅']='邂逅丶:BAAALgAFFAQJBAABLgAFFAYJCgANAM8MAA==.',
['那个']='那个牧湿:BAAALgAECgkJCQAAAA==.',
['邦邦']='邦邦:BAABLgAFFH8GAAIDAAIJpyGRFADJAAADAAIJpyGRFADJAAAAAA==.',
['邪之']='邪之神罚:BAAALgAECgQJBgAAAA==.',
['邪恶']='邪恶伽蓝:BAAALgAECgMJAwAAAA==.邪恶的核桃:BAAALgAFFAEJAQAAAA==.',
['邪暴']='邪暴:BAAALgAECgMJAwAAAA==.',
['邮电']='邮电部诗人:BAAALgAECgMJAwAAAA==.',
['郁闷']='郁闷的地瓜:BAAALgAECgMJAwAAAA==.',
['酒僧']='酒僧:BAAALgAECgYJCgAAAA==.',
['酷酷']='酷酷圣骑:BAAALgAECgQJBAAAAA==.',
['酸奶']='酸奶不是很酸:BAAALgAECgkJCQAAAA==.',
['醉丶']='醉丶清尘:BAABLgAFFH8IAAIKAAUJdyMwAQD5AQAKAAUJdyMwAQD5AQAAAA==.',
['醉得']='醉得扛不住:BAAALgAECgcJBQAAAA==.',
['醉长']='醉长亭魔:BAAALgAECgUJCgAAAA==.',
['采丶']='采丶采:BAAALgAFFAEJAQAAAA==.',
['里昂']='里昂纳多:BAAALgAECgYJBwAAAA==.',
['野兽']='野兽控制丶:BAAALgAECgEJAgAAAA==.',
['錒木']='錒木:BAAALgAECgEJAgAAAA==.',
['鎏哖']='鎏哖如歌:BAAALgAECggJEAAAAA==.',
['鏖戰']='鏖戰阿纳:BAABLgAFFH8NAAINAAQJ1hX9CABHAQANAAQJ1hX9CABHAQAAAA==.',
['钢角']='钢角大王:BAAALgAFFAQJAgAAAA==.',
['钢铁']='钢铁妖男:BAAALgAECgIJAwAAAA==.',
['铁蛋']='铁蛋想吃啥:BAABLgAFFH8IAAIKAAMJRBr5CADrAAAKAAMJRBr5CADrAAAAAA==.',
['铁衣']='铁衣在旅行:BAAALgAECgQJBQAAAA==.',
['铁锤']='铁锤灬妹妹:BAAALgADCgcJCAAAAA==.',
['铁骨']='铁骨丹心:BAAALgAECggJCAAAAA==.',
['铅笔']='铅笔与硬币:BAAALgAFFAEJAgAAAA==.',
['铭天']='铭天:BAAALgAECgQJBgAAAA==.',
['银月']='银月之怜:BAABLgAECn8VAAMBAAkJuBnyEwDgAgABAAkJuBnyEwDgAgAfAAYJExE0MwA+AQAAAA==.',
['锋丨']='锋丨行:BAAALgAECgEJAgAAAA==.',
['锤飞']='锤飞你是我:BAAALgAFFAEJAQAAAA==.',
['锦年']='锦年的酒仙:BAAALgAECgUJBQAAAA==.',
['长亭']='长亭灬清寒:BAACLgAFFH8GAAMaAAMJFgN+EwBtAAAaAAIJ8AF+EwBtAAAHAAIJXAEdHQBAAAAuAAQKfxcABAcACAktDLhFABcBAAcABQlLELhFABcBABoABwmAB5tpABYBABsAAQkzA4Y6ABEAAAAA.',
['開車']='開車不喝酒:BAAALgAECgYJCgAAAA==.',
['闪电']='闪电舞连鞭:BAAALgADCgUJBQAAAA==.',
['闫明']='闫明好朋友:BAAALgAECgUJBwAAAA==.',
['闲逸']='闲逸的云:BAAALgAECgcJDAAAAA==.',
['阈界']='阈界巡狩:BAAALgAECgcJCQAAAA==.',
['阳光']='阳光真强猎:BAAALgAECgEJAQAAAA==.',
['阿列']='阿列克谢深蓝:BAABLgAECn8aAAMIAAcJJx1ABAAdAgAIAAcJJx1ABAAdAgAgAAYJ5wwkTgALAQAAAA==.',
['阿利']='阿利斯牠:BAAALgAECgQJCAABLgAFFAUJEAAKALAWAA==.阿利路亚丶:BAAALgAECgYJBwAAAA==.',
['阿十']='阿十六:BAAALgAFFAQJBAAAAA==.',
['阿奴']='阿奴:BAAALgAECgYJBgAAAA==.',
['阿尔']='阿尔杨罗本:BAAALgAECgQJBAAAAA==.阿尔萨丝:BAAALgAECgIJAgAAAA==.',
['阿笛']='阿笛达斯:BAAALgAECgEJAQAAAA==.',
['阿纳']='阿纳克斯神:BAAALgAECgEJAgAAAA==.',
['阿达']='阿达兽:BAABLgAFFH8IAAIUAAMJJBDrCwADAQAUAAMJJBDrCwADAQAAAA==.',
['阿遥']='阿遥:BAAALgAECgUJCQAAAA==.',
['陈伯']='陈伯:BAAALgAECgUJCwAAAA==.',
['陈局']='陈局:BAAALgAECgEJAQAAAA==.',
['陈萍']='陈萍萍:BAABLgAECn8YAAIRAAkJfiASBQBqAwARAAkJfiASBQBqAwAAAA==.',
['陌上']='陌上丶丶:BAAALgAFFAIJBAAAAA==.',
['随水']='随水漂流:BAAALgAECgYJEgAAAA==.',
['隐姓']='隐姓埋灬名:BAAALgAECgMJAwAAAA==.',
['隔壁']='隔壁的老黄:BAAALgAECgUJBgAAAA==.隔壁舅妈:BAAALgAECgQJBAAAAA==.',
['雄鹰']='雄鹰般的女人:BAAALgAFFAIJAgAAAA==.',
['雅典']='雅典娜丶:BAAALgAECgEJAQAAAA==.',
['集火']='集火那个小德:BAAALgAECgYJBgAAAA==.集火那个武僧:BAACLgAFFH8OAAINAAQJIyHJAwB3AQANAAQJIyHJAwB3AQAuAAQKfxUAAg0ABwkcIi8pAJUCAA0ABwkcIi8pAJUCAAAA.集火那个萨满:BAAALgAECgcJDgAAAA==.',
['雨小']='雨小盐:BAABLgAFFH8IAAIcAAMJEBwBEAAnAQAcAAMJEBwBEAAnAQAAAA==.',
['雨薇']='雨薇薇:BAAALgADCgUJBQAAAA==.',
['雪中']='雪中悍刀行:BAAALgAECggJAQAAAA==.',
['雪落']='雪落飘痕:BAAALgAECgEJAwAAAA==.雪落黎明:BAAALgAECgEJAgAAAA==.',
['雪靈']='雪靈:BAAALgAECgkJCQABLgAFFAMJCAAYAM0MAA==.',
['雪音']='雪音丶小贱:BAAALgAECgQJBAAAAA==.',
['零壹']='零壹:BAAALgAECgEJAQAAAA==.',
['雷惊']='雷惊天地:BAAALgAECgkJCQAAAA==.',
['雷电']='雷电彡法王:BAAALgADCgcJBwAAAA==.',
['雷霆']='雷霆加赞:BAAALgAECgkJEgAAAA==.雷霆大王:BAAALgAECgQJBAAAAA==.',
['霜之']='霜之嗨:BAAALgADCgQJBAAAAA==.霜之暴风:BAAALgAECgQJBAAAAA==.霜之雷霆:BAAALgADCgIJAgAAAA==.',
['霜轮']='霜轮:BAABLgAFFH8JAAIGAAUJsxgkBgB7AQAGAAUJsxgkBgB7AQABLgAFFAYJDwAGAPgeAA==.',
['霸气']='霸气丶有沐有:BAAALgAECgEJAQAAAA==.霸气灬允默:BAAALgAECgYJCQAAAA==.',
['霸霸']='霸霸僧:BAAALgAFFAEJAgAAAA==.',
['靈灬']='靈灬:BAAALgAECgQJBAAAAA==.',
['青梅']='青梅配柠檬:BAAALgAFFAIJAgAAAA==.',
['青豌']='青豌豆:BAAALgAECgQJAgAAAA==.',
['非酋']='非酋:BAABLgAECn8aAAINAAcJvCRsGQDkAgANAAcJvCRsGQDkAgAAAA==.',
['面对']='面对波波吧:BAAALgAECgYJCQAAAA==.',
['頂風']='頂風做案:BAAALgADCgQJBAAAAA==.',
['顽皮']='顽皮的小火:BAAALgADCgYJAQAAAA==.',
['顾北']='顾北丶:BAAALgAFFAMJAgAAAA==.',
['風湮']='風湮灭了夏雨:BAAALgADCgQJBAAAAA==.',
['風純']='風純:BAAALgAECgYJBgAAAA==.',
['風螢']='風螢:BAAALgAECggJCAAAAA==.',
['风痕']='风痕九号:BAAALgAECgYJBgAAAA==.',
['飘如']='飘如陌上尘:BAAALgAECgYJEgAAAA==.',
['飙车']='飙车光环:BAAALgAECgEJAQAAAA==.',
['饭饭']='饭饭特别稀:BAAALgADCgIJAgAAAA==.',
['饮血']='饮血翡翠:BAABLgAFFH8GAAIFAAMJPgm2BQC8AAAFAAMJPgm2BQC8AAAAAA==.',
['饿魔']='饿魔:BAAALgAECgEJAQAAAA==.',
['香克']='香克斯:BAAALgAECgUJBwAAAA==.香克斯丶:BAAALgAFFAIJAgAAAA==.',
['香菇']='香菇牛丸子:BAAALgAECgIJAgAAAA==.',
['马小']='马小宝儿:BAAALgAECgkJCQAAAA==.',
['马波']='马波尼:BAAALgAECgYJEwAAAA==.',
['驭邪']='驭邪焚荒:BAAALgAECgEJAQAAAA==.',
['骄傲']='骄傲放纵:BAAALgAFFAEJAQAAAA==.',
['骑着']='骑着毛驴的牛:BAAALgADCgQJBAAAAA==.',
['高大']='高大帅:BAAALgAECgYJBwAAAA==.',
['高橋']='高橋南:BAAALgAFFAIJAgAAAA==.',
['高阶']='高阶司机:BAAALgAECgEJAQAAAA==.',
['髪剋']='髪剋骜氟:BAAALgAECgEJAQAAAA==.',
['鬼火']='鬼火配雪花:BAAALgAECgYJCwAAAA==.',
['鬼的']='鬼的电话号码:BAAALgADCgIJAgAAAA==.',
['魂断']='魂断丨楼兰:BAAALgAFFAEJAQAAAA==.',
['魔兽']='魔兽:BAAALgAECgcJDwAAAA==.',
['魔力']='魔力喷粉咒:BAAALgADCgQJBAAAAA==.',
['鯊人']='鯊人如麻哥:BAAALgAECgYJAgABLgAFFAQJBAACAAAAAA==.',
['鱼音']='鱼音:BAAALgAECgIJAgAAAA==.',
['鲜花']='鲜花配烈酒:BAAALgAECgIJAwAAAA==.',
['鲜血']='鲜血雷鸣飒:BAAALgAECgEJAwAAAA==.',
['鲨鱼']='鲨鱼圣骑:BAAALgAECgYJBgAAAA==.',
['鸡柳']='鸡柳火腿卷饼:BAABLgAECn8YAAIcAAYJ1hsubQCjAQAcAAYJ1hsubQCjAQAAAA==.',
['鸡纠']='鸡纠纠:BAACLgAFFH8hAAIBAAgJ9B4xAAAfAwABAAgJ9B4xAAAfAwAuAAQKfyAAAwEACQkXJa0BAMEDAAEACQnLJK0BAMEDAB8ABwk+IN8WABMCAAAA.',
['鸡腿']='鸡腿:BAAALgAECgcJCQAAAA==.鸡腿不见了:BAAALgAECgQJBAAAAA==.',
['鸽子']='鸽子奶奶:BAAALgAECgkJDwAAAA==.',
['鹭岛']='鹭岛逸少:BAAALgAFFAEJAQAAAA==.',
['鹿岛']='鹿岛丨:BAAALgAECgYJBwAAAA==.鹿岛丶:BAAALgAECgYJBgAAAA==.',
['麗丶']='麗丶惊雨:BAAALgAFFAEJAQAAAA==.',
['麦子']='麦子丶:BAAALgAECgQJCAAAAA==.',
['麦晓']='麦晓鼠:BAAALgAECgYJCgAAAA==.',
['麦迪']='麦迪汶:BAAALgAECgkJAgAAAA==.',
['麻呱']='麻呱朮士:BAAALgAECgYJBgAAAA==.',
['麻尔']='麻尔蛋蛋炮:BAABLgAFFH8IAAIRAAMJsBKzEgD/AAARAAMJsBKzEgD/AAAAAA==.',
['麻辣']='麻辣甜小龙虾:BAAALgAECgUJBQAAAA==.',
['黑山']='黑山万兽无疆:BAAALgAFFAEJAQAAAA==.',
['黑暗']='黑暗异灵:BAAALgAFFAIJAgAAAA==.',
['黑猛']='黑猛牛:BAAALgADCgEJAQAAAA==.',
['黑皮']='黑皮体育生哟:BAABLgAECn8YAAIBAAgJahtFJgBtAgABAAgJahtFJgBtAgAAAA==.',
['黑羽']='黑羽兽:BAAALgAECgEJAgAAAA==.黑羽喵:BAAALgAECgEJAQAAAA==.黑羽圣:BAAALgAECgEJAgAAAA==.',
['黑莓']='黑莓乌托邦:BAAALgADCgUJBQAAAA==.',
['黑锋']='黑锋瘸子领主:BAAALgAFFAIJAgAAAA==.',
['黑魔']='黑魔兽土灵:BAAALgAECgIJAgAAAA==.',
['黛溪']='黛溪:BAAALgAECgEJAwAAAA==.',
['鼻子']='鼻子頂豆:BAAALgAECgYJCwAAAA==.',
['龍丶']='龍丶风暴烈酒:BAAALgAECgEJAQAAAA==.',
['龙人']='龙人不会飞:BAAALgADCgYJAQAAAA==.',
['龙山']='龙山区昆凌:BAAALgAFFAIJAgAAAA==.',
['龙德']='龙德广场:BAAALgAECgQJBAABLgAFFAUJBAACAAAAAA==.',
['龙筱']='龙筱玉:BAAALgAECgMJAwAAAA==.龙筱雨:BAAALgAECgUJBQAAAA==.',
['龙驭']='龙驭者:BAAALgAECgYJBgAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
