local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Mage-Frost','Hunter-Marksmanship','Druid-Restoration','Unknown-Unknown','DemonHunter-Havoc','DemonHunter-Devourer','Shaman-Restoration','DeathKnight-Unholy','DeathKnight-Blood','Paladin-Holy','Priest-Discipline','Monk-Brewmaster','Paladin-Protection','Rogue-Subtlety','Shaman-Elemental','Priest-Holy','Warlock-Demonology','Warlock-Destruction','Paladin-Retribution','Warlock-Affliction','Warrior-Fury','Warrior-Arms','Shaman-Enhancement','Druid-Balance','Druid-Feral','Hunter-BeastMastery','Evoker-Preservation','DemonHunter-Vengeance','DeathKnight-Frost','Druid-Guardian','Evoker-Augmentation','Monk-Mistweaver','Monk-Windwalker','Priest-Shadow','Rogue-Outlaw','Evoker-Devastation','Mage-Arcane','Mage-Fire','Warrior-Protection',}
local provider = {region='CN',realm='红龙军团',name='CN',type='weekly',zone=46,date='2026-04-25',data={Ab='Abcdefghijkl:BAAALgAECgQJBAAAAA==.',
Ac='Acexx:BAAALgAECgQJBAAAAA==.Acosta:BAAALgAFFAIJAgAAAA==.',
Ak='Akashas:BAABLgAFFH8KAAIBAAMJPhNvLQABAQABAAMJPhNvLQABAQAAAA==.',
Al='Alsyve:BAAALgAECgkJBwABLgAFFAUJCQACAAIQAA==.',
Am='Amelielacro:BAAALgAECgQJBAAAAA==.Amory:BAAALgAECgYJBgAAAA==.',
An='Angelabb:BAAALgAECgYJBgAAAA==.Anticlimax:BAABLgAFFH8IAAIBAAQJiyRBBACQAQABAAQJiyRBBACQAQAAAA==.',
Ar='Ares:BAAALgAFFAEJAQABLgAFFAMJCAADALoOAA==.',
Au='Austinrunner:BAAALgAFFAMJAwAAAA==.',
Av='Avaion:BAAALgAECgUJBgAAAA==.',
Aw='Awindrunner:BAAALgADCgQJBAABLgAECgEJAQAEAAAAAA==.',
Az='Azalia:BAAALgAECgYJBgAAAA==.',
Ba='Barbatos:BAAALgAECgcJDgAAAA==.',
Bi='Bigbing:BAAALgAECgYJCwAAAA==.',
Bl='Blackzero:BAAALgAECgIJAgAAAA==.',
Bo='Bone:BAAALgAECgcJBgAAAA==.',
Ca='Camelot:BAAALgAECgYJCQAAAA==.Carless:BAAALgADCgIJAgAAAA==.',
Ci='Ciri:BAAALgAECgQJBAAAAA==.',
Cl='Clanquire:BAACLgAFFH8HAAIFAAMJrQWnBgDdAAAFAAMJrQWnBgDdAAAuAAQKfxcAAwUACAlNG38EALMBAAUACAlNG38EALMBAAYAAQmtDQDnACsAAAAA.Cloudg:BAAALgAECgUJBQAAAA==.',
Cr='Crazypayer:BAAALgAECgcJBwAAAA==.',
Cu='Cuizj:BAAALgADCgUJBQAAAA==.',
Cy='Cybertein:BAAALgAECgYJBgAAAA==.',
Da='Daphne:BAAALgAECgkJCAAAAA==.Darmelon:BAAALgAFFAEJAQAAAA==.Dazzling:BAABLgAFFH8IAAIHAAQJwiADAgCUAQAHAAQJwiADAgCUAQAAAA==.',
Db='Dboy:BAAALgAECgYJCQAAAA==.',
De='Degenbrecher:BAABLgAECn8UAAIIAAcJkR8JLACIAgAIAAcJkR8JLACIAgAAAA==.Delsin:BAABLgAFFH8JAAICAAQJLRU1FAD8AAACAAQJLRU1FAD8AAAAAA==.Despair:BAABLgAFFH8JAAMJAAUJOR2qAgCiAQAJAAUJkByqAgCiAQAIAAQJhhZ/FgBKAQAAAA==.',
Di='Dissolve:BAAALgAFFAIJBAAAAA==.Dizzykit:BAACLgAFFH8JAAIHAAUJRxngAgCxAQAHAAUJRxngAgCxAQAuAAQKfxUAAgcACQn3HPUIAOcCAAcACQn3HPUIAOcCAAEuAAUUBQkSAAcArSIA.Dizzykitt:BAABLgAFFH8OAAIHAAUJHyHJAQDcAQAHAAUJHyHJAQDcAQAAAA==.Dizzykitto:BAABLgAFFH8NAAIHAAUJABqyAQChAQAHAAUJABqyAQChAQAAAA==.',
Dk='Dkriss:BAAALgAECgUJAwAAAA==.',
Do='Doub:BAAALgAECgMJAwAAAA==.',
El='Elves:BAAALgAECgIJAwAAAA==.',
Er='Erio:BAAALgAECgcJBwAAAA==.',
Eu='Eulogizee:BAAALgAECgUJBQAAAA==.',
Fo='Fota:BAAALgAECgEJBAAAAA==.',
Fu='Furry:BAAALgAECgQJBAABLgAFFAQJBAAEAAAAAA==.',
Hi='Hixxc:BAABLgAECn8WAAIKAAcJxBgQKADsAQAKAAcJxBgQKADsAQAAAA==.',
Ho='Honeydragon:BAAALgADCgEJAQAAAA==.Honeysxj:BAAALgADCgMJBAAAAA==.',
Hs='Hsibbur:BAAALgAECgkJCgABLgAFFAYJBgALAGgbAA==.Hsyndrome:BAAALgAECgUJDAAAAA==.',
Hu='Hullbreaker:BAAALgAECgYJCgAAAA==.',
Ic='Icey:BAABLgAECn8dAAIMAAgJqAlnOwBaAQAMAAgJqAlnOwBaAQAAAA==.',
Il='Illya:BAAALgAECgIJAgAAAA==.',
In='Incomprise:BAAALgAECgMJAwAAAA==.',
Is='Isla:BAAALgAECgkJCQAAAA==.',
Ja='Jainna:BAACLgAFFH8IAAIBAAMJGwmIMADwAAABAAMJGwmIMADwAAAuAAQKfxgAAgEABwmDH+lFAGYCAAEABwmDH+lFAGYCAAAA.',
Jo='Jormungand:BAAALgAFFAUJAQABLgAFFAUJCQAJADkdAA==.',
Ju='Jude:BAAALgAECgMJAwABLgAECgcJBwAEAAAAAA==.',
Ka='Kairy:BAAALgAECgkJDwAAAA==.',
Kc='Kckc:BAAALgAFFAQJBAAAAA==.',
Ki='Kido:BAABLgAECn8XAAINAAcJQRDxEwCNAQANAAcJQRDxEwCNAQAAAA==.Kiriko:BAAALgADCgYJBgAAAA==.',
Kk='Kkdht:BAAALgAECgIJAgAAAA==.',
Ko='Kojuro:BAAALgAECgUJCQAAAA==.',
Ma='Mageffa:BAABLgAECn8ZAAIBAAYJHSEqDwDvAQABAAYJHSEqDwDvAQAAAA==.',
Mk='Mkipooxxs:BAAALgADCgMJAwAAAA==.Mkipxoox:BAAALgAECgEJAQAAAA==.',
Mn='Mnhero:BAAALgAECgkJCQAAAA==.',
Mo='Morgan:BAAALgAECgMJAwAAAA==.Moxl:BAAALgAECgYJBQAAAA==.',
Mt='Mtou:BAAALgAECgQJBAAAAA==.',
No='Novalis:BAAALgAECgUJCQAAAA==.',
On='Onlydeath:BAAALgADCgMJAwAAAA==.',
Op='Oprometheus:BAAALgAECggJEwAAAA==.',
Or='Orange:BAAALgAECgEJAQAAAA==.',
Pe='Perrita:BAABLgAFFH8IAAIDAAMJug5JDgCoAAADAAMJug5JDgCoAAAAAA==.',
Ph='Phantomx:BAAALgAECgQJAwAAAA==.',
Pi='Piew:BAAALgAECgMJAwAAAA==.Pisces:BAABLgAECn8VAAIOAAYJ8hm0BwCHAQAOAAYJ8hm0BwCHAQAAAA==.',
Pl='Playermlipfz:BAAALgAECgMJBQAAAA==.Playeryzdtcw:BAAALgAFFAEJAQAAAA==.',
Po='Poro:BAAALgAECgIJAgABLgAFFAYJFgAPAMUZAA==.Potato:BAABLgAFFH8GAAMQAAQJAyK9BAA6AQAQAAMJESO9BAA6AQALAAEJ2B4aFwBgAAAAAA==.',
Pr='Prologue:BAAALgAFFAQJBAABLgAFFAUJEgAHAK0iAA==.',
Ps='Psychéend:BAAALgAECgcJBwAAAA==.',
Pu='Purity:BAAALgAFFAMJAwAAAA==.Push:BAAALgADCgMJAwAAAA==.',
Ra='Rafael:BAAALgAECgEJAQAAAA==.Raybreath:BAAALgAECgEJAgAAAA==.',
Re='Redme:BAACLgAFFH8GAAICAAMJhh+uEQAeAQACAAMJhh+uEQAeAQAuAAQKfxoAAgIABwlDJCgTAJkCAAIABwlDJCgTAJkCAAAA.Relaxs:BAAALgAFFAEJAgAAAA==.Remains:BAABLgAECn8XAAMGAAgJWxj5QADwAQAGAAcJvRf5QADwAQAFAAMJaxuAQAD4AAAAAA==.Rexa:BAAALgAECgUJBQAAAA==.',
Ri='Right:BAAALgADCgYJAQAAAA==.',
Ro='Rosin:BAACLgAFFH8NAAIRAAUJLCB6BADXAQARAAUJLCB6BADXAQAuAAQKfxwAAxEACAmQJOELABsDABEACAmQJOELABsDABIAAwmbFus4ANEAAAAA.Rox:BAAALgAECgcJDAAAAA==.',
Ru='Ruien:BAAALgAECgcJEQAAAA==.Rush:BAAALgAECgIJAwAAAA==.',
Ry='Ryota:BAAALgAFFAEJAQAAAA==.Ryougimana:BAAALgAECgQJBAAAAA==.Ryougishiki:BAAALgAECgIJAgAAAA==.',
Rz='Rztfqs:BAABLgAECn8WAAMKAAcJIRk3MwCxAQAKAAYJ9Bs3MwCxAQATAAQJ7RwDKQAqAQAAAA==.',
Sa='Sanctus:BAABLgAECn8XAAMFAAYJZSAXJQCVAQAFAAUJMiIXJQCVAQAGAAYJOhUaXwCEAQAAAA==.',
Se='Sevensuger:BAAALgAECgUJEAAAAA==.',
Sg='Sgmax:BAAALgADCgEJAQAAAA==.Sgoesdfg:BAAALgAECgUJBwAAAA==.',
Sh='Shizuka:BAAALgADCgYJBgAAAA==.Shuaims:BAAALgAECgYJBAAAAA==.Shuaism:BAABLgAFFH8FAAIHAAIJkw/QGACYAAAHAAIJkw/QGACYAAAAAA==.',
Sk='Skullbrook:BAAALgAECgUJBQAAAA==.',
Sm='Smallforesta:BAAALgAECgIJAwAAAA==.',
Sp='Spiral:BAABLgAFFH8KAAIHAAUJrSCAAADxAQAHAAUJrSCAAADxAQABLgAFFAUJEgAHAK0iAA==.',
Su='Superko:BAAALgAECgUJBQAAAA==.Superq:BAABLgAFFH8JAAIBAAMJRSAmEwAZAQABAAMJRSAmEwAZAQAAAA==.',
Ta='Tatum:BAAALgAECgEJAQAAAA==.',
Th='Theendearing:BAAALgAECgYJBwAAAA==.Thepoor:BAAALgAECgEJAQAAAA==.Theresa:BAAALgAECgQJAgAAAA==.Thesavior:BAAALgADCgUJCAAAAA==.',
To='Tomorin:BAAALgAECgEJAQAAAA==.',
Tr='Traingazing:BAAALgAFFAQJBAABLgAFFAUJEgAHAK0iAA==.',
Um='Umbrion:BAAALgAECgUJBQAAAA==.',
Ve='Veritasium:BAAALgAECgUJBQABLgAECgcJBwAEAAAAAA==.',
Vi='Vira:BAAALgAFFAEJAQAAAA==.',
We='Westdoor:BAAALgADCgEJAQAAAA==.',
Wi='Wintermelon:BAAALgAECgYJEQABLgAFFAQJBgAQAAMiAA==.',
Wo='Wolo:BAAALgAECgMJAwAAAA==.Woloo:BAAALgAFFAEJAQAAAA==.',
Xy='Xyzshield:BAAALgAECgcJCAAAAA==.',
Yi='Yisoo:BAAALgAECgIJAwAAAA==.',
Yo='Yooz:BAAALgAECgQJBAAAAA==.',
Zo='Zos:BAAALgAFFAEJAQAAAA==.Zouldh:BAAALgAECgUJCAAAAA==.',
['一切']='一切丶:BAABLgAFFH8KAAIHAAMJ3SGKCwAgAQAHAAMJ3SGKCwAgAQAAAA==.',
['一剑']='一剑西来:BAAALgAFFAEJAQAAAA==.',
['一力']='一力丹:BAAALgAFFAQJBAABLgAFFAYJAgAEAAAAAA==.',
['一千']='一千年以后丶:BAAALgAECgcJDQAAAA==.',
['一只']='一只喵:BAAALgAECgEJAQAAAA==.一只张小爆:BAAALgAECgYJBAAAAA==.',
['一头']='一头纯牛马:BAAALgADCgYJCgAAAA==.',
['一岁']='一岁杀豪猪:BAAALgADCgYJBgAAAA==.',
['一把']='一把寒酸泪:BAAALgADCgYJBgAAAA==.',
['一斤']='一斤竹又:BAAALgAECgcJDgAAAA==.',
['一条']='一条鱼啊:BAAALgADCgUJBgAAAA==.',
['一枪']='一枪一个准:BAAALgAECgMJBAABLgAECgUJBQAEAAAAAA==.',
['一眼']='一眼瞬间:BAABLgAFFH8NAAIGAAQJ2QzODAAVAQAGAAQJ2QzODAAVAQAAAA==.',
['一粒']='一粒沙可覆海:BAAALgAECgQJBQAAAA==.',
['一航']='一航宝:BAAALgAECgQJBwAAAA==.',
['一草']='一草一木:BAAALgAECgYJCQAAAA==.',
['一起']='一起数星星吗:BAAALgAFFAIJAgAAAA==.',
['一黑']='一黑白一:BAABLgAECn8YAAQTAAkJvB/KBwBXAwATAAkJvB/KBwBXAwAKAAIJFwzbhQBhAAANAAEJLwIOTAAbAAAAAA==.',
['丁又']='丁又丁不懂:BAAALgAECgUJBQABLgAECgYJDAAEAAAAAA==.',
['丁灬']='丁灬磊:BAAALgAECgEJAgAAAA==.',
['七个']='七个球:BAAALgAECgQJBAAAAA==.',
['七月']='七月里娣樱桃:BAACLgAFFH8JAAIIAAQJ/BeaDABxAQAIAAQJ/BeaDABxAQAuAAQKfyMAAggACQnZImAEAI4DAAgACQnZImAEAI4DAAAA.',
['三分']='三分妖气:BAAALgAFFAIJAgAAAA==.',
['三本']='三本钩:BAACLgAFFH8OAAMRAAQJFyZ0AQC0AQARAAQJYCV0AQC0AQASAAIJXCViCADgAAAuAAQKfxwABBEABwkqIIQ7AB4CABEABwkqIIQ7AB4CABIABAnlI0kaAHsBABQAAglMJTMWANEAAAAA.',
['三皮']='三皮牛牛:BAAALgAECgEJAQAAAA==.',
['上帝']='上帝卡卡:BAAALgAECgQJBQAAAA==.',
['下次']='下次你请:BAAALgADCgMJBAAAAA==.',
['不会']='不会做冰激凌:BAAALgAECgEJAQAAAA==.',
['不吃']='不吃石头:BAAALgADCgMJAwAAAA==.',
['不屈']='不屈的云吞面:BAAALgADCgkJCQAAAA==.不屈的意志:BAAALgAECgEJAQAAAA==.不屈的斗志:BAAALgAECgEJAQAAAA==.不屈的猎手:BAAALgADCggJCAAAAA==.',
['不是']='不是猫丶:BAAALgAECgMJAwAAAA==.',
['不破']='不破愛花丶:BAAALgAECgYJBwAAAA==.',
['不能']='不能缺德的:BAAALgAECgEJAQAAAA==.',
['不起']='不起名字了:BAAALgAFFAIJAgAAAA==.',
['丙午']='丙午狂龙:BAAALgAECgYJBgAAAA==.',
['东莞']='东莞张学友:BAAALgAECgIJAwAAAA==.',
['东风']='东风谷丶早苗:BAAALgADCgEJAQAAAA==.',
['丨一']='丨一切丨:BAAALgAECgIJAgAAAA==.',
['丨乌']='丨乌冬丨:BAABLgAFFH8GAAIDAAIJaRghFwCoAAADAAIJaRghFwCoAAABLgAFFAQJDwACAD0aAA==.',
['丨德']='丨德罪丨:BAAALgADCgcJBwAAAA==.',
['丨月']='丨月下丶心花:BAAALgAFFAIJAgAAAA==.',
['丨椛']='丨椛前丶枂芐:BAAALgAECgUJBQAAAA==.',
['丨泉']='丨泉此方丨:BAAALgADCgUJBQAAAA==.',
['丨空']='丨空空:BAAALgAFFAQJBAAAAA==.',
['丨贼']='丨贼丶帅:BAAALgAECgEJAQAAAA==.',
['丨飞']='丨飞火灵晔丨:BAAALgAECgUJBQAAAA==.',
['中军']='中军光一:BAAALgAECgYJCgAAAA==.',
['中有']='中有千千结:BAAALgAECgkJEAAAAA==.',
['临江']='临江仙:BAAALgAECgEJAQAAAA==.',
['丶五']='丶五月:BAAALgAECgEJAgAAAA==.',
['丶大']='丶大米:BAABLgAFFH8HAAMJAAMJew1yDQCVAAAJAAMJYQ1yDQCVAAAIAAEJOgKAOABDAAAAAA==.',
['丶常']='丶常威丶:BAACLgAFFH8JAAIVAAQJMxE2CwBLAQAVAAQJMxE2CwBLAQAuAAQKfygAAxUACAlQH28VAKICABUACAlQH28VAKICABYABwnZF2cKAAACAAAA.',
['丶晚']='丶晚枫:BAAALgAECgcJCgAAAA==.',
['丶林']='丶林夕:BAABLgAFFH8FAAIBAAMJZBQ7GAD9AAABAAMJZBQ7GAD9AAAAAA==.',
['丶枫']='丶枫:BAAALgAECgMJAwAAAA==.',
['丶橘']='丶橘子酱:BAAALgAECgQJBQAAAA==.',
['丶橙']='丶橙月:BAAALgAECggJDgAAAA==.',
['丶湮']='丶湮灭:BAAALgAECgEJAQAAAA==.',
['丶溜']='丶溜溜柒:BAAALgAECgEJAQAAAA==.',
['丶猎']='丶猎:BAAALgAECgYJBQAAAA==.',
['丶艾']='丶艾雅法拉:BAACLgAFFH8QAAIBAAQJviBvBACOAQABAAQJviBvBACOAQAuAAQKfyUAAgEACAmFJTULAGoDAAEACAmFJTULAGoDAAAA.',
['丶贰']='丶贰一:BAABLgAECn8XAAITAAcJfBhxWwDRAQATAAcJfBhxWwDRAQAAAA==.',
['丶黑']='丶黑白:BAAALgADCgQJBAAAAA==.',
['丶龙']='丶龙虾:BAAALgAECgQJCwAAAA==.',
['丷妃']='丷妃:BAAALgAECgYJBgAAAA==.',
['丷無']='丷無情丷:BAAALgAECgYJBgAAAA==.',
['丷骑']='丷骑士:BAAALgAECgYJCgAAAA==.',
['为丶']='为丶你而战:BAAALgAECgQJBAAAAA==.',
['举起']='举起爪来:BAAALgAFFAEJAQAAAA==.',
['丿半']='丿半杯拿铁丿:BAAALgAFFAEJAQAAAA==.',
['丿无']='丿无尽:BAACLgAFFH8MAAIBAAQJExk1CgBgAQABAAQJExk1CgBgAQAuAAQKfxYAAgEABwmqGl9kABACAAEABwmqGl9kABACAAAA.',
['丿沐']='丿沐丶齐齐:BAACLgAFFH8HAAIXAAMJ/g5sAwD5AAAXAAMJ/g5sAwD5AAAuAAQKfyYAAxcACAmSGpgHAG4CABcACAmSGpgHAG4CAAcABwlbC0NNAE4BAAAA.',
['丿源']='丿源丶:BAACLgAFFH8FAAIVAAMJARMeEQD+AAAVAAMJARMeEQD+AAAuAAQKfyAAAxUACAkBHpgNAOkCABUACAkBHpgNAOkCABYAAQmkDRJBADYAAAAA.',
['么脾']='么脾气的靓仔:BAAALgAFFAIJAgAAAA==.',
['乌丑']='乌丑:BAAALgADCgMJAwAAAA==.',
['乐姐']='乐姐的青春荳:BAAALgAECgYJBgAAAA==.',
['乔小']='乔小钰:BAAALgAECgUJBwAAAA==.',
['乖乖']='乖乖不是猫:BAAALgAECgUJBQAAAA==.',
['九一']='九一号:BAAALgAFFAEJAgAAAA==.',
['九死']='九死犹未悔:BAAALgADCgQJBQAAAA==.',
['九里']='九里虎:BAAALgAECgcJBgAAAA==.',
['乱搞']='乱搞乱发财:BAAALgAECgYJDQAAAA==.',
['乱粒']='乱粒丑急:BAAALgAECgMJAgAAAA==.',
['乾坤']='乾坤豆豆:BAAALgAECgYJBgAAAA==.',
['乾爻']='乾爻:BAAALgAECgUJBgAAAA==.',
['二十']='二十丶旭:BAABLgAFFH8KAAIGAAQJmxejEQBCAQAGAAQJmxejEQBCAQAAAA==.二十年:BAAALgAECgMJAwAAAA==.',
['二哈']='二哈僧:BAAALgADCgQJBAAAAA==.二哈德:BAAALgADCgEJAQAAAA==.二哈恶魔:BAAALgADCgYJBgAAAA==.',
['云与']='云与幽灵:BAACLgAFFH8JAAIHAAUJZCAWAQABAgAHAAUJZCAWAQABAgAuAAQKfx0AAgcACQkcHnwFABoDAAcACQkcHnwFABoDAAEuAAUUBQkSAAcArSIA.',
['云天']='云天岚:BAAALgAECgcJDQAAAA==.',
['云璃']='云璃:BAAALgAECgcJCgAAAA==.',
['五丶']='五丶月:BAAALgAECgYJBgAAAA==.',
['五火']='五火:BAAALgAECgEJAgAAAA==.',
['五菱']='五菱汽车:BAAALgAECgYJAgAAAA==.',
['亚坦']='亚坦尼斯:BAACLgAFFH8HAAMNAAMJZhVjAgDkAAANAAMJZhVjAgDkAAATAAIJ3gIHGQCMAAAuAAQKfx0AAw0ABwl7ILYHAGICAA0ABwl7ILYHAGICABMABQmKClA/ANAAAAAA.',
['亚格']='亚格:BAAALgAECgEJAQAAAA==.',
['亡魂']='亡魂之羽:BAABLgAFFH8FAAITAAIJ1BPwJgCcAAATAAIJ1BPwJgCcAAAAAA==.',
['亥伯']='亥伯龙:BAAALgAFFAIJAgAAAA==.',
['京东']='京东白嫖:BAAALgADCgYJBgAAAA==.',
['人参']='人参公鸡:BAAALgAECgIJAgAAAA==.',
['今晚']='今晚看我的:BAAALgADCgUJBQAAAA==.',
['介孔']='介孔碳子:BAAALgAECgUJBQAAAA==.',
['从小']='从小就低调:BAAALgADCgkJCQAAAA==.',
['从此']='从此无犄角:BAAALgAECgQJBAAAAA==.',
['仓鼠']='仓鼠丸子:BAAALgAFFAMJAwAAAA==.',
['以符']='以符:BAAALgADCgEJAQAAAA==.',
['仲夏']='仲夏夜猫:BAAALgAECgcJDAAAAA==.仲夏残阳:BAAALgAECgkJCQAAAA==.',
['任风']='任风过也不错:BAAALgAECgcJBwAAAA==.',
['仼者']='仼者丶暗影:BAAALgAECgEJAQAAAA==.',
['伊利']='伊利達雷:BAAALgAECgIJAwAAAA==.',
['伊莱']='伊莱亚:BAAALgAFFAEJAQABLgAFFAUJDwAYAHsmAA==.伊莱克斯血皇:BAAALgADCgIJAgAAAA==.',
['会长']='会长小肘花:BAAALgADCgYJBgAAAA==.',
['伦鲁']='伦鲁迪洛尓:BAAALgAECgEJAQAAAA==.',
['估咚']='估咚:BAAALgAECgMJAwAAAA==.',
['估计']='估计快了:BAAALgADCgYJBgAAAA==.',
['低調']='低調叁索男:BAAALgAECgEJAQAAAA==.',
['何所']='何所见:BAAALgAECgMJAwAAAA==.',
['你也']='你也想起舞么:BAAALgAFFAEJAQAAAA==.',
['你什']='你什么意思丶:BAAALgAFFAcJAgAAAA==.',
['你卤']='你卤味:BAAALgAECgMJAwAAAA==.',
['你懂']='你懂完了:BAABLgAFFH8FAAIGAAUJixhdBgC9AQAGAAUJixhdBgC9AQABLgAFFAYJAgAEAAAAAA==.',
['你是']='你是不是猪头:BAAALgAFFAQJBAAAAA==.',
['你没']='你没一分像她:BAABLgAFFH8FAAIFAAUJhBUiAQCpAQAFAAUJhBUiAQCpAQAAAA==.',
['侃侃']='侃侃丶怒风:BAAALgAECgcJDQAAAA==.',
['依然']='依然丶小的:BAAALgAECgYJDQAAAA==.',
['保修']='保修卡:BAAALgAECgcJAwAAAA==.',
['修罗']='修罗牌浪:BAAALgAECgYJBwABLgAFFAMJBgANAEwNAA==.',
['俺叫']='俺叫肥点:BAAALgAECgQJBAAAAA==.',
['做人']='做人不候刀:BAAALgAECgQJBAAAAA==.',
['偷油']='偷油的耗子:BAAALgAECgEJAQAAAA==.',
['偷睡']='偷睡:BAAALgAECgIJAgAAAA==.',
['傅里']='傅里叶:BAAALgAFFAIJBAAAAA==.',
['僵尸']='僵尸娃娃:BAAALgAECgMJBAAAAA==.',
['元气']='元气少女李逵:BAAALgAECgEJAQAAAA==.',
['兄弟']='兄弟你好香阿:BAAALgAECgEJAQAAAA==.',
['光之']='光之裁决:BAAALgAECgEJAQABLgAECgIJAgAEAAAAAA==.',
['克雷']='克雷西佩耶尔:BAAALgAECgYJBgAAAA==.',
['全凭']='全凭感觉:BAAALgAECgEJAQAAAA==.',
['全身']='全身冰凉:BAAALgAECgMJAwAAAA==.',
['全部']='全部灭:BAAALgAECgEJAQAAAA==.',
['八百']='八百狸丨熊叔:BAAALgADCgYJCgAAAA==.',
['八神']='八神庵:BAAALgAECgcJDwAAAA==.',
['八零']='八零后老帅哥:BAABLgAFFH8FAAMYAAUJ7wMMDgD+AAAYAAQJ7wMMDgD+AAADAAEJlRzQIQBbAAAAAA==.',
['六六']='六六的小霖子:BAABLgAECn8bAAIBAAgJgCAUHgD9AgABAAgJgCAUHgD9AgAAAA==.',
['六条']='六条鱼:BAAALgAECgUJBgAAAA==.',
['关键']='关键丶先生:BAAALgADCgEJAQAAAA==.',
['典狱']='典狱长的舔狗:BAABLgAFFH8FAAMYAAMJGxt4DAAdAQAYAAMJGxt4DAAdAQADAAIJ9Qv3HACJAAAAAA==.',
['养一']='养一隻死一隻:BAAALgAECgEJAQAAAA==.',
['兽女']='兽女只会冲锋:BAAALgADCgcJBwAAAA==.',
['冉飞']='冉飞:BAAALgAECgEJAQAAAA==.',
['再次']='再次路过的人:BAAALgAECgEJAQAAAA==.',
['冠军']='冠军儿:BAABLgAFFH8FAAIDAAMJPBWPCgDcAAADAAMJPBWPCgDcAAAAAA==.',
['冥锋']='冥锋:BAAALgAECgkJBAAAAA==.',
['冬日']='冬日烟火:BAABLgAFFH8LAAIHAAUJJyDBBQBvAQAHAAUJJyDBBQBvAQABLgAFFAUJEgAHAK0iAA==.',
['冯洪']='冯洪语:BAABLgAFFH8GAAMTAAMJ0yAeEAAmAQATAAMJ0yAeEAAmAQANAAEJSg3lBwA4AAAAAA==.',
['冰凝']='冰凝嘟嘟:BAACLgAFFH8HAAIYAAMJmwZnEADaAAAYAAMJmwZnEADaAAAuAAQKfxcABBgABwkhGlwdABUCABgABwkhGlwdABUCABkAAglEA54zADMAAAMAAQnwEDLQAC4AAAAA.',
['冰柠']='冰柠薄荷:BAAALgADCgQJBAAAAA==.',
['冰白']='冰白咖啡:BAAALgAECgYJAQAAAA==.',
['冲锋']='冲锋撞枪口:BAAALgAECgEJAQAAAA==.',
['冷凝']='冷凝艳:BAAALgAECggJCAAAAA==.',
['凉生']='凉生初雨:BAAALgAECgUJBgAAAA==.',
['凌霄']='凌霄仙子:BAAALgAECgIJAwAAAA==.',
['凝思']='凝思:BAAALgADCgIJAgAAAA==.',
['凯恩']='凯恩丶血怒:BAAALgAECgMJAQAAAA==.',
['凶残']='凶残的瑶瑶:BAACLgAFFH8HAAIBAAMJxANeMQDoAAABAAMJxANeMQDoAAAuAAQKfxwAAgEACAlnFG1hABcCAAEACAlnFG1hABcCAAAA.',
['刀斧']='刀斧手:BAAALgAFFAEJAQAAAA==.',
['刘新']='刘新建:BAAALgAECgEJAQABLgAFFAIJBAAEAAAAAA==.',
['刘狈']='刘狈和狲权:BAAALgAECgYJBgAAAA==.',
['利冰']='利冰兰:BAAALgAECgYJCAAAAA==.',
['别拽']='别拽黑皮耳朵:BAAALgAFFAEJAgAAAA==.',
['别摸']='别摸我腹肌:BAAALgAECgcJBgAAAA==.',
['别追']='别追着我打啦:BAAALgADCgEJAQAAAA==.',
['刹那']='刹那握住未来:BAAALgAFFAIJAgAAAA==.',
['前男']='前男友:BAAALgADCgcJBwAAAA==.',
['剑仙']='剑仙艾瑞莉娅:BAAALgAECgYJBwAAAA==.',
['劣质']='劣质活动假人:BAACLgAFFH8GAAIIAAIJWR+qNwCsAAAIAAIJWR+qNwCsAAAuAAQKfxQAAwgABwk1GzxXAOwBAAgABwk1GzxXAOwBAAkABAmMBSw6AHIAAAAA.',
['勇士']='勇士雅哈:BAAALgADCgYJBgAAAA==.',
['勇度']='勇度:BAAALgAECgIJAgAAAA==.',
['勒芒']='勒芒:BAAALgAECgEJAQAAAA==.',
['化吾']='化吾为王:BAACLgAFFH8QAAQSAAUJ+BmTCADXAAARAAMJ/RqkGwAXAQASAAMJQgyTCADXAAAUAAIJzwcjAgBRAAAuAAQKfxwAAxEACQmbGggWANECABEACQmnGQgWANECABIABQkkExcfAFgBAAAA.',
['北冥']='北冥有余:BAAALgAECgEJAQAAAA==.',
['北方']='北方锁钥:BAAALgAECgEJAQAAAA==.',
['十八']='十八厘米含头:BAAALgADCgMJAwAAAA==.十八号当铺:BAAALgADCgMJAwAAAA==.十八號:BAAALgAECgEJAQAAAA==.',
['十誡']='十誡:BAAALgAECgEJAQAAAA==.',
['千刀']='千刀雪:BAAALgAECgIJAgAAAA==.',
['千山']='千山鳥飛绝:BAAALgAECgMJAwAAAA==.',
['千岛']='千岛冰龙:BAAALgAECgIJAgAAAA==.',
['千思']='千思百道:BAAALgAECgYJCgAAAA==.',
['半楼']='半楼城:BAAALgAECgEJAgAAAA==.',
['华筝']='华筝:BAABLgAFFH8FAAIaAAIJpxx+EADEAAAaAAIJpxx+EADEAAAAAA==.',
['南山']='南山不落梅:BAACLgAFFH8FAAMaAAIJGiKYEAC1AAACAAIJOiGXGADKAAAaAAIJVhaYEAC1AAAuAAQKfxsAAxoACAn/HUMdAFYCABoABgkgI0MdAFYCAAIABgkcGQkyAKUBAAAA.',
['占戈']='占戈灬哥欠:BAAALgAECgEJAgAAAA==.',
['卡卡']='卡卡洛斯:BAAALgAECgEJAgAAAA==.',
['卡尔']='卡尔洛斯:BAAALgAFFAEJAQAAAA==.',
['卡巴']='卡巴档胶粘:BAAALgAECgYJDgAAAA==.',
['卫攻']='卫攻士狼丶:BAAALgAECgYJCQAAAA==.',
['历久']='历久弥新:BAAALgAECgEJAQAAAA==.',
['厚切']='厚切西冷瓜:BAAALgAECgQJBAAAAA==.',
['厨神']='厨神小当家:BAAALgAECgcJEAABLgAFFAQJCAAIAKEkAA==.',
['双魚']='双魚理:BAACLgAFFH8GAAIBAAMJJyHXJQAcAQABAAMJJyHXJQAcAQAuAAQKfxUAAgEABwmlIZYuALgCAAEABwmlIZYuALgCAAEuAAUUBgkLAAEAxRsA.',
['双龙']='双龙入氵同:BAACLgAFFH8HAAIbAAMJvBByDgDwAAAbAAMJvBByDgDwAAAuAAQKfyEAAhsABwnZGz8SABsCABsABwnZGz8SABsCAAAA.',
['叛逆']='叛逆游轩子:BAAALgAECgUJCQAAAA==.',
['古堡']='古堡龙姬:BAAALgAECgcJBwAAAA==.',
['古墓']='古墓天神:BAAALgADCgYJBgAAAA==.古墓狂笑:BAAALgADCgYJBgAAAA==.',
['古爸']='古爸爸一号:BAAALgAECgEJAQAAAA==.',
['叨叨']='叨叨致命丶:BAAALgAECgcJCwAAAA==.',
['只放']='只放门不拉人:BAABLgAFFH8IAAIRAAMJYRkrEAAOAQARAAMJYRkrEAAOAQAAAA==.',
['只穿']='只穿四角裤:BAAALgADCgQJBAAAAA==.',
['只要']='只要功夫深:BAAALgAECgMJAwAAAA==.',
['叮丁']='叮丁鼎町:BAAALgADCgEJAQAAAA==.',
['司牧']='司牧:BAAALgAFFAEJAQAAAA==.',
['吃饭']='吃饭没钱给:BAAALgAECgYJBgAAAA==.',
['向前']='向前向前向前:BAAALgAFFAYJAgAAAA==.',
['吕玲']='吕玲綺:BAAALgADCgEJAQAAAA==.',
['听说']='听说你很能打:BAAALgADCgMJAwAAAA==.',
['吾去']='吾去托她衣:BAAALgAECgEJAgAAAA==.',
['呆呆']='呆呆鸟:BAAALgAECgEJBAAAAA==.',
['呆子']='呆子你向前看:BAAALgAECgUJBwAAAA==.',
['呆熊']='呆熊:BAAALgAFFAIJAgABLgAFFAIJBgAPAH0cAA==.',
['呆胶']='呆胶布:BAAALgADCggJCAAAAA==.',
['周周']='周周鸭:BAAALgAECgkJCQAAAA==.',
['周舟']='周舟周舟:BAAALgAFFAIJAgAAAA==.',
['和歌']='和歌橘:BAAALgAECgMJBQAAAA==.',
['咔噼']='咔噼吧啦:BAAALgAFFAQJBAABLgAFFAUJEgAHAK0iAA==.',
['咕之']='咕之小:BAAALgAECgQJBQAAAA==.',
['咖啡']='咖啡余生:BAAALgAECgEJAQAAAA==.咖啡烟雨灬:BAAALgAFFAEJAQAAAA==.咖啡钚解酒醉:BAAALgADCgUJBQAAAA==.',
['咖喱']='咖喱哥哥:BAABLgAFFH8IAAMJAAMJgAmUDQCTAAAJAAMJQwKUDQCTAAAIAAEJIRqiUQBSAAAAAA==.咖喱鱼蛋:BAAALgAFFAIJBAAAAA==.',
['咲良']='咲良:BAAALgAFFAIJAwAAAA==.',
['咸鱼']='咸鱼飞蛋:BAAALgAECgEJAQAAAA==.',
['哀伤']='哀伤之泪:BAAALgAFFAQJAQAAAA==.',
['哆咯']='哆咯咚:BAAALgAFFAEJAQAAAA==.',
['哆唻']='哆唻咪法:BAABLgAECn8UAAIBAAYJ/x5WZwAIAgABAAYJ/x5WZwAIAgAAAA==.',
['哈基']='哈基拳师:BAAALgADCgYJBgAAAA==.',
['哈悠']='哈悠悠:BAAALgADCgcJDAAAAA==.',
['哈皮']='哈皮牛耶:BAAALgAECgQJCQAAAA==.',
['哎呀']='哎呀妈呀:BAACLgAFFH8IAAIGAAIJPCXtHwDXAAAGAAIJPCXtHwDXAAAuAAQKfxoAAgYACQmIH+MGAFkDAAYACQmIH+MGAFkDAAAA.',
['哑紫']='哑紫风铃:BAAALgAECgYJCQAAAA==.',
['哔卟']='哔卟哔卟哔卟:BAAALgAECgIJAgAAAA==.',
['哔哩']='哔哩吧啦丶:BAAALgAECgcJBwAAAA==.',
['商鞅']='商鞅知马力:BAABLgAFFH8LAAIGAAUJgCM+AwAJAgAGAAUJgCM+AwAJAgABLgAFFAYJAgAEAAAAAA==.',
['啊呐']='啊呐呐:BAAALgAFFAIJAgAAAA==.',
['啊啦']='啊啦有法伤:BAAALgAECgUJBAAAAA==.',
['啵啵']='啵啵小朋友:BAAALgAECgUJBQAAAA==.',
['喜欢']='喜欢吃苹果:BAAALgAECgEJAQAAAA==.',
['喵喵']='喵喵丶怪:BAAALgAECgYJCQAAAA==.',
['喵帕']='喵帕喵帕斯:BAAALgADCgYJBgAAAA==.',
['喵影']='喵影:BAAALgADCgYJBgAAAA==.',
['喵樹']='喵樹咕:BAAALgAECgEJAQAAAA==.',
['嗳緔']='嗳緔魔尩:BAAALgAECgEJAQAAAA==.',
['嘎嘎']='嘎嘎不坏:BAAALgADCgcJCQAAAA==.',
['四乃']='四乃森苍紫:BAAALgAFFAIJBAAAAA==.',
['四十']='四十贯右马头:BAAALgAFFAEJAQAAAA==.',
['四月']='四月她爸:BAAALgAECgEJAQAAAA==.四月的谎言丶:BAAALgAECgIJBAAAAA==.',
['回忆']='回忆总想哭:BAACLgAFFH8PAAIQAAQJJxT6AwBMAQAQAAQJJxT6AwBMAQAuAAQKfyUAAhAACAlxGNgYABUCABAACAlxGNgYABUCAAAA.',
['囧囧']='囧囧炽天使:BAAALgAECgUJBgAAAA==.',
['圈一']='圈一:BAAALgAECgcJDQAAAA==.',
['土神']='土神灵:BAAALgAECgEJAQAAAA==.',
['圣光']='圣光云影:BAAALgAECgEJAQAAAA==.圣光修罗:BAAALgAECgcJCgAAAA==.圣光和牛:BAAALgADCgYJBgAAAA==.圣光渐朽:BAAALgAFFAMJBAAAAA==.圣光龙龙:BAAALgAECgcJBgABLgAFFAYJBgABABIBAA==.',
['圣翎']='圣翎律歌:BAAALgAECgEJAgAAAA==.',
['在纸']='在纸上来回丶:BAAALgAECgQJBgAAAA==.',
['坚定']='坚定牛牛:BAAALgADCgMJAwAAAA==.',
['坚挺']='坚挺的小强:BAABLgAECn8bAAQFAAcJNxdIKQB5AQAFAAUJ5hlIKQB5AQAGAAUJ6gsikQD9AAAcAAcJtQm+BgDdAAAAAA==.',
['埃什']='埃什:BAAALgADCgEJAQAAAA==.',
['堕红']='堕红尘:BAAALgAFFAIJAgAAAA==.',
['塞洛']='塞洛波波雷:BAAALgAECgIJAQAAAA==.',
['塞门']='塞门:BAAALgAFFAEJAQAAAA==.',
['墨舞']='墨舞星尘:BAAALgAECgMJAwAAAA==.',
['墨镜']='墨镜:BAAALgADCgYJBgAAAA==.',
['墮落']='墮落丶契約:BAAALgAECgQJBQAAAA==.',
['壮熊']='壮熊:BAAALgADCgEJAQAAAA==.',
['夏三']='夏三白:BAABLgAFFH8IAAIRAAMJuwUzGADYAAARAAMJuwUzGADYAAAAAA==.',
['夏夜']='夏夜奶咖:BAABLgAFFH8GAAITAAMJ/RdBFAAGAQATAAMJ/RdBFAAGAQAAAA==.',
['夏天']='夏天丶灬:BAAALgAECgcJDwAAAA==.',
['夏末']='夏末浅殇:BAAALgADCgEJAQAAAA==.',
['夕晖']='夕晖:BAAALgAFFAQJBAABLgAFFAUJEgAHAK0iAA==.',
['夕沉']='夕沉:BAAALgAECgYJDQAAAA==.',
['夕霧']='夕霧綴理:BAAALgAECgQJCQAAAA==.',
['多重']='多重射击:BAAALgADCgcJBwAAAA==.',
['夜不']='夜不曾眠:BAACLgAFFH8KAAMIAAMJYyKaHwAdAQAIAAMJTSGaHwAdAQAdAAIJKhfNAgC8AAAuAAQKfyUAAggACAnuIQUFAFoCAAgACAnuIQUFAFoCAAAA.',
['夜之']='夜之语:BAAALgADCgEJAQABLgAFFAYJFQAYAHIhAA==.',
['夜夜']='夜夜破寺规:BAAALgADCgIJAgAAAA==.',
['夜雨']='夜雨如歌:BAACLgAFFH8IAAIHAAMJzRG5CQDgAAAHAAMJzRG5CQDgAAAuAAQKfxoAAgcACAmqFfU0ALABAAcACAmqFfU0ALABAAAA.',
['夜静']='夜静人空:BAACLgAFFH8KAAMHAAUJYhhTAQCzAQAHAAUJYhhTAQCzAQAPAAIJMQ9UFgCfAAAuAAQKfxQAAw8ABwmMIXcTAIQCAA8ABwmMIXcTAIQCAAcAAgl9EouGAHoAAAAA.',
['大丶']='大丶熊丶:BAACLgAFFH8LAAMTAAMJCBNUDgDxAAATAAMJCBNUDgDxAAANAAIJZgcPBgBgAAAuAAQKfxQAAw0ACAkcHZYQAL0BAA0ABwn5FJYQAL0BABMAAwnEI0qlADYBAAAA.',
['大内']='大内灵灵死:BAAALgAECgYJCwAAAA==.大内灵灵萨:BAAALgAECgYJCgAAAA==.大内灵灵骑:BAAALgAECgcJAwAAAA==.',
['大凉']='大凉龙雀丶:BAACLgAFFH8IAAIYAAMJpwSaEQC7AAAYAAMJpwSaEQC7AAAuAAQKfxsAAx4ABwnvFvUPAHoBAB4ABwk+EfUPAHoBABgABAnPHRE8AEQBAAAA.',
['大地']='大地之牛:BAABLgAFFH8FAAIHAAMJ9ADKDQCiAAAHAAMJ9ADKDQCiAAAAAA==.',
['大大']='大大们好:BAAALgAECgUJBQAAAA==.',
['大宝']='大宝天天见:BAAALgADCgUJBQAAAA==.',
['大库']='大库啊:BAABLgAFFH8JAAIKAAMJTCTQBABEAQAKAAMJTCTQBABEAQAAAA==.',
['大桶']='大桶咸鱼:BAAALgAECgYJDgAAAA==.',
['大波']='大波米:BAAALgAECgMJAwAAAA==.',
['大熊']='大熊丶丶:BAACLgAFFH8QAAIJAAQJsgvfCAD6AAAJAAQJsgvfCAD6AAAuAAQKfyYAAgkACAn8GfUNAC4CAAkACAn8GfUNAC4CAAAA.',
['大猛']='大猛哥:BAABLgAFFH8NAAIHAAQJsBLsCAA+AQAHAAQJsBLsCAA+AQAAAA==.',
['大翔']='大翔鸽:BAACLgAFFH8HAAITAAMJOSN1DwAsAQATAAMJOSN1DwAsAQAuAAQKfyMAAhMACAnvIf4MACYDABMACAnvIf4MACYDAAAA.',
['大能']='大能猫:BAAALgADCgEJAQAAAA==.',
['大草']='大草:BAAALgAFFAEJAQAAAA==.',
['大青']='大青柠:BAACLgAFFH8HAAIGAAQJ+wueDQANAQAGAAQJ+wueDQANAQAuAAQKfxQAAwYABwmRG3I2AB0CAAYABwmRG3I2AB0CAAUABAnVByNTAJwAAAAA.',
['天下']='天下一人:BAABLgAFFH8GAAIIAAMJ7hUrJwD6AAAIAAMJ7hUrJwD6AAAAAA==.',
['天呐']='天呐好美:BAAALgAECgEJAgAAAA==.',
['天宇']='天宇圣魂:BAAALgAECgYJBwAAAA==.',
['天然']='天然坑:BAAALgAECgUJCgAAAA==.',
['天界']='天界崩坏:BAAALgAECgIJAgAAAA==.',
['天赐']='天赐玄机丶:BAAALgAECgUJEgAAAA==.',
['天骄']='天骄无双:BAAALgADCgIJAgAAAA==.',
['太子']='太子宝贝:BAAALgAECgUJDwAAAA==.',
['太无']='太无耻了:BAAALgAECgQJBAAAAA==.',
['夭夭']='夭夭光明骑:BAAALgADCgYJBgAAAA==.',
['头上']='头上的犄角:BAAALgADCgcJCAAAAA==.',
['夶熊']='夶熊:BAAALgADCgIJAgAAAA==.夶熊丶:BAAALgAECgYJDQAAAA==.',
['夺缘']='夺缘丶嗜分:BAAALgADCgEJAQAAAA==.',
['奇可']='奇可:BAACLgAFFH8GAAIPAAIJfRz5EgC+AAAPAAIJfRz5EgC+AAAuAAQKfxkAAg8ABgnNI/8XAFYCAA8ABgnNI/8XAFYCAAAA.',
['奇尔']='奇尔沙治:BAAALgAECgkJCQAAAA==.',
['奈死']='奈死:BAACLgAFFH8HAAIKAAMJqCTkCABFAQAKAAMJqCTkCABFAQAuAAQKfyMAAgoACAnGIxgGAAoDAAoACAnGIxgGAAoDAAAA.',
['奕奕']='奕奕术师:BAAALgADCgYJBgAAAA==.奕奕法诗:BAAALgAECgcJBwAAAA==.奕奕生辉:BAAALgADCgEJAQAAAA==.',
['套子']='套子不要:BAABLgAFFH8FAAIJAAMJuwBvCQBzAAAJAAMJuwBvCQBzAAABLgAFFAMJBQATADINAA==.套子要要:BAABLgAFFH8FAAITAAMJMg0+FwDzAAATAAMJMg0+FwDzAAAAAA==.',
['奥利']='奥利波斯猎:BAACLgAFFH8IAAMaAAMJqhqhCAAdAQAaAAMJqhqhCAAdAQACAAEJxApxKQBJAAAuAAQKfxQAAwIABwlJHiEzAJ4BAAIABQkrHyEzAJ4BABoABAnkHaJQAHcBAAAA.',
['奥莉']='奥莉微亚:BAACLgAFFH8IAAIFAAIJZSJzBwC5AAAFAAIJZSJzBwC5AAAuAAQKfxUAAgUABgmcIMkEAKkBAAUABgmcIMkEAKkBAAAA.',
['奥蕾']='奥蕾莉雅:BAAALgAECgQJBAAAAA==.',
['女王']='女王打人:BAAALgAECgYJDQAAAA==.女王的舔狗:BAAALgAFFAEJAQAAAA==.',
['奶嘴']='奶嘴蜂:BAAALgADCgEJAQAAAA==.',
['奶油']='奶油西米露:BAAALgAFFAQJBAAAAA==.',
['奶牛']='奶牛老生:BAAALgADCgYJBgAAAA==.',
['如我']='如我西沉:BAAALgAFFAIJBAAAAA==.',
['如故']='如故:BAABLgAFFH8FAAIIAAIJPSFyMgC/AAAIAAIJPSFyMgC/AAAAAA==.',
['如露']='如露亦如電:BAAALgAFFAIJAgAAAA==.',
['妖怪']='妖怪妈妈:BAAALgAFFAIJAgAAAA==.',
['妖气']='妖气:BAAALgAECgYJCwAAAA==.',
['妖邪']='妖邪必败:BAAALgAECggJCwAAAA==.',
['妖魅']='妖魅兔子:BAAALgAECgUJBQAAAA==.',
['妮菲']='妮菲塔利:BAAALgAECgQJBAAAAA==.',
['妳个']='妳个熊猫:BAAALgAECgIJBAAAAA==.',
['姆巴']='姆巴佩丶:BAAALgAECgcJDQAAAA==.',
['始于']='始于颜值:BAAALgAFFAIJAwABLgAFFAQJDwAGAGkgAA==.',
['威客']='威客:BAAALgAECgcJBwAAAA==.',
['威骑']='威骑熊村雅猪:BAACLgAFFH8QAAIMAAQJGSXJAAC8AQAMAAQJGSXJAAC8AQAuAAQKfxgAAgwACAmsJaUGABwDAAwACAmsJaUGABwDAAAA.',
['娜妞']='娜妞萨鲁法尔:BAACLgAFFH8HAAIBAAMJLiL5IQA3AQABAAMJLiL5IQA3AQAuAAQKfxsAAgEACAk8I70SADcDAAEACAk8I70SADcDAAAA.',
['娜娜']='娜娜倒杯水:BAAALgAECgkJCwAAAA==.',
['娜扎']='娜扎和热巴:BAAALgADCgYJBgAAAA==.',
['孤独']='孤独小装死:BAAALgAECgEJAQAAAA==.孤独的观测者:BAAALgAFFAEJAQABLgAFFAYJAwAEAAAAAA==.',
['孫燕']='孫燕姿:BAAALgAECgUJCAAAAA==.',
['宇宙']='宇宙大烧麦:BAAALgAECgQJBAABLgAFFAYJAwAEAAAAAA==.宇宙浪漫辞典:BAAALgADCgEJAQAAAA==.',
['安小']='安小之:BAAALgAFFAIJAwAAAA==.',
['安慰']='安慰剂:BAABLgAFFH8FAAIHAAUJqhwSAgDNAQAHAAUJqhwSAgDNAQABLgAFFAUJEgAHAK0iAA==.',
['安然']='安然泪下:BAACLgAFFH8SAAIbAAUJmR+BAgD1AQAbAAUJmR+BAgD1AQAuAAQKfyUAAxsACAkPJbYCAEADABsACAkPJbYCAEADAB8AAQkMC/1gADcAAAAA.安然泪夏:BAAALgAECgMJAwAAAA==.',
['安養']='安養寺姫芽:BAAALgAECgMJAwAAAA==.',
['定边']='定边二道街:BAAALgAECgYJAQAAAA==.定边鼓楼:BAAALgAECgYJDQABLgAECgYJDQAEAAAAAA==.',
['宝矿']='宝矿力洗衣机:BAABLgAFFH8GAAIIAAIJaBMUJQCSAAAIAAIJaBMUJQCSAAAAAA==.',
['实在']='实在忒滑稽:BAAALgADCgMJAwAAAA==.',
['宣传']='宣传企鹅娘:BAAALgAECgEJAQAAAA==.',
['宵辉']='宵辉亮亮:BAABLgAECn8dAAIgAAYJ2CBGBwC8AQAgAAYJ2CBGBwC8AQAAAA==.',
['寂寞']='寂寞桃花:BAAALgAFFAQJBAAAAA==.寂寞的传说叔:BAAALgAECgEJAQAAAA==.',
['寒江']='寒江孤影:BAABLgAECn8lAAIaAAgJ0xVTIQA9AgAaAAgJ0xVTIQA9AgAAAA==.',
['寒雪']='寒雪精灵:BAAALgAFFAIJBAAAAA==.',
['对酒']='对酒當歌:BAAALgAECgEJAQAAAA==.',
['封不']='封不停:BAAALgAECgYJCAAAAA==.',
['射穿']='射穿钢板:BAAALgAECgYJDwAAAA==.',
['小俊']='小俊俊:BAAALgAECgMJAwAAAA==.',
['小克']='小克里琴科:BAAALgAECgEJAQAAAA==.',
['小兔']='小兔的凯西:BAAALgAECgEJAQAAAA==.',
['小团']='小团子桑:BAACLgAFFH8GAAITAAIJkyVDDwDjAAATAAIJkyVDDwDjAAAuAAQKfxQAAhMACAm/I0sOABwDABMACAm/I0sOABwDAAAA.',
['小姜']='小姜奶:BAAALgAECggJCAAAAA==.',
['小小']='小小筱武僧:BAAALgADCgUJBQAAAA==.小小酥灬:BAAALgAECgcJBQAAAA==.',
['小布']='小布点点:BAAALgAECgcJBgABLgAFFAQJBgAMAFUbAA==.',
['小晓']='小晓强:BAAALgAECgkJCQAAAA==.',
['小杨']='小杨鸽:BAABLgAFFH8FAAIRAAMJAySTFQBBAQARAAMJAySTFQBBAQAAAA==.',
['小林']='小林历奇:BAACLgAFFH8PAAIYAAQJViWiBAChAQAYAAQJViWiBAChAQAuAAQKfx4AAhgACAnGJXgDAHYDABgACAnGJXgDAHYDAAAA.',
['小楼']='小楼哭泣:BAAALgAECgYJBwAAAA==.',
['小橙']='小橙光:BAAALgAFFAEJAQAAAA==.',
['小汤']='小汤圆:BAAALgADCgcJBwAAAA==.',
['小波']='小波米:BAAALgADCgEJAQAAAA==.',
['小火']='小火龙龙:BAAALgAECgkJAQAAAA==.',
['小爷']='小爷报道:BAAALgAECgUJBQAAAA==.',
['小牛']='小牛爱吃草:BAAALgAECgMJAwAAAA==.',
['小白']='小白少爷:BAAALgADCgEJAQAAAA==.小白很勇敢:BAACLgAFFH8GAAIhAAMJqhtsAwAUAQAhAAMJqhtsAwAUAQAuAAQKfxYAAiEACAmJIC0HAAsDACEACAmJIC0HAAsDAAEuAAUUBAkLAA4ArhoA.',
['小羊']='小羊咩:BAABLgAFFH8FAAIBAAIJchRCIQCwAAABAAIJchRCIQCwAAAAAA==.',
['小肥']='小肥柴丶:BAAALgAECgYJBgAAAA==.',
['小胖']='小胖球:BAAALgADCgIJAgAAAA==.',
['小葵']='小葵灬:BAAALgAECgUJBQAAAA==.',
['小象']='小象超人:BAAALgAECgEJAQABLgAFFAEJAQAEAAAAAA==.',
['小贵']='小贵子:BAAALgAECgYJDgAAAA==.',
['小陈']='小陈同学:BAAALgAFFAEJAQAAAA==.',
['小魔']='小魔仙随身变:BAAALgAECgMJBAAAAA==.',
['小鱼']='小鱼不吃鱼:BAAALgAECgYJDgAAAA==.',
['小鸡']='小鸡丶炖蘑菇:BAAALgAECgEJAQAAAA==.',
['尐尐']='尐尐爺:BAAALgAFFAIJAwAAAA==.',
['少名']='少名针妙丸:BAAALgAECgEJAQABLgAECgcJBwAEAAAAAA==.',
['少废']='少废话:BAAALgAECgIJAgAAAA==.',
['尖尖']='尖尖哇嘎乃:BAAALgAECgkJBAAAAA==.',
['尖椒']='尖椒泡椒:BAAALgAECgEJAQAAAA==.',
['尘逸']='尘逸鸢:BAAALgAECgEJAQAAAA==.',
['尤利']='尤利萨迦:BAAALgAECgIJAgAAAA==.',
['尤弥']='尤弥尔:BAAALgAECgYJBwAAAA==.',
['就是']='就是不想奶丶:BAAALgAFFAcJBAAAAA==.就是呆:BAACLgAFFH8OAAITAAQJCxB8BwA3AQATAAQJCxB8BwA3AQAuAAQKfyEAAhMACAnWIqIQAAoDABMACAnWIqIQAAoDAAAA.',
['尹鸡']='尹鸡:BAAALgAECgMJAwAAAA==.',
['尼加']='尼加拉野猴子:BAAALgAECgYJAwAAAA==.',
['尼奥']='尼奥罗萨:BAABLgAFFH8IAAIiAAQJMyAUAQCMAQAiAAQJMyAUAQCMAQABLgAFFAYJGAARAJAlAA==.',
['尼莫']='尼莫小可爱:BAAALgAECgcJBwAAAA==.',
['屮灬']='屮灬你去助他:BAAALgAECgUJBQAAAA==.屮灬广智救我:BAAALgAECgQJBAAAAA==.屮灬我来助你:BAAALgAECgEJAQAAAA==.',
['岚夜']='岚夜狩:BAABLgAECn8YAAITAAcJ8xWxXQDKAQATAAcJ8xWxXQDKAQAAAA==.',
['岛胜']='岛胜猛:BAAALgAECgYJBgAAAA==.',
['崔莱']='崔莱蒂:BAACLgAFFH8PAAMaAAQJRh2FAQCOAQAaAAQJRh2FAQCOAQACAAIJ5BYDHQCiAAAuAAQKfyQAAxoACAnzJA8KAPgCABoABwkqIw8KAPgCAAIABwn5I6sRAKkCAAAA.',
['左丨']='左丨梦丨尘:BAAALgAECgYJDQABLgAFFAIJBAAEAAAAAA==.左丨飞丨卿:BAAALgAFFAIJBAAAAA==.',
['左右']='左右:BAAALgADCgcJBwAAAA==.',
['左耳']='左耳:BAAALgAECgYJCAAAAA==.',
['巧克']='巧克力丶妹纸:BAAALgAECgMJAwAAAA==.巧克力团团:BAAALgAFFAEJAQAAAA==.巧克力泥头车:BAAALgAECgEJAQABLgAECgcJGAAbALQWAA==.巧克力白兰地:BAAALgAECgQJAwAAAA==.巧克力蛋挞:BAAALgAECgYJCQAAAA==.巧克力馅饼:BAAALgADCgEJAQAAAA==.巧克力香菜:BAACLgAFFH8FAAIGAAIJxxjmIwCwAAAGAAIJxxjmIwCwAAAuAAQKfxYABBwABwncHrUIAOwBABwABwk/HbUIAOwBAAYABgngGc1ZAJQBAAUAAwndGXtEAOQAAAAA.',
['巫小']='巫小巫:BAABLgAFFH8KAAIbAAcJfxU4AABmAgAbAAcJfxU4AABmAgAAAA==.',
['巫龙']='巫龙一:BAABLgAFFH8MAAIbAAcJVBLjAABbAgAbAAcJVBLjAABbAgAAAA==.巫龙二:BAABLgAFFH8FAAIbAAUJQxF3BQCfAQAbAAUJQxF3BQCfAQAAAA==.',
['布倫']='布倫希尔德:BAAALgADCgEJAQAAAA==.',
['布响']='布响丸辣:BAAALgAECgcJDAABLgAFFAQJEAABAL4gAA==.',
['布布']='布布哥:BAAALgAECgMJAwAAAA==.',
['布都']='布都御魂:BAAALgAECgcJBwAAAA==.',
['希尔']='希尔薇思:BAAALgAECgEJAgAAAA==.',
['希维']='希维尔:BAAALgAFFAIJAgAAAA==.',
['带带']='带带瘤子把:BAAALgAECgcJBgAAAA==.',
['常威']='常威:BAABLgAFFH8FAAIVAAQJzheSAgBnAQAVAAQJzheSAgBnAQAAAA==.',
['年月']='年月:BAAALgAECgUJBQAAAA==.',
['幻化']='幻化终结者:BAAALgADCgYJBgAAAA==.',
['幻蓝']='幻蓝尘:BAAALgAECgEJAQAAAA==.',
['幻雪']='幻雪天烬:BAAALgAECgIJAQAAAA==.',
['幽若']='幽若羽默:BAAALgAECgkJCQAAAA==.',
['幽默']='幽默醉拳:BAAALgAECgEJAQAAAA==.',
['康斯']='康斯坦仃:BAAALgAECgIJAgAAAA==.',
['开拓']='开拓者小派蒙:BAAALgAECgkJBQAAAA==.',
['弄帮']='弄帮吾关特:BAAALgADCgQJBAAAAA==.',
['弑枫']='弑枫:BAAALgAECgYJBgAAAA==.',
['引火']='引火归源:BAAALgAECgEJAQAAAA==.',
['张总']='张总又没来:BAAALgAECgEJAQABLgAECgcJDQAEAAAAAA==.',
['张灬']='张灬根硕:BAABLgAECn8UAAITAAYJrxNYeQCHAQATAAYJrxNYeQCHAQAAAA==.',
['张猎']='张猎猎:BAAALgAECgcJDQAAAA==.',
['弼鸟']='弼鸟温:BAAALgADCgUJBQAAAA==.',
['影丶']='影丶白鸟:BAABLgAECn8fAAIjAAcJnxs8AgB5AgAjAAcJnxs8AgB5AgAAAA==.',
['影涯']='影涯:BAAALgAFFAEJAQAAAA==.',
['影遁']='影遁:BAAALgADCgYJBgAAAA==.',
['待续']='待续丨狂野:BAAALgAFFAIJAgAAAA==.',
['很高']='很高兴遇见你:BAAALgAECgEJAQAAAA==.',
['得鲁']='得鲁伊下:BAAALgADCgUJBQAAAA==.',
['微斯']='微斯人孰与归:BAAALgAECgkJEAABLgAFFAQJBAAEAAAAAA==.',
['德理']='德理徳气:BAAALgAFFAIJAwAAAA==.',
['德道']='德道高僧:BAAALgAECgUJBgAAAA==.',
['心中']='心中之城:BAAALgAECgYJCAAAAA==.',
['心似']='心似双丝网:BAABLgAECn8XAAIGAAkJvhnnFwDGAgAGAAkJvhnnFwDGAgAAAA==.',
['心灵']='心灵匕首:BAAALgAECgkJEAABLgAFFAcJGgAOAJkjAA==.',
['必须']='必须得:BAAALgAECgIJAgAAAA==.',
['忆寒']='忆寒殇:BAAALgAECgYJCgAAAA==.',
['忆往']='忆往云烟:BAAALgAECgkJCQAAAA==.忆往芸樱:BAAALgAECgkJCQAAAA==.',
['忆者']='忆者之枫:BAAALgAECgEJAQAAAA==.',
['忘食']='忘食:BAACLgAFFH8LAAMCAAQJdBrNAQBdAQACAAQJ/RjNAQBdAQAaAAEJkCBYIQBeAAAuAAQKfx8AAwIACAmbIwwKAAADAAIACAmpIgwKAAADABoAAQlzJdm1AFcAAAAA.',
['忧末']='忧末:BAAALgAECgUJCAAAAA==.',
['忧纆']='忧纆:BAAALgAECgEJAQAAAA==.',
['忧默']='忧默:BAAALgADCgMJAwAAAA==.',
['快乐']='快乐丶胖豆:BAAALgAECgQJBAAAAA==.',
['怒之']='怒之咆哮:BAAALgAECgQJBAAAAA==.',
['思我']='思我往矣:BAAALgAECggJEAAAAA==.',
['怪咖']='怪咖丨可乐酱:BAABLgAFFH8GAAIgAAMJXxRiCwDvAAAgAAMJXxRiCwDvAAAAAA==.',
['悔恨']='悔恨:BAAALgADCgcJBwAAAA==.',
['悠悠']='悠悠乐乐:BAAALgAECggJCwAAAA==.',
['悲妄']='悲妄之生:BAAALgAECgUJBwAAAA==.',
['情怀']='情怀雾谷:BAAALgAECgYJEAAAAA==.',
['惊涛']='惊涛:BAAALgAECgYJBgAAAA==.',
['惩戒']='惩戒歧视:BAAALgAFFAEJAgAAAA==.',
['想安']='想安静的叶导:BAAALgAFFAIJAgAAAA==.',
['想抓']='想抓喵德:BAAALgADCgEJAQAAAA==.',
['想被']='想被壮熊抱抱:BAAALgAFFAIJAwAAAA==.',
['愛撕']='愛撕愛摸:BAAALgAECgEJAQAAAA==.',
['愤怒']='愤怒的流星:BAAALgAECgMJAgAAAA==.',
['慈祥']='慈祥的小凯文:BAAALgAECgEJAQAAAA==.',
['慎罗']='慎罗:BAAALgAECgYJBgAAAA==.',
['憨憨']='憨憨:BAAALgAECggJBwAAAA==.',
['懂先']='懂先生:BAAALgAECgQJBwAAAA==.',
['懒大']='懒大王:BAAALgAFFAQJBAAAAA==.',
['懒得']='懒得取:BAAALgADCgYJBgAAAA==.懒得起名:BAAALgAECggJCAAAAA==.',
['懒觉']='懒觉:BAAALgAFFAEJAwAAAA==.',
['戈薇']='戈薇:BAAALgAECgYJBwAAAA==.',
['成都']='成都吴彦祖:BAAALgAECgIJAwAAAA==.',
['我一']='我一个眼棱:BAAALgAFFAUJBAABLgAFFAYJAgAEAAAAAA==.',
['我不']='我不会奶人:BAACLgAFFH8HAAIYAAMJUBI7DgD7AAAYAAMJUBI7DgD7AAAuAAQKfyAAAxgABwn6I4wOALQCABgABwn6I4wOALQCAAMABgkAG7g+AKgBAAAA.',
['我也']='我也许是狐人:BAAALgAECgYJBwAAAA==.',
['我作']='我作业写完了:BAABLgAFFH8KAAIgAAUJTwvPAwBeAQAgAAUJTwvPAwBeAQAAAA==.',
['我叫']='我叫阿立:BAAALgAECgUJBQAAAA==.',
['我天']='我天生强大:BAAALgAECgEJAQAAAA==.',
['我愛']='我愛老卡的毛:BAAALgAECgQJBQAAAA==.',
['我没']='我没有腰啊:BAAALgAFFAEJAQAAAA==.',
['我爱']='我爱上班:BAAALgAECgQJBAAAAA==.',
['我玩']='我玩原神玩的:BAAALgADCgcJDAAAAA==.',
['我看']='我看看怎么事:BAACLgAFFH8PAAIRAAQJayQrBwCxAQARAAQJayQrBwCxAQAuAAQKfyIAAhEACAlNJrIDAIIDABEACAlNJrIDAIIDAAAA.',
['我真']='我真会救你:BAAALgAFFAEJAQAAAA==.我真的大:BAAALgAFFAQJAQAAAA==.',
['我要']='我要开花:BAAALgAECgEJAQAAAA==.',
['战兜']='战兜兜:BAAALgAECgYJCQAAAA==.',
['战斗']='战斗暴龙兽:BAABLgAFFH8JAAMbAAMJVSRgDAAhAQAbAAMJVSRgDAAhAQAfAAEJ9A+GFQBTAAAAAA==.',
['战歌']='战歌血吼灬:BAAALgADCgEJAQAAAA==.',
['抱抱']='抱抱壮熊:BAAALgAFFAIJAgAAAA==.',
['抽象']='抽象的翼手龙:BAAALgAECgcJDQABLgAFFAQJCAAbAHYZAA==.',
['拈花']='拈花一笑:BAAALgAFFAIJAgAAAA==.',
['拉丶']='拉丶娜娅:BAAALgAECgQJAQAAAA==.',
['拉布']='拉布布:BAAALgADCgkJEQAAAA==.',
['拉比']='拉比林斯:BAAALgADCgIJAgAAAA==.',
['拉芙']='拉芙特:BAACLgAFFH8bAAQIAAcJqyM0AADOAgAIAAcJqyM0AADOAgAdAAIJohjWAgC6AAAJAAEJAAA8DgAAAAAuAAQKfyIABAgACQmJJPoFAHYDAAgACQlCJPoFAHYDAB0AAwkHIksKACoBAAkAAgkICfpBAEMAAAAA.',
['拳王']='拳王月灼:BAAALgAFFAQJAgAAAA==.',
['拾七']='拾七:BAAALgAFFAIJAwAAAA==.',
['拾壹']='拾壹酱丶:BAAALgAECgYJCwAAAA==.',
['挖洞']='挖洞宾:BAAALgAECgYJCwAAAA==.',
['挖鼻']='挖鼻孔的大象:BAAALgAECgIJAgAAAA==.',
['挽狂']='挽狂澜于既倒:BAABLgAFFH8GAAINAAIJLiAnAwC+AAANAAIJLiAnAwC+AAAAAA==.',
['捣蛋']='捣蛋鬼别捣蛋:BAAALgAECgkJCQABLgAFFAkJAQAEAAAAAA==.',
['接接']='接接林:BAAALgADCgEJAgAAAA==.',
['摄像']='摄像:BAAALgAECgYJBgAAAA==.',
['摇滚']='摇滚湮灭龙:BAABLgAECn8YAAQbAAcJtBbXHACeAQAbAAcJtBbXHACeAQAfAAUJXxUFLwBLAQAkAAQJRxlHHwAzAQAAAA==.摇滚老腊肉:BAABLgAFFH8HAAIBAAIJAxZ3OQC3AAABAAIJAxZ3OQC3AAAAAA==.摇滚西米露:BAABLgAECn8UAAIIAAcJAxvhWQDkAQAIAAcJAxvhWQDkAQAAAA==.',
['摩伊']='摩伊拉:BAAALgAECgkJCwABLgAFFAUJDAARAKgRAA==.',
['撞撞']='撞撞牛:BAAALgADCgQJBAAAAA==.',
['救世']='救世祭司:BAAALgAFFAMJAwAAAA==.',
['救赎']='救赎自由灵魂:BAABLgAFFH8FAAIHAAUJIQiEBQBzAQAHAAUJIQiEBQBzAQAAAA==.',
['文荣']='文荣:BAABLgAFFH8KAAIMAAQJNg0HCAAUAQAMAAQJNg0HCAAUAQAAAA==.',
['斩刃']='斩刃:BAAALgAFFAQJBAAAAA==.',
['断罪']='断罪灬之翼:BAAALgAECgEJAQAAAA==.',
['新哥']='新哥呢救一下:BAAALgAECgcJBwAAAA==.',
['方天']='方天画戟:BAAALgAECgYJCgAAAA==.',
['施奶']='施奶杀手:BAABLgAECn8UAAMiAAYJtwibEwDyAAAiAAYJtwibEwDyAAAQAAMJOgKAbgBtAAAAAA==.施奶猎手:BAAALgAECgYJCgAAAA==.',
['无助']='无助怜宝:BAAALgAECgQJBAAAAA==.',
['无声']='无声铃鹿:BAABLgAFFH8LAAIaAAMJqiXwBABUAQAaAAMJqiXwBABUAQABLgAFFAQJDwAYAFYlAA==.',
['无形']='无形之刃:BAAALgAECgYJDAAAAA==.',
['无慈']='无慈悲的安迪:BAACLgAFFH8GAAMcAAMJqhzVAgCYAAAcAAIJ/BjVAgCYAAAFAAIJ5R5fCwBnAAAuAAQKfyIAAwUACAk4HbcRAFACAAUABgmIJbcRAFACABwACAnuFZIHAAwCAAAA.',
['无效']='无效水位:BAAALgAECgEJAgAAAA==.',
['无敌']='无敌小歘歘:BAABLgAFFH8HAAICAAUJtyLuBADhAQACAAUJtyLuBADhAQAAAA==.无敌小钊哥:BAAALgAECgUJCgAAAA==.无敌钊神:BAAALgADCgYJBgAAAA==.',
['无误']='无误龙龙:BAAALgAFFAQJBAAAAA==.',
['无锋']='无锋:BAABLgAECn8ZAAITAAcJ/x5zFQCbAQATAAcJ/x5zFQCbAQAAAA==.',
['旧城']='旧城以西:BAAALgAFFAIJAgAAAA==.',
['早濑']='早濑优香:BAAALgAECgIJBgAAAA==.',
['时光']='时光如水:BAAALgAECgYJEwABLgAFFAQJAQAEAAAAAA==.',
['明月']='明月栖山阿:BAAALgAFFAEJAQAAAA==.明月涤吾心:BAAALgAFFAEJAgAAAA==.',
['易痒']='易痒欠吸:BAAALgAECggJCAAAAA==.',
['星光']='星光体育生:BAAALgAECgQJBQAAAA==.星光熊熊:BAAALgAFFAEJAQAAAA==.',
['星垂']='星垂瑶光:BAAALgAECgIJBAAAAA==.',
['星星']='星星火法:BAAALgAECgYJDwAAAA==.',
['星月']='星月同梦:BAAALgAECgcJBwAAAA==.',
['星空']='星空丶噬:BAAALgAECgYJBgAAAA==.',
['春秋']='春秋一梦:BAAALgAECgEJAQABLgAECgYJDQAEAAAAAA==.',
['春逝']='春逝:BAABLgAFFH8FAAIHAAUJNglNBQB4AQAHAAUJNglNBQB4AQAAAA==.',
['是一']='是一条小青龙:BAACLgAFFH8PAAMkAAQJoxUuBAAEAQAkAAMJaRQuBAAEAQAfAAQJDg6kEwDgAAAuAAQKfx8AAyQACAmFIqQDAOECACQACAmCH6QDAOECAB8ABwmSHXgVAC8CAAAA.',
['是彦']='是彦祖吗:BAAALgAECgYJBgAAAA==.',
['時来']='時来运转:BAAALgAECgMJAwAAAA==.',
['晚枫']='晚枫如荼丶:BAAALgAECgYJBgAAAA==.',
['晨寳']='晨寳寳:BAAALgADCgIJAgAAAA==.',
['普罗']='普罗米修斯:BAAALgAECgcJAgAAAA==.',
['晴太']='晴太丶:BAAALgAECgMJAwABLgAECgYJDQAEAAAAAA==.',
['暗影']='暗影君王:BAABLgAFFH8HAAIIAAIJHBoANQC0AAAIAAIJHBoANQC0AAAAAA==.暗影猎:BAACLgAFFH8HAAMaAAMJ/x5gEwCoAAACAAIJZBcpGwCrAAAaAAMJhRZgEwCoAAAuAAQKfyMAAwIACAkhHo0SAJ8CAAIACAkhHo0SAJ8CABoAAQn4HeW1AFcAAAAA.暗影界扛把子:BAAALgAECgcJCAAAAA==.',
['暗蝶']='暗蝶:BAAALgAECggJDQAAAA==.',
['暮尧']='暮尧子:BAAALgAECgIJAgAAAA==.',
['暮幽']='暮幽兰:BAABLgAECn8XAAIIAAgJlRddOgBOAgAIAAgJlRddOgBOAgAAAA==.',
['暮雨']='暮雨:BAAALgADCgMJAwAAAA==.',
['暴击']='暴击无罪:BAAALgAECgQJAwAAAA==.',
['暴脾']='暴脾气小怪兽:BAAALgAFFAEJAQAAAA==.暴脾气的小哥:BAAALgAECgQJBAAAAA==.',
['暴走']='暴走射基:BAAALgAECgYJDAAAAA==.暴走饭仔:BAACLgAFFH8IAAIRAAMJURsPHgALAQARAAMJURsPHgALAQAuAAQKfyEAAxEABwmhIdcFAD0CABEABwmPIdcFAD0CABIAAwnRHy0uAAMBAAAA.',
['暴躁']='暴躁的根硕:BAAALgAECgYJBwAAAA==.',
['暴雨']='暴雨图腾:BAAALgAECgcJDQAAAA==.',
['暴鲤']='暴鲤龙:BAAALgAECgcJCQAAAA==.',
['最后']='最后一个影子:BAAALgAECgQJBQAAAA==.最后一位优熊:BAABLgAFFH8GAAMHAAIJ8xn0FQCnAAAHAAIJ8xn0FQCnAAAPAAEJvBBdHQBMAAAAAA==.最后的荣耀:BAAALgAECgEJAQAAAA==.最后的雪:BAAALgAECgIJAgABLgAECgcJCQAEAAAAAA==.',
['最帅']='最帅橙色职业:BAABLgAFFH8FAAIDAAIJzQ7qEQB9AAADAAIJzQ7qEQB9AAAAAA==.',
['月下']='月下僚美妹:BAAALgAECgYJDQAAAA==.',
['月亮']='月亮的女儿:BAAALgAECgMJAwAAAA==.',
['月影']='月影公会会员:BAAALgADCgEJAQAAAA==.月影珊:BAAALgAECgcJAgAAAA==.',
['月色']='月色落幕:BAABLgAECn8dAAIjAAgJPRceAQDJAQAjAAgJPRceAQDJAQAAAA==.',
['月藏']='月藏锋:BAAALgAECgEJAwAAAA==.',
['有本']='有本事集火我:BAAALgADCgUJBQAAAA==.',
['有的']='有的跑了:BAAALgADCgUJBQAAAA==.',
['望江']='望江红:BAAALgAECgIJAwABLgAFFAIJBAAEAAAAAA==.',
['朝曦']='朝曦:BAACLgAFFH8HAAIQAAMJVBZRCADjAAAQAAMJVBZRCADjAAAuAAQKfyMAAxAACAnqF4IbAAACABAACAnqF4IbAAACAAsAAQlfDetVADUAAAAA.',
['朝酒']='朝酒晚跳舞:BAAALgAECgkJDQAAAA==.',
['木子']='木子丶:BAAALgAECgQJBAAAAA==.',
['未确']='未确认:BAAALgAECgEJAQAAAA==.',
['本大']='本大等:BAAALgAECgQJBAAAAA==.',
['术业']='术业有术:BAAALgADCgcJBwAAAA==.',
['术爹']='术爹:BAAALgAECggJCgAAAA==.',
['李大']='李大块头:BAAALgADCgYJBgAAAA==.',
['李拜']='李拜天丶:BAABLgAECn8aAAMFAAgJOB3vDwBnAgAFAAcJ7R3vDwBnAgAcAAYJbQ9/EQA5AQAAAA==.',
['李老']='李老酒:BAACLgAFFH8SAAIMAAUJ7QnKCQA8AQAMAAUJ7QnKCQA8AQAuAAQKfyEAAgwACAlmGUcbACkCAAwACAlmGUcbACkCAAAA.',
['村村']='村村:BAACLgAFFH8MAAMlAAQJtB+GAADKAAABAAMJoBuDJgAYAQAlAAMJXCCGAADKAAAuAAQKfxgABCUACAn6IiEDAEoCACUABwndIiEDAEoCAAEABwn0GglPAEoCACYAAQl3BmQRACsAAAAA.村村丨:BAABLgAFFH8FAAIZAAIJKQIbBQCNAAAZAAIJKQIbBQCNAAABLgAFFAQJDAAlALQfAA==.',
['来了']='来了淑诗:BAAALgAECgcJBwAAAA==.',
['来大']='来大雨哔:BAAALgAECgEJAQAAAA==.',
['杨老']='杨老六:BAAALgADCgIJAgAAAA==.',
['杯酒']='杯酒释恩仇:BAABLgAFFH8IAAITAAMJ2RIIFwD1AAATAAMJ2RIIFwD1AAAAAA==.',
['杰洛']='杰洛齐贝林:BAAALgAECgkJEgABLgAFFAQJBwABANkcAA==.',
['東云']='東云灬澪:BAAALgAECgcJBwAAAA==.',
['松江']='松江杜卵泡:BAAALgAFFAQJBAAAAA==.',
['极品']='极品盲流:BAAALgAECgEJAQAAAA==.',
['林北']='林北柯志華丷:BAAALgAECgcJCQAAAA==.',
['林小']='林小鹿:BAAALgADCgUJBQAAAA==.',
['枫念']='枫念:BAAALgAECgcJBwAAAA==.',
['枫木']='枫木晚晴:BAAALgAECgcJEAABLgAFFAIJBAAEAAAAAA==.',
['柒杠']='柒杠捌调:BAAALgAECgUJBQAAAA==.',
['柒柒']='柒柒丷丷:BAAALgAECgkJCgAAAA==.',
['染上']='染上夜色:BAABLgAFFH8JAAIHAAUJVRxtAQCvAQAHAAUJVRxtAQCvAQABLgAFFAUJEgAHAK0iAA==.',
['柯蒂']='柯蒂斯丶寂灭:BAAALgAFFAIJAgAAAA==.',
['栀子']='栀子与邙:BAAALgAECggJBwAAAA==.',
['树哥']='树哥:BAAALgAECgYJCwAAAA==.',
['栖雨']='栖雨:BAAALgADCgYJBwAAAA==.',
['桃树']='桃树:BAAALgAFFAEJAgAAAA==.',
['桐羽']='桐羽:BAAALgAECgYJCgAAAA==.',
['梅子']='梅子酒:BAAALgAECgYJBwAAAA==.',
['梓昂']='梓昂丶小红手:BAAALgAECgEJAQAAAA==.',
['梦灬']='梦灬星辰:BAACLgAFFH8QAAIHAAQJ+ibVAADQAQAHAAQJ+ibVAADQAQAuAAQKfyAAAgcACAlRJtMCAFIDAAcACAlRJtMCAFIDAAAA.',
['梦见']='梦见石榴姐:BAACLgAFFH8FAAIBAAMJShHWFgAEAQABAAMJShHWFgAEAQAuAAQKfxcAAwEABwkhId1DAGwCAAEABwn5IN1DAGwCACUAAgkVF3wUAH4AAAAA.',
['梦言']='梦言彼岸雨:BAAALgAECgYJBgAAAA==.',
['梦醒']='梦醒十纷:BAAALgAECgcJBwAAAA==.',
['森林']='森林大魔王:BAAALgAECgYJCgAAAA==.',
['椰子']='椰子鸡:BAAALgADCgMJAwAAAA==.',
['樱丶']='樱丶:BAAALgAECgkJCQAAAA==.',
['樱桃']='樱桃牛奶酱:BAAALgAECgEJAgAAAA==.',
['橘子']='橘子君:BAABLgAFFH8IAAIGAAQJbAzFEwA0AQAGAAQJbAzFEwA0AQAAAA==.橘子汽水丶:BAAALgAECgYJDQAAAA==.',
['橘猫']='橘猫:BAAALgAFFAIJBAAAAA==.',
['橙兜']='橙兜兜:BAAALgAECgEJAQAAAA==.',
['橙新']='橙新橙益:BAAALgAECgcJBwAAAA==.',
['橙芯']='橙芯橙苡:BAAALgADCgQJBAAAAA==.',
['橙苡']='橙苡芯橙:BAABLgAFFH8KAAMaAAQJ4An0BQBDAQAaAAQJ4An0BQBDAQACAAEJFAHALQA5AAAAAA==.',
['欧皇']='欧皇八八:BAAALgAECgYJBgAAAA==.欧皇粑粑:BAAALgAECgYJBgABLgAFFAQJCAAIAMYYAA==.',
['欲望']='欲望之主:BAAALgAECgEJAgAAAA==.',
['欸我']='欸我怎么红了:BAABLgAFFH8FAAIGAAUJux/mBADfAQAGAAUJux/mBADfAQABLgAFFAYJAgAEAAAAAA==.',
['歌颂']='歌颂黄河:BAAALgAECgQJBAAAAA==.',
['武十']='武十僧:BAAALgAECgYJDAAAAA==.',
['武坦']='武坦:BAACLgAFFH8GAAIMAAMJSSQGCQBEAQAMAAMJSSQGCQBEAQAuAAQKfxkAAgwABwknJLIPAKACAAwABwknJLIPAKACAAAA.',
['武泉']='武泉:BAAALgADCgkJEAAAAA==.',
['死亡']='死亡霸气:BAAALgAECgYJCAAAAA==.',
['残阳']='残阳落艳:BAAALgAFFAQJAQAAAA==.',
['残響']='残響散歌:BAACLgAFFH8SAAIHAAUJrSIFAQAEAgAHAAUJrSIFAQAEAgAuAAQKfx0AAgcACQlJH20FABoDAAcACQlJH20FABoDAAAA.',
['毛毛']='毛毛血旺盛:BAABLgAECn8XAAIBAAgJvxs+WgArAgABAAgJvxs+WgArAgABLgAFFAUJAQAEAAAAAA==.',
['水无']='水无文凉:BAAALgAECgUJBwAAAA==.',
['水果']='水果雨雨:BAAALgADCgcJBwAAAA==.',
['水無']='水無文凉:BAAALgAECgEJAgAAAA==.水無文涼:BAAALgAECgYJBwAAAA==.',
['水銀']='水銀燈:BAAALgAECgIJAgAAAA==.',
['水闸']='水闸厂长:BAAALgAECgcJBwAAAA==.',
['氵寺']='氵寺堇:BAAALgAECgYJBgAAAA==.',
['永恒']='永恒的晨曦:BAAALgAECgEJAgAAAA==.',
['汝辈']='汝辈为何而战:BAAALgADCgYJDAAAAA==.',
['江南']='江南如歌:BAAALgAECgMJAwAAAA==.江南柳树青:BAAALgADCgUJBQAAAA==.',
['江大']='江大江丶:BAAALgAECgIJAwABLgAFFAQJDAAlALQfAA==.',
['江小']='江小江丶:BAABLgAFFH8LAAIcAAMJkyPkAAA5AQAcAAMJkyPkAAA5AQAAAA==.',
['江河']='江河翻滚:BAAALgADCgUJBQAAAA==.',
['江起']='江起南风:BAAALgADCgcJBwAAAA==.',
['江风']='江风南吹:BAAALgADCgEJAQAAAA==.',
['污沫']='污沫贝贝:BAAALgAECgYJCwAAAA==.',
['沁雨']='沁雨:BAAALgAECgcJCgAAAA==.',
['沃卡']='沃卡恩:BAAALgAFFAEJAQAAAA==.',
['沃特']='沃特坎爱誰:BAAALgAECgcJBwAAAA==.',
['沉夜']='沉夜孤星:BAAALgAECgQJBAAAAA==.',
['沐灵']='沐灵:BAAALgAECgQJBAAAAA==.',
['没事']='没事澡澡卵:BAABLgAECn8gAAMSAAgJ3RoWFQCiAQASAAUJ2xgWFQCiAQARAAUJEBU1gQBYAQAAAA==.',
['没地']='没地方的基地:BAAALgAECgYJDAAAAA==.',
['沫奈']='沫奈子:BAAALgAECgEJAQAAAA==.',
['沫沫']='沫沫奈:BAAALgAECgMJAwAAAA==.',
['油炸']='油炸亲故:BAAALgADCgYJBwAAAA==.',
['治鸟']='治鸟坦:BAAALgADCgEJAgAAAA==.',
['沾雨']='沾雨醉清尘:BAAALgADCgYJCAAAAA==.',
['法伤']='法伤上亿:BAAALgAECgEJAQAAAA==.',
['法撕']='法撕:BAAALgAFFAIJAwAAAA==.',
['法杖']='法杖弯弯:BAAALgADCgEJAQAAAA==.',
['泡泡']='泡泡奶壶:BAAALgAECgcJAQAAAA==.',
['波雅']='波雅罕库克:BAAALgAECgUJCAAAAA==.',
['泽七']='泽七:BAAALgADCgkJCQAAAA==.',
['洛丹']='洛丹伦的王子:BAAALgAECgYJEQAAAA==.',
['洛儿']='洛儿老谢:BAAALgAECgYJDgAAAA==.',
['洛克']='洛克鲁塔:BAAALgADCgUJBQAAAA==.',
['洛洛']='洛洛总裁:BAABLgAFFH8IAAIbAAMJPgrNBwDVAAAbAAMJPgrNBwDVAAAAAA==.',
['洛白']='洛白鸟:BAAALgAECgcJDwAAAA==.',
['洛萨']='洛萨之子:BAAALgADCgEJAQAAAA==.',
['洪荒']='洪荒丶之力:BAAALgAFFAEJAQAAAA==.',
['派蒙']='派蒙:BAAALgAECgcJDwAAAA==.',
['流星']='流星丶花落:BAAALgAECgUJBQAAAA==.',
['流浪']='流浪的丿魂:BAABLgAFFH8IAAIHAAIJkB3RFAC0AAAHAAIJkB3RFAC0AAAAAA==.',
['流离']='流离思所:BAABLgAFFH8LAAIRAAQJjBRsEgBTAQARAAQJjBRsEgBTAQABLgAFFAUJFQABAPUjAA==.',
['浅夏']='浅夏未央:BAAALgADCgYJBQAAAA==.',
['济南']='济南钢铁集团:BAABLgAECn8VAAIGAAkJ9RacFwDIAgAGAAkJ9RacFwDIAgAAAA==.',
['浙北']='浙北吴彦祖:BAAALgAECgMJBAAAAA==.浙北小汤圆:BAABLgAECn8VAAIIAAcJlhj2egCOAQAIAAcJlhj2egCOAQAAAA==.浙北梁朝伟:BAAALgAFFAQJBAAAAA==.浙北蔡宝奇:BAABLgAFFH8GAAIMAAMJaw/qCwDUAAAMAAMJaw/qCwDUAAAAAA==.',
['海之']='海之幽霊:BAABLgAFFH8FAAIHAAUJYw5RBACNAQAHAAUJYw5RBACNAQABLgAFFAUJEgAHAK0iAA==.',
['海哥']='海哥丶:BAAALgAECgUJCAAAAA==.',
['海浪']='海浪丶涛涛:BAAALgAFFAQJAwAAAA==.',
['海蓝']='海蓝见鲸:BAAALgAECgEJAQAAAA==.',
['海贝']='海贝尔乂熊猫:BAAALgAECgEJAQAAAA==.',
['海鲜']='海鲜炒饭:BAAALgADCgcJBwAAAA==.',
['消愁']='消愁:BAAALgAECgEJAQAAAA==.',
['涩影']='涩影老湿:BAAALgAECgYJDwAAAA==.',
['深海']='深海色:BAAALgAECgEJAQAAAA==.',
['清晨']='清晨之光:BAAALgAECgUJCAAAAA==.',
['清欢']='清欢渡:BAAALgAECgYJDAAAAA==.',
['清秀']='清秀的姑娘:BAAALgAECgMJAwAAAA==.',
['渐朽']='渐朽:BAABLgAECn8dAAMVAAcJEB1AKwAJAgAVAAcJkBxAKwAJAgAWAAIJPhWEMgBpAAAAAA==.',
['渔盆']='渔盆是我滴:BAAALgAECgMJBAAAAA==.',
['游坦']='游坦之:BAAALgAECgEJAQAAAA==.',
['渺渺']='渺渺无言:BAAALgAECgYJCQAAAA==.',
['湿趴']='湿趴摸门:BAAALgAECgYJBgAAAA==.',
['滑稽']='滑稽贝贝:BAAALgAECgEJAQAAAA==.',
['满天']='满天繁星星:BAAALgADCgYJBgAAAA==.',
['潘多']='潘多拉磊:BAAALgAECgMJAwAAAA==.',
['潘腿']='潘腿腿:BAAALgAECgQJBAAAAA==.',
['潴潴']='潴潴灬小星:BAAALgAECgMJAwABLgAFFAMJBAAEAAAAAA==.潴潴灬小鑫:BAAALgAFFAIJBAABLgAFFAMJBAAEAAAAAA==.',
['澈欢']='澈欢:BAAALgADCgIJAgAAAA==.',
['澪境']='澪境:BAAALgAECgIJAgAAAA==.',
['激发']='激发队友潜能:BAAALgADCgMJAwAAAA==.',
['火包']='火包女且:BAAALgAECgQJBAAAAA==.',
['灬幻']='灬幻丶灵:BAACLgAFFH8HAAIDAAMJYgzZEgDSAAADAAMJYgzZEgDSAAAuAAQKfyMAAwMACAkNHdoTAJcCAAMACAkNHdoTAJcCABgABAnqFlJTANkAAAAA.',
['灬想']='灬想你:BAAALgADCgEJAQAAAA==.',
['灬抹']='灬抹茶星冰乐:BAAALgAECgUJBQAAAA==.',
['灬暴']='灬暴躁灬:BAABLgAFFH8GAAMVAAMJkQdhFADOAAAVAAMJSAVhFADOAAAnAAEJZAzCEAA9AAAAAA==.',
['灰毛']='灰毛衣:BAAALgAFFAQJBAAAAA==.',
['灰灰']='灰灰西卡:BAAALgAECgIJAgAAAA==.',
['灰烬']='灰烬之瞳:BAAALgAECgcJCwAAAA==.',
['灰隼']='灰隼:BAAALgAECgQJBwAAAA==.',
['灼心']='灼心斯卡蒂丶:BAAALgAFFAMJAwAAAA==.',
['灼骨']='灼骨阳炎:BAAALgAFFAIJBAAAAA==.',
['炎湮']='炎湮落花箫:BAACLgAFFH8QAAQQAAQJvhe+BAA6AQAQAAQJvhe+BAA6AQAiAAMJXwbNDADdAAALAAMJVw1YFACTAAAuAAQKfxQABAsABwn9FjEaAMcBAAsABwnnFDEaAMcBACIABQkjFWcrAIABABAABAmcGelLAAkBAAAA.',
['炖鸡']='炖鸡宝宝:BAAALgAECgEJAQABLgAFFAIJBAAEAAAAAA==.',
['炭子']='炭子丶:BAABLgAFFH8GAAIMAAMJTAriDADCAAAMAAMJTAriDADCAAAAAA==.',
['炸猪']='炸猪排丶:BAABLgAECn8YAAMPAAcJIBFNNgB6AQAPAAcJWQ9NNgB6AQAXAAYJ+g7/FQBeAQABLgAFFAYJFgAZAJQiAA==.',
['烈火']='烈火旸:BAAALgAFFAMJBAAAAA==.',
['無情']='無情战:BAAALgAECgMJAwAAAA==.',
['無鸡']='無鸡鲅鱼丶:BAABLgAFFH8FAAIRAAIJ2xa5MgCtAAARAAIJ2xa5MgCtAAAAAA==.',
['焦糖']='焦糖雪饼:BAAALgAECgYJBwAAAA==.',
['焱霜']='焱霜鹰:BAACLgAFFH8FAAIMAAMJxADtGwCOAAAMAAMJxADtGwCOAAAuAAQKfx4AAgwABwlGCto9AE4BAAwABwlGCto9AE4BAAAA.',
['熊丶']='熊丶空空:BAAALgAFFAQJBAAAAA==.',
['熊妹']='熊妹妹丶:BAAALgADCgEJAQAAAA==.',
['熊抱']='熊抱警告:BAAALgADCgcJBwAAAA==.',
['熊根']='熊根根:BAAALgAECgYJBwABLgAECgcJDgAEAAAAAA==.',
['熊爸']='熊爸:BAABLgAFFH8GAAMYAAMJJgkRCQDTAAAYAAMJPAURCQDTAAAeAAIJKAoDBQBvAAAAAA==.',
['熊猫']='熊猫丸子:BAAALgADCgUJBQAAAA==.',
['熊的']='熊的白丶:BAAALgADCgMJAwAAAA==.',
['熔岩']='熔岩爆裂蛋糕:BAABLgAFFH8HAAITAAMJSQbhGADkAAATAAMJSQbhGADkAAAAAA==.',
['爆兜']='爆兜兜:BAAALgAECgcJEgAAAA==.',
['爱丽']='爱丽数码:BAAALgAECggJDgAAAA==.',
['爱伺']='爱伺机摸人:BAAALgAECgQJBAAAAA==.',
['爱则']='爱则拉丝:BAAALgAECgEJAQAAAA==.',
['爱喝']='爱喝果粒橙橙:BAAALgAECgQJBAAAAA==.爱喝茅台:BAAALgAECgYJBwAAAA==.',
['爱尔']='爱尔兰炖肉:BAAALgAECgUJBQAAAA==.',
['爱舍']='爱舍离:BAAALgAFFAEJAQAAAA==.',
['牛叫']='牛叫兽:BAABLgAFFH8GAAIHAAIJLByaFAC1AAAHAAIJLByaFAC1AAAAAA==.',
['牛奶']='牛奶扎糖:BAAALgAECgEJAQAAAA==.',
['牛灬']='牛灬子豪:BAABLgAECn8iAAMVAAcJ1xw2HwBXAgAVAAcJ1xw2HwBXAgAnAAEJnwUYSgApAAAAAA==.',
['牛牛']='牛牛尾巴:BAAALgAECgYJDAAAAA==.',
['牛翻']='牛翻喜:BAAALgAECgcJBwAAAA==.',
['牛顿']='牛顿元帅:BAAALgAECgYJCwAAAA==.',
['牢龙']='牢龙:BAAALgAECgkJBgABLgAFFAYJAwAEAAAAAA==.',
['牧有']='牧有文化:BAAALgADCgEJAQAAAA==.',
['牧野']='牧野晨风:BAAALgAECgQJBAAAAA==.',
['特诺']='特诺奇蒂特兰:BAAALgAECgcJDQAAAA==.',
['犦猦']='犦猦焱龍:BAAALgAECggJDQAAAA==.',
['犹格']='犹格索托斯:BAAALgAECgIJAwABLgAFFAYJGAARAJAlAA==.',
['狂暴']='狂暴毛毛虫:BAAALgADCgEJAQAAAA==.',
['狐狸']='狐狸爱上猫:BAAALgAFFAEJAQAAAA==.',
['狗熊']='狗熊岭三兄弟:BAAALgADCgEJAQAAAA==.',
['狗狗']='狗狗祟祟:BAAALgAECgkJCQAAAA==.',
['狩猎']='狩猎大师栏杆:BAAALgAECgEJAQAAAA==.',
['独门']='独门到宁健灬:BAAALgAECgYJCQAAAA==.',
['狼之']='狼之召唤者:BAAALgAECgcJBwAAAA==.',
['狼怨']='狼怨:BAAALgAECgUJBQAAAA==.',
['猪头']='猪头牧:BAAALgAECgMJAwAAAA==.',
['猫玖']='猫玖丶:BAAALgAFFAEJAQABLgAFFAIJBAAEAAAAAA==.',
['玄白']='玄白:BAACLgAFFH8FAAIBAAMJYBdXKAASAQABAAMJYBdXKAASAQAuAAQKfyMAAgEACAkGI+4UACsDAAEACAkGI+4UACsDAAAA.',
['玄霜']='玄霜:BAAALgADCgUJBQAAAA==.',
['王串']='王串场老大哥:BAAALgADCgcJBwAAAA==.',
['王九']='王九壹:BAAALgAECgkJCAAAAA==.',
['王仙']='王仙芝:BAAALgAECgcJCgAAAA==.',
['王根']='王根硕:BAAALgAECgcJCwAAAA==.',
['王牌']='王牌飞行员:BAAALgAECgEJAQAAAA==.',
['王玖']='王玖一:BAAALgAECgcJBwABLgAECgkJCAAEAAAAAA==.',
['玖悦']='玖悦:BAAALgAECgYJBwAAAA==.',
['玖袋']='玖袋丶長佬:BAAALgAECgIJAgAAAA==.',
['玛卡']='玛卡笆卡:BAACLgAFFH8NAAMaAAQJgyMtBwAvAQAaAAMJbx8tBwAvAQACAAIJSyJyGQC7AAAuAAQKfxUAAwIACAkTHYErAM4BAAIABwnXGYErAM4BABoABQmQH1RFAJsBAAAA.',
['玛薇']='玛薇卡丶:BAAALgAECgUJBQAAAA==.',
['玛露']='玛露希尔:BAAALgAECgEJAQAAAA==.',
['玩具']='玩具巨龙:BAACLgAFFH8IAAIbAAMJayb0CABZAQAbAAMJayb0CABZAQAuAAQKfxcAAxsABwm1IhUJAKUCABsABgmeJhUJAKUCAB8AAgm0DcpUAHEAAAAA.玩具鸡:BAABLgAFFH8IAAIYAAMJ7hCfDgD2AAAYAAMJ7hCfDgD2AAAAAA==.玩具龙:BAAALgAECgYJEQAAAA==.',
['琉瑅']='琉瑅:BAAALgAECgEJAQAAAA==.',
['琉璃']='琉璃清袂:BAAALgAECgcJDAAAAA==.',
['琥珀']='琥珀川:BAAALgAECgYJDAAAAA==.',
['瑾年']='瑾年丨拉布布:BAAALgAECgYJBwAAAA==.',
['璐瑶']='璐瑶不知马力:BAAALgAFFAUJBAABLgAFFAYJAgAEAAAAAA==.',
['瓦利']='瓦利安丶:BAAALgAECgYJCQABLgAECgYJDQAEAAAAAA==.',
['甑曦']='甑曦:BAAALgAECgkJCAAAAA==.',
['生在']='生在红旗下:BAAALgAECgQJBwABLgAFFAYJFgAPAMUZAA==.',
['生烫']='生烫牛肉面:BAABLgAFFH8FAAIIAAMJ2hEDJgD+AAAIAAMJ2hEDJgD+AAAAAA==.',
['电波']='电波草莓:BAAALgADCgIJAgAAAA==.',
['电车']='电车难题:BAABLgAFFH8NAAIDAAUJWBduAgCeAQADAAUJWBduAgCeAQAAAA==.',
['番茄']='番茄:BAABLgAFFH8HAAMLAAMJoAD0EgCeAAALAAMJoAD0EgCeAAAQAAIJmgBSGAAwAAAAAA==.',
['疯一']='疯一样的牛:BAAALgAECgEJAgAAAA==.',
['疯狂']='疯狂的瓶子:BAAALgAECgEJAQAAAA==.',
['登天']='登天德:BAAALgAECgEJAQAAAA==.',
['白丶']='白丶樱花:BAAALgAECgEJAQAAAA==.白丶水:BAAALgAFFAEJAQAAAA==.白丶白:BAAALgAFFAEJAQAAAA==.',
['白也']='白也诗乄敌:BAAALgAECgMJBAAAAA==.',
['白敬']='白敬亭:BAAALgAECgUJBwAAAA==.',
['白桃']='白桃乌龙:BAAALgAFFAQJBAABLgAFFAQJCwAOAK4aAA==.',
['白鸟']='白鸟非鸟:BAAALgAECgcJDQABLgAECgcJHwAjAJ8bAA==.',
['白鼠']='白鼠:BAAALgAECgcJCgABLgAFFAIJAgAEAAAAAA==.',
['白龙']='白龙希斯:BAAALgAECgYJCwAAAA==.',
['百万']='百万别:BAAALgAECggJDAAAAA==.',
['百变']='百变铁花花:BAAALgADCgcJBwAAAA==.',
['百花']='百花酿豆腐:BAAALgAECggJCgAAAA==.',
['皇牛']='皇牛:BAAALgAECgYJBwABLgAFFAMJCAAVAGQaAA==.',
['皈头']='皈头:BAAALgAECgkJCQAAAA==.',
['皓月']='皓月当空:BAABLgAFFH8NAAIBAAUJyRvbBgB1AQABAAUJyRvbBgB1AQAAAA==.皓月星痕:BAABLgAFFH8IAAIRAAMJFSFuFwA1AQARAAMJFSFuFwA1AQAAAA==.',
['皮纳']='皮纳格的浪漫:BAAALgAECgYJBwAAAA==.',
['盐奶']='盐奶盖啊:BAAALgAECgMJBAAAAA==.',
['盖聂']='盖聂:BAACLgAFFH8LAAIOAAQJrhq5BgB0AQAOAAQJrhq5BgB0AQAuAAQKfxoAAg4ACAk3Hk8SAIsCAA4ACAk3Hk8SAIsCAAAA.',
['盲丶']='盲丶僧:BAAALgAECgUJBQAAAA==.',
['盲眼']='盲眼者丶阿炳:BAAALgAECgEJAQAAAA==.',
['相信']='相信我就是光:BAACLgAFFH8FAAITAAMJchHMFAACAQATAAMJchHMFAACAQAuAAQKfyEAAxMACAkTIcMQAAkDABMACAkTIcMQAAkDAAoAAwk4AmmCAG4AAAAA.',
['眉间']='眉间雪:BAAALgAECgYJDAABLgAFFAIJBAAEAAAAAA==.',
['看蓝']='看蓝猫学蓝猫:BAAALgADCgEJAQAAAA==.',
['真不']='真不想玩术:BAAALgAFFAIJAgAAAA==.真不想玩浩劫:BAAALgADCgYJBgAAAA==.',
['真是']='真是好人:BAAALgAFFAIJAgAAAA==.',
['真的']='真的值得吗:BAAALgAECgYJCwAAAA==.',
['眷念']='眷念少年情愁:BAAALgAFFAIJAgAAAA==.',
['知花']='知花也未:BAAALgAECgYJDAAAAA==.',
['短粗']='短粗熊叔:BAAALgAECgEJAQAAAA==.',
['石头']='石头塞不满:BAAALgADCgEJAQAAAA==.',
['码民']='码民:BAABLgAFFH8HAAMMAAIJUBUGGgCaAAAMAAIJUBUGGgCaAAAgAAEJThm+FQBMAAAAAA==.',
['砂之']='砂之惑星:BAAALgAFFAMJAwABLgAFFAUJEgAHAK0iAA==.',
['破碎']='破碎新月:BAAALgAFFAIJAwAAAA==.',
['破约']='破约:BAAALgAECgcJBwAAAA==.',
['碎碎']='碎碎念的熊熊:BAAALgADCgUJBQAAAA==.',
['碗姐']='碗姐:BAAALgADCgQJBAAAAA==.',
['祁同']='祁同伟:BAAALgAECgYJBgAAAA==.',
['祁本']='祁本里香:BAAALgAECgEJAQAAAA==.',
['神奇']='神奇小精灵:BAAALgADCgIJAgAAAA==.',
['神姿']='神姿舞姿:BAAALgAECgIJAgAAAA==.',
['神志']='神志雅悟:BAAALgAFFAEJAQAAAA==.',
['神牛']='神牛都是浮云:BAAALgAECgUJCAAAAA==.',
['神者']='神者来:BAAALgADCgEJAQAAAA==.',
['神説']='神説丶要有光:BAAALgAECgUJBQAAAA==.',
['神谷']='神谷薰:BAAALgAECgYJDwAAAA==.',
['神龙']='神龙丸:BAAALgAFFAQJBAAAAA==.',
['离殇']='离殇情:BAAALgAECgEJAQAAAA==.',
['秃灵']='秃灵:BAAALgAECgEJAQAAAA==.',
['秋凉']='秋凉花语:BAABLgAFFH8IAAIGAAQJYw3JEwDYAAAGAAQJYw3JEwDYAAAAAA==.',
['秦箭']='秦箭:BAAALgAECgcJCgAAAA==.',
['穆里']='穆里尼奥:BAABLgAFFH8FAAIHAAUJsB6CAADwAQAHAAUJsB6CAADwAQAAAA==.',
['穗辫']='穗辫丸丸灬:BAAALgAECgMJAwAAAA==.',
['穷哥']='穷哥们:BAAALgAECgQJBgAAAA==.',
['空巷']='空巷的空想:BAAALgAECgcJCAAAAA==.',
['空格']='空格躲冰环丶:BAAALgAECgEJAQAAAA==.',
['空空']='空空叔叔:BAAALgAECgcJBwAAAA==.',
['穿心']='穿心茉莉:BAAALgADCgUJAgAAAA==.',
['竹国']='竹国狂小猛:BAAALgAECgYJBgAAAA==.',
['笨蛋']='笨蛋青了蛙:BAAALgADCgEJAQAAAA==.',
['第四']='第四个影子:BAAALgAECgUJBQAAAA==.',
['筋肉']='筋肉人:BAAALgAECgYJBwAAAA==.',
['米拉']='米拉娜灬:BAABLgAECn8UAAMaAAcJUSVDCAAMAwAaAAcJUSVDCAAMAwACAAUJBBdYTAAgAQABLgAFFAcJCgABAO4cAA==.',
['米村']='米村长:BAAALgAECgEJAQAAAA==.',
['粗尾']='粗尾猫:BAAALgAECgMJAwAAAA==.',
['粗猫']='粗猫尾:BAAALgAECgIJAgAAAA==.',
['粽子']='粽子节吃元宵:BAECLgAFFH8MAAIRAAQJiw5wCgA/AQARAAQJiw5wCgA/AQAuAAQKfxcAAxEACAk6IUMQAPgCABEACAk6IUMQAPgCABQAAQkAAPExADoAAAAA.',
['精轲']='精轲:BAAALgAECgYJBQAAAA==.',
['精通']='精通小子:BAACLgAFFH8JAAMPAAMJUxmYDgADAQAPAAMJUxmYDgADAQAHAAIJ+w5CDwCSAAAuAAQKfxcABA8ACAkdHKwGAMQBAA8ABwkyHawGAMQBABcAAgn+BkonAGYAAAcAAglYHfSMAGEAAAAA.',
['糖醋']='糖醋小龙虾:BAACLgAFFH8HAAIPAAMJRCH3CwAtAQAPAAMJRCH3CwAtAQAuAAQKfyMAAw8ACAlWICQLAOYCAA8ACAlWICQLAOYCAAcAAgl1DhSKAGwAAAAA.糖醋里脊:BAAALgAFFAIJBAABLgAFFAQJCAAMALATAA==.',
['糖门']='糖门呼我:BAAALgAECgcJEQAAAA==.',
['素手']='素手引清辉:BAAALgAECgkJCQAAAA==.',
['素还']='素还菇:BAABLgAFFH8FAAIMAAQJPhE4DAAjAQAMAAQJPhE4DAAjAQAAAA==.素还菇菇:BAAALgAECgYJBgAAAA==.',
['紫色']='紫色圣灵:BAAALgADCgUJBQAAAA==.紫色幻化哥:BAABLgAFFH8IAAIGAAQJpRnTDgBYAQAGAAQJpRnTDgBYAQABLgAFFAYJAgAEAAAAAA==.紫色幻化弟:BAAALgAFFAUJAQABLgAFFAYJAgAEAAAAAA==.紫色狠有孕味:BAAALgAFFAYJAgABLgAFFAYJAgAEAAAAAA==.紫色罪有孕味:BAAALgAFFAUJAwABLgAFFAYJAgAEAAAAAA==.',
['紫薇']='紫薇自滋味:BAAALgADCgMJAwAAAA==.',
['紫龙']='紫龙:BAAALgAECgcJBwAAAA==.',
['紳士']='紳士丶猫:BAABLgAFFH8HAAIiAAMJDAk5DADuAAAiAAMJDAk5DADuAAAAAA==.',
['練丶']='練丶白龍:BAAALgAECgQJBQAAAA==.',
['红油']='红油爆椒仔鸡:BAAALgAECgcJCgAAAA==.',
['红烧']='红烧香咕:BAAALgAFFAIJAgAAAA==.',
['红皮']='红皮鞋丶:BAAALgAECgYJCAAAAA==.',
['红色']='红色豆豆鞋:BAAALgAFFAIJAQAAAA==.',
['红豆']='红豆月灼:BAAALgADCgIJAgAAAA==.',
['纱卡']='纱卡奶爸:BAABLgAFFH8GAAIKAAIJZBfAEgCyAAAKAAIJZBfAEgCyAAAAAA==.',
['纲手']='纲手:BAAALgADCgEJAQAAAA==.',
['纳兰']='纳兰康:BAAALgAECgEJAQAAAA==.',
['纸短']='纸短情长:BAAALgADCgcJBwAAAA==.',
['练劈']='练劈叉的毒蛇:BAAALgAECgcJEgAAAA==.',
['绝美']='绝美:BAAALgADCgYJBgAAAA==.',
['绡扬']='绡扬:BAACLgAFFH8HAAIBAAMJ6A+nLgD8AAABAAMJ6A+nLgD8AAAuAAQKfyMAAgEACAkQIJUwALACAAEACAkQIJUwALACAAAA.',
['绪钦']='绪钦:BAAALgAFFAIJBAAAAA==.',
['绯鸢']='绯鸢:BAAALgAECgEJAQABLgAFFAIJBAAEAAAAAA==.',
['维维']='维维恩:BAAALgAECgEJAQAAAA==.',
['绽放']='绽放如花:BAABLgAFFH8MAAIHAAUJqBaxAQChAQAHAAUJqBaxAQChAQABLgAFFAUJEgAHAK0iAA==.',
['绿皮']='绿皮水鬼:BAAALgAFFAIJAwAAAA==.',
['缇丝']='缇丝托莉亚:BAAALgAECgcJDAAAAA==.',
['缝上']='缝上都不给:BAAALgAECgUJBQAAAA==.',
['缨络']='缨络:BAAALgAECgEJAQAAAA==.',
['网恋']='网恋骗人三万:BAAALgAECgMJAwAAAA==.',
['罗小']='罗小鸡:BAAALgAECgYJCQAAAA==.',
['羊濄']='羊濄小笼女:BAAALgAECgkJEAAAAA==.',
['美燈']='美燈丶:BAAALgAECgEJAQAAAA==.',
['翠翠']='翠翠猫:BAABLgAFFH8IAAIMAAIJbx1rFwC1AAAMAAIJbx1rFwC1AAAAAA==.',
['翻车']='翻车爆裂拳:BAAALgAECgUJBQAAAA==.',
['老太']='老太半夜五杀:BAAALgADCgcJBwAAAA==.',
['老娘']='老娘韵犹存:BAAALgAECgYJBQAAAA==.',
['老子']='老子为所欲为:BAAALgAECgYJCQAAAA==.',
['考拉']='考拉丶慢慢:BAAALgAECgEJAQAAAA==.考拉丶熟食:BAAALgAECgYJDwAAAA==.',
['聖啟']='聖啟獅:BAAALgAECgYJDgAAAA==.',
['肉墩']='肉墩:BAAALgAECgMJBgAAAA==.',
['肖战']='肖战头号粉丝:BAAALgAFFAEJAgAAAA==.',
['背心']='背心猛虎:BAAALgAECgYJCQABLgAFFAMJBgANAEwNAA==.背心黑洞:BAABLgAFFH8GAAMNAAMJTA1wAwCyAAANAAMJTA1wAwCyAAATAAIJvAWJKQCRAAAAAA==.',
['胖宝']='胖宝宝熊:BAAALgAECgcJDgAAAA==.',
['胖达']='胖达达:BAAALgAFFAEJAQAAAA==.',
['胡滕']='胡滕:BAAALgAECgUJBQAAAA==.',
['胸肌']='胸肌夹死苍蝇:BAAALgAFFAEJAQAAAA==.',
['脆皮']='脆皮鹅鹅鵝:BAAALgAECgYJBgAAAA==.',
['脖子']='脖子右宁:BAAALgAECgEJAQAAAA==.',
['脚麻']='脚麻吗:BAAALgAFFAEJAQAAAA==.',
['腊狗']='腊狗:BAAALgAECgYJBgAAAA==.',
['腦漿']='腦漿四射:BAAALgAECgkJDgAAAA==.',
['腰疼']='腰疼:BAAALgAFFAIJAwAAAA==.',
['腳踢']='腳踢會爆鸡:BAAALgAECgUJBgAAAA==.',
['自然']='自然崩:BAAALgAECgEJAQAAAA==.',
['自由']='自由夸克:BAAALgAFFAIJAgAAAA==.自由漫步:BAAALgAECgYJEQAAAA==.',
['舞風']='舞風:BAAALgAECgEJAQAAAA==.',
['艾伦']='艾伦小德:BAAALgAECgYJCgAAAA==.',
['艾叶']='艾叶丶:BAABLgAECn8WAAIDAAYJPhd6RwCEAQADAAYJPhd6RwCEAQAAAA==.',
['艾姆']='艾姆褅:BAAALgADCgEJAQAAAA==.',
['芋圆']='芋圆豆花:BAABLgAECn8VAAITAAcJexlrSQAGAgATAAcJexlrSQAGAgAAAA==.',
['芝士']='芝士猎仁:BAAALgAECgEJAQAAAA==.芝士盗賊:BAAALgAECgMJBAAAAA==.',
['芝麻']='芝麻小汤团:BAAALgAECgQJBAAAAA==.',
['芥末']='芥末难吃:BAAALgAFFAEJAQAAAA==.',
['芯苡']='芯苡橙橙:BAACLgAFFH8HAAMFAAMJ+QNGAwDSAAAFAAMJ+QNGAwDSAAAGAAEJXQCEPAAzAAAuAAQKfx4AAwUACAmeHDsLAK0CAAUACAmeHDsLAK0CAAYAAglcCcbMAFwAAAAA.',
['花开']='花开富贵啊:BAAALgADCgUJBQAAAA==.',
['花束']='花束之下:BAAALgAFFAIJAgABLgAFFAUJEgAHAK0iAA==.',
['花茂']='花茂茂:BAAALgAECgYJAgAAAA==.',
['花落']='花落:BAAALgAECgYJCQABLgAECgYJDQAEAAAAAA==.花落春残:BAAALgAECgYJDQAAAA==.',
['苏伊']='苏伊什:BAAALgAECgYJCgAAAA==.',
['苦修']='苦修不动:BAAALgAECgYJBwAAAA==.',
['范乔']='范乔丹:BAAALgAECgEJAQAAAA==.',
['范尼']='范尼斯德:BAAALgAECgQJCAAAAA==.',
['荧月']='荧月:BAAALgAECgcJEAAAAA==.',
['莎莉']='莎莉娜:BAAALgAECgEJAQABLgAFFAIJBgAPAH0cAA==.',
['莫牛']='莫牛牛:BAAALgADCgUJBQAAAA==.',
['莫甘']='莫甘娜:BAAALgAECgIJAwAAAA==.',
['莫知']='莫知我哀:BAACLgAFFH8eAAQRAAcJqyJ2AAB0AgARAAYJsyR2AAB0AgASAAUJUBwOAQDzAQAUAAEJAADCBABZAAAuAAQKfxsAAxEACQlAJEoHAEwDABEACQntI0oHAEwDABIAAwl3JC8kADgBAAAA.',
['莱布']='莱布拉:BAAALgAECgYJEQAAAA==.',
['菜篮']='菜篮子:BAABLgAFFH8IAAIDAAQJGh+dCgAxAQADAAQJGh+dCgAxAQAAAA==.',
['菜薹']='菜薹:BAACLgAFFH8PAAMaAAQJMxP1CwADAQACAAQJ6wgyEgAXAQAaAAQJTRL1CwADAQAuAAQKfx0AAwIACAkzHV8WAHoCAAIACAkzHV8WAHoCABoAAwkKFU1+AOwAAAAA.',
['菠萝']='菠萝鸡肉盖饭:BAAALgAECggJAwABLgAFFAQJBQARAAkQAA==.',
['菱梦']='菱梦:BAAALgAECgUJCAAAAA==.',
['菲尔']='菲尔莉莉:BAAALgAECgEJAQAAAA==.',
['萌萌']='萌萌哒哈宝宝:BAAALgAECgEJAQAAAA==.萌萌灬软妹子:BAAALgAECgYJCwAAAA==.',
['萧凌']='萧凌:BAAALgAECgcJDAAAAA==.',
['落日']='落日与晚风灬:BAAALgAECgkJCQAAAA==.',
['葬影']='葬影小囧猪丶:BAACLgAFFH8OAAIPAAQJ6CMrBACkAQAPAAQJ6CMrBACkAQAuAAQKfyUAAw8ACAnkIhMGADIDAA8ACAnkIhMGADIDAAcABwkOHkIrAOABAAAA.',
['葱烧']='葱烧鸡腿肉:BAAALgAECgYJEQABLgAFFAUJBAAEAAAAAA==.',
['蒙丨']='蒙丨牛丨丹:BAAALgAECgYJDAAAAA==.',
['蓝波']='蓝波酱:BAAALgAFFAIJBAAAAA==.',
['蓝海']='蓝海精灵王:BAAALgAFFAQJBAABLgAFFAYJCgAWAH4fAA==.',
['蓝色']='蓝色学渣:BAACLgAFFH8RAAIBAAQJuR01FQB1AQABAAQJuR01FQB1AQAuAAQKfxkAAgEACAlfIU0yAKkCAAEACAlfIU0yAKkCAAAA.蓝色恶魔:BAAALgAECgYJCAAAAA==.蓝色的风:BAAALgAECgcJEgAAAA==.蓝色等于忧伤:BAAALgADCgQJBAABLgAFFAMJCgAIAGMiAA==.',
['薄荷']='薄荷双生:BAACLgAFFH8JAAIBAAMJ9x0JFQANAQABAAMJ9x0JFQANAQAuAAQKfxMAAgEABgnlI/I/AHkCAAEABgnlI/I/AHkCAAAA.薄荷尘:BAAALgAFFAEJAQAAAA==.薄荷苏打:BAAALgADCgEJAQAAAA==.',
['虎弟']='虎弟:BAACLgAFFH8GAAIhAAIJ7QzVDQCUAAAhAAIJ7QzVDQCUAAAuAAQKfxQAAiEACAlVGnIiAMIBACEACAlVGnIiAMIBAAAA.',
['虚空']='虚空底欸起:BAAALgAFFAQJBAABLgAFFAYJAgAEAAAAAA==.',
['蚊子']='蚊子叮叮:BAAALgAECgMJAwAAAA==.',
['蛄蛹']='蛄蛹者:BAAALgAFFAIJAgAAAA==.',
['蛋蛋']='蛋蛋啊:BAAALgAECgYJBAAAAA==.',
['蛮蠻']='蛮蠻破布:BAAALgAECgcJCgAAAA==.',
['蜜三']='蜜三刀:BAAALgADCgEJAQAAAA==.',
['蜜鯨']='蜜鯨虫:BAAALgAECgUJBgABLgAECgcJDgAEAAAAAA==.',
['蜡笔']='蜡笔没笔芯:BAAALgAECgIJAgAAAA==.',
['蜥铁']='蜥铁石:BAAALgAECgcJDQAAAA==.',
['融道']='融道长:BAABLgAECn8YAAMQAAcJ5RiaIADdAQAQAAcJ5RiaIADdAQALAAQJSAQDQgCjAAAAAA==.',
['螟蛊']='螟蛊:BAAALgAECgcJDgAAAA==.',
['血月']='血月骑士:BAAALgAECgIJAgAAAA==.',
['血腥']='血腥瑪丽:BAAALgAECgYJBgAAAA==.',
['血色']='血色慕斯:BAAALgAECgYJDAAAAA==.',
['行天']='行天宫外:BAAALgAECgkJCQAAAA==.',
['袁四']='袁四杏:BAAALgAECgQJBAAAAA==.',
['袁崇']='袁崇焕字元素:BAAALgAFFAIJAgAAAA==.',
['裂穿']='裂穿牙:BAAALgADCgEJAQAAAA==.',
['西北']='西北望射天狼:BAACLgAFFH8MAAMaAAQJzBo0AgB9AQAaAAQJzBo0AgB9AQACAAEJGAOuLABAAAAuAAQKfyMAAxoACAnRItgJAPoCABoABwkDJdgJAPoCAAIABgkNHNs1AI4BAAAA.',
['西替']='西替利嗪:BAAALgAFFAIJAwAAAA==.',
['西湖']='西湖龙井:BAAALgADCgYJBgAAAA==.',
['訫灬']='訫灬宇:BAAALgAECgIJAwAAAA==.',
['詹弗']='詹弗朗哥:BAABLgAECn8VAAIYAAYJIBQqNABuAQAYAAYJIBQqNABuAQAAAA==.',
['謎誓']='謎誓:BAAALgAECgEJAQAAAA==.',
['让键']='让键飞一会:BAAALgAECgQJBgAAAA==.',
['诅咒']='诅咒玫瑰:BAAALgAECgIJAgAAAA==.',
['说不']='说不出来感觉:BAAALgAFFAEJAQAAAA==.',
['请叫']='请叫我好人:BAACLgAFFH8GAAMRAAMJjBbcLQC4AAARAAIJyhrcLQC4AAASAAEJDw5tFQBUAAAuAAQKfxQAAxEABwlQH3I0ADoCABEABwkaHnI0ADoCABIABQl4Ga4ZAH8BAAAA.',
['谛听']='谛听多莉苏尔:BAAALgAECgcJBwAAAA==.',
['豆崽']='豆崽:BAAALgAFFAEJAQAAAA==.',
['豆腐']='豆腐脑忒甜:BAAALgAFFAIJBAAAAA==.',
['贺茂']='贺茂义心:BAAALgAFFAEJAQABLgAFFAIJBAAEAAAAAA==.',
['贼惦']='贼惦记萌武僧:BAAALgADCgcJBwAAAA==.贼惦记骑士牛:BAAALgADCgcJDgAAAA==.',
['贾贵']='贾贵:BAAALgAECgYJBgAAAA==.',
['赤红']='赤红猫爪子:BAACLgAFFH8GAAIIAAIJPCVQLwDYAAAIAAIJPCVQLwDYAAAuAAQKfxkAAggABwk9JUIXAPACAAgABwk9JUIXAPACAAAA.',
['赫斯']='赫斯乄提亚:BAAALgAECgYJBgAAAA==.',
['超凡']='超凡双生:BAAALgAECgYJDAAAAA==.',
['超大']='超大牛角子:BAAALgAECgYJCQAAAA==.',
['超弹']='超弹力牛肉丸:BAAALgAECgQJBAAAAA==.',
['趟尸']='趟尸术:BAAALgADCgIJAgAAAA==.',
['跑的']='跑的很慢:BAAALgAECgYJBgAAAA==.',
['跟丫']='跟丫拼了:BAAALgAECgUJBQAAAA==.',
['路易']='路易斯破輪子:BAAALgAFFAIJAwAAAA==.路易斯破饺子:BAABLgAFFH8GAAIDAAMJ0RYQCgDlAAADAAMJ0RYQCgDlAAAAAA==.',
['輕骨']='輕骨頭:BAACLgAFFH8FAAIOAAMJKBMxEwCzAAAOAAMJKBMxEwCzAAAuAAQKfyMAAg4ACAndFYoXAE0CAA4ACAndFYoXAE0CAAAA.',
['轩辕']='轩辕逸丶曌:BAAALgAECgEJAQAAAA==.',
['软软']='软软的毛毛:BAAALgAECgUJCAAAAA==.',
['辣相']='辣相两记:BAABLgAFFH8IAAInAAMJAAbnCQCwAAAnAAMJAAbnCQCwAAAAAA==.',
['边走']='边走边杀:BAAALgAECgMJBAAAAA==.边走边飞:BAAALgAECgYJCAAAAA==.',
['过期']='过期的时间:BAAALgADCgYJBgAAAA==.',
['迈勒']='迈勒佛冷:BAAALgAECgYJBgAAAA==.',
['运动']='运动:BAAALgAECgcJBwAAAA==.',
['近战']='近战地皮爱斯:BAACLgAFFH8LAAIbAAQJORfTBABCAQAbAAQJORfTBABCAQAuAAQKfxgAAhsACAlGIVMFAPYCABsACAlGIVMFAPYCAAAA.',
['这么']='这么这么叼:BAAALgAECgMJAwAAAA==.',
['远方']='远方:BAAALgADCgYJBgAAAA==.',
['远程']='远程地皮哀斯:BAAALgAECgcJCwAAAA==.',
['违规']='违规的夏亚:BAAALgAECgcJDwAAAA==.',
['迪尔']='迪尔卡纳:BAABLgAFFH8JAAIKAAMJjyWfBABLAQAKAAMJjyWfBABLAQAAAA==.迪尔卡纳咪:BAABLgAFFH8GAAIgAAMJzB4YBgARAQAgAAMJzB4YBgARAQAAAA==.',
['迪布']='迪布丽托:BAAALgAECgcJBwAAAA==.',
['迪迪']='迪迪丶威:BAAALgAECgcJBAAAAA==.',
['追击']='追击者:BAAALgAECgcJEQAAAA==.',
['追忆']='追忆乌鸦:BAABLgAECn8gAAQSAAkJ2Bm1EADJAQASAAYJjhq1EADJAQARAAYJbxPDOADQAAAUAAIJDyYQBwBzAAAAAA==.追忆逝去年华:BAAALgAECgEJAQAAAA==.',
['逆丶']='逆丶零:BAAALgAECgcJBwAAAA==.',
['逆时']='逆时针丷:BAABLgAFFH8FAAIRAAUJXxtOBADaAQARAAUJXxtOBADaAQAAAA==.',
['逐凨']='逐凨:BAABLgAFFH8FAAIMAAMJZQqgFQDIAAAMAAMJZQqgFQDIAAAAAA==.',
['通电']='通电魔尊:BAABLgAECn8XAAIHAAcJdBprIAAdAgAHAAcJdBprIAAdAgAAAA==.',
['遥远']='遥远的阿瓦隆:BAAALgADCgEJAQAAAA==.',
['邙流']='邙流:BAAALgAECgQJBQAAAA==.',
['那个']='那个萨别划水:BAAALgADCgEJAQAAAA==.',
['那年']='那年敷衍:BAAALgAECgIJAgAAAA==.',
['邪冬']='邪冬的谎言:BAAALgAECgYJBwAAAA==.',
['邪恶']='邪恶的小豚:BAAALgAECgcJBwAAAA==.',
['部落']='部落白富美:BAAALgAFFAMJAwABLgAFFAYJFQAYAHIhAA==.',
['鄂霸']='鄂霸:BAAALgAECgEJAQAAAA==.',
['酒肉']='酒肉和尚:BAAALgADCgYJAQAAAA==.',
['酒舞']='酒舞丶至尊:BAAALgAECgEJAQAAAA==.',
['酥餠']='酥餠:BAAALgAECgcJEQAAAA==.',
['酷帅']='酷帅狂霸刁:BAAALgADCgUJBQAAAA==.',
['酷辣']='酷辣丫咪:BAAALgAECgYJBQAAAA==.',
['酸甜']='酸甜葡萄酱:BAAALgAECgUJBwAAAA==.',
['酸萝']='酸萝卜憋吃:BAAALgAECgkJCQAAAA==.',
['醉丶']='醉丶意丨:BAAALgAECgUJBwAAAA==.',
['醉飘']='醉飘香:BAAALgAECgMJAwAAAA==.',
['醒目']='醒目:BAAALgAFFAIJAQAAAA==.',
['重拳']='重拳粗击:BAABLgAFFH8FAAIhAAIJPh8SBgDAAAAhAAIJPh8SBgDAAAAAAA==.',
['野猫']='野猫丶娜美:BAAALgAECgYJBgAAAA==.',
['野良']='野良:BAAALgAECgYJDAAAAA==.',
['鑨櫳']='鑨櫳瀧爖壠:BAAALgAECgcJDQAAAA==.',
['钢羽']='钢羽:BAAALgAECgUJBAAAAA==.',
['钻石']='钻石王老四:BAAALgADCgYJBgAAAA==.',
['铁拳']='铁拳断风:BAAALgADCgEJAQAAAA==.',
['铅笔']='铅笔:BAAALgAECgYJBgAAAA==.',
['银临']='银临:BAAALgAECgYJCgAAAA==.',
['银河']='银河星辰:BAAALgAECgUJBQABLgAFFAQJEAAZAOsiAA==.',
['长留']='长留:BAAALgAECgYJCQAAAA==.',
['门前']='门前一群鸭:BAAALgAFFAEJAgAAAA==.',
['闪烁']='闪烁的发丝:BAABLgAFFH8FAAIBAAMJUgdnGwDjAAABAAMJUgdnGwDjAAAAAA==.',
['闪闪']='闪闪儿:BAAALgAECgYJBgAAAA==.',
['闭眼']='闭眼装瞎:BAAALgADCgcJBwAAAA==.',
['问题']='问题很尖锐:BAAALgAECggJDgAAAA==.',
['阮大']='阮大师:BAAALgAECgEJAQAAAA==.',
['阳见']='阳见惠凪:BAAALgAECgEJAQAAAA==.',
['阿兰']='阿兰朵贝尔蒂:BAAALgAECgYJCQAAAA==.',
['阿呆']='阿呆灬:BAACLgAFFH8HAAMWAAMJGRV9AwDQAAAWAAMJGRV9AwDQAAAVAAEJjAZNJABMAAAuAAQKfxQABBUACQkuEtJNAG8BABUABgkLE9JNAG8BABYAAgkKEWcuAIIAACcAAgn2DTU5AIAAAAEuAAUUBwkNACcAzhkA.',
['阿夏']='阿夏夏:BAAALgAFFAIJAgAAAA==.',
['阿尒']='阿尒萨斯神选:BAAALgADCgUJBQAAAA==.',
['阿德']='阿德哥的倔强:BAAALgAECgcJBwAAAA==.',
['阿慢']='阿慢苏尔:BAAALgAECgUJBwAAAA==.',
['阿柒']='阿柒启示录:BAAALgAECgUJBQAAAA==.',
['阿灬']='阿灬远:BAAALgADCgYJBgAAAA==.',
['阿牧']='阿牧牧丶:BAACLgAFFH8QAAIiAAQJEBXLAwA0AQAiAAQJEBXLAwA0AQAuAAQKfx0AAiIACQlDHqcFADQDACIACQlDHqcFADQDAAAA.',
['阿育']='阿育娅:BAAALgAECgIJAgAAAA==.',
['阿葛']='阿葛雷尔:BAAALgAECgEJAQAAAA==.',
['阿豹']='阿豹:BAAALgAECgMJAwAAAA==.',
['阿鬼']='阿鬼哥:BAAALgAECgEJAwAAAA==.',
['阿齐']='阿齐:BAAALgAFFAEJAQAAAA==.',
['陆柒']='陆柒叁柒叁灬:BAAALgAECgcJBwAAAA==.',
['陈伯']='陈伯:BAAALgAECgEJAQAAAA==.',
['陈某']='陈某眸丶:BAAALgAECgYJDwAAAA==.',
['降龙']='降龙尊者:BAAALgAECgEJAQAAAA==.',
['除了']='除了圣光不修:BAABLgAFFH8NAAIKAAQJxw+IBQAzAQAKAAQJxw+IBQAzAQAAAA==.除了小树不修:BAABLgAFFH8FAAIDAAIJNRJAEQCEAAADAAIJNRJAEQCEAAAAAA==.',
['陳奕']='陳奕迅所长:BAAALgAECgcJAgAAAA==.',
['随便']='随便起名:BAAALgADCgIJAgAAAA==.',
['雨逝']='雨逝无筝:BAAALgAFFAIJAwABLgAFFAIJBAAEAAAAAA==.',
['雪無']='雪無:BAAALgAECgEJAQABLgAFFAUJBQAIADsiAA==.',
['雪糕']='雪糕与烧烤:BAABLgAFFH8GAAIBAAMJCR93IgAyAQABAAMJCR93IgAyAQAAAA==.',
['零翼']='零翼边走:BAAALgAECgUJBwAAAA==.',
['零语']='零语:BAAALgAECgYJBgAAAA==.',
['零鱼']='零鱼鱼:BAABLgAECn8iAAMRAAgJIiBqDQAOAwARAAgJIiBqDQAOAwASAAQJxw6vNQDfAAAAAA==.',
['霜之']='霜之四季豆:BAAALgAECgIJAgAAAA==.霜之大灰狼:BAAALgAECgYJDQAAAA==.霜之小西几:BAAALgAECgYJDAAAAA==.霜之小馒头:BAABLgAECn8WAAMYAAgJSCCBDQDCAgAYAAgJSCCBDQDCAgADAAEJLgEz7AAWAAAAAA==.',
['霜冥']='霜冥:BAAALgAECgQJAQAAAA==.',
['霜杀']='霜杀墨染樱:BAABLgAECn8XAAIIAAkJzhZKMgBuAgAIAAkJzhZKMgBuAgAAAA==.',
['露西']='露西法:BAAALgAECgQJBAAAAA==.',
['霸小']='霸小骑:BAAALgAECgUJBQAAAA==.',
['霸王']='霸王杈汊衩:BAAALgAECgQJCAAAAA==.',
['霸霸']='霸霸牛:BAAALgAECgIJAgABLgAECgUJBQAEAAAAAA==.',
['靈魂']='靈魂風暴:BAAALgAECgEJAgAAAA==.',
['青僷']='青僷:BAACLgAFFH8IAAMQAAMJOxUlCQDVAAAQAAMJxwwlCQDVAAALAAMJ3BNmCgCoAAAuAAQKfxsAAxAABwnYHwIZABQCABAABgnNIAIZABQCAAsABgkfFz8bAL0BAAAA.',
['青山']='青山依然在:BAAALgAFFAEJAQAAAA==.',
['青皮']='青皮吴彦祖:BAAALgAECgQJBAAAAA==.',
['青随']='青随:BAAALgAECgYJCAAAAA==.',
['青鸦']='青鸦:BAAALgAECgUJCgAAAA==.',
['静墨']='静墨如烟:BAAALgAECgEJAQAAAA==.',
['韩艺']='韩艺瑟:BAAALgAECgUJCAAAAA==.',
['风中']='风中的小百合:BAAALgAECgUJBgAAAA==.风中的小菊花:BAAALgAFFAEJAQAAAA==.',
['风依']='风依旧:BAAALgAECgYJCgAAAA==.',
['风吹']='风吹雀雀扬:BAAALgAECgcJDAAAAA==.',
['风笛']='风笛:BAABLgAFFH8GAAIaAAMJPRLiCwADAQAaAAMJPRLiCwADAQAAAA==.',
['风雨']='风雨颂:BAAALgAECgMJAwAAAA==.',
['风雪']='风雪卡卡:BAAALgAECgQJBQAAAA==.',
['飘飘']='飘飘何所伊:BAAALgADCgMJAwAAAA==.飘飘何所似:BAEALgAECgQJBwABLgAFFAEJBAAEAAAAAA==.飘飘何所依:BAEALgAFFAEJBAAAAA==.',
['飝龙']='飝龙在天:BAAALgAECgkJCQAAAA==.',
['飞天']='飞天小猎手:BAAALgADCgcJBwAAAA==.',
['飞龙']='飞龙骑脸射击:BAAALgADCgMJAwAAAA==.',
['食蜂']='食蜂:BAACLgAFFH8HAAITAAMJ0xT9FAABAQATAAMJ0xT9FAABAQAuAAQKfyMAAhMACAkvGbkzAFMCABMACAkvGbkzAFMCAAAA.',
['饭饭']='饭饭的熊猫:BAAALgAECgIJAQAAAA==.',
['馒头']='馒头莫格莱尼:BAAALgAECgQJAwAAAA==.',
['香椰']='香椰拿铁:BAAALgADCgIJAgAAAA==.',
['香翅']='香翅佬饭:BAAALgAFFAIJBAAAAA==.',
['香菜']='香菜拿铁:BAABLgAFFH8GAAIRAAIJqR9fLAC9AAARAAIJqR9fLAC9AAAAAA==.',
['馬東']='馬東锡:BAAALgAECgUJBgABLgAFFAUJBgABADQdAA==.',
['马飞']='马飞瑞恩:BAAALgAECgYJBgAAAA==.',
['骑士']='骑士拽吗:BAAALgAECgUJBQAAAA==.',
['高德']='高德卵:BAAALgAECgkJCQAAAA==.',
['高洁']='高洁魔女:BAAALgAFFAIJAgAAAA==.',
['高育']='高育良:BAAALgAFFAIJBAAAAA==.',
['鬼冢']='鬼冢英吉:BAAALgAECgQJAwAAAA==.',
['鬼爷']='鬼爷爷:BAAALgAECgYJBwAAAA==.',
['魔兜']='魔兜兜:BAAALgAECgcJEQAAAA==.',
['魔幻']='魔幻橙影:BAAALgADCgEJAQABLgAECgEJAQAEAAAAAA==.',
['魔法']='魔法少女飞雪:BAAALgAECgMJAQAAAA==.',
['魔爷']='魔爷:BAAALgAECgYJBwAAAA==.',
['鱼人']='鱼人哀木涕:BAAALgADCgkJCQAAAA==.',
['鲁迪']='鲁迪:BAAALgAECgYJBgAAAA==.',
['鳯弓']='鳯弓羽凰:BAAALgAECgEJAQAAAA==.',
['鳯灬']='鳯灬凰:BAAALgAECgIJAgAAAA==.',
['鵺鸟']='鵺鸟:BAAALgAECgYJBgAAAA==.',
['鸟不']='鸟不懒惰:BAAALgAECgEJAQAAAA==.',
['鸡光']='鸡光毛血旺:BAABLgAFFH8HAAITAAMJxxKGDQD5AAATAAMJxxKGDQD5AAAAAA==.',
['鸡川']='鸡川富狼:BAAALgAECgUJAwAAAA==.',
['鸽子']='鸽子壹号丶:BAABLgAFFH8FAAIDAAUJgCFTAQAOAgADAAUJgCFTAQAOAgAAAA==.',
['鹤筆']='鹤筆翁:BAAALgAECgIJAgAAAA==.',
['麝香']='麝香葡萄:BAAALgAFFAQJBAABLgAFFAUJEgAHAK0iAA==.',
['麻辣']='麻辣九宫格:BAABLgAECn8cAAIHAAgJuQ72MgC5AQAHAAgJuQ72MgC5AQAAAA==.麻辣棒棒德:BAAALgAECgIJAgAAAA==.',
['黄發']='黄發財:BAAALgAECgYJCwABLgAFFAMJBwATANsJAA==.',
['黎明']='黎明嘚糖:BAAALgAECgUJBQAAAA==.',
['黑之']='黑之煞:BAAALgAECgcJDwAAAA==.',
['黑又']='黑又粗:BAABLgAECn8UAAMKAAcJqw47RgBfAQAKAAcJqw47RgBfAQATAAYJthN9HwBZAQAAAA==.',
['黑山']='黑山老妖:BAAALgAECgMJBwAAAA==.',
['黑暗']='黑暗升华:BAAALgAFFAIJAgAAAA==.黑暗料理:BAAALgAECgIJAgAAAA==.',
['黑椒']='黑椒厚切全熟:BAAALgAECgEJAQAAAA==.',
['黑漆']='黑漆漆的卡尔:BAAALgAECgkJBgAAAA==.黑漆漆的芝麻:BAAALgADCgYJBgAAAA==.',
['黑皮']='黑皮双马尾:BAAALgAFFAUJAQAAAA==.',
['黑鐹']='黑鐹我背:BAAALgAECgcJAQAAAA==.',
['黑锋']='黑锋:BAAALgAECgQJBQAAAA==.',
['黑鱼']='黑鱼桥小霸王:BAAALgAFFAEJAgAAAA==.',
['黑黑']='黑黑术:BAAALgAECgcJBQAAAA==.黑黑法:BAAALgADCgQJBAAAAA==.',
['龙乃']='龙乃潜藏:BAABLgAFFH8FAAIIAAUJmBqjAwB5AQAIAAUJmBqjAwB5AQAAAA==.',
['龙城']='龙城扫地僧:BAAALgAFFAEJAQAAAA==.',
['龙爸']='龙爸:BAAALgAECgYJBgAAAA==.',
['龙牡']='龙牡壮骨:BAAALgAECgkJEwAAAA==.',
['龙舞']='龙舞大魔王:BAAALgADCgMJAwAAAA==.',
['龙龙']='龙龙巫:BAAALgAFFAUJAgAAAA==.',
['龟古']='龟古神奇:BAAALgAECgMJAwAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
