local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Priest-Holy','Mage-Frost','Shaman-Elemental','Shaman-Enhancement','Shaman-Restoration','Rogue-Subtlety','DeathKnight-Unholy','DeathKnight-Blood','Unknown-Unknown','Paladin-Holy','Hunter-BeastMastery','Hunter-Marksmanship','Monk-Mistweaver','Monk-Windwalker','Druid-Restoration','DeathKnight-Frost','Warrior-Fury','Warrior-Protection','Warlock-Demonology','Priest-Shadow','Warlock-Destruction','Warlock-Affliction','Mage-Arcane','Evoker-Preservation','DemonHunter-Devourer','Warrior-Arms','Rogue-Outlaw','Monk-Brewmaster','Druid-Guardian','Druid-Balance','Paladin-Retribution','Paladin-Protection','Evoker-Augmentation','Mage-Fire','Priest-Discipline','DemonHunter-Havoc','Druid-Feral','Hunter-Survival','Evoker-Devastation',}
local provider = {region='CN',realm='遗忘海岸',name='CN',type='weekly',zone=46,date='2026-04-25',data={Ah='Ahang:BAAALgAECgEJAQAAAA==.',
Ai='Ailrini:BAAALgADCgYJBgAAAA==.',
Am='Amansur:BAAALgAECgkJAQABLgAFFAQJCgABAAQgAA==.',
As='Asheseight:BAAALgAFFAQJBAAAAA==.Ashesnine:BAAALgAFFAUJBAAAAA==.Ashesten:BAABLgAFFH8IAAICAAQJNiLbFgBuAQACAAQJNiLbFgBuAQAAAA==.',
Av='Avemujica:BAAALgAECgYJDAAAAA==.',
Az='Azaghal:BAACLgAFFH8TAAQDAAcJkyKNAQAIAgADAAUJ3SGNAQAIAgAEAAEJAAB0BgBUAAAFAAEJlwbbIgBIAAAuAAQKfxsAAwMACAn5IrYcACsCAAMABQlsJbYcACsCAAQABwnSGbsOANABAAAA.',
Ba='Backstreet:BAABLgAECn8ZAAIGAAgJVxzIAQBYAgAGAAgJVxzIAQBYAgAAAA==.Baker:BAABLgAFFH8FAAMHAAUJLBTYEwBTAQAHAAQJLBTYEwBTAQAIAAEJAADBGAA5AAAAAA==.',
Bi='Birdwizd:BAAALgAECgYJBgABLgAFFAEJAQAJAAAAAA==.Biscuit:BAAALgAFFAIJAgAAAA==.',
Bu='Bull:BAABLgAECn8YAAIKAAkJqB63GgA+AgAKAAkJqB63GgA+AgABLgAFFAUJAQAJAAAAAA==.',
Bz='Bzknight:BAAALgAECgMJBAAAAA==.',
Ch='Chilidruid:BAAALgAECgcJDgAAAA==.Chromy:BAAALgAECgYJBwAAAA==.',
Ci='Ciallo:BAAALgAECgMJBAAAAA==.',
Cj='Cjismine:BAABLgAFFH8GAAMLAAIJ1CMmHgBmAAAMAAEJMiXfIgBsAAALAAEJdiImHgBmAAAAAA==.',
De='Determined:BAABLgAECn8WAAICAAgJrCI+FQApAwACAAgJrCI+FQApAwABLgAFFAQJCgABAAQgAA==.',
Dk='Dka:BAAALgAECgYJCAABLgAFFAUJCwAHAIwTAA==.Dkplus:BAAALgAFFAIJBAABLgAFFAIJBQAGAJQLAA==.',
Dr='Drwan:BAEBLgAFFH8OAAMNAAQJ4ibuAgDUAQANAAQJ4ibuAgDUAQAOAAIJFQEdEQBPAAAAAA==.',
Ed='Edruid:BAAALgAFFAYJAwABLgAFFAYJEwAPAAcbAA==.Eduin:BAAALgADCgEJAQAAAA==.',
Eg='Egzz:BAAALgAECgQJBAAAAA==.',
El='Elidaray:BAAALgAECgUJBQAAAA==.Elsawspirit:BAAALgAECgYJBgAAAA==.',
Em='Emanon:BAACLgAFFH8VAAICAAYJjCJ0AQCaAgACAAYJjCJ0AQCaAgAuAAQKfxwAAgIACAkZJkQNAFsDAAIACAkZJkQNAFsDAAAA.',
Fl='Flamezz:BAAALgAECgQJBQAAAA==.Floors:BAAALgAFFAEJAgAAAA==.',
Fr='Franzzy:BAAALgAECgMJAwAAAA==.',
Fu='Fuera:BAAALgAECgcJBwAAAA==.',
Gd='Gdruid:BAAALgAFFAYJAwABLgAFFAYJEwAPAAcbAA==.Gdruidf:BAAALgAFFAQJBAAAAA==.',
Ge='Geloria:BAAALgAFFAEJAQAAAA==.',
Gh='Ghostmage:BAAALgADCgcJBgAAAA==.',
Gi='Giih:BAABLgAECn8jAAMIAAgJ5h8SCQCPAgAIAAgJ5h8SCQCPAgAQAAEJURqoCQBQAAAAAA==.',
Go='Gougua:BAAALgAECggJCAAAAA==.',
Gr='Gracek:BAAALgAECgcJBwAAAA==.Graymane:BAAALgAECgQJBQAAAA==.',
Gu='Gustavo:BAAALgAECgYJBgAAAA==.',
Ha='Hansir:BAAALgAECgUJBQAAAA==.Hatsuneåmiku:BAAALgAECgEJAQAAAA==.',
Hb='Hblue:BAAALgAFFAIJAgABLgAFFAQJBAAJAAAAAA==.',
Hd='Hdruid:BAABLgAFFH8FAAIPAAQJQRCfCgAxAQAPAAQJQRCfCgAxAQABLgAFFAYJEwAPAAcbAA==.',
He='Helluin:BAAALgAECgEJAQAAAA==.',
Id='Idruid:BAAALgAFFAUJBAABLgAFFAYJEwAPAAcbAA==.',
Jd='Jdruid:BAABLgAFFH8FAAIPAAUJShi7BQA9AQAPAAUJShi7BQA9AQABLgAFFAYJEwAPAAcbAA==.',
Ju='Juggler:BAACLgAFFH8NAAICAAQJsyQjDQCyAQACAAQJsyQjDQCyAQAuAAQKfyUAAgIACAktJhcJAH4DAAIACAktJhcJAH4DAAAA.',
Ka='Kan:BAABLgAECn8cAAIRAAcJ/hR+MgDiAQARAAcJ/hR+MgDiAQABLgAFFAUJCgASAHUSAA==.Kane:BAAALgAECgQJBQAAAA==.Kanyewst:BAAALgAECgEJAQAAAA==.',
Ki='Kirammi:BAAALgAECgEJAQAAAA==.',
Kn='Knocks:BAAALgAECgIJAwAAAA==.',
Kr='Krossy:BAAALgADCgkJCQAAAA==.',
Ku='Kullervo:BAAALgAFFAEJAQAAAA==.',
Le='Leftegger:BAAALgAECgEJAQAAAA==.Leseul:BAAALgAECgcJDgABLgAFFAQJCgABAAQgAA==.',
Lj='Ljbdb:BAAALgADCgIJAgAAAA==.',
Lu='Lumi:BAAALgAFFAEJAQAAAA==.Luthic:BAAALgAFFAYJAwAAAA==.',
Ma='Mambaout:BAAALgAECgIJAgAAAA==.Margiela:BAAALgAFFAEJAgAAAA==.',
Me='Meg:BAABLgAFFH8HAAIGAAMJOhaSBgAQAQAGAAMJOhaSBgAQAQAAAA==.Meowscaller:BAEBLgAFFH8GAAITAAQJOCMtCACkAQATAAQJOCMtCACkAQABLgAFFAUJFgACABElAA==.Metaverse:BAAALgAECgEJAQAAAA==.',
Mi='Mielsen:BAAALgAECgEJAQAAAA==.',
Ml='Mlgmdd:BAAALgAECgEJAgAAAA==.',
Mo='Modoko:BAABLgAFFH8FAAILAAMJtBTsEADBAAALAAMJtBTsEADBAAAAAA==.Moonchild:BAAALgAECgQJBAAAAA==.',
My='Mydkk:BAAALgADCgIJAgAAAA==.',
Nd='Ndruid:BAAALgAFFAUJBAABLgAFFAYJEwAPAAcbAA==.',
Ne='Nebulas:BAABLgAECn8fAAIUAAYJtR4JHgDpAQAUAAYJtR4JHgDpAQAAAA==.',
Ni='Nightrain:BAACLgAFFH8JAAMTAAQJvhWNEABdAQATAAQJwxSNEABdAQAVAAEJBxGAFABVAAAuAAQKfx4ABBMACAlIIOciAIkCABMABwlIIOciAIkCABUABQmPEy8eAF4BABYAAgkrG3UcAI8AAAAA.Nii:BAAALgAFFAIJAgAAAA==.Nimdok:BAAALgADCgMJAwAAAA==.',
Nl='Nlgger:BAAALgAECgIJAgABLgAECgYJHwAUALUeAA==.',
No='Notion:BAAALgAECgEJAQABLgAECgQJDAAJAAAAAA==.',
Nw='Nword:BAABLgAECn8cAAMCAAYJEyARZwAJAgACAAYJEyARZwAJAgAXAAEJkBb1GgBAAAABLgAECgYJHwAUALUeAA==.',
Od='Odruid:BAAALgAFFAUJAgABLgAFFAYJEwAPAAcbAA==.',
Oo='Ootman:BAAALgAFFAEJAQAAAA==.',
Or='Orian:BAAALgAECgUJBQAAAA==.',
Ot='Otae:BAAALgAFFAQJBAAAAA==.',
Pa='Pareo:BAABLgAFFH8IAAMTAAQJhA9/EwD7AAATAAMJWRJ/EwD7AAAVAAEJBQdjBwBSAAAAAA==.Parker:BAAALgAECgcJCAABLgAECgYJGAAYALwSAA==.',
Pl='Plaguerarr:BAABLgAFFH8GAAIHAAIJQx5ONQCzAAAHAAIJQx5ONQCzAAAAAA==.Playertpokvp:BAAALgAECgQJBAAAAA==.',
Qd='Qdruid:BAAALgAFFAUJBAABLgAFFAYJEwAPAAcbAA==.',
Ra='Ranzershaman:BAAALgAFFAMJBAAAAA==.',
Rd='Rdruid:BAABLgAFFH8FAAIPAAQJBQoNDQAVAQAPAAQJBQoNDQAVAQABLgAFFAYJEwAPAAcbAA==.',
Re='Re:BAAALgAECgYJBgAAAA==.',
Ru='Ruoyutt:BAACLgAFFH8MAAICAAQJ9iDoEQCHAQACAAQJ9iDoEQCHAQAuAAQKfyIAAgIACAl2I5USADgDAAIACAl2I5USADgDAAAA.',
Sa='Samage:BAAALgAECgMJBAAAAA==.',
Sd='Sdruid:BAAALgAFFAQJBAABLgAFFAYJEwAPAAcbAA==.',
Se='Select:BAAALgAECgEJAQAAAA==.Serviper:BAAALgAECgYJBgABLgAECgYJCQAJAAAAAA==.',
Sh='Shininglight:BAAALgAECgEJAQAAAA==.Shirayuki:BAAALgAECgEJAQAAAA==.Shoheiohtani:BAABLgAFFH8OAAIDAAQJZRqNAwBKAQADAAQJZRqNAwBKAQAAAA==.',
Si='Sicarius:BAAALgAECgUJBgAAAA==.',
Sk='Skyrocket:BAAALgAECgMJAwAAAA==.',
Sm='Smalloneal:BAAALgADCgcJCgAAAA==.Smallwade:BAAALgAECgcJDwAAAA==.Smcylx:BAAALgAFFAIJAwAAAA==.',
So='Somalhautdk:BAACLgAFFH8RAAMHAAQJSQcLHQAuAQAHAAQJSQcLHQAuAQAIAAEJXQFKGAA7AAAuAAQKfx8AAwcACAluHM4yAGwCAAcACAl7Gs4yAGwCAAgAAgk3G7U3AIUAAAAA.Souloy:BAAALgAECgIJAQAAAA==.Soulscream:BAABLgAFFH8GAAIZAAQJmRs9DQBnAQAZAAQJmRs9DQBnAQAAAA==.',
St='Statham:BAAALgAFFAEJAQAAAA==.',
Su='Supersama:BAAALgAECgEJAQAAAA==.',
Sw='Swarm:BAACLgAFFH8NAAMLAAUJfxhxCAAXAQAMAAUJfRXwDQBFAQALAAMJihlxCAAXAQAuAAQKfyQAAwwACAlcJHcFAEUDAAwACAlPJHcFAEUDAAsAAgkOIl9IAFkAAAAA.',
Td='Tdruid:BAAALgAFFAYJBAABLgAFFAYJEwAPAAcbAA==.',
Th='Thesix:BAAALgAECgIJAgAAAA==.Thicksnow:BAAALgAECgIJAgAAAA==.',
Ti='Timekeeper:BAABLgAECn8VAAILAAcJtA8vOQDKAQALAAcJtA8vOQDKAQAAAA==.',
Tr='Traxex:BAAALgAECgQJBQAAAA==.',
['Tí']='Tíamo:BAAALgAECgQJDAAAAA==.',
Vi='Viciou:BAAALgADCgUJCgABLgAFFAYJEAAHAC0hAA==.Viego:BAAALgADCgIJAgAAAA==.Vitmaru:BAAALgAECgYJCQAAAA==.',
Wa='Watermelon:BAAALgAECgkJCQAAAA==.',
We='Welsher:BAAALgAECgMJBAAAAA==.',
Wh='Whydunit:BAAALgAFFAEJAQABLgAFFAEJAQAJAAAAAA==.',
Wi='Winterzz:BAAALgADCgUJBQAAAA==.',
Wv='Wve:BAEALgAECgYJCgABLgAFFAQJDgANAOImAA==.',
Xe='Xeron:BAAALgAECgMJAwAAAA==.',
Ya='Yannefer:BAAALgAECgcJBwAAAA==.',
Yh='Yhzws:BAAALgAECgcJDQAAAA==.',
Yu='Yunan:BAAALgAECgYJBwAAAA==.',
Yz='Yzza:BAAALgAECgcJDAABLgAFFAQJDwARADAlAA==.Yzzh:BAACLgAFFH8PAAMRAAQJMCWxAACbAQARAAQJMCWxAACbAQAaAAMJgCOhAgA9AQAuAAQKfxkAAxoACAlXJCYCAAsDABEACAk0JKYFAE0DABoACAnzISYCAAsDAAAA.',
Zd='Zdruid:BAAALgAFFAQJBAABLgAFFAYJEwAPAAcbAA==.',
Zo='Zoeal:BAAALgAECgUJBgAAAA==.Zoes:BAAALgAECgEJAQAAAA==.',
['一丘']='一丘之貉:BAAALgADCgEJAQAAAA==.',
['一个']='一个人的路:BAAALgAECgYJCQAAAA==.',
['一些']='一些面包人:BAAALgAECgYJCQAAAA==.',
['一光']='一光北一:BAAALgAFFAEJAQAAAA==.',
['一刀']='一刀烈火丶:BAABLgAFFH8HAAMaAAcJKxcOAAA/AgAaAAYJKxcOAAA/AgARAAEJAABYFQAAAAAAAA==.',
['一只']='一只柴犬:BAABLgAECn8hAAMLAAkJ7h6qAwBWAwALAAkJ7h6qAwBWAwAMAAUJihMeUgAEAQAAAA==.',
['一呀']='一呀呀:BAACLgAFFH8RAAIbAAUJ1CIgAADqAQAbAAUJ1CIgAADqAQAuAAQKfyEAAhsACAmsJW0AAF0DABsACAmsJW0AAF0DAAAA.',
['一夕']='一夕明道:BAABLgAFFH8HAAINAAUJhBhIBgBlAQANAAUJhBhIBgBlAQAAAA==.',
['一年']='一年宅物:BAABLgAFFH8GAAIHAAQJyQbsHQAoAQAHAAQJyQbsHQAoAQAAAA==.',
['一德']='一德徳一:BAAALgADCgYJBgAAAA==.',
['一拳']='一拳撂倒丶:BAAALgAFFAQJBAAAAA==.',
['一本']='一本贯乳:BAAALgAFFAQJBAAAAA==.',
['一点']='一点小椰子:BAACLgAFFH8JAAIPAAUJVwuJCwAoAQAPAAUJVwuJCwAoAQAuAAQKfxcAAg8ACAmHF8wsAPsBAA8ACAmHF8wsAPsBAAAA.',
['一罪']='一罪明今:BAABLgAFFH8NAAINAAUJKR3AAQC4AQANAAUJKR3AAQC4AQAAAA==.',
['一股']='一股班味:BAAALgAECgEJAgAAAA==.',
['一表']='一表人才:BAAALgAFFAEJAQAAAA==.',
['一路']='一路小白:BAAALgAECgEJAQAAAA==.',
['一身']='一身仙女味:BAAALgAECggJDgAAAA==.',
['丁丁']='丁丁猫:BAABLgAECn8UAAINAAcJOBwjFQAfAgANAAcJOBwjFQAfAgAAAA==.',
['丁师']='丁师傅:BAAALgAECgQJBQABLgAFFAQJBgAcACscAA==.',
['七只']='七只卅漫:BAAALgAFFAQJBAABLgAFFAQJDAADABgmAA==.七只小鱼:BAAALgAECgIJAgAAAA==.',
['七夜']='七夜极胤:BAAALgAECgQJCAABLgAECgYJDgAJAAAAAA==.',
['七大']='七大棒:BAAALgAFFAQJBAAAAA==.',
['七对']='七对子之神:BAAALgAECgIJAgAAAA==.',
['七拳']='七拳撂倒丶:BAABLgAFFH8GAAMRAAYJkhhbCQBcAQARAAQJUhpbCQBcAQAaAAIJEhU1BQDDAAAAAA==.',
['七次']='七次小郎君:BAAALgADCgYJBgAAAA==.',
['万津']='万津莫:BAAALgAFFAEJAQAAAA==.',
['三刀']='三刀烈火丶:BAAALgAFFAQJBAAAAA==.',
['三年']='三年宅物:BAAALgAECgcJDQAAAA==.',
['三拳']='三拳撂倒丶:BAABLgAFFH8GAAIaAAYJ+RwzAADuAQAaAAYJ+RwzAADuAQAAAA==.',
['三日']='三日凌空:BAAALgAECgYJBgAAAA==.',
['三秋']='三秋:BAAALgAFFAIJAwAAAA==.',
['三笠']='三笠醬:BAAALgAECgYJBgAAAA==.',
['三聚']='三聚氰胺:BAAALgAECgMJBAAAAA==.',
['三途']='三途梦:BAAALgADCgIJAgAAAA==.',
['上訷']='上訷丶德:BAABLgAECn8UAAQdAAYJmQeKIgCIAAAeAAQJagYfZACQAAAdAAYJdgSKIgCIAAAPAAMJVAI8wABHAAAAAA==.',
['下班']='下班不做吗喽:BAAALgAECgEJAQAAAA==.',
['下雨']='下雨天不打伞:BAAALgAECgYJCQAAAA==.',
['不丨']='不丨语丶法:BAABLgAFFH8IAAICAAMJbyMhEQApAQACAAMJbyMhEQApAQAAAA==.',
['不会']='不会玩就会混:BAAALgAECgYJCQAAAA==.',
['不吃']='不吃盐须:BAAALgAECgEJAQAAAA==.',
['不得']='不得其名:BAABLgAFFH8EAAIZAAMJPCQCEQBGAQAZAAMJPCQCEQBGAQAAAA==.',
['不换']='不换药的猫猫:BAAALgADCgEJAQAAAA==.',
['不是']='不是爱慕涕:BAAALgAECgIJAgABLgAFFAMJBgAfANYhAA==.',
['不要']='不要叫我七七:BAABLgAECn8VAAMMAAYJFyN0LQDCAQAMAAYJDxt0LQDCAQALAAUJ/STuRQCZAQAAAA==.',
['不起']='不起眼的法妹:BAAALgAECgYJCQAAAA==.',
['世界']='世界第一舞娘:BAAALgAECgYJDgAAAA==.',
['东瘟']='东瘟疫大蛆:BAABLgAFFH8FAAIaAAMJHhrcAwDBAAAaAAMJHhrcAwDBAAAAAA==.',
['东皇']='东皇钟:BAABLgAECn8cAAICAAgJ4xdCfwDSAQACAAgJ4xdCfwDSAQAAAA==.',
['东风']='东风没铁龙:BAAALgAECgQJBQAAAA==.',
['丧钟']='丧钟之咒:BAAALgAECgEJAQAAAA==.',
['丨无']='丨无瓤西瓜丨:BAAALgADCgcJBwAAAA==.',
['丨爆']='丨爆丶燥丨:BAAALgAECgUJBQAAAA==.丨爆丶裂丨:BAAALgAFFAMJBAABLgAFFAYJFQAIAE4QAA==.',
['丨菜']='丨菜需捆丨:BAAALgAECgMJAwAAAA==.',
['丨萧']='丨萧瑟丨:BAAALgAECgYJBgAAAA==.',
['中指']='中指的寂寞:BAAALgAECgIJAgAAAA==.',
['丶半']='丶半山:BAAALgAECgkJAgAAAA==.',
['丶土']='丶土豆烧洋芋:BAAALgAECgQJBQAAAA==.',
['丶夜']='丶夜一:BAAALgADCgMJAwAAAA==.',
['丶奎']='丶奎尔丹尼:BAAALgAECgEJAQAAAA==.',
['丶打']='丶打小我就懵:BAAALgAECgUJBwAAAA==.',
['丶米']='丶米奈希尔:BAAALgAECgQJBAAAAA==.',
['丶若']='丶若彬丶:BAAALgAECgUJBQAAAA==.',
['丶蠢']='丶蠢蠢欲动:BAABLgAECn8UAAICAAYJMByBkQCwAQACAAYJMByBkQCwAQABLgAFFAMJBgAHADoXAA==.',
['丶铅']='丶铅笔丶:BAAALgADCgYJBwAAAA==.',
['丷凡']='丷凡尘:BAAALgAECgYJBgAAAA==.',
['丹德']='丹德莱恩:BAAALgAECgQJBwAAAA==.',
['丹青']='丹青画鹢:BAAALgAFFAEJAQAAAA==.',
['主将']='主将重现:BAABLgAECn8aAAMTAAcJJh7fRgD2AQATAAcJJh7fRgD2AQAVAAIJXBgaRQChAAAAAA==.',
['丿蠢']='丿蠢蠢欲动:BAABLgAFFH8GAAIHAAMJOheEJQAAAQAHAAMJOheEJQAAAQAAAA==.',
['乌云']='乌云覆雪:BAAALgAECgcJCAAAAA==.',
['乘风']='乘风归丶:BAABLgAECn8VAAILAAcJ2CLUFACQAgALAAcJ2CLUFACQAgAAAA==.',
['乙巳']='乙巳乙酉:BAAALgAFFAQJBAAAAA==.',
['九只']='九只卅漫:BAABLgAFFH8MAAIDAAQJGCY6AQCXAQADAAQJGCY6AQCXAQAAAA==.',
['九智']='九智保安:BAAALgAECgYJCQAAAA==.',
['二号']='二号野狗:BAAALgAECgIJBgAAAA==.',
['云观']='云观澜兮:BAAALgADCgcJBwAAAA==.',
['五年']='五年宅物:BAAALgAECgcJBQAAAA==.',
['五星']='五星沙首:BAAALgAFFAEJAQAAAA==.',
['五费']='五费欢笑姐夫:BAAALgAECgcJDAAAAA==.',
['五颜']='五颜六色的花:BAAALgAECgQJBAAAAA==.',
['些许']='些许邪能罢了:BAAALgADCgEJAQAAAA==.',
['人间']='人间客:BAAALgADCgYJBgAAAA==.',
['亿枪']='亿枪一个丶:BAAALgAFFAMJAwAAAA==.',
['什么']='什么小蛋糕:BAAALgAFFAEJAQAAAA==.',
['仗剑']='仗剑为誓言丶:BAABLgAFFH8MAAMfAAQJZxPWBgBBAQAfAAQJZxPWBgBBAQAgAAEJTQo2CAA1AAAAAA==.',
['伊人']='伊人丶红妆:BAABLgAECn8VAAMTAAkJ2CDVBgBTAwATAAkJ2CDVBgBTAwAVAAIJ1x57SgCOAAAAAA==.',
['伊利']='伊利牛奶蛋:BAAALgAECgEJAQAAAA==.伊利蛋挞:BAACLgAFFH8LAAIZAAQJ8CE6CwB9AQAZAAQJ8CE6CwB9AQAuAAQKfxoAAhkACAmzI3QCAKsCABkACAmzI3QCAKsCAAAA.',
['伊尔']='伊尔珊诗舞:BAABLgAECn8WAAICAAcJoxeGcgDuAQACAAcJoxeGcgDuAQAAAA==.',
['伊布']='伊布哒:BAAALgAECgYJBgAAAA==.',
['优秀']='优秀创客:BAABLgAFFH8FAAICAAUJ4BRQCQDVAQACAAUJ4BRQCQDVAQAAAA==.',
['会开']='会开英勇:BAAALgADCgcJBwAAAA==.',
['伸出']='伸出魔爪:BAAALgAECgMJAwAAAA==.',
['似水']='似水流年灬:BAAALgAECgMJAwAAAA==.',
['低保']='低保选冥殇:BAAALgAFFAEJAQAAAA==.',
['低调']='低调:BAAALgAECgYJCQAAAA==.低调丶:BAAALgAFFAIJAwAAAA==.低调做人:BAAALgAECgUJCQAAAA==.低调骑士:BAAALgAECgMJBAAAAA==.',
['低黑']='低黑高红:BAAALgAFFAIJAgAAAA==.',
['佑月']='佑月:BAAALgAECgMJAwAAAA==.',
['余生']='余生小死骑:BAAALgAECgMJAwAAAA==.',
['余笙']='余笙:BAAALgAECgcJCQAAAA==.',
['余苼']='余苼:BAAALgAECgMJAwAAAA==.',
['佛丁']='佛丁丨法火:BAAALgAECgYJBwAAAA==.',
['你也']='你也想起舞嗎:BAAALgAECgEJAQAAAA==.',
['你们']='你们输了:BAAALgAECgYJCwAAAA==.',
['你头']='你头发乱了哟:BAAALgAECgYJBgAAAA==.',
['你是']='你是个艺术家:BAAALgAECgEJAQAAAA==.',
['你说']='你说了那个字:BAAALgAECgUJCAAAAA==.',
['依然']='依然明月在:BAAALgAECgIJBQAAAA==.依然明月心:BAAALgADCgUJBQAAAA==.依然西楼明月:BAAALgAECgcJCAAAAA==.依然踏山花:BAAALgAECgEJAQAAAA==.',
['保佑']='保佑:BAAALgADCgUJBQAAAA==.',
['保安']='保安战神:BAAALgAECgIJAgAAAA==.保安队长丶:BAAALgAECgQJBQAAAA==.',
['信仰']='信仰的白羽:BAAALgADCgIJAwAAAA==.',
['俺上']='俺上山打老虎:BAABLgAECn8cAAIDAAcJXhBGMQCZAQADAAcJXhBGMQCZAQAAAA==.',
['俺是']='俺是哀木涕:BAAALgAECgYJBgAAAA==.',
['倆仪']='倆仪式:BAAALgAECgcJCwAAAA==.',
['倒地']='倒地耍原神:BAAALgADCgEJAQAAAA==.',
['候梨']='候梨蟹:BAAALgAECgEJAQAAAA==.',
['倪蓝']='倪蓝:BAAALgAECgcJAQAAAA==.',
['倪静']='倪静:BAAALgAECgQJBQAAAA==.',
['倾穹']='倾穹舞笑风尘:BAAALgAECgEJAQAAAA==.',
['偷偷']='偷偷摸一下:BAAALgAECgUJCAAAAA==.',
['元素']='元素之俏:BAAALgAECgMJAwAAAA==.',
['先天']='先天一炁:BAAALgAECgkJDgAAAA==.',
['光之']='光之回响:BAAALgAECgUJBQAAAA==.',
['光影']='光影的舞蹈家:BAAALgAECgEJAQAAAA==.',
['克星']='克星三号:BAAALgAFFAIJAgAAAA==.克星六号:BAABLgAFFH8GAAIHAAQJLgvDGwA1AQAHAAQJLgvDGwA1AQAAAA==.克星十一号:BAAALgAECgEJAQAAAA==.克星十五号:BAAALgAFFAMJAwAAAA==.克星十六号:BAAALgAFFAQJBAAAAA==.克星十号:BAAALgAECgEJAQAAAA==.',
['全能']='全能加三:BAAALgAFFAIJAwAAAA==.',
['八千']='八千代:BAAALgAFFAIJBAAAAA==.',
['八只']='八只卅漫:BAABLgAFFH8LAAIDAAQJ/CXGAgDKAQADAAQJ/CXGAgDKAQABLgAFFAQJDAADABgmAA==.',
['八幡']='八幡海鈴:BAAALgAFFAIJAgAAAA==.',
['八拳']='八拳撂倒丶:BAAALgAFFAUJBAAAAA==.',
['六只']='六只卅漫:BAABLgAFFH8IAAIDAAQJlCRqAwC2AQADAAQJlCRqAwC2AQABLgAFFAQJDAADABgmAA==.',
['六拳']='六拳撂倒丶:BAAALgAFFAUJAQAAAA==.',
['兰娜']='兰娜瑟尔:BAAALgAECgQJBQAAAA==.',
['兲青']='兲青色瞪眼鱼:BAAALgADCgEJAQAAAA==.',
['兵部']='兵部尚书:BAAALgADCgYJBgAAAA==.',
['内个']='内个老马:BAAALgAECgUJBQAAAA==.',
['册那']='册那队长:BAAALgAECgYJBgABLgAFFAQJDgAHAN0cAA==.',
['再会']='再会丷:BAAALgAECgIJAgAAAA==.',
['冠希']='冠希老师:BAAALgAECgIJAgAAAA==.',
['冬马']='冬马和纱:BAAALgAECgIJAwAAAA==.',
['冯雪']='冯雪娟:BAAALgAECgYJBgAAAA==.',
['冰与']='冰与光的龙诗:BAAALgAECgYJDgABLgAFFAgJFgAhAH0HAA==.',
['冰冰']='冰冰碎汪汪:BAAALgAECgEJAQAAAA==.',
['冰毛']='冰毛豆:BAAALgAECgYJBwAAAA==.',
['冰麻']='冰麻子:BAABLgAFFH8NAAIcAAUJkQ3YBgAlAQAcAAUJkQ3YBgAlAQAAAA==.',
['凊淨']='凊淨:BAAALgAECgYJDgAAAA==.',
['凌霜']='凌霜华:BAAALgAFFAEJAQAAAA==.',
['几分']='几分之几:BAAALgAECgkJBwAAAA==.',
['凤清']='凤清扬:BAABLgAECn8VAAQFAAcJHxLlOACeAQAFAAcJHxLlOACeAQADAAUJhwyfTwAIAQAEAAEJ/wOALgAsAAAAAA==.',
['凨丶']='凨丶叶:BAAALgAECgEJAQAAAA==.',
['凭空']='凭空圣光闪现:BAAALgAECgIJAgAAAA==.',
['凱尓']='凱尓萨斯:BAAALgAECgQJBAAAAA==.',
['击毙']='击毙麦克白:BAAALgAFFAEJAgAAAA==.',
['刘德']='刘德华佗在世:BAABLgAECn8WAAIKAAcJzBC6QwBpAQAKAAcJzBC6QwBpAQAAAA==.',
['初二']='初二丶:BAAALgAECgMJAwAAAA==.',
['初凉']='初凉情切切:BAAALgAECgEJAQAAAA==.',
['初桜']='初桜丨:BAAALgAECgUJBwAAAA==.',
['初见']='初见丨:BAAALgAECgQJBAAAAA==.',
['别冲']='别冲太猛:BAACLgAFFH8JAAIfAAMJHh8wCQAeAQAfAAMJHh8wCQAeAQAuAAQKfxsAAh8ACAnrIc8UAO0CAB8ACAnrIc8UAO0CAAAA.',
['别扒']='别扒拉我:BAAALgADCgEJAQAAAA==.',
['别逗']='别逗了:BAAALgAECgMJAwABLgAFFAcJCwAaAP0dAA==.',
['刺杀']='刺杀贼赫娜:BAAALgAECgUJBQAAAA==.',
['前天']='前天那个:BAABLgAECn8VAAMiAAgJkBf7AwC5AQAiAAgJBQ/7AwC5AQACAAcJ4xTPjgC1AQAAAA==.',
['剑与']='剑与圣光:BAAALgAECgEJAgAAAA==.',
['劣质']='劣质电:BAAALgAECgYJDwAAAA==.',
['劲仔']='劲仔小熊:BAAALgAECgYJEQAAAA==.',
['势如']='势如闪电:BAAALgADCgEJAQAAAA==.',
['勿忘']='勿忘:BAAALgAECgQJBAAAAA==.',
['化科']='化科:BAAALgAECgIJAQABLgAFFAMJBgAfANYhAA==.',
['北北']='北北丶:BAAALgAECgYJBgAAAA==.',
['十一']='十一只卅漫:BAABLgAFFH8MAAIDAAQJmiTHAAC4AQADAAQJmiTHAAC4AQABLgAFFAQJDAADABgmAA==.',
['十七']='十七度雨:BAAALgAECgMJAwAAAA==.',
['十二']='十二只萨满:BAABLgAFFH8IAAIDAAQJeSMLBACnAQADAAQJeSMLBACnAQABLgAFFAQJDAADABgmAA==.',
['十只']='十只卅漫:BAABLgAFFH8LAAIDAAQJiSaVAgDRAQADAAQJiSaVAgDRAQABLgAFFAQJDAADABgmAA==.',
['十字']='十字军之心:BAAALgAECgcJBwAAAA==.',
['千八']='千八十烦恼凤:BAABLgAFFH8FAAIPAAIJLw9hEACNAAAPAAIJLw9hEACNAAAAAA==.',
['千叶']='千叶影儿:BAAALgAFFAIJBAAAAA==.',
['千早']='千早爱音丶:BAAALgAFFAIJAwAAAA==.',
['半半']='半半:BAAALgAECgkJDgAAAA==.',
['半枫']='半枫荷丶:BAAALgAECgEJAQAAAA==.',
['南宮']='南宮恨:BAAALgAECgMJBAAAAA==.南宮殇:BAAALgAFFAQJBAAAAA==.南宮熵:BAAALgAECgEJAQAAAA==.',
['南风']='南风丶:BAAALgAECgQJBgAAAA==.',
['卡卡']='卡卡有力气:BAAALgADCgEJAQAAAA==.卡卡羅特:BAAALgADCgEJAQAAAA==.',
['卡提']='卡提希娅:BAAALgAECgcJEwAAAA==.',
['卡米']='卡米卡米:BAAALgAFFAIJAwAAAA==.',
['卡雷']='卡雷什通缉犯:BAAALgADCgcJDgAAAA==.',
['厉送']='厉送摆:BAAALgAFFAQJBAAAAA==.',
['双手']='双手指天:BAABLgAFFH8FAAIHAAIJ9B7PPACkAAAHAAIJ9B7PPACkAAAAAA==.',
['双魚']='双魚理:BAAALgAFFAUJBAABLgAFFAYJCwACAMUbAA==.',
['发光']='发光乌萨奇:BAAALgADCgUJBQAAAA==.',
['发财']='发财丶:BAAALgAECgkJCgAAAA==.',
['取牛']='取牛奶:BAAALgAECgEJAQAAAA==.',
['古他']='古他喵黑暗神:BAAALgAFFAIJAgAAAA==.',
['古兰']='古兰修:BAAALgAFFAIJAgAAAA==.',
['古冰']='古冰:BAAALgADCgMJAwAAAA==.',
['叫我']='叫我小伙就行:BAABLgAECn8YAAMVAAgJQSSQCwAIAgAVAAUJiSSQCwAIAgATAAQJRCQxaACTAQAAAA==.',
['可乐']='可乐加冰:BAABLgAFFH8GAAMcAAQJKxxABgBwAQAcAAQJKxxABgBwAQANAAEJcxVVFgBIAAAAAA==.',
['可坦']='可坦可奶可打:BAAALgAECgUJBgAAAA==.',
['可苦']='可苦可乐:BAAALgAECgUJDAAAAA==.',
['台阶']='台阶壮:BAAALgADCgUJBQAAAA==.',
['史克']='史克莱姆:BAAALgADCgEJAQAAAA==.',
['叶落']='叶落初雪:BAABLgAFFH8FAAIGAAIJlAsdDAChAAAGAAIJlAsdDAChAAAAAA==.',
['吃一']='吃一个大芒果:BAAALgAFFAIJBAAAAA==.',
['吃梨']='吃梨:BAAALgAECgEJAQAAAA==.',
['君蹈']='君蹈危:BAAALgAECgYJAgAAAA==.',
['吟荡']='吟荡丶:BAAALgAECgEJAQAAAA==.',
['吧唧']='吧唧浪:BAAALgADCgEJAQAAAA==.',
['听我']='听我指挥:BAAALgAECggJAwAAAA==.',
['听香']='听香小谢:BAAALgAECgYJBwAAAA==.',
['吸取']='吸取灵魂:BAAALgAECgEJAQAAAA==.',
['呆瓜']='呆瓜猴子:BAAALgADCgEJAgAAAA==.',
['呱呱']='呱呱牛牛:BAAALgAECgMJAwAAAA==.',
['和安']='和安:BAAALgAECgUJBQAAAA==.',
['和栗']='和栗薰子:BAABLgAFFH8PAAMTAAUJYyPgBQDCAQATAAUJYyPgBQDCAQAVAAEJjAG9GgBDAAAAAA==.',
['咑个']='咑个响指:BAAALgADCgYJBgAAAA==.',
['咔嚓']='咔嚓:BAAALgADCgYJBgAAAA==.',
['咕咕']='咕咕仔:BAAALgAECgYJBgAAAA==.咕咕嘎噶:BAAALgAECgQJDAAAAA==.',
['咖啡']='咖啡女:BAAALgAECgYJBgAAAA==.',
['哇咔']='哇咔咔咯蹦:BAABLgAFFH8FAAIhAAMJzAokFADYAAAhAAMJzAokFADYAAAAAA==.',
['哇塞']='哇塞侠:BAAALgADCgEJAQAAAA==.',
['哈基']='哈基米曼波儿:BAAALgADCgIJAgAAAA==.',
['哎呀']='哎呀小小见:BAABLgAFFH8LAAQSAAUJbRBlBAA4AQASAAUJcgllBAA4AQAaAAEJGBGMCwBUAAARAAQJbA55EwBPAAAAAA==.',
['哎幽']='哎幽微:BAAALgADCgUJBQAAAA==.',
['哑巴']='哑巴的不语:BAABLgAFFH8IAAMOAAQJxRfSAQBPAQAOAAQJchPSAQBPAQAcAAQJwRGrCwAoAQAAAA==.',
['哔哔']='哔哔叽哇:BAAALgAFFAIJAgAAAA==.',
['哔哩']='哔哩哔哩:BAAALgAECgMJAwAAAA==.',
['哟丶']='哟丶訷貓:BAAALgAECgYJEwAAAA==.',
['哦马']='哦马自立曼波:BAAALgAECgIJAwAAAA==.',
['唐方']='唐方一战:BAAALgAECgYJBgAAAA==.',
['啄木']='啄木鸟:BAABLgAFFH8IAAIjAAYJBiI8AgD/AQAjAAYJBiI8AgD/AQAAAA==.',
['啊尔']='啊尔瑟斯:BAAALgAECgUJBQAAAA==.',
['啊菜']='啊菜:BAAALgAECgMJAwAAAA==.',
['喵了']='喵了个咪的啊:BAAALgAECgcJBgAAAA==.',
['喵呜']='喵呜咕咕哒:BAABLgAECn8ZAAIPAAgJAg55TAByAQAPAAgJAg55TAByAQAAAA==.',
['喵尔']='喵尔摩斯彡彡:BAABLgAFFH8FAAIFAAIJgiaCEADkAAAFAAIJgiaCEADkAAAAAA==.',
['喵蛙']='喵蛙:BAAALgAECgcJCAAAAA==.',
['嘉言']='嘉言不加糖:BAAALgAECgEJAQAAAA==.嘉言配可乐:BAAALgAECgEJAQAAAA==.',
['嘉贝']='嘉贝莉娜:BAABLgAFFH8MAAMZAAQJMBdVBwBJAQAZAAQJMBdVBwBJAQAkAAEJ+hFWDQBRAAAAAA==.',
['嘟督']='嘟督:BAAALgAECgEJAQAAAA==.',
['嘿嘿']='嘿嘿奶茶来咯:BAACLgAFFH8LAAINAAUJpxI/AwB0AQANAAUJpxI/AwB0AQAuAAQKfxUAAg0ABwm+IiQKALECAA0ABwm+IiQKALECAAEuAAUUBQkNAA0AKR0A.',
['噩魔']='噩魔人:BAAALgAECgkJCQAAAA==.',
['噬神']='噬神灭神:BAAALgAECgEJAQAAAA==.',
['四处']='四处逛逛:BAAALgADCgEJAQAAAA==.',
['四季']='四季骑士:BAAALgAECgUJBgAAAA==.',
['四费']='四费抗压龟:BAACLgAFFH8KAAICAAQJVAdaEQAnAQACAAQJVAdaEQAnAQAuAAQKfxsAAgIACAmaFHZiABUCAAIACAmaFHZiABUCAAAA.',
['土灵']='土灵小萨满:BAAALgADCgEJAQAAAA==.',
['圣主']='圣主丶:BAAALgAECgMJAwABLgAFFAYJDgAkACcTAA==.',
['圣光']='圣光一族:BAAALgAECgQJBAAAAA==.圣光三袞三袞:BAAALgAECgkJCQAAAA==.圣光光丶:BAABLgAFFH8KAAMBAAQJBCA9BQAxAQABAAMJ8SI9BQAxAQAjAAEJPRcpDgBVAAAAAA==.圣光粽子:BAAALgAECgcJEwAAAA==.圣光青果:BAACLgAFFH8IAAIKAAIJfBiNEwCnAAAKAAIJfBiNEwCnAAAuAAQKfxoAAgoACAkCGTUYAFACAAoACAkCGTUYAFACAAAA.',
['圣吉']='圣吉列斯:BAACLgAFFH8JAAMfAAQJ6xQpCwBTAQAfAAQJ8xMpCwBTAQAgAAMJJA7KAQDAAAAuAAQKfxUAAyAABwnlE5UXAFsBACAABwlhEpUXAFsBAB8AAQnCFL8xAUAAAAAA.',
['在下']='在下龙傲天:BAAALgAECgIJAQABLgAECgcJDAAJAAAAAA==.',
['坏人']='坏人艾瑞巴斯:BAAALgAFFAEJAQAAAA==.',
['坏尔']='坏尔萨斯:BAAALgAFFAIJBAAAAA==.',
['埃涅']='埃涅阿斯:BAAALgAECgQJBgAAAA==.',
['城门']='城门上晒腊肉:BAAALgADCgEJAQAAAA==.',
['埘亓']='埘亓:BAAALgAECgcJBQAAAA==.',
['堕落']='堕落丶肥肥:BAAALgAECgEJAQAAAA==.堕落丶辣汤:BAACLgAFFH8CAAITAAIJlwp5IQCkAAATAAIJlwp5IQCkAAAuAAQKfxEAAxUABwk0HuExAPEAABMABAnGHfWUAC8BABUAAwkOH+ExAPEAAAAA.',
['塔纳']='塔纳利斯:BAAALgAECgUJBQAAAA==.',
['墨小']='墨小菊:BAAALgADCgQJBAAAAA==.',
['墨淼']='墨淼:BAAALgADCgIJAgAAAA==.',
['夏之']='夏之枫:BAAALgADCgYJDgAAAA==.',
['夏侯']='夏侯迈轩:BAABLgAECn8VAAMFAAYJJCKUGgBEAgAFAAYJJCKUGgBEAgADAAEJGgmXMgAvAAAAAA==.',
['夏多']='夏多雷:BAAALgAECgYJEQAAAA==.',
['夏川']='夏川:BAABLgAFFH8HAAMTAAMJ1yJ1JgDlAAATAAIJtiZ1JgDlAAAWAAEJGBvlAwBdAAAAAA==.',
['夕之']='夕之夜:BAAALgAECgYJCAAAAA==.',
['多喝']='多喝水:BAAALgADCgUJBQAAAA==.多喝水丨:BAAALgADCgUJBQAAAA==.',
['多情']='多情妖僧:BAAALgAFFAQJBAAAAA==.',
['夜刖']='夜刖:BAACLgAFFH8OAAIGAAQJuhR9CQBZAQAGAAQJuhR9CQBZAQAuAAQKfycAAgYACAkbG0cPAK8CAAYACAkbG0cPAK8CAAAA.',
['夜夜']='夜夜酱:BAAALgAECgUJBgAAAA==.夜夜飘雪:BAACLgAFFH8MAAMBAAUJPCBhAADXAQABAAUJJRthAADXAQAjAAQJQBCLCgA2AQAuAAQKfxkAAwEACAkGH1ELAJsCAAEACAlaHlELAJsCACMAAwm1HT41APoAAAAA.',
['夜弦']='夜弦:BAABLgAFFH8GAAIZAAQJEx4UDAB0AQAZAAQJEx4UDAB0AQAAAA==.',
['夜班']='夜班车:BAAALgADCgEJAQAAAA==.',
['夜空']='夜空之虹:BAAALgAECgYJBAABLgAFFAEJAQAJAAAAAA==.',
['夜羽']='夜羽之殇:BAAALgADCgEJAQAAAA==.',
['夜阑']='夜阑听雪:BAAALgAECgcJCAAAAA==.',
['夢不']='夢不覺:BAAALgAECgYJCQAAAA==.',
['大丶']='大丶大丶姐丶:BAAALgADCgcJDQAAAA==.',
['大吃']='大吃一斤:BAAALgAECgIJAgAAAA==.',
['大喜']='大喜:BAAALgAECgcJAgAAAA==.',
['大宗']='大宗师希林:BAAALgAFFAIJAgAAAA==.',
['大笨']='大笨钟:BAABLgAFFH8VAAIUAAYJHB4aAQAyAgAUAAYJHB4aAQAyAgAAAA==.',
['大胖']='大胖橘:BAAALgAECgYJDAAAAA==.',
['大花']='大花:BAAALgADCgcJBwAAAA==.',
['大蛋']='大蛋蛋:BAAALgAECgUJCAAAAA==.',
['大跳']='大跳飞狮:BAAALgAECgEJAQAAAA==.',
['天佑']='天佑发发:BAAALgAECgEJAQAAAA==.',
['天使']='天使日:BAAALgAECgYJDAAAAA==.',
['天海']='天海天兔:BAAALgAECgEJAQAAAA==.',
['天火']='天火焚曦:BAAALgAECgEJAQAAAA==.',
['天灾']='天灾酋长:BAABLgAECn8WAAIHAAcJbSGLJwCdAgAHAAcJbSGLJwCdAgAAAA==.',
['天霆']='天霆号:BAAALgAFFAIJAwAAAA==.',
['天风']='天风寄影:BAACLgAFFH8IAAINAAUJIRh3AgCSAQANAAUJIRh3AgCSAQAuAAQKfxgAAg0ABgnLH1YYAP0BAA0ABgnLH1YYAP0BAAAA.',
['太库']='太库辣:BAAALgADCgEJAQAAAA==.',
['失衡']='失衡:BAACLgAFFH8IAAIGAAQJOCZqAwDEAQAGAAQJOCZqAwDEAQAuAAQKfx0AAgYACAnGJd0CAHcDAAYACAnGJd0CAHcDAAAA.失衡丶:BAABLgAFFH8IAAIfAAQJJh7MAQCMAQAfAAQJJh7MAQCMAQABLgAFFAQJCAAGADgmAA==.',
['头上']='头上没妙脆角:BAAALgAECgMJBQABLgAFFAQJDAATAEAlAA==.',
['夺魄']='夺魄:BAAALgAECgQJBAAAAA==.',
['奈何']='奈何一谒:BAACLgAFFH8LAAINAAUJ0BvqAgDVAQANAAUJ0BvqAgDVAQAuAAQKfxYAAg0ACQmyIlsBAJMDAA0ACQmyIlsBAJMDAAEuAAUUBQkNAA0AKR0A.奈何二心:BAABLgAFFH8KAAINAAQJUB/mBQBxAQANAAQJUB/mBQBxAQABLgAFFAUJDQANACkdAA==.',
['奈川']='奈川零号机:BAAALgAECgEJAQAAAA==.',
['奈斐']='奈斐天:BAAALgAECgIJAgAAAA==.',
['奈非']='奈非天二:BAAALgAECgYJEgAAAA==.',
['奥德']='奥德彪夫人:BAAALgADCgUJBwAAAA==.',
['奥森']='奥森喜羊羊:BAAALgADCgUJBQAAAA==.',
['奶茶']='奶茶少爷:BAAALgAECgEJAQAAAA==.',
['她只']='她只是不恨我:BAACLgAFFH8KAAIGAAQJSBqABgB4AQAGAAQJSBqABgB4AQAuAAQKfyYAAgYACAkNJSIDAG8DAAYACAkNJSIDAG8DAAAA.她只是不理我:BAAALgADCgcJCAAAAA==.',
['好女']='好女孩:BAABLgAECn8UAAIYAAYJvxklGQDGAQAYAAYJvxklGQDGAQABLgAFFAQJDgAjAAcUAA==.',
['如心']='如心:BAAALgADCgYJCAAAAA==.',
['如昨']='如昨:BAAALgAFFAIJBAAAAA==.',
['如歌']='如歌:BAAALgAECgcJBwAAAA==.',
['如风']='如风逐影:BAAALgADCgEJAQAAAA==.',
['妄为']='妄为丶:BAABLgAFFH8JAAICAAMJGCQODwA+AQACAAMJGCQODwA+AQAAAA==.',
['妖姬']='妖姬莉迪婭:BAAALgAECgIJAgAAAA==.',
['子时']='子时丶:BAACLgAFFH8SAAMTAAYJix5JAQA3AgATAAYJix5JAQA3AgAVAAIJIRIuDACqAAAuAAQKfx8ABBMACQlwIQEDAJIDABMACQlwIQEDAJIDABYAAQkAAIYgAHAAABUAAQkAAG5iAEkAAAAA.',
['子虚']='子虚:BAAALgAECgYJBgAAAA==.',
['存牛']='存牛奶:BAAALgAECgMJAwAAAA==.',
['季风']='季风行渡者:BAAALgADCgEJAQAAAA==.',
['孤人']='孤人自嘲鼁:BAAALgAECgMJAwAAAA==.',
['孤渡']='孤渡:BAAALgAECgcJDwAAAA==.',
['学会']='学会放弃:BAAALgAECgYJCQAAAA==.',
['宇佐']='宇佐美春:BAAALgADCgMJAwAAAA==.',
['宇宙']='宇宙萨:BAAALgAECgYJCAAAAA==.',
['安欧']='安欧维恩丶:BAAALgAECgYJBwAAAA==.',
['宝宝']='宝宝发如雪:BAAALgADCgUJBgAAAA==.',
['寂夜']='寂夜挽歌:BAACLgAFFH8JAAIUAAQJKgkIBAAsAQAUAAQJKgkIBAAsAQAuAAQKfxwAAhQABwlGIfkMALQCABQABwlGIfkMALQCAAAA.',
['寂寞']='寂寞来袭:BAABLgAFFH8FAAITAAQJ9Qq1FwAyAQATAAQJ9Qq1FwAyAQAAAA==.',
['寒烁']='寒烁:BAAALgAECgQJBAABLgAECgYJBgAJAAAAAA==.',
['对健']='对健康不好喔:BAAALgAECgMJAQAAAA==.',
['对唔']='对唔嗨住:BAAALgAECgkJCQAAAA==.',
['尊嘟']='尊嘟假嘟:BAAALgAECgEJAgAAAA==.',
['小冷']='小冷多吃点:BAAALgAFFAQJBAABLgAFFAQJCgABAAQgAA==.小冷少熬夜:BAABLgAFFH8GAAIBAAMJLx9rAwAZAQABAAMJLx9rAwAZAQABLgAFFAQJCgABAAQgAA==.',
['小别']='小别兔别又别:BAAALgAFFAQJBAAAAA==.',
['小咪']='小咪:BAAALgAFFAIJAgAAAA==.',
['小学']='小学财:BAAALgAECgIJAgAAAA==.',
['小小']='小小牛奶:BAAALgAFFAEJAQAAAA==.小小花:BAACLgAFFH8PAAMUAAQJVReHAwA6AQAUAAQJVReHAwA6AQAjAAEJ1QUxGwBCAAAuAAQKfyIABBQACAlOIh4HABgDABQACAlOIh4HABgDAAEABQlvF682AGIBACMAAQk5GRRRAEgAAAAA.',
['小心']='小心点:BAAALgAECgYJCgAAAA==.',
['小手']='小手氷凉:BAAALgAECgMJAwAAAA==.',
['小木']='小木曾雪菜:BAAALgAECgcJDgAAAA==.',
['小欣']='小欣欣:BAABLgAECn8UAAICAAcJrxpTYwATAgACAAcJrxpTYwATAgAAAA==.',
['小河']='小河虾米:BAAALgAFFAEJAQAAAA==.',
['小火']='小火兔:BAAALgAECgYJDAAAAA==.',
['小熊']='小熊爪:BAACLgAFFH8IAAIKAAUJ5iXFAAAvAgAKAAUJ5iXFAAAvAgAuAAQKfxwAAwoABwlJJWQJANsCAAoABwlJJWQJANsCAB8AAwndGVfTAOQAAAAA.',
['小牛']='小牛奶:BAAALgAECgMJAwAAAA==.',
['小砖']='小砖头:BAABLgAFFH8MAAITAAUJQR2eEABcAQATAAUJQR2eEABcAQABLgAFFAgJCQAVAC0aAA==.',
['小脆']='小脆糕丶:BAACLgAFFH8JAAIPAAMJuhkjDwD1AAAPAAMJuhkjDwD1AAAuAAQKfxUAAg8ACQkcHOAJAPYCAA8ACQkcHOAJAPYCAAEuAAUUBQkGAA8AEhMA.',
['小花']='小花糕丶:BAABLgAFFH8GAAIPAAUJEhNmAwB8AQAPAAUJEhNmAwB8AQAAAA==.',
['小行']='小行家:BAABLgAFFH8JAAILAAQJWiJRAQCTAQALAAQJWiJRAQCTAQAAAA==.',
['小豆']='小豆泽心羽:BAAALgAECgYJBgAAAA==.',
['小郡']='小郡肝打乱拳:BAAALgAECgYJCAAAAA==.',
['小阿']='小阿發:BAAALgADCgcJBwAAAA==.',
['小雪']='小雪转晴:BAAALgAECgkJCQAAAA==.',
['小飞']='小飞棘来喽:BAAALgAFFAIJAwABLgAFFAMJBQAFAFUSAA==.',
['小黄']='小黄鬼:BAAALgAECgMJAwAAAA==.',
['小龙']='小龙套财:BAAALgAECgYJDAAAAA==.',
['少爺']='少爺:BAAALgADCgEJAQAAAA==.',
['就是']='就是看得远:BAAALgADCgEJAQAAAA==.',
['尼德']='尼德丶霍格:BAAALgADCgIJAgAAAA==.',
['属实']='属实可乐:BAAALgAECgMJAwAAAA==.',
['山丘']='山丘的雪见樱:BAAALgAECgEJAQAAAA==.',
['山竹']='山竹泡茶:BAAALgAECgYJBgABLgAECgYJFQABALkeAA==.',
['山茶']='山茶:BAAALgAECgUJBgAAAA==.',
['山远']='山远水阔:BAACLgAFFH8IAAIIAAMJ+RSjCgDVAAAIAAMJ+RSjCgDVAAAuAAQKfxsAAwgACAldHE4KAHUCAAgACAlZHE4KAHUCABAABQmTGugKABcBAAAA.',
['岛田']='岛田推车家族:BAABLgAECn8cAAICAAgJ6h2wIQDtAgACAAgJ6h2wIQDtAgAAAA==.',
['岩怒']='岩怒:BAAALgAECgYJBgAAAA==.',
['崔夕']='崔夕斯:BAAALgAECgEJAgAAAA==.',
['巨角']='巨角冲撞:BAAALgAECgEJAQAAAA==.',
['巴巴']='巴巴博弈:BAAALgAFFAQJBAAAAA==.',
['帅瓜']='帅瓜瓜:BAAALgAECgEJAQAAAA==.',
['带带']='带带小汤姆:BAAALgADCgEJAQAAAA==.',
['幕夜']='幕夜星河:BAAALgAECgYJDAAAAA==.',
['平生']='平生意:BAAALgADCgcJBwAAAA==.',
['平静']='平静的阿昆达:BAAALgAECgEJAQAAAA==.',
['幺陆']='幺陆璠石榴:BAAALgAFFAMJAwAAAA==.',
['幺鸡']='幺鸡丶:BAAALgAECgcJEgAAAA==.',
['幽莹']='幽莹:BAABLgAECn8bAAIPAAcJWxxbIABAAgAPAAcJWxxbIABAAgAAAA==.',
['库小']='库小酷:BAAALgADCgQJBAAAAA==.',
['应易']='应易:BAAALgAECgcJAQAAAA==.',
['废人']='废人告白:BAAALgAECgEJAQABLgAECgYJDgAJAAAAAA==.',
['开一']='开一局吗:BAAALgAECgMJAwAAAA==.',
['张先']='张先森:BAAALgAECgkJCQAAAA==.',
['弦化']='弦化喵喵:BAAALgAFFAEJAQAAAA==.',
['彩虹']='彩虹小鸟鸭:BAABLgAECn8XAAQPAAcJZhPuQwCSAQAPAAYJZRbuQwCSAQAeAAUJ4gURWADDAAAlAAEJDg5wMgA3AAAAAA==.',
['影矢']='影矢:BAABLgAECn8ZAAILAAkJHRlYEAC3AgALAAkJHRlYEAC3AgAAAA==.',
['徐小']='徐小杰:BAAALgAECgIJAgAAAA==.',
['御坂']='御坂丨美琴:BAABLgAFFH8FAAIFAAIJvR0+FAC5AAAFAAIJvR0+FAC5AAAAAA==.',
['御清']='御清绝:BAABLgAFFH8IAAINAAUJ4hgSAgClAQANAAUJ4hgSAgClAQAAAA==.',
['微风']='微风凝羽:BAAALgAECgQJBQAAAA==.',
['德帝']='德帝一:BAAALgAECgQJBAAAAA==.',
['德彪']='德彪西风斜阳:BAAALgADCgMJAwAAAA==.',
['德玛']='德玛西亚凡飞:BAAALgAECgUJBQAAAA==.',
['德财']='德财兼倍:BAAALgAECgUJDQAAAA==.',
['心婷']='心婷:BAAALgAECgcJBwAAAA==.',
['心灵']='心灵冰冻:BAAALgAECgQJBQAAAA==.',
['心若']='心若止水丶:BAABLgAECn8bAAICAAcJAyZpIgDpAgACAAcJAyZpIgDpAgAAAA==.',
['忆暖']='忆暖丶:BAAALgAECgkJAQAAAA==.',
['忆轩']='忆轩:BAABLgAFFH8FAAIfAAMJygVqGQDcAAAfAAMJygVqGQDcAAAAAA==.',
['忧郁']='忧郁美男球:BAAALgADCgYJBgAAAA==.',
['快进']='快进我棉被:BAABLgAFFH8HAAIfAAYJYxQHAQCrAQAfAAYJYxQHAQCrAQAAAA==.',
['怎么']='怎么那么萌:BAAALgAECgQJBwAAAA==.',
['总攻']='总攻达人:BAAALgADCgUJBQAAAA==.',
['恐怖']='恐怖钕主角:BAAALgAECgcJEgAAAA==.',
['恩培']='恩培多克勒:BAAALgAFFAMJBAAAAA==.',
['恶魔']='恶魔菠刚:BAACLgAFFH8PAAMZAAUJlAVkEgA9AQAZAAUJjANkEgA9AQAkAAMJTQaCBgDkAAAuAAQKfxQAAyQACAmYGTodANYBACQABwmMGzodANYBABkABwknGAlLAMgBAAAA.',
['悠哉']='悠哉德:BAAALgAFFAEJAQAAAA==.',
['悠悠']='悠悠大魔王:BAAALgAFFAQJBAAAAA==.',
['惊风']='惊风夜引:BAAALgAECgYJBgAAAA==.',
['惟君']='惟君为英雄:BAACLgAFFH8GAAIKAAMJbhlRDgDyAAAKAAMJbhlRDgDyAAAuAAQKfxUAAgoABwlzHcUsANIBAAoABwlzHcUsANIBAAAA.',
['惟心']='惟心凭罪:BAABLgAFFH8LAAINAAQJ0RXFBgBXAQANAAQJ0RXFBgBXAQABLgAFFAUJDQANACkdAA==.',
['想吃']='想吃雪花:BAAALgAECgIJAgAAAA==.',
['惹毛']='惹毛会变绒绒:BAACLgAFFH8PAAIPAAQJ5iZaAQDWAQAPAAQJ5iZaAQDWAQAuAAQKfyUAAw8ACAl3JggIAAwDAA8ACAl3JggIAAwDAB0ABglGIDYNALMBAAAA.',
['愚蠢']='愚蠢的绵羊:BAAALgAECgEJAQAAAA==.',
['愤怒']='愤怒的瓶盖:BAAALgAECgEJAQAAAA==.',
['慈兜']='慈兜兜:BAAALgAECgIJAQAAAA==.',
['懒懒']='懒懒拉:BAABLgAFFH8HAAIHAAMJHBQ2FwDfAAAHAAMJHBQ2FwDfAAAAAA==.',
['懵懂']='懵懂的小狐狸:BAAALgADCgcJCAAAAA==.',
['戈德']='戈德隆:BAAALgADCgEJAQAAAA==.',
['戌寅']='戌寅午:BAAALgADCgMJAwAAAA==.',
['我上']='我上山打老虎:BAAALgAECgMJAwAAAA==.',
['我不']='我不喜欢吃鱼:BAAALgAECgcJBwAAAA==.我不是瓜皮王:BAAALgAFFAQJAgAAAA==.',
['我两']='我两眼一黑啦:BAAALgAECgYJBgAAAA==.',
['我真']='我真没招了:BAABLgAFFH8QAAMSAAQJHRC7AwAFAQASAAQJ8Qm7AwAFAQARAAEJGSIRHgBhAAAAAA==.',
['我蛋']='我蛋蛋复活了:BAAALgAECgYJBwAAAA==.',
['戴三']='戴三刀:BAAALgADCgEJAQAAAA==.',
['托比']='托比欧电话铃:BAAALgAECgIJAgAAAA==.',
['托泥']='托泥屎瑞克:BAAALgAECgYJBgAAAA==.',
['托雷']='托雷克铁眉:BAAALgADCgIJAgAAAA==.',
['执子']='执子之约:BAAALgADCgMJAwAAAA==.',
['扫地']='扫地僧丶:BAAALgAECgUJBgAAAA==.',
['抚琴']='抚琴:BAAALgADCgYJBgAAAA==.',
['抡大']='抡大剑:BAABLgAFFH8JAAIaAAcJOxwMAABKAgAaAAcJOxwMAABKAgAAAA==.',
['抢脸']='抢脸僧:BAAALgAECgcJBwAAAA==.',
['披靡']='披靡:BAAALgAECgYJDgAAAA==.',
['拖延']='拖延的小短腿:BAAALgAECgYJBgAAAA==.',
['拾捌']='拾捌楽:BAAALgADCgQJBAAAAA==.',
['振翅']='振翅高飞:BAAALgAECgIJAgAAAA==.',
['挽云']='挽云:BAAALgAFFAQJBAAAAA==.',
['捡漏']='捡漏专家:BAAALgAECgcJBgABLgAECgcJDQAJAAAAAA==.',
['捷克']='捷克羅姆:BAAALgAECgIJAgAAAA==.',
['掉血']='掉血多喝热水:BAABLgAFFH8TAAIPAAYJBxuuAQD5AQAPAAYJBxuuAQD5AQAAAA==.',
['推丫']='推丫环:BAAALgAECgIJAgAAAA==.',
['提尔']='提尔丶林德曼:BAAALgAECgYJBwAAAA==.',
['提瑞']='提瑞斯法:BAAALgAECgUJDQAAAA==.',
['摇奶']='摇奶茶宗师:BAAALgADCgUJBQAAAA==.',
['收尾']='收尾升腾:BAABLgAFFH8IAAIDAAQJNybJAgDKAQADAAQJNybJAgDKAQABLgAFFAQJDAADABgmAA==.',
['收牛']='收牛奶:BAAALgAECgQJBQAAAA==.',
['改变']='改变为你:BAAALgAECgYJBgAAAA==.',
['放豬']='放豬的老星星:BAAALgADCgEJAQAAAA==.',
['故人']='故人昔归:BAAALgAECgQJAgAAAA==.',
['敲可']='敲可爱的鸭:BAAALgAECgcJBwAAAA==.',
['文羽']='文羽:BAAALgAECgEJAQAAAA==.',
['斜阳']='斜阳晚照:BAAALgADCgUJAwAAAA==.',
['斯嘉']='斯嘉丽约翰孙:BAAALgAECgYJEQAAAA==.',
['新晋']='新晋守护者:BAAALgADCgEJAQAAAA==.',
['无力']='无力琨琨:BAAALgAECgYJBgAAAA==.',
['无尽']='无尽翻滚:BAAALgAFFAIJBAAAAA==.',
['无火']='无火的余烬:BAAALgAECgYJBgAAAA==.',
['无疑']='无疑尔尔:BAAALgAECgYJAwAAAA==.无疑谔谔:BAAALgAECgkJBgAAAA==.',
['无非']='无非:BAAALgAECgYJAgAAAA==.',
['旧城']='旧城故梦丶:BAAALgAECgcJBwAAAA==.',
['旧忆']='旧忆缝合怪:BAAALgAECgkJCQAAAA==.',
['早间']='早间沙织:BAAALgAFFAQJBAAAAA==.',
['旭东']='旭东丸:BAAALgAECgYJBwABLgAECgYJGAAYALwSAA==.',
['时影']='时影小扎:BAAALgAECgIJAgAAAA==.',
['明前']='明前奶绿:BAAALgADCgUJBQAAAA==.',
['明日']='明日之光:BAAALgAECgQJBQAAAA==.',
['明月']='明月映星河:BAAALgAECgYJDwAAAA==.明月照大江:BAAALgAECgYJBgAAAA==.',
['星光']='星光初现:BAAALgAFFAMJAwAAAA==.',
['星球']='星球垮垮掌:BAABLgAFFH8FAAIcAAMJWh22EAD6AAAcAAMJWh22EAD6AAAAAA==.',
['星界']='星界折磨者丶:BAAALgADCgEJAQAAAA==.',
['星语']='星语丶:BAAALgAECgMJAwAAAA==.',
['星辰']='星辰羽:BAAALgAECgMJBAABLgAECgQJBAAJAAAAAA==.星辰郁郁:BAAALgAECgEJAQABLgAECgQJBAAJAAAAAA==.星辰闪耀:BAAALgAECgcJDQAAAA==.星辰音梦:BAAALgAECgQJBAAAAA==.',
['春芒']='春芒懈寒:BAAALgAECgMJBAAAAA==.',
['是奥']='是奥不是火:BAAALgAECgYJBQAAAA==.',
['显眼']='显眼宝:BAAALgAECgUJCQAAAA==.',
['晓孟']='晓孟:BAAALgAECgMJBAAAAA==.',
['晓风']='晓风吹起:BAAALgADCgQJCAAAAA==.',
['晚意']='晚意借北风:BAAALgADCgQJBAAAAA==.',
['景晟']='景晟:BAAALgAECgUJBQAAAA==.',
['晰晰']='晰晰:BAAALgAECgcJDgAAAA==.晰晰小可爱:BAAALgAECgYJDQAAAA==.',
['晴菜']='晴菜:BAACLgAFFH8FAAIOAAIJ4h8XBgC+AAAOAAIJ4h8XBgC+AAAuAAQKfxcAAg4ABgmRI30QAHkCAA4ABgmRI30QAHkCAAAA.',
['暁狐']='暁狐仙:BAAALgAECgMJAwAAAA==.',
['暗之']='暗之夜:BAABLgAFFH8HAAIRAAQJJRycBgCEAQARAAQJJRycBgCEAQAAAA==.',
['暗夜']='暗夜启示:BAAALgAECgYJEAAAAA==.暗夜暮宝:BAAALgAECgQJBAAAAA==.',
['暗影']='暗影人丶:BAAALgAECgUJBwAAAA==.',
['暗戰']='暗戰:BAAALgAECgQJBgAAAA==.',
['暗月']='暗月之蚀:BAAALgAECgIJAgAAAA==.',
['暗狱']='暗狱呢喃:BAAALgAECgEJAQAAAA==.',
['暗空']='暗空山新雨后:BAAALgADCgEJAQAAAA==.',
['暗颖']='暗颖:BAACLgAFFH8GAAMBAAMJ2h8NBgAfAQABAAMJ2h8NBgAfAQAUAAEJVxRFFABTAAAuAAQKfyYABAEACQmNIpgFAPYCAAEACQmNIpgFAPYCACMABwlWF/MZAMkBABQABgkLG8IwAF4BAAAA.',
['暮光']='暮光之心:BAACLgAFFH8PAAMLAAQJYRPEAwBbAQALAAQJwRHEAwBbAQAMAAQJbw9JEAAuAQAuAAQKfyIAAwwACAn3IB8KAP8CAAwACAn3IB8KAP8CAAsABQmFE6CGANQAAAAA.暮光龙崽:BAAALgAECgcJDQAAAA==.',
['暮色']='暮色染清秋:BAAALgADCgUJBQAAAA==.',
['暴怒']='暴怒丶:BAAALgAFFAEJAQAAAA==.',
['曼曼']='曼曼法:BAAALgAECgEJAQAAAA==.',
['曼谷']='曼谷过夜:BAAALgAECgkJBgAAAA==.',
['曼陀']='曼陀萝:BAAALgAECgIJAgAAAA==.',
['月上']='月上柳梢頭:BAACLgAFFH8KAAIRAAQJTxd+AgBoAQARAAQJTxd+AgBoAQAuAAQKfxoAAhEACAnVJBgBALACABEACAnVJBgBALACAAAA.',
['月下']='月下夜叉:BAAALgAECgQJBAAAAA==.月下邪能雨:BAAALgAECgYJBwAAAA==.',
['月亏']='月亏则盈:BAAALgAECgEJAQAAAA==.',
['月亮']='月亮小饼干吖:BAABLgAFFH8FAAICAAQJYRQHLAAGAQACAAQJYRQHLAAGAQAAAA==.',
['月夜']='月夜猎手:BAAALgAECgYJBgAAAA==.',
['月社']='月社妃:BAAALgAECgEJAQAAAA==.',
['月舞']='月舞:BAACLgAFFH8OAAIjAAYJ1hQbAgAEAgAjAAYJ1hQbAgAEAgAuAAQKfxcAAiMACAkLGSwQADwCACMACAkLGSwQADwCAAAA.',
['有医']='有医保的先上:BAAALgAECgUJBQAAAA==.',
['有奶']='有奶如骑:BAABLgAFFH8IAAIKAAQJzRI7BQA6AQAKAAQJzRI7BQA6AQAAAA==.',
['有生']='有生之莲:BAABLgAFFH8MAAINAAQJGxsEBABVAQANAAQJGxsEBABVAQAAAA==.',
['朗寶']='朗寶寶:BAAALgAECgIJAgAAAA==.',
['朗月']='朗月星未沉:BAAALgAECgIJAwAAAA==.',
['未来']='未来日记:BAAALgAECgcJBwABLgAFFAYJCgAFAHYKAA==.未来龙皇:BAAALgAECgcJEgAAAA==.',
['末狩']='末狩风影:BAAALgADCgMJAwAAAA==.',
['本间']='本间心铃:BAABLgAFFH8TAAIDAAUJKCCUAgDRAQADAAUJKCCUAgDRAQAAAA==.',
['术无']='术无可数:BAAALgAECgUJBgAAAA==.',
['朱小']='朱小涛:BAAALgAECgcJEQAAAA==.',
['机械']='机械硬盘:BAAALgAFFAEJAgAAAA==.',
['李恭']='李恭梓:BAABLgAFFH8FAAICAAUJyyJkBgD5AQACAAUJyyJkBgD5AQAAAA==.',
['李舜']='李舜生丶:BAAALgADCgEJAQAAAA==.',
['李轩']='李轩辕:BAAALgADCgcJBwAAAA==.',
['来吃']='来吃糖了:BAAALgADCgEJAQAAAA==.',
['来碗']='来碗鱼粥:BAABLgAFFH8GAAIFAAQJlBvuBACBAQAFAAQJlBvuBACBAQAAAA==.',
['枫霜']='枫霜黙:BAAALgAECgYJBgAAAA==.',
['枭锋']='枭锋:BAAALgAECgMJAwABLgAECgYJBgAJAAAAAA==.',
['柏拉']='柏拉图之泪:BAAALgAECgYJDQAAAA==.',
['某作']='某作业:BAACLgAFFH8QAAICAAUJ+yP9BQACAgACAAUJ+yP9BQACAgAuAAQKfxoAAgIACAkZJAoWACUDAAIACAkZJAoWACUDAAAA.',
['柠檬']='柠檬丶雪碧:BAAALgAECgYJDgAAAA==.柠檬维他茶:BAAALgAECgUJCQAAAA==.',
['柳生']='柳生剑影:BAABLgAFFH8GAAMHAAUJywr1HAAuAQAHAAQJywr1HAAuAQAIAAEJAABpGgAzAAAAAA==.',
['栊娘']='栊娘:BAAALgAECgMJAwAAAA==.',
['栗子']='栗子泡饭:BAAALgAECgMJAgABLgAECgYJFQABALkeAA==.',
['格兰']='格兰蒂娅:BAAALgAECgEJAQAAAA==.',
['桀桀']='桀桀不桀桀:BAAALgAECgYJBgAAAA==.',
['桂花']='桂花麻薯:BAACLgAFFH8NAAMMAAQJZiE2AwAcAQAMAAMJ0iA2AwAcAQALAAEJIiN5FwBqAAAuAAQKfx4AAgwACAkEInkIABYDAAwACAkEInkIABYDAAAA.',
['桃子']='桃子味汽水:BAAALgAECgEJAQAAAA==.',
['桑葚']='桑葚牛奶冰:BAAALgAFFAIJAwAAAA==.',
['桦树']='桦树:BAAALgAECggJCAAAAA==.',
['梅兰']='梅兰勒:BAAALgADCgcJBwAAAA==.',
['梅川']='梅川贼:BAAALgADCgEJAQAAAA==.',
['梅林']='梅林用腮呼吸:BAAALgADCgMJAwAAAA==.',
['梅菜']='梅菜扣肉丿:BAAALgADCgEJAgAAAA==.',
['梆吉']='梆吉的硬儿:BAAALgAECgEJAgAAAA==.',
['梦璃']='梦璃丶:BAABLgAFFH8GAAITAAMJ6wyUJQDrAAATAAMJ6wyUJQDrAAAAAA==.',
['梵妄']='梵妄浸澈:BAAALgAECgcJEAAAAA==.',
['椎名']='椎名真昼:BAAALgAECgYJBgABLgAFFAQJDwADAIUXAA==.',
['椰椰']='椰椰泡茶:BAABLgAECn8VAAIBAAYJuR5WGwACAgABAAYJuR5WGwACAgAAAA==.',
['樱桃']='樱桃来帮你:BAAALgAFFAIJAgABLgAFFAMJBQACAAgdAA==.樱桃的夏天:BAACLgAFFH8FAAICAAMJCB31IwAnAQACAAMJCB31IwAnAQAuAAQKfxYAAgIABwnhJfQoAM8CAAIABwnhJfQoAM8CAAAA.',
['橘子']='橘子泡茶:BAAALgAECgMJBgABLgAECgYJFQABALkeAA==.',
['橘栀']='橘栀清澈:BAAALgAECggJEgAAAA==.',
['檎獣']='檎獣:BAAALgADCgEJAQAAAA==.',
['檬檬']='檬檬子:BAAALgADCgMJAwABLgAECgUJBQAJAAAAAA==.',
['欣喜']='欣喜咯:BAABLgAFFH8IAAMLAAQJ4RbVDADnAAALAAMJzRjVDADnAAAmAAEJGxEaCQBWAAAAAA==.',
['欧欧']='欧欧法萝:BAAALgAECgEJAQAAAA==.',
['欧洲']='欧洲通行证:BAAALgAFFAQJBAAAAA==.',
['欧罗']='欧罗罗伽亚:BAAALgAECgEJAQABLgAFFAIJAgAJAAAAAA==.',
['止战']='止战挥戈:BAAALgAECgEJAgAAAA==.',
['死丽']='死丽濡:BAAALgAFFAEJAQABLgAFFAYJFQACAIwiAA==.',
['死在']='死在阴雨天:BAAALgAFFAMJAwAAAA==.',
['殇信']='殇信:BAAALgAECgYJCwAAAA==.',
['比克']='比克提尼:BAAALgAECggJCAAAAA==.',
['比八']='比八卜:BAAALgADCgUJBQAAAA==.',
['水之']='水之湄:BAAALgADCgQJBAAAAA==.',
['永夜']='永夜:BAAALgAECgIJAgAAAA==.',
['永真']='永真:BAAALgAECgEJAgAAAA==.',
['汉谟']='汉谟拉电:BAABLgAFFH8FAAILAAMJSw/0CwD2AAALAAMJSw/0CwD2AAAAAA==.',
['江梳']='江梳影:BAAALgADCgMJAwAAAA==.',
['江淮']='江淮寄雨:BAAALgAFFAIJAgAAAA==.',
['污喵']='污喵王:BAABLgAECn8VAAIHAAYJ1hcNcgCjAQAHAAYJ1hcNcgCjAQAAAA==.',
['污水']='污水塘:BAAALgAECgYJBgAAAA==.',
['沅芷']='沅芷澧兰:BAAALgAFFAIJBAAAAA==.',
['沈寂']='沈寂未央:BAABLgAFFH8GAAITAAQJdRf0MgCtAAATAAQJdRf0MgCtAAAAAA==.',
['沉梦']='沉梦啊丶:BAAALgAECgEJAQAAAA==.',
['沐月']='沐月之魂:BAAALgADCgcJCAAAAA==.',
['沙奈']='沙奈朵:BAABLgAECn8dAAMBAAgJcyFBBgDrAgABAAgJcyFBBgDrAgAjAAYJ8BqeGADXAQAAAA==.',
['沙德']='沙德木刻:BAACLgAFFH8RAAMDAAUJgByaCABSAQADAAQJ5RuaCABSAQAEAAUJZhOeAgAjAQAuAAQKfxwAAwMACAkpI3QOAL0CAAMABwlUJHQOAL0CAAQABwlSGOcQAKgBAAAA.',
['没有']='没有七:BAABLgAFFH8HAAIhAAMJGBD9EQDwAAAhAAMJGBD9EQDwAAAAAA==.',
['没馅']='没馅饺子:BAAALgAECgQJBAAAAA==.',
['沧海']='沧海星辰:BAAALgADCgYJBgAAAA==.',
['沫了']='沫了油的猪:BAAALgAFFAEJAQABLgAFFAIJAwAJAAAAAA==.',
['泉絮']='泉絮:BAAALgAECgYJCAAAAA==.',
['法力']='法力幼龙色散:BAACLgAFFH8IAAMhAAQJhAgzDgAdAQAhAAQJlAczDgAdAQAnAAEJqAlBCgBSAAAuAAQKfx4AAyEACAkAF4geANABACEABwnLFogeANABACcABgk4EvIYAHABAAAA.',
['法式']='法式节鸽:BAAALgAECgQJBAABLgAFFAIJBAAJAAAAAA==.',
['法爷']='法爷来个门:BAAALgAFFAQJBAAAAA==.',
['法甜']='法甜:BAAALgAECgEJAQAAAA==.',
['法饼']='法饼:BAAALgAECgYJCgAAAA==.',
['泠苓']='泠苓:BAAALgAECgEJAQAAAA==.',
['泰瑞']='泰瑞纳斯:BAAALgAFFAEJAQAAAA==.',
['泷骑']='泷骑士:BAAALgAECgkJCQAAAA==.',
['洛水']='洛水蝶依:BAACLgAFFH8HAAIHAAMJaSCzHAAwAQAHAAMJaSCzHAAwAQAuAAQKfxkAAgcACAlUI94XAOwCAAcACAlUI94XAOwCAAEuAAUUBQkHAB4A2RkA.',
['活人']='活人不医丶:BAAALgAECgEJAQAAAA==.',
['流氓']='流氓还不住手:BAAALgAECgQJBAAAAA==.',
['流浪']='流浪的西芹:BAAALgAECgEJAgAAAA==.',
['流离']='流离者的海:BAAALgADCgEJAQAAAA==.',
['浅唱']='浅唱灬星冉:BAAALgADCgYJBgAAAA==.',
['浅灬']='浅灬眠:BAAALgAECgYJBQAAAA==.',
['浊酒']='浊酒慰平生:BAAALgADCgYJBgAAAA==.',
['浮世']='浮世震鸣:BAABLgAFFH8HAAIfAAMJmSY8CgBbAQAfAAMJmSY8CgBbAQAAAA==.',
['海之']='海之光:BAAALgAECgEJAgAAAA==.',
['海拉']='海拉细胞:BAAALgAECggJBAAAAA==.',
['海烟']='海烟:BAAALgAECgcJCAAAAA==.',
['海王']='海王杨过:BAAALgAECgEJAQAAAA==.',
['海阔']='海阔天空:BAAALgADCgMJAwAAAA==.',
['涧阳']='涧阳丶:BAACLgAFFH8FAAMHAAMJqR1LHQCqAAAHAAIJHh9LHQCqAAAIAAEJvho4FABQAAAuAAQKfxQAAwcABwndG7FPAAMCAAcABwndG7FPAAMCAAgAAwmrFRgyAK8AAAAA.',
['深海']='深海小憩:BAAALgAECgEJAQAAAA==.深海黑牛:BAAALgAECgUJBQAAAA==.',
['深濑']='深濑慧:BAAALgAFFAEJAQAAAA==.',
['混沌']='混沌恶:BAAALgAECgEJAQAAAA==.',
['清心']='清心普善:BAAALgAECgMJBgAAAA==.',
['清辉']='清辉:BAAALgADCgIJAgAAAA==.',
['渣渣']='渣渣不是喳喳:BAACLgAFFH8FAAIeAAIJSRvNEQC4AAAeAAIJSRvNEQC4AAAuAAQKfxoAAh4ACAlNINQLANoCAB4ACAlNINQLANoCAAAA.',
['温柔']='温柔留给妈妈:BAAALgAECgQJBQAAAA==.',
['温水']='温水:BAAALgAECgMJBAAAAA==.',
['温蒂']='温蒂慕萨:BAACLgAFFH8PAAQhAAQJyw/eEAD6AAAhAAMJPBTeEAD6AAAnAAIJPARvBwCQAAAYAAEJzQEJGABCAAAuAAQKfyQAAxgACAmVHvYHALwCABgACAmVHvYHALwCACEABglTJAsRAGgCAAAA.',
['源稚']='源稚女:BAAALgADCgEJAQAAAA==.',
['溜溜']='溜溜梅:BAAALgAECgYJCgAAAA==.',
['滑雪']='滑雪人:BAAALgAECgUJCAABLgAFFAYJDwATALsgAA==.',
['漆黑']='漆黑意志:BAABLgAFFH8HAAIfAAQJVhGVBQBSAQAfAAQJVhGVBQBSAQABLgAFFAUJCQAaAGMXAA==.',
['漫步']='漫步:BAAALgAFFAEJAQAAAA==.',
['潇洒']='潇洒丶潇洒:BAAALgAECgYJDgAAAA==.潇洒就完了:BAAALgAECgYJDAAAAA==.',
['火法']='火法再见:BAACLgAFFH8OAAMkAAYJJxNiAwBSAQAkAAQJahFiAwBSAQAZAAMJ6xDtHADsAAAuAAQKfyUAAyQACQlGIfUBAHwDACQACQlGIfUBAHwDABkABwngGHc8AAICAAAA.',
['火雷']='火雷:BAAALgAECgIJAgAAAA==.',
['火鸡']='火鸡味的锅八:BAAALgADCgEJAgAAAA==.',
['灬天']='灬天殺灬:BAAALgADCgkJCQAAAA==.',
['灬帝']='灬帝炎:BAAALgADCgUJBQAAAA==.',
['灬无']='灬无情灬:BAAALgAECgYJDQAAAA==.',
['灬辣']='灬辣椒灬:BAAALgADCgEJAQABLgADCgcJBwAJAAAAAA==.',
['灵感']='灵感菇:BAAALgADCgEJAQAAAA==.',
['炁体']='炁体源流:BAAALgAECgkJAgAAAA==.',
['炎爆']='炎爆波比:BAAALgAECgIJAgAAAA==.',
['炫冰']='炫冰酷:BAABLgAFFH8MAAIcAAQJ+gxODgARAQAcAAQJ+gxODgARAQAAAA==.',
['炫酷']='炫酷酷:BAABLgAFFH8MAAIcAAQJ9BJ1CwArAQAcAAQJ9BJ1CwArAQAAAA==.',
['点点']='点点星光:BAAALgADCgYJCQAAAA==.点点眼欲:BAAALgAECgIJAgABLgAECgkJCwAJAAAAAA==.点点眼钰:BAAALgAFFAEJAQAAAA==.',
['炽光']='炽光色散:BAAALgAFFAIJBAABLgAFFAQJCAAhAIQIAA==.',
['烟雨']='烟雨之意:BAAALgADCgEJAQAAAA==.',
['烧饼']='烧饼哥哥:BAACLgAFFH8JAAILAAQJpCVxAADGAQALAAQJpCVxAADGAQAuAAQKfxMAAwsABwlcJQkKAPgCAAsABwlcJQkKAPgCAAwAAQkvCvCPACsAAAAA.',
['热心']='热心市民嘉哥:BAAALgAECgEJAQAAAA==.热心市民小曹:BAAALgAECgEJAQAAAA==.',
['焚风']='焚风的小不点:BAAALgAFFAIJAgAAAA==.',
['焦骨']='焦骨:BAAALgAECgEJAQAAAA==.',
['然尔']='然尔:BAAALgAECgEJAQAAAA==.',
['熊喵']='熊喵丶:BAAALgADCgEJAQAAAA==.',
['熊样']='熊样的猫:BAAALgAFFAEJAQAAAA==.',
['熙熙']='熙熙酱:BAACLgAFFH8SAAIfAAYJxR6IAADPAQAfAAYJxR6IAADPAQAuAAQKfxwAAh8ACQmXJeoCAKgDAB8ACQmXJeoCAKgDAAAA.',
['燃烧']='燃烧的羽翼:BAAALgADCgcJBwAAAA==.',
['爱丽']='爱丽丝历险记:BAAALgAECgEJAQAAAA==.',
['爱做']='爱做梦:BAAALgAECgcJAwAAAA==.',
['爱吃']='爱吃蛋挞:BAAALgAECgYJBgAAAA==.',
['爱喝']='爱喝奶的安美:BAAALgAECgcJDAABLgAECggJFwACAIobAA==.',
['爱莉']='爱莉希亚:BAAALgAFFAQJBAAAAA==.爱莉希娅:BAAALgAFFAQJBAAAAA==.爱莉西雅:BAABLgAFFH8FAAIfAAUJ5BrIAgDRAQAfAAUJ5BrIAgDRAQAAAA==.',
['爱莫']='爱莫能助呀:BAAALgAFFAEJAgAAAA==.',
['爺有']='爺有爺的范:BAAALgADCggJDgAAAA==.',
['牛奶']='牛奶膻:BAAALgAECgQJBAAAAA==.',
['牛波']='牛波一丶:BAAALgAECgcJBwABLgAFFAQJCgAhAGocAA==.牛波一丶龙:BAABLgAFFH8KAAIhAAQJahzECABhAQAhAAQJahzECABhAQAAAA==.',
['牛鼻']='牛鼻子强盗:BAAALgAFFAQJAQAAAA==.牛鼻子海盗:BAAALgAFFAQJBAAAAA==.牛鼻子老盗:BAABLgAFFH8FAAMRAAUJWhpkCABoAQARAAQJ/BtkCABoAQAaAAEJdBVFCQBfAAAAAA==.',
['牢大']='牢大闪击宿舍:BAAALgAECgcJDQAAAA==.',
['牢达']='牢达:BAABLgAFFH8HAAICAAMJugO3MQDjAAACAAMJugO3MQDjAAABLgAFFAQJDAAfAGcTAA==.',
['牧一']='牧一诗:BAAALgAECgYJDAAAAA==.',
['牧光']='牧光之城:BAAALgAFFAIJAgAAAA==.',
['牧瀬']='牧瀬红莉栖:BAACLgAFFH8OAAMCAAUJdiUmBAAvAgACAAUJdiUmBAAvAgAXAAEJJSYQAQB0AAAuAAQKfx8AAwIACQmAJRsDAM0DAAIACQmAJRsDAM0DABcAAgnEJJgOANoAAAAA.',
['牧魂']='牧魂者:BAAALgAECgEJAQAAAA==.',
['狂奔']='狂奔的灰烬:BAAALgAECgYJCgAAAA==.',
['狂小']='狂小鸭:BAABLgAECn8WAAMFAAcJhxOTMwC2AQAFAAcJhxOTMwC2AQADAAEJMAX5jAArAAAAAA==.',
['狂暴']='狂暴战大王:BAABLgAFFH8GAAIfAAMJ1iExEAAlAQAfAAMJ1iExEAAlAQAAAA==.',
['狐哩']='狐哩:BAABLgAFFH8JAAImAAUJ0xVZAQBuAQAmAAUJ0xVZAQBuAQAAAA==.',
['狐狸']='狐狸花不丸:BAAALgAECgMJAwAAAA==.',
['狠潤']='狠潤丶:BAAALgAFFAEJAQAAAA==.',
['独我']='独我南行:BAAALgAECgMJAwAAAA==.',
['独步']='独步暗舞射手:BAAALgADCgYJBgAAAA==.',
['狮鹫']='狮鹫狮鹫:BAAALgAECgQJBQAAAA==.',
['狸猫']='狸猫:BAABLgAFFH8MAAMQAAQJCCMdAACkAQAQAAQJkiEdAACkAQAHAAQJ4B46CQCHAQAAAA==.',
['狼与']='狼与卡布奇诺:BAABLgAFFH8FAAILAAQJpxWRAwBkAQALAAQJpxWRAwBkAQAAAA==.',
['狼的']='狼的兄弟:BAAALgAECgUJBQAAAA==.',
['狼骑']='狼骑竹马来:BAAALgAECgYJCAAAAA==.',
['猎熊']='猎熊宝宝:BAAALgAFFAIJAwAAAA==.',
['猪打']='猪打牌:BAABLgAECn8kAAICAAgJAiQ/EABGAwACAAgJAiQ/EABGAwAAAA==.',
['猫爪']='猫爪在上:BAAALgAECgIJAgAAAA==.',
['猴掌']='猴掌瓜哈尼此:BAAALgADCgUJBQAAAA==.',
['玄月']='玄月骑士:BAABLgAFFH8FAAIfAAUJ7wYBCAAvAQAfAAUJ7wYBCAAvAQAAAA==.',
['玉玉']='玉玉:BAAALgAECgEJAQAAAA==.',
['玉藻']='玉藻十字:BAAALgAFFAIJBAAAAA==.',
['王伟']='王伟:BAAALgAECgEJAQAAAA==.',
['玛莎']='玛莎里墩:BAAALgADCgIJAgAAAA==.',
['玛露']='玛露希尔:BAACLgAFFH8NAAICAAUJiQ1UDQCxAQACAAUJiQ1UDQCxAQAuAAQKfyQAAgIACAk8IhoXAB8DAAIACAk8IhoXAB8DAAAA.',
['玲珑']='玲珑:BAAALgAECgcJBwAAAA==.',
['珍妮']='珍妮玛丨士多:BAABLgAFFH8HAAIcAAIJvBMVHACNAAAcAAIJvBMVHACNAAAAAA==.',
['琉聆']='琉聆漱枳:BAACLgAFFH8aAAMHAAcJpSJ7AAB9AgAHAAYJpSJ7AAB9AgAIAAEJAABDGAA7AAAuAAQKfxYAAgcACQluJREEAJMDAAcACQluJREEAJMDAAAA.',
['琥丨']='琥丨珀:BAAALgAECgkJAwAAAA==.',
['瑟拉']='瑟拉妮尔:BAAALgADCgEJAgAAAA==.',
['璘儿']='璘儿:BAABLgAFFH8KAAIBAAQJcCG6AgB8AQABAAQJcCG6AgB8AQAAAA==.',
['瓦琅']='瓦琅:BAAALgAECgIJAgAAAA==.',
['瓯瓯']='瓯瓯子:BAABLgAFFH8FAAIHAAIJ/hStHwCiAAAHAAIJ/hStHwCiAAAAAA==.',
['甜宝']='甜宝:BAACLgAFFH8JAAIhAAQJAxI2DAA7AQAhAAQJAxI2DAA7AQAuAAQKfxcAAyEABwmrHY8RAGECACEABwmrHY8RAGECABgAAwlaAHRGAD4AAAAA.',
['甜崽']='甜崽:BAABLgAFFH8QAAITAAUJISZUAgAPAgATAAUJISZUAgAPAgAAAA==.',
['甜筒']='甜筒大王:BAAALgAECgMJAwAAAA==.',
['生吞']='生吞:BAAALgAECgUJBQAAAA==.',
['生茧']='生茧的左手:BAAALgADCgYJBgAAAA==.',
['用晦']='用晦而明:BAAALgADCgYJCAAAAA==.',
['电击']='电击爽疗:BAAALgAECgMJAwAAAA==.',
['电子']='电子羊:BAAALgAFFAIJBAAAAA==.',
['电炎']='电炎绝手:BAAALgAECgEJAQAAAA==.',
['电疗']='电疗主治医生:BAAALgAECgUJBwAAAA==.',
['疯子']='疯子戴夫:BAAALgADCgUJBQAAAA==.',
['疯狂']='疯狂小柯基:BAAALgADCgUJBQAAAA==.疯狂掷弹手丶:BAAALgAECgYJBgAAAA==.疯狂的电钻:BAAALgADCgYJBgAAAA==.',
['痛苦']='痛苦消散:BAAALgAECgUJCwAAAA==.',
['痞大']='痞大波萝派:BAAALgAECgEJAQAAAA==.痞大菠萝派:BAAALgAECgEJAQAAAA==.',
['白夜']='白夜狼魂:BAABLgAFFH8IAAMeAAQJBxxnBwBrAQAeAAQJBxxnBwBrAQAPAAQJJgvRBwAVAQABLgAFFAYJEQAeADQeAA==.',
['白帝']='白帝子:BAAALgADCgYJBgAAAA==.',
['白昼']='白昼:BAABLgAECn8WAAQTAAkJBxSMVgDEAQATAAcJZBWMVgDEAQAVAAMJ8w+qQACyAAAWAAEJAADXMAA8AAAAAA==.',
['白毛']='白毛酋长:BAABLgAFFH8NAAITAAUJTiE3AgCbAQATAAUJTiE3AgCbAQAAAA==.',
['白衣']='白衣梅子酒:BAAALgAFFAIJAgAAAA==.',
['白面']='白面鸮:BAAALgADCgEJAQAAAA==.',
['皮蛋']='皮蛋瘦肉粥:BAAALgAECgUJBQAAAA==.',
['盗之']='盗之隐者:BAAALgAECgcJBwAAAA==.',
['盾大']='盾大胖:BAAALgADCgEJAQAAAA==.',
['真男']='真男人开越野:BAAALgAECgIJBAAAAA==.',
['真页']='真页:BAAALgAECgQJBQAAAA==.',
['着魔']='着魔:BAAALgAFFAIJBAAAAA==.',
['睚眦']='睚眦之怨:BAAALgADCgMJAwAAAA==.',
['矮呦']='矮呦薇:BAAALgADCgUJBQAAAA==.',
['石头']='石头先生:BAAALgAECgQJBAAAAA==.',
['破万']='破万剑:BAAALgAECgQJBwAAAA==.',
['破碎']='破碎是常态:BAABLgAFFH8JAAIOAAQJRyHnAQBLAQAOAAQJRyHnAQBLAQAAAA==.',
['碎碎']='碎碎的怀念:BAABLgAECn8bAAQfAAYJFCQkDAD0AQAfAAYJFCQkDAD0AQAgAAIJqQvcOwBPAAAKAAEJBgZ9mwAuAAAAAA==.',
['礼送']='礼送白:BAABLgAFFH8FAAIcAAQJ4AMnEwDfAAAcAAQJ4AMnEwDfAAAAAA==.',
['神棍']='神棍归来:BAAALgADCgMJAwAAAA==.神棍徳:BAAALgADCgYJBgAAAA==.',
['神裂']='神裂火织:BAAALgAECgEJAQAAAA==.',
['福娃']='福娃虚影:BAAALgAECgYJBwAAAA==.',
['福瑞']='福瑞狼:BAAALgAECgEJAgAAAA==.',
['禽史']='禽史黄:BAAALgAECgYJBgAAAA==.',
['秋天']='秋天的丰盛:BAAALgAECgYJBgAAAA==.',
['秋月']='秋月涑水:BAAALgAECgYJBwAAAA==.',
['秋水']='秋水凝思:BAAALgAECgEJAQAAAA==.秋水揽星河丶:BAAALgAECgYJCQAAAA==.',
['秋荷']='秋荷:BAAALgADCgEJAQAAAA==.',
['秒切']='秒切战斗脸:BAAALgAFFAMJBAAAAA==.',
['稻壳']='稻壳浮叠:BAAALgAECgYJBgAAAA==.',
['穆恩']='穆恩帕拉丁:BAAALgAECgYJCgAAAA==.穆恩萌德:BAAALgAECgYJDAAAAA==.',
['穿雲']='穿雲剑:BAAALgAECgYJBgAAAA==.',
['窕窕']='窕窕:BAAALgADCgcJBwAAAA==.',
['窝心']='窝心的纯牛奶:BAAALgAECgQJBgAAAA==.',
['立崧']='立崧败:BAABLgAFFH8JAAIcAAUJfAUmCwAtAQAcAAUJfAUmCwAtAQAAAA==.',
['竹叶']='竹叶清酒:BAAALgAECgIJAgAAAA==.',
['笑傲']='笑傲苍穹:BAAALgAECgYJAQAAAA==.',
['笑嘻']='笑嘻了:BAAALgADCgEJAQAAAA==.',
['笑忘']='笑忘歌:BAAALgAECgEJAgAAAA==.',
['等一']='等一轮明月:BAACLgAFFH8JAAIKAAQJNhnOCABGAQAKAAQJNhnOCABGAQAuAAQKfx8AAgoACAkxJOgEAB4DAAoACAkxJOgEAB4DAAAA.',
['等天']='等天黑:BAABLgAFFH8JAAIFAAQJ3h2vBQAtAQAFAAQJ3h2vBQAtAQAAAA==.',
['等等']='等等酱:BAAALgAECgQJBgAAAA==.',
['筱川']='筱川:BAAALgAECgEJAgAAAA==.',
['筱灬']='筱灬川:BAAALgAECgEJAQAAAA==.',
['简子']='简子凡:BAABLgAFFH8DAAITAAMJGQnNJgDjAAATAAMJGQnNJgDjAAAAAA==.',
['箴言']='箴言徒:BAAALgAECgYJBAAAAA==.',
['範馬']='範馬刃牙:BAAALgAECgUJBwAAAA==.',
['篝之']='篝之丶雾枝:BAAALgAECgEJAgAAAA==.',
['米俢']='米俢:BAACLgAFFH8GAAIYAAQJOhL+CQBJAQAYAAQJOhL+CQBJAQAuAAQKfxcABBgACAkAGAQNAGUCABgACAkAGAQNAGUCACcAAQnHBtk/ADEAACEAAQlEDlZkAC0AAAAA.',
['米拉']='米拉希尔:BAAALgAECgQJBAAAAA==.米拉波雷亚斯:BAAALgAECgQJCAAAAA==.',
['米迦']='米迦勒之翼:BAAALgADCgYJBgAAAA==.',
['粉头']='粉头双马尾:BAAALgAECgEJAgAAAA==.',
['糕仁']='糕仁:BAABLgAECn8cAAIeAAgJlx0MDQDIAgAeAAgJlx0MDQDIAgAAAA==.',
['糖分']='糖分摄取过量:BAAALgAECgMJAwAAAA==.',
['糖果']='糖果小子:BAAALgAECgEJAQAAAA==.',
['糖门']='糖门灬滚:BAAALgAECgYJCAAAAA==.',
['索爾']='索爾迦雷歐:BAAALgAECgYJCgAAAA==.',
['索薇']='索薇尔公爵:BAAALgAECgMJBQAAAA==.',
['紫色']='紫色怎么了:BAAALgAECgkJCwAAAA==.',
['红浪']='红浪漫技师:BAAALgAECgEJAQAAAA==.',
['红烧']='红烧原味猫:BAAALgAECgcJBwAAAA==.',
['红莲']='红莲鹰歌:BAAALgAECgIJAgAAAA==.',
['红豆']='红豆同书:BAACLgAFFH8FAAMLAAQJQCAvCAAiAQALAAMJ+x8vCAAiAQAMAAEJDyF7IwBfAAAuAAQKfxkAAwsACQmlJCQTAJ4CAAsABgnhJSQTAJ4CAAwABQkgHU00AJcBAAAA.',
['绊猪']='绊猪吃恐龙:BAAALgAFFAMJAwAAAA==.绊猪吃竹子:BAAALgADCgQJBAAAAA==.绊猪吃蚊子:BAAALgADCgUJBQAAAA==.',
['绚丽']='绚丽凤凰小风:BAAALgAFFAEJAQAAAA==.',
['绝世']='绝世可爱精:BAAALgAECgQJBQAAAA==.',
['绝无']='绝无城:BAAALgAECgcJDQAAAA==.',
['续断']='续断:BAABLgAECn8UAAIfAAgJyx1wLQBuAgAfAAgJyx1wLQBuAgAAAA==.',
['维罗']='维罗妮卡诺顿:BAEALgAECgUJBwABLgAFFAEJAQAJAAAAAA==.',
['绿莹']='绿莹莹:BAAALgAECgYJBgAAAA==.',
['罪人']='罪人挽歌:BAABLgAFFH8JAAIfAAUJYyExAgDqAQAfAAUJYyExAgDqAQAAAA==.',
['老公']='老公么么哒:BAAALgAECgcJBwAAAA==.',
['老夏']='老夏丶:BAABLgAECn8WAAIfAAkJyB9vDwATAwAfAAkJyB9vDwATAwABLgAFFAUJAwAJAAAAAA==.',
['老李']='老李頭的脛骨:BAACLgAFFH8JAAICAAQJQwkiIABGAQACAAQJQwkiIABGAQAuAAQKfxoAAgIACAmcHYE5AJACAAIACAmcHYE5AJACAAAA.',
['老细']='老细我撇先:BAAALgAECgUJDQAAAA==.',
['老鬼']='老鬼骑士:BAAALgAECgEJAQAAAA==.',
['耐落']='耐落:BAAALgAECgEJAQAAAA==.',
['联盟']='联盟女侠:BAAALgAECgEJAQAAAA==.',
['聚气']='聚气冢:BAACLgAFFH8GAAIcAAQJjA8lDQAcAQAcAAQJjA8lDQAcAQAuAAQKfxsAAxwABwnEGREgAAECABwABwnEGREgAAECAA0AAQmiGmZgAE0AAAAA.',
['聚集']='聚集的祈愿:BAAALgAFFAUJAQAAAA==.',
['肆号']='肆号:BAAALgAECgEJAQAAAA==.',
['肉蛋']='肉蛋聪鸡:BAAALgAECgYJBgAAAA==.',
['胧云']='胧云绯月:BAAALgADCgYJBgAAAA==.',
['脆皮']='脆皮小狐狸:BAAALgAFFAIJBAAAAA==.',
['脆脆']='脆脆黄桃罐头:BAABLgAFFH8IAAQLAAQJ1yKdBwApAQALAAQJ1yKdBwApAQAmAAEJYBMeCABfAAAMAAEJzR3ZIwBaAAABLgAFFAQJBQALAEAgAA==.',
['臭鸨']='臭鸨:BAAALgAECgEJAQAAAA==.',
['致命']='致命之书:BAAALgADCgEJAQAAAA==.',
['致尊']='致尊寳:BAAALgADCgEJAQAAAA==.',
['艾妮']='艾妮:BAAALgADCgIJAgAAAA==.',
['艾玛']='艾玛莎:BAAALgAECgYJBAAAAA==.',
['艾由']='艾由曦:BAAALgAECgIJAgAAAA==.艾由莎:BAAALgAECgYJBgAAAA==.',
['芭乐']='芭乐味奶糖:BAAALgAECgkJBgABLgAFFAQJAQAJAAAAAA==.',
['花开']='花开依旧在:BAAALgAECgMJAwAAAA==.',
['苍太']='苍太子:BAAALgADCgEJAQAAAA==.',
['苏小']='苏小美:BAAALgAECgYJDAAAAA==.',
['苏文']='苏文纨丶:BAABLgAECn8dAAIGAAgJpB5oEgCKAgAGAAgJpB5oEgCKAgAAAA==.',
['若彬']='若彬丶:BAAALgAECgYJBgAAAA==.',
['苦瓜']='苦瓜:BAAALgAECgMJBgAAAA==.',
['英勇']='英勇無比:BAACLgAFFH8OAAIRAAQJHyP+AACMAQARAAQJHyP+AACMAQAuAAQKfxoAAhEACAlnHGcYAIkCABEACAlnHGcYAIkCAAAA.',
['英雄']='英雄冢:BAAALgAECgMJAwAAAA==.',
['茄子']='茄子肉沫盖饭:BAAALgAECgUJBQAAAA==.',
['茗寞']='茗寞幽殇:BAAALgAECgMJAwAAAA==.',
['茜色']='茜色诗篇:BAACLgAFFH8PAAIDAAQJhRfaBwBcAQADAAQJhRfaBwBcAQAuAAQKfx8AAgMACQmdIxEDAHcDAAMACQmdIxEDAHcDAAAA.',
['茶白']='茶白布丁丶:BAAALgAECgQJBQAAAA==.',
['茶酱']='茶酱:BAACLgAFFH8IAAIDAAQJaAsiDAAqAQADAAQJaAsiDAAqAQAuAAQKfxgAAwUABwkeI3QQAJQCAAUABwkeI3QQAJQCAAMABgl+H4QfABQCAAEuAAUUBgkJAA0Auh0A.',
['荀文']='荀文若:BAAALgAFFAEJAQABLgAFFAIJBAAJAAAAAA==.',
['草莓']='草莓招了:BAACLgAFFH8XAAIIAAYJWCYlAACsAgAIAAYJWCYlAACsAgAuAAQKfxcAAggACAn9JYQBAHUDAAgACAn9JYQBAHUDAAAA.',
['荏苒']='荏苒如沙:BAAALgAECgQJBQAAAA==.',
['荔枝']='荔枝骑士:BAAALgAECgIJAgAAAA==.',
['莉亚']='莉亚德澪:BAAALgAFFAEJAQAAAA==.',
['莱奥']='莱奥波波:BAABLgAECn8VAAIPAAYJcSRQGAB0AgAPAAYJcSRQGAB0AgAAAA==.',
['莱萨']='莱萨杰丝丶:BAAALgADCgEJAQAAAA==.',
['莱雅']='莱雅娜丶夜歌:BAAALgAECgQJBAAAAA==.',
['菜异']='菜异灵丶:BAAALgAECgUJBwAAAA==.',
['菲菲']='菲菲:BAAALgAECgQJBwAAAA==.',
['萌新']='萌新求赞:BAABLgAECn8ZAAIKAAgJfxGOIQARAgAKAAgJfxGOIQARAgAAAA==.',
['萌球']='萌球丸:BAAALgAFFAQJBAAAAA==.',
['萌萌']='萌萌丨恶魔:BAAALgAECgYJBgAAAA==.萌萌霸霸:BAAALgAFFAQJBAAAAA==.萌萌香:BAAALgAECgQJBAAAAA==.萌萌麻麻呀:BAAALgAFFAQJBAAAAA==.',
['落叶']='落叶二面黄:BAAALgADCgYJBgAAAA==.',
['蒋劲']='蒋劲夫的拳:BAAALgAECgEJAQAAAA==.',
['蓝毛']='蓝毛酋长:BAACLgAFFH8IAAICAAMJlBnYEwAUAQACAAMJlBnYEwAUAQAuAAQKfxsAAgIACAkcG68yAKgCAAIACAkcG68yAKgCAAAA.',
['蓝海']='蓝海悦:BAAALgAFFAMJAwAAAA==.',
['蓝特']='蓝特里:BAAALgAECgcJDgAAAA==.',
['蓝盈']='蓝盈盈:BAAALgAECgYJEgAAAA==.',
['蓝色']='蓝色绚影:BAAALgAECgYJDAAAAA==.',
['蓝莓']='蓝莓泡芙:BAAALgAECgYJBgAAAA==.',
['蓝蓝']='蓝蓝雨君:BAABLgAECn8WAAICAAcJNAmZRQDiAAACAAcJNAmZRQDiAAAAAA==.',
['蓦然']='蓦然回首丶:BAAALgAFFAEJAQAAAA==.',
['蕾繆']='蕾繆安:BAAALgAECgcJEAABLgAFFAgJHQADAMMfAA==.',
['薄荷']='薄荷嘤嘤鱼:BAAALgAECgcJDQAAAA==.',
['薇小']='薇小薇:BAAALgADCgYJBgABLgAFFAcJBQACANIGAA==.',
['薇薇']='薇薇风影:BAAALgADCgEJAQAAAA==.',
['薛淺']='薛淺情:BAAALgADCgYJBgAAAA==.',
['薛迪']='薛迪凯:BAAALgAECgEJAQAAAA==.',
['薩拉']='薩拉迈尼:BAAALgAECggJDQAAAA==.',
['藤虎']='藤虎一笑:BAAALgAECgEJAgAAAA==.',
['虚空']='虚空牛牛:BAAALgADCgMJAwAAAA==.',
['虫前']='虫前有只猫:BAAALgAFFAIJAgAAAA==.',
['蛇遣']='蛇遣骑士:BAAALgAFFAEJAQAAAA==.',
['蜀道']='蜀道山棒棒娃:BAAALgAECgUJBQAAAA==.',
['蜗牛']='蜗牛侠:BAAALgAECgcJCgAAAA==.',
['蝎纸']='蝎纸莱莱:BAABLgAFFH8JAAIhAAUJnhtDBADNAQAhAAUJnhtDBADNAQAAAA==.',
['蠕虫']='蠕虫低语:BAAALgAECgIJAgAAAA==.',
['血与']='血与火的深渊:BAAALgAFFAQJAQAAAA==.',
['血色']='血色神话:BAAALgADCgMJAwAAAA==.',
['表妹']='表妹慢热手:BAAALgAECgQJBAAAAA==.',
['袁紫']='袁紫衣:BAAALgAECgEJAgAAAA==.',
['被偷']='被偷正面了:BAABLgAECn8WAAMeAAgJeRCpKwClAQAeAAgJeRCpKwClAQAPAAQJURUgdQD4AAAAAA==.',
['被吸']='被吸血包:BAAALgAECgcJBwAAAA==.',
['裂心']='裂心:BAAALgAFFAIJAwAAAA==.',
['裂牙']='裂牙:BAAALgADCgEJAQAAAA==.',
['褚樱']='褚樱桃:BAAALgAECgYJBwAAAA==.',
['西照']='西照:BAAALgAFFAEJAQAAAA==.',
['西苓']='西苓:BAAALgAECgYJDgAAAA==.',
['西野']='西野加奈丶:BAAALgAECgYJDAAAAA==.',
['要爪']='要爪子随便你:BAAALgADCgEJAQAAAA==.',
['见习']='见习的巫师:BAAALgAECgEJAgAAAA==.',
['角角']='角角大冰刺儿:BAAALgAECgIJAgABLgAFFAQJDAATAEAlAA==.角角的糖门滚:BAACLgAFFH8MAAMTAAQJQCVtAgCXAQATAAQJQCVtAgCXAQAVAAEJixPQFABVAAAuAAQKfxQAAxMABwktJDw7AB8CABMABgnAIzw7AB8CABUAAwnDGJI1AOAAAAAA.',
['誓死']='誓死效忠圣光:BAAALgAECgEJAQAAAA==.',
['计云']='计云:BAAALgAECgIJAgAAAA==.',
['认真']='认真玩个涕吧:BAAALgAECgkJAQAAAA==.',
['许喵']='许喵熊:BAAALgAFFAQJBAAAAA==.',
['许旌']='许旌阳:BAAALgAECgIJAwAAAA==.',
['诗云']='诗云:BAAALgAECgEJAQAAAA==.',
['说与']='说与山嵬听:BAAALgAECgEJAQAAAA==.',
['谁在']='谁在打我:BAAALgADCgYJBgAAAA==.',
['豆包']='豆包包:BAAALgAECgQJBAAAAA==.',
['败家']='败家姐姐:BAAALgAECgEJAQAAAA==.',
['贰叁']='贰叁叁丶:BAAALgAECgYJAgABLgAECggJCQAJAAAAAA==.贰叁叁会哈玖:BAAALgAECggJCQAAAA==.贰叁叁会巴掌:BAAALgAECgcJBwAAAA==.贰叁叁会糖门:BAAALgAECgUJBQAAAA==.',
['费尔']='费尔西多:BAACLgAFFH8KAAIkAAQJAhF1AwBQAQAkAAQJAhF1AwBQAQAuAAQKfyAAAyQACAnyHMAIANcCACQACAnyHMAIANcCABkAAQkXAbr1ABgAAAAA.',
['赛法']='赛法莉娅:BAAALgAECgUJCAAAAA==.',
['赤沙']='赤沙之蠍:BAAALgADCgYJBgAAAA==.',
['走饭']='走饭:BAAALgAECgEJAQAAAA==.',
['赵客']='赵客缦胡缨:BAACLgAFFH8HAAIHAAQJRBH3HAAuAQAHAAQJRBH3HAAuAQAuAAQKfxkAAgcABwlzILMtAIICAAcABwlzILMtAIICAAAA.',
['赵小']='赵小波浪:BAAALgAECgcJBwAAAA==.',
['起司']='起司丶:BAAALgAECgEJAgAAAA==.',
['超人']='超人猫猫:BAAALgAECgcJBgAAAA==.',
['超大']='超大油条:BAAALgADCgcJEAAAAA==.',
['超甜']='超甜豆浆:BAAALgADCgcJEAAAAA==.',
['超级']='超级南瓜瓜:BAAALgAFFAQJBAAAAA==.超级咕猫熊:BAAALgAECgQJBAAAAA==.超级大红肠:BAAALgAECgYJBgAAAA==.超级牛冲天:BAABLgAFFH8FAAIRAAIJ+whzDQCiAAARAAIJ+whzDQCiAAAAAA==.',
['路绘']='路绘:BAABLgAFFH8GAAMjAAQJlhfvCABNAQAjAAQJlhfvCABNAQAUAAEJvQI3FQBPAAAAAA==.',
['跳舞']='跳舞街:BAAALgAECgEJAQAAAA==.',
['踏血']='踏血寻莓:BAAALgAECgEJAQAAAA==.',
['蹦蹦']='蹦蹦丶跳跳:BAACLgAFFH8JAAMHAAMJwiAKHgAoAQAHAAMJwiAKHgAoAQAQAAEJ3BmCAgBWAAAuAAQKfyAAAgcACQkWHEgEAGwCAAcACQkWHEgEAGwCAAAA.',
['躲不']='躲不过去心动:BAAALgADCgEJAQAAAA==.',
['辛唐']='辛唐未吉泽:BAAALgAECgMJAwAAAA==.',
['辛德']='辛德拉:BAABLgAECn8ZAAIZAAgJXRefQQDuAQAZAAgJXRefQQDuAQAAAA==.',
['辞云']='辞云雀舞:BAAALgAECgMJAwABLgAFFAEJAQAJAAAAAA==.',
['辰星']='辰星:BAAALgADCgUJBQABLgAFFAMJBAAZADwkAA==.',
['达利']='达利亚:BAAALgAFFAIJAgAAAA==.',
['达维']='达维安:BAAALgADCgcJBwAAAA==.',
['达美']='达美乐:BAAALgAECgUJDAAAAA==.',
['还不']='还不下班:BAAALgAFFAEJAQAAAA==.',
['这德']='这德:BAAALgAECgUJBgAAAA==.',
['这是']='这是垃圾职业:BAAALgADCgMJAwAAAA==.',
['这牧']='这牧:BAAALgAECgYJBwAAAA==.',
['这花']='这花:BAAALgAFFAQJBAAAAA==.',
['远古']='远古毒瘤:BAAALgAECgYJBwABLgAECgcJDQAJAAAAAA==.',
['远夜']='远夜:BAAALgADCgEJAgAAAA==.',
['远思']='远思大领主:BAAALgAECgUJCQAAAA==.',
['迢夜']='迢夜为怡楠棉:BAAALgAFFAEJAQAAAA==.',
['迪克']='迪克节鸽:BAAALgAFFAIJBAAAAA==.',
['送丹']='送丹丹:BAAALgAFFAIJAwAAAA==.',
['选择']='选择大于努力:BAAALgAECgYJCQABLgAECgYJHwAUALUeAA==.',
['逝去']='逝去的豆包:BAAALgADCgUJBQAAAA==.',
['遇见']='遇见靜:BAAALgAECgIJAgAAAA==.',
['遗忘']='遗忘的孤单:BAAALgAECgUJBQAAAA==.',
['邓紫']='邓紫棋:BAAALgAECgUJCwAAAA==.',
['那年']='那年圣光绽放:BAAALgAECgEJAQAAAA==.',
['酒是']='酒是老英雄:BAAALgAECgUJBQAAAA==.',
['酷小']='酷小懿:BAAALgAECgMJAwAAAA==.',
['酸奶']='酸奶紫米露:BAAALgAECgQJCwAAAA==.',
['酸菜']='酸菜鱼鳞:BAAALgAECgIJAgAAAA==.',
['醉卧']='醉卧九天:BAAALgAECgEJAQAAAA==.',
['醉枕']='醉枕孤潮:BAABLgAFFH8IAAIcAAQJoyDLBACJAQAcAAQJoyDLBACJAQABLgAFFAYJFwAIAFgmAA==.',
['钢须']='钢须:BAAALgAECgEJAQAAAA==.',
['钵钵']='钵钵鸟:BAAALgAECgYJCQAAAA==.',
['银月']='银月先生丶:BAAALgAECgMJBQAAAA==.',
['银色']='银色牡鹿:BAACLgAFFH8HAAIHAAMJIReGJgD8AAAHAAMJIReGJgD8AAAuAAQKfxkAAwcABwmUG/pEACYCAAcABwmUG/pEACYCAAgABgnKC9AlABABAAAA.银色荆棘:BAAALgAECgQJBAAAAA==.',
['销魂']='销魂灬蚀骨:BAACLgAFFH8RAAIHAAQJfB3LBQBgAQAHAAQJfB3LBQBgAQAuAAQKfycAAgcACAmzINspAJICAAcACAmzINspAJICAAAA.',
['锤你']='锤你懒子:BAAALgAECgkJCQAAAA==.',
['长刀']='长刀研:BAAALgADCgIJAgAAAA==.',
['长骑']='长骑素士:BAABLgAECn8mAAMKAAgJLQ/VLwDCAQAKAAgJLQ/VLwDCAQAfAAIJYgSxYgBVAAAAAA==.',
['闪焰']='闪焰:BAAALgAECgEJAQABLgAECggJJAACAAIkAA==.',
['闪电']='闪电猫:BAAALgAECgYJDAAAAA==.',
['阳焱']='阳焱复顾:BAAALgAECgYJEQAAAA==.',
['阿也']='阿也:BAAALgAECgYJBAAAAA==.',
['阿塞']='阿塞雷:BAAALgAECgEJAgAAAA==.',
['阿尔']='阿尔蒂弥斯:BAAALgADCgIJAgAAAA==.',
['阿张']='阿张饲养员:BAABLgAECn8WAAISAAcJ7xzUDQAtAgASAAcJ7xzUDQAtAgAAAA==.',
['阿斯']='阿斯呦:BAAALgAECgQJBAAAAA==.',
['阿柜']='阿柜:BAAALgAECgEJAQAAAA==.',
['阿米']='阿米娅:BAAALgADCgIJAgAAAA==.',
['阿莫']='阿莫西林猫:BAAALgAECgEJAQAAAA==.',
['阿萨']='阿萨德丁丁:BAAALgAECgIJAgAAAA==.',
['阿鳝']='阿鳝:BAAALgAECgEJAgAAAA==.',
['陆展']='陆展玄:BAAALgAFFAIJAgAAAA==.',
['陆登']='陆登的回声:BAAALgAECgQJBAAAAA==.',
['陈皮']='陈皮柠檬:BAABLgAECn8YAAICAAYJLBoEgADRAQACAAYJLBoEgADRAQAAAA==.',
['陌上']='陌上狐:BAAALgAFFAEJAQAAAA==.',
['隐者']='隐者小号:BAAALgAECgYJBgAAAA==.隐者无畏:BAAALgAECgkJCQAAAA==.',
['难受']='难受啊别啊:BAAALgADCgIJAgAAAA==.',
['雅坤']='雅坤:BAAALgAECgEJBAAAAA==.',
['雅拉']='雅拉:BAAALgAECgcJDAAAAA==.',
['雨下']='雨下一整碗:BAAALgAECgYJBgAAAA==.',
['雨中']='雨中溜达:BAAALgAECgYJDwAAAA==.',
['雨思']='雨思纷飞:BAAALgADCgYJBgAAAA==.',
['雨柱']='雨柱:BAAALgAFFAEJAQAAAA==.',
['雨诺']='雨诺诺:BAABLgAFFH8HAAINAAUJCxC3AgCJAQANAAUJCxC3AgCJAQAAAA==.',
['雪中']='雪中尘埃:BAAALgAECgkJDAAAAA==.',
['雪浪']='雪浪摇空:BAAALgAECgEJAQABLgAFFAMJBwAfAJkmAA==.',
['雪色']='雪色光晕:BAAALgADCgcJBwAAAA==.',
['雪莉']='雪莉玫丶:BAAALgAFFAIJAwAAAA==.',
['雪魅']='雪魅之影:BAAALgADCgEJAgAAAA==.',
['雲云']='雲云:BAAALgADCgUJBQAAAA==.',
['零度']='零度依然可乐:BAAALgAECgUJBwABLgAFFAUJDQALAH8YAA==.零度可乐:BAABLgAFFH8FAAMHAAUJzxehEQBaAQAHAAQJzxehEQBaAQAIAAEJAABpHAAhAAAAAA==.',
['零时']='零时迷子:BAAALgAFFAMJBAABLgAFFAQJDwADAIUXAA==.',
['零碎']='零碎记忆:BAAALgAFFAIJAgAAAA==.',
['雷妮']='雷妮亚拉:BAAALgAFFAEJAQAAAA==.',
['雷霆']='雷霆法神:BAAALgAECgcJCgAAAA==.',
['霜冷']='霜冷长河:BAAALgAECgEJAQAAAA==.',
['霜竹']='霜竹清影:BAAALgADCgcJCAAAAA==.',
['露奈']='露奈雅拉:BAAALgAECgMJAwAAAA==.',
['露西']='露西艾拉:BAAALgAFFAQJBAAAAA==.',
['青墨']='青墨:BAAALgADCgQJBAAAAA==.',
['青柠']='青柠喵:BAAALgAECgEJAQAAAA==.青柠泡茶:BAAALgAECgYJEQABLgAECgYJFQABALkeAA==.',
['青落']='青落:BAABLgAFFH8GAAMKAAIJ2Aa8DACJAAAKAAIJ2Aa8DACJAAAfAAEJ0gCGOwA7AAAAAA==.',
['青锋']='青锋:BAAALgAECgkJCQAAAA==.',
['非酋']='非酋猎:BAAALgAFFAIJAgAAAA==.',
['顶级']='顶级龙套:BAAALgAECggJDQAAAA==.',
['顿顿']='顿顿有肉吃:BAAALgAECgQJAwAAAA==.',
['颠勺']='颠勺糕手:BAAALgAECgEJAQAAAA==.',
['风之']='风之力祈福:BAAALgADCgEJAQAAAA==.',
['风吹']='风吹过的日子:BAABLgAECn8ZAAIHAAcJZSCqDADVAQAHAAcJZSCqDADVAQAAAA==.',
['风栖']='风栖月涧:BAAALgAECgEJAQAAAA==.',
['风清']='风清隐旧窗:BAABLgAFFH8IAAIfAAQJMghCEQAbAQAfAAQJMghCEQAbAQAAAA==.',
['风继']='风继续吹:BAAALgAFFAEJAQABLgAFFAYJFQACAIwiAA==.',
['风莲']='风莲:BAACLgAFFH8KAAIcAAQJJRnRBgBmAQAcAAQJJRnRBgBmAQAuAAQKfx4AAhwABwlMIyUMAMwCABwABwlMIyUMAMwCAAAA.',
['风过']='风过谢桃花:BAAALgADCgcJBwAAAA==.',
['风铃']='风铃可兰:BAAALgAECgcJAQAAAA==.',
['风飘']='风飘心:BAAALgADCgQJBAAAAA==.风飘訫:BAAALgAECgQJBQAAAA==.',
['飒飒']='飒飒潵:BAAALgAECgcJEQAAAA==.',
['飞奔']='飞奔的小龙女:BAAALgAECgkJAwAAAA==.',
['飞鱼']='飞鱼苍苍:BAAALgADCgEJAQAAAA==.',
['食神']='食神史蒂芬周:BAAALgAECgMJBQAAAA==.',
['饕餮']='饕餮德古拉:BAAALgAECgkJEQAAAA==.',
['饿了']='饿了会捡垃圾:BAAALgAECgMJAwABLgAFFAQJDwAPAOYmAA==.',
['馒头']='馒头吃米饭:BAAALgAECgQJBAAAAA==.',
['香印']='香印青蹄:BAAALgAFFAIJAgAAAA==.',
['香扇']='香扇坠儿:BAAALgADCgcJBwAAAA==.',
['香浓']='香浓拿铁:BAAALgAECgQJAQAAAA==.香浓芝士:BAAALgAECgEJAQAAAA==.',
['香菜']='香菜貓餅:BAABLgAFFH8JAAIjAAQJnBWoBABYAQAjAAQJnBWoBABYAQAAAA==.',
['骄阳']='骄阳晨曦:BAAALgAECgcJCAAAAA==.',
['骑士']='骑士之勇:BAAALgAECgYJBgAAAA==.',
['骑太']='骑太奶过马路:BAAALgAECgcJBwAAAA==.',
['骑猪']='骑猪撇标枪:BAAALgAECgUJCAAAAA==.',
['骨靈']='骨靈:BAAALgADCgcJDQAAAA==.',
['高冷']='高冷信仰冰:BAABLgAFFH8JAAICAAQJHyCWEQCJAQACAAQJHyCWEQCJAQAAAA==.',
['高拉']='高拉格:BAAALgAECgYJCAAAAA==.',
['鬼兽']='鬼兽:BAAALgAECgYJDQAAAA==.',
['魂天']='魂天帝:BAABLgAFFH8HAAIOAAIJ7iKhCQDPAAAOAAIJ7iKhCQDPAAABLgAFFAQJCQAOAEchAA==.',
['魂归']='魂归献祭:BAAALgADCgEJAQAAAA==.',
['魑丨']='魑丨魅:BAAALgAECgQJBAAAAA==.',
['魔剑']='魔剑仙:BAAALgAFFAIJAgAAAA==.',
['魔域']='魔域天使:BAACLgAFFH8KAAMWAAQJZQavAQCgAAATAAMJdgU4JwDgAAAWAAIJPgavAQCgAAAuAAQKfx0ABBMABwl8G008ABsCABMABwkEF008ABsCABUAAwkdEtI9AL0AABYAAwmBG/EFAKcAAAAA.',
['魔法']='魔法少女蛋挞:BAAALgAECgYJCgABLgAFFAQJCwAZAPAhAA==.魔法猫咪喵呜:BAAALgADCgcJCAAAAA==.',
['魔涌']='魔涌小子:BAAALgADCgYJAQABLgAFFAYJDgAkACcTAA==.',
['鱼摆']='鱼摆摆了不起:BAAALgAECgcJBwAAAA==.',
['鱼粥']='鱼粥唱晚:BAAALgAECgQJBwAAAA==.',
['鱼鱼']='鱼鱼宝贝:BAAALgAECgYJDAAAAA==.',
['鲸井']='鲸井令子:BAAALgAECgYJBgAAAA==.',
['鲸鱼']='鲸鱼:BAAALgADCgUJCgAAAA==.',
['鸡蛋']='鸡蛋饼不加糖:BAAALgAECgMJAwAAAA==.',
['鹅啊']='鹅啊鹅:BAAALgAFFAEJAQAAAA==.',
['鹤雪']='鹤雪霏霏:BAAALgADCgEJAQAAAA==.',
['麦狄']='麦狄文:BAAALgADCgUJBQAAAA==.',
['麻辣']='麻辣鱼鳞:BAABLgAECn8ZAAIUAAgJBA4zIADXAQAUAAgJBA4zIADXAQAAAA==.',
['麻麻']='麻麻她戳我:BAAALgAECgYJCgAAAA==.',
['黄昏']='黄昏隐士:BAAALgAFFAIJAgAAAA==.',
['黑人']='黑人酋长:BAAALgAFFAIJAwAAAA==.',
['黑旋']='黑旋风李某:BAACLgAFFH8IAAIfAAMJ+xgaEwANAQAfAAMJ+xgaEwANAQAuAAQKfx4AAh8ACAl0H5I1AEwCAB8ACAl0H5I1AEwCAAAA.',
['黑暗']='黑暗控制者:BAAALgAECgEJAQAAAA==.',
['黑椒']='黑椒牛柳意面:BAAALgAECgkJBwAAAA==.',
['黑洞']='黑洞洞香鸡排:BAABLgAFFH8FAAMLAAMJxwqTFQCuAAALAAIJrwyTFQCuAAAMAAIJFQe0IACRAAAAAA==.',
['黑石']='黑石摇滚:BAAALgAECgEJAQABLgAFFAUJEQADAIAcAA==.',
['黑茉']='黑茉莉:BAAALgADCggJCAAAAA==.',
['黑钥']='黑钥匙鳞片:BAABLgAFFH8IAAMYAAUJ9xLnCQBLAQAYAAQJ3hHnCQBLAQAhAAIJyQM2HQCGAAAAAA==.',
['龍息']='龍息:BAACLgAFFH8KAAMRAAQJNR6oBgCDAQARAAQJ1BuoBgCDAQAaAAEJxhskCgBaAAAuAAQKfx4ABBoABwn5IcMLAOUBABoABQkHIsMLAOUBABEABQlfIQg6AL4BABIAAgmIIK4PAKwAAAAA.',
['龘咕']='龘咕咕龘:BAAALgAECgEJAQAAAA==.',
['龙傲']='龙傲天打响指:BAAALgADCgQJBAAAAA==.',
['龙刃']='龙刃出鞘:BAABLgAECn8YAAMYAAYJvBJxIQBwAQAYAAYJvBJxIQBwAQAhAAMJaw6FTQCaAAAAAA==.',
['龙飞']='龙飞扬:BAABLgAECn8VAAIOAAYJoRNQEAD5AAAOAAYJoRNQEAD5AAAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
