local V2_TAG_NUMBER = 4

---@param v2Rankings ProviderProfileV2Rankings
---@return ProviderProfileSpec
local function convertRankingsToV1Format(v2Rankings, difficultyId, sizeId)
	---@type ProviderProfileSpec
	local v1Rankings = {}
	v1Rankings.progress = v2Rankings.progressKilled
	v1Rankings.total = v2Rankings.progressPossible
	v1Rankings.average = v2Rankings.bestAverage
	v1Rankings.spec = v2Rankings.spec
	v1Rankings.asp = v2Rankings.allStarPoints
	v1Rankings.rank = v2Rankings.allStarRank
	v1Rankings.difficulty = difficultyId
	v1Rankings.size = sizeId

	v1Rankings.encounters = {}
	for id, encounter in pairs(v2Rankings.encountersById) do
		v1Rankings.encounters[id] = {
			kills = encounter.kills,
			best = encounter.best,
		}
	end

	return v1Rankings
end

---Convert a v2 profile to a v1 profile
---@param v2 ProviderProfileV2
---@return ProviderProfile
local function convertToV1Format(v2)
	---@type ProviderProfile
	local v1 = {}
	v1.subscriber = v2.isSubscriber
	v1.perSpec = {}

	if v2.summary ~= nil then
		v1.progress = v2.summary.progressKilled
		v1.total = v2.summary.progressPossible
		v1.totalKillCount = v2.summary.totalKills
		v1.difficulty = v2.summary.difficultyId
		v1.size = v2.summary.sizeId
	else
		local bestSection = v2.sections[1]
		v1.progress = bestSection.anySpecRankings.progressKilled
		v1.total = bestSection.anySpecRankings.progressPossible
		v1.average = bestSection.anySpecRankings.bestAverage
		v1.totalKillCount = bestSection.totalKills
		v1.difficulty = bestSection.difficultyId
		v1.size = bestSection.sizeId
		v1.anySpec = convertRankingsToV1Format(bestSection.anySpecRankings, bestSection.difficultyId, bestSection.sizeId)
		for i, rankings in pairs(bestSection.perSpecRankings) do
			v1.perSpec[i] = convertRankingsToV1Format(rankings, bestSection.difficultyId, bestSection.sizeId)
		end
		v1.encounters = v1.anySpec.encounters
	end

	if v2.mainCharacter ~= nil then
		v1.mainCharacter = {}
		v1.mainCharacter.spec = v2.mainCharacter.spec
		v1.mainCharacter.average = v2.mainCharacter.bestAverage
		v1.mainCharacter.difficulty = v2.mainCharacter.difficultyId
		v1.mainCharacter.size = v2.mainCharacter.sizeId
		v1.mainCharacter.progress = v2.mainCharacter.progressKilled
		v1.mainCharacter.total = v2.mainCharacter.progressPossible
		v1.mainCharacter.totalKillCount = v2.mainCharacter.totalKills
	end

	return v1
end

---Parse a single set of rankings from `state`
---@param decoder BitDecoder
---@param state ParseState
---@param lookup table<number, string>
---@return ProviderProfileV2Rankings
local function parseRankings(decoder, state, lookup)
	---@type ProviderProfileV2Rankings
	local result = {}
	result.spec = decoder.decodeString(state, lookup)
	result.progressKilled = decoder.decodeInteger(state, 1)
	result.progressPossible = decoder.decodeInteger(state, 1)
	result.bestAverage = decoder.decodePercentileFixed(state)
	result.allStarRank = decoder.decodeInteger(state, 3)
	result.allStarPoints = decoder.decodeInteger(state, 2)

	local encounterCount = decoder.decodeInteger(state, 1)
	result.encountersById = {}
	for i = 1, encounterCount do
		local id = decoder.decodeInteger(state, 4)
		local kills = decoder.decodeInteger(state, 2)
		local best = decoder.decodeInteger(state, 1)
		local isHidden = decoder.decodeBoolean(state)

		result.encountersById[id] = { kills = kills, best = best, isHidden = isHidden }
	end

	return result
end

---Parse a binary-encoded data string into a provider profile
---@param decoder BitDecoder
---@param content string
---@param lookup table<number, string>
---@param formatVersion number
---@return ProviderProfile|ProviderProfileV2|nil
local function parse(decoder, content, lookup, formatVersion) -- luacheck: ignore 211
	-- For backwards compatibility. The existing addon will leave this as nil
	-- so we know to use the old format. The new addon will specify this as 2.
	formatVersion = formatVersion or 1
	if formatVersion > 2 then
		return nil
	end

	---@type ParseState
	local state = { content = content, position = 1 }

	local tag = decoder.decodeInteger(state, 1)
	if tag ~= V2_TAG_NUMBER then
		return nil
	end

	---@type ProviderProfileV2
	local result = {}
	result.isSubscriber = decoder.decodeBoolean(state)
	result.summary = nil
	result.sections = {}
	result.progressOnly = false
	result.mainCharacter = nil

	local sectionsCount = decoder.decodeInteger(state, 1)
	if sectionsCount == 0 then
		---@type ProviderProfileV2Summary
		local summary = {}
		summary.zoneId = decoder.decodeInteger(state, 2)
		summary.difficultyId = decoder.decodeInteger(state, 1)
		summary.sizeId = decoder.decodeInteger(state, 1)
		summary.progressKilled = decoder.decodeInteger(state, 1)
		summary.progressPossible = decoder.decodeInteger(state, 1)
		summary.totalKills = decoder.decodeInteger(state, 2)

		result.summary = summary
	else
		for i = 1, sectionsCount do
			---@type ProviderProfileV2Section
			local section = {}
			section.zoneId = decoder.decodeInteger(state, 2)
			section.difficultyId = decoder.decodeInteger(state, 1)
			section.sizeId = decoder.decodeInteger(state, 1)
			section.partitionId = decoder.decodeInteger(state, 1) - 128
			section.totalKills = decoder.decodeInteger(state, 2)

			local specCount = decoder.decodeInteger(state, 1)
			section.anySpecRankings = parseRankings(decoder, state, lookup)

			section.perSpecRankings = {}
			for j = 1, specCount - 1 do
				local specRankings = parseRankings(decoder, state, lookup)
				table.insert(section.perSpecRankings, specRankings)
			end

			table.insert(result.sections, section)
		end
	end

	local hasMainCharacter = decoder.decodeBoolean(state)
	if hasMainCharacter then
		---@type ProviderProfileV2MainCharacter
		local mainCharacter = {}
		mainCharacter.zoneId = decoder.decodeInteger(state, 2)
		mainCharacter.difficultyId = decoder.decodeInteger(state, 1)
		mainCharacter.sizeId = decoder.decodeInteger(state, 1)
		mainCharacter.progressKilled = decoder.decodeInteger(state, 1)
		mainCharacter.progressPossible = decoder.decodeInteger(state, 1)
		mainCharacter.totalKills = decoder.decodeInteger(state, 2)
		mainCharacter.spec = decoder.decodeString(state, lookup)
		mainCharacter.bestAverage = decoder.decodePercentileFixed(state)

		result.mainCharacter = mainCharacter
	end

	local progressOnly = decoder.decodeBoolean(state)
	result.progressOnly = progressOnly

	if formatVersion == 1 then
		return convertToV1Format(result)
	end

	return result
end
--- the utf8 global is not available, so we polyfill utf8.offset so we can correctly find prefixes of utf8 strings
---@param str string
---@param index number
---@return number|nil
local function Utf8Offset(str, index)
	local len = #str

	if index <= 0 or index > len then
		return nil -- Out of bounds
	end

	-- Move forward to the nth character
	local count = 0
	for i = 1, len do
		local byte = string.byte(str, i)
		local isContinuationByte = byte >= 128 and byte < 192
		if not isContinuationByte then
			count = count + 1
			if count == index then
				return i
			end
		end
	end

	return nil -- If the nth character is not found
end

---@param table table<string, string> raw data table with character name prefixes as keys
---@param length number the number of complete characters to include in the prefix
---@return fun(characterName: string):string|nil getChunk function to retrieve a character chunk by prefix using a complete character name
local function getChunkLookup(table, length)
	return function(characterName)
		local startOfNextCharacter = Utf8Offset(characterName, length + 1)

		local prefix
		if startOfNextCharacter == nil then
			prefix = characterName
		else
			prefix = string.sub(characterName, 1, startOfNextCharacter - 1)
		end

		return table[prefix]
	end
end

local lookup = {'Evoker-Devastation','Rogue-Assassination','Rogue-Subtlety','Rogue-Outlaw','DeathKnight-Unholy','Warlock-Demonology','DemonHunter-Devourer','DemonHunter-Havoc','Warlock-Affliction','Unknown-Unknown','Warlock-Destruction','Monk-Mistweaver','Monk-Brewmaster','DeathKnight-Blood','Mage-Frost','Paladin-Retribution','Priest-Holy','Druid-Balance','Evoker-Preservation','Evoker-Augmentation','Druid-Restoration','Warrior-Fury','Monk-Windwalker','Warrior-Arms','Hunter-BeastMastery','Hunter-Marksmanship','Warrior-Protection','Hunter-Ranged','Priest-Shadow','Priest-Discipline','Hunter-Survival','Shaman-Restoration','Paladin-Protection','Shaman-Elemental','Paladin-Holy','Druid-Guardian','DeathKnight-Frost',}
local provider = {region='CN',realm='塞拉摩',name='CN',type='weekly',zone=46,date='2026-04-25',data={Ab='Abba:BAAALgAECgEJAQAAAA==.',
Ae='Aerynsff:BAAALgAECgYJBgABLgAFFAMJBQABAL4LAA==.',
Ak='Akims:BAAALgAECgQJBgAAAA==.',
Al='Alievve:BAACLgAFFH8VAAQCAAQJVSL1AgDYAAADAAMJRxuNCwAsAQACAAIJNyL1AgDYAAAEAAQJTBbQAQBZAAAuAAQKfzQABAMABwmzIxAOAL4CAAMABwngIRAOAL4CAAQAAQk7HcAEAFgAAAIAAQkoHCcaAFgAAAAA.',
Am='Amana:BAAALgAECgUJBQAAAA==.',
An='Angelbeats:BAABLgAFFH8FAAIFAAMJ4QsbLQDnAAAFAAMJ4QsbLQDnAAAAAA==.Annehathawa:BAAALgAECgYJEAAAAA==.Anniel:BAABLgAFFH8FAAIGAAIJEyOqKQDMAAAGAAIJEyOqKQDMAAAAAA==.Anonchihaya:BAAALgAECgYJCgAAAA==.',
As='Ashstar:BAAALgADCgMJBgAAAA==.',
Au='Augustin:BAAALgAECgcJEQAAAA==.Austintun:BAABLgAECn8UAAMHAAcJdB/2MAA3AgAHAAcJdB/2MAA3AgAIAAYJuQyHNwAnAQAAAA==.',
Be='Bellania:BAAALgAECgYJBQAAAA==.',
Bl='Blacksickle:BAAALgAECgEJAQAAAA==.Blazekid:BAABLgAFFH8OAAMGAAQJwBnvFQC1AAAGAAQJwBnvFQC1AAAJAAEJNw32BQBUAAAAAA==.Bluecourse:BAAALgAFFAIJAwAAAA==.Bluetrp:BAAALgAECgQJBAAAAA==.',
Bo='Bomshakalaka:BAAALgAECgEJAQAAAA==.Bornthisway:BAAALgAECgQJBAAAAA==.',
Br='Bruce:BAAALgADCgEJAQAAAA==.',
Bu='Bucketsama:BAAALgAECgQJBAAAAA==.',
Ca='Cassiebee:BAAALgAECggJAwAAAA==.Castorice:BAAALgAFFAIJAgAAAA==.Catone:BAAALgADCgkJDwABLgAECgYJBgAKAAAAAA==.Catura:BAAALgAECgQJBQAAAA==.',
Cc='Cchengi:BAAALgAECgYJCQAAAA==.',
Ch='Chase:BAAALgAECgUJBQAAAA==.Chastiser:BAAALgAECgcJAQAAAA==.Chocobonbon:BAEALgAFFAMJBAABLgAFFAQJCAALAGYTAA==.Christknight:BAAALgAFFAIJAgAAAA==.',
Ci='Cic:BAAALgAECgcJEgAAAA==.Cigarmojito:BAABLgAFFH8JAAIMAAUJ4B6ZDgCzAAAMAAUJ4B6ZDgCzAAAAAA==.',
Co='Cojio:BAAALgAFFAEJAQAAAA==.Constan:BAAALgAECgQJBQAAAA==.Cowryws:BAABLgAFFH8HAAINAAMJmxQlEQD1AAANAAMJmxQlEQD1AAAAAA==.',
Cr='Credos:BAAALgAECgcJEAAAAA==.',
Da='Daina:BAAALgAECgEJAQABLgAECgcJFgADAG0aAA==.',
De='Deathkzz:BAABLgAECn8WAAIFAAYJDSGTZADGAQAFAAYJDSGTZADGAQAAAA==.Demonhzz:BAAALgAECgIJAgABLgAECgYJFgAFAA0hAA==.',
Dh='Dheck:BAAALgAFFAEJAQAAAA==.',
Di='Divineoxts:BAAALgAECgEJAQAAAA==.',
Do='Doubeninth:BAAALgAECgIJAwAAAA==.',
Du='Duandk:BAABLgAECn8UAAIFAAgJEBraPQBAAgAFAAgJEBraPQBAAgAAAA==.Dubc:BAAALgADCgEJAQAAAA==.',
Ep='Ephoenix:BAAALgAECgcJBwAAAA==.',
Er='Erroruname:BAAALgADCgEJAQAAAA==.',
Es='Escapistnemo:BAAALgAECgQJDQAAAA==.',
Ev='Evais:BAACLgAFFH8PAAIOAAQJqweYBADrAAAOAAQJqweYBADrAAAuAAQKfxQAAg4ABwnYB70lABEBAA4ABwnYB70lABEBAAAA.Everlost:BAAALgAECgEJAQAAAA==.',
Fa='Fantasystar:BAAALgADCgkJCQAAAA==.Faplatinum:BAAALgAECgIJBAAAAA==.',
Fr='Fraux:BAAALgAECgIJAgAAAA==.Frostfox:BAABLgAECn8XAAIPAAgJegr8kACxAQAPAAgJegr8kACxAQAAAA==.',
Fu='Fuhua:BAACLgAFFH8IAAIQAAMJsw6iFgD3AAAQAAMJsw6iFgD3AAAuAAQKfx8AAhAABwlwHD04AEICABAABwlwHD04AEICAAAA.Fuker:BAAALgAECgEJAQAAAA==.',
Ga='Gandaofu:BAAALgAECgEJAgAAAA==.Gaosir:BAABLgAFFH8FAAIHAAMJFQrvHgDgAAAHAAMJFQrvHgDgAAAAAA==.Gatsbyfight:BAAALgAECggJBwAAAA==.Gavinsecond:BAAALgAFFAIJAwAAAA==.',
Gc='Gcc:BAAALgAECgYJCQAAAA==.',
Ha='Happyfox:BAABLgAECn8gAAIRAAgJCSMeBAATAwARAAgJCSMeBAATAwAAAA==.',
Ho='Holyash:BAAALgAECgEJAQAAAA==.Hotshotve:BAAALgAECgEJAQAAAA==.',
Im='Imperial:BAAALgADCgUJBQAAAA==.',
In='Invinci:BAAALgAECgEJAQAAAA==.',
Ji='Jieshao:BAAALgAECgEJAQAAAA==.',
Jj='Jjd:BAAALgAECgYJDwAAAA==.',
Jo='Joli:BAAALgAECgEJAQAAAA==.',
Ju='Justingguand:BAAALgAECgkJCQAAAA==.',
Ka='Kanamomonogi:BAABLgAFFH8FAAIGAAMJvA7+JADuAAAGAAMJvA7+JADuAAAAAA==.',
Kc='Kcolrawlive:BAABLgAFFH8HAAMGAAMJSg0ZGQCkAAAGAAIJARMZGQCkAAALAAEJ2wG2GgBDAAAAAA==.',
Ke='Keeheechul:BAAALgAECgYJBgAAAA==.',
Kh='Khalilfong:BAACLgAFFH8FAAISAAQJ0RdvBwBqAQASAAQJ0RdvBwBqAQAuAAQKfxoAAhIACAlgHwYNAMgCABIACAlgHwYNAMgCAAAA.',
Ki='Kissrain:BAAALgAECgEJAQAAAA==.',
Ko='Kokora:BAAALgAECgYJBwAAAA==.',
Ky='Kyoku:BAAALgAECgcJDwAAAA==.',
La='Lanternn:BAAALgAECgcJDwAAAA==.Laoeryuovo:BAAALgAECggJDgAAAA==.Laughiing:BAACLgAFFH8KAAMTAAQJIgEhDgD2AAATAAQJIgEhDgD2AAAUAAMJ2ghvDQCdAAAuAAQKfxcAAxQACQmqFVgPAIECABQACQmqFVgPAIECABMABwlrAbswAOoAAAAA.',
Le='Leozy:BAAALgAECgEJAQAAAA==.',
Li='Lichkingcave:BAABLgAFFH8FAAIFAAIJmxnMOACqAAAFAAIJmxnMOACqAAAAAA==.Lightblues:BAAALgAECgEJAQAAAA==.Likejennie:BAAALgAFFAIJBAAAAA==.Lilith:BAAALgADCgIJAgAAAA==.Liltits:BAAALgAECgYJBgAAAA==.',
Lk='Lkppig:BAAALgAECgMJBQAAAA==.',
Lr='Lrper:BAAALgADCgYJBgAAAA==.',
Lu='Luckypigg:BAACLgAFFH8NAAMLAAQJIiGNCQC/AAALAAMJPBmNCQC/AAAGAAMJPx6mLQC5AAAuAAQKfxsAAwYACAlDITZAAA0CAAYABgnDHjZAAA0CAAsABQneIEwfAFcBAAAA.Luckyppig:BAAALgAFFAEJAQAAAA==.Lukepresentv:BAABLgAFFH8KAAIVAAQJbyGoAgCAAQAVAAQJbyGoAgCAAQAAAA==.',
Ly='Lyre:BAAALgAECgYJBgAAAA==.',
Ma='Maginá:BAAALgAFFAIJAwAAAA==.Maiooizumi:BAECLgAFFH8IAAILAAQJZhMQBABSAQALAAQJZhMQBABSAQAuAAQKfxUAAgsACAlAIOkCANECAAsACAlAIOkCANECAAAA.Margiela:BAAALgAECgIJAgAAAA==.Mawuka:BAABLgAFFH8LAAIWAAQJOiBuBQCbAQAWAAQJOiBuBQCbAQAAAA==.Maylier:BAAALgAECgEJAQAAAA==.',
Me='Merlinn:BAAALgAFFAEJAgAAAA==.',
Mi='Miol:BAAALgAECgIJAgAAAA==.',
Mo='Mongolianman:BAAALgADCgIJAgAAAA==.',
Ne='Neojin:BAAALgAECgcJDQAAAA==.',
Ni='Nightriver:BAAALgAECgcJCAAAAA==.Niklau:BAAALgADCggJCQAAAA==.Niuniuzxc:BAACLgAFFH8GAAIPAAMJohdOJwAWAQAPAAMJohdOJwAWAQAuAAQKfxwAAg8ACAl9IQQhAO8CAA8ACAl9IQQhAO8CAAAA.Niusniu:BAAALgAFFAIJAgAAAA==.',
No='Novacainex:BAAALgADCgEJAQAAAA==.',
Nt='Ntree:BAAALgAECgQJBgAAAA==.',
Oo='Ooyyl:BAAALgAFFAQJBAAAAA==.Ooyyll:BAAALgAFFAQJBAAAAA==.',
Ot='Ottll:BAAALgADCgcJBAAAAA==.',
Ou='Ouyangyl:BAABLgAFFH8HAAIPAAUJJhUQCgDOAQAPAAUJJhUQCgDOAQABLgAFFAUJCgAPAGkOAA==.Ouyangyll:BAABLgAFFH8IAAIPAAQJiAvUIABBAQAPAAQJiAvUIABBAQABLgAFFAUJCgAPAGkOAA==.Ouyangyyl:BAAALgAECgYJAwAAAA==.',
Oy='Oyyli:BAAALgAFFAMJBAAAAA==.Oyylii:BAAALgAECgIJAgAAAA==.Oyyll:BAABLgAFFH8IAAIPAAQJyhAvJAAmAQAPAAQJyhAvJAAmAQAAAA==.',
Pe='Pepsl:BAAALgADCgIJAgAAAA==.Petskeeper:BAAALgAECgMJAwAAAA==.',
Pi='Piatinum:BAAALgAECgMJAwAAAA==.Pinkhx:BAAALgAECgcJCAAAAA==.Piy:BAAALgAECgYJCwAAAA==.',
Pl='Playerhkiixh:BAAALgAECgEJAwABLgAFFAIJAgAKAAAAAA==.',
Pu='Punishes:BAAALgADCgcJBwAAAA==.Pupo:BAAALgAECgMJCAAAAA==.',
Qi='Qilko:BAAALgADCgEJAQAAAA==.',
Qu='Quanr:BAAALgAECgQJBQAAAA==.',
Ra='Rainbow:BAAALgAECgQJBAAAAA==.Ranko:BAABLgAECn8VAAMGAAgJtR/fDgADAwAGAAgJtR/fDgADAwALAAEJAABgZgBDAAAAAA==.Rayyawarlock:BAAALgAECgMJAwAAAA==.',
Re='Reawaker:BAABLgAECn8XAAIXAAcJzx4EEgBnAgAXAAcJzx4EEgBnAgAAAA==.Rebreeze:BAAALgAECgYJEAAAAA==.',
Ro='Rocky:BAAALgAECgEJAQAAAA==.Rong:BAAALgAECgUJBQAAAA==.',
Sa='Sadie:BAAALgAECgMJBgAAAA==.Satsuki:BAAALgAECgMJAgAAAA==.',
Sb='Sbwifi:BAABLgAFFH8KAAIHAAQJ+iSuBgC4AQAHAAQJ+iSuBgC4AQABLgAFFAUJCgABAEsgAA==.',
Sh='Shakedk:BAAALgAECgEJAQAAAA==.Shakez:BAAALgAECgEJAwAAAA==.Shenleg:BAAALgAECgEJAQAAAA==.Shink:BAAALgAECgYJBgAAAA==.Shrikebird:BAAALgAECgMJAwAAAA==.',
Si='Siglud:BAACLgAFFH8HAAIYAAMJNxPgAwADAQAYAAMJNxPgAwADAQAuAAQKfyoAAhgACAncGh4BACMCABgACAncGh4BACMCAAAA.Sisyphos:BAAALgAECgMJAwAAAA==.',
Sk='Skimo:BAABLgAECn8WAAIPAAYJKR+7XAAkAgAPAAYJKR+7XAAkAgAAAA==.',
So='Solitudinis:BAABLgAECn8bAAINAAcJ3CUxCQD1AgANAAcJ3CUxCQD1AgAAAA==.Sommnus:BAAALgAECgQJCQAAAA==.Soulmatec:BAAALgAECgYJDAAAAA==.',
Sp='Spiriter:BAAALgAECgMJAwAAAA==.',
St='Staw:BAABLgAECn8VAAIWAAkJMA59RwCGAQAWAAkJMA59RwCGAQAAAA==.',
Sw='Sweetbaby:BAAALgAECgUJCAAAAA==.',
Te='Teddymeow:BAAALgAFFAMJAwABLgAFFAUJCwAHAPMZAA==.Teddyuwu:BAABLgAFFH8LAAIHAAUJ8xlQBgC/AQAHAAUJ8xlQBgC/AQAAAA==.',
Th='Thesc:BAAALgAFFAEJAQAAAA==.',
Tm='Tmt:BAABLgAFFH8HAAIFAAMJ4R2RHwAdAQAFAAMJ4R2RHwAdAQAAAA==.',
Va='Vaelistra:BAAALgADCgIJAgAAAA==.',
Vl='Vll:BAAALgAECgEJAQAAAA==.',
Vo='Volrayball:BAEALgAFFAEJAQABLgAFFAMJBwAPAOEWAA==.Volraybelle:BAEBLgAFFH8HAAIPAAMJ4RbXKgAKAQAPAAMJ4RbXKgAKAQAAAA==.',
Wa='Waffle:BAAALgADCgIJAgAAAA==.Warlockzz:BAAALgADCgEJAQAAAA==.',
We='Weissery:BAABLgAECn8aAAMZAAgJWxeyIgA1AgAZAAgJGRWyIgA1AgAaAAUJeBM5SQAuAQAAAA==.',
Wo='Wodiwodi:BAAALgAECgMJBQAAAA==.Wonderfuluu:BAAALgAFFAEJAQAAAA==.',
Ya='Yahir:BAEALgAFFAIJAwABLgAFFAMJBwAPAOEWAA==.',
Ye='Yee:BAAALgAECgEJAgAAAA==.',
Yi='Yildiz:BAABLgAFFH8JAAMDAAQJyhfYBgByAQADAAQJyhfYBgByAQACAAEJAwGcBwBGAAAAAA==.',
Ze='Zerotwo:BAAALgAECgEJAQAAAA==.',
Zr='Zre:BAAALgADCgIJAgAAAA==.',
Zu='Zujiayang:BAAALgAECgQJBAAAAA==.',
['Âã']='Âãäåäå:BAABLgAFFH8JAAIFAAQJtCNMBQCtAQAFAAQJtCNMBQCtAQAAAA==.',
['一人']='一人杀一群:BAAALgAECgIJAwAAAA==.',
['一今']='一今:BAAALgAECgMJAwAAAA==.',
['一介']='一介散人:BAAALgADCgEJAQAAAA==.',
['一切']='一切皆有救赎:BAAALgAECgEJAQAAAA==.',
['一力']='一力担丶怒风:BAAALgADCgEJAQAAAA==.',
['一只']='一只大白牛:BAAALgAECgYJCgAAAA==.',
['一圣']='一圣骑:BAAALgAECggJEwAAAA==.',
['一念']='一念初心:BAAALgAECgEJAQAAAA==.',
['一捧']='一捧赤砂:BAAALgADCgEJAQAAAA==.',
['一枝']='一枝鱼花花:BAAALgADCgYJBgAAAA==.',
['一栗']='一栗丶:BAAALgAECgYJAwAAAA==.',
['一直']='一直生病的丘:BAAALgAECgIJAgAAAA==.',
['一粒']='一粒糖豆:BAAALgAECggJCAAAAA==.',
['一里']='一里一丹黯:BAAALgAECgYJCgAAAA==.',
['一黎']='一黎明破晓一:BAAALgAECgEJAQAAAA==.',
['丁真']='丁真骑马射箭:BAAALgAECgYJCQAAAA==.',
['七岁']='七岁的萌萌:BAAALgAFFAEJAgAAAA==.',
['七性']='七性鱼乐:BAAALgAECgUJBgAAAA==.',
['七月']='七月晚风凉:BAAALgAECgQJBQAAAA==.',
['七秀']='七秀叶芷青:BAAALgAECgYJBgAAAA==.',
['万灵']='万灵之召:BAAALgAECgQJBQAAAA==.万灵星火:BAAALgAECgEJAQAAAA==.',
['万能']='万能的小黑:BAAALgAECgUJBQAAAA==.',
['万贱']='万贱归宗:BAAALgAECgUJBAAAAA==.',
['三两']='三两银够不够:BAAALgAECgUJCQAAAA==.',
['三千']='三千莲心火:BAAALgAECgEJAQAAAA==.',
['三對']='三對月神牧湿:BAAALgAECgYJAQAAAA==.',
['三尺']='三尺血兽来了:BAABLgAFFH8JAAIFAAMJiAxYLADqAAAFAAMJiAxYLADqAAAAAA==.',
['三灬']='三灬炅:BAAALgAECgYJCAAAAA==.',
['三超']='三超预期必买:BAAALgADCgEJAQAAAA==.',
['三重']='三重德华:BAAALgAECgQJBAAAAA==.',
['上岸']='上岸先忘本:BAAALgAECgEJAQAAAA==.',
['不丶']='不丶制裁:BAAALgAFFAEJAQAAAA==.不丶恐惧:BAAALgADCgcJBwAAAA==.',
['不似']='不似个人:BAAALgAECgUJBgAAAA==.不似是人:BAAALgADCgMJAwAAAA==.',
['不加']='不加氰胺:BAAALgAFFAIJAgAAAA==.',
['不奶']='不奶我就骂:BAACLgAFFH8OAAMLAAQJdCOLAAAlAQALAAMJvhqLAAAlAQAGAAIJ9CV/KQDNAAAuAAQKfx4ABAsABgk7JQUdAGYBAAYABQlWI1xXAMIBAAsABAnzIwUdAGYBAAkAAQkAAIIvAD8AAAAA.',
['不小']='不小:BAAALgAECgUJBQAAAA==.',
['不想']='不想带眼罩:BAAALgAFFAEJAQAAAA==.',
['不曾']='不曾:BAABLgAECn8bAAIbAAYJjRk7FwCeAQAbAAYJjRk7FwCeAQAAAA==.',
['不管']='不管粥粥的事:BAAALgAECgMJAwAAAA==.',
['不要']='不要乐奈:BAABLgAECn8kAAISAAgJ4yPIBQA/AwASAAgJ4yPIBQA/AwAAAA==.',
['丑陋']='丑陋亡法:BAAALgAECgYJBgAAAA==.',
['专技']='专技为你而站:BAAALgADCgUJBQAAAA==.',
['东一']='东一剑西一剑:BAAALgAECgYJCwAAAA==.',
['东山']='东山陈奕迅:BAAALgAECgEJAQAAAA==.',
['东风']='东风浩荡丶:BAAALgAECgUJCwAAAA==.',
['丢那']='丢那马:BAAALgAECgIJAgAAAA==.',
['两仪']='两仪未岚:BAAALgADCgcJBgAAAA==.',
['两生']='两生丶契:BAAALgAECgUJBwAAAA==.',
['丨丰']='丨丰川祥子丨:BAAALgAECgYJBgAAAA==.',
['丨安']='丨安欣丨:BAAALgAECgEJAQAAAA==.',
['丨挽']='丨挽丶歌丨:BAAALgADCgEJAQAAAA==.',
['丨春']='丨春丽丨:BAAALgAECgIJAwAAAA==.',
['丨時']='丨時雨:BAAALgAECgYJDAAAAA==.',
['丨荒']='丨荒唐镜丨:BAAALgAECgQJBAAAAA==.',
['丨镜']='丨镜花水月:BAACLgAFFH8MAAMIAAQJxg3sBQD2AAAIAAMJWw7sBQD2AAAHAAEJBwxcNABQAAAuAAQKfxoAAwgABgmCJJoTADcCAAgABgmCJJoTADcCAAcABgmdDzyJABIBAAAA.',
['中秋']='中秋:BAAALgADCgUJBQAAAA==.',
['丶六']='丶六餠:BAAALgADCgIJAgAAAA==.丶六饼:BAAALgAECgUJBgAAAA==.',
['丶千']='丶千川川:BAABLgAFFH8GAAMcAAMJRQ0AAAAAAAAZAAIJxBIAAAAAAAAaAAEJRgIAAAAAAAAAAA==.',
['丶古']='丶古尓丹丶:BAAALgAFFAEJAQAAAA==.',
['丶后']='丶后来:BAAALgAECgQJBgAAAA==.',
['丶圣']='丶圣:BAAALgAECgUJBQAAAA==.',
['丶夜']='丶夜啸:BAAALgAFFAEJAQAAAA==.',
['丶天']='丶天真:BAAALgADCgYJBAAAAA==.',
['丶布']='丶布布:BAAALgAECgMJBAABLgAECggJCAAKAAAAAA==.',
['丶干']='丶干枯大地:BAAALgAECgQJBAAAAA==.',
['丶果']='丶果灬尐冻:BAAALgAECgQJBAAAAA==.',
['丶淡']='丶淡雅香:BAAALgAECgcJBwAAAA==.',
['丶肥']='丶肥肥鲨:BAAALgAECggJCAAAAA==.',
['丶薯']='丶薯灬尐片:BAAALgAECgcJDAAAAA==.',
['丶陌']='丶陌生:BAAALgAECgIJAgAAAA==.',
['丶風']='丶風行者:BAAALgAECgIJAgAAAA==.',
['丶马']='丶马小战:BAACLgAFFH8FAAMbAAIJ1xHSCwCMAAAbAAIJ1xHSCwCMAAAWAAEJGRGdIABUAAAuAAQKfxQAAxYACQlXGr4iAD8CABYACAnhF74iAD8CABsABQkEGLIbAG0BAAAA.丶马鞭马蛋:BAABLgAFFH8KAAIFAAMJdx2OJAADAQAFAAMJdx2OJAADAQAAAA==.',
['丸子']='丸子路痴:BAAALgAFFAEJAQAAAA==.',
['举公']='举公:BAACLgAFFH8JAAMdAAQJ+BCGBwBPAQAdAAQJ+BCGBwBPAQAeAAIJqhHdEwCXAAAuAAQKfxcAAx0ACAkmIgcHABoDAB0ACAkmIgcHABoDAB4AAQkGJQpPAFQAAAAA.',
['丿子']='丿子弹:BAAALgAECgQJAgAAAA==.丿子萨:BAAALgAECgEJAQAAAA==.',
['丿混']='丿混沌黑魔导:BAAALgADCgIJAgAAAA==.',
['丿耗']='丿耗子尾汁丶:BAAALgAECgEJAQAAAA==.',
['丿逍']='丿逍遥:BAAALgAECgEJAQAAAA==.',
['乂清']='乂清风乂:BAAALgAECgEJAQAAAA==.乂清风乄术:BAAALgAECgIJAgAAAA==.',
['乄丶']='乄丶德:BAAALgAECgYJBgAAAA==.',
['乄清']='乄清風乂:BAAALgAECgcJCgAAAA==.乄清风丶:BAAALgAFFAIJAgAAAA==.乄清风乄:BAAALgAECgIJAgAAAA==.',
['义勇']='义勇狄:BAAALgAECgYJBgAAAA==.',
['义薄']='义薄雲天:BAAALgAECgEJAQAAAA==.',
['乌尔']='乌尔貝萨:BAAALgAECgIJAwAAAA==.',
['乌索']='乌索普丶丶:BAAALgADCgMJAwAAAA==.',
['乔夭']='乔夭夭:BAAALgADCgEJAQAAAA==.',
['乔治']='乔治你干嘛呢:BAAALgADCgUJBQAAAA==.',
['乙丑']='乙丑:BAAALgAECgIJAgAAAA==.',
['九曜']='九曜:BAAALgAECgEJAwAAAA==.',
['书生']='书生不读书:BAABLgAECn8YAAMaAAgJKhgCHgAzAgAaAAgJKhgCHgAzAgAfAAEJRxMbLQA+AAAAAA==.书生想读书:BAAALgAECggJCAAAAA==.书生爱读书:BAAALgADCgYJBgAAAA==.',
['乱世']='乱世佳人:BAAALgAECgYJCAAAAA==.乱世如枫菲:BAAALgAECgUJCAAAAA==.乱世如枫飞:BAAALgAECgYJAgAAAA==.',
['乱琦']='乱琦琦:BAAALgAECgIJAgAAAA==.',
['了不']='了不起的小林:BAAALgADCgYJBgAAAA==.',
['二代']='二代目重生:BAAALgAECgQJBAAAAA==.',
['二臣']='二臣贼子:BAAALgAECgQJBgAAAA==.',
['二虎']='二虎:BAAALgAECgQJBAAAAA==.',
['云心']='云心无我:BAAALgAECgEJAQAAAA==.',
['云霄']='云霄破击:BAAALgAECgQJCgAAAA==.',
['亓韩']='亓韩:BAAALgAECggJDwAAAA==.',
['五分']='五分熟比较好:BAAALgAECgYJCgAAAA==.',
['亖季']='亖季稻:BAAALgAECgYJCQAAAA==.',
['亚托']='亚托克斯文:BAAALgAFFAEJAgAAAA==.',
['亚瑟']='亚瑟兰斯洛特:BAAALgAECgEJAgAAAA==.',
['亞里']='亞里安:BAAALgADCgcJBwAAAA==.',
['亡晴']='亡晴之暮:BAAALgAECgMJAwAAAA==.',
['亦季']='亦季:BAAALgAECgYJBgAAAA==.',
['享耳']='享耳木风:BAABLgAECn8XAAIgAAcJuxisJgD4AQAgAAcJuxisJgD4AQAAAA==.',
['亮闪']='亮闪闪的翅膀:BAAALgAECgIJAgAAAA==.',
['亲爱']='亲爱的小甜橙:BAAALgAECgIJAwAAAA==.',
['人小']='人小输出大:BAAALgAECgUJBQAAAA==.',
['人没']='人没了:BAAALgAECgYJCwAAAA==.',
['今天']='今天不打猎了:BAAALgAECgYJCAAAAA==.今天吃面了吗:BAAALgAECgcJBgAAAA==.',
['今晚']='今晚我来传菜:BAAALgAFFAEJAQAAAA==.',
['今浠']='今浠:BAAALgAECgEJAQAAAA==.',
['他乡']='他乡遇古交:BAAALgADCgQJBQAAAA==.',
['他做']='他做到了:BAAALgAECgQJBQABLgAFFAEJAQAKAAAAAA==.',
['付卿']='付卿:BAAALgAFFAQJBAAAAA==.',
['代达']='代达洛斯之殇:BAAALgAECgYJCgAAAA==.',
['以吻']='以吻封唇:BAAALgAECgIJAgAAAA==.',
['以太']='以太赞颂章:BAAALgAECgQJBAABLgAECgYJDAAKAAAAAA==.',
['伊热']='伊热陆零:BAABLgAFFH8GAAINAAQJqBwuBgBxAQANAAQJqBwuBgBxAQAAAA==.',
['伊瑟']='伊瑟瑞丶月影:BAAALgADCgQJBAAAAA==.',
['伊耿']='伊耿二世:BAAALgAFFAEJAQAAAA==.',
['伊蒙']='伊蒙利牛丹:BAAALgADCgEJAQAAAA==.',
['伍德']='伍德术:BAAALgAECgUJBwAAAA==.',
['优雅']='优雅的骨头:BAAALgADCgkJAQAAAA==.优雅的魔术师:BAAALgAECgUJCgAAAA==.优雅骨头:BAAALgAECgQJBAAAAA==.',
['会飞']='会飞的沙:BAAALgAECgQJBAAAAA==.',
['伤年']='伤年如此:BAAALgAFFAYJAQAAAA==.',
['伽陵']='伽陵频迦:BAAALgAECgYJDwAAAA==.',
['佛三']='佛三爪:BAAALgAECgQJBwAAAA==.',
['你也']='你也很业余哦:BAACLgAFFH8UAAMWAAYJ3SH8AQDeAQAWAAUJKyT8AQDeAQAYAAIJdR5QBABxAAAuAAQKfyEAAhYACQkpJa8AANkDABYACQkpJa8AANkDAAAA.',
['你是']='你是猪吗:BAAALgAECgYJBgAAAA==.',
['你的']='你的推推棒:BAAALgAECgQJBgAAAA==.',
['你皮']='你皮任你皮丶:BAAALgAECgYJBgAAAA==.',
['你真']='你真吊丶:BAAALgADCgIJAgAAAA==.',
['你要']='你要加油啊:BAAALgAFFAEJAQABLgAFFAYJDgAYANUkAA==.',
['依水']='依水风痕:BAAALgAECgQJBAAAAA==.',
['便携']='便携式火炉:BAEALgAECggJDwABLgAFFAYJFAAVAJMjAA==.',
['信仰']='信仰下的朝阳:BAAALgAECgMJAwAAAA==.信仰圣光鈀:BAAALgAECgMJAwAAAA==.',
['修川']='修川丶地藏:BAAALgAFFAIJAgAAAA==.',
['俺不']='俺不懂:BAAALgAFFAEJAQAAAA==.',
['俺胡']='俺胡汉三来了:BAAALgADCgMJAwAAAA==.',
['健康']='健康的皮卡丘:BAAALgAECgIJAgAAAA==.',
['傻傻']='傻傻人騎:BAABLgAECn8bAAIQAAcJLxTNGABcAQAQAAcJLxTNGABcAQAAAA==.',
['允川']='允川:BAAALgAECgMJAwAAAA==.',
['光之']='光之右手:BAAALgAECgEJAQAAAA==.',
['光明']='光明与您同在:BAABLgAFFH8GAAIRAAIJXBRnCwCsAAARAAIJXBRnCwCsAAABLgAFFAYJFwAQAN0fAA==.光明赞美调:BAAALgAECgEJAQABLgAECgYJDAAKAAAAAA==.',
['克洛']='克洛伊洁芙:BAAALgAECgcJDQAAAA==.',
['克里']='克里斯桃桃:BAAALgAECgUJBgAAAA==.',
['克鲁']='克鲁维斯:BAAALgAECgUJDQAAAA==.',
['兜胯']='兜胯一正蹬:BAAALgAFFAEJAQAAAA==.',
['全凭']='全凭身法:BAAALgAFFAQJBAAAAA==.',
['六欲']='六欲红尘度:BAAALgAFFAIJBAAAAA==.',
['六灬']='六灬饼:BAAALgADCgUJBQAAAA==.',
['六餠']='六餠:BAAALgAECgUJBQAAAA==.',
['六饼']='六饼:BAAALgADCgUJBQAAAA==.六饼灬:BAAALgADCgUJBQAAAA==.',
['兰亭']='兰亭序:BAAALgAFFAEJAQAAAA==.',
['兰娜']='兰娜瑟尔:BAAALgAECgcJDQAAAA==.',
['兽群']='兽群奔腾:BAAALgAECgIJAgAAAA==.',
['冒着']='冒着雪贴近你:BAAALgAECgUJCgAAAA==.',
['军团']='军团宗师乘风:BAAALgAECgMJAwAAAA==.军团骑士暴风:BAAALgAECgIJAgAAAA==.',
['冠位']='冠位铁炮山上:BAAALgAFFAIJAgABLgAFFAQJBgAXADIQAA==.',
['冥犼']='冥犼:BAAALgADCgEJAQAAAA==.',
['冫水']='冫水紅嗏:BAAALgAECgYJBgAAAA==.',
['冬天']='冬天的奥秘:BAAALgAFFAMJAwAAAA==.',
['冬日']='冬日暖阳:BAAALgAECgUJBgAAAA==.',
['冬熊']='冬熊丷忽悠:BAAALgAECgYJDQABLgAECgcJDwAKAAAAAA==.冬熊丷甜酒:BAAALgAECgcJDwAAAA==.',
['冰冰']='冰冰胖胖:BAAALgAECgEJAQAAAA==.',
['冰吻']='冰吻之淚:BAAALgAECgUJBQABLgAFFAIJBQAGAFcVAA==.',
['冰封']='冰封丷溪谷:BAAALgADCgIJAgAAAA==.',
['冰心']='冰心玉壶:BAAALgAECgYJBwAAAA==.',
['冰枪']='冰枪佬太婆:BAAALgAECgUJCAAAAA==.',
['冰灬']='冰灬奥:BAAALgADCgcJBwAAAA==.',
['冰結']='冰結型蛋丁:BAABLgAFFH8FAAIFAAIJVxTuOgCnAAAFAAIJVxTuOgCnAAAAAA==.',
['冰霜']='冰霜傲骨:BAAALgAECgYJCwAAAA==.',
['冲钅']='冲钅小鬼:BAAALgAFFAIJAgAAAA==.',
['冲锋']='冲锋崴脚战:BAAALgAECgcJBwAAAA==.',
['冷漠']='冷漠之夜:BAAALgAECgYJDQAAAA==.冷漠小鸽:BAAALgAFFAIJAgAAAA==.',
['凌乱']='凌乱天祭:BAAALgAFFAQJBAAAAA==.',
['凌歌']='凌歌:BAAALgAECgcJCgAAAA==.',
['凍檸']='凍檸茶:BAAALgAECgYJEgAAAA==.',
['减糖']='减糖美式:BAAALgADCgYJBgAAAA==.',
['凶猛']='凶猛小恐龙:BAABLgAECn8gAAQeAAcJ1SMWCAC+AgAeAAcJ1SMWCAC+AgARAAcJ+xHSKQCkAQAdAAEJRyUdVgBoAAAAAA==.',
['出逃']='出逃鲨鱼抱枕:BAAALgAECggJCwAAAA==.',
['刀酱']='刀酱的火机子:BAACLgAFFH8VAAIDAAUJXxsWAQCKAQADAAUJXxsWAQCKAQAuAAQKfx0AAgMACAm9IYoKAOkCAAMACAm9IYoKAOkCAAAA.',
['刘正']='刘正又来了:BAAALgAECgIJAwAAAA==.',
['刘达']='刘达夏:BAAALgAFFAEJAQAAAA==.刘达莫:BAAALgAECgYJDgAAAA==.刘达风:BAAALgAFFAEJAQAAAA==.',
['初时']='初时未见:BAABLgAFFH8GAAIFAAIJZx8uOACrAAAFAAIJZx8uOACrAAAAAA==.',
['利廉']='利廉实业:BAAALgAECgIJAgAAAA==.',
['利蒙']='利蒙懂:BAAALgADCgYJBgAAAA==.',
['刹玲']='刹玲音:BAAALgAFFAIJAgAAAA==.',
['剑崎']='剑崎:BAAALgAFFAIJAwAAAA==.',
['剑琅']='剑琅琊:BAAALgADCgEJAQAAAA==.',
['割了']='割了吧都焦了:BAAALgAECgQJBQAAAA==.',
['功夫']='功夫柠檬:BAAALgAECgYJCAAAAA==.',
['加血']='加血小能手:BAAALgADCgEJAQAAAA==.',
['加载']='加载失败:BAABLgAECn8cAAIFAAcJHR2yNgBcAgAFAAcJHR2yNgBcAgAAAA==.',
['北上']='北上北北:BAAALgAECgYJDAAAAA==.',
['北方']='北方:BAAALgADCgQJBAAAAA==.',
['北部']='北部玄驹:BAAALgAECgYJBgAAAA==.',
['北门']='北门刘海柱:BAAALgAFFAIJAwAAAA==.北门外无比帅:BAAALgAECgcJEwAAAA==.北门茅山术:BAAALgAECgYJBgAAAA==.',
['北非']='北非大酋长:BAAALgAFFAEJAQAAAA==.',
['十五']='十五的面包:BAAALgAECgYJDQAAAA==.十五的面包吐:BAAALgAECgMJBAAAAA==.',
['十分']='十分跳跃:BAAALgAECgcJAQAAAA==.',
['千丨']='千丨川:BAAALgAECgcJDgAAAA==.',
['千川']='千川龙:BAACLgAFFH8JAAITAAQJ/QgqDAAmAQATAAQJ/QgqDAAmAQAuAAQKfyQAAhMABwnpFL0XANgBABMABwnpFL0XANgBAAAA.',
['千术']='千术丶:BAABLgAECn8VAAMGAAgJURqdIgCLAgAGAAgJURqdIgCLAgALAAIJcBnORwCXAAABLgAFFAEJAQAKAAAAAA==.',
['千橙']='千橙伊人:BAAALgAECgcJDQAAAA==.',
['千送']='千送伊丶:BAAALgAECgUJCAAAAA==.',
['千野']='千野丶:BAAALgAFFAEJAQAAAA==.',
['半世']='半世花落:BAAALgAECgYJBwAAAA==.',
['半咖']='半咖乀:BAAALgAECgEJAQAAAA==.',
['半夜']='半夜妩媚:BAAALgAECgMJAwAAAA==.',
['半服']='半服不服:BAAALgAECgcJBwAAAA==.',
['华北']='华北川建帼:BAAALgAECgUJBQAAAA==.',
['南北']='南北多歧路:BAAALgAFFAIJAwAAAA==.',
['南瓜']='南瓜粥:BAAALgAECgUJBgAAAA==.南瓜糕:BAAALgADCgYJCAAAAA==.',
['卟可']='卟可以:BAAALgAECgYJBgAAAA==.',
['卡娜']='卡娜不洗脚:BAAALgADCgEJAQAAAA==.',
['卡托']='卡托西卡留斯:BAAALgADCgMJAwAAAA==.',
['卡璞']='卡璞丶哞哞:BAABLgAECn8dAAISAAgJxiEwCAATAwASAAgJxiEwCAATAwAAAA==.卡璞熊熊:BAABLgAECn8WAAMXAAgJwxYpFwAsAgAXAAgJwxYpFwAsAgAMAAUJnQ8FOQAIAQAAAA==.',
['危她']='危她命:BAAALgADCgUJBQAAAA==.',
['原味']='原味阿萨姆:BAAALgAFFAMJBAAAAA==.',
['叁鹿']='叁鹿大頭娃丶:BAAALgAECgUJBgAAAA==.',
['又见']='又见秋天:BAAALgAFFAQJBAAAAA==.',
['双层']='双层芝士汉堡:BAAALgAECgIJAgAAAA==.',
['双月']='双月之殇:BAAALgAECgEJAQAAAA==.',
['发条']='发条地精:BAAALgAFFAIJBAAAAA==.',
['叟泰']='叟泰尔德:BAABLgAFFH8GAAINAAMJNhQiEgDqAAANAAMJNhQiEgDqAAAAAA==.',
['叠角']='叠角龙:BAAALgAECggJEwAAAA==.',
['口实']='口实心扉:BAAALgAECgMJAwAAAA==.',
['只吃']='只吃饭卜洗碗:BAAALgAECgcJCwAAAA==.',
['只是']='只是一小颗枣:BAAALgAFFAEJAQAAAA==.',
['叫我']='叫我胖胖:BAABLgAECn8fAAIgAAgJyyInBQAeAwAgAAgJyyInBQAeAwAAAA==.叫我阿穸:BAAALgAECgYJDAAAAA==.',
['可乐']='可乐灬可乐:BAAALgADCgEJAQAAAA==.可乐请加冰:BAAALgAECgYJCQAAAA==.',
['可咪']='可咪可米:BAAALgAECgQJBAAAAA==.',
['可达']='可达鸭灬:BAAALgADCgMJAwABLgAECgUJBgAKAAAAAA==.',
['叶奈']='叶奈法:BAACLgAFFH8RAAIPAAYJjyWQAQCSAgAPAAYJjyWQAQCSAgAuAAQKfxgAAg8ACQnVJRUTADUDAA8ACQnVJRUTADUDAAAA.',
['叶诗']='叶诗涵:BAAALgAECgYJBgAAAA==.',
['司烨']='司烨:BAAALgAECgQJBwAAAA==.',
['司马']='司马光咣当:BAAALgAECgIJAgAAAA==.',
['吃瓜']='吃瓜萌主:BAAALgAECgIJAgAAAA==.',
['吃醋']='吃醋:BAAALgAECgYJDAAAAA==.',
['吉祥']='吉祥如意宝:BAAALgAECgEJAQAAAA==.',
['后跳']='后跳崴到脚:BAAALgAFFAIJAwAAAA==.',
['吚洫']='吚洫脃琪戀:BAAALgAFFAQJAwAAAA==.',
['君咯']='君咯雨:BAAALgAECgEJAQAAAA==.',
['君王']='君王的欲望:BAAALgAECgEJAQAAAA==.',
['吞酒']='吞酒兽:BAAALgAECgQJBQAAAA==.',
['听江']='听江声:BAAALgAFFAEJAQAAAA==.',
['听茶']='听茶:BAABLgAFFH8FAAMBAAMJvgtGCQBXAAABAAEJahBGCQBXAAAUAAMJvgt7IgBJAAAAAA==.',
['启禀']='启禀猿帅:BAABLgAFFH8FAAIFAAIJoB1APQCkAAAFAAIJoB1APQCkAAAAAA==.',
['吸搓']='吸搓咬抽:BAAALgAECgQJBwAAAA==.',
['呆壳']='呆壳兽:BAAALgAECgYJEQABLgAECggJFgAXAMMWAA==.',
['呉月']='呉月:BAAALgAECgYJCQAAAA==.',
['告别']='告别不安:BAAALgAECgEJAQAAAA==.',
['命运']='命运赦令:BAAALgAECgUJBQAAAA==.',
['咏春']='咏春柠檬:BAAALgAECgUJBQAAAA==.',
['咕咕']='咕咕丶鸡:BAAALgADCgQJBAAAAA==.',
['咖喱']='咖喱的咖喱:BAAALgADCgcJBwAAAA==.',
['咯尼']='咯尼美:BAABLgAECn8XAAMFAAcJXRzgRQAjAgAFAAcJXRzgRQAjAgAOAAUJkAMvMgCuAAAAAA==.',
['咱晚']='咱晚上吃什么:BAAALgADCgQJBAAAAA==.',
['咸鱼']='咸鱼鍀闲鱼:BAAALgAECgQJBAAAAA==.',
['咾司']='咾司机:BAAALgAFFAEJAQAAAA==.',
['哆啦']='哆啦美丶:BAAALgAECgEJAQAAAA==.',
['哇哈']='哇哈哈灬:BAAALgAECgYJCgAAAA==.',
['哈利']='哈利会魔法:BAAALgADCgEJAQAAAA==.',
['哈吉']='哈吉米:BAABLgAECn8eAAISAAgJxhi7EwB2AgASAAgJxhi7EwB2AgAAAA==.',
['哈基']='哈基园:BAAALgAECgcJBgAAAA==.哈基谴:BAAALgAECgkJEAABLgAFFAYJCwAPAL0cAA==.',
['哈尔']='哈尔辛丶:BAAALgAECgYJCAAAAA==.',
['哥不']='哥不要太帅:BAAALgAECgQJBAAAAA==.',
['哥伦']='哥伦布:BAAALgAFFAEJAQAAAA==.',
['哦嘛']='哦嘛咪呗呗哄:BAAALgAECgEJAQAAAA==.',
['哪些']='哪些旁白:BAAALgAECgQJBgAAAA==.',
['唤啊']='唤啊唤啊唤:BAABLgAFFH8FAAMTAAMJYBm2BgC4AAATAAMJYBm2BgC4AAAUAAEJLALwJAA+AAAAAA==.',
['唯一']='唯一的黑手:BAACLgAFFH8MAAIFAAQJ9w9JGgA8AQAFAAQJ9w9JGgA8AQAuAAQKfxUAAgUACQkyG8IfAMMCAAUACQkyG8IfAMMCAAAA.唯一的黑角:BAAALgAFFAEJAQAAAA==.',
['商务']='商务模特:BAAALgAECgUJBQAAAA==.',
['啊吊']='啊吊十八点五:BAAALgAFFAEJAQAAAA==.啊吊终结掉率:BAAALgADCgEJAQAAAA==.啊吊自己都怕:BAAALgAECgYJBgAAAA==.',
['啊哈']='啊哈哈快站好:BAAALgAECgYJCgAAAA==.',
['啊瓦']='啊瓦达啃大呱:BAAALgADCgEJAQAAAA==.',
['喂了']='喂了联盟农药:BAAALgAECgEJAgAAAA==.',
['喵叽']='喵叽别:BAABLgAFFH8FAAIFAAIJAAn6SgCGAAAFAAIJAAn6SgCGAAAAAA==.',
['喵呜']='喵呜丶圣喵神:BAAALgAECgIJAgABLgAECgYJCgAKAAAAAA==.喵呜丶胖喵神:BAAALgADCggJCAABLgAECgYJCgAKAAAAAA==.喵呜怪怪:BAAALgAFFAQJAwAAAA==.',
['嗖嗖']='嗖嗖是混子:BAAALgAFFAEJAQAAAA==.',
['嘀嘀']='嘀嘀叭叭唔:BAAALgAECgUJCQAAAA==.',
['嘉然']='嘉然带我走叭:BAAALgAECgQJBQAAAA==.',
['嘎嘎']='嘎嘎一通乱滚:BAAALgAFFAEJAQAAAA==.',
['嘎子']='嘎子:BAAALgAECgQJBAAAAA==.',
['嘤悦']='嘤悦:BAACLgAFFH8GAAQfAAMJJRVwAwC/AAAfAAIJSBpwAwC/AAAZAAEJ3wruFQBVAAAaAAEJ2QWqKABKAAAuAAQKfxUABB8ABwmVH+IJAD8CAB8ABwmVH+IJAD8CABoABAm2DbVeAMYAABkAAQk/FEXVADAAAAAA.',
['嘻哈']='嘻哈小丸子:BAAALgAECgMJAwAAAA==.嘻哈战神:BAAALgAECgEJAQAAAA==.',
['嘿嘿']='嘿嘿德:BAAALgAECgEJAwABLgAECgcJCQAKAAAAAA==.',
['噁魔']='噁魔獵掱:BAAALgADCgcJCAAAAA==.',
['噩夜']='噩夜颖:BAAALgADCgQJBQAAAA==.',
['噬灵']='噬灵妖孽:BAAALgAECgQJCQAAAA==.',
['噬身']='噬身之蛇:BAAALgAECgYJBgAAAA==.',
['噬魂']='噬魂天琪:BAAALgAECgQJBQAAAA==.噬魂天雅:BAAALgADCgQJBAAAAA==.噬魂狩猎者:BAAALgAECgUJBQAAAA==.',
['嚯梳']='嚯梳子:BAAALgADCgEJAQABLgAFFAYJDwAGALsgAA==.',
['四丶']='四丶夕:BAAALgAECgIJAgAAAA==.',
['四二']='四二八:BAAALgAECgMJAwAAAA==.',
['四只']='四只米儿:BAAALgAECgUJBQAAAA==.',
['四眼']='四眼:BAAALgAFFAIJAgAAAA==.',
['四费']='四费二鬼爆破:BAAALgADCgEJAQAAAA==.',
['回来']='回来吧叮咚鸡:BAAALgAECgUJBgAAAA==.',
['因果']='因果拉尔戈:BAAALgAECgEJAQAAAA==.',
['国土']='国土之战三:BAAALgAECgEJAQAAAA==.',
['国色']='国色恬香:BAAALgADCgcJBwAAAA==.',
['圆圆']='圆圆碌碌:BAAALgAECgUJBQAAAA==.',
['國之']='國之哀伤:BAAALgAECgYJCgAAAA==.',
['圣光']='圣光丶罗兰:BAAALgAECgUJCQAAAA==.圣光小白兽:BAABLgAFFH8FAAIQAAUJvQlJBwB8AQAQAAUJvQlJBwB8AQAAAA==.圣光惧人心:BAAALgAECgQJBAAAAA==.圣光柠檬:BAABLgAFFH8FAAIQAAIJzRS4IgCnAAAQAAIJzRS4IgCnAAAAAA==.圣光照你碧芝:BAAALgAECgEJAQAAAA==.圣光自爆兵:BAAALgAECgMJBAAAAA==.圣光葡萄:BAAALgAECgYJBgAAAA==.',
['圣加']='圣加西亚:BAAALgAECgcJCgAAAA==.',
['圣君']='圣君起飞:BAAALgADCgMJAwAAAA==.',
['圣斯']='圣斯坦:BAAALgAECgYJCAAAAA==.',
['地中']='地中海兄:BAAALgAECgQJBAAAAA==.',
['地狱']='地狱来者:BAAALgADCgYJBgAAAA==.',
['地獄']='地獄咆哮:BAAALgADCgEJAQAAAA==.',
['坑亲']='坑亲王:BAAALgAECgYJCwAAAA==.',
['埃提']='埃提耶什:BAAALgAECgUJBQAAAA==.',
['埋头']='埋头做牛:BAAALgAECgEJAQAAAA==.',
['堕落']='堕落的白洁:BAAALgAECgMJAwAAAA==.',
['塞纳']='塞纳玛丶怒风:BAAALgAECgcJBgAAAA==.',
['墨尔']='墨尔本晴灬:BAAALgADCgUJBQAAAA==.',
['墨染']='墨染丶冰辙:BAAALgAECgYJAgAAAA==.',
['墨漪']='墨漪清:BAABLgAECn8dAAMeAAYJFyEfEQAxAgAeAAYJ0SAfEQAxAgARAAUJuRb1OgBPAQAAAA==.',
['墨苍']='墨苍离:BAAALgAECgEJAgAAAA==.',
['壹瞬']='壹瞬壹生丶:BAAALgAECgUJBQAAAA==.',
['复仇']='复仇乄勇士:BAAALgAECgcJCwAAAA==.',
['夏二']='夏二可:BAACLgAFFH8HAAIhAAIJ7wuZBQBpAAAhAAIJ7wuZBQBpAAAuAAQKfxUAAiEABgm8GEkTAJYBACEABgm8GEkTAJYBAAAA.',
['夏天']='夏天的星光:BAAALgAECgQJBAAAAA==.夏天的游鱼:BAABLgAECn8bAAIPAAgJWxhBbgD4AQAPAAgJWxhBbgD4AQAAAA==.',
['夕晖']='夕晖之翼:BAAALgAFFAIJAQAAAA==.',
['夕颜']='夕颜丶浣溪纱:BAABLgAECn8VAAMgAAYJHBkSCQCzAQAgAAYJHBkSCQCzAQAiAAEJUAW8kgAkAAAAAA==.夕颜丶浣溪莎:BAABLgAECn8ZAAIGAAYJTA+BgwBTAQAGAAYJTA+BgwBTAQAAAA==.',
['多吃']='多吃肉身体好:BAAALgAECgEJBAAAAA==.',
['多多']='多多开心:BAAALgAECgYJBgAAAA==.',
['夜丷']='夜丷空:BAAALgAECgEJAQAAAA==.',
['夜之']='夜之魅影:BAAALgAECgQJBAAAAA==.',
['夜卿']='夜卿:BAAALgAFFAIJAgAAAA==.',
['夜如']='夜如此尴尬:BAAALgAECgIJAgAAAA==.',
['夜色']='夜色惑人心:BAAALgADCgcJBwAAAA==.',
['夜风']='夜风雨歌:BAAALgAECgQJBAAAAA==.',
['大专']='大专领主:BAACLgAFFH8NAAIjAAQJ2w+hBAAoAQAjAAQJ2w+hBAAoAQAuAAQKfyEAAyMABwm1HyUTAHkCACMABwm1HyUTAHkCABAABwlhCjqHAGwBAAAA.',
['大中']='大中华田园胖:BAAALgAECgUJBgAAAA==.',
['大丶']='大丶脸丶萌:BAAALgAECgEJAgAAAA==.',
['大乃']='大乃牛她妹:BAAALgADCgYJBgAAAA==.',
['大份']='大份可可慕斯:BAAALgAECgYJBgAAAA==.大份哈根达斯:BAAALgAFFAQJBAAAAA==.',
['大刀']='大刀捅主任:BAAALgAECgIJAwAAAA==.',
['大地']='大地之巅:BAAALgAECgQJBAAAAA==.大地信仰:BAAALgAECgYJBwAAAA==.',
['大大']='大大的德:BAAALgAECgcJCwAAAA==.',
['大彤']='大彤:BAAALgADCgcJBwAAAA==.',
['大拾']='大拾柒:BAAALgADCgcJBwAAAA==.',
['大核']='大核桃丨:BAAALgAECgQJBQAAAA==.',
['大潘']='大潘:BAAALgAECgIJAgAAAA==.',
['大爷']='大爷常来玩丫:BAAALgAECgIJAgAAAA==.',
['大爸']='大爸丶:BAAALgAECgUJBwAAAA==.',
['大皮']='大皮叔针强:BAAALgAECgUJBwABLgAECgkJCQAKAAAAAA==.',
['大盘']='大盘鸡烤肉:BAAALgAECgIJAQAAAA==.',
['大石']='大石彩香:BAABLgAECn8WAAMHAAgJnhojJgBtAgAHAAgJnhojJgBtAgAIAAEJzgqIaABCAAAAAA==.',
['大胡']='大胡子双马尾:BAAALgAECgUJBwAAAA==.',
['大裤']='大裤裤:BAAALgAECgUJBQAAAA==.',
['大西']='大西几丶:BAAALgAECgcJCwAAAA==.',
['大角']='大角角:BAAALgAECgQJBwAAAA==.',
['大阿']='大阿橙:BAAALgAECgYJBwAAAA==.',
['大飞']='大飞打非机:BAAALgAECgMJAwAAAA==.',
['大鸟']='大鸟转转丶:BAAALgAFFAIJAgAAAA==.',
['大黑']='大黑熊:BAAALgAFFAIJAwAAAA==.大黑袜子哦:BAAALgAECgEJAQAAAA==.',
['天丶']='天丶启:BAAALgADCgMJAgAAAA==.',
['天使']='天使自然喵:BAABLgAFFH8FAAIPAAUJewlbEQCLAQAPAAUJewlbEQCLAQAAAA==.',
['天启']='天启灬骑士:BAAALgAFFAIJAgAAAA==.',
['天命']='天命继承者丶:BAAALgADCgYJBgAAAA==.',
['天涯']='天涯海角丶若:BAAALgAECgcJBwAAAA==.',
['天祈']='天祈:BAAALgADCgEJAQAAAA==.',
['天空']='天空船长:BAAALgAECgEJAQAAAA==.',
['天黯']='天黯了:BAAALgAFFAEJAwABLgAFFAQJCAAFAMYYAA==.',
['太白']='太白熊:BAAALgAECgYJCwAAAA==.',
['太阳']='太阳之子:BAAALgAECgEJAQAAAA==.',
['头上']='头上一抹绿:BAAALgAECgEJAQAAAA==.',
['夹芯']='夹芯饼干:BAAALgAECgQJAwABLgAFFAYJFAAdAGIeAA==.',
['奇迹']='奇迹于你:BAAALgAECgIJBAAAAA==.',
['奈替']='奈替米星:BAAALgAECgEJAQAAAA==.',
['奈萌']='奈萌萌:BAAALgADCgQJBAAAAA==.',
['奈非']='奈非天迪凯:BAAALgAECgUJBQAAAA==.',
['奔跑']='奔跑的小猪:BAAALgADCgIJAgAAAA==.',
['套子']='套子战:BAAALgAECgIJAgAAAA==.',
['奥尔']='奥尔加玛丽:BAAALgAECgEJAQAAAA==.',
['奥斯']='奥斯蒂娅:BAAALgAECgcJEQAAAA==.',
['奥术']='奥术沖鸡:BAAALgAFFAEJAQAAAA==.',
['奥特']='奥特曼丶法神:BAAALgAECgMJBAAAAA==.',
['奥黛']='奥黛丽冰冰:BAAALgADCgEJAQAAAA==.',
['奧古']='奧古斯:BAAALgAECgcJBwAAAA==.',
['奰奰']='奰奰:BAAALgAFFAEJAQAAAA==.',
['女厕']='女厕:BAAALgAECgQJBAAAAA==.',
['女搜']='女搜官:BAAALgAECgQJBAAAAA==.',
['奶啤']='奶啤:BAACLgAFFH8HAAINAAMJyRqWEQDwAAANAAMJyRqWEQDwAAAuAAQKfyQAAw0ACAnBHTYQAJoCAA0ACAnBHTYQAJoCABcABAm8EXlKAOkAAAAA.',
['奶尐']='奶尐瓶:BAABLgAECn8gAAINAAgJmxSRCABtAQANAAgJmxSRCABtAQAAAA==.',
['奶水']='奶水有毒:BAAALgAECgUJCAAAAA==.',
['奶骑']='奶骑快交光环:BAAALgAECgQJBAAAAA==.',
['她灬']='她灬風騷:BAAALgAECgYJDAAAAA==.',
['好牛']='好牛奶啊:BAAALgAECggJDgAAAA==.',
['如洱']='如洱:BAAALgAECgcJBwAAAA==.',
['妖娆']='妖娆绽放:BAAALgAECgkJEgABLgAFFAcJAgAKAAAAAA==.',
['妙义']='妙义丶:BAAALgAECgEJAQAAAA==.',
['妹妹']='妹妹看看腿:BAAALgAECgEJAgAAAA==.',
['姬羽']='姬羽灵:BAAALgAFFAIJAgAAAA==.',
['姿味']='姿味:BAAALgADCgMJAwAAAA==.',
['娇妹']='娇妹杨箭的爱:BAAALgAECgYJBwAAAA==.',
['娇羞']='娇羞小母牛:BAAALgAECgEJAQAAAA==.',
['娘娘']='娘娘枪:BAAALgAECgEJAQAAAA==.',
['娜米']='娜米娅:BAAALgAECggJBgAAAA==.',
['婲木']='婲木兰:BAAALgAECgEJAQAAAA==.',
['嫩嫩']='嫩嫩的小鲜肉:BAAALgAECgYJBwAAAA==.',
['孙策']='孙策伯符:BAAALgAECgEJAQAAAA==.',
['孙行']='孙行者伊库:BAAALgAECgcJBwAAAA==.',
['孟铁']='孟铁通:BAABLgAECn8XAAIPAAgJGyK9FQAmAwAPAAgJGyK9FQAmAwAAAA==.',
['孤风']='孤风血影:BAAALgAECgUJBgAAAA==.',
['孤鸿']='孤鸿踏霜:BAAALgAECgQJBAAAAA==.',
['宇智']='宇智波富贵:BAABLgAFFH8KAAIQAAQJ1RzABgCDAQAQAAQJ1RzABgCDAQAAAA==.宇智玻带土:BAACLgAFFH8IAAIFAAMJxhumIgAMAQAFAAMJxhumIgAMAQAuAAQKfxkAAwUABgkAIgVRAP8BAAUABgkAIgVRAP8BAA4ABQl4DE4MALcAAAAA.',
['守护']='守护你的梦想:BAAALgAECgcJDwAAAA==.',
['安倪']='安倪妮海瑟薇:BAAALgADCgcJBwAAAA==.',
['安徽']='安徽张凌赫:BAAALgAECgcJBwAAAA==.',
['安舍']='安舍:BAAALgAECgQJBAAAAA==.',
['宙撕']='宙撕:BAAALgAECgUJBwAAAA==.',
['宝宝']='宝宝奶昔宝宝:BAAALgADCgQJBAAAAA==.',
['宴中']='宴中酒灬:BAAALgADCgcJAwAAAA==.',
['寂寞']='寂寞那谁谁:BAAALgAECgkJCQAAAA==.',
['寄予']='寄予思慕丶:BAACLgAFFH8JAAIFAAMJ4RwVJwD7AAAFAAMJ4RwVJwD7AAAuAAQKfxkAAgUABwnxGsI+AD0CAAUABwnxGsI+AD0CAAAA.',
['寒酥']='寒酥烬影:BAAALgAECgcJBQAAAA==.',
['寒风']='寒风天策:BAAALgAECgUJBQAAAA==.',
['寶唄']='寶唄唲的爪牙:BAABLgAFFH8GAAIgAAMJ0BCfDwDrAAAgAAMJ0BCfDwDrAAAAAA==.',
['小丸']='小丸甜喵德:BAAALgADCgQJBAAAAA==.',
['小九']='小九么:BAAALgADCgYJCQAAAA==.',
['小单']='小单曲:BAAALgAECgYJBgAAAA==.',
['小噹']='小噹:BAABLgAFFH8KAAIFAAQJNx8GAgCSAQAFAAQJNx8GAgCSAQAAAA==.',
['小小']='小小怪酋长:BAAALgADCgYJBAAAAA==.',
['小手']='小手一挥:BAAALgAECgYJBwAAAA==.',
['小拳']='小拳拳锤你头:BAAALgAECgMJAwAAAA==.',
['小洁']='小洁吃葡萄:BAABLgAFFH8GAAINAAQJjR3xBgBkAQANAAQJjR3xBgBkAQAAAA==.',
['小潘']='小潘潘丶:BAAALgAFFAEJAQAAAA==.',
['小火']='小火龍:BAAALgAECgYJBgAAAA==.',
['小狐']='小狐猎:BAAALgADCgEJAQAAAA==.',
['小猪']='小猪乔治:BAAALgAECgYJBgAAAA==.',
['小猫']='小猫神奶:BAAALgAECgMJAwAAAA==.',
['小白']='小白手套哟:BAABLgAECn8fAAMhAAgJ9yK0AQAzAwAhAAgJ9yK0AQAzAwAQAAMJrAZPDAF+AAAAAA==.',
['小秋']='小秋子:BAAALgAECgMJAwAAAA==.',
['小米']='小米喵:BAAALgAECgcJAQAAAA==.小米苏:BAAALgAECgEJAQAAAA==.',
['小细']='小细菌:BAAALgADCgEJAQAAAA==.',
['小羊']='小羊快逃:BAAALgAFFAQJBAAAAA==.小羊肉汤:BAAALgAECgYJCgAAAA==.',
['小肚']='小肚兜:BAAALgADCgIJAgAAAA==.',
['小自']='小自然:BAAALgAECgUJCQABLgAFFAUJBQAPAHsJAA==.',
['小苹']='小苹果树:BAAALgAECgEJAQAAAA==.',
['小荷']='小荷塘月:BAAALgADCgEJAQAAAA==.',
['小血']='小血瓶子:BAAALgAECgYJCQAAAA==.',
['小钢']='小钢板:BAAALgAECgUJBgAAAA==.',
['小锤']='小锤锤砸你头:BAAALgAECgIJAwAAAA==.',
['小阿']='小阿橙丶:BAABLgAECn8lAAMGAAkJPxodAwBnAgAGAAkJPxodAwBnAgALAAIJxRkERAClAAAAAA==.',
['小陆']='小陆老师:BAAALgAECgYJCAAAAA==.',
['小隻']='小隻龙:BAAALgAFFAQJBAABLgAFFAcJCAATAJcjAA==.',
['小马']='小马溜溜达达:BAAALgAECgEJAQAAAA==.',
['小魔']='小魔星:BAAALgADCgQJBAAAAA==.',
['小鸟']='小鸟不会飞:BAAALgAECgYJBQAAAA==.',
['小黑']='小黑手套哟:BAAALgADCgcJDAAAAA==.',
['少林']='少林功夫劲嘢:BAAALgAECgUJCgAAAA==.',
['尔思']='尔思丶狩猎:BAAALgAECgYJCwAAAA==.',
['就哒']='就哒徳:BAAALgADCgUJBQAAAA==.',
['就得']='就得是光头:BAAALgADCgEJAQAAAA==.',
['就是']='就是个牧仕:BAAALgAECgUJBQAAAA==.',
['尾巴']='尾巴的钵钵鸡:BAAALgAECgMJBQAAAA==.',
['山旮']='山旮旯野拳:BAAALgAFFAIJAwAAAA==.',
['岸边']='岸边的少女:BAAALgAECgEJAQAAAA==.',
['崴脚']='崴脚少年:BAAALgAECgEJAQAAAA==.',
['嶋野']='嶋野狂犬:BAAALgAECgcJDAAAAA==.',
['巃凤']='巃凤呈祥:BAAALgAECgEJAQAAAA==.',
['左边']='左边锋:BAAALgAECgUJBQAAAA==.',
['巧克']='巧克力棉花糖:BAAALgAECggJCgAAAA==.',
['巧爷']='巧爷不喝热奶:BAAALgAECgMJBQAAAA==.',
['巴布']='巴布巴巴:BAAALgAECgUJCgAAAA==.',
['巴黎']='巴黎卡姿兰:BAAALgAECgYJBgAAAA==.',
['布莱']='布莱克:BAAALgAECgQJBAAAAA==.',
['布衣']='布衣小白:BAAALgAECgMJAwAAAA==.',
['布达']='布达佩斯:BAAALgAFFAQJBAAAAA==.',
['帅得']='帅得那么精彩:BAAALgAECgIJAwAAAA==.',
['帅气']='帅气小姆:BAAALgAECgEJAQABLgAFFAIJAwAKAAAAAA==.',
['师承']='师承桃门:BAAALgAECgQJBAAAAA==.',
['希天']='希天青:BAAALgAECgYJBgAAAA==.',
['希彤']='希彤橘:BAAALgAECgYJEQAAAA==.',
['希柳']='希柳绿:BAAALgAECgYJBgAAAA==.',
['希樱']='希樱粉:BAAALgAECgMJAgAAAA==.',
['希绯']='希绯红:BAAALgADCgIJAgAAAA==.',
['希蔚']='希蔚蓝:BAAALgAECgYJDQAAAA==.',
['帕丁']='帕丁顿熊大:BAAALgAECgYJCwAAAA==.',
['帝龙']='帝龙胤:BAAALgAFFAMJAwAAAA==.',
['带带']='带带小咕咕:BAAALgADCgIJAgAAAA==.',
['帮你']='帮你握出来:BAACLgAFFH8JAAIFAAMJkyABJAAGAQAFAAMJkyABJAAGAQAuAAQKfxgAAgUABglnI6NKABMCAAUABglnI6NKABMCAAAA.',
['年少']='年少的欢喜丶:BAAALgAECgUJBwAAAA==.',
['幻灯']='幻灯花:BAAALgADCgMJAwAAAA==.',
['幽冥']='幽冥一箭:BAAALgAECgQJBQAAAA==.',
['幽奇']='幽奇:BAAALgAECgMJAwAAAA==.',
['幽梦']='幽梦糖糖:BAAALgADCgMJAwAAAA==.',
['幽蝶']='幽蝶花舞:BAAALgAFFAMJBAAAAA==.',
['幽魂']='幽魂魔尊:BAAALgAECgQJBwAAAA==.',
['床前']='床前一道光:BAAALgAECgQJBAAAAA==.',
['庐山']='庐山升龙爸:BAAALgAFFAIJAwAAAA==.',
['库卡']='库卡隆指挥官:BAAALgAECgQJBAAAAA==.',
['应钟']='应钟丶:BAAALgAECgIJAgAAAA==.',
['底层']='底层逻辑:BAABLgAFFH8FAAMUAAMJlgS2CgDGAAAUAAMJlgS2CgDGAAATAAIJQAOOFAB/AAAAAA==.',
['康娜']='康娜卡姆依:BAAALgAFFAIJAgAAAA==.',
['开心']='开心小钉裆:BAAALgAFFAIJBAAAAA==.',
['开水']='开水瓶:BAAALgADCgEJAQAAAA==.',
['开颅']='开颅手烨烨:BAAALgADCgIJAwAAAA==.',
['式部']='式部茉优:BAAALgAECgcJCAABLgAFFAIJBAAKAAAAAA==.',
['弗雷']='弗雷:BAAALgAFFAEJAQAAAA==.',
['张翼']='张翼德:BAAALgADCgYJBQAAAA==.',
['弹弓']='弹弓打你脸:BAAALgAECgEJAQAAAA==.',
['强行']='强行支付:BAAALgAECgYJBgAAAA==.',
['彩色']='彩色的岚:BAAALgAECgYJDgAAAA==.',
['影色']='影色舞:BAAALgAECgcJBwAAAA==.',
['彼岸']='彼岸的真谛:BAAALgAECgYJBgAAAA==.',
['很狂']='很狂浪的牛:BAAALgADCgcJBwAAAA==.',
['很硬']='很硬的茬子:BAABLgAFFH8FAAMaAAMJqB8fEwAKAQAaAAMJ3xcfEwAKAQAZAAIJoSYAAAAAAAABLgAFFAQJCQAFALQjAA==.',
['得闲']='得闲炒饭:BAAALgAECgUJBQAAAA==.',
['御景']='御景天:BAAALgAECgEJAQAAAA==.御景明:BAAALgAECgQJBAAAAA==.',
['微白']='微白灬思杰凯:BAAALgAECgUJBQAAAA==.',
['微笑']='微笑灬鹏鹏:BAAALgAECgkJCQAAAA==.',
['微醺']='微醺兔崽:BAAALgADCgEJAQAAAA==.',
['德不']='德不德德:BAAALgADCgYJBgAAAA==.',
['德云']='德云大傻:BAAALgADCgIJAgAAAA==.',
['德修']='德修拉:BAABLgAECn8cAAIVAAgJPRjfCADQAQAVAAgJPRjfCADQAQAAAA==.',
['德罪']='德罪不起:BAAALgAECgYJBAAAAA==.',
['德高']='德高妄重:BAAALgADCgYJBgAAAA==.',
['心寬']='心寬體胖:BAAALgAECgQJBAAAAA==.',
['心灵']='心灵吉慧:BAAALgAECgQJBQAAAA==.',
['心语']='心语诉说:BAAALgAECgcJBwAAAA==.',
['心跳']='心跳:BAAALgAECgYJCgAAAA==.',
['快到']='快到碗里去丶:BAAALgAECgYJDQAAAA==.',
['怀旧']='怀旧服团长:BAAALgAECgYJCgAAAA==.',
['怒犬']='怒犬:BAABLgAECn8XAAMNAAcJuw/cOgBdAQANAAYJ/hDcOgBdAQAXAAYJ3wo7RAAFAQAAAA==.',
['怒风']='怒风年轻时:BAAALgAECgYJCAAAAA==.',
['思绪']='思绪渐已成河:BAACLgAFFH8HAAIHAAMJuRiEGQAEAQAHAAMJuRiEGQAEAQAuAAQKfx4AAwcACAmHII0YAMICAAcACAl7II0YAMICAAgABQn5H9wwAEsBAAAA.',
['性感']='性感大蟑螂:BAAALgAECgcJBwAAAA==.性感小蹄子灬:BAAALgAFFAIJAgAAAA==.',
['恐怖']='恐怖的夜魔:BAAALgADCgQJBAAAAA==.',
['恩賜']='恩賜解脫:BAAALgADCgEJAQAAAA==.',
['恬逸']='恬逸:BAAALgADCgUJBQAAAA==.',
['恰恰']='恰恰嗨皮:BAAALgAFFAIJAgAAAA==.',
['恶啵']='恶啵咆哮:BAAALgAECgMJAwAAAA==.',
['恶气']='恶气的老萝卜:BAAALgAECgkJCQAAAA==.',
['恶质']='恶质上司:BAAALgAECgMJAwAAAA==.',
['恶魔']='恶魔兔蛋蛋:BAAALgAECgYJEQAAAA==.恶魔雷龙:BAAALgAECgcJBwAAAA==.',
['悖论']='悖论:BAAALgAECgMJAwABLgAECgkJCQAKAAAAAA==.',
['悠悠']='悠悠的户晨风:BAAALgADCgUJBQAAAA==.',
['悠然']='悠然的云:BAAALgAECgYJBwAAAA==.',
['悦帆']='悦帆:BAAALgADCgMJAwAAAA==.',
['想飞']='想飞天的鱼:BAAALgAECgYJDQAAAA==.',
['惹怒']='惹怒人儿:BAAALgAECgMJBAAAAA==.惹怒人儿丶:BAABLgAFFH8HAAIQAAMJ/xObGQDZAAAQAAMJ/xObGQDZAAAAAA==.',
['意大']='意大利小吊灯:BAAALgAECgIJAgAAAA==.',
['愚戏']='愚戏:BAABLgAFFH8RAAMeAAQJ2yDPCwAdAQAeAAMJXx/PCwAdAQAdAAEJuBoeEwBaAAAAAA==.',
['愛丽']='愛丽斯:BAAALgAECgEJAQAAAA==.',
['愤怒']='愤怒的哀木涕:BAACLgAFFH8HAAIbAAMJnhEuCADXAAAbAAMJnhEuCADXAAAuAAQKfxkAAxsABwlVG/EMADwCABsABwlVG/EMADwCABYABQmqE79fADEBAAAA.',
['愿太']='愿太阳温暖你:BAAALgAECgcJAgAAAA==.',
['慕容']='慕容翰:BAAALgADCgUJBQAAAA==.',
['慕流']='慕流年:BAAALgADCgEJAQAAAA==.',
['慾鈥']='慾鈥:BAAALgADCgEJAQAAAA==.',
['懑懑']='懑懑鼕燑:BAAALgAECgcJDQAAAA==.',
['戊辰']='戊辰:BAAALgAECgYJBwAAAA==.',
['成都']='成都电信:BAAALgAECgYJBgAAAA==.',
['我不']='我不是很随便:BAAALgAFFAEJAQAAAA==.我不能哈气了:BAAALgAECgUJCQAAAA==.',
['我乃']='我乃邢道荣:BAAALgADCgEJAQAAAA==.',
['我劝']='我劝你老实点:BAAALgAFFAEJAQAAAA==.',
['我又']='我又又回来了:BAAALgAECgUJBgAAAA==.',
['我叫']='我叫忠哥:BAAALgAECgUJCgAAAA==.',
['我圣']='我圣光超度你:BAAALgAECgMJAwAAAA==.',
['我就']='我就是风暴:BAAALgAECgEJAQAAAA==.',
['我是']='我是苏三:BAAALgAECgcJBwAAAA==.我是西红柿:BAAALgAECgUJCAAAAA==.我是龙也好:BAAALgAECgEJAQAAAA==.',
['我有']='我有六个小三:BAAALgAECgYJBwAAAA==.',
['我燃']='我燃烧好了:BAAALgAECgYJCgAAAA==.',
['我爱']='我爱中单光一:BAAALgAECgEJAQAAAA==.',
['我的']='我的好大儿:BAAALgAECgIJAgAAAA==.我的朋友很少:BAAALgAECgYJDQAAAA==.我的神光优呀:BAAALgAECgMJAwAAAA==.',
['我饿']='我饿死了:BAAALgADCgEJAQAAAA==.',
['战貂']='战貂:BAAALgADCgIJAgAAAA==.',
['战魂']='战魂夺魄:BAAALgADCgQJBAAAAA==.',
['戦灬']='戦灬殇:BAAALgADCgYJBAAAAA==.',
['戴安']='戴安娜敏雯:BAAALgAECgQJBAAAAA==.戴安娜静静:BAAALgADCgEJAQAAAA==.',
['戸戸']='戸戸:BAAALgAECgIJAgAAAA==.',
['手残']='手残粉:BAAALgAECgQJAQAAAA==.',
['打俺']='打俺就冰箱:BAAALgAECgIJAgABLgAECgcJCQAKAAAAAA==.',
['打本']='打本不用眼:BAAALgADCgYJCwAAAA==.',
['打蕉']='打蕉高手:BAAALgAECgQJBAAAAA==.',
['托马']='托马斯术爹:BAAALgAECgIJAgAAAA==.',
['执戟']='执戟修罗丶:BAAALgAECgkJCQAAAA==.',
['技能']='技能正在冷却:BAAALgAECggJDwAAAA==.',
['抓猪']='抓猪的小伙:BAAALgAFFAEJAgAAAA==.',
['抠脚']='抠脚的牛牛:BAAALgAECgMJAwAAAA==.',
['披星']='披星戴月:BAAALgAECgEJAQAAAA==.',
['拉风']='拉风的德:BAAALgAECgEJAgAAAA==.',
['拒绝']='拒绝开门:BAAALgADCgEJAQAAAA==.',
['拖鞋']='拖鞋正飞过来:BAAALgAECgEJAgAAAA==.',
['拾捌']='拾捌:BAAALgAECgEJAgAAAA==.',
['捞逼']='捞逼:BAAALgADCgYJDAAAAA==.',
['排骨']='排骨小妹:BAAALgADCgcJBwAAAA==.排骨新娘:BAAALgAECgMJAwAAAA==.排骨新郎:BAABLgAECn8UAAIFAAcJ7BXPbACxAQAFAAcJ7BXPbACxAQAAAA==.排骨猎:BAAALgAECggJDwAAAA==.排骨骑士:BAABLgAECn8YAAIQAAkJvRwJGwDHAgAQAAkJvRwJGwDHAgAAAA==.',
['推手']='推手大师:BAAALgAECgYJCwAAAA==.',
['摩西']='摩西德德:BAAALgAECgEJAQAAAA==.',
['摸手']='摸手灬诗洁:BAAALgAECgEJAQAAAA==.',
['摸摸']='摸摸昊昊下面:BAAALgAECgcJEgAAAA==.',
['摸黑']='摸黑上床:BAAALgAFFAIJAgABLgAFFAIJAgAKAAAAAA==.',
['撫劍']='撫劍聽雨:BAAALgADCgEJAQAAAA==.',
['收售']='收售旧冰箱:BAAALgAECgcJBwAAAA==.',
['放冰']='放冰的小笨蛋:BAAALgAECgYJBwAAAA==.',
['放开']='放开让我来:BAAALgAFFAEJAQAAAA==.',
['故乡']='故乡的春卷:BAACLgAFFH8GAAIGAAMJqx7iGwAWAQAGAAMJqx7iGwAWAQAuAAQKfxsAAwYACAmvIGwfAJsCAAYABwmvIGwfAJsCAAsABAnLGYwmACwBAAAA.',
['敗者']='敗者食塵丶:BAAALgAECgUJBgAAAA==.',
['敢做']='敢做不敢荡:BAAALgAECgMJAwAAAA==.',
['文绉']='文绉绉:BAAALgAECgQJCAAAAA==.',
['斯马']='斯马维德托:BAAALgAECgEJAQAAAA==.',
['新手']='新手二饼威猛:BAACLgAFFH8HAAIQAAMJawbKGQDWAAAQAAMJawbKGQDWAAAuAAQKfxcAAhAACAleDKpxAJgBABAACAleDKpxAJgBAAAA.',
['新新']='新新暗夜猎手:BAAALgADCgkJAgAAAA==.',
['斷劍']='斷劍重鑄:BAAALgADCgEJAQAAAA==.',
['无人']='无人摘星辰:BAAALgAECgcJBwAAAA==.',
['无情']='无情的日:BAAALgAECgQJBAABLgAFFAIJAgAKAAAAAA==.',
['无敌']='无敌大宝剑:BAAALgADCgUJBAAAAA==.无敌小小术:BAAALgAECgYJCgAAAA==.',
['无极']='无极刀法:BAAALgAECgYJCgAAAA==.无极剑剑无极:BAAALgAFFAEJAQAAAA==.',
['无能']='无能的妻子:BAAALgAECgQJCQAAAA==.',
['无豆']='无豆的凯子:BAABLgAECn8UAAMZAAYJNxaqRwCTAQAZAAYJsxWqRwCTAQAaAAYJhArjTgATAQAAAA==.',
['旧城']='旧城等新人:BAAALgAECgQJBAAAAA==.',
['昆明']='昆明马保国:BAAALgAFFAEJAQAAAA==.',
['昊昊']='昊昊想我了吗:BAAALgADCgEJAQAAAA==.',
['明丶']='明丶:BAAALgAECgkJDgAAAA==.',
['明坤']='明坤沐苒:BAAALgAECgYJEwAAAA==.',
['明月']='明月清风:BAAALgAECgMJBgAAAA==.明月长生:BAAALgAECgUJAwAAAA==.',
['明画']='明画丿:BAAALgAECgMJAwAAAA==.',
['星丨']='星丨歌:BAAALgAECgQJBwAAAA==.',
['星丶']='星丶歌:BAAALgAECgMJAwAAAA==.',
['星川']='星川落子:BAAALgAECgQJBAAAAA==.',
['星星']='星星之怒丶:BAAALgAECgYJCwAAAA==.',
['星月']='星月丶信鸦:BAAALgAECgQJBAAAAA==.',
['星灵']='星灵移位丶:BAAALgADCgEJAQAAAA==.',
['星见']='星见入然:BAAALgAECgYJAgAAAA==.',
['星象']='星象轨迹:BAAALgAECgEJAQAAAA==.',
['星辰']='星辰丶:BAAALgAECgYJBgAAAA==.',
['星高']='星高空:BAAALgAECgYJCwAAAA==.',
['春见']='春见:BAAALgAECgYJBwAAAA==.',
['显卡']='显卡:BAAALgAECgIJAgAAAA==.',
['晒太']='晒太阳的桌子:BAAALgADCgEJAQAAAA==.',
['晓丶']='晓丶獠牙:BAAALgADCgYJBQAAAA==.',
['晓晓']='晓晓小浣熊:BAABLgAFFH8NAAIMAAQJjxVCBwBMAQAMAAQJjxVCBwBMAQAAAA==.',
['晚秋']='晚秋骄阳:BAAALgAECgYJCAAAAA==.',
['晨丶']='晨丶翎:BAAALgAECgEJAQAAAA==.',
['晨花']='晨花心火:BAABLgAECn8ZAAMVAAcJuwuEXQA5AQAVAAcJuwuEXQA5AQASAAYJ9QuyRwAOAQAAAA==.',
['晨风']='晨风灬沐雨:BAAALgAECgYJDgAAAA==.',
['普洱']='普洱东:BAAALgAECgYJBgAAAA==.',
['暁氺']='暁氺暁:BAAALgADCgYJBgAAAA==.',
['暗夜']='暗夜凯:BAAALgAECgMJAwAAAA==.暗夜米兹:BAAALgADCgEJAQAAAA==.',
['暗影']='暗影放成烟花:BAAALgAECgEJAQAAAA==.',
['暗紫']='暗紫骷髅:BAAALgAECgQJBQAAAA==.',
['暗黑']='暗黑血天使:BAAALgAECgYJBwAAAA==.',
['暗龙']='暗龙果:BAAALgAECgIJAgAAAA==.',
['暮晓']='暮晓丶:BAAALgADCgYJCwAAAA==.',
['暮色']='暮色丶:BAAALgAECgEJAQAAAA==.',
['暮雪']='暮雪灬逍遥:BAAALgAECgEJAQAAAA==.暮雪逍遥:BAAALgAECgcJDAAAAA==.',
['暴力']='暴力的大哥大:BAAALgADCgIJAgAAAA==.暴力裁决:BAAALgAECgUJBwAAAA==.',
['暴怒']='暴怒任遨游:BAAALgAECgYJEgAAAA==.暴怒的恰恰:BAACLgAFFH8TAAMgAAUJuCJSAAADAgAgAAUJuCJSAAADAgAiAAMJUR7dDQAOAQAuAAQKfyQAAyIACAlQJSoHACADACIACAlQJSoHACADACAACAmXHaQOAKUCAAAA.',
['暴暴']='暴暴大队长:BAAALgADCgkJCgAAAA==.',
['暴粗']='暴粗大野兽:BAAALgADCgIJAgAAAA==.',
['暴走']='暴走暴走:BAAALgAECgQJBAAAAA==.暴走神牛:BAAALgAFFAEJAQAAAA==.',
['暴躁']='暴躁的冲天炮:BAAALgAECgYJDQAAAA==.暴躁老登:BAAALgAECgQJBgAAAA==.',
['曳光']='曳光:BAAALgAECgEJAQAAAA==.',
['曼曼']='曼曼波:BAAALgAECgIJAgAAAA==.',
['最后']='最后的自由:BAAALgAECgIJAgAAAA==.',
['最後']='最後灬奶霸:BAAALgAECgYJBwAAAA==.',
['最爱']='最爱吃果冻:BAAALgAECgkJCAAAAA==.',
['月夜']='月夜渐微凉:BAAALgADCgIJAgAAAA==.',
['月有']='月有阴晴圆缺:BAAALgAECgEJAQAAAA==.',
['月染']='月染:BAAALgAECgYJCgAAAA==.',
['月神']='月神丶:BAABLgAFFH8FAAIdAAIJrRyyDQC9AAAdAAIJrRyyDQC9AAAAAA==.月神忽悠着我:BAAALgAECgQJBgAAAA==.',
['月萱']='月萱丶:BAAALgAECgYJCgAAAA==.',
['月衣']='月衣夜会丶:BAAALgAECgYJCwAAAA==.',
['月靈']='月靈:BAAALgAFFAQJAgAAAA==.',
['月韵']='月韵芝:BAAALgAECgQJBAAAAA==.',
['有棵']='有棵树:BAAALgAECgEJAQAAAA==.',
['有融']='有融:BAAALgAECgEJAQAAAA==.',
['木有']='木有奶兮:BAAALgAECgMJAwAAAA==.',
['木桥']='木桥小谣:BAAALgAECgQJBAAAAA==.',
['木鹿']='木鹿大王:BAAALgAECgQJCAAAAA==.',
['未小']='未小满:BAAALgADCgYJBgAAAA==.',
['未来']='未来已经改变:BAAALgAECgQJBwAAAA==.',
['未知']='未知未见:BAAALgAFFAIJAwAAAA==.未知的:BAAALgAECgcJDQAAAA==.',
['末厄']='末厄:BAAALgAECgEJAQABLgAFFAIJBgAFADgmAA==.',
['术手']='术手就擒:BAAALgADCgEJAQAAAA==.',
['机制']='机制大于操作:BAAALgAECgEJAQAAAA==.',
['朽叶']='朽叶千咲:BAAALgAECgEJAQAAAA==.',
['杀一']='杀一刀:BAAALgAECgkJCAAAAA==.',
['李彩']='李彩领:BAAALgADCgcJBwAAAA==.',
['村东']='村东头什么的:BAAALgAECgMJAwAAAA==.村东头刘大爷:BAACLgAFFH8PAAINAAQJERsqBwBgAQANAAQJERsqBwBgAQAuAAQKfxsAAg0ACAk7G34iAO4BAA0ACAk7G34iAO4BAAAA.村东头老干部:BAAALgAECgYJBgAAAA==.',
['杜梅']='杜梅拉:BAABLgAECn8aAAIPAAgJ5Bx3LADBAgAPAAgJ5Bx3LADBAgAAAA==.',
['来个']='来个五连鞭:BAAALgAECgQJAwAAAA==.',
['来我']='来我家睡吗:BAAALgADCgUJBQAAAA==.',
['杰钹']='杰钹烬渽:BAAALgAECgIJAgAAAA==.',
['板甲']='板甲老圣光:BAAALgAECgcJCwAAAA==.',
['枫的']='枫的最后一句:BAAALgAECgcJCwAAAA==.',
['枫舞']='枫舞小陳:BAAALgAECgEJAQAAAA==.',
['柒之']='柒之丶:BAAALgAECgEJAwAAAA==.',
['柠檬']='柠檬灬丨:BAAALgADCgEJAQAAAA==.',
['查狄']='查狄伦暴风:BAAALgAECgEJAQAAAA==.',
['柴柯']='柴柯夫斯基:BAAALgAECgYJBgAAAA==.',
['根本']='根本不给你加:BAAALgAECgEJAQAAAA==.',
['桀骜']='桀骜的烬:BAAALgAFFAIJAwAAAA==.',
['桐心']='桐心:BAAALgAECgkJEAAAAA==.',
['桥本']='桥本三世:BAAALgAFFAIJAgAAAA==.',
['梦回']='梦回灬弑殇:BAAALgAFFAUJAgAAAA==.',
['梦应']='梦应归于何处:BAAALgADCgcJBwAAAA==.',
['梦碎']='梦碎大道:BAABLgAECn8hAAMDAAgJdR+qAQBCAgADAAgJdR+qAQBCAgACAAEJYBD6HABCAAAAAA==.',
['梨羽']='梨羽:BAAALgAECgUJBQAAAA==.',
['樱伤']='樱伤漓洛:BAABLgAFFH8FAAIQAAUJDwLdFQD8AAAQAAUJDwLdFQD8AAAAAA==.',
['樱桃']='樱桃仙女:BAAALgAECgQJCgAAAA==.',
['樱羽']='樱羽艾玛的爱:BAAALgAECgYJDgAAAA==.',
['橘前']='橘前辈还在看:BAAALgAECgIJAgAAAA==.',
['橙光']='橙光老牛:BAAALgADCgMJAwAAAA==.',
['橙鈊']='橙鈊橙镱:BAAALgAECgEJAQAAAA==.',
['欧吃']='欧吃矛:BAAALgAECgkJEwABLgAFFAQJBwAPANkcAA==.',
['欧阳']='欧阳一法神:BAAALgAFFAQJBAAAAA==.欧阳三法神:BAAALgAFFAIJAQABLgAFFAUJCgAPAGkOAA==.欧阳二法神:BAAALgAECgkJDwABLgAFFAUJCgAPAGkOAA==.欧阳法神:BAABLgAFFH8GAAIPAAQJ6BC+GgBgAQAPAAQJ6BC+GgBgAQABLgAFFAUJCgAPAGkOAA==.',
['正义']='正义的馒头:BAAALgADCgEJAQAAAA==.',
['正规']='正规大宝剑:BAAALgAECgkJCQAAAA==.',
['正道']='正道的胱呀:BAAALgAFFAIJAgABLgAFFAYJEQAPAI8lAA==.',
['武器']='武器战丨:BAAALgADCgIJAgAAAA==.',
['武战']='武战之空:BAAALgAECgIJAgAAAA==.',
['武装']='武装侦察:BAAALgAFFAIJAgAAAA==.',
['歪比']='歪比坝卜:BAAALgAFFAUJBAAAAA==.歪比歪比:BAAALgAFFAIJAwAAAA==.',
['死于']='死于炖鸡:BAAALgAECgIJAgAAAA==.',
['死亡']='死亡球球:BAAALgAECgMJAwAAAA==.',
['歼世']='歼世灭尽龙:BAAALgAECgYJBQAAAA==.',
['歼灭']='歼灭天使:BAAALgADCgEJAQAAAA==.',
['残丶']='残丶雪:BAAALgAFFAEJAQAAAA==.',
['比克']='比克大魔汪:BAAALgAECgMJAwAAAA==.',
['比卡']='比卡丘丶:BAAALgADCgkJCQAAAA==.',
['比比']='比比拉布丶:BAAALgAECgEJAgAAAA==.',
['毛怪']='毛怪:BAAALgAECgMJBAAAAA==.',
['毛栗']='毛栗子丶:BAAALgAECgcJBwAAAA==.',
['水蓝']='水蓝天蝎:BAAALgAECgMJAwAAAA==.',
['永信']='永信大师:BAAALgADCgEJAQAAAA==.',
['永恒']='永恒:BAAALgAECgEJAQAAAA==.',
['氺小']='氺小学生氺:BAAALgAECgEJAQAAAA==.',
['汏溮']='汏溮兇:BAAALgAECgMJAwAAAA==.',
['江死']='江死炮:BAAALgAECgEJAQAAAA==.',
['江湖']='江湖传说氤氤:BAAALgAECgQJBAAAAA==.',
['汪汪']='汪汪小卡:BAAALgAECgUJBQAAAA==.',
['汲取']='汲取虚空之力:BAAALgAECgYJCgAAAA==.',
['沃古']='沃古斯:BAAALgAFFAIJAgAAAA==.',
['沉影']='沉影:BAAALgAECgIJAgAAAA==.',
['沐老']='沐老师:BAAALgAFFAIJAwAAAA==.',
['沙条']='沙条綾香:BAAALgAECgMJAwAAAA==.',
['沙滩']='沙滩雪糕:BAAALgADCgIJAQAAAA==.',
['没尾']='没尾巴就好了:BAAALgAECgIJBAAAAA==.',
['法力']='法力残渣丶:BAABLgAFFH8HAAIPAAQJGBdGCQBWAQAPAAQJGBdGCQBWAQAAAA==.',
['法盲']='法盲大壮:BAABLgAFFH8GAAIPAAMJ8giBLwD4AAAPAAMJ8giBLwD4AAAAAA==.',
['泡一']='泡一沫:BAAALgADCgIJAgAAAA==.',
['波一']='波一霸:BAAALgAECgMJAwAAAA==.',
['波蕥']='波蕥汉庫克:BAAALgADCgcJBwAAAA==.',
['泪冠']='泪冠哀歌:BAAALgAECgMJBQABLgAECgkJCQAKAAAAAA==.',
['泰术']='泰术瑞亚:BAAALgAECgcJBwAAAA==.',
['洒安']='洒安德洒:BAAALgAECggJCQAAAA==.',
['洗袜']='洗袜克:BAAALgAECgYJCgAAAA==.',
['洛圣']='洛圣都改猫王:BAAALgAECgMJAwAAAA==.',
['洛杉']='洛杉矶之魂:BAAALgAECgYJBwAAAA==.',
['洺甄']='洺甄:BAAALgAECggJBwAAAA==.',
['流水']='流水兮兮:BAAALgAECgcJCgAAAA==.',
['流风']='流风婉转丨德:BAAALgAECgQJAwAAAA==.',
['浅笺']='浅笺淡墨:BAAALgAECgYJBgAAAA==.',
['浅色']='浅色记弋:BAAALgAECgEJAQAAAA==.',
['浊酒']='浊酒:BAAALgAECgIJAgAAAA==.',
['海天']='海天翼:BAAALgAECgcJBwAAAA==.',
['海水']='海水好靓:BAAALgAFFAUJAQAAAA==.',
['涂山']='涂山卿:BAAALgAECgYJCwAAAA==.',
['涩问']='涩问是条狗:BAAALgAECgYJBgAAAA==.',
['涵珞']='涵珞依:BAAALgADCgUJBQAAAA==.',
['涵虚']='涵虚:BAAALgAECgUJBgAAAA==.',
['深吸']='深吸了一口气:BAAALgAECgMJBwAAAA==.',
['深圳']='深圳猎头:BAABLgAECn8YAAMZAAcJ4hVaUgBxAQAZAAcJ4BJaUgBxAQAaAAIJ7hCycQB3AAAAAA==.',
['混身']='混身是汉:BAAALgAECgIJAgAAAA==.',
['淼丶']='淼丶风行者:BAAALgAECgMJBAAAAA==.',
['淼淼']='淼淼归来:BAAALgAECgEJAQAAAA==.',
['渡月']='渡月橋:BAAALgAFFAIJBAAAAA==.',
['温温']='温温酱:BAAALgAFFAEJAgAAAA==.',
['渲暮']='渲暮笙央:BAAALgAECgQJAQAAAA==.',
['游泳']='游泳小能手:BAABLgAFFH8GAAINAAQJ0x7IBQB3AQANAAQJ0x7IBQB3AQAAAA==.',
['溜冰']='溜冰小能手:BAABLgAFFH8IAAMNAAUJvB79BQB0AQANAAQJvB79BQB0AQAXAAEJAACdEwBEAAAAAA==.',
['滑水']='滑水丶法爷:BAAALgAECgIJAgAAAA==.',
['滑进']='滑进去喽:BAAALgAECgIJAgAAAA==.',
['滚小']='滚小叔:BAAALgAFFAMJAwAAAA==.',
['滚来']='滚来滚去喵:BAACLgAFFH8TAAMNAAUJexByBgBsAQANAAUJexByBgBsAQAXAAEJAAAAAAAAAAAuAAQKfxcAAw0ABgkLGkssAKsBAA0ABgkYGEssAKsBABcABgmeFFgyAFoBAAAA.',
['滚滚']='滚滚袁:BAABLgAFFH8MAAIPAAQJ9A2VHwBKAQAPAAQJ9A2VHwBKAQAAAA==.',
['满天']='满天下灬:BAAALgAECgMJBAAAAA==.',
['滴地']='滴地德:BAAALgAECgMJAwAAAA==.',
['漫漫']='漫漫飞雪:BAAALgAECgIJBAAAAA==.',
['漱泉']='漱泉:BAAALgAECgEJAQAAAA==.',
['潘达']='潘达武僧:BAAALgAECgIJAgAAAA==.',
['灌篮']='灌篮小能手:BAABLgAFFH8OAAQNAAYJQhx+BQB8AQANAAQJQR9+BQB8AQAMAAEJ7gGjFwBBAAAXAAEJAAACFQA0AAAAAA==.',
['火之']='火之晨曦丶:BAAALgAECgEJAQAAAA==.',
['火星']='火星来的萌牛:BAAALgAECgcJBgAAAA==.',
['火雨']='火雨法:BAAALgADCgQJBAAAAA==.',
['灬六']='灬六饼灬:BAAALgAECgUJCQAAAA==.',
['灬尧']='灬尧尧丶:BAABLgAECn8XAAIjAAYJuxQjQwBrAQAjAAYJuxQjQwBrAQAAAA==.',
['灬惺']='灬惺惺相惜灬:BAAALgADCgUJBQAAAA==.',
['灬戦']='灬戦丶車灬:BAAALgAECgUJBQAAAA==.',
['灬捉']='灬捉捉:BAAALgAFFAEJAQAAAA==.',
['灬灵']='灬灵兒灬:BAAALgAFFAEJAQAAAA==.',
['灬英']='灬英雄本色:BAAALgADCgUJBQAAAA==.',
['灬银']='灬银翼灬:BAAALgAFFAIJBAAAAA==.',
['灬飘']='灬飘逸如溪灬:BAABLgAFFH8FAAIGAAUJwgp9CgCJAQAGAAUJwgp9CgCJAQAAAA==.',
['灰桥']='灰桥:BAABLgAFFH8FAAIFAAMJdgomLwDZAAAFAAMJdgomLwDZAAABLgAFFAUJBQAFAFUTAA==.',
['灵界']='灵界打击:BAAALgAFFAIJAwAAAA==.',
['灵肉']='灵肉魂:BAAALgAECgMJAwAAAA==.',
['灵音']='灵音:BAAALgAECgYJBwAAAA==.',
['灵魂']='灵魂七稚女:BAABLgAECn8VAAIPAAcJUxQJfADZAQAPAAcJUxQJfADZAQAAAA==.灵魂给我呗:BAAALgAFFAIJAwAAAA==.灵魂链接:BAAALgAECgEJAQAAAA==.',
['炭烤']='炭烤咕咕:BAAALgADCgYJBgAAAA==.',
['炸鱼']='炸鱼不好吃:BAABLgAECn8YAAMYAAYJIx8XCgAHAgAYAAYJ5RsXCgAHAgAWAAUJaiImOwC5AQABLgAFFAcJDQAbAM4ZAA==.',
['烈阳']='烈阳丶:BAAALgAECgQJBQAAAA==.',
['烬星']='烬星辰:BAAALgAFFAIJAgAAAA==.',
['热心']='热心市民小薛:BAAALgAECgUJBAAAAA==.',
['热情']='热情早已消散:BAAALgAECgEJAQAAAA==.',
['無欲']='無欲之誠:BAAALgAECgEJAQAAAA==.',
['焱火']='焱火炎:BAAALgADCgYJBwAAAA==.',
['煤气']='煤气罐子丶:BAAALgAECgQJDQAAAA==.',
['熊啊']='熊啊熊啊熊:BAAALgAFFAEJAQAAAA==.',
['熊大']='熊大丨丶:BAABLgAFFH8GAAIVAAIJshDYDACJAAAVAAIJshDYDACJAAAAAA==.',
['熊宝']='熊宝宝爪机:BAAALgAECgMJBAAAAA==.',
['熊德']='熊德扛他:BAAALgAFFAEJAQAAAA==.',
['熊本']='熊本小超:BAACLgAFFH8JAAMZAAMJkBvvBwAlAQAZAAMJkBvvBwAlAQAfAAEJXQoAAAAAAAAuAAQKfxoABBkACAnbIKkNANECABkABwkGI6kNANECABoABwlVHGgpANwBAB8AAwkCE8EkAKMAAAEuAAUUBAkFABoAPg8A.',
['熔岩']='熔岩魔神:BAAALgAECgYJDAABLgAECgkJCQAKAAAAAA==.',
['燕九']='燕九郎全垒打:BAACLgAFFH8RAAIeAAUJihbWAwC3AQAeAAUJihbWAwC3AQAuAAQKfx0ABB4ACQkZH2oEABYDAB4ACQkZH2oEABYDABEAAgk8AZZ4AEcAAB0AAQn4C+1fADgAAAAA.',
['爆头']='爆头小能手:BAAALgADCgUJBQAAAA==.',
['爱丽']='爱丽丝大魔王:BAAALgAFFAIJAgAAAA==.爱丽希雅:BAAALgAECgIJAgAAAA==.',
['爱吃']='爱吃牢饭的菜:BAABLgAFFH8NAAIeAAQJGRbAAwBWAQAeAAQJGRbAAwBWAQAAAA==.',
['爱喝']='爱喝拿铁:BAABLgAECn8eAAIgAAgJ/hz7HgAmAgAgAAgJ/hz7HgAmAgAAAA==.爱喝茉莉奶白:BAAALgAECgUJCgAAAA==.',
['爱撸']='爱撸猫灬头鹰:BAAALgAECgUJBwAAAA==.',
['爱活']='爱活阔落:BAAALgAECgEJAQAAAA==.',
['爱的']='爱的恰恰:BAAALgADCgEJAQAAAA==.',
['爵丨']='爵丨爺:BAAALgAECgEJAQAAAA==.',
['爸爸']='爸爸顶住:BAAALgADCgYJBgAAAA==.',
['牛古']='牛古力:BAAALgADCgUJBQAAAA==.',
['牛奶']='牛奶香脆:BAAALgADCgYJBgAAAA==.',
['牛巴']='牛巴里巴:BAAALgADCgEJAQAAAA==.',
['牛白']='牛白伯:BAAALgAECgYJEgAAAA==.',
['牢大']='牢大先干的:BAABLgAFFH8HAAMLAAQJZxdyDQChAAAGAAIJeyMNKQDQAAALAAIJUwtyDQChAAABLgAFFAQJDgALAHQjAA==.',
['牧瀨']='牧瀨紅莉栖:BAAALgAECgYJCgAAAA==.',
['牧雪']='牧雪逍遥:BAAALgADCgYJBgAAAA==.',
['狂兽']='狂兽啸天:BAAALgAECgMJAwAAAA==.',
['狂暴']='狂暴小牛仔:BAAALgADCgMJAwAAAA==.',
['狂派']='狂派黑少:BAAALgAECgYJCAAAAA==.',
['狂疯']='狂疯虎豹骑:BAAALgAECgEJAQAAAA==.狂疯麦克斯:BAAALgAECgEJAQAAAA==.',
['狂野']='狂野女孩:BAAALgADCgEJAQAAAA==.',
['狐小']='狐小满:BAAALgADCgIJAgAAAA==.',
['狗命']='狗命要紧:BAAALgAECgYJCAAAAA==.',
['狗带']='狗带小登:BAAALgAECgIJAwAAAA==.',
['狙撃']='狙撃者:BAAALgAFFAMJBAAAAA==.',
['独儿']='独儿的怒:BAABLgAECn8YAAMkAAcJuQxZFQAdAQAkAAcJuQxZFQAdAQASAAMJ6gIwbgBmAAAAAA==.',
['独行']='独行闪电侠:BAABLgAECn8cAAIPAAcJDx2LSgBXAgAPAAcJDx2LSgBXAgAAAA==.独行闪电猪:BAAALgADCgYJBgAAAA==.',
['狸狸']='狸狸牧可爱捏:BAAALgAECgMJAwAAAA==.',
['狼牙']='狼牙之刺:BAAALgAECgUJBQAAAA==.',
['狼色']='狼色不射:BAAALgAFFAIJAgABLgAFFAIJAgAKAAAAAA==.',
['猛禽']='猛禽利爪:BAAALgADCgMJAwAAAA==.',
['猪儿']='猪儿会上树:BAAALgAECgcJDAAAAA==.',
['猪猪']='猪猪牧:BAAALgAFFAIJAgAAAA==.',
['猫公']='猫公子:BAAALgADCgUJBQAAAA==.',
['猫猫']='猫猫翻滚:BAAALgAECgYJBgAAAA==.猫猫躲:BAAALgAFFAEJAQAAAA==.',
['猴哥']='猴哥真坑啊:BAAALgADCgcJBgAAAA==.',
['玄学']='玄学小黑手:BAAALgAECgYJBgAAAA==.',
['玄玑']='玄玑丨星枢:BAAALgAECgIJAgAAAA==.',
['玄色']='玄色:BAAALgAECgEJAQAAAA==.',
['玉笥']='玉笥犹残药:BAAALgAECgEJAQAAAA==.',
['玉藻']='玉藻黔:BAAALgAECgYJBgAAAA==.',
['王二']='王二狗:BAAALgAECgQJBwAAAA==.',
['王怼']='王怼怼丶:BAAALgAECgYJCgAAAA==.',
['王石']='王石虎:BAAALgAECgIJAgAAAA==.',
['王阿']='王阿美:BAAALgAECgYJEgAAAA==.',
['玖伍']='玖伍壹:BAAALgAECgUJBQAAAA==.',
['玛格']='玛格丽塔:BAAALgADCgMJAQAAAA==.玛格会魔法:BAAALgAECgEJAQAAAA==.',
['玛莲']='玛莲霓娅:BAAALgAECgUJBQAAAA==.',
['玥玥']='玥玥儿:BAAALgAECgIJAgAAAA==.',
['玫瑰']='玫瑰多少钱:BAAALgAECgYJDgAAAA==.玫瑰是我偷:BAABLgAFFH8GAAMjAAIJxhlCFACfAAAjAAIJxhlCFACfAAAQAAEJPSOSKwBqAAAAAA==.玫瑰荔枝冻冻:BAAALgAECgEJAQAAAA==.',
['珊蒂']='珊蒂斯丶月咏:BAAALgAECgkJEAAAAA==.',
['琪露']='琪露诺大人:BAAALgAECgIJAgAAAA==.',
['瑞不']='瑞不是踹:BAABLgAFFH8FAAIPAAMJiQwRMAD1AAAPAAMJiQwRMAD1AAABLgAFFAcJBQAPANIGAA==.',
['瑞恩']='瑞恩赫尔:BAAALgAECgMJAwAAAA==.',
['瑟拉']='瑟拉娜丶冰箭:BAAALgAECgIJAwAAAA==.瑟拉薇恩:BAAALgAFFAIJAwAAAA==.',
['瑟曦']='瑟曦:BAAALgADCgUJBQAAAA==.',
['瑤瑤']='瑤瑤妖精:BAABLgAFFH8FAAIFAAUJHA0/CQCHAQAFAAUJHA0/CQCHAQAAAA==.',
['璀枯']='璀枯拉朽:BAAALgADCgQJBAAAAA==.',
['璃月']='璃月刻晴:BAAALgAECgcJCAAAAA==.',
['瓦丝']='瓦丝琪女士:BAABLgAFFH8GAAIDAAIJ5yU1BwDMAAADAAIJ5yU1BwDMAAAAAA==.',
['瓦里']='瓦里安思聪:BAAALgAECgYJBgAAAA==.',
['甑阿']='甑阿牛:BAAALgAECgUJBQAAAA==.',
['生与']='生与死的徘徊:BAAALgAECgEJAQAAAA==.',
['生命']='生命缚誓者:BAAALgAECgEJAQABLgAFFAIJAgAKAAAAAA==.',
['用剣']='用剣问好:BAAALgADCgIJAgAAAA==.',
['用屁']='用屁屁转圈:BAAALgAFFAIJBAABLgAFFAUJEQAeAIoWAA==.',
['申留']='申留真:BAABLgAFFH8FAAIGAAQJXg/qBgBQAQAGAAQJXg/qBgBQAQAAAA==.',
['电奶']='电奶电:BAAALgAFFAQJBAAAAA==.',
['电气']='电气牛:BAAALgAECgQJBQAAAA==.',
['疏影']='疏影弥漫:BAAALgAECgMJAwAAAA==.',
['疯摸']='疯摸万千妇女:BAAALgAECgEJAQAAAA==.疯摸万千少女:BAAALgAECgEJAQAAAA==.疯摸万千靓女:BAAALgAECgYJCQAAAA==.',
['疯癫']='疯癫不痴呆:BAAALgAECgcJEgAAAA==.',
['登丶']='登丶等灯等灯:BAAALgADCgYJBgAAAA==.',
['發光']='發光的石板:BAACLgAFFH8IAAISAAQJxxXZCABVAQASAAQJxxXZCABVAQAuAAQKfyAAAhIACAnEH1MKAPACABIACAnEH1MKAPACAAAA.',
['白发']='白发的邪:BAAALgAECgQJCgAAAA==.',
['白嫖']='白嫖怪:BAAALgAECgcJCwAAAA==.',
['白晶']='白晶龙:BAAALgAECgcJBwAAAA==.',
['白术']='白术:BAAALgAECgIJAgAAAA==.',
['白洁']='白洁:BAAALgAECgQJCgAAAA==.',
['白瓷']='白瓷梅子汤:BAAALgAECgEJAQAAAA==.',
['白给']='白给骑吴培茄:BAAALgAECgYJDwAAAA==.',
['白色']='白色獠牙:BAAALgAFFAQJBAAAAA==.',
['白虎']='白虎猖狂:BAAALgAECgYJBgAAAA==.',
['白鸽']='白鸽丶:BAAALgAFFAEJAQAAAA==.',
['百亿']='百亿少女的梦:BAAALgAECgQJBAAAAA==.',
['百里']='百里风实花:BAAALgAECgcJCQABLgAFFAIJBAAKAAAAAA==.',
['皇家']='皇家玫瑰:BAAALgAECgMJAwAAAA==.',
['皮毛']='皮毛火漂:BAABLgAFFH8GAAIFAAIJDhBrQwCcAAAFAAIJDhBrQwCcAAAAAA==.',
['盎然']='盎然:BAAALgADCgYJBgAAAA==.',
['盖里']='盖里:BAAALgAECgIJAgAAAA==.',
['盾盾']='盾盾吃得好:BAAALgAECgUJCAAAAA==.',
['真索']='真索瑞森大帝:BAABLgAECn8gAAQbAAgJQBqTCwBVAgAbAAgJBhqTCwBVAgAWAAcJsw9EPQCvAQAYAAQJyQ62IgDXAAAAAA==.',
['真言']='真言奶宝:BAAALgAECgQJBAAAAA==.',
['瞄准']='瞄准丶那只熊:BAAALgAECgEJAQAAAA==.',
['矢泽']='矢泽妮可:BAACLgAFFH8LAAIfAAQJkxQuAQBuAQAfAAQJkxQuAQBuAQAuAAQKfx8AAh8ACAkRIu0CAAUDAB8ACAkRIu0CAAUDAAAA.',
['知你']='知你是梦:BAAALgAECgYJBgAAAA==.',
['石头']='石头儿空空:BAAALgAECgUJBAAAAA==.',
['破碎']='破碎的星光:BAAALgAECgEJAQAAAA==.破碎的梦:BAAALgADCgYJBgAAAA==.',
['硬逼']='硬逼:BAAALgAECgMJBAAAAA==.',
['碎梦']='碎梦蝶舞:BAAALgADCgMJAwAAAA==.',
['碰哭']='碰哭精:BAAALgAECggJEwAAAA==.',
['磨爪']='磨爪:BAEBLgAECn8gAAMiAAgJuhYqCAB+AQAiAAgJuhYqCAB+AQAgAAIJwgQ4kwBPAAAAAA==.',
['神一']='神一歪歪:BAAALgAECgEJAQAAAA==.',
['神力']='神力加特林:BAAALgAECgYJCQAAAA==.',
['神圣']='神圣钉子裤:BAAALgAECgEJAQAAAA==.',
['神枪']='神枪无二打:BAAALgAECgQJBQAAAA==.神枪李书文:BAABLgAFFH8GAAIXAAQJMhDhBABAAQAXAAQJMhDhBABAAQAAAA==.',
['神童']='神童花百洛:BAAALgAECgUJBQAAAA==.',
['神蕴']='神蕴素心:BAAALgAFFAEJAgAAAA==.',
['禁咒']='禁咒法则:BAAALgAECgEJAQAAAA==.',
['福宝']='福宝骑士:BAAALgAECgEJAQAAAA==.',
['福氣']='福氣:BAAALgAECgQJBAAAAA==.',
['秘雕']='秘雕五不全:BAAALgAFFAEJAgAAAA==.',
['空即']='空即是空:BAAALgAECgYJBwAAAA==.',
['空小']='空小栢:BAAALgAECgkJDwAAAA==.',
['空虚']='空虚精灵:BAAALgAECgYJCAAAAA==.',
['空谷']='空谷残聲:BAABLgAFFH8FAAMlAAUJPSAZAACjAQAlAAQJPSAZAACjAQAOAAEJAAB+GQA2AAAAAA==.',
['窝里']='窝里横:BAAALgAECgQJBAABLgAFFAQJCgAFADcfAA==.',
['窦臂']='窦臂饰腻:BAAALgAECgYJBgAAAA==.',
['立华']='立华奏:BAAALgADCgQJBAAAAA==.',
['立定']='立定站好:BAAALgAFFAMJAwAAAA==.',
['章临']='章临凤:BAAALgAFFAIJAgAAAA==.',
['竭心']='竭心光环:BAABLgAECn8ZAAMJAAgJriHtAAALAwAJAAgJriHtAAALAwALAAEJAABNaQA/AAAAAA==.',
['竹喧']='竹喧灬归浣女:BAABLgAFFH8FAAIaAAUJUhcKBwCsAQAaAAUJUhcKBwCsAQAAAA==.',
['竹影']='竹影清风舞剑:BAAALgAECgUJCAAAAA==.',
['笑出']='笑出猪声:BAACLgAFFH8JAAIPAAMJXCRaCgBLAQAPAAMJXCRaCgBLAQAuAAQKfxUAAg8ABgk7JTY5AJECAA8ABgk7JTY5AJECAAEuAAUUBAkGAA8A9BkA.',
['笑白']='笑白海:BAAALgAECgQJBwAAAA==.',
['等你']='等你在秋季:BAAALgAECgEJAQAAAA==.',
['等君']='等君影袭决:BAAALgAECgYJBwAAAA==.',
['简拉']='简拉基次德:BAAALgAECgEJAQAAAA==.',
['米奈']='米奈丨希尔:BAAALgAECgYJCAAAAA==.',
['米粒']='米粒儿:BAAALgAECgEJAQAAAA==.',
['粉色']='粉色合剂:BAAALgAFFAIJBAAAAA==.',
['粉黛']='粉黛丶嫣然笑:BAAALgAECgIJAwAAAA==.',
['粥粥']='粥粥丶术:BAABLgAFFH8BAAIGAAEJ4gPMUABFAAAGAAEJ4gPMUABFAAAAAA==.',
['紅蓮']='紅蓮石:BAAALgAECgEJAQAAAA==.',
['紫涵']='紫涵丶:BAAALgAECgcJBwAAAA==.',
['紫轩']='紫轩灬:BAAALgAECgYJCwAAAA==.',
['红手']='红手大聪明:BAAALgADCgEJAQAAAA==.',
['红牛']='红牛小斌:BAAALgAECgQJBAAAAA==.',
['红色']='红色天花板:BAAALgAFFAEJAQAAAA==.红色猫德:BAABLgAECn8fAAIFAAgJBR/IHADSAgAFAAgJBR/IHADSAgAAAA==.',
['红豆']='红豆最相思丶:BAAALgAECgYJDAAAAA==.',
['纯阳']='纯阳沈剑心:BAAALgAECgIJAgAAAA==.',
['纸灰']='纸灰灰丶:BAAALgAECgcJDgABLgAECggJHwARAGMZAA==.',
['纸白']='纸白白丶:BAABLgAECn8fAAMRAAgJYxn/EABbAgARAAgJYxn/EABbAgAdAAgJuhVOCgBLAQAAAA==.',
['绅丨']='绅丨士:BAABLgAECn8YAAIVAAYJCwNPjwCzAAAVAAYJCwNPjwCzAAAAAA==.',
['织姬']='织姬:BAAALgADCgEJAQAAAA==.',
['终之']='终之人:BAAALgAECgUJBgAAAA==.',
['终鸡']='终鸡:BAAALgAECgQJBAAAAA==.',
['结月']='结月織:BAAALgAFFAEJAQAAAA==.',
['绘梨']='绘梨衣丶:BAABLgAFFH8RAAIPAAQJhhLpHgBOAQAPAAQJhhLpHgBOAQAAAA==.',
['维哆']='维哆莉亚:BAAALgAECgEJAgAAAA==.',
['绿皮']='绿皮小苦力:BAAALgADCgcJBwAAAA==.',
['绿风']='绿风丶风行者:BAAALgAECgUJCgAAAA==.',
['罐头']='罐头:BAAALgAFFAEJAQAAAA==.',
['网友']='网友大司马:BAAALgAECgYJBgAAAA==.',
['网瘾']='网瘾治疗带师:BAAALgAECgYJBgAAAA==.',
['罩一']='罩一罩:BAAALgADCgcJDQAAAA==.',
['羊八']='羊八井:BAAALgADCgYJCgAAAA==.',
['羽落']='羽落倾辰:BAAALgAECgYJDgAAAA==.',
['羿父']='羿父:BAAALgAECgQJBAAAAA==.',
['翻滚']='翻滚吧小蝌蚪:BAAALgAECgYJAgAAAA==.',
['翼丶']='翼丶心:BAAALgAECgcJCwAAAA==.',
['老一']='老一的呆:BAAALgAECgQJAwAAAA==.',
['老人']='老人与竹:BAAALgAECgMJBAAAAA==.',
['老北']='老北京豆汁儿:BAAALgAECgMJBAAAAA==.',
['老大']='老大的牛牛了:BAAALgAECgIJAgAAAA==.',
['老板']='老板喊你加班:BAAALgAECgMJBgAAAA==.',
['老爷']='老爷带你走:BAAALgAECgIJAgAAAA==.',
['老虎']='老虎木耳菜:BAAALgAFFAIJBAAAAA==.',
['老雷']='老雷御用奶骑:BAAALgAECgQJBQAAAA==.',
['聖丶']='聖丶贖:BAAALgAECgYJDgABLgAFFAQJCwAXAEgaAA==.',
['聖光']='聖光照你碧芝:BAAALgAECgQJAwAAAA==.',
['肆意']='肆意野蛮丶:BAAALgAECgYJCwAAAA==.',
['肥肥']='肥肥鲨丶:BAAALgAECgYJBgABLgAECggJCAAKAAAAAA==.',
['胖德']='胖德鲁:BAAALgADCgEJAQAAAA==.',
['胖骑']='胖骑士:BAACLgAFFH8HAAMQAAMJgxmAJACjAAAQAAIJ7xeAJACjAAAjAAEJHAoAAAAAAAAuAAQKfxgAAxAACAmBEs5OAPYBABAACAmBEs5OAPYBACMABgl5DW5PADsBAAAA.',
['自信']='自信的奶毛:BAAALgAFFAEJAQAAAA==.',
['自在']='自在由心:BAAALgADCgMJAwAAAA==.',
['自爆']='自爆拖拉机:BAAALgAECgcJEQAAAA==.',
['臻棒']='臻棒:BAAALgAECgQJBAABLgAECgYJCgAKAAAAAA==.',
['舊莳']='舊莳茪灬:BAAALgAECgYJBwAAAA==.',
['舍我']='舍我骑谁:BAAALgAECgYJCwAAAA==.',
['舞风']='舞风漫月:BAAALgADCgMJAwAAAA==.',
['艰难']='艰难依旧坚持:BAAALgAECgMJAwAAAA==.',
['艾什']='艾什凡观察员:BAAALgAECgIJBAAAAA==.',
['艾伦']='艾伦耶格尔:BAAALgADCgYJBgAAAA==.',
['艾璐']='艾璐恩的泪石:BAAALgAECgYJCwAAAA==.',
['芙兰']='芙兰丶:BAAALgADCgYJBgAAAA==.',
['芜湖']='芜湖小德:BAAALgAECgEJAQAAAA==.',
['芥末']='芥末味曲奇:BAAALgADCgYJBgAAAA==.',
['花仙']='花仙獸:BAAALgAECgYJCQAAAA==.',
['花女']='花女皇波赛姆:BAAALgAFFAIJAgAAAA==.',
['花落']='花落雨夜:BAAALgAFFAIJBAAAAA==.',
['芹則']='芹則多摩熊:BAAALgAECgYJCAAAAA==.',
['苍白']='苍白之瞳:BAACLgAFFH8FAAIFAAIJYg3lGACkAAAFAAIJYg3lGACkAAAuAAQKfyEAAwUACAlIF6Q9AEECAAUACAlIF6Q9AEECAA4AAQksC8NHACkAAAAA.',
['苍穹']='苍穹天刃:BAAALgAECgQJBQAAAA==.',
['苏尔']='苏尔特洛奇:BAAALgAECgYJBwAAAA==.',
['苏帕']='苏帕萨亚锦丶:BAAALgAFFAEJAQAAAA==.',
['苏打']='苏打柠檬:BAAALgAFFAIJAgAAAA==.',
['若丶']='若丶相惜:BAAALgAFFAIJAgAAAA==.',
['若月']='若月光:BAAALgADCgYJBgAAAA==.',
['若游']='若游龙:BAAALgADCgEJAQAAAA==.',
['若葉']='若葉睦:BAAALgAECgQJBAAAAA==.',
['范阿']='范阿尔特:BAAALgAFFAMJAwAAAA==.',
['茜茜']='茜茜的诬妖王:BAAALgADCgMJAwABLgAECgIJAgAKAAAAAA==.',
['荆棘']='荆棘岚月:BAACLgAFFH8FAAIQAAMJlBn/EAAdAQAQAAMJlBn/EAAdAQAuAAQKfyAAAxAACAl1IuwRAAIDABAACAl1IuwRAAIDACEAAglhGPQrAK0AAAAA.荆棘谷的雨:BAAALgAECgcJBwAAAA==.',
['荆芥']='荆芥柠檬:BAAALgAFFAEJAQAAAA==.',
['草木']='草木依旧:BAABLgAFFH8GAAIFAAMJEwZREQDnAAAFAAMJEwZREQDnAAAAAA==.',
['莫浅']='莫浅璃:BAAALgAECgcJBgABLgAFFAUJBQAVAJkcAA==.',
['莫西']='莫西阳光:BAAALgAECgEJAQAAAA==.',
['莫轻']='莫轻儛:BAAALgAFFAEJAgAAAA==.',
['菠鲁']='菠鲁买:BAAALgAECgYJBgABLgAECgcJAQAKAAAAAA==.',
['菲洛']='菲洛米娜:BAAALgAECgQJBAAAAA==.',
['菻芯']='菻芯茹的姐姐:BAAALgAECgIJAgAAAA==.',
['萌属']='萌属性的猫:BAAALgAECgQJBwAAAA==.',
['萌新']='萌新丿就是我:BAAALgAECgQJBAAAAA==.萌新小薯条:BAAALgADCggJEAAAAA==.萌新小豆芽:BAAALgAECgUJBQAAAA==.',
['萨姆']='萨姆雷龙:BAAALgAECgkJEAAAAA==.',
['萨布']='萨布丽娜:BAAALgAECgQJBQAAAA==.',
['萨满']='萨满奶我:BAAALgAFFAEJAQAAAA==.',
['萨萨']='萨萨不飒:BAAALgAECgYJBgAAAA==.萨萨弦影:BAAALgAECgcJBwAAAA==.',
['落云']='落云宗宋玉:BAAALgAECgEJAQAAAA==.',
['落后']='落后就要挨打:BAAALgAFFAEJAQAAAA==.',
['落子']='落子天元:BAAALgAECgEJAgAAAA==.',
['落白']='落白:BAAALgAFFAIJAgAAAA==.',
['落雨']='落雨天空:BAAALgAFFAEJAgAAAA==.',
['蒸饺']='蒸饺儿:BAAALgAECgcJCQAAAA==.',
['蓝染']='蓝染忽右介灬:BAAALgAECgUJBQAAAA==.',
['蓝猫']='蓝猫埖埖:BAAALgADCgMJAwAAAA==.',
['蓝瑟']='蓝瑟:BAAALgAECgYJDAAAAA==.',
['蓝胖']='蓝胖子伤害高:BAAALgAFFAEJAQAAAA==.',
['蓝花']='蓝花猫猫:BAAALgADCgQJBAAAAA==.',
['蓝莓']='蓝莓糕:BAAALgADCgYJBgAAAA==.',
['蔓蔓']='蔓蔓奶黄包:BAAALgADCgMJAwAAAA==.',
['蕾茉']='蕾茉妮雅:BAAALgAECgIJAgAAAA==.',
['薄暮']='薄暮安禅:BAAALgAECgEJAQAAAA==.',
['藏马']='藏马:BAAALgAECgEJAQAAAA==.',
['蘑菇']='蘑菇会下雨:BAAALgAECgYJDgAAAA==.',
['虎嘯']='虎嘯風生:BAAALgAECgQJBQAAAA==.',
['虎皮']='虎皮蛋黄派:BAAALgADCggJCAAAAA==.',
['虚星']='虚星陨坠:BAACLgAFFH8TAAIHAAUJch5tBQDSAQAHAAUJch5tBQDSAQAuAAQKfxgAAgcACAmqG8gsAEoCAAcACAmqG8gsAEoCAAAA.',
['虞山']='虞山掌萌人:BAAALgAECgQJBAAAAA==.',
['虾米']='虾米我来了:BAAALgAECgYJBgAAAA==.',
['蛋疼']='蛋疼的网意:BAAALgADCgYJBgAAAA==.',
['蛛丝']='蛛丝麻吉:BAAALgADCgEJAQAAAA==.',
['蛮姨']='蛮姨:BAAALgADCgEJAQAAAA==.',
['蝶澜']='蝶澜:BAAALgADCgQJBAAAAA==.',
['血刃']='血刃者邵拉达:BAAALgAECgEJAQABLgAFFAEJAQAKAAAAAA==.',
['血地']='血地之魂:BAAALgAECgIJAwAAAA==.',
['血月']='血月骑士残风:BAAALgAECggJCwAAAA==.',
['血血']='血血色豆腐:BAAALgAECgkJCQAAAA==.',
['血骑']='血骑士月煌:BAAALgAECgEJAQAAAA==.',
['街上']='街上的宝剑:BAAALgAECgYJBwAAAA==.',
['街头']='街头霸王周卓:BAAALgADCgEJAQAAAA==.',
['被神']='被神卷顾的人:BAAALgAECgYJCQAAAA==.',
['裂蹄']='裂蹄牛伤害高:BAAALgAFFAIJBAAAAA==.',
['装死']='装死不死:BAAALgAECgcJAQABLgAFFAUJAQAKAAAAAA==.',
['裤衩']='裤衩焦黄儿:BAAALgAECgYJCwAAAA==.',
['裤里']='裤里丝:BAAALgAECgYJDAAAAA==.',
['西乡']='西乡塘码王:BAAALgAECgIJAgAAAA==.',
['西扎']='西扎:BAAALgAECgYJBgAAAA==.',
['西西']='西西子:BAAALgAECgEJAQAAAA==.',
['要吃']='要吃香菜:BAAALgAECgMJAwAAAA==.',
['要往']='要往何处去:BAACLgAFFH8FAAIQAAQJjhKyCwBOAQAQAAQJjhKyCwBOAQAuAAQKfxQAAhAACAnEIBURAAcDABAACAnEIBURAAcDAAAA.',
['詪黃']='詪黃詪嚗力:BAAALgAECgUJBQABLgAFFAYJFAAgANUFAA==.',
['让我']='让我变个球:BAAALgAECgMJBAAAAA==.',
['该死']='该死的甜美:BAAALgAECgEJAQAAAA==.',
['诺缈']='诺缈:BAAALgAECgUJDgAAAA==.',
['诺雨']='诺雨:BAAALgAECgcJDQAAAA==.',
['谁关']='谁关的灯:BAAALgAECgMJAwAAAA==.',
['谜尔']='谜尔瓦娜斯:BAAALgADCgEJAQAAAA==.',
['谦虚']='谦虚的蛋蛋丶:BAAALgAECgYJCgAAAA==.',
['豆儿']='豆儿芽的土灵:BAAALgADCgMJAwAAAA==.豆儿芽的术爹:BAAALgAECgYJBwAAAA==.',
['贤者']='贤者叙事遥:BAAALgAECgYJDAAAAA==.',
['贵州']='贵州茅台:BAAALgADCgEJAQAAAA==.',
['赛尔']='赛尔瑟娅:BAAALgAECgQJBAABLgAFFAEJAQAKAAAAAA==.',
['赵相']='赵相机:BAAALgADCgEJAQAAAA==.',
['赵腊']='赵腊月:BAAALgAECgIJAgAAAA==.',
['起起']='起起丶:BAABLgAECn8XAAMjAAkJVB5OAAA4AwAjAAkJVB5OAAA4AwAQAAUJEwsczgDtAAAAAA==.',
['超爱']='超爱小苏:BAAALgAECgQJBgAAAA==.',
['超级']='超级厉害:BAAALgAECgMJAwAAAA==.',
['趴趴']='趴趴灬熊:BAAALgAFFAIJBAAAAA==.',
['路边']='路边小德:BAAALgAECgYJBgAAAA==.',
['踏纱']='踏纱:BAABLgAECn8gAAIQAAgJvSFrEgD/AgAQAAgJvSFrEgD/AgAAAA==.',
['踢你']='踢你下三路:BAAALgADCgIJAgAAAA==.',
['踩踩']='踩踩背:BAAALgADCgYJBgAAAA==.',
['蹄儿']='蹄儿朝西:BAAALgAECgEJAQAAAA==.',
['輪盤']='輪盤丶戮槍舞:BAAALgAECgYJBwABLgAFFAQJCwAXAEgaAA==.',
['轧死']='轧死一只猫:BAAALgAECgUJBQAAAA==.',
['轨道']='轨道炮叁号:BAAALgADCgcJBwAAAA==.',
['转世']='转世灵峥:BAACLgAFFH8NAAIgAAQJjQw8CADQAAAgAAQJjQw8CADQAAAuAAQKfy8AAyAACAl8IRMHAAIDACAACAl8IRMHAAIDACIAAQk8DdGNACoAAAAA.转世灵笙:BAAALgAECgEJAQAAAA==.',
['辕门']='辕门射戟:BAAALgAECgYJCAAAAA==.',
['辣真']='辣真滴牛批:BAAALgADCgEJAQAAAA==.',
['过去']='过去过不去:BAAALgAECgIJAwAAAA==.过去过不去丶:BAAALgAECgMJAwAAAA==.',
['还是']='还是我杀的:BAAALgAECgIJAwAAAA==.',
['这是']='这是一条龙:BAAALgAFFAEJAQAAAA==.',
['追随']='追随大智慧:BAAALgAFFAEJAQAAAA==.',
['退役']='退役人员:BAAALgAECgEJAQAAAA==.',
['逍遥']='逍遥啊:BAACLgAFFH8LAAIEAAQJyh5nAACJAQAEAAQJyh5nAACJAQAuAAQKfx8AAgQACAmBJW8AAFsDAAQACAmBJW8AAFsDAAAA.逍遥游僧:BAAALgAECgUJCAAAAA==.逍遥阿:BAAALgAECgEJAQABLgAFFAQJCwAEAMoeAA==.',
['道士']='道士十伍狗:BAAALgAECgYJCgAAAA==.',
['遗失']='遗失的三围:BAAALgAECgEJAQAAAA==.遗失的奶水:BAAALgAECgEJAQABLgAFFAIJAgAKAAAAAA==.遗失的奶氺:BAAALgAFFAIJAgAAAA==.遗失的妹子:BAAALgAFFAIJAgABLgAFFAIJAgAKAAAAAA==.遗失的爱人:BAAALgAECgEJAgABLgAFFAIJAgAKAAAAAA==.',
['邓架']='邓架先:BAAALgAFFAIJAgAAAA==.',
['那个']='那个战仕:BAAALgADCgEJAQAAAA==.',
['那咋']='那咋了:BAAALgAFFAIJAgAAAA==.',
['那彳']='那彳亍吧:BAAALgAECgYJCAAAAA==.',
['郭二']='郭二呆:BAACLgAFFH8FAAIPAAIJrx63NQDAAAAPAAIJrx63NQDAAAAuAAQKfx0AAg8ACAl+IOsqAMcCAA8ACAl+IOsqAMcCAAAA.',
['酒以']='酒以成欢:BAAALgAECgYJBgAAAA==.',
['酒酿']='酒酿见手青:BAAALgAECgYJBgAAAA==.',
['酱板']='酱板鸭:BAAALgAECgUJBQAAAA==.',
['酷酷']='酷酷的兔兔:BAAALgAECgYJCwAAAA==.',
['酸汤']='酸汤丝娃娃:BAAALgAFFAIJAgAAAA==.',
['醉剑']='醉剑:BAAALgAECgYJDAABLgAFFAUJAQAKAAAAAA==.',
['醉卧']='醉卧泪沾裳:BAAALgAECgQJBgAAAA==.',
['醉灬']='醉灬箭:BAAALgAECgYJBgAAAA==.',
['醉霧']='醉霧丶織風:BAABLgAFFH8LAAIXAAQJSBrsAABqAQAXAAQJSBrsAABqAQAAAA==.',
['重海']='重海丶长鲸:BAAALgAECgQJCQAAAA==.',
['重生']='重生小球:BAAALgAECgYJCgAAAA==.',
['野性']='野性柠檬:BAAALgAFFAIJAwAAAA==.',
['野格']='野格丶炸蛋:BAAALgAFFAIJBAABLgAFFAQJDAAPAPQNAA==.',
['鐵劑']='鐵劑丶紅塵:BAAALgAECggJEAAAAA==.',
['钢板']='钢板柠檬:BAAALgAECgYJCAAAAA==.',
['钢铁']='钢铁之沁:BAAALgADCgEJAQAAAA==.',
['铃木']='铃木心春丶:BAAALgAFFAIJAwAAAA==.',
['银发']='银发斯嘉萨:BAABLgAECn8WAAIFAAcJniUKIADCAgAFAAcJniUKIADCAgABLgAFFAYJFAAFADIkAA==.',
['银翼']='银翼:BAAALgAECgcJDgAAAA==.',
['银龙']='银龙王:BAAALgAECgUJBwAAAA==.',
['铺路']='铺路大爷:BAAALgAECgQJBAAAAA==.',
['锦上']='锦上花灬:BAAALgADCgMJAwAAAA==.',
['镇魂']='镇魂军丨潮汐:BAAALgAECgQJBAAAAA==.',
['镜丶']='镜丶炽羽之赫:BAAALgADCgEJAQAAAA==.',
['长风']='长风归处:BAAALgAECgQJBAAAAA==.',
['门三']='门三儿:BAAALgAECgcJAQAAAA==.',
['闻花']='闻花答歌名:BAABLgAFFH8IAAIZAAMJaBn3DwDIAAAZAAMJaBn3DwDIAAAAAA==.',
['防不']='防不圣防:BAAALgAFFAIJAgAAAA==.',
['阳见']='阳见惠凪:BAAALgAFFAIJBAAAAA==.',
['阴影']='阴影利刃:BAAALgAECgYJAgAAAA==.',
['阴阴']='阴阴德就是我:BAAALgAECgQJBAAAAA==.',
['阿修']='阿修罗霸凤拳:BAAALgAECgYJBwAAAA==.',
['阿历']='阿历航德:BAAALgAECgYJEAAAAA==.',
['阿可']='阿可萌德:BAABLgAECn8WAAISAAcJRx4+FwBRAgASAAcJRx4+FwBRAgAAAA==.',
['阿妹']='阿妹快放手:BAAALgADCgEJAQAAAA==.',
['阿嬷']='阿嬷手作:BAAALgAECgcJBAAAAA==.',
['阿尓']='阿尓泰尔:BAAALgAECgYJAwAAAA==.',
['阿氪']='阿氪蒙德:BAAALgAECgEJAQAAAA==.',
['阿瞒']='阿瞒:BAAALgADCgMJAwAAAA==.',
['阿矛']='阿矛:BAAALgAECgYJDgAAAA==.',
['阿美']='阿美丽卡:BAAALgAECgQJBAAAAA==.',
['阿莱']='阿莱斯哈特:BAAALgAECgMJBAAAAA==.',
['陆仁']='陆仁乙:BAAALgAECgEJAQAAAA==.',
['陈瞎']='陈瞎子一:BAAALgAFFAYJBAAAAA==.陈瞎子三:BAABLgAFFH8IAAIHAAUJVAmQFgAdAQAHAAUJVAmQFgAdAQAAAA==.陈瞎子二:BAAALgAFFAUJBAAAAA==.',
['陈陈']='陈陈的陈:BAAALgAFFAIJAwAAAA==.',
['随丶']='随丶心:BAAALgAECgQJBAAAAA==.',
['随机']='随机信仰:BAAALgAECgkJBAAAAA==.',
['随风']='随风祭司之怒:BAAALgAECgYJCQAAAA==.',
['隐世']='隐世少年:BAAALgAECgUJCQAAAA==.',
['雀神']='雀神:BAAALgAECgUJBQAAAA==.',
['集合']='集合石大帝:BAAALgAFFAIJAgAAAA==.',
['雨下']='雨下整晚:BAAALgAFFAEJAQAAAA==.',
['雨中']='雨中镇魂曲:BAAALgAECgYJCwAAAA==.',
['雨亻']='雨亻希流:BAAALgAECgYJBgAAAA==.',
['雨啸']='雨啸:BAAALgADCgYJBgAAAA==.',
['雨夜']='雨夜灬月:BAAALgADCgYJBgAAAA==.',
['雪糕']='雪糕没有热量:BAAALgAECgYJCgAAAA==.',
['零丶']='零丶心:BAAALgAECgUJBQAAAA==.',
['零骑']='零骑:BAAALgAECgYJBgAAAA==.',
['雷电']='雷电法亡:BAAALgAFFAIJAgABLgAFFAYJEQAPAI8lAA==.',
['雷神']='雷神伊德:BAAALgAECgIJBAAAAA==.',
['雾散']='雾散丶不见你:BAAALgAECgcJCAAAAA==.',
['雾野']='雾野千寻:BAABLgAECn8VAAIGAAcJ0RpNRgD4AQAGAAcJ0RpNRgD4AQABLgAFFAYJDwAGALsgAA==.',
['霜夷']='霜夷:BAAALgAECgYJBgAAAA==.',
['霜寒']='霜寒之月:BAAALgAECgcJEAAAAA==.',
['青如']='青如晓天丶:BAAALgAECgEJAQAAAA==.',
['青豌']='青豌豆布丁:BAAALgAECgIJAwAAAA==.',
['静乔']='静乔斯达:BAAALgAECgYJDAAAAA==.',
['非我']='非我执笔:BAAALgAECgEJAQAAAA==.',
['非洲']='非洲势力:BAAALgAECgkJBgAAAA==.非洲老龙鸣:BAAALgAECgMJBAAAAA==.',
['面包']='面包机器:BAAALgADCgUJBQAAAA==.',
['韩立']='韩立:BAAALgAECgEJAQAAAA==.',
['頽廢']='頽廢旳尛徫:BAAALgAECgcJCQAAAA==.',
['颍上']='颍上彭于晏:BAAALgADCgYJBgAAAA==.',
['風轻']='風轻灬雲淡:BAAALgAECgUJBgAAAA==.',
['风之']='风之伊薇:BAAALgADCgEJAQAAAA==.风之天堂:BAABLgAECn8fAAMZAAgJXCQyCgD2AgAZAAgJXCQyCgD2AgAaAAcJehdcKwDPAQAAAA==.',
['风信']='风信紫:BAAALgAECgIJAgAAAA==.',
['风清']='风清扬灬:BAAALgAECgMJBQAAAA==.',
['风行']='风行者游侠:BAAALgADCgYJBgAAAA==.',
['风车']='风车丶:BAAALgAECgYJCAAAAA==.',
['风雷']='风雷召唤师:BAAALgAECgYJBwAAAA==.',
['飒岚']='飒岚:BAABLgAECn8WAAIRAAcJbBdRIADfAQARAAcJbBdRIADfAQAAAA==.',
['飘吖']='飘吖飘:BAAALgAECgcJEgAAAA==.飘吖飘丶:BAAALgAECgMJAwABLgAECgcJEgAKAAAAAA==.',
['飘飛']='飘飛雪舞:BAAALgAECgcJCAAAAA==.',
['飞弹']='飞弹鹰比等:BAAALgADCgIJAgAAAA==.',
['飞机']='飞机又来了:BAAALgAECgUJBgAAAA==.',
['飞瀑']='飞瀑怒潮:BAAALgAECgYJEAAAAA==.',
['飞翔']='飞翔的二姨妈:BAAALgADCgYJBwAAAA==.飞翔的奶瓶:BAAALgAECgQJBwAAAA==.飞翔的魔法:BAAALgADCgYJBgAAAA==.',
['飞霄']='飞霄:BAAALgAECgYJBgAAAA==.',
['香草']='香草加冰:BAAALgAECgQJBgAAAA==.',
['香菜']='香菜君来咯:BAAALgAECgMJAwAAAA==.',
['马儿']='马儿自己跑:BAAALgAECgUJBQAAAA==.马儿跑不快:BAACLgAFFH8HAAIWAAMJOg8CEwDtAAAWAAMJOg8CEwDtAAAuAAQKfx0AAxYACAnbF1MfAFYCABYACAnbF1MfAFYCABgAAQk5Ck1FAC4AAAAA.',
['马国']='马国成:BAAALgAECgcJBwAAAA==.',
['马基']='马基科:BAABLgAECn8WAAQLAAgJ7xp2GQCAAQAGAAYJkhrgXgCsAQALAAUJVxh2GQCAAQAJAAEJDQyoMAA9AAAAAA==.',
['马库']='马库斯之父:BAAALgAECgEJAQAAAA==.',
['骑啊']='骑啊骑啊:BAAALgADCgMJBQAAAA==.',
['骗你']='骗你:BAABLgAECn8iAAIGAAkJoR7ACwAcAwAGAAkJoR7ACwAcAwAAAA==.',
['骚年']='骚年不说骚话:BAAALgADCgYJBgAAAA==.',
['骷髅']='骷髅鱼:BAAALgADCgEJAQAAAA==.',
['高帅']='高帅酷:BAAALgADCgkJBwAAAA==.',
['高楯']='高楯欧丽叶:BAAALgADCgUJBQABLgAFFAIJBAAKAAAAAA==.',
['高蛋']='高蛋白:BAAALgAECgMJAwAAAA==.',
['魅魔']='魅魔指挥官:BAAALgADCgIJAgAAAA==.魅魔说我菜:BAAALgAECgYJAwAAAA==.',
['魇璃']='魇璃诡谲:BAAALgAECgQJBAAAAA==.',
['魔影']='魔影清风:BAAALgAECgYJBgAAAA==.',
['魔法']='魔法老师瑟濂:BAAALgAFFAEJAQAAAA==.',
['魔瘾']='魔瘾者:BAAALgAECgYJCwAAAA==.',
['魔音']='魔音道道主:BAAALgAECgQJBAAAAA==.',
['魔鬼']='魔鬼茎肉人:BAAALgAECgYJDgAAAA==.',
['魔魂']='魔魂丶醉逍遥:BAAALgAECgMJAwAAAA==.',
['鱼章']='鱼章:BAAALgAECgkJCAAAAA==.',
['鲁依']='鲁依:BAAALgAECgEJAgAAAA==.',
['鲜血']='鲜血酒:BAAALgAECgMJAwABLgAECgYJCwAKAAAAAA==.',
['鲜鲜']='鲜鲜的小嫩肉:BAAALgAECgIJAgAAAA==.',
['鳄鱼']='鳄鱼想睡觉:BAAALgAECgcJDQAAAA==.',
['鳝丝']='鳝丝猪肝面:BAAALgADCgUJBQAAAA==.',
['鸡屁']='鸡屁股蘸大酱:BAABLgAFFH8IAAIFAAMJ/hlUJQAAAQAFAAMJ/hlUJQAAAQAAAA==.',
['鸡翅']='鸡翅加卤蛋:BAAALgAECgEJAQAAAA==.',
['鸨仔']='鸨仔饭:BAABLgAECn8eAAMWAAcJuxz0JQAqAgAWAAcJuxz0JQAqAgAbAAYJewWODACxAAAAAA==.',
['鸽尔']='鸽尔泰:BAAALgAECgUJCQAAAA==.',
['鹿野']='鹿野妤紫:BAAALgAECgYJBgAAAA==.',
['麦兜']='麦兜小笨猪:BAAALgADCgIJAgAAAA==.',
['麦欧']='麦欧卡灬:BAAALgAFFAIJAgAAAA==.',
['黄包']='黄包车牌号:BAAALgAECgYJCQAAAA==.',
['黄泽']='黄泽一:BAAALgAECgIJAgAAAA==.',
['黄筱']='黄筱贰:BAAALgAECgEJBQAAAA==.',
['黄豆']='黄豆糕:BAAALgAECgYJCwABLgAECgcJDwAKAAAAAA==.',
['黎桦']='黎桦楦:BAAALgAECgYJDQAAAA==.',
['黎黎']='黎黎:BAAALgAECgYJCwAAAA==.',
['黑僧']='黑僧:BAAALgAECgEJAQAAAA==.',
['黑喂']='黑喂狗:BAACLgAFFH8IAAMiAAQJ+x5FCADJAAAiAAQJ+x5FCADJAAAgAAEJ/QpkIABQAAAuAAQKfxQAAyAABwm0Dco/AIEBACAABwm0Dco/AIEBACIABQl3G644AG4BAAAA.',
['黑夜']='黑夜恨白天:BAABLgAFFH8IAAMeAAQJVxtvBwBmAQAeAAQJFhtvBwBmAQARAAQJZhUAAAAAAAAAAA==.黑夜问白天:BAAALgADCgEJAQABLgAFFAQJCAAeAFcbAA==.',
['黑妹']='黑妹妹:BAAALgADCgMJAwAAAA==.',
['黑巧']='黑巧柠檬:BAABLgAFFH8HAAIFAAMJChEjKQD1AAAFAAMJChEjKQD1AAAAAA==.',
['黑柒']='黑柒吖:BAAALgAECgcJDAAAAA==.',
['黑闪']='黑闪闪的牛:BAAALgAFFAEJAQAAAA==.',
['黒崎']='黒崎:BAAALgAECgUJBwAAAA==.',
['默不']='默不回首:BAAALgADCgcJCgAAAA==.',
['龍雲']='龍雲军团:BAAALgAFFAEJAQAAAA==.',
['龘石']='龘石榴哥龘:BAAALgAECgEJAQAAAA==.龘石榴龖:BAAALgADCgEJAgAAAA==.',
['龙剑']='龙剑飞:BAAALgADCgEJAQAAAA==.',
['龙咩']='龙咩咩:BAAALgADCgIJAgAAAA==.',
['龙啊']='龙啊龙啊龙:BAAALgAECgQJBAAAAA==.',
['龙小']='龙小墨:BAAALgAECgUJBgABLgAFFAUJBAAKAAAAAA==.',
['龙尾']='龙尾小回旋:BAAALgAECgkJCQAAAA==.',
['龙希']='龙希尔万:BAAALgAECgUJCAAAAA==.',
['龙是']='龙是帝王之征:BAAALgAECgMJAwAAAA==.',
['龙民']='龙民公:BAAALgAECgYJBgAAAA==.',
},}
provider.parse = parse

local rawData = provider.data
provider.data = {}
provider.getChunk = getChunkLookup(rawData, 2)

setmetatable(provider.data, {
	__index = function(table, key)
		provider.getChunk(key)
	end,
})

if _G["ArchonTooltip"] and ArchonTooltip.AddProviderV2 then
	ArchonTooltip.AddProviderV2(lookup, provider)
end
