-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Thunderaan Season of Discovery", {
	[11642] = {"green","orange"},
	[465700] = {"blue","red"},
	[466211] = {"blue","purple"},
	[466774] = "yellow",
	[470866] = "blue",
})

BigWigs:AddSounds("Thunderaan Season of Discovery", {
	[11642] = "alert",
	[465700] = "warning",
	[466211] = "alarm",
	[466774] = "info",
	[470866] = "underyou",
})
