
-------------------------------------------------------------------------------
-- English localization file for enUS
-- Auto-Generated by buildlocales.py on <Thu May 04 15:00:24 2017>
-------------------------------------------------------------------------------

local AceLocale = LibStub:GetLibrary("AceLocale-3.0")
local L = AceLocale:NewLocale("SpeakinSpell", "enUS", true, true)
if not L then return end

SpeakinSpell:PrintLoading("Locales/Locale-enUS.lua")

------------------------------------------
---------- SpeakinSpell.lua     ----------
------------------------------------------
L["Default settings restored"] = "Default settings restored"
L["SpeakinSpell Loaded"] = "SpeakinSpell Loaded"
L["Misc. Event: "] = "Misc. Event: "
L["NPC: "] = "NPC: "
L["Resurrection: "] = "Resurrection: "
L["Data Sharing Event (Rx): "] = "Data Sharing Event (Rx): "
L["Data Sharing Event (Tx): "] = "Data Sharing Event (Tx): "
L["Chat Event: "] = "Chat Event: "
L["Combat Event: "] = "Combat Event: "
L["Achievement Earned by "] = "Achievement Earned by "
L["When I Type: /ss "] = "When I Type: /ss "
L["When I buff myself with: "] = "When I buff myself with: "
L["When I debuff myself with: "] = "When I debuff myself with: "
L["When someone else buffs me with: "] = "When someone else buffs me with: "
L["When someone else debuffs me with: "] = "When someone else debuffs me with: "
L["When I lose the buff: "] = "When I lose the buff: "
L["When I lose the debuff: "] = "When I lose the debuff: "
L["When I Start Channeling: "] = "When I Start Channeling: "
L["When I Stop Channeling: "] = "When I Stop Channeling: "
L["When I Start Casting: "] = "When I Start Casting: "
L["When I Fail to Cast: "] = "When I Fail to Cast: "
L["When I'm interrupted while casting: "] = "When I'm interrupted while casting: "
L["When I Stop Casting: "] = "When I Stop Casting: "
L["When I Successfully Cast: "] = "When I Successfully Cast: "
L["When my Pet Successfully Cast: "] = "When my Pet Successfully Cast: "
L["_ Show All Types of Events _"] = "_ Show All Types of Events _"
L["Misc. Events"] = "Misc. Events"
L["Interaction with NPCs"] = "Interaction with NPCs"
L["Resurrection Events (LibResComm)"] = "Resurrection Events (LibResComm)"
L["Data Sharing Events (Received)"] = "Data Sharing Events (Received)"
L["Data Sharing Events (Sent)"] = "Data Sharing Events (Sent)"
L["Chat Events"] = "Chat Events"
L["Combat Events"] = "Combat Events"
L["/ss macro things you type"] = "/ss macro things you type"
L["Self Buffs (includes procs)"] = "Self Buffs (includes procs)"
L["Self Debuffs"] = "Self Debuffs"
L["Buffs from Others (includes totems)"] = "Buffs from Others (includes totems)"
L["Debuffs from Others"] = "Debuffs from Others"
L["Fading Buffs (includes procs)"] = "Fading Buffs (includes procs)"
L["Fading Debuffs"] = "Fading Debuffs"
L["Channeled Spells Start"] = "Channeled Spells Start"
L["Channeled Spells Stop"] = "Channeled Spells Stop"
L["Spells, Abilities, and Items (Start Casting)"] = "Spells, Abilities, and Items (Start Casting)"
L["Spells, Abilities, and Items (Failed)"] = "Spells, Abilities, and Items (Failed)"
L["Spells, Abilities, and Items (Interrupted)"] = "Spells, Abilities, and Items (Interrupted)"
L["Spells, Abilities, and Items (Stop Casting)"] = "Spells, Abilities, and Items (Stop Casting)"
L["Spells, Abilities, and Items (Successful Cast)"] = "Spells, Abilities, and Items (Successful Cast)"
L["Pet's Abilities (Successful Cast)"] = "Pet's Abilities (Successful Cast)"
-- [buildlocales.py copy] ./SpeakinSpell.lua(265)
-- The names of chat channels use internal channel ID names
-- instead of the English text that is normally used in a one-to-one match

L["Silent"]						= "Silent" -- this means that messages are disabled
L["SPEAKINSPELL CHANNEL"]		= "Self-Chat (SpeakinSpell:)"
L["SELF RAID WARNING CHANNEL"]	= "Self-Only Raid Warning"
L["RAID_BOSS_WHISPER"]			= "Boss Whisper"
L["MYSTERIOUS VOICE"]			= "[Mysterious Voice] whispers:"
L["COMM TRAFFIC RX"]			= "Comm Traffic Received (Rx)"
L["COMM TRAFFIC TX"]			= "Comm Traffic Sent (Tx)"

-- The rest of the channel lookup table is built from GlobalStrings.lua
-- using the following format
L["<text> (<slash>)"] = "<text> (<slash>)" --example: "Say (/s)" or "Guild (/g)"

-- [buildlocales.py end of copy] ./SpeakinSpell.lua(281)
L["[/ss guides]"] = "[/ss guides]"
L["Setup guides are enabled. <clickhere> to disable them"] = "Setup guides are enabled. <clickhere> to disable them"
L["[/ss recent]"] = "[/ss recent]"
L["<clickhere> to review recent events and speeches"] = "<clickhere> to review recent events and speeches"
L["Setup guides have been disabled. <clickhere> to enable them"] = "Setup guides have been disabled. <clickhere> to enable them"
L["[Click Here]"] = "[Click Here]"
L["Welcome to SpeakinSpell v<version> <clickhere> to edit options"] = "Welcome to SpeakinSpell v<version> <clickhere> to edit options"
L["Automatic event detection and announcements are enabled."] = "Automatic event detection and announcements are enabled."
L["Automatic event detection and announcements are disabled."] = "Automatic event detection and announcements are disabled."
L["However, \"/ss macro something\" will still trigger announcements if run manually"] = "However, \"/ss macro something\" will still trigger announcements if run manually"
L["Recent Events Detected..."] = "Recent Events Detected..."
L["Recent Speech Announcements..."] = "Recent Speech Announcements..."

------------------------------------------
---------- substitutions.lua    ----------
------------------------------------------
L["key"] = "key"
L["lasttarget"] = "lasttarget"
L["selected"] = "selected"
L["mouseover"] = "mouseover"
L["realm"] = "realm"
L["playertitle"] = "playertitle"
L["playerfulltitle"] = "playerfulltitle"
L["subzone"] = "subzone"
L["spelllink"] = "spelllink"
L["scenario"] = "scenario"
L["eventtype"] = "eventtype"
L["eventtypeprefix"] = "eventtypeprefix"
L["displayname"] = "displayname"
L["displaylink"] = "displaylink"
L["spellname"] = "spellname"
L["tm"] = "tm"
L["r"] = "r"
L["c"] = "c"
L["mdyhms"] = "mdyhms"
L["mdy"] = "mdy"
L["hms"] = "hms"
L["md"] = "md"
L["hm"] = "hm"
L["companion"] = "companion"
L["mount"] = "mount"
L["text"] = "text"
L["overkill"] = "overkill"
L["achievement"] = "achievement"
L["desc"] = "desc"
L["reward"] = "reward"
L["points"] = "points"
L["NPC"] = "NPC"
-- [buildlocales.py copy] ./substitutions.lua(360)
-- The following phrases are the possible values of <scenario>
-- as in the phrase "<displaylink> is silent while in <scenario>."
-- or "Just a sec, I am busy with <scenario>."
-- [buildlocales.py end of copy] ./substitutions.lua(364)
L["The Arena"] = "The Arena"
L["A Battleground"] = "A Battleground"
L["World PVP"] = "World PVP"
L["Raid Leadership Mode"] = "Raid Leadership Mode"
L["Raid Officer Mode"] = "Raid Officer Mode"
L["A Raid"] = "A Raid"
L["A Party"] = "A Party"
L["Party Leadership Mode"] = "Party Leadership Mode"
L["Solo Mode"] = "Solo Mode"
L["Test Event: "] = "Test Event: "
L["Test Events"] = "Test Events"
L["<EventTypePrefix><name>"] = "<EventTypePrefix><name>"
-- [buildlocales.py copy] ./substitutions.lua(679)
-- The wrapping symbols around <substitutions> may be localized
L["<"] = "<"
L[">"] = ">"
-- L["<(.-)>"] is a regular expression match pattern for string.gsub()
-- [buildlocales.py end of copy] ./substitutions.lua(684)
L["<(.-)>"] = "<(.-)>"
-- [buildlocales.py copy] ./substitutions.lua(698)
-- The wrapping symbols around <target|_embedded substitutions_> may be localized
L["_"] = "_"
-- L["_(.-)_"] is a regular expression match pattern for string.gsub()
-- [buildlocales.py end of copy] ./substitutions.lua(702)
L["_(.-)_"] = "_(.-)_"

------------------------------------------
---------- slashcommands.lua    ----------
------------------------------------------
L["ss"] = "ss"
L["speakinspell"] = "speakinspell"
L["toggle"] = "toggle"
L["options"] = "options"
L["create"] = "create"
L["messages"] = "messages"
L["random"] = "random"
L["import"] = "import"
L["network"] = "network"
L["help"] = "help"
L["reset"] = "reset"
L["advertise"] = "advertise"
L["ad"] = "ad"
L["ad /s"] = "ad /s"
L["ad /g"] = "ad /g"
L["ad /p"] = "ad /p"
L["ad /ra"] = "ad /ra"
L["testallsubs"] = "testallsubs"
L["memory"] = "memory"
L["sync"] = "sync"
L["guides"] = "guides"
L["recent"] = "recent"
L["ad "] = "ad "
L["sync "] = "sync "
-- [buildlocales.py copy] ./slashcommands.lua(96)
-- to satisfy slash command general-case logic that supports both English and localized text
-- we can get these localized words from GlobalStrings (which are Capitalized)
L["colors"] = strlower(COLORS)
L["macro"] = strlower(MACRO)
-- [buildlocales.py end of copy] ./slashcommands.lua(101)
L["<newline>"] = "<newline>"
L["the /ss macro would keep calling itself forever"] = "the /ss macro would keep calling itself forever"

------------------------------------------
---------- data.lua             ----------
------------------------------------------
L["the random chance failed (<frequency>%)"] = "the random chance failed (<frequency>%)"
L["this event trigger's cooldown is in effect (<remaining>/<cd> seconds remaining)"] = "this event trigger's cooldown is in effect (<remaining>/<cd> seconds remaining)"
L["Announcement of \"<displaylink>\" was silenced because <reason>. <clickhere> to change this setting."] = "Announcement of \"<displaylink>\" was silenced because <reason>. <clickhere> to change this setting."
-- L["[Click Here]"] recycled from: ./SpeakinSpell.lua(394)
L["this event trigger is disabled"] = "this event trigger is disabled"
L["all automated SpeakinSpell announcements are disabled (except for /ss macro events)"] = "all automated SpeakinSpell announcements are disabled (except for /ss macro events)"
L["the global cooldown is in effect"] = "the global cooldown is in effect"
L["no target selected"] = "no target selected"
L["this event trigger is limited to once per target (<target>)"] = "this event trigger is limited to once per target (<target>)"
L["this event trigger is limited to once per combat / once per out-of-combat"] = "this event trigger is limited to once per combat / once per out-of-combat"
L["All event triggers and speeches have been erased. You now have a clean slate."] = "All event triggers and speeches have been erased. You now have a clean slate."

------------------------------------------
---------- utils.lua            ----------
------------------------------------------
L["Your friends"] = "Your friends"
L["<basecolor><eventtypeprefix><colormatchedname>"] = "<basecolor><eventtypeprefix><colormatchedname>"
L["<basecolor><colormatchedname>"] = "<basecolor><colormatchedname>"
L["Memory usage report\n"] = "Memory usage report\n"
L["<module>: <kb> kb"] = "<module>: <kb> kb"
L["Total: <kb> kb"] = "Total: <kb> kb"
L["Unknown Damage Type"] = "Unknown Damage Type"
L["swimmer"] = "swimmer"
L["Qiraj"] = "Qiraj"
L["changes"] = "changes"
L["Outland"] = "Outland"
L["extremely"] = "extremely"
L["very"] = "very"

------------------------------------------
---------- parser.lua           ----------
------------------------------------------
L["|"] = "|"
L["*"] = "*"

------------------------------------------
---------- minimapbutton.lua    ----------
------------------------------------------
L[" is ON"] = " is ON"
L[" is OFF"] = " is OFF"
L["Click|r to toggle SpeakinSpell on/off"] = "Click|r to toggle SpeakinSpell on/off"
L["Right-click|r to open the options"] = "Right-click|r to open the options"

------------------------------------------
---------- speech.lua           ----------
------------------------------------------
L["[Edit Speeches]"] = "[Edit Speeches]"
L["[Setup New Event]"] = "[Setup New Event]"
-- L["[/ss guides]"] recycled from: ./SpeakinSpell.lua(375)
L["<toggleguides> <clicktoedit> <displaylink>"] = "<toggleguides> <clicktoedit> <displaylink>"
L["NumLanguages=%d, selected Random=%d"] = "NumLanguages=%d, selected Random=%d"
L["WARNING: can't execute protected command: <text>"] = "WARNING: can't execute protected command: <text>"
L["[Mysterious Voice] whispers: "] = "[Mysterious Voice] whispers: "
L["SS Network "] = "SS Network "
L["* <player> <emotes> *"] = "* <player> <emotes> *"
L["the selected chat channel is \"Silent\" while in <Scenario>"] = "the selected chat channel is \"Silent\" while in <Scenario>"
L["no speeches are defined"] = "no speeches are defined"

------------------------------------------
---------- network.lua          ----------
------------------------------------------
L[" (Unreleased Developer Version)"] = " (Unreleased Developer Version)"
L["Auto-Sync With Player"] = "Auto-Sync With Player"
L["Starting Sync with <target>"] = "Starting Sync with <target>"
L["General Auto-Sync"] = "General Auto-Sync"
L["Performing General Auto-Sync"] = "Performing General Auto-Sync"
L["General Auto-Sync Failed"] = "General Auto-Sync Failed"
L["No channels are available. For global syncs, join a guild, party, raid, or battleground."] = "No channels are available. For global syncs, join a guild, party, raid, or battleground."
L["No New Events to Send to <target>"] = "No New Events to Send to <target>"
L["NEW? reply canceled - all event hooks are already known to <target>"] = "NEW? reply canceled - all event hooks are already known to <target>"
L["Each Packet Sent"] = "Each Packet Sent"
L["<target> -> <command> <sent> / <textlen> - <percent>%"] = "<target> -> <command> <sent> / <textlen> - <percent>%"
L["Send Data"] = "Send Data"
L["Send to <target> <command> (<size> chars)"] = "Send to <target> <command> (<size> chars)"
L["Receive Data"] = "Receive Data"
L["Received from <sender> (<distribution>): <command> (<size> chars)"] = "Received from <sender> (<distribution>): <command> (<size> chars)"
L["Transfer Complete"] = "Transfer Complete"
L["Send Complete: <command> -> <target> (<size> chars)"] = "Send Complete: <command> -> <target> (<size> chars)"
L["Tx Queue is Empty"] = "Tx Queue is Empty"
L["All sending is complete (for now)"] = "All sending is complete (for now)"
L["Newer version available: "] = "Newer version available: "
L["Found a SpeakinSpell User <username> running v<version>"] = "Found a SpeakinSpell User <username> running v<version>"
L["Network Error"] = "Network Error"
L["Network Error: "] = "Network Error: "
L["Received new event hooks"] = "Received new event hooks"
L["Discovered <n> new event hooks from <sender> (<channel>)"] = "Discovered <n> new event hooks from <sender> (<channel>)"
L["Collected Event Table (Speeches)"] = "Collected Event Table (Speeches)"
L["Collected an Event Table from: <sender>"] = "Collected an Event Table from: <sender>"
L["Collected Random Substitutions"] = "Collected Random Substitutions"
L["Collected random substitutions from: <sender>"] = "Collected random substitutions from: <sender>"
L["Random"] = "Random"

------------------------------------------
---------- rez.lua              ----------
------------------------------------------
L["Start Casting (I'm the caster)"] = "Start Casting (I'm the caster)"
L["Start Casting (I'm the target)"] = "Start Casting (I'm the target)"
L["Start Casting (I'm not involved)"] = "Start Casting (I'm not involved)"
L["End Casting (I'm the caster)"] = "End Casting (I'm the caster)"
L["End Casting (I'm the target)"] = "End Casting (I'm the target)"
L["End Casting (I'm not involved)"] = "End Casting (I'm not involved)"
L["Received by target"] = "Received by target"
L["Someone can self-res (SS, Ankh)"] = "Someone can self-res (SS, Ankh)"
L["Expired or Declined"] = "Expired or Declined"

------------------------------------------
---------- wowevents.lua        ----------
------------------------------------------
L["Melee Swing"] = "Melee Swing"
L["Critical Strike"] = "Critical Strike"
L["Killing Blow"] = "Killing Blow"
L["I Lost Aggro"] = "I Lost Aggro"
L["I Gained Aggro"] = "I Gained Aggro"
L["Dismiss Mount"] = "Dismiss Mount"
L["Summon Mount"] = "Summon Mount"
L["Dismiss Companion Pet"] = "Dismiss Companion Pet"
L["Summon Companion Pet"] = "Summon Companion Pet"
L["I Died"] = "I Died"
L["Entering Combat"] = "Entering Combat"
L["Exiting Combat"] = "Exiting Combat"
L["Changed Zone"] = "Changed Zone"
L["Changed Sub-Zone"] = "Changed Sub-Zone"
L["Whispered While In-Combat"] = "Whispered While In-Combat"

L[
[[A guild member said ding]]
] = 
[[A guild member said ding]]


L[
[[A party member said ding]]
] = 
[[A party member said ding]]

L["Begin /follow"] = "Begin /follow"
L["End /follow"] = "End /follow"
L["Someone Nearby"] = "Someone Nearby"
L["a Guild Member"] = "a Guild Member"
L["Open Gossip Window"] = "Open Gossip Window"
L["Enter Barber Chair"] = "Enter Barber Chair"
L["Exit Barber Chair"] = "Exit Barber Chair"
L["Open Mailbox"] = "Open Mailbox"
L["Talk to Vendor"] = "Talk to Vendor"
L["Talk to Quest-Giver"] = "Talk to Quest-Giver"
L["Talk to Flight Master"] = "Talk to Flight Master"
L["Talk to Trainer"] = "Talk to Trainer"
L["a player sent me a rez"] = "a player sent me a rez"
L["Open Trade Window"] = "Open Trade Window"

------------------------------------------
---------- oldversions.lua      ----------
------------------------------------------
L["Updating saved data <oldversion> -> <newversion>"] = "Updating saved data <oldversion> -> <newversion>"

L[
[[ERROR: SpeakinSpell_Patches could not be loaded on demand
Reason: <message>
Your saved data is out of date from an older version of SpeakinSpell
This may cause additional errors
Please return to the character selection screen and enable the SpeakinSpell_Patches addon]]
] = 
[[ERROR: SpeakinSpell_Patches could not be loaded on demand
Reason: <message>
Your saved data is out of date from an older version of SpeakinSpell
This may cause additional errors
Please return to the character selection screen and enable the SpeakinSpell_Patches addon]]


------------------------------------------
---------- gui/gui.lua          ----------
------------------------------------------
L["Select a Speech Event"] = "Select a Speech Event"

------------------------------------------
---------- gui/generaloptions.lua ----------
------------------------------------------
L["General Settings"] = "General Settings"
L["General Settings for SpeakinSpell"] = "General Settings for SpeakinSpell"
L["Information"] = "Information"
L["Data format compatible with v >="] = "Data format compatible with v >="
L["Open the User's Manual"] = "Open the User's Manual"
L["Enable Automatic SpeakinSpell Event Announcements"] = "Enable Automatic SpeakinSpell Event Announcements"
L["ON|r"] = "ON|r"
L["OFF|r"] = "OFF|r"

L[
[[SpeakinSpell is <on>

Disable this option to turn SpeakinSpell <off> and silence all SpeakinSpell speeches

/ss macro events are always enabled if you manually type it or click a button for it.
]]
] = 
[[SpeakinSpell is <on>

Disable this option to turn SpeakinSpell <off> and silence all SpeakinSpell speeches

/ss macro events are always enabled if you manually type it or click a button for it.
]]


L[
[[SpeakinSpell is <off>

Enable this option to turn SpeakinSpell <on> and resume announcing SpeakinSpell Speech Events

/ss macro events are always enabled if you manually type it or click a button for it.
]]
] = 
[[SpeakinSpell is <off>

Enable this option to turn SpeakinSpell <on> and resume announcing SpeakinSpell Speech Events

/ss macro events are always enabled if you manually type it or click a button for it.
]]

L["Show Minimap Button"] = "Show Minimap Button"
L["Show the SpeakinSpell minimap button"] = "Show the SpeakinSpell minimap button"
L["Show Welcome Message"] = "Show Welcome Message"
L["Show the version number in chat when loading SpeakinSpell during login"] = "Show the version number in chat when loading SpeakinSpell during login"
L["Share Speeches for All Characters"] = "Share Speeches for All Characters"

L[
[[OFF = All of your characters will use separate lists of event triggers and random speeches, which you can copy from one to the other using "/ss import"

ON = All of your characters will share the same event triggers and speeches

Toggling this option will merge or split your settings between all of your characters]]
] = 
[[OFF = All of your characters will use separate lists of event triggers and random speeches, which you can copy from one to the other using "/ss import"

ON = All of your characters will share the same event triggers and speeches

Toggling this option will merge or split your settings between all of your characters]]

L["Always use <language>"] = "Always use <language>"
L["Don't ever use racial/roleplay languages based on your character's race or class"] = "Don't ever use racial/roleplay languages based on your character's race or class"
L["Global Cooldown"] = "Global Cooldown"
L["This option will silence SpeakinSpell for this many seconds after any event announcement."] = "This option will silence SpeakinSpell for this many seconds after any event announcement."
L["Edit Speeches"] = "Edit Speeches"
L["Diagnostics"] = "Diagnostics"
L["Show Setup Guides"] = "Show Setup Guides"

L[
[[Enable this option to make SpeakinSpell show you (and only you) all of your own spell casting events and other events that can be announced.

This includes any spell, ability, item, /ss macro things, or automatically obtained effect (e.g. Trinkets or Talents) that you cast or use.]]
] = 
[[Enable this option to make SpeakinSpell show you (and only you) all of your own spell casting events and other events that can be announced.

This includes any spell, ability, item, /ss macro things, or automatically obtained effect (e.g. Trinkets or Talents) that you cast or use.]]

L["Show Why Event Triggers Do Not Fire"] = "Show Why Event Triggers Do Not Fire"
L["If you have an event trigger that does not appear to be firing, this option will tell you which setting silenced the announcement of that event, for example because it's on cooldown, or the random chance failed."] = "If you have an event trigger that does not appear to be firing, this option will tell you which setting silenced the announcement of that event, for example because it's on cooldown, or the random chance failed."
L["Show Debugging Messages (verbose)"] = "Show Debugging Messages (verbose)"
L["Enable this option to show an overwhelming amount of information"] = "Enable this option to show an overwhelming amount of information"
L["DO NOT PRESS THIS BUTTON"] = "DO NOT PRESS THIS BUTTON"
L["Under no circumstances should you ever, EVER push this button.\n\nI'm warning you.\n\nDon't do it.\n\nSeriously, you're already hovering over it for too long, and that's dangerous.\n\nMove your mouse before it's too late!"] = "Under no circumstances should you ever, EVER push this button.\n\nI'm warning you.\n\nDon't do it.\n\nSeriously, you're already hovering over it for too long, and that's dangerous.\n\nMove your mouse before it's too late!"

------------------------------------------
---------- gui/currentmessages.lua ----------
------------------------------------------
L["Message Settings"] = "Message Settings"
L["Your active speeches"] = "Your active speeches"
L["Edit Speech / Announcement Settings"] = "Edit Speech / Announcement Settings"
L["1. Search..."] = "1. Search..."
L["Type some of the name of what you're looking for, to narrow down the list below"] = "Type some of the name of what you're looking for, to narrow down the list below"
L["Select a Category of Events"] = "Select a Category of Events"
L["Show only this kind of event in the list below"] = "Show only this kind of event in the list below"
L["Show More than 100 Search Results"] = "Show More than 100 Search Results"
L["Enable to show more than 100 search results in the drop-down list below.\n\nEnabling this option can slow down the performance of this window. (capped at 200 max to avoid memory overflows)"] = "Enable to show more than 100 search results in the drop-down list below.\n\nEnabling this option can slow down the performance of this window. (capped at 200 max to avoid memory overflows)"
L["2. Select..."] = "2. Select..."
L["No Matching Search Results Found"] = "No Matching Search Results Found"
L["Select a spell from the list to configure the random announcements for that spell."] = "Select a spell from the list to configure the random announcements for that spell."
L["Create New..."] = "Create New..."
L["Click here to create settings for a new spell, ability, effect, macro, or other event"] = "Click here to create settings for a new spell, ability, effect, macro, or other event"
L["3. Edit..."] = "3. Edit..."
L["How Often? <selectedevent>"] = "How Often? <selectedevent>"
L["Show These Options"] = "Show These Options"
L["Show these options for chat frequency, cooldowns, and other limits"] = "Show these options for chat frequency, cooldowns, and other limits"
L["Delete this Event"] = "Delete this Event"
L["Remove the selected spell from the list"] = "Remove the selected spell from the list"
L["Disable announcements for this Speech Event"] = "Disable announcements for this Speech Event"
L["Stop SpeakinSpell from announcing the selected spell or event"] = "Stop SpeakinSpell from announcing the selected spell or event"
L["Random Chance (%)"] = "Random Chance (%)"

L[
[[You have a random chance to say a message each time you use the selected spell, based on this selected percentage.

100% will always speak. 0% will never speak.]]
] = 
[[You have a random chance to say a message each time you use the selected spell, based on this selected percentage.

100% will always speak. 0% will never speak.]]

L["Cooldown (seconds)"] = "Cooldown (seconds)"
L["To prevent SpeakinSpell from speaking in the chat too often for this spell, you can set a cooldown for how many seconds must pass before SpeakinSpell will announce this spell again."] = "To prevent SpeakinSpell from speaking in the chat too often for this spell, you can set a cooldown for how many seconds must pass before SpeakinSpell will announce this spell again."
L["Limit once per combat"] = "Limit once per combat"
L["Do not announce this event more than once until you either leave combat, or enter combat."] = "Do not announce this event more than once until you either leave combat, or enter combat."
L["Limit once per <target>"] = "Limit once per <target>"

L[
[[Do not announce this event more than once in a row for the same <target> name.

Note that for spells and events that only ever target you, you're name will never change, so this would limit the announcement to once per login session.]]
] = 
[[Do not announce this event more than once in a row for the same <target> name.

Note that for spells and events that only ever target you, you're name will never change, so this would limit the announcement to once per login session.]]

L["How often you say (Cooldowns/Limits)"] = "How often you say (Cooldowns/Limits)"
L["Which Channel? <selectedevent>"] = "Which Channel? <selectedevent>"
L["Show these options for chat channel selections"] = "Show these options for chat channel selections"
L["Use the Instance Channel when Available"] = "Use the Instance Channel when Available"

L[
[[Useful for Dungeon Finder and Raid Finder groups.

If the Instance Channel is available, use it as a replacement for the /party or /raid channels selected below.

The Instance Channel will only be used as a replacement for /party and /raid channels, otherwise the selected channel will be used, i.e. /say, etc.]]
] = 
[[Useful for Dungeon Finder and Raid Finder groups.

If the Instance Channel is available, use it as a replacement for the /party or /raid channels selected below.

The Instance Channel will only be used as a replacement for /party and /raid channels, otherwise the selected channel will be used, i.e. /say, etc.]]

L["Whisper the message to your <target>"] = "Whisper the message to your <target>"

L[
[[Enable whispering the announcement to the friendly <target> of your spell.

Non-spell Speech Events also have a <target>. This uses the same target as the <target> substitution, and will not whisper to yourself.]]
] = 
[[Enable whispering the announcement to the friendly <target> of your spell.

Non-spell Speech Events also have a <target>. This uses the same target as the <target> substitution, and will not whisper to yourself.]]

L["Select the channel to use for this spell, while..."] = "Select the channel to use for this spell, while..."
L["By yourself"] = "By yourself"
L["Select which channel to use for this spell while playing solo"] = "Select which channel to use for this spell while playing solo"
L["In a Party"] = "In a Party"
L["Select which channel to use for this spell while in a Party"] = "Select which channel to use for this spell while in a Party"
L["In a Raid"] = "In a Raid"
L["Select which channel to use for this spell while in a Raid"] = "Select which channel to use for this spell while in a Raid"
L["Use this channel if you are the leader of a 5-man party"] = "Use this channel if you are the leader of a 5-man party"
L["Use this channel if you are the leader of a raid group"] = "Use this channel if you are the leader of a raid group"
L["Raid Officer"] = "Raid Officer"
L["Use this channel if you are promoted to assist in a raid group"] = "Use this channel if you are promoted to assist in a raid group"
L["In a Battleground"] = "In a Battleground"
L["Select which channel to use for this spell while in a Battleground"] = "Select which channel to use for this spell while in a Battleground"
L["In Arena"] = "In Arena"
L["Select which channel to use for this spell while playing in the Arena"] = "Select which channel to use for this spell while playing in the Arena"
L["In World PVP (WG/TB)"] = "In World PVP (WG/TB)"

L[
[[Select which channel to use for this spell while playing in a Wintergrasp or Tol Barad battle.  This only applies during an active battle.]]
] = 
[[Select which channel to use for this spell while playing in a Wintergrasp or Tol Barad battle.  This only applies during an active battle.]]

L["Where you say (Channels/Whisper)"] = "Where you say (Channels/Whisper)"
L["What to Say? <selectedevent>"] = "What to Say? <selectedevent>"
L["Delete All Speeches"] = "Delete All Speeches"
L["Delete all of the speeches for the selected event, INCLUDING read-only speeches"] = "Delete all of the speeches for the selected event, INCLUDING read-only speeches"
L["Show Read-Only Speeches"] = "Show Read-Only Speeches"
L["Toggle showing read-only speeches in the list below."] = "Toggle showing read-only speeches in the list below."
L["Show Ready-Only Speeches"] = "Show Ready-Only Speeches"
L["<hidden> of <total> speeches are read-only / hidden"] = "<hidden> of <total> speeches are read-only / hidden"
L["Use Multi-Line Edit Boxes"] = "Use Multi-Line Edit Boxes"
L["Toggle showing single-line or multi-line edit boxes for speeches"] = "Toggle showing single-line or multi-line edit boxes for speeches"
L["Select the racial game language you want to use to announce these speeches\n\nThis option will be ignored if you set the \"Always Use Common\" option under general settings."] = "Select the racial game language you want to use to announce these speeches\n\nThis option will be ignored if you set the \"Always Use Common\" option under general settings."
-- L["Random"] recycled from: ./network.lua(572)
L["Expand /ss macros as lists-only"] = "Expand /ss macros as lists-only"

L[
[[For /ss macros used in the speeches below, enable this option to import the macro event's speech list into this event's speech list when selecting a random speech.

This will more evenly distribute the random selection of speeches in nested macros, while ignoring the macro event's own separate settings for chat channels, cooldowns, etc.

This option is not recursive, so if you want nested macros to expand sub-macro calls, you must enable this option in the separate settings for the nested macro events.
]]
] = 
[[For /ss macros used in the speeches below, enable this option to import the macro event's speech list into this event's speech list when selecting a random speech.

This will more evenly distribute the random selection of speeches in nested macros, while ignoring the macro event's own separate settings for chat channels, cooldowns, etc.

This option is not recursive, so if you want nested macros to expand sub-macro calls, you must enable this option in the separate settings for the nested macro events.
]]

L["What you say (Speeches)"] = "What you say (Speeches)"
L["Random Speech <number>"] = "Random Speech <number>"
L["Edit"] = "Edit"

L[
[[Write an announcement for this event.

Duplicates of speeches listed above will not be accepted]]
] = 
[[Write an announcement for this event.

Duplicates of speeches listed above will not be accepted]]

L["Delete this speech"] = "Delete this speech"
L["Read-Only"] = "Read-Only"
L["Toggle showing edit controls or a compressed display"] = "Toggle showing edit controls or a compressed display"
L["Edit Macro Event"] = "Edit Macro Event"
L["Open the event settings to edit speeches and other options for When I Type: "] = "Open the event settings to edit speeches and other options for When I Type: "
L["Import Macro's List"] = "Import Macro's List"
L["Copy the speeches from this macro into the current event, replacing the macro call here with the list of speeches from that macro."] = "Copy the speeches from this macro into the current event, replacing the macro call here with the list of speeches from that macro."
-- L["Silent"] recycled from: ./SpeakinSpell.lua(269)
-- L["<newline>"] recycled from: ./slashcommands.lua(261)

------------------------------------------
---------- gui/createnew.lua    ----------
------------------------------------------
-- L["Create New..."] recycled from: ./gui/currentmessages.lua(109)
L["Create a New Speech Event Trigger"] = "Create a New Speech Event Trigger"
L["Create a New Speech Event"] = "Create a New Speech Event"

L[
[[SpeakinSpell can announce many different spells, abilities, items, buffs, procced effects, and other events, and can discover new events the longer you use it.

If the spell or event that you're looking for is not in the list, then cast it or trigger its effect.

To define a custom event, type "/ss macro something" in the default chat frame.

Total event hooks known: <number>]]
] = 
[[SpeakinSpell can announce many different spells, abilities, items, buffs, procced effects, and other events, and can discover new events the longer you use it.

If the spell or event that you're looking for is not in the list, then cast it or trigger its effect.

To define a custom event, type "/ss macro something" in the default chat frame.

Total event hooks known: <number>]]

L["Reset Event List"] = "Reset Event List"
L["Reset the list of event hooks to the default basic list, removing all discovered and collected event hooks"] = "Reset the list of event hooks to the default basic list, removing all discovered and collected event hooks"
L["Search Filter Options"] = "Search Filter Options"
-- L["Type some of the name of what you're looking for, to narrow down the list below"] recycled from: ./gui/currentmessages.lua(40)
-- L["Select a Category of Events"] recycled from: ./gui/currentmessages.lua(48)
-- L["Show only this kind of event in the list below"] recycled from: ./gui/currentmessages.lua(49)
-- L["Show More than 100 Search Results"] recycled from: ./gui/currentmessages.lua(58)
L["Enable to show more than 100 search results in the drop-down list below.\n\nEnabling this option can slow down the performance of this window (capped at 200 max to avoid memory overflows)."] = "Enable to show more than 100 search results in the drop-down list below.\n\nEnabling this option can slow down the performance of this window (capped at 200 max to avoid memory overflows)."
L["Show Used Event Hooks"] = "Show Used Event Hooks"
L["Enable to show the event hooks that you already use."] = "Enable to show the event hooks that you already use."
L["Select and Create"] = "Select and Create"
L["This is a list of all the detected spells, abilities, items, and procced effects which SpeakinSpell has seen you cast or receive recently."] = "This is a list of all the detected spells, abilities, items, and procced effects which SpeakinSpell has seen you cast or receive recently."
-- L["No Matching Search Results Found"] recycled from: ./gui/currentmessages.lua(81)
L["Create Speech Event"] = "Create Speech Event"
L["Select the new spell event you want to announce in chat above, then push this button"] = "Select the new spell event you want to announce in chat above, then push this button"

------------------------------------------
---------- gui/import.lua       ----------
------------------------------------------
L["Import"] = "Import"
L["Import New Content"] = "Import New Content"
L["Import New Data"] = "Import New Data"

L[
[[New content is not currently loaded in memory.

Click the button below to continue.

This will scan for new content among:
- The default speeches that come with SpeakinSpell
- Your alternate characters
- Data collected from other SpeakinSpell users
]]
] = 
[[New content is not currently loaded in memory.

Click the button below to continue.

This will scan for new content among:
- The default speeches that come with SpeakinSpell
- Your alternate characters
- Data collected from other SpeakinSpell users
]]

L["Search for New Data"] = "Search for New Data"
L["Search for new content that you are not currently using"] = "Search for new content that you are not currently using"
L["New Content Browser"] = "New Content Browser"
L["Show Import Progress"] = "Show Import Progress"
L["Report import processing results in the chat frame"] = "Report import processing results in the chat frame"
L["Use All"] = "Use All"
L["Import all content from all templates"] = "Import all content from all templates"
L["Import All Templates"] = "Import All Templates"
L["Hide All"] = "Hide All"
L["Hide all remaining new content and unload it from memory"] = "Hide all remaining new content and unload it from memory"
L["Select a Content Pack"] = "Select a Content Pack"
L["Each of these packs contain new content which you might enjoy using in SpeakinSpell"] = "Each of these packs contain new content which you might enjoy using in SpeakinSpell"
L["Select a Template"] = "Select a Template"
L["Import From: "] = "Import From: "
L["Import all new content from the selected content pack"] = "Import all new content from the selected content pack"
L["Import Whole Template"] = "Import Whole Template"
L["Hide all remaining new content in the selected content pack and unload it from memory"] = "Hide all remaining new content in the selected content pack and unload it from memory"
L["Import Events"] = "Import Events"
L["Import all speech events, and their speeches, for the selected content pack"] = "Import all speech events, and their speeches, for the selected content pack"
L["Import All Speech Events for the Selected Template"] = "Import All Speech Events for the Selected Template"
L["Hide all remaining speech events for the selected content pack, and unload them from memory"] = "Hide all remaining speech events for the selected content pack, and unload them from memory"
-- L["Select a Speech Event"] recycled from: ./gui/gui.lua(28)
-- L["Select a spell from the list to configure the random announcements for that spell."] recycled from: ./gui/currentmessages.lua(93)
L["Selected Event: "] = "Selected Event: "
L["Import all speeches for the selected event"] = "Import all speeches for the selected event"
L["Import All speeches for the Selected Speech Event"] = "Import All speeches for the Selected Speech Event"
L["Hide all remaining speeches for the selected event, and unload the selected event template from memory"] = "Hide all remaining speeches for the selected event, and unload the selected event template from memory"
L["Import Random Substitutions"] = "Import Random Substitutions"
L["Import all <randomsub> word lists for the selected content pack"] = "Import all <randomsub> word lists for the selected content pack"
L["Import All <randomsubs>"] = "Import All <randomsubs>"
L["Hide all <randomsub> word lists for the selected content pack, and unload them from memory"] = "Hide all <randomsub> word lists for the selected content pack, and unload them from memory"
L["Select a <substitution>"] = "Select a <substitution>"
L["Select a Randomized Substitution\n\nThese substitutions may be used in speeches when announcing events, and a random result from the list below will be selected."] = "Select a Randomized Substitution\n\nThese substitutions may be used in speeches when announcing events, and a random result from the list below will be selected."
-- L["<"] recycled from: ./substitutions.lua(681)
L["Import words for: <colorcode><substitution>"] = "Import words for: <colorcode><substitution>"
L["Import all \"words\" for the selected <randomsub>"] = "Import all \"words\" for the selected <randomsub>"
L["Import All Words"] = "Import All Words"
L["Hide all remaining \"words\" for the selected <randomsub>, and unload the selected <randomsub> template from memory"] = "Hide all remaining \"words\" for the selected <randomsub>, and unload the selected <randomsub> template from memory"
-- L["Random Speech <number>"] recycled from: ./gui/currentmessages.lua(807)
L["Use this Random Speech for the selected Event"] = "Use this Random Speech for the selected Event"
L["<red>Don't<normalcolor> Use this Random Speech for the selected Event"] = "<red>Don't<normalcolor> Use this Random Speech for the selected Event"
L["Random Word <number>"] = "Random Word <number>"
L["Use this Random Word for the selected <substitution>"] = "Use this Random Word for the selected <substitution>"
L["<red>Don't<normalcolor> Use this Random Word for the selected <substitution>"] = "<red>Don't<normalcolor> Use this Random Word for the selected <substitution>"
L["You are already using all of the available content"] = "You are already using all of the available content"

------------------------------------------
---------- gui/colors.lua       ----------
------------------------------------------
L["Colors used by SpeakinSpell"] = "Colors used by SpeakinSpell"
L["The options below allow you to change the colors used by SpeakinSpell."] = "The options below allow you to change the colors used by SpeakinSpell."
L["SpeakinSpell Options GUI Colors"] = "SpeakinSpell Options GUI Colors"
L["Colors used in the SS options GUI"] = "Colors used in the SS options GUI"
L["Search Match"] = "Search Match"
L["The color used to highlight search matches in the options GUI"] = "The color used to highlight search matches in the options GUI"
L["Selected Item"] = "Selected Item"
L["The color used to highlight the name of the selected item in the group headings for areas of the SS options GUI screens"] = "The color used to highlight the name of the selected item in the group headings for areas of the SS options GUI screens"
L["Headings"] = "Headings"
L["The color used for main section headings in the options GUI"] = "The color used for main section headings in the options GUI"
-- L["[Click Here]"] recycled from: ./SpeakinSpell.lua(394)
L["The color used for [Click Here] links in SpeakinSpell chat frame messages"] = "The color used for [Click Here] links in SpeakinSpell chat frame messages"
L["Chat Channel Colors"] = "Chat Channel Colors"
L["Colors of SpeakinSpell's special chat channels."] = "Colors of SpeakinSpell's special chat channels."
L["Self-Chat"] = "Self-Chat"

L[
[[The color of <colorcode>SpeakinSpell:<normalcolor> in the self-chat channel.

This applies only to speech event announcements.  Status and debugging messages will always use the <defaultcolor>SpeakinSpell<normalcolor> color]]
] = 
[[The color of <colorcode>SpeakinSpell:<normalcolor> in the self-chat channel.

This applies only to speech event announcements.  Status and debugging messages will always use the <defaultcolor>SpeakinSpell<normalcolor> color]]

L["Self Raid Warnings"] = "Self Raid Warnings"
L["The color of self-only raid warnings generated by SpeakinSpell"] = "The color of self-only raid warnings generated by SpeakinSpell"
L["[Mysterious Voice] whispers:"] = "[Mysterious Voice] whispers:"
L["The color of SpeakinSpell's Mysterious Voice channel option"] = "The color of SpeakinSpell's Mysterious Voice channel option"
L["Comm Traffic Rx"] = "Comm Traffic Rx"
L["The color of the Comm Traffic channel used to show data sharing progress for Inbound (Rx) data received"] = "The color of the Comm Traffic channel used to show data sharing progress for Inbound (Rx) data received"
L["Comm Traffic Tx"] = "Comm Traffic Tx"
L["The color of the Comm Traffic channel used to show data sharing progress for Outbound (Tx) data sent"] = "The color of the Comm Traffic channel used to show data sharing progress for Outbound (Tx) data sent"

------------------------------------------
---------- gui/help.lua         ----------
------------------------------------------
L["Help"] = "Help"
L["The Complete User's Manual"] = "The Complete User's Manual"
L["User's Manual"] = "User's Manual"
L["Select a topic..."] = "Select a topic..."
L["1. About SpeakinSpell"] = "1. About SpeakinSpell"

------------------------------------------
---------- gui/networkgui.lua   ----------
------------------------------------------
L["Data Sharing"] = "Data Sharing"
L["Share speeches and other data with other SpeakinSpell users"] = "Share speeches and other data with other SpeakinSpell users"
L["Networking Options and Commands"] = "Networking Options and Commands"
-- L["Diagnostics"] recycled from: ./gui/generaloptions.lua(191)
L["Show Comm Traffic"] = "Show Comm Traffic"
L["Show data sharing communication progress messages in the chat"] = "Show data sharing communication progress messages in the chat"
L["Show Transfer Progress"] = "Show Transfer Progress"
L["Show outbound data transfer progress"] = "Show outbound data transfer progress"
L["During this session, you have synced with the following players:"] = "During this session, you have synced with the following players:"
L["None"] = "None"
L["<name> (<version>)"] = "<name> (<version>)"
L["Show Statistics"] = "Show Statistics"
L["Show network transfer statistics"] = "Show network transfer statistics"
L["Network stats unavailable"] = "Network stats unavailable"

L[
[[
Send queue
size:<queuesize>
peek:<queuepeek>

Total Sent
user data:<rawqueued>
actual:<sentactual>
Compressed to <sendcompression>%

Total Received
actual:<receivedactual>
user data:<receiveduser>
Compressed to <receivedcompression>%

Actual Sent - Received = <deficit>

LibSmartComm overhead
for packets:<overheadpacket>
for addonid:<overheadid>
total:<overheadlsc>
percent overhead:<overheadpercent>%

Overhead per packet
compressed:<packovercomp>
uncompressed:<packoverraw>
total packets:<numpackets>

addonid prefix:<prefixsize>
total segments:<segments>
]]
] = 
[[
Send queue
size:<queuesize>
peek:<queuepeek>

Total Sent
user data:<rawqueued>
actual:<sentactual>
Compressed to <sendcompression>%

Total Received
actual:<receivedactual>
user data:<receiveduser>
Compressed to <receivedcompression>%

Actual Sent - Received = <deficit>

LibSmartComm overhead
for packets:<overheadpacket>
for addonid:<overheadid>
total:<overheadlsc>
percent overhead:<overheadpercent>%

Overhead per packet
compressed:<packovercomp>
uncompressed:<packoverraw>
total packets:<numpackets>

addonid prefix:<prefixsize>
total segments:<segments>
]]

L["Auto-Sync Options"] = "Auto-Sync Options"
L["Auto-sync at Login"] = "Auto-sync at Login"
L["Send a data sharing request to GUILD, RAID, PARTY, and INSTANCE_CHAT channels every time you login or /reloadui"] = "Send a data sharing request to GUILD, RAID, PARTY, and INSTANCE_CHAT channels every time you login or /reloadui"
L["Global Sync"] = "Global Sync"
L["Send a data sharing request to GUILD, RAID, PARTY, and INSTANCE_CHAT channels.\n\nSame as \"/ss sync\""] = "Send a data sharing request to GUILD, RAID, PARTY, and INSTANCE_CHAT channels.\n\nSame as \"/ss sync\""
L["Sync with Target"] = "Sync with Target"
L["Send a data sharing request to your selected target.\n\nSame as \"/ss sync <target>\""] = "Send a data sharing request to your selected target.\n\nSame as \"/ss sync <target>\""
L["Sharing vs. Privacy"] = "Sharing vs. Privacy"
L["Share my speeches"] = "Share my speeches"
L["Share the speeches I have written for SpeakinSpell events"] = "Share the speeches I have written for SpeakinSpell events"
L["Share my random <substitutions>"] = "Share my random <substitutions>"
L["Share my word lists for <randomsub> words"] = "Share my word lists for <randomsub> words"
L["Share my detected event hooks"] = "Share my detected event hooks"
L["Share my list of New Events Detected from the \"/ss create\" interface"] = "Share my list of New Events Detected from the \"/ss create\" interface"
L["Collect from others"] = "Collect from others"
L["Collect Speeches"] = "Collect Speeches"
L["Collect and save speeches written by other SpeakinSpell users"] = "Collect and save speeches written by other SpeakinSpell users"
L["Collect Random <substitutions>"] = "Collect Random <substitutions>"
L["Collect and save <randomsub> word lists from other SpeakinSpell users"] = "Collect and save <randomsub> word lists from other SpeakinSpell users"
L["Collect New Event Hooks"] = "Collect New Event Hooks"
L["Collect detected event hooks for the list in the \"/ss create\" interface"] = "Collect detected event hooks for the list in the \"/ss create\" interface"
L["Browse Collected Content"] = "Browse Collected Content"
L["Click to go to the Import New Data screen to browse the speeches and <randomsub> lists that you've collected from others"] = "Click to go to the Import New Data screen to browse the speeches and <randomsub> lists that you've collected from others"

------------------------------------------
---------- gui/randomsubs.lua   ----------
------------------------------------------
L["Random Substitutions"] = "Random Substitutions"
L["Random Substitutions like <randomtaunt> and <randomfaction>"] = "Random Substitutions like <randomtaunt> and <randomfaction>"
L["Edit the values that may be used for random <substitutions>"] = "Edit the values that may be used for random <substitutions>"
-- L["Select a <substitution>"] recycled from: ./gui/import.lua(309)
-- L["Select a Randomized Substitution\n\nThese substitutions may be used in speeches when announcing events, and a random result from the list below will be selected."] recycled from: ./gui/import.lua(310)
L["Delete Word List"] = "Delete Word List"
L["Delete the selected word list and <substitution> word"] = "Delete the selected word list and <substitution> word"
L["New Word List"] = "New Word List"
L["Create a new <randomword> list by typing the randomword into this box.\nDo not include the brackets <>"] = "Create a new <randomword> list by typing the randomword into this box.\nDo not include the brackets <>"
-- L["<"] recycled from: ./substitutions.lua(681)
L["Anything you type here might be used as a substitution for <selected>"] = "Anything you type here might be used as a substitution for <selected>"

------------------------------------------
---------- patches/patches.lua  ----------
------------------------------------------
-- [buildlocales.py copy] ./patches/patches.lua(21)

-- Localization of this file has to be careful because some localized strings
-- were used as functional table keys and may be required to match old data
--
-- If the L[] value is in source data, then it must be preserved forever in
--		order to be able to find matching data in old saved data
-- If the L[] value is a destination value, then it may use the newest value
--		which can freely be changed in order to perfect the translation
--		or change the way the UI looks
-- If the L[] value is not used in data at all because it is a status message
--		then it may be changed freely
-- Old transtions need to be saved following this naming convention
-- For locale files that didn't exist yet in these older versions, use English

-- DO NOT CHANGE! -- the value of L["/macro"] in release 3.1.2.05
L["3.1.2.05 /macro"] = "macro"

-- DO NOT CHANGE! -- the <newline> substitution key word from 3.2.2.02
L["3.2.2.02 <newline>"] = "<newline>"

-- DO NOT CHANGE! -- display names for some event hooks in 3.2.2.14
L["3.2.2.14 Entering Combat"] = "Entering Combat"
L["3.2.2.14 Exiting Combat"] = "Exiting Combat"
L["3.2.2.14 Whispered While In-Combat"] = "Whispered While In-Combat"

-- REFERENCED OUTSIDE THIS FILE (authorized list) --
-- These are expected overlaps with other code files
-- The following warnings will be auto-detected by the script
-- The dominant translations used elsewhere in the UI may be used, and freely changed
--L["SpeakinSpell Loaded"] already defined under:SpeakinSpell.lua
--L["<newline>"] already defined under:gui/currentmessages.lua

-- OK TO CHANGE --
-- the remaining definitions below are auto-generated
-- they may be changed freely to provide the best possible translation

-- [buildlocales.py end of copy] ./patches/patches.lua(58)
-- L["SpeakinSpell Loaded"] recycled from: ./SpeakinSpell.lua(151)
-- L["<newline>"] recycled from: ./slashcommands.lua(261)

L[
[[Alert: WoW patch 4.01 had a major impact on SpeakinSpell
some of your event triggers may no longer be valid
especially for spells which have been removed or renamed
<reset> to reset to the new default settings
<eraseall> to erase all your data and start over from a clean slate
<messages> to review and edit your speeches]]
] = 
[[Alert: WoW patch 4.01 had a major impact on SpeakinSpell
some of your event triggers may no longer be valid
especially for spells which have been removed or renamed
<reset> to reset to the new default settings
<eraseall> to erase all your data and start over from a clean slate
<messages> to review and edit your speeches]]

L["[/ss reset]"] = "[/ss reset]"
L["[/ss eraseall]"] = "[/ss eraseall]"
L["[/ss messages]"] = "[/ss messages]"

------------------------------------------
---------- defaults/templates.lua ----------
------------------------------------------
L["Empty Template"] = "Empty Template"
L["An empty template containing no data at all"] = "An empty template containing no data at all"
L["(<type>) <name>"] = "(<type>) <name>"
L["Enemy of <name>"] = "Enemy of <name>"
L["AUTO"] = "AUTO"
L["Merged speeches for <displayname>"] = "Merged speeches for <displayname>"
L["Added speech: <speech>"] = "Added speech: <speech>"
L["Added speeches for <displayname>"] = "Added speeches for <displayname>"
L["Added <randomkey>: <newword>"] = "Added <randomkey>: <newword>"
-- L["<"] recycled from: ./substitutions.lua(681)
L["Merged word list for <keyword>"] = "Merged word list for <keyword>"
L["Added word list for <keyword>"] = "Added word list for <keyword>"
L["Importing Template: <name>"] = "Importing Template: <name>"
L["<creator's> shared speeches"] = "<creator's> shared speeches"
L["<creator's> speeches, shared with you over the network"] = "<creator's> speeches, shared with you over the network"
L["<creator's> shared random substitutions"] = "<creator's> shared random substitutions"
L["<creator's> random <susbtitution> word lists, shared with you over the network"] = "<creator's> random <susbtitution> word lists, shared with you over the network"
L["<toon's> speeches (<realm>)"] = "<toon's> speeches (<realm>)"
L["<toon's> speeches (your alternate character on <realm>)"] = "<toon's> speeches (your alternate character on <realm>)"
L["ALT"] = "ALT"


