-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lord Marrowgar", {
	[69057] = {"blue","yellow"},
	[69076] = "red",
	[69138] = "blue",
})

BigWigs:AddSounds("Lord Marrowgar", {
	[69057] = "alert",
	[69076] = "long",
	[69138] = "underyou",
})

BigWigs:AddColors("Lady Deathwhisper", {
	[70900] = "cyan",
	[70901] = "cyan",
	[71001] = "blue",
	[71204] = {"blue","orange"},
	[71237] = {"blue","red"},
	[71289] = {"blue","orange"},
	[71426] = "yellow",
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lady Deathwhisper", {
	[70900] = "alert",
	[70901] = "alert",
	[71001] = "underyou",
	[71289] = "alarm",
	[71426] = "long",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Icecrown Gunship Battle", {
	[69638] = {"blue","orange"},
	[69651] = {"blue","red"},
	["adds"] = "cyan",
	["mage"] = "yellow",
})

BigWigs:AddSounds("Icecrown Gunship Battle", {
	["adds"] = "info",
	["mage"] = "alarm",
})

BigWigs:AddColors("Deathbringer Saurfang", {
	[72293] = {"blue","yellow"},
	[72385] = {"blue","orange"},
	[72410] = {"blue","purple"},
	[72737] = "red",
	["adds"] = "cyan",
})

BigWigs:AddSounds("Deathbringer Saurfang", {
	[72293] = "alert",
	[72410] = "warning",
	[72737] = "long",
	["adds"] = "info",
})

BigWigs:AddColors("Festergut", {
	[69165] = "yellow",
	[69195] = "yellow",
	[69240] = "red",
	[69279] = {"blue","orange"},
	[72219] = {"blue","green"},
	[72295] = "red",
})

BigWigs:AddSounds("Festergut", {
	[69279] = "alert",
})

BigWigs:AddColors("Rotface", {
	[69508] = "red",
	[69674] = "blue",
	[69839] = "orange",
	["ooze"] = "yellow",
})

BigWigs:AddSounds("Rotface", {
	[69508] = "alarm",
	[69839] = "alert",
})

BigWigs:AddColors("Professor Putricide", {
	[70351] = "yellow",
	[70447] = "blue",
	[70672] = "blue",
	[70911] = "blue",
	[71255] = "orange",
	[72295] = {"blue","yellow"},
	[72451] = {"blue","orange"},
	["phase"] = {"green","red"},
})

BigWigs:AddSounds("Professor Putricide", {
	[70351] = "alert",
	[70911] = "alert",
	[72451] = "info",
})

BigWigs:AddColors("Blood Prince Council", {
	[70981] = "green",
	[72037] = {"blue","orange"},
	[72039] = "red",
	[72040] = {"blue","orange"},
	[72052] = "yellow",
	[72999] = "blue",
})

BigWigs:AddSounds("Blood Prince Council", {
	[70981] = "info",
	[72039] = "long",
	[72040] = "long",
	[72052] = "alert",
})

BigWigs:AddColors("Blood-Queen Lana'thel", {
	[70877] = "orange",
	[71265] = {"blue","yellow"},
	[71340] = {"blue","red"},
	[71623] = {"blue","yellow"},
	[71772] = "red",
})

BigWigs:AddSounds("Blood-Queen Lana'thel", {
	[70877] = "alert",
	[71772] = "alarm",
})

BigWigs:AddColors("Valithria Dreamwalker", {
	[69325] = "yellow",
	[71086] = "blue",
	["blazing"] = "green",
	["portal"] = "red",
})

BigWigs:AddSounds("Valithria Dreamwalker", {
	[71086] = "alarm",
})

BigWigs:AddColors("Sindragosa", {
	[69762] = "blue",
	[69766] = "blue",
	[70106] = "blue",
	[70123] = "red",
	[70126] = {"blue","orange"},
	[70127] = "yellow",
	["airphase"] = "green",
	["phase2"] = "green",
})

BigWigs:AddSounds("Sindragosa", {
	[69762] = "alert",
	[70123] = "alarm",
	[70127] = "info",
	["phase2"] = "long",
})

BigWigs:AddColors("The Lich King", {
	[68980] = {"blue","yellow"},
	[68981] = "orange",
	[69037] = {"blue","orange","yellow"},
	[69200] = "blue",
	[69409] = "blue",
	[70337] = "blue",
	[70372] = {"red","yellow"},
	[70498] = "orange",
	[70541] = "orange",
	[72143] = "yellow",
	[72262] = "orange",
	[72762] = {"blue","red"},
	[73529] = {"blue","yellow"},
})

BigWigs:AddSounds("The Lich King", {
	[68981] = "long",
	[69200] = "alert",
	[69409] = "alert",
	[70337] = "alert",
	[70372] = {"info","long"},
	[72143] = "alert",
	[72262] = "long",
	[72762] = {"alert","info"},
})

BigWigs:AddColors("Icecrown Citadel Trash", {
	[69483] = {"blue","red"},
	[71022] = "red",
	[71127] = {"blue","purple"},
})

BigWigs:AddSounds("Icecrown Citadel Trash", {
	[69483] = "warning",
	[71022] = "alarm",
	[71127] = "warning",
})
