-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Patchwerk", {
	[28131] = "orange",
})

BigWigs:AddSounds("Patchwerk", {
	[28131] = "long",
})

BigWigs:AddColors("Grobbulus", {
	[28169] = {"blue","red"},
	[28240] = "yellow",
	["adds"] = "orange",
})

BigWigs:AddSounds("Grobbulus", {
	[28169] = "warning",
	[28240] = "info",
	["adds"] = "long",
})

BigWigs:AddColors("Gluth", {
	[28371] = {"green","orange"},
	[28375] = "red",
	[29306] = "blue",
	[54378] = {"blue","purple"},
})

BigWigs:AddSounds("Gluth", {
	[28371] = "alert",
	[28375] = "warning",
	[54378] = "info",
})

BigWigs:AddColors("Thaddius", {
	[28059] = "blue",
	[28084] = "blue",
	[28089] = "orange",
	[28134] = "red",
	[28338] = "red",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Thaddius", {
	[28059] = "warning",
	[28084] = "warning",
	[28089] = "long",
	[28338] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Noth the Plaguebringer", {
	[29208] = "yellow",
	[29212] = "blue",
	[29213] = {"green","red"},
	[29214] = "red",
	["adds"] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Noth the Plaguebringer", {
	[29208] = "alert",
	[29213] = "warning",
	[29214] = "alarm",
	["adds"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Heigan the Unclean", {
	[29998] = {"green","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Heigan the Unclean", {
	[29998] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Loatheb", {
	[29204] = {"orange","red","yellow"},
	[29234] = "green",
	[29865] = "yellow",
	[55593] = {"green","red"},
})

BigWigs:AddSounds("Loatheb", {
	[29204] = {"alarm","long"},
	[29865] = "alert",
	[55593] = "info",
})

BigWigs:AddColors("Anub'Rekhan", {
	[28783] = "orange",
	[28785] = {"green","red","yellow"},
	["add"] = "purple",
})

BigWigs:AddSounds("Anub'Rekhan", {
	[28783] = "alert",
	[28785] = {"alarm","info","long"},
	["add"] = "warning",
})

BigWigs:AddColors("Grand Widow Faerlina", {
	[28732] = {"green","orange"},
	[28794] = "blue",
	[28798] = {"green","orange","red","yellow"},
})

BigWigs:AddSounds("Grand Widow Faerlina", {
	[28732] = "info",
	[28794] = "underyou",
	[28798] = "warning",
})

BigWigs:AddColors("Maexxna", {
	[28741] = "purple",
	[28747] = {"orange","red"},
	[28776] = {"blue","cyan"},
	[29484] = {"red","yellow"},
	["spiders"] = "yellow",
	["web_wrap"] = {"blue","orange","red","yellow"},
})

BigWigs:AddSounds("Maexxna", {
	[28747] = {"alarm","long"},
	[28776] = "info",
	[29484] = "info",
	["spiders"] = "alert",
	["web_wrap"] = {"alarm","warning"},
})

BigWigs:AddColors("Instructor Razuvious", {
	[29060] = {"green","yellow"},
	[29061] = {"green","yellow"},
	[55543] = {"orange","red"},
	[55550] = {"blue","cyan"},
})

BigWigs:AddSounds("Instructor Razuvious", {
	[29060] = "info",
	[55543] = {"alarm","alert"},
})

BigWigs:AddColors("Gothik the Harvester", {
	["add"] = {"orange","red","yellow"},
	["add_death"] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Gothik the Harvester", {
	["add_death"] = {"alert","info"},
	["stages"] = {"alarm","info","long"},
})

BigWigs:AddColors("The Four Horsemen", {
	[28863] = "orange",
	[28883] = "yellow",
	[28884] = "red",
	[57369] = {"blue","purple"},
	["mark"] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("The Four Horsemen", {
})

BigWigs:AddColors("Sapphiron", {
	[28522] = {"blue","yellow"},
	[28524] = "red",
	[28542] = "yellow",
	[55699] = "blue",
	["berserk"] = {"orange","red","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Sapphiron", {
	[28524] = "alarm",
	[28542] = "alert",
	[55699] = "underyou",
	["berserk"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Kel'Thuzad Naxxramas", {
	[27808] = {"blue","red","yellow"},
	[27810] = "red",
	[27819] = {"blue","yellow"},
	[28410] = {"blue","orange","red"},
	["guardians"] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Kel'Thuzad Naxxramas", {
	[27808] = "alert",
	[27819] = "alert",
	[28410] = "alert",
	["stages"] = {"info","long"},
})
