-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Emeriss Season of Discovery", {
	[24814] = "green",
	[24910] = "red",
	[1213155] = {"blue","orange"},
	[1213169] = "blue",
	[1213170] = {"blue","purple","yellow"},
})

BigWigs:AddSounds("Emeriss Season of Discovery", {
	[24814] = "info",
	[24910] = {"alarm","long"},
	[1213155] = "alert",
	[1213169] = "underyou",
	[1213170] = "warning",
})

BigWigs:AddColors("Lethon Season of Discovery", {
	[24814] = "green",
	[24821] = "yellow",
	[1213170] = {"blue","purple","yellow"},
	[1214002] = "red",
})

BigWigs:AddSounds("Lethon Season of Discovery", {
	[24814] = "info",
	[24821] = "alert",
	[1213170] = "warning",
	[1214002] = "long",
})

BigWigs:AddColors("Taerar Season of Discovery", {
	[24814] = "green",
	[1213170] = {"blue","purple","yellow"},
	[1214008] = "cyan",
	[1214028] = "orange",
})

BigWigs:AddSounds("Taerar Season of Discovery", {
	[24814] = "info",
	[1213170] = "warning",
	[1214008] = "long",
})

BigWigs:AddColors("Ysondre Season of Discovery", {
	[24795] = "cyan",
	[24814] = "green",
	[1213170] = {"blue","purple","yellow"},
	[1214136] = {"blue","orange"},
})

BigWigs:AddSounds("Ysondre Season of Discovery", {
	[24795] = "long",
	[24814] = "info",
	[1213170] = "warning",
	[1214136] = "warning",
})
