-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Kalecgos", {
	[44799] = "yellow",
	[44806] = {"orange","red"},
	[44866] = "orange",
	[45029] = {"blue","orange"},
	["realm"] = "orange",
	["wild_magic_casting"] = {"green","yellow"},
	["wild_magic_healing"] = "yellow",
	["wild_magic_hit"] = {"blue","yellow"},
	["wild_magic_threat"] = "blue",
})

BigWigs:AddSounds("Kalecgos", {
	[44799] = "info",
	[44806] = "alarm",
	[44866] = "alert",
	["realm"] = "alert",
	["wild_magic_casting"] = "long",
	["wild_magic_healing"] = "long",
	["wild_magic_hit"] = "long",
})

BigWigs:AddColors("Brutallus", {
	[45150] = "orange",
	[45185] = {"blue","orange","yellow"},
	[46394] = {"blue","green","red","yellow"},
	["burnresist"] = "green",
})

BigWigs:AddSounds("Brutallus", {
	[45150] = "alert",
	[46394] = {"info","warning"},
})

BigWigs:AddColors("Felmyst", {
	[45402] = {"blue","orange"},
	[45661] = {"blue","red","yellow"},
	[45855] = "yellow",
	[45866] = {"blue","purple"},
	["breath"] = "yellow",
	["phase"] = "yellow",
})

BigWigs:AddSounds("Felmyst", {
	[45402] = "alert",
	[45661] = "alert",
	[45866] = "warning",
})

BigWigs:AddColors("The Eredar Twins", {
	[45230] = {"blue","green","orange"},
	[45329] = {"blue","red"},
	[45342] = {"blue","yellow"},
})

BigWigs:AddSounds("The Eredar Twins", {
	[45230] = "info",
	[45329] = "long",
	[45342] = "warning",
})

BigWigs:AddColors("M'uru", {
	[45934] = "red",
	[45996] = "orange",
	[46282] = "orange",
	["humanoid"] = "orange",
	["sentinel"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("M'uru", {
	[45996] = "long",
})

BigWigs:AddColors("Kil'jaeden", {
	[45641] = {"blue","red"},
	[45848] = "orange",
	[45885] = "yellow",
	[45892] = "yellow",
	[46605] = {"orange","yellow"},
	["blueorb"] = "yellow",
	["orb"] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Kil'jaeden", {
	[45641] = "warning",
	[45848] = "info",
	[46605] = "long",
	["orb"] = "alert",
	["stages"] = "info",
})
