-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Imperial Vizier Zor'lok", {
	[122740] = {"blue","yellow"},
	[122761] = {"blue","red"},
	["attenuation"] = {"orange","yellow"},
	["force"] = {"orange","red"},
	["stages"] = "green",
})

BigWigs:AddSounds("Imperial Vizier Zor'lok", {
	["attenuation"] = {"alarm","alert"},
	["force"] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Blade Lord Ta'yak", {
	[-6350] = "green",
	[-6346] = {"blue","orange","yellow"},
	[123474] = {"blue","orange"},
	[125310] = "red",
})

BigWigs:AddSounds("Blade Lord Ta'yak", {
	[-6350] = "long",
	[-6346] = {"alarm","alert"},
	[123474] = "info",
	[125310] = "alarm",
})

BigWigs:AddColors("Garalon", {
	[-6294] = "green",
	[122754] = "orange",
	[122774] = "red",
	[122835] = {"blue","red","yellow"},
	[123081] = {"blue","yellow"},
	[123120] = "blue",
	[123495] = "orange",
})

BigWigs:AddSounds("Garalon", {
	[-6294] = {"info","long"},
	[122774] = "alarm",
	[122835] = {"alarm","info"},
	[123120] = "alert",
})

BigWigs:AddColors("Wind Lord Mel'jarak", {
	[-6554] = "yellow",
	[121881] = {"blue","red"},
	[121896] = {"blue","orange"},
	[122055] = "green",
	[122064] = "blue",
	[122125] = "blue",
	[122149] = "yellow",
	[122224] = "blue",
	[122406] = "red",
	[122409] = {"blue","orange"},
	[131830] = {"blue","orange"},
	["mending"] = "blue",
	["recklessness"] = "yellow",
	["stages"] = "green",
})

BigWigs:AddSounds("Wind Lord Mel'jarak", {
	[121881] = "info",
	[121896] = {"alarm","info"},
	[122064] = "info",
	[122125] = "info",
	[122149] = "alert",
	[122224] = "info",
	[122406] = "alert",
	[122409] = "alarm",
	[131830] = "alarm",
	["mending"] = "alert",
	["recklessness"] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Amber-Shaper Un'sok", {
	[-6548] = {"blue","red"},
	[121949] = {"blue","orange"},
	[121995] = "yellow",
	[122408] = "orange",
	[122413] = {"blue","orange"},
	[122784] = {"blue","orange"},
	[123020] = "blue",
	[123060] = "blue",
	["explosion_by_other"] = "yellow",
	["explosion_casting_by_other"] = {"blue","red"},
	["explosion_casting_by_you"] = "blue",
	["stages"] = {"green","yellow"},
	["willpower"] = "blue",
})

BigWigs:AddSounds("Amber-Shaper Un'sok", {
	[-6548] = "alert",
	[121949] = "long",
	[122408] = "alarm",
	[122413] = "alarm",
	[122784] = "alarm",
	[123020] = "alarm",
	["explosion_casting_by_other"] = "alert",
	["explosion_casting_by_you"] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Grand Empress Shek'zeer", {
	[-6325] = "yellow",
	[123788] = {"blue","yellow"},
	[123845] = {"blue","red"},
	[124077] = "orange",
	[124097] = "blue",
	[124849] = "red",
	[124862] = {"blue","red","yellow"},
	[125390] = {"blue","yellow"},
	[125826] = "yellow",
	["eyes"] = {"blue","orange"},
	["phases"] = "green",
})

BigWigs:AddSounds("Grand Empress Shek'zeer", {
	[123788] = "long",
	[123845] = "info",
	[124077] = "long",
	[124097] = "info",
	[124849] = "alert",
	[124862] = {"alarm","alert"},
	[125390] = "info",
	["eyes"] = "info",
	["phases"] = "info",
})
