-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Beasts of Northrend", {
	[66317] = "blue",
	[66330] = "red",
	[66331] = {"blue","orange"},
	[66758] = "green",
	[66759] = "red",
	[66770] = {"blue","yellow"},
	[66823] = {"blue","orange"},
	[66869] = {"blue","orange"},
	[66883] = {"blue","yellow"},
	[68335] = "red",
	["bosses"] = "green",
	["charge"] = "blue",
	["snobold"] = {"blue","yellow"},
	["spew"] = "yellow",
	["sprays"] = "red",
})

BigWigs:AddSounds("The Beasts of Northrend", {
	[66317] = "alarm",
	[66331] = "info",
	[66823] = "info",
	[66869] = "info",
	[66883] = "alarm",
	[68335] = "long",
	["charge"] = "alarm",
})

BigWigs:AddColors("Lord Jaraxxus", {
	[66197] = "blue",
	[66228] = "yellow",
	[66237] = {"blue","green","orange"},
	[66334] = "blue",
	["adds"] = "orange",
})

BigWigs:AddSounds("Lord Jaraxxus", {
	[66197] = "alert",
	[66237] = "info",
	["adds"] = "alarm",
})

BigWigs:AddColors("Faction Champions", {
	[65801] = {"blue","yellow"},
	[65816] = {"blue","orange"},
	[65877] = {"blue","yellow"},
	[65947] = "red",
	[65960] = {"blue","yellow"},
	[65980] = "red",
	[65983] = "red",
	[66010] = "orange",
	[67514] = "orange",
	[67777] = "orange",
})

BigWigs:AddSounds("Faction Champions", {
	[65816] = "alarm",
})

BigWigs:AddColors("The Twin Val'kyr", {
	["shield"] = {"orange","red"},
	["touch"] = "blue",
	["vortex"] = {"blue","green"},
})

BigWigs:AddSounds("The Twin Val'kyr", {
	["shield"] = "alert",
	["touch"] = "info",
	["vortex"] = "alarm",
})

BigWigs:AddColors("Anub'arak", {
	[66013] = "blue",
	[66118] = "red",
	[66134] = "yellow",
	[67574] = "blue",
	["burrow"] = {"orange","yellow"},
})

BigWigs:AddSounds("Anub'arak", {
	[66118] = "long",
	[67574] = "alert",
})
