----- AUTO GENERATED - DO NOT EDIT

if GetLocale() ~= "ruRU" then
    return
end

local L = BtWQuests.L
L["ALLIED_RACE_MECHAGNOME"] = "Союзные Расы: Механогномы"
L["ALLIED_RACE_VULPERA"] = "Союзные Расы: Вульперы"
L["AN_ALLIANCE_FOOTHOLD"] = "Плацдарм Альянса"
L["ASSAULT_AMATHET_ADVANCE_ACTIVE"] = "Нападение: наступление аматетов Активно"
L["ASSAULT_AQIR_UNEARTHED_ACTIVE"] = "Нападение: появление акиров Активно"
L["ASSAULT_THE_ENDLESS_SWARM_ACTIVE"] = "Нападение: нескончаемый рой Активно"
L["ASSAULT_THE_WARRING_CLANS_ACTIVE"] = "Нападение: враждебные кланы Активно"
L["A_HORDE_FOOTHOLD"] = "Ордынский плацдарм"
L["BTWQUESTS_ALLIED_RACE_DARK_IRON_DWARF"] = "Союзная раса: Дворфы Черного Железа"
L["BTWQUESTS_ALLIED_RACE_KUL_TIRAN"] = "Союзная раса: Култирасцы"
L["BTWQUESTS_ALLIED_RACE_MAGHAR_ORC"] = "Союзная раса: Маг'хары"
L["BTWQUESTS_ALLIED_RACE_ZANDALARI_TROLL"] = "Союзная раса: Зандаларские тролли"
L["BTWQUESTS_BEGIN_THE_BATTLE_FOR_BRENNADAM"] = "Начни битву за Бреннадам"
L["BTWQUESTS_COSMETIC_WAIST_OF_TIME"] = "Декоративный предмет: Часовой пояс"
L["BTWQUESTS_FLIGHT_MASTER_KELYA_MOONFALL"] = "Мастер Полетов: Келия Закат Луны"
L["BTWQUESTS_GIFT_OF_NZOTH"] = "Дар Н'Зота"
L["BTWQUESTS_GIFT_OF_NZOTH_BREADCRUMB"] = "Убивайте наг на Атака наг! Локальное Задание"
L["BTWQUESTS_HATI_REBORN"] = "Возрождение Хати"
L["BTWQUESTS_HERITAGE_OF_GILNEAS"] = "Наследие Гилнеаса"
L["BTWQUESTS_HERITAGE_OF_GNOMEREGAN"] = "Наследие Гномрегана"
L["BTWQUESTS_HERITAGE_OF_KEZAN"] = "Наследие Кезана"
L["BTWQUESTS_HERITAGE_OF_THE_BRONZEBEARD"] = "Наследие Бронзобородов"
L["BTWQUESTS_HERITAGE_OF_THE_SHUHALO"] = "Наследие шу'хало"
L["BTWQUESTS_HERITAGE_OF_THE_SINDOREI"] = "Наследие син'дорай"
L["BTWQUESTS_ITEM_POCKET_SIZED_COMPUTATION_DEVICE"] = "Предмет: Карманное вычислительное устройство"
L["BTWQUESTS_MAGHAR_ORC"] = "Маг'хар Орки"
L["BTWQUESTS_MAJO_AND_JOMA"] = "Майо и Йома"
L["BTWQUESTS_NIGHT_WARRIOR_NIGHT_ELF_CUSTOMIZATION"] = "'Ночная Воительница' Кастомизация для Ночных Эльфов"
L["BTWQUESTS_PROGRESS_THE_WAR_CAMPAIGN"] = "Прогресс Военной Компании"
L["BTWQUESTS_THE_WAR_CAMPAIGN"] = "Военная Компания"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_1"] = "Военная Компания: Битва за Дазар'алор"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_1_5"] = "Военная Компания: Горнило Штормов"
L["BTWQUESTS_THE_WAR_CAMPAIGN_8_2"] = "Военная Компания: Восстание Азшары"
L["BTWQUESTS_UNLOCK_FLIGHT_WHISTLE"] = "Разблокировать Свисток распорядителя полетов"
L["BTWQUESTS_VENDOR_MRRL"] = "Торговец: Мррл"
L["BTWQUESTS_WARFRONT_THE_BATTLE_FOR_DARKSHORE"] = "Фронт: битва за Темные берега"
L["COLLECT_AN_ASHVANE_DISGUISE"] = "Соберите Униформу корпорации Эшвейнов"
L["DUNGEON_KINGS_REST"] = "Подземелье: Гробница королей"
L["DUNGEON_SIEGE_OF_BORALUS"] = "Подземелье: Осада Боралуса"
L["MECHAGNOME"] = "Механогномы"
L["PET_BUMBLES_OR_SEABREEZE_BUMBLEBEE"] = "Питомцы: Жмель или Приморский шмель"
L["PICK_A_LOA"] = "Выберите лоа"
L["RAISE_YOUR_DIREHORN_TO_A_JUVENILE"] = "Вырастите своего Дикорога до состояния детеныша"
L["RAISE_YOUR_DIREHORN_TO_MATURITY"] = "Вырастите своего Дикорога до взрослого состояния"
L["RISE_OF_AZSHARA_ZONES"] = "Локации Восстания Азшары"
L["SUMMON_BUMBLES_OR_SEABREEZE_BUMBLEBEE"] = "Призови Жмель или Приморский шмель"
L["VISIONS_OF_NZOTH"] = "Видения Н'Зота"
L["VULPERA"] = "Вульпера"
L["WAIST_OF_TIME"] = "Часовой пояс"
L["WAIT_UNTIL_AVAILABLE"] = "Подождите пока не появится"
