-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Doomwalker", {
	[33653] = {"orange","red"},
	["earthquake"] = {"red","yellow"},
	["overrun"] = {"red","yellow"},
})

BigWigs:AddSounds("Doomwalker", {
	[33653] = "alarm",
})

BigWigs:AddColors("Gruul the Dragonkiller", {
	[36240] = "blue",
	[36297] = {"orange","yellow"},
	["grasp"] = {"green","orange","yellow"},
	["grow"] = "red",
})

BigWigs:AddSounds("Gruul the Dragonkiller", {
	[36240] = "alarm",
})

BigWigs:AddColors("Doom Lord Kazzak", {
	[21063] = {"blue","yellow"},
	[32960] = "blue",
	["berserk"] = {"green","orange","red","yellow"},
})

BigWigs:AddSounds("Doom Lord Kazzak", {
	[32960] = "alarm",
	["berserk"] = "alert",
})

BigWigs:AddColors("Magtheridon", {
	[30616] = {"green","orange"},
	[36449] = {"green","red"},
	["abyssal"] = "yellow",
	["banish"] = {"red","yellow"},
	["escape"] = {"green","orange","yellow"},
	["heal"] = "orange",
})

BigWigs:AddSounds("Magtheridon", {
	[30616] = "warning",
	[36449] = "alert",
	["banish"] = "info",
	["escape"] = "long",
	["heal"] = "alarm",
})

BigWigs:AddColors("High King Maulgar", {
	[33054] = "yellow",
	[33131] = "yellow",
	[33147] = "red",
	[33152] = "red",
	[33232] = {"green","red"},
	[33238] = {"orange","red","yellow"},
})

BigWigs:AddSounds("High King Maulgar", {
	[33054] = "info",
	[33131] = "long",
	[33152] = "alarm",
})
