-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Archavon the Stone Watcher", {
	[58663] = {"green","yellow"},
	[58678] = {"blue","red"},
	[58965] = "blue",
	["charge"] = {"blue","yellow"},
})

BigWigs:AddSounds("Archavon the Stone Watcher", {
	[58965] = "alarm",
})

BigWigs:AddColors("Malygos", {
	[57429] = "orange",
	["breath"] = {"red","yellow"},
	["phase"] = "yellow",
	["sparkbuff"] = "red",
	["sparks"] = {"red","yellow"},
	["surge"] = "blue",
	["vortex"] = "yellow",
})

BigWigs:AddSounds("Malygos", {
	["breath"] = "alert",
	["sparks"] = "alert",
	["surge"] = "alarm",
})

BigWigs:AddColors("Sartharion", {
	[57491] = "red",
	[58793] = "yellow",
	[58835] = {"blue","green"},
	[59127] = "yellow",
	[60430] = {"blue","purple"},
	["acolyte_shadron"] = "orange",
	["acolyte_vesperon"] = "orange",
	["drakes"] = "yellow",
})

BigWigs:AddSounds("Sartharion", {
	[57491] = "warning",
	[58793] = "info",
	[58835] = "long",
	[59127] = "alert",
	["acolyte_shadron"] = "info",
})

BigWigs:AddColors("Emalon the Storm Watcher", {
	[64216] = "yellow",
	[64218] = "green",
})

BigWigs:AddSounds("Emalon the Storm Watcher", {
})

BigWigs:AddColors("Koralon the Flame Watcher", {
	[66665] = {"green","yellow"},
	[66684] = "blue",
	[66725] = "yellow",
})

BigWigs:AddSounds("Koralon the Flame Watcher", {
	[66684] = "alarm",
})

BigWigs:AddColors("Toravon the Ice Watcher", {
	[72004] = {"blue","orange"},
	[72034] = {"green","yellow"},
	[72090] = "blue",
	[72091] = "red",
})

BigWigs:AddSounds("Toravon the Ice Watcher", {
})

BigWigs:AddColors("Onyxia", {
	[17086] = "red",
	[18392] = "blue",
	[18431] = "yellow",
	[18435] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Onyxia", {
	[17086] = "warning",
	[18392] = "alarm",
	[18431] = "info",
	[18435] = "alert",
	["stages"] = "long",
})
