-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Drov the Ruiner", {
	[175791] = "red",
	[175827] = "yellow",
	[175915] = "blue",
})

BigWigs:AddSounds("Drov the Ruiner", {
	[175791] = "alarm",
	[175915] = "alarm",
})

BigWigs:AddColors("Tarlna the Ageless", {
	[175973] = "red",
	[175979] = "yellow",
	[176001] = "blue",
	[176013] = "orange",
	[176037] = "blue",
})

BigWigs:AddSounds("Tarlna the Ageless", {
	[175973] = "alarm",
	[175979] = "long",
	[176001] = "alert",
	[176037] = "alert",
})

BigWigs:AddColors("Rukhmar", {
	[167615] = {"blue","yellow"},
	[167647] = "yellow",
	[167679] = "orange",
	[167757] = "blue",
})

BigWigs:AddSounds("Rukhmar", {
	[167615] = "warning",
	[167647] = "long",
	[167757] = "alarm",
})

BigWigs:AddColors("Supreme Lord Kazzak", {
	[187471] = {"blue","yellow"},
	[187664] = {"blue","orange"},
	[187668] = "blue",
	[187702] = "red",
})

BigWigs:AddSounds("Supreme Lord Kazzak", {
	[187471] = "info",
	[187664] = "alert",
	[187668] = "alarm",
	[187702] = "long",
})
