-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lucifron", {
	[19702] = "red",
	[19703] = {"green","yellow"},
	[20604] = {"blue","orange"},
})

BigWigs:AddSounds("Lucifron", {
	[19702] = "long",
	[19703] = "info",
})

BigWigs:AddColors("Magmadar", {
	[19408] = "orange",
	[19428] = "blue",
	[19451] = {"green","yellow"},
	[461131] = "cyan",
})

BigWigs:AddSounds("Magmadar", {
	[19408] = "long",
	[19428] = "underyou",
	[19451] = "info",
	[461131] = "alert",
})

BigWigs:AddColors("Gehennas", {
	[19716] = {"green","orange"},
	[19717] = "blue",
})

BigWigs:AddSounds("Gehennas", {
	[19717] = "underyou",
})

BigWigs:AddColors("Garr", {
	[19492] = {"red","yellow"},
})

BigWigs:AddSounds("Garr", {
	[19492] = "info",
})

BigWigs:AddColors("Baron Geddon", {
	[19659] = {"green","yellow"},
	[19695] = "red",
	[20475] = {"blue","orange","red"},
	[20478] = "orange",
	[461103] = "blue",
})

BigWigs:AddSounds("Baron Geddon", {
	[19659] = "info",
	[19695] = "alarm",
	[20475] = "warning",
	[20478] = "long",
	[461103] = "underyou",
})

BigWigs:AddColors("Shazzrah", {
	[19713] = "yellow",
	[19714] = {"green","orange"},
	[19715] = "yellow",
	[23138] = "red",
	[460856] = {"green","red"},
})

BigWigs:AddSounds("Shazzrah", {
	[19713] = "alarm",
	[19714] = "alarm",
	[19715] = "alert",
	[23138] = "long",
	[460856] = {"info","warning"},
})

BigWigs:AddColors("Sulfuron Harbinger", {
	[19775] = "red",
	[19778] = "orange",
	[19779] = "yellow",
	[461103] = "blue",
})

BigWigs:AddSounds("Sulfuron Harbinger", {
	[19775] = "alert",
	[19778] = "alarm",
	[19779] = "info",
	[461103] = "underyou",
})

BigWigs:AddColors("Golemagg the Incinerator", {
	[13880] = {"blue","purple"},
	[20228] = {"blue","orange"},
	[460858] = {"blue","orange"},
	[461463] = "red",
})

BigWigs:AddSounds("Golemagg the Incinerator", {
	[13880] = "alert",
	[460858] = "alarm",
	[461463] = "warning",
})

BigWigs:AddColors("Majordomo Executus", {
	[20534] = {"blue","yellow"},
	[20619] = "red",
	[21075] = "yellow",
	[364895] = "orange",
	[364908] = "orange",
	[461056] = {"blue","red"},
})

BigWigs:AddSounds("Majordomo Executus", {
	[20619] = "info",
	[21075] = "info",
	[364895] = "alert",
	[364908] = "alert",
	[461056] = "warning",
})

BigWigs:AddColors("Ragnaros Classic", {
	[20566] = "red",
	[461062] = "blue",
	["adds"] = "green",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ragnaros Classic", {
	[20566] = "info",
	[461062] = "underyou",
	["stages"] = "long",
})

BigWigs:AddColors("The Molten Core", {
	[460883] = "red",
	[460885] = "red",
	[460887] = "orange",
	[460895] = {"blue","yellow"},
	[460898] = {"blue","yellow"},
	["adds"] = "cyan",
})

BigWigs:AddSounds("The Molten Core", {
	[460883] = "alert",
	[460885] = "long",
	[460887] = "alarm",
	[460895] = "warning",
	[460898] = "warning",
	["adds"] = "info",
})
