-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("T'zane", {
	[261552] = "red",
	[261600] = "yellow",
	[261605] = {"blue","orange"},
	[262004] = {"blue","purple"},
})

BigWigs:AddSounds("T'zane", {
	[261552] = "long",
	[261600] = "info",
	[261605] = "alarm",
	[262004] = "warning",
})

BigWigs:AddColors("Ji'arak", {
	[260908] = "yellow",
	[261088] = "red",
	[261467] = "orange",
})

BigWigs:AddSounds("Ji'arak", {
	[260908] = "info",
	[261088] = "long",
	[261467] = "alert",
})

BigWigs:AddColors("Hailstone Construct", {
	[274891] = "yellow",
	[274895] = "red",
})

BigWigs:AddSounds("Hailstone Construct", {
	[274891] = "long",
	[274895] = "warning",
})

BigWigs:AddColors("Azurethos, The Winged Typhoon", {
	[274829] = "red",
	[274832] = "purple",
	[274839] = "yellow",
})

BigWigs:AddSounds("Azurethos, The Winged Typhoon", {
	[274829] = "warning",
	[274832] = "long",
	[274839] = "long",
})

BigWigs:AddColors("Doom's Howl", {
	[271120] = "blue",
	[271163] = "purple",
	[271164] = "orange",
	[271223] = "cyan",
	[271800] = "red",
})

BigWigs:AddSounds("Doom's Howl", {
	[271120] = "alarm",
	[271163] = "alert",
	[271164] = "info",
	[271223] = "long",
	[271800] = "warning",
})

BigWigs:AddColors("The Lion's Roar", {
	[271120] = "blue",
	[271163] = "purple",
	[271164] = "orange",
	[271223] = "cyan",
	[271800] = "red",
})

BigWigs:AddSounds("The Lion's Roar", {
	[271120] = "alarm",
	[271163] = "alert",
	[271164] = "info",
	[271223] = "long",
	[271800] = "warning",
})

BigWigs:AddColors("Warbringer Yenajz", {
	[274842] = "yellow",
	[274904] = "blue",
	[274932] = "red",
})

BigWigs:AddSounds("Warbringer Yenajz", {
	[274842] = "info",
	[274904] = "alarm",
	[274932] = "long",
})

BigWigs:AddColors("Dunegorger Kraulok", {
	[275200] = "orange",
	[276046] = "red",
})

BigWigs:AddSounds("Dunegorger Kraulok", {
	[275200] = "info",
	[276046] = "long",
})
