-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Taloc", {
	[270290] = "blue",
	[271224] = {"blue","yellow"},
	[271296] = "red",
	[271728] = "orange",
	[271895] = {"blue","yellow"},
	[275189] = "yellow",
	[275205] = {"blue","orange"},
	[275270] = "blue",
	[275432] = {"blue","red"},
	["stages"] = "green",
})

BigWigs:AddSounds("Taloc", {
	[270290] = "alarm",
	[271224] = "warning",
	[271296] = "warning",
	[271728] = "alarm",
	[271895] = "alert",
	[275189] = "alert",
	[275205] = "warning",
	[275270] = "warning",
	[275432] = {"alarm","long"},
	["stages"] = "long",
})

BigWigs:AddColors("MOTHER", {
	[267787] = {"blue","purple","red"},
	[267795] = {"blue","yellow"},
	[267878] = "red",
	[268198] = "orange",
	[268253] = {"blue","yellow"},
	[269051] = {"cyan","red"},
	[274205] = {"blue","green"},
	[279662] = {"blue","yellow"},
})

BigWigs:AddSounds("MOTHER", {
	[267787] = {"alarm","alert"},
	[267795] = {"alarm","alert"},
	[267878] = "warning",
	[268198] = "alert",
	[268253] = {"alarm","alert"},
	[269051] = {"alarm","info"},
	[274205] = "long",
	[279662] = "warning",
})

BigWigs:AddColors("Fetid Devourer", {
	[262277] = "purple",
	[262288] = "orange",
	[262313] = {"blue","orange"},
	[262314] = {"blue","orange"},
	[262364] = {"cyan","red"},
	[262378] = "cyan",
	["breath"] = "yellow",
})

BigWigs:AddSounds("Fetid Devourer", {
	[262277] = "alert",
	[262288] = "alarm",
	[262313] = {"info","warning"},
	[262314] = "warning",
	[262364] = {"long","warning"},
	[262378] = "info",
	["breath"] = "alert",
})

BigWigs:AddColors("Zek'voz, Herald of N'zoth", {
	[-18397] = "cyan",
	[-18390] = "cyan",
	[264382] = {"blue","yellow"},
	[265231] = "orange",
	[265248] = "purple",
	[265360] = {"blue","yellow"},
	[265530] = "red",
	[265646] = {"blue","red"},
	[265662] = "blue",
	[267180] = "yellow",
	[267239] = "yellow",
	["mythic_adds"] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("Zek'voz, Herald of N'zoth", {
	[-18397] = "long",
	[-18390] = "long",
	[264382] = {"alert","warning"},
	[265231] = "alarm",
	[265248] = "alert",
	[265360] = "warning",
	[265530] = "long",
	[265646] = "warning",
	[265662] = "long",
	[267180] = "alert",
	[267239] = "alert",
	["mythic_adds"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Vectis", {
	[265127] = "blue",
	[265143] = "blue",
	[265178] = {"blue","purple"},
	[265206] = "orange",
	[265212] = {"blue","orange"},
	[265217] = "cyan",
	[266459] = "red",
	[267242] = "orange",
	[274990] = "blue",
})

BigWigs:AddSounds("Vectis", {
	[265127] = "warning",
	[265143] = "alarm",
	[265178] = "alert",
	[265206] = "alarm",
	[265212] = "alert",
	[265217] = {"info","long"},
	[266459] = "warning",
	[267242] = "alarm",
	[274990] = "warning",
})

BigWigs:AddColors("Zul", {
	[-18530] = "cyan",
	[269936] = "blue",
	[273288] = "yellow",
	[273350] = "orange",
	[273361] = "orange",
	[273365] = {"blue","yellow"},
	[273451] = "red",
	[274271] = {"blue","orange"},
	[274358] = {"blue","purple"},
	[276299] = "yellow",
	["bloodhexer"] = "cyan",
	["crawg"] = "cyan",
	["crusher"] = "cyan",
	["stages"] = "green",
})

BigWigs:AddSounds("Zul", {
	[269936] = "warning",
	[273288] = "alert",
	[273350] = "alert",
	[273361] = "info",
	[273365] = "warning",
	[273451] = "alarm",
	[274271] = "alarm",
	[274358] = "warning",
	[276299] = "alarm",
	["bloodhexer"] = "long",
	["crawg"] = "long",
	["crusher"] = "long",
	["stages"] = "long",
})

BigWigs:AddColors("Mythrax the Unraveler", {
	[272115] = "orange",
	[272404] = "red",
	[272536] = {"blue","yellow"},
	[273282] = {"blue","purple","red"},
	[273538] = "orange",
	[273810] = "yellow",
	[273949] = "red",
	[274230] = "green",
	[276922] = {"cyan","green","orange"},
	[279013] = "red",
	[279157] = "orange",
	["stages"] = {"cyan","green"},
})

BigWigs:AddSounds("Mythrax the Unraveler", {
	[272115] = "long",
	[272404] = "warning",
	[272536] = "alert",
	[273282] = {"alarm","alert"},
	[273538] = "alert",
	[273810] = "long",
	[273949] = "warning",
	[274230] = "info",
	[276922] = {"info","long"},
	[279013] = "long",
	[279157] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("G'huun", {
	[-18109] = "green",
	[263235] = {"blue","red"},
	[263307] = "orange",
	[263321] = "blue",
	[263482] = "green",
	[267409] = "red",
	[267412] = "purple",
	[267427] = "yellow",
	[267462] = "orange",
	[267509] = "cyan",
	[270287] = "blue",
	[270373] = "yellow",
	[270447] = {"blue","purple"},
	[272506] = {"blue","orange"},
	[274582] = "red",
	[275160] = "orange",
	[277007] = {"blue","red"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("G'huun", {
	[-18109] = "long",
	[263235] = "alert",
	[263307] = "alarm",
	[263321] = "alarm",
	[263482] = "long",
	[267409] = "alert",
	[267412] = "alarm",
	[267427] = "alert",
	[267462] = "warning",
	[267509] = "info",
	[270287] = "alarm",
	[270373] = "alarm",
	[270447] = "alarm",
	[272506] = "alarm",
	[274582] = "alarm",
	[275160] = "warning",
	[277007] = {"info","warning"},
	["stages"] = "long",
})

BigWigs:AddColors("Uldir Trash", {
	[276540] = "red",
	[277047] = {"blue","yellow"},
	[278990] = "red",
})

BigWigs:AddSounds("Uldir Trash", {
	[276540] = "long",
	[277047] = "warning",
	[278990] = "long",
})
