-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("The Stone Guard", {
	[115852] = "cyan",
	[116006] = "cyan",
	[116036] = "cyan",
	[116057] = "cyan",
	[116529] = "orange",
	[130395] = {"blue","yellow"},
	[130774] = "blue",
	["energy"] = "red",
})

BigWigs:AddSounds("The Stone Guard", {
	[115852] = "alert",
	[116006] = "alert",
	[116036] = "alert",
	[116057] = "alert",
	[116529] = "info",
	[130395] = "warning",
	[130774] = "underyou",
	["energy"] = "long",
})

BigWigs:AddColors("Feng the Accursed", {
	[115817] = "orange",
	[115911] = {"blue","orange"},
	[116018] = "red",
	[116157] = "orange",
	[116364] = {"red","yellow"},
	[116417] = {"blue","orange"},
	[116711] = "red",
	[116784] = {"blue","orange"},
	[116793] = "blue",
	[118071] = "red",
	["stages"] = "cyan",
	["tank"] = {"blue","purple"},
})

BigWigs:AddSounds("Feng the Accursed", {
	[115817] = "info",
	[115911] = "info",
	[116018] = "alarm",
	[116364] = "alarm",
	[116417] = "warning",
	[116711] = "alarm",
	[116784] = "warning",
	[116793] = "underyou",
	[118071] = "alarm",
	["stages"] = "info",
	["tank"] = "info",
})

BigWigs:AddColors("Gara'jal the Spiritbinder", {
	[116174] = "yellow",
	[116272] = "orange",
	[117752] = "red",
	[122151] = {"blue","red"},
})

BigWigs:AddSounds("Gara'jal the Spiritbinder", {
	[116272] = "alarm",
	[117752] = "long",
})

BigWigs:AddColors("The Spirit Kings", {
	[117697] = {"green","red"},
	[117708] = "orange",
	[117837] = "orange",
	[117910] = "yellow",
	[117961] = {"green","red"},
	[118047] = "orange",
	[118094] = "orange",
	[118122] = {"blue","red"},
	[118162] = "red",
	[118303] = "blue",
	[119521] = "orange",
	["bosses"] = "cyan",
	["cowardice"] = {"blue","green","orange","yellow"},
})

BigWigs:AddSounds("The Spirit Kings", {
	[117697] = {"alert","info"},
	[117708] = "alarm",
	[117837] = "alert",
	[117910] = "long",
	[117961] = {"alert","info"},
	[118047] = "alarm",
	[118122] = "alarm",
	[118162] = "alert",
	[118303] = "info",
	[119521] = "alarm",
	["bosses"] = "info",
})

BigWigs:AddColors("Elegon", {
	[-6186] = "red",
	[117878] = "blue",
	[119360] = "yellow",
	["adds"] = "yellow",
	["floor"] = "blue",
	["stages"] = "green",
})

BigWigs:AddSounds("Elegon", {
	[-6186] = "alert",
	[117878] = "info",
	["floor"] = "alarm",
	["stages"] = "info",
})

BigWigs:AddColors("Will of the Emperor", {
	[-5670] = {"red","yellow"},
	[116525] = "blue",
	[116829] = {"blue","yellow"},
	["arc"] = "orange",
	["bosses"] = "yellow",
	["combo"] = "orange",
	["courage"] = "yellow",
	["rage"] = "yellow",
	["strength"] = "yellow",
})

BigWigs:AddSounds("Will of the Emperor", {
	[-5670] = "alarm",
	[116525] = "info",
	[116829] = "info",
	["combo"] = "long",
})
