local ADDON_NAME, ns = ...

local HandyNotes = LibStub("AceAddon-3.0"):GetAddon("HandyNotes", true)
if not HandyNotes then return end

local iconLink = "Interface\\Addons\\" .. ADDON_NAME .. "\\Images\\"

ns.icons = {
--Addon Logo
["MNL"] = iconLink .. "MNL4",
--General
["DarkMoon"] = iconLink .. "DarkMoon",
["Innkeeper"] = iconLink .. "InnkeeperN",
["InnkeeperN"] = iconLink .. "InnkeeperN",
["InnkeeperA"] = iconLink .. "InnkeeperA",
["InnkeeperH"] = iconLink .. "InnkeeperH",
["Auctioneer"] = iconLink .. "Auctioneer",
["Bank"] = iconLink .. "BankNew",
["BankOld"] = iconLink .. "Bank",
["BankNew"] = iconLink .. "BankNew",
["Barber"] = iconLink .. "Barber",
["Transmogger"] = iconLink .. "Transmogger",
["PvPVendor"] = iconLink .. "PvPVendor",
["PvPVendorH"] = iconLink .. "PvPVendorH",
["PvPVendorA"] = iconLink .. "PvPVendorA",
["PvEVendor"] = iconLink .. "PvEVendor",
["PvEVendorH"] = iconLink .. "PvEVendorH",
["PvEVendorA"] = iconLink .. "PvEVendorA",
["RenownQuartermaster"] = iconLink .. "RenownQuartermaster",
["RenownQuartermasterH"] = iconLink .. "RenownQuartermasterH",
["RenownQuartermasterA"] = iconLink .. "RenownQuartermasterA",
["ItemUpgrade"] = iconLink .. "ItemUpgrade",
["ScoutingMap"] = iconLink .. "ScoutingMap",
["DragonFlyTransmog"] = iconLink .. "DragonFlyTransmog",
["Catalyst"] = iconLink .. "Catalyst",
["Zidormi"] = "interface/worldmap/chatbubble_64grey",
["BlackMarket"] = iconLink .. "BlackMarket",
["Mailbox"] = iconLink .. "MailboxN",
["CHMailbox"] = iconLink .. "MailboxN",
["MailboxN"] = iconLink .. "MailboxN",
["MailboxH"] = iconLink .. "MailboxH",
["MailboxA"] = iconLink .. "MailboxA",
["StablemasterN"] = iconLink .. "StablemasterN",
["StablemasterH"] = iconLink .. "StablemasterH",
["StablemasterA"] = iconLink .. "StablemasterA",
["TradingPost"] = iconLink .. "TradingPost",
["MountMerchant"] = iconLink .. "MountMerchant",
["CHMountMerchant"] = iconLink .. "MountMerchant",
-- Icons if enemy faction is disabled for General zone icons
["OriginalInnkeeperA"] = iconLink .. "InnkeeperA",
["OriginalInnkeeperH"] = iconLink .. "InnkeeperH",
["OriginalStablemasterH"] = iconLink .. "StablemasterH",
["OriginalStablemasterA"] = iconLink .. "StablemasterA",
["OriginalMailboxH"] = iconLink .. "MailboxH",
["OriginalMailboxA"] = iconLink .. "MailboxA",
["OriginalPvPVendorH"] = iconLink .. "PvPVendorH",
["OriginalPvPVendorA"] = iconLink .. "PvPVendorA",
["OriginalPvEVendorH"] = iconLink .. "PvEVendorH",
["OriginalPvEVendorA"] = iconLink .. "PvEVendorA",
["OriginalRenownQuartermasterH"] = iconLink .. "RenownQuartermasterH",
["OriginalRenownQuartermasterA"] = iconLink .. "RenownQuartermasterA",
-- Icons if enemy faction is disabled for General minimap icons
["MMInnkeeperA"] = iconLink .. "InnkeeperA",
["MMInnkeeperH"] = iconLink .. "InnkeeperH",
["MMStablemasterH"] = iconLink .. "StablemasterH",
["MMStablemasterA"] = iconLink .. "StablemasterA",
["MMMailboxH"] = iconLink .. "MailboxH",
["MMMailboxA"] = iconLink .. "MailboxA",
["MMPvEVendor"] = iconLink .. "PvEVendor",
["MMPvPVendorH"] = iconLink .. "PvPVendorH",
["MMPvPVendorA"] = iconLink .. "PvPVendorA",
["MMPvEVendorH"] = iconLink .. "PvEVendorH",
["MMPvEVendorA"] = iconLink .. "PvEVendorA",
["MMRenownQuartermasterH"] = iconLink .. "RenownQuartermasterH",
["MMRenownQuartermasterA"] = iconLink .. "RenownQuartermasterA",
-- Icons if enemy faction is disabled for General zone icons
["ZonePvEVendor"] = iconLink .. "PvEVendor",
["ZonePvEVendorH"] = iconLink .. "PvEVendorH",
["ZonePvPVendorH"] = iconLink .. "PvPVendorH",
["ZonePvEVendorA"] = iconLink .. "PvEVendorA",
["ZonePvPVendorA"] = iconLink .. "PvPVendorA",
["ZoneRenownQuartermasterH"] = iconLink .. "RenownQuartermasterH",
["ZoneRenownQuartermasterA"] = iconLink .. "RenownQuartermasterA",
-- Icons if enemy faction is disabled for General continent icons
["ContinentPvEVendorH"] = iconLink .. "PvEVendorH",
["ContinentPvEVendorA"] = iconLink .. "PvEVendorA",
["ContinentPvPVendorH"] = iconLink .. "PvPVendorH",
["ContinentPvPVendorA"] = iconLink .. "PvPVendorA",
["ContinentRenownQuartermasterH"] = iconLink .. "RenownQuartermasterH",
["ContinentRenownQuartermasterA"] = iconLink .. "RenownQuartermasterA",
--Professions MN New
["ProfessionsMixed"] = "interface/minimap/tracking/profession",
["ProfessionOrders"] = iconLink .. "CraftingOrders",
["Engineer"] = iconLink .. "Engineering",
["Alchemy"] = iconLink .. "Alchemy",
["Blacksmith"] = iconLink .. "Blacksmithing",
["Skinning"] = iconLink .. "Skinning",
["Enchanting"] = iconLink .. "Enchanting",
["Tailoring"] = iconLink .. "Tailoring",
["Jewelcrafting"] = iconLink .. "Jewelcrafting",
["Leatherworking"] = iconLink .. "Leatherworking",
["Herbalism"] = iconLink .. "Herbalism",
["Mining"] = iconLink .. "Mining",
["Inscription"] = iconLink .. "Inscription",
["Archaeology"] = iconLink .. "Archeology",
["Fishing"] = iconLink .. "Fishing",
["Cooking"] = iconLink .. "Cooking",
["FirstAid"] ="interface/icons/spell_holy_sealofsacrifice",
--Professions Original
["OriginalEngineer"] = "interface/icons/ui_profession_engineering",
["OriginalAlchemy"] = "interface/icons/ui_profession_alchemy",
["OriginalBlacksmith"] = "interface/icons/ui_profession_blacksmithing",
["OriginalSkinning"] = "interface/icons/ui_profession_skinning",
["OriginalEnchanting"] = "interface/icons/ui_profession_enchanting",
["OriginalTailoring"] = "interface/icons/ui_profession_tailoring",
["OriginalJewelcrafting"] = "interface/icons/ui_profession_jewelcrafting",
["OriginalLeatherworking"] = "interface/icons/ui_profession_leatherworking",
["OriginalHerbalism"] = "interface/icons/ui_profession_herbalism",
["OriginalMining"] = "interface/icons/ui_profession_mining",
["OriginalInscription"] = "interface/icons/ui_profession_inscription",
["OriginalArchaeology"] = "interface/archeology/arch-icon-marker",
["OriginalFishing"] = "interface/icons/ui_profession_fishing",
["OriginalCooking"] = "interface/icons/ui_profession_cooking",
--Professions Classic Original
["ClassicOriginalEngineer"] = "interface/icons/trade_engineering",
["ClassicOriginalAlchemy"] = "interface/icons/trade_alchemy",
["ClassicOriginalBlacksmith"] = "interface/icons/trade_blacksmithing",
["ClassicOriginalSkinning"] = "interface/icons/inv_misc_pelt_wolf_01",
["ClassicOriginalEnchanting"] = "interface/icons/trade_engraving",
["ClassicOriginalTailoring"] = "interface/icons/trade_tailoring",
["ClassicOriginalJewelcrafting"] = "interface/icons/inv_misc_gem_02",
["ClassicOriginalLeatherworking"] = "interface/icons/trade_leatherworking",
["ClassicOriginalHerbalism"] = "interface/icons/trade_herbalism",
["ClassicOriginalMining"] = "interface/icons/trade_mining",
["ClassicOriginalInscription"] = "interface/icons/inv_inscription_tradeskill01",
["ClassicOriginalArchaeology"] = "interface/archeology/arch-icon-marker",
["ClassicOriginalFishing"] = "interface/icons/trade_fishing",
["ClassicOriginalCooking"] = "interface/icons/inv_misc_food_15",
--Professions New
["ProfessionOrdersNew"] = iconLink .. "CraftingOrders",
["EngineerNew"] = iconLink .. "Engineering",
["AlchemyNew"] = iconLink .. "Alchemy",
["BlacksmithNew"] = iconLink .. "Blacksmithing",
["SkinningNew"] = iconLink .. "Skinning",
["EnchantingNew"] = iconLink .. "Enchanting",
["TailoringNew"] = iconLink .. "Tailoring",
["JewelcraftingNew"] = iconLink .. "Jewelcrafting",
["LeatherworkingNew"] = iconLink .. "Leatherworking",
["HerbalismNew"] = iconLink .. "Herbalism",
["MiningNew"] = iconLink .. "Mining",
["InscriptionNew"] = iconLink .. "Inscription",
["ArchaeologyNew"] = iconLink .. "Archeology",
["FishingNew"] = iconLink .. "Fishing",
["CookingNew"] = iconLink .. "Cooking",
--expansion 
["LKalimdor"] = "interface/characterframe/temporaryportrait-male-orc",
["LEK"] = "interface/characterframe/temporaryportrait-female-Human",
["LBC"] = "Interface/Icons/Achievement_Boss_Illidan",
["LDF"] = "interface/characterframe/temporaryportrait-Male-Dracthyr",
["LZ"] = "interface/characterframe/temporaryportrait-female-ZandalariTroll",
["LKT"] = "interface/characterframe/temporaryportrait-Male-KulTiran",
["LLG"] = "Interface/Icons/artifactability_HavocDemonHunter_AnguishoftheDeceiver",
["LMOP"] = "interface/characterframe/temporaryportrait-female-PANDAREN",
["LWotlk"] = "interface/lfgframe/ui-lfr-portrait",
["TWW"] = "interface/characterframe/temporaryportrait-female-voidelf",
--paths
["PathO"] = iconLink .. "PathO",
["PathRO"] = iconLink .. "PathRO",
["PathR"] = iconLink .. "PathR",
["PathRU"] = iconLink .. "PathRU",
["PathU"] = iconLink .. "PathU",
["PathLU"] = iconLink .. "PathLU",
["PathL"] = iconLink .. "PathL",
["PathLO"] = iconLink .. "PathLO",
--paths red
["RedPathO"] = iconLink .. "RedPathO",
["RedPathRO"] = iconLink .. "RedPathRO",
["RedPathR"] = iconLink .. "RedPathR",
["RedPathRU"] = iconLink .. "RedPathRU",
["RedPathU"] = iconLink .. "RedPathU",
["RedPathLU"] = iconLink .. "RedPathLU",
["RedPathL"] = iconLink .. "RedPathL",
["RedPathLO"] = iconLink .. "RedPathLO",
--instance
["PetBattleDungeon"] = iconLink .. "PetBattleDungeon",
["LFR"] = iconLink .. "LFR",
["PassageLFR"] = iconLink .. "PassageLFR",
["Dungeon"] = iconLink .. "Dungeon", 
["Raid"] = iconLink .. "Raid",
["Delves"] = iconLink .. "Delves",
["DelvesPassage"] = iconLink .. "DelvesPassage",
["VInstance"] = iconLink .. "vanillaInstance",
["VInstanceD"] = iconLink .. "vanillaInstance",
["VInstanceR"] = iconLink .. "vanillaInstance",
["MultiVInstance"] = iconLink .. "multivanillaInstance",
["MultiVInstanceD"] = iconLink .. "multivanillaInstance",
["MultiVInstanceR"] = iconLink .. "multivanillaInstance",
["VKey1"] = iconLink .. "vkey1",
["MultipleM"] = iconLink .. "multipleM",
["MultipleD"] = iconLink .. "multipleD",
["MultipleR"] = iconLink .. "multipleR",
["Gray"] = iconLink .. "gray",
--zeppelin
["Zeppelin"] = iconLink .. "portal",
["HZeppelin"] = iconLink .. "hportal",
--zeppelin Old
["ZeppelinOld"] = iconLink .. "zeppelin",
["HZeppelinOld"] = iconLink .. "zeppelinH",
--zeppelin restore
["ZeppelinNew"] = iconLink .. "portal",
["HZeppelinNew"] = iconLink .. "hportal",
--portal
["Portal"] = iconLink .. "portal",
["PortalS"] = iconLink .. "portalS",
["HPortal"] = iconLink .. "hportal",
["HPortalS"] = iconLink .. "hportalS",
["HPortalGray"] = iconLink .. "hportalGray",
["HPortalSGray"] = iconLink .. "hportalSGray",
["APortal"] = iconLink .. "aportal",
["APortalS"] = iconLink .. "aportalS",
["APortalGray"] = iconLink .. "aportalGray",
["APortalSGray"] = iconLink .. "aportalSGray",
["PassagePortal"] = iconLink .. "passagePortal",
["PassageHPortal"] = iconLink .. "passageHPortal",
["PassageAPortal"] = iconLink .. "passageAPortal",
["PortalPetBattleDungeon"] = iconLink .. "portalPetBattleDungeon",
["PortalHPetBattleDungeon"] = iconLink .. "portalHPetBattleDungeon",
["PortalAPetBattleDungeon"] = iconLink .. "portalAPetBattleDungeon",
--portal Old
["PortalOld"] = iconLink .. "portalOld",
["PortalSOld"] = iconLink .. "portalSOld",
["HPortalOld"] = iconLink .. "hportalOld",
["HPortalSOld"] = iconLink .. "hportalSOld",
["HPortalOldGray"] = iconLink .. "hportalOldGray",
["HPortalSOldGray"] = iconLink .. "hportalSOldGray",
["APortalOld"] = iconLink .. "aportalOld",
["APortalSOld"] = iconLink .. "aportalSOld",
["APortalOldGray"] = iconLink .. "aportalOldGray",
["APortalSOldGray"] = iconLink .. "aportalSOldGray",
["PassagePortalOld"] = iconLink .. "passagePortalOld",
["PassageHPortalOld"] = iconLink .. "passageHPortalOld",
["PassageAPortalOld"] = iconLink .. "passageAPortalOld",
--portal restore nodes
["PortalNew"] = iconLink .. "portal", -- nodes for Classic Icon Style function to get new the new icons back
["PortalSNew"] = iconLink .. "portalS", -- nodes for Classic Icon Style function to get new the new icons back
["HPortalNew"] = iconLink .. "hportal", -- nodes for Classic Icon Style function to get new the new icons back
["HPortalSNew"] = iconLink .. "hportalS", -- nodes for Classic Icon Style function to get new the new icons back
["HPortalNewGray"] = iconLink .. "hportalGray", -- nodes for Classic Icon Style function to get new the new icons back
["HPortalSNewGray"] = iconLink .. "hportalSGray", -- nodes for Classic Icon Style function to get new the new icons back
["APortalNew"] = iconLink .. "aportal", -- nodes for Classic Icon Style function to get new the new icons back
["APortalSNew"] = iconLink .. "aportalS", -- nodes for Classic Icon Style function to get new the new icons back
["APortalNewGray"] = iconLink .. "aportalGray", -- nodes for Classic Icon Style function to get new the new icons back
["APortalSNewGray"] = iconLink .. "aportalSGray", -- nodes for Classic Icon Style function to get new the new icons back
["PassagePortalNew"] = iconLink .. "passagePortal", -- nodes for Classic Icon Style function to get new the new icons back
["PassageHPortalNew"] = iconLink .. "passageHPortal", -- nodes for Classic Icon Style function to get new the new icons back
["PassageAPortalNew"] = iconLink .. "passageAPortal", -- nodes for Classic Icon Style function to get new the new icons back
--ship
["Ship"] = iconLink .. "portal",
["HShip"] = iconLink .. "hportal",
["AShip"] = iconLink .. "aportal",
--ship Old
["ShipOld"] = iconLink .. "shipOld",
["HShipOld"] = iconLink .. "shipHOld",
["AShipOld"] = iconLink .. "shipAOld",
--ship restore nodes
["ShipNew"] = iconLink .. "portal", -- nodes for Classic Icon Style function to get new the new icons back
["HShipNew"] = iconLink .. "hportal", -- nodes for Classic Icon Style function to get new the new icons back
["AShipNew"] = iconLink .. "aportal", -- nodes for Classic Icon Style function to get new the new icons back
--world passage
["PassageDungeonRaid"] = iconLink .. "PassageDungeon",
["PassageDungeon"] = iconLink .. "PassageDungeon", 
["PassageRaid"] = iconLink .. "passageRaid", 
["PassageDungeonRaidMulti"] = iconLink .. "PassageDungeonRaidMulti", 
["PassageRaidMulti"] = iconLink .. "passageRaidMulti",
["PassageDungeonMulti"] = iconLink .. "PassageDungeonMulti",
["PassageCaveUp"] = iconLink .. "passageCaveUp", 
["PassageCaveDown"] = iconLink .. "passageCaveDown",
["PassageElevatorUp"] = iconLink .. "passageCaveUp", 
["PassageElevatorDown"] = iconLink .. "passageCaveDown",
--inside dungeon icons
["Exit"] = iconLink .. "Exit",
["PassageUpL"] = iconLink .. "passageupL",
["PassageDownL"] = iconLink .. "passagedownL",
["PassageRightL"] = iconLink .. "passagerightL",
["PassageLeftL"] = iconLink .. "passageleftL",
--transport
["Tport2"] = iconLink .. "tport2",
["OgreWaygate"] = iconLink .. "ogreWaygate",
["Mirror"] = iconLink .. "mirror",
["WayGateGolden"] = iconLink .. "WayGateGolden",
["WayGateGreen"] = iconLink .. "WayGateGreen",
["Carriage"] = iconLink .. "Carriage",
["TorghastUp"] = iconLink .. "TorghastUp",
["MoleMachine"] = iconLink .. "MoleMachine",
["RocketDrill"] = iconLink .. "RocketDrill",
["MoleMachineDwarf"] = iconLink .. "MoleMachine",
--travel
["CHTravel"] = iconLink .. "travelL",
["TravelL"] = iconLink .. "travelL",
["TravelM"] = iconLink .. "travelm",
["Travel"] = iconLink .. "travel", -- Horde and Alliance FP
["TravelH"] = iconLink .. "travelH", -- Horde FP
["TravelA"] = iconLink .. "travelA", -- Alliance FP
--special icons
["HIcon"] = iconLink .. "HIcon",
["AIcon"] = iconLink .. "AIcon",
["Ghost"] = iconLink .. "Ghost",
--race portrait icons
["MOrcM"] = "interface/characterframe/temporaryportrait-male-magharorc",
["MOrcF"] = "interface/characterframe/temporaryportrait-female-magharorc",
["N11M"] = "interface/characterframe/temporaryportrait-male-nightelf",
["N11F"] = "interface/characterframe/temporaryportrait-female-nightelf",
["GoblinM"] = "interface/characterframe/temporaryportrait-male-goblin",
["GoblinF"] = "interface/characterframe/temporaryportrait-female-goblin",
["KulM"] = "interface/characterframe/temporaryportrait-male-KulTiran",
["KulF"] = "interface/characterframe/temporaryportrait-female-KulTiran",
["DwarfM"] = "interface/characterframe/temporaryportrait-male-dwarf",
["DwarfF"] = "interface/characterframe/temporaryportrait-female-dwarf",
["OrcM"] = "interface/characterframe/temporaryportrait-male-Orc",
["OrcF"] = "interface/characterframe/temporaryportrait-female-Orc",
["UndeadM"] = "interface/characterframe/temporaryportrait-male-scourge",
["UndeadF"] = "interface/characterframe/temporaryportrait-female-scourge",
["GilneanM"] = "interface/characterframe/temporaryportrait-male-gilnean",
["GilneanF"] = "interface/characterframe/temporaryportrait-female-gilnean",
["GnomeM"] = "interface/characterframe/temporaryportrait-male-gnome",
["GnomeF"] = "interface/characterframe/temporaryportrait-female-gnome",
["DraeneiM"] = "interface/characterframe/temporaryportrait-male-draenei",
["DraeneiF"] = "interface/characterframe/temporaryportrait-female-draenei",
["B11M"] = "interface/characterframe/temporaryportrait-male-bloodelf",
["B11F"] = "interface/characterframe/temporaryportrait-female-bloodelf",
["TrollM"] = "interface/characterframe/temporaryportrait-male-troll",
["TrollF"] = "interface/characterframe/temporaryportrait-female-troll",
["TaureM"] = "interface/characterframe/temporaryportrait-male-tauren",
["TaureF"] = "interface/characterframe/temporaryportrait-female-tauren",
["PandaM"] = "interface/characterframe/temporaryportrait-male-pandaren",
["PandaF"] = "interface/characterframe/temporaryportrait-female-pandaren",
["HMTaurenM"] = "interface/characterframe/temporaryportrait-male-highmountaintauren",
["HMTaurenF"] = "interface/characterframe/temporaryportrait-female-highmountaintauren",
["LFDraeneiM"] = "interface/characterframe/temporaryportrait-male-lightforgeddraenei",
["LFDraeneiF"] = "interface/characterframe/temporaryportrait-female-lightforgeddraenei",
["LN11BorneM"] = "interface/characterframe/temporaryportrait-male-nightborne",
["LN11BorneF"] = "interface/characterframe/temporaryportrait-female-nightborne",
["Void11M"] = "interface/characterframe/temporaryportrait-male-voidelf",
["Void11F"] = "interface/characterframe/temporaryportrait-female-voidelf",
["DarkDwarfM"] = "interface/characterframe/temporaryportrait-male-darkirondwarf",
["DarkDwarfF"] = "interface/characterframe/temporaryportrait-female-darkirondwarf",
["DracthyrM"] = "interface/characterframe/temporaryportrait-male-dracthyr",
["DracthyrF"] = "interface/characterframe/temporaryportrait-female-dracthyr",
["VulperaM"] = "interface/characterframe/temporaryportrait-male-vulpera",
["VulperaF"] = "interface/characterframe/temporaryportrait-female-vulpera",
["MechaGnomeM"] = "interface/characterframe/temporaryportrait-male-mechagnome",
["MechaGnomeF"] = "interface/characterframe/temporaryportrait-female-mechagnome",
["ZandalariTrollM"] = "interface/characterframe/temporaryportrait-male-zandalaritroll",
["ZandalariTrollF"] = "interface/characterframe/temporaryportrait-female-zandalaritroll",
--classes
["Druid"] = "interface/icons/classicon_druid",
["Hunter"] = "interface/icons/classicon_hunter",
["Mage"] = "interface/icons/classicon_mage",
["Paladin"] = "interface/icons/classicon_paladin",
["Priest"] = "interface/icons/classicon_priest",
["Rogue"] = "interface/icons/classicon_rogue",
["Shaman"] = "interface/icons/classicon_shaman",
["Warlock"] = "interface/icons/classicon_warlock",
["Warrior"] = "interface/icons/classicon_warrior",
-- Class Halls
["CHUpgrade"] = "interface/minimap/tracking/class",
["CHScoutingMap"] = iconLink .. "ScoutingMap",
["CHPortal"] = iconLink .. "portalOld",
["ArtifactForge"] = "interface/minimap/vehicle-hammergold-3",
["Recruit"] = "interface/gossipframe/workordergossipicon",
["CHVendor"] = iconLink .. "PvEVendor",
["Archivar"] = "interface/cursor/crosshair/inspect",
["CHStablemasterN"] = iconLink .. "StablemasterN",
-- Class Hall Class Iocns
["CHDeathknight"] = iconLink .. "CHDeathknight",
["CHDemonhunter"] = iconLink .. "CHDemonhunter",
["CHDracyr"] = iconLink .. "CHDracyr",
["CHDruid"] = iconLink .. "CHDruid",
["CHHunter"] = iconLink .. "CHHunter",
["CHMage"] = iconLink .. "CHMage",
["CHMonk"] = iconLink .. "CHMonk",
["CHPaladin"] = iconLink .. "CHPaladin",
["CHPriest"] = iconLink .. "CHPriest",
["CHRogue"] = iconLink .. "CHRogue",
["CHShaman"] = iconLink .. "CHShaman",
["CHWarlock"] = iconLink .. "CHWarlock",
["CHWarrior"] = iconLink .. "CHWarrior",

}

-- change size example: 
-- TextIconMNL4 = TextIcon(iconLink .. "MNL4", { Size = 20 })

TextIconMNL4 = TextIcon(iconLink .. "MNL4")
TextIconInfo = TextIcon("Interface\\FriendsFrame\\InformationIcon")
--General
TextIconInnkeeper = TextIcon("interface/minimap/tracking/innkeeper")
TextIconInnkeeperN = TextIcon(iconLink .. "InnkeeperN")
TextIconInnkeeperH = TextIcon(iconLink .. "InnkeeperH")
TextIconInnkeeperA = TextIcon(iconLink .. "InnkeeperA")
TextIconAuctioneer = TextIcon(iconLink .. "Auctioneer")
TextIconBlackMarket = TextIcon(iconLink .. "BlackMarket")
TextIconBank = TextIcon(iconLink .. "BankNew")
TextIconBankOld = TextIcon("interface/minimap/tracking/banker")
TextIconBankNew = TextIcon(iconLink .. "BankNew")
TextIconBarber = TextIcon("interface/minimap/tracking/barbershop")
TextIconTransmogger = TextIcon("interface/minimap/tracking/transmogrifier")
TextIconPvPVendor = TextIcon(iconLink .. "PvPVendor")
TextIconPvPVendorH = TextIcon(iconLink .. "PvPVendorH")
TextIconPvPVendorA = TextIcon(iconLink .. "PvPVendorA")
TextIconPvEVendor = TextIcon(iconLink .. "PvEVendor")
TextIconPvEVendorH = TextIcon(iconLink .. "PvEVendorH")
TextIconPvEVendorA = TextIcon(iconLink .. "PvEVendorA")
TextIconRenownQuartermaster = TextIcon(iconLink .. "RenownQuartermaster")
TextIconRenownQuartermasterH = TextIcon(iconLink .. "RenownQuartermasterH")
TextIconRenownQuartermasterA = TextIcon(iconLink .. "RenownQuartermasterA")
TextIconItemUpgrade = TextIcon(iconLink .. "ItemUpgrade")
TextIconDragonFlyTransmog = TextIcon(iconLink .. "DragonFlyTransmog")
TextIconCatalyst = TextIcon(iconLink .. "Catalyst")
TextIconZidormi = TextIcon("interface/worldmap/chatbubble_64grey")
TextIconMailbox = TextIcon("interface/minimap/tracking/mailbox")
TextIconMailboxN = TextIcon(iconLink .. "MailboxN")
TextIconMailboxH = TextIcon(iconLink .. "MailboxH")
TextIconMailboxA = TextIcon(iconLink .. "MailboxA")
TextIconStablemasterN = TextIcon(iconLink .. "StablemasterN")
TextIconStablemasterH = TextIcon(iconLink .. "StablemasterH")
TextIconStablemasterA = TextIcon(iconLink .. "StablemasterA")
TextIconTradingPost = TextIcon(iconLink .. "TradingPost")
TextIconMountMerchant = TextIcon(iconLink .. "MountMerchant")
--Cities
TextIconOrgrimmar = TextIcon("interface/icons/spell_arcane_teleportorgrimmar")
TextIconThunderBluff = TextIcon("interface/icons/spell_arcane_teleportthunderbluff")
TextIconSilvermoon = TextIcon("interface/icons/spell_arcane_teleportsilvermoon")
TextIconUndercity = TextIcon("interface/icons/spell_arcane_teleportundercity")
TextIconStormwind = TextIcon("interface/icons/spell_arcane_teleportstormwind")
TextIconIronforge = TextIcon("interface/icons/spell_arcane_teleportironforge")
TextIconDarnassus = TextIcon("interface/icons/spell_arcane_teleportdarnassus")
TextIconExodar = TextIcon("interface/icons/spell_arcane_teleportexodar")
TextIconShattrath = TextIcon("interface/icons/spell_arcane_teleportshattrath")
TextIconDalaranNorthrend = TextIcon("interface/icons/spell_arcane_teleportdalaran")
TextIconDalaranLegion = TextIcon("interface/icons/spell_arcane_teleportdalaranbrokenisles")
TextIconDazarAlor = TextIcon("interface/icons/spell_arcane_teleportzandalar")
TextIconBoralus = TextIcon("interface/icons/spell_arcane_teleportkultiras")
TextIconSot2M = TextIcon("interface/icons/spell_arcane_teleporthalloftheguardian")
TextIconSot7S = TextIcon("interface/icons/spell_arcane_teleporttolbarad")
TextIconWarspear = TextIcon("interface/icons/spell_arcane_teleportwarspear")
TextIconStormshield = TextIcon("interface/icons/spell_arcane_teleportstormshield")
TextIconOribos = TextIcon("interface/icons/spell_arcane_teleportoribos")
TextIconValdrakken = TextIcon("interface/icons/spell_arcane_teleportvaldrakken")
TextIconDornogal = TextIcon("interface/icons/inv_spell_arcane_telepotdornogal")
--profession
TextIconProfessionsMixed = TextIcon("interface/minimap/tracking/profession")
TextIconProfessionOrders = TextIcon(iconLink .. "CraftingOrders")
TextIconEngineer = TextIcon(iconLink .. "Engineering")
TextIconAlchemy = TextIcon(iconLink .. "Alchemy")
TextIconBlacksmith = TextIcon(iconLink .. "Blacksmithing")
TextIconSkinning = TextIcon(iconLink .. "Skinning")
TextIconTailoring = TextIcon(iconLink .. "Tailoring")
TextIconJewelcrafting = TextIcon(iconLink .. "Jewelcrafting")
TextIconLeatherworking = TextIcon(iconLink .. "Leatherworking")
TextIconHerbalism = TextIcon(iconLink .. "Herbalism")
TextIconMining = TextIcon(iconLink .. "Mining")
TextIconArchaeology = TextIcon(iconLink .. "Archeology")
TextIconFishing = TextIcon(iconLink .. "Fishing")
TextIconCooking = TextIcon(iconLink .. "Cooking")
TextIconInscription = TextIcon(iconLink .. "Inscription")
TextIconEnchanting = TextIcon(iconLink .. "Enchanting")
TextIconFirstAid = TextIcon("interface/icons/spell_holy_sealofsacrifice")
--profession Original
TextIconOriginalEngineer = TextIcon("interface/icons/ui_profession_engineering")
TextIconOriginalAlchemy = TextIcon("interface/icons/ui_profession_alchemy")
TextIconOriginalBlacksmith = TextIcon("interface/icons/ui_profession_blacksmithing")
TextIconOriginalSkinning = TextIcon("interface/icons/ui_profession_skinning")
TextIconOriginalTailoring = TextIcon("interface/icons/ui_profession_tailoring")
TextIconOriginalJewelcrafting = TextIcon("interface/icons/ui_profession_jewelcrafting")
TextIconOriginalLeatherworking = TextIcon("interface/icons/ui_profession_leatherworking")
TextIconOriginalHerbalism = TextIcon("interface/icons/ui_profession_herbalism")
TextIconOriginalMining = TextIcon("interface/icons/ui_profession_mining")
TextIconOriginalArchaeology = TextIcon("interface/archeology/arch-icon-marker")
TextIconOriginalFishing = TextIcon("interface/icons/ui_profession_fishing")
TextIconOriginalCooking = TextIcon("interface/icons/ui_profession_cooking")
TextIconOriginalInscription = TextIcon("interface/icons/ui_profession_inscription")
TextIconOriginalEnchanting = TextIcon("interface/icons/ui_profession_enchanting")
--profession ClassicOriginal
TextIconClassicOriginalEngineer = TextIcon("interface/icons/trade_engineering")
TextIconClassicOriginalAlchemy = TextIcon("interface/icons/trade_alchemy")
TextIconClassicOriginalBlacksmith = TextIcon("interface/icons/trade_blacksmithing")
TextIconClassicOriginalSkinning = TextIcon("interface/icons/inv_misc_pelt_wolf_01")
TextIconClassicOriginalTailoring = TextIcon("interface/icons/trade_tailoring")
TextIconClassicOriginalJewelcrafting = TextIcon("interface/icons/inv_misc_gem_02")
TextIconClassicOriginalLeatherworking = TextIcon("interface/icons/trade_leatherworking")
TextIconClassicOriginalHerbalism = TextIcon("interface/icons/trade_herbalism")
TextIconClassicOriginalMining = TextIcon("interface/icons/trade_mining")
TextIconClassicOriginalArchaeology = TextIcon("interface/archeology/arch-icon-marker")
TextIconClassicOriginalFishing = TextIcon("interface/icons/trade_fishing")
TextIconClassicOriginalCooking = TextIcon("interface/icons/inv_misc_food_15")
TextIconClassicOriginalInscription = TextIcon("interface/icons/inv_inscription_tradeskill01")
TextIconClassicOriginalEnchanting = TextIcon("interface/icons/trade_engraving")
--portal
TextIconPortal = TextIcon(iconLink .. "portal") 
TextIconHPortal = TextIcon(iconLink .. "hportal")
TextIconAPortal = TextIcon(iconLink .. "aportal")
TextIconPassagePortal = TextIcon(iconLink .. "passagePortal") 
TextIconPassageHPortal = TextIcon(iconLink .. "passageHPortal")
TextIconPassageAPortal = TextIcon(iconLink .. "passageAPortal")
TextIconWayGateGolden = TextIcon(iconLink .. "WayGateGolden")
TextIconWayGateGreen = TextIcon(iconLink .. "WayGateGreen")
TextIconDarkMoon = TextIcon(iconLink .. "DarkMoon")
TextIconTorghastUp = TextIcon(iconLink .. "TorghastUp")
TextIconPortalPetBattleDungeon = TextIcon(iconLink .. "portalPetBattleDungeon")
TextIconPortalHPetBattleDungeon = TextIcon(iconLink .. "portalHPetBattleDungeon")
TextIconPortalAPetBattleDungeon = TextIcon(iconLink .. "portalAPetBattleDungeon")
--portal Old
TextIconPortalOld = TextIcon(iconLink .. "portalOld") 
TextIconHPortalOld = TextIcon(iconLink .. "hportalOld")
TextIconAPortalOld = TextIcon(iconLink .. "aportalOld")
TextIconPassagePortalOld = TextIcon(iconLink .. "passagePortalOld") 
TextIconPassageHPortalOld = TextIcon(iconLink .. "passageHPortalOld")
TextIconPassageAPortalOld = TextIcon(iconLink .. "passageAPortalOld")
--paths
TextIconPathO = TextIcon(iconLink .. "PathO")
TextIconPathR = TextIcon(iconLink .. "PathR")
TextIconPathU = TextIcon(iconLink .. "PathU")
TextIconPathL = TextIcon(iconLink .. "PathL")
--paths red
TextIconRedPathO = TextIcon(iconLink .. "RedPathO")
TextIconRedPathR = TextIcon(iconLink .. "RedPathR")
TextIconRedPathU = TextIcon(iconLink .. "RedPathU")
TextIconRedPathL = TextIcon(iconLink .. "RedPathL")
TextIconRedPathRO = TextIcon(iconLink .. "RedPathRO")
TextIconRedPathRU = TextIcon(iconLink .. "RedPathRU")
TextIconRedPathLU = TextIcon(iconLink .. "RedPathLU")
TextIconRedPathLO = TextIcon(iconLink .. "RedPathLO")
--instance
TextIconPetBattleDungeon = TextIcon(iconLink .. "PetBattleDungeon")
TextIconLFR = TextIcon(iconLink .. "LFR")
TextIconPassageLFR = TextIcon(iconLink .. "PassageLFR")
TextIconDungeon = TextIcon(iconLink .. "Dungeon")
TextIconRaid = TextIcon(iconLink .. "Raid")
TextIconDelves = TextIcon(iconLink .. "Delves")
TextIconDelvesPassage = TextIcon(iconLink .. "DelvesPassage")
TextIconVInstance = TextIcon(iconLink .. "vanillaInstance")
TextIconMultiVInstance = TextIcon(iconLink .. "multivanillaInstance")
TextIconVKey1 = TextIcon(iconLink .. "vkey1")
TextIconMultipleM = TextIcon(iconLink .. "multipleM")
TextIconMultipleD = TextIcon(iconLink .. "multipleD")
TextIconMultipleR = TextIcon(iconLink .. "multipleR")
TextIconPassageDungeonRaidM = TextIcon(iconLink .. "PassageDungeonRaid")
TextIconPassageDungeonM = TextIcon(iconLink .. "PassageDungeon")
TextIconPassageRaidM = TextIcon(iconLink .. "PassageRaid")
TextIconPassageDungeonRaidMultiM = TextIcon(iconLink .. "PassageDungeonRaidMulti")
TextIconPassageDungeonMultiM = TextIcon(iconLink .. "PassageDungeonMulti")
TextIconPassageRaidMultiM = TextIcon(iconLink .. "PassageRaidMulti")
TextIconLocked = TextIcon(iconLink .. "gray")
--zeppelin
TextIconZeppelin = TextIcon(iconLink .. "portal")
TextIconHZeppelin = TextIcon(iconLink .. "hportal")
--zeppelin Old
TextIconZeppelinOld = TextIcon(iconLink .. "zeppelin")
TextIconHZeppelinOld = TextIcon(iconLink .. "zeppelinH")
--ship
TextIconShip = TextIcon(iconLink .. "portal")
TextIconHShip = TextIcon(iconLink .. "hportal")
TextIconAShip = TextIcon(iconLink .. "aportal")
--ship Old
TextIconShipOld = TextIcon(iconLink .. "shipOld")
TextIconHShipOld = TextIcon(iconLink .. "shipHOld")
TextIconAShipOld = TextIcon(iconLink .. "shipAOld")
--passage World
TextIconPassageCaveUp = TextIcon(iconLink .. "PassageCaveUp")
TextIconPassageCaveDown = TextIcon(iconLink .. "PassageCaveDown")
--inside dungeon icons
TextIconExit = TextIcon(iconLink .. "Exit")
TextIconPassageup = TextIcon(iconLink .. "PassageUpL")
TextIconPassagedown = TextIcon(iconLink .. "PassageDownL")
TextIconPassageright = TextIcon(iconLink .. "PassageRightL")
TextIconPassageleft = TextIcon(iconLink .. "PassageLeftL")
--special icon
TextIconTravel = TextIcon(iconLink .. "travel")
TextIconTravelA = TextIcon(iconLink .. "travelA")
TextIconTravelH = TextIcon(iconLink .. "travelH")
TextIconTravelL = TextIcon(iconLink .. "travelL")
TextIconAIcon = TextIcon(iconLink .. "AIcon")
TextIconHIcon = TextIcon(iconLink .. "HIcon")
TextIconGhost = TextIcon(iconLink .. "Ghost")
--transport
TextIconTransport = TextIcon(iconLink .. "tport2")
TextIconOgreWaygate = TextIcon("Interface/Minimap/Vehicle-AllianceWarlockPortal")
TextIconToyTransport = TextIcon("interface/icons/inv_tailoring_elekkplushie")
TextIconMirror = TextIcon(iconLink .. "mirror")
TextIconCarriage = TextIcon("interface/minimap/vehicle-carriage")
TextIconMoleMachine = TextIcon(iconLink .. "MoleMachine")
TextIconRocketDrill = TextIcon(iconLink .. "RocketDrill")
TextIconPassageElevatorUp = TextIcon(iconLink .. "PassageCaveUp")
TextIconPassageElevatorDown = TextIcon(iconLink .. "PassageCaveDown")
--information
TextIconCheck = TextIcon("Interface/Buttons/UI-CheckBox-Up")
TextIconHorde = TextIcon("interface/pvprankbadges/pvprankhorde")
TextIconAlliance = TextIcon("interface/pvprankbadges/pvprankalliance")
TextIconTomTom = TextIcon(iconLink .."tomtompoint")
TextIconWayPoint = TextIcon("interface/minimap/minimap-waypoint-mappin-untracked")
TextIconJournal = TextIcon("interface/icons/inv_misc_book_09")
TextIconBosses = TextIcon("Interface/TargetingFrame/UI-RaidTargetingIcon_8")
TextIconTarget = TextIcon("Interface/TargetingFrame/UI-RaidTargetingIcon_7")
--expansions
TextIconKalimdor = TextIcon("interface/characterframe/temporaryportrait-female-Orc")
TextIconEK = TextIcon("interface/characterframe/temporaryportrait-female-Human")
TextIconBC = TextIcon("Interface/Icons/Achievement_Boss_Illidan")
TextIconNorthrend = TextIcon("interface/lfgframe/ui-lfr-portrait")
TextIconPandaria = TextIcon("interface/characterframe/temporaryportrait-female-PANDAREN")
TextIconDraenor = TextIcon("interface/characterframe/temporaryportrait-Male-MagharOrc")
TextIconLegion = TextIcon("Interface/Icons/artifactability_HavocDemonHunter_AnguishoftheDeceiver")
TextIconZandalar = TextIcon("interface/characterframe/temporaryportrait-female-ZandalariTroll")
TextIconKT = TextIcon("interface/characterframe/temporaryportrait-Male-KulTiran")
TextIconSL = TextIcon("interface/icons/achievement_leader_sylvanas")
TextIconDF = TextIcon("interface/characterframe/temporaryportrait-Male-Dracthyr")
TextIconKA = TextIcon("interface/lfgframe/lfgicon-khazalgar")
TextIconHousing = TextIcon(iconLink .. "Housing")
--race portrait icons
TextIconMOrcM = TextIcon("interface/characterframe/temporaryportrait-male-magharorc")
TextIconMOrcF = TextIcon("interface/characterframe/temporaryportrait-female-magharorc")
TextIconN11M = TextIcon("interface/characterframe/temporaryportrait-male-nightelf")
TextIconN11F = TextIcon("interface/characterframe/temporaryportrait-female-nightelf")
TextIconGoblinM = TextIcon("interface/characterframe/temporaryportrait-male-goblin")
TextIconGoblinF = TextIcon("interface/characterframe/temporaryportrait-female-goblin")
TextIconKulM = TextIcon("interface/characterframe/temporaryportrait-male-KulTiran")
TextIconKulF = TextIcon("interface/characterframe/temporaryportrait-female-KulTiran")
TextIconDwarfM = TextIcon("interface/characterframe/temporaryportrait-male-dwarf")
TextIconDwarfF = TextIcon("interface/characterframe/temporaryportrait-female-dwarf")
TextIconOrcM = TextIcon("interface/characterframe/temporaryportrait-male-Orc")
TextIconOrcF = TextIcon("interface/characterframe/temporaryportrait-female-Orc")
TextIconUndeadM = TextIcon("interface/characterframe/temporaryportrait-male-scourge")
TextIconUndeadF = TextIcon("interface/characterframe/temporaryportrait-female-scourge")
TextIconGilneanM = TextIcon("interface/characterframe/temporaryportrait-male-gilnean")
TextIconGilneanF = TextIcon("interface/characterframe/temporaryportrait-female-gilnean")
TextIconGnomeM = TextIcon("interface/characterframe/temporaryportrait-male-gnome")
TextIconGnomeF = TextIcon("interface/characterframe/temporaryportrait-female-gnome")
TextIconDraeneiM = TextIcon("interface/characterframe/temporaryportrait-male-draenei")
TextIconDraeneiF = TextIcon("interface/characterframe/temporaryportrait-female-draenei")
TextIconB11M = TextIcon("interface/characterframe/temporaryportrait-male-bloodelf")
TextIconB11F = TextIcon("interface/characterframe/temporaryportrait-female-bloodelf")
TextIconTrollM = TextIcon("interface/characterframe/temporaryportrait-male-troll")
TextIconTrollF = TextIcon("interface/characterframe/temporaryportrait-female-troll")
TextIconTaurenM = TextIcon("interface/characterframe/temporaryportrait-male-tauren")
TextIconTaurenF = TextIcon("interface/characterframe/temporaryportrait-female-tauren")
TextIconPandaM = TextIcon("interface/characterframe/temporaryportrait-male-pandaren")
TextIconPandaF = TextIcon("interface/characterframe/temporaryportrait-female-pandaren")
TextIconHMTaureM = TextIcon("interface/characterframe/temporaryportrait-male-highmountaintauren")
TextIconHMTaureF = TextIcon("interface/characterframe/temporaryportrait-female-highmountaintauren")
TextIconLFDraeneiM = TextIcon("interface/characterframe/temporaryportrait-male-lightforgeddraenei")
TextIconLFDraeneiF = TextIcon("interface/characterframe/temporaryportrait-female-lightforgeddraenei")
TextIconLN11BorneM = TextIcon("interface/characterframe/temporaryportrait-male-nightborne")
TextIconLN11BorneF = TextIcon("interface/characterframe/temporaryportrait-female-nightborne")
TextIconVoid11M = TextIcon("interface/characterframe/temporaryportrait-male-voidelf")
TextIconVoid11F = TextIcon("interface/characterframe/temporaryportrait-female-voidelf")
TextIconDarkDwarfM = TextIcon("interface/characterframe/temporaryportrait-male-darkirondwarf")
TextIconDarkDwarfF = TextIcon("interface/characterframe/temporaryportrait-female-darkirondwarf")
TextIconDracthyrM = TextIcon("interface/characterframe/temporaryportrait-male-dracthyr")
TextIconDracthyrF = TextIcon("interface/characterframe/temporaryportrait-female-dracthyr")
TextIconVulperaM = TextIcon("interface/characterframe/temporaryportrait-male-vulpera")
TextIconVulperaF = TextIcon("interface/characterframe/temporaryportrait-female-vulpera")
TextIconMechaGnomeM = TextIcon("interface/characterframe/temporaryportrait-male-mechagnome")
TextIconMechaGnomeF = TextIcon("interface/characterframe/temporaryportrait-female-mechagnome")
TextIconZandalariTrollM = TextIcon("interface/characterframe/temporaryportrait-male-zandalaritroll")
TextIconZandalariTrollF = TextIcon("interface/characterframe/temporaryportrait-female-zandalaritroll")
--classes
TextIconClassDruid = TextIcon("interface/icons/classicon_druid")
TextIconClassHunter = TextIcon("interface/icons/classicon_hunter")
TextIconClassMage = TextIcon("interface/icons/classicon_mage")
TextIconClassPaladin = TextIcon("interface/icons/classicon_paladin")
TextIconClassPriest = TextIcon("interface/icons/classicon_priest")
TextIconClassRogue = TextIcon("interface/icons/classicon_rogue")
TextIconClassShaman = TextIcon("interface/icons/classicon_shaman")
TextIconClassWarlock = TextIcon("interface/icons/classicon_warlock")
TextIconClassWarrior = TextIcon("interface/icons/classicon_warrior")
-- Class Halls
TextIconUpgrade = TextIcon("interface/minimap/tracking/class")
TextIconScoutingMap = TextIcon(iconLink .. "ScoutingMap")
TextIconCHTravel = TextIcon(iconLink .. "travelL")
TextIconArtifactForge = TextIcon("interface/minimap/vehicle-hammergold-3")
TextIconRecruit = TextIcon("interface/gossipframe/workordergossipicon")
TextIconArchivar = TextIcon("interface/cursor/crosshair/inspect")
-- Class Hall Class Iocns
TextIconCHDeathknight = TextIcon(iconLink .. "CHDeathknight")
TextIconCHDemonhunter = TextIcon(iconLink .. "CHDemonhunter")
TextIconCHDracyr = TextIcon(iconLink .. "CHDracyr")
TextIconCHDruid = TextIcon(iconLink .. "CHDruid")
TextIconCHHunter = TextIcon(iconLink .. "CHHunter")
TextIconCHMage = TextIcon(iconLink .. "CHMage")
TextIconCHMonk = TextIcon(iconLink .. "CHMonk")
TextIconCHPaladin = TextIcon(iconLink .. "CHPaladin")
TextIconCHPriest = TextIcon(iconLink .. "CHPriest")
TextIconCHRogue = TextIcon(iconLink .. "CHRogue")
TextIconCHShaman = TextIcon(iconLink .. "CHShaman")
TextIconCHWarlock = TextIcon(iconLink .. "CHWarlock")
TextIconCHWarrior = TextIcon(iconLink .. "CHWarrior")