-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Immerseus", {
	[143020] = "cyan",
	[143295] = "blue",
	[143309] = "red",
	[143436] = {"blue","orange"},
	[143469] = "cyan",
	[143574] = "yellow",
	[143579] = "blue",
})

BigWigs:AddSounds("Immerseus", {
	[143295] = "info",
	[143309] = "long",
	[143436] = {"alarm","warning"},
	[143574] = "alert",
	[143579] = "info",
})

BigWigs:AddColors("The Fallen Protectors", {
	[-7959] = {"blue","orange"},
	[-7958] = "orange",
	[143007] = "red",
	[143019] = "blue",
	[143027] = "yellow",
	[143292] = {"blue","yellow"},
	[143330] = "orange",
	[143423] = "blue",
	[143446] = "orange",
	[143491] = "yellow",
	[143497] = "green",
	[143564] = "blue",
	[143840] = {"blue","red"},
	[143958] = "blue",
	[144367] = "blue",
	[144396] = "orange",
	["defile_you"] = "blue",
	["inferno_self"] = {"blue","orange"},
	["intermission"] = {"cyan","red"},
})

BigWigs:AddSounds("The Fallen Protectors", {
	[-7958] = "alarm",
	[143007] = "alarm",
	[143019] = "info",
	[143292] = "long",
	[143330] = "warning",
	[143423] = "warning",
	[143446] = "alarm",
	[143497] = "warning",
	[143564] = "info",
	[143840] = {"alert","info"},
	[143958] = "info",
	[144367] = "info",
	[144396] = "alarm",
	["defile_you"] = "info",
	["inferno_self"] = "warning",
	["intermission"] = {"alert","info"},
})

BigWigs:AddColors("Norushen", {
	[-8220] = {"blue","cyan"},
	[-8218] = "yellow",
	[144482] = "yellow",
	[144514] = "orange",
	[144628] = "yellow",
	[144649] = "orange",
	[145132] = "yellow",
	[145226] = "red",
	[146124] = {"blue","yellow"},
	["big_adds"] = {"orange","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Norushen", {
	[-8220] = "warning",
	[144482] = "info",
	[144514] = "warning",
	[144628] = "info",
	[144649] = "warning",
	[145226] = "long",
	[146124] = "info",
	["big_adds"] = {"alarm","alert"},
	["stages"] = {"info","warning"},
})

BigWigs:AddColors("Sha of Pride", {
	[-8349] = "cyan",
	[-8270] = {"blue","yellow"},
	[-8262] = "orange",
	[-8258] = "blue",
	[-8257] = "blue",
	[144351] = "red",
	[144358] = {"blue","red"},
	[144400] = "yellow",
	[144563] = {"blue","cyan"},
	[144800] = "red",
	[144832] = "cyan",
	[145215] = {"blue","yellow"},
	[146595] = {"cyan","green"},
	[146817] = "blue",
	[147207] = "blue",
})

BigWigs:AddSounds("Sha of Pride", {
	[-8349] = "info",
	[-8262] = "alert",
	[-8258] = "warning",
	[-8257] = "alarm",
	[144351] = "alarm",
	[144358] = "warning",
	[144400] = "info",
	[144832] = "info",
	[146595] = "long",
	[146817] = "alert",
})

BigWigs:AddColors("Galakras", {
	[-8489] = "orange",
	[-8443] = "orange",
	[146757] = "red",
	[146765] = "blue",
	[146769] = "orange",
	[146899] = {"blue","orange"},
	[147068] = {"blue","red","yellow"},
	[147328] = "orange",
	[147705] = "blue",
	["adds"] = "yellow",
	["demolisher"] = "yellow",
	["drakes"] = "yellow",
	["stages"] = {"blue","cyan"},
	["towers"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Galakras", {
	[-8489] = "warning",
	[-8443] = "alert",
	[146757] = "warning",
	[146769] = "alert",
	[146899] = "alarm",
	[147068] = "warning",
	[147705] = "info",
	["adds"] = "info",
	["drakes"] = "info",
	["stages"] = "warning",
	["towers"] = "long",
})

BigWigs:AddColors("Iron Juggernaut", {
	[-8190] = {"blue","red"},
	[-8183] = "orange",
	[-8181] = "yellow",
	[-8179] = {"blue","yellow"},
	[144459] = {"blue","red"},
	[144467] = {"blue","yellow"},
	[144485] = "yellow",
	[144498] = {"blue","yellow"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Iron Juggernaut", {
	[-8190] = "warning",
	[-8179] = "info",
	[144485] = "alert",
	[144498] = "info",
	["stages"] = "long",
})

BigWigs:AddColors("Kor'kron Dark Shaman", {
	[-8132] = {"blue","green"},
	[-8124] = "cyan",
	[143973] = "yellow",
	[143990] = {"blue","red"},
	[144005] = {"blue","orange"},
	[144070] = "cyan",
	[144215] = {"blue","yellow"},
	[144302] = "cyan",
	[144328] = "red",
	[144330] = "yellow",
})

BigWigs:AddSounds("Kor'kron Dark Shaman", {
	[-8132] = "alarm",
	[-8124] = "info",
	[143973] = "info",
	[143990] = "alert",
	[144005] = {"alert","info"},
	[144215] = "warning",
	[144302] = "info",
	[144328] = "long",
	[144330] = "warning",
})

BigWigs:AddColors("General Nazgrim", {
	[-7947] = {"blue","yellow"},
	[-7933] = {"blue","yellow"},
	[-7920] = "cyan",
	[-7915] = "green",
	[143431] = "red",
	[143474] = "yellow",
	[143475] = {"blue","green"},
	[143494] = {"blue","yellow"},
	[143502] = "red",
	[143503] = "red",
	[143536] = "yellow",
	[143638] = {"blue","orange"},
	[143716] = {"blue","orange"},
	[143872] = {"blue","orange"},
	["arcane_shock"] = "blue",
	["chain_heal"] = "blue",
})

BigWigs:AddSounds("General Nazgrim", {
	[-7947] = "alarm",
	[-7933] = "info",
	[-7920] = {"info","long"},
	[-7915] = "alert",
	[143431] = "alarm",
	[143475] = "warning",
	[143494] = "info",
	[143502] = "warning",
	[143503] = "warning",
	[143536] = "alert",
	[143638] = "info",
	[143716] = "alarm",
	[143872] = "alarm",
	["arcane_shock"] = "alert",
	["chain_heal"] = "alert",
})

BigWigs:AddColors("Malkorok", {
	[142826] = "yellow",
	[142842] = "red",
	[142851] = "orange",
	[142879] = "cyan",
	[142913] = {"blue","orange"},
	[142986] = "orange",
	[142990] = {"blue","yellow"},
})

BigWigs:AddSounds("Malkorok", {
	[142842] = "warning",
	[142851] = "info",
	[142879] = "long",
	[142913] = "alert",
	[142986] = "alarm",
})

BigWigs:AddColors("Spoils of Pandaria", {
	[142694] = "yellow",
	[142947] = "orange",
	[145288] = "red",
	[145461] = "orange",
	[145692] = {"blue","orange"},
	[145715] = "blue",
	[145747] = "blue",
	[145786] = {"orange","yellow"},
	[145987] = {"green","red"},
	[146217] = "blue",
	[146222] = "yellow",
	[146257] = "blue",
	[146815] = "red",
	["berserk"] = "green",
	["crates"] = {"red","yellow"},
})

BigWigs:AddSounds("Spoils of Pandaria", {
	[142947] = {"alarm","warning"},
	[145288] = "alert",
	[145461] = "alarm",
	[145692] = "alarm",
	[145715] = "info",
	[145747] = "info",
	[145786] = "alarm",
	[145987] = "warning",
	[146217] = "info",
	[146222] = "long",
	[146257] = "info",
	[146815] = "alert",
	["crates"] = "long",
})

BigWigs:AddColors("Thok the Bloodthirsty", {
	[-7981] = {"cyan","yellow"},
	[-7980] = {"blue","green","orange"},
	[-7963] = "yellow",
	[143766] = {"blue","yellow"},
	[143767] = {"blue","yellow"},
	[143773] = {"blue","yellow"},
	[143777] = {"blue","yellow"},
	[143780] = {"blue","yellow"},
	[143783] = "blue",
	[145974] = {"blue","orange"},
	[146589] = {"blue","green","yellow"},
	[148145] = "red",
})

BigWigs:AddSounds("Thok the Bloodthirsty", {
	[-7981] = "long",
	[-7980] = "alarm",
	[143766] = "warning",
	[143767] = "warning",
	[143773] = "warning",
	[143780] = "warning",
	[143783] = "info",
	[145974] = "alert",
	[146589] = {"alert","warning"},
	[148145] = "warning",
})

BigWigs:AddColors("Siegecrafter Blackfuse", {
	[-8408] = "red",
	[-8212] = {"blue","orange"},
	[-8208] = "blue",
	[-8207] = "green",
	[-8202] = {"cyan","green"},
	[-8199] = "yellow",
	[-8195] = {"blue","green"},
	[143385] = {"blue","yellow"},
	[143639] = "orange",
	[143856] = "blue",
	[144208] = "yellow",
	[144466] = "red",
	[145365] = "yellow",
	[145444] = "orange",
	[146479] = {"blue","yellow"},
})

BigWigs:AddSounds("Siegecrafter Blackfuse", {
	[-8212] = "info",
	[-8208] = "info",
	[-8202] = "warning",
	[-8199] = "long",
	[-8195] = "info",
	[143385] = "info",
	[143856] = "info",
	[144208] = "alert",
	[144466] = "long",
	[145365] = "long",
	[146479] = "alarm",
})

BigWigs:AddColors("Paragons of the Klaxxi", {
	[-8073] = {"blue","red"},
	[-8065] = "blue",
	[-8055] = {"blue","yellow"},
	[-8034] = {"blue","cyan"},
	[-8008] = {"blue","orange"},
	[-8003] = "cyan",
	[142564] = {"blue","red"},
	[142671] = {"blue","red"},
	[142803] = "blue",
	[142931] = {"blue","yellow"},
	[143243] = "orange",
	[143280] = "red",
	[143337] = "yellow",
	[143339] = {"green","orange","yellow"},
	[143576] = "blue",
	[143701] = {"blue","orange"},
	[143735] = "blue",
	[143759] = "yellow",
	[143939] = {"blue","orange"},
	[143974] = {"blue","orange"},
	[148589] = {"blue","red"},
	[148677] = "orange",
})

BigWigs:AddSounds("Paragons of the Klaxxi", {
	[-8073] = "warning",
	[-8065] = "info",
	[-8055] = "info",
	[-8034] = {"alert","long"},
	[-8008] = "alarm",
	[142564] = "warning",
	[142671] = "warning",
	[142803] = "info",
	[143243] = "long",
	[143280] = "warning",
	[143337] = "alert",
	[143339] = {"info","warning"},
	[143576] = "info",
	[143701] = "info",
	[143735] = "info",
	[143939] = "alarm",
	[143974] = "alarm",
	[148589] = "warning",
	[148677] = "long",
})

BigWigs:AddColors("Garrosh Hellscream", {
	[-8305] = "cyan",
	[-8298] = "yellow",
	[-8294] = "orange",
	[-8292] = "yellow",
	[144616] = "red",
	[144758] = {"blue","orange"},
	[144821] = "yellow",
	[144945] = {"blue","green","yellow"},
	[144969] = "yellow",
	[144985] = "red",
	[145065] = "orange",
	[145183] = {"blue","yellow"},
	[147209] = {"blue","orange"},
	[147235] = "blue",
	[147665] = {"blue","yellow"},
	["bombardment"] = "yellow",
	["chain_heal"] = "blue",
	["clump_check"] = "red",
	["manifest_rage"] = "red",
	["stages"] = {"cyan","yellow"},
})

BigWigs:AddSounds("Garrosh Hellscream", {
	[-8294] = "alert",
	[144758] = "alarm",
	[144945] = {"long","warning"},
	[144985] = "long",
	[145065] = "alert",
	[145183] = "warning",
	[147209] = "alarm",
	[147235] = "alert",
	[147665] = "warning",
	["chain_heal"] = "alert",
	["clump_check"] = "long",
	["manifest_rage"] = "warning",
	["stages"] = "info",
})
