-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Akil'zon", {
	[43648] = {"blue","red"},
})

BigWigs:AddSounds("Akil'zon", {
	[43648] = "alert",
})

BigWigs:AddColors("Nalorakk", {
	[42398] = {"blue","yellow"},
	["stages"] = "red",
})

BigWigs:AddSounds("Nalorakk", {
	[42398] = "info",
})

BigWigs:AddColors("Jan'alai", {
	[42630] = "orange",
	[43140] = {"blue","red"},
	[43962] = "yellow",
})

BigWigs:AddSounds("Jan'alai", {
	[42630] = "info",
	[43140] = "alert",
	[43962] = "long",
})

BigWigs:AddColors("Halazzi", {
	[43139] = "red",
	[43302] = "orange",
	[43303] = {"blue","yellow"},
	["stages"] = "green",
})

BigWigs:AddSounds("Halazzi", {
	[43302] = "alert",
	[43303] = "alarm",
})

BigWigs:AddColors("Hex Lord Malacrass", {
	[43383] = "red",
	[43421] = {"blue","orange"},
	[43429] = "red",
	[43431] = "orange",
	[43436] = "yellow",
	[43451] = "orange",
	[43501] = {"blue","yellow"},
	[43548] = "orange",
})

BigWigs:AddSounds("Hex Lord Malacrass", {
	[43421] = "alarm",
	[43429] = "info",
	[43431] = "alarm",
	[43436] = "alert",
	[43451] = "alarm",
	[43548] = "alarm",
})

BigWigs:AddColors("Zul'jin", {
	[43093] = {"blue","yellow"},
	[43095] = "yellow",
	[43150] = {"blue","red"},
	["stages"] = "red",
})

BigWigs:AddSounds("Zul'jin", {
	[43093] = "alarm",
	[43095] = "warning",
	[43150] = "alert",
})
