-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Hydross the Unstable", {
	[38235] = {"blue","yellow"},
	[38246] = {"blue","yellow"},
	["mark"] = "red",
	["stance"] = "red",
})

BigWigs:AddSounds("Hydross the Unstable", {
	["mark"] = "alert",
})

BigWigs:AddColors("The Lurker Below", {
	[37478] = "yellow",
	["dive"] = {"cyan","green","orange","yellow"},
	["spout"] = {"red","yellow"},
})

BigWigs:AddSounds("The Lurker Below", {
	["dive"] = {"alarm","alert","info","long"},
	["spout"] = "warning",
})

BigWigs:AddColors("Leotheras the Blind", {
	[37640] = {"red","yellow"},
	["image"] = {"orange","red"},
	["mindcontrol"] = {"blue","orange"},
	["phase"] = {"orange","red","yellow"},
	["whisper"] = {"blue","yellow"},
})

BigWigs:AddSounds("Leotheras the Blind", {
	[37640] = "alert",
	["mindcontrol"] = "alert",
})

BigWigs:AddColors("Fathom-Lord Karathress", {
	[38330] = "red",
	["totem"] = {"orange","yellow"},
})

BigWigs:AddSounds("Fathom-Lord Karathress", {
	[38330] = "long",
	["totem"] = "alarm",
})

BigWigs:AddColors("Morogrim Tidewalker", {
	[37730] = "orange",
	[37850] = {"blue","red"},
	["globules"] = {"green","red"},
	["murloc"] = {"green","yellow"},
})

BigWigs:AddSounds("Morogrim Tidewalker", {
	[37730] = "alarm",
	[37850] = "alert",
	["globules"] = "alert",
})

BigWigs:AddColors("Lady Vashj", {
	[38280] = {"blue","red"},
	["barrier"] = "yellow",
	["elemental"] = "red",
	["naga"] = "yellow",
	["phase"] = {"red","yellow"},
	["strider"] = "yellow",
})

BigWigs:AddSounds("Lady Vashj", {
	[38280] = "alert",
	["phase"] = "alarm",
})
