-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Grubbis Discovery", {
	[3019] = {"green","red"},
	[434168] = "cyan",
	[434724] = {"blue","yellow"},
	[434941] = "orange",
	[436027] = "yellow",
	[436059] = "yellow",
	[436074] = {"green","red"},
	[436100] = {"blue","green","orange","yellow"},
	[439956] = "orange",
	["adds"] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Grubbis Discovery", {
	[434941] = "info",
	[436027] = "long",
	[436059] = "long",
	[436074] = "alarm",
	[436100] = {"alert","warning"},
	[439956] = "warning",
	["adds"] = "info",
	["stages"] = "info",
})

BigWigs:AddColors("Viscous Fallout Discovery", {
	[433546] = "orange",
	[434358] = "cyan",
	[434434] = {"blue","red"},
})

BigWigs:AddSounds("Viscous Fallout Discovery", {
	[433546] = {"info","warning"},
	[434358] = "long",
	[434434] = {"alarm","underyou"},
})

BigWigs:AddColors("Crowd Pummeler 9-60 Discovery", {
	[431839] = "blue",
	[432062] = {"blue","yellow"},
	[432423] = "orange",
})

BigWigs:AddSounds("Crowd Pummeler 9-60 Discovery", {
	[432062] = "alarm",
	[432423] = "warning",
})

BigWigs:AddColors("Electrocutioner 6000 Discovery", {
	[433251] = {"blue","red"},
	[433359] = {"blue","yellow"},
	[433398] = "orange",
})

BigWigs:AddSounds("Electrocutioner 6000 Discovery", {
	[433251] = "warning",
	[433359] = "alarm",
	[433398] = "info",
})

BigWigs:AddColors("Mechanical Menagerie Discovery", {
	[436570] = "orange",
	[436692] = "cyan",
	[436695] = "red",
	[436816] = {"blue","yellow"},
	[436825] = {"green","red"},
	[436833] = "orange",
	[436836] = "yellow",
	[438735] = "blue",
	[440073] = {"blue","cyan"},
	["run"] = "blue",
})

BigWigs:AddSounds("Mechanical Menagerie Discovery", {
	[436692] = "info",
	[436695] = "warning",
	[436816] = "alarm",
	[436833] = "alert",
	[436836] = {"info","long"},
	[438735] = "long",
	[440073] = "long",
})

BigWigs:AddColors("Mekgineer Thermaplugg Discovery", {
	[437853] = "cyan",
	[438683] = "purple",
	[438710] = {"blue","orange"},
	[438713] = "yellow",
	[438719] = "purple",
	[438720] = {"blue","orange"},
	[438723] = "yellow",
	[438726] = "purple",
	[438727] = {"blue","orange"},
	[438732] = {"green","yellow"},
	[438735] = "blue",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Mekgineer Thermaplugg Discovery", {
	[437853] = "info",
	[438683] = "alarm",
	[438713] = "alert",
	[438719] = "alarm",
	[438723] = "alert",
	[438726] = "alarm",
	[438732] = "alert",
	[438735] = "long",
})
