--
-- Generated by Raider.IO on 2025-07-31T06:02:29Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 6067,
        ["instance_map_id"] = 996,
        ["lfd_activity_ids"] = { 343, 344, 345, 346 },
        ["name"] = "Terrace of Endless Spring",
        ["shortName"] = "ToES",
    },
    [2] = {
        ["id"] = 6125,
        ["instance_map_id"] = 1008,
        ["lfd_activity_ids"] = { 335, 336, 337, 338 },
        ["name"] = "Mogu'shan Vaults",
        ["shortName"] = "MSV",
    },
    [3] = {
        ["id"] = 6297,
        ["instance_map_id"] = 1009,
        ["lfd_activity_ids"] = { 339, 340, 341, 342 },
        ["name"] = "Heart of Fear",
        ["shortName"] = "HOF",
    },
}
