--
-- Generated by Raider.IO on 2026-04-29T08:06:49Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 6622,
        ["instance_map_id"] = 1098,
        ["instance_map_ids"] = { 1098 },
        ["lfd_activity_ids"] = { 347, 348, 349, 350 },
        ["name"] = "Throne of Thunder",
        ["shortName"] = "TOT",
        ["localizationKey"] = "TOT",
    },
}
