--
-- Generated by Raider.IO on 2025-03-14T06:05:52Z
-- All rights reserved.
--
local _, ns = ...

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 5723,
        ["instance_map_id"] = 720,
        ["lfd_activity_ids"] = { 1586, 1587, 1588, 1589 },
        ["name"] = "Firelands",
        ["shortName"] = "FL",
    },
    [2] = {
        ["id"] = 5806,
        ["instance_map_id"] = 967,
        ["lfd_activity_ids"] = {  },
        ["name"] = "Dragon Soul",
        ["shortName"] = "DS",
    },
}
