--
-- Generated by Raider.IO on 2023-05-04T19:43:15Z
-- All rights reserved.
--
local _, ns = ...

-- Dungeon listing sorted by id
ns.dungeons = {
    [1] = {
        ["id"] = 5965,
        ["keystone_instance"] = 2,
        ["instance_map_id"] = 960,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Temple of the Jade Serpent",
        ["shortName"] = "TJS",
    },
    [2] = {
        ["id"] = 6932,
        ["keystone_instance"] = 165,
        ["instance_map_id"] = 1176,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "Shadowmoon Burial Grounds",
        ["shortName"] = "SBG",
    },
    [3] = {
        ["id"] = 7672,
        ["keystone_instance"] = 200,
        ["instance_map_id"] = 1477,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1368, 1824, 2280 },
        ["name"] = "Halls of Valor",
        ["shortName"] = "HOV",
    },
    [4] = {
        ["id"] = 8079,
        ["keystone_instance"] = 210,
        ["instance_map_id"] = 1571,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Court of Stars",
        ["shortName"] = "COS",
    },
    [5] = {
        ["id"] = 13954,
        ["keystone_instance"] = 401,
        ["instance_map_id"] = 2515,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1278, 1704, 2130 },
        ["name"] = "The Azure Vault",
        ["shortName"] = "AV",
    },
    [6] = {
        ["id"] = 13982,
        ["keystone_instance"] = 400,
        ["instance_map_id"] = 2516,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1440, 1920, 2400 },
        ["name"] = "The Nokhud Offensive",
        ["shortName"] = "NO",
    },
    [7] = {
        ["id"] = 14032,
        ["keystone_instance"] = 402,
        ["instance_map_id"] = 2526,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1152, 1536, 1920 },
        ["name"] = "Algeth'ar Academy",
        ["shortName"] = "AA",
    },
    [8] = {
        ["id"] = 14063,
        ["keystone_instance"] = 399,
        ["instance_map_id"] = 2521,
        ["lfd_activity_ids"] = {  },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Ruby Life Pools",
        ["shortName"] = "RLP",
    },
}

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 14030,
        ["instance_map_id"] = 2522,
        ["lfd_activity_ids"] = {  },
        ["name"] = "Vault of the Incarnates",
        ["shortName"] = "VOTI",
    },
}
