--
-- Generated by Raider.IO on 2023-06-21T21:15:07Z
-- All rights reserved.
--
local _, ns = ...

-- Dungeon listing sorted by id
ns.dungeons = {
    [1] = {
        ["id"] = 5035,
        ["keystone_instance"] = 438,
        ["instance_map_id"] = 657,
        ["lfd_activity_ids"] = { 138, 140, 1195 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "The Vortex Pinnacle",
        ["shortName"] = "VP",
    },
    [2] = {
        ["id"] = 7546,
        ["keystone_instance"] = 206,
        ["instance_map_id"] = 1458,
        ["lfd_activity_ids"] = { 428, 438, 448, 462 },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "Neltharion's Lair",
        ["shortName"] = "NL",
    },
    [3] = {
        ["id"] = 9164,
        ["keystone_instance"] = 245,
        ["instance_map_id"] = 1754,
        ["lfd_activity_ids"] = { 516, 517, 518, 519, 539 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "Freehold",
        ["shortName"] = "FH",
    },
    [4] = {
        ["id"] = 9391,
        ["keystone_instance"] = 251,
        ["instance_map_id"] = 1841,
        ["lfd_activity_ids"] = { 506, 507, 508, 541, 644 },
        ["timers"] = { 1080, 1440, 1800 },
        ["name"] = "The Underrot",
        ["shortName"] = "UNDR",
    },
    [5] = {
        ["id"] = 13968,
        ["keystone_instance"] = 403,
        ["instance_map_id"] = 2451,
        ["lfd_activity_ids"] = { 1185, 1186, 1187, 1188, 1194 },
        ["timers"] = { 1260, 1680, 2100 },
        ["name"] = "Uldaman: Legacy of Tyr",
        ["shortName"] = "ULD",
    },
    [6] = {
        ["id"] = 13991,
        ["keystone_instance"] = 405,
        ["instance_map_id"] = 2520,
        ["lfd_activity_ids"] = { 1161, 1162, 1163, 1164 },
        ["timers"] = { 1260, 1680, 2100 },
        ["name"] = "Brackenhide Hollow",
        ["shortName"] = "BH",
    },
    [7] = {
        ["id"] = 14011,
        ["keystone_instance"] = 404,
        ["instance_map_id"] = 2519,
        ["lfd_activity_ids"] = { 1169, 1170, 1171, 1172 },
        ["timers"] = { 1188, 1584, 1980 },
        ["name"] = "Neltharus",
        ["shortName"] = "NELT",
    },
    [8] = {
        ["id"] = 14082,
        ["keystone_instance"] = 406,
        ["instance_map_id"] = 2527,
        ["lfd_activity_ids"] = { 1165, 1166, 1167, 1168 },
        ["timers"] = { 1260, 1680, 2100 },
        ["name"] = "Halls of Infusion",
        ["shortName"] = "HOI",
    },
}

-- Raid listing sorted by id
ns.raids = {
    [1] = {
        ["id"] = 14663,
        ["instance_map_id"] = 2569,
        ["lfd_activity_ids"] = { 1235, 1236, 1237 },
        ["name"] = "Aberrus, the Shadowed Crucible",
        ["shortName"] = "ATSC",
    },
}
