local BtWQuests = BtWQuests;

do
    BtWQuests.Constant.Expansions.Classic = LE_EXPANSION_CLASSIC or 0
    BtWQuests.Constant.Category.Classic = BtWQuests.Constant.Category.Classic or {}
    BtWQuests.Constant.Chain.Classic = BtWQuests.Constant.Chain.Classic or {}
    local Category = BtWQuests.Constant.Category.Classic
    local Chain = BtWQuests.Constant.Chain.Classic

    Category.TheCapeOfStranglethorn = 122
    Chain.TheCapeOfStranglethorn = {
        TheTrollsOfZulgurubAlliance = 12201,
        TheTrollsOfZulgurubHorde = 12202,
        BustlingBootyBay = 12203,
        APiratesLifeForYou = 12204,
        BloodsailAndBrashtide = 12205,

        EmbedChain01 = 12211,
        EmbedChain02 = 12212,

        OtherAlliance = 12297,
        OtherHorde = 12298,
        OtherBoth = 12299,
    }

    -- 1
    BTWQUESTS_CATEGORY_CLASSIC_DUNMOROGH = 101
    BTWQUESTS_CATEGORY_CLASSIC_DUROTAR = 102
    BTWQUESTS_CATEGORY_CLASSIC_ELWYNN_FOREST = 103
    BTWQUESTS_CATEGORY_CLASSIC_MULGORE = 104
    BTWQUESTS_CATEGORY_CLASSIC_TIRISFAL_GLADES = 105
    BTWQUESTS_CATEGORY_CLASSIC_TELDRASSIL = 106

    -- 10
    BTWQUESTS_CATEGORY_CLASSIC_AZSHARA = 107
    BTWQUESTS_CATEGORY_CLASSIC_DARKSHORE = 108
    BTWQUESTS_CATEGORY_CLASSIC_LOCH_MODAN = 109
    BTWQUESTS_CATEGORY_CLASSIC_NORTHERN_BARRENS = 110
    BTWQUESTS_CATEGORY_CLASSIC_SILVERPINE_FOREST = 111
    BTWQUESTS_CATEGORY_CLASSIC_WESTFALL = 112

    -- 15
    BTWQUESTS_CATEGORY_CLASSIC_ASHENVALE = 113
    BTWQUESTS_CATEGORY_CLASSIC_HILLSBRAD_FOOTHILLS = 114
    BTWQUESTS_CATEGORY_CLASSIC_REDRIDGE_MOUNTAINS = 115

    --20
    BTWQUESTS_CATEGORY_CLASSIC_DUSKWOOD = 116
    BTWQUESTS_CATEGORY_CLASSIC_STONETALON_MOUNTAINS = 117
    BTWQUESTS_CATEGORY_CLASSIC_WETLANDS = 118

    --25
    BTWQUESTS_CATEGORY_CLASSIC_ARATHI_HIGHLANDS = 119
    BTWQUESTS_CATEGORY_CLASSIC_NORTHERN_STRANGLETHORN = 120
    BTWQUESTS_CATEGORY_CLASSIC_SOUTHERN_BARRENS = 121

    --30
    BTWQUESTS_CATEGORY_CLASSIC_CAPE_OF_STRANGLETHORN = 122
    BTWQUESTS_CATEGORY_CLASSIC_DESOLACE = 123
    BTWQUESTS_CATEGORY_CLASSIC_HINTERLANDS = 124

    --35
    BTWQUESTS_CATEGORY_CLASSIC_DUSTWALLOW_MARSH = 125
    BTWQUESTS_CATEGORY_CLASSIC_FERALAS = 126
    BTWQUESTS_CATEGORY_CLASSIC_WESTERN_PLAGUELANDS = 127

    --40
    BTWQUESTS_CATEGORY_CLASSIC_BADLANDS = 128
    BTWQUESTS_CATEGORY_CLASSIC_BLASTED_LANDS = 129
    BTWQUESTS_CATEGORY_CLASSIC_BURNING_STEPPES = 130
    BTWQUESTS_CATEGORY_CLASSIC_EASTERN_PLAGUELANDS = 131
    BTWQUESTS_CATEGORY_CLASSIC_FELWOOD = 132
    BTWQUESTS_CATEGORY_CLASSIC_SEARING_GORGE = 133
    BTWQUESTS_CATEGORY_CLASSIC_SILITHUS = 134
    BTWQUESTS_CATEGORY_CLASSIC_SWAMP_OF_SORROWS = 135
    BTWQUESTS_CATEGORY_CLASSIC_TANARIS = 136
    BTWQUESTS_CATEGORY_CLASSIC_THOUSAND_NEEDLES = 137
    BTWQUESTS_CATEGORY_CLASSIC_UNGORO_CRATER = 138
    BTWQUESTS_CATEGORY_CLASSIC_WINTERSPRING = 139

    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_DEFENDING_ORGRIMMAR = 10701
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_REDIRECTING_THE_LEY_LINES = 10702
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_SISTERS_OF_THE_SEA = 10703
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_SUBJECT_NINE_FROM_SPACE = 10704
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_THE_RAREST_SUBSTANCE_ON_AZEROTH = 10705
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_HEART_OF_ARKKOROC = 10706
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_THE_BEST_APPRENTICE = 10707
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_THE_CONQUEST_OF_AZSHARA = 10708
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_CHAIN1 = 10709
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_CHAIN2 = 10710
    BTWQUESTS_CHAIN_CLASSIC_AZSHARA_CHAIN3 = 10711

    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_THE_GREAT_ANIMAL_SPIRIT = 10801
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_THE_SHATTERSPEAR = 10802
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_THE_EYE_OF_ALL_STORMS = 10803
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_THE_DEVOURER = 10804
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_CONSUMED_BY_MADNESS = 10805
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_THE_BATTLE_FOR_DARKSHORE = 10806
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_CHAIN1 = 10807
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_CHAIN2 = 10808
    BTWQUESTS_CHAIN_CLASSIC_DARKSHORE_OTHER_ALLIANCE = 10809

    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_THE_ROAD_TO_THELSAMAR = 10901
    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_THE_AXIS_OF_AWFUL = 10902
    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_TWILIGHT_THREATS = 10903
    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_THE_FARSTRIDER_LODGE = 10904
    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_CHAIN1 = 10905
    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_CHAIN2 = 10906
    BTWQUESTS_CHAIN_CLASSIC_LOCH_MODAN_CHAIN3 = 10907

    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_FAR_WATCH = 11001
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_GROLDOM_FARM = 11002
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_DEFEATING_THE_KOLKAR = 11003
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_MYSTERIES_OF_THE_OASES = 11004
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_RATCHET = 11005
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_NOZZLEPOTS_OUTPOST = 11006
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_INSPIRATION_AND_HOPE = 11007
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN1 = 11008
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN2 = 11009
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN3 = 11010
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN4 = 11011
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN5 = 11012
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN6 = 11013
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_BARRENS_CHAIN7 = 11014

    BTWQUESTS_CHAIN_CLASSIC_SILVERPINE_FOREST_FORSAKEN_HIGH_COMMAND = 11101
    BTWQUESTS_CHAIN_CLASSIC_SILVERPINE_FOREST_FORSAKEN_REAR_GUARD = 11102
    BTWQUESTS_CHAIN_CLASSIC_SILVERPINE_FOREST_THE_SEPULCHER = 11103
    BTWQUESTS_CHAIN_CLASSIC_SILVERPINE_FOREST_THE_RUINS_OF_GILNEAS = 11104
    BTWQUESTS_CHAIN_CLASSIC_SILVERPINE_FOREST_AMBERMILL = 11105
    BTWQUESTS_CHAIN_CLASSIC_SILVERPINE_FOREST_ON_THE_BATTLEFRONT = 11106

    BTWQUESTS_CHAIN_CLASSIC_WESTFALL_CRIMESCENEINVESTIGATION = 11201
    BTWQUESTS_CHAIN_CLASSIC_WESTFALL_INVESTIGATINGTHESHADOWS = 11202
    BTWQUESTS_CHAIN_CLASSIC_WESTFALL_THEDEFIASBROTHERHOODREBORN = 11203
    BTWQUESTS_CHAIN_CLASSIC_WESTFALL_CHAIN1 = 11204
    BTWQUESTS_CHAIN_CLASSIC_WESTFALL_CHAIN2 = 11205

    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_MAESTRAS_POST = 11301
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_SAVING_ASTRANAAR = 11302
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_STARDUST_SPIRE = 11303
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_THE_POWER_OF_DARTOLS_ROD = 11304
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_BRINGING_HARMONY_TO_THE_ELEMENTS_ALLIANCE = 11305
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_THE_SATYR_OF_SATYRNAAR = 11306
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_THE_CORRUPTED_HEART_OF_THE_FOREST_ALLIANCE = 11307

    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_THE_CORRUPTED_HEART_OF_THE_FOREST_HORDE = 11311
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_THE_DIPLOMAT_FROM_SILVERMOON = 11312
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_SPLINTERTREES_DEMONIC_DEFENSE = 11313
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_ZORAMGAR_OUTPOST = 11314
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_THE_BOMBING_OF_ASTRANAAR = 11315
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_WEAPONS_OF_THEIR_DESTRUCTION = 11316
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_BRINGING_HARMONY_TO_THE_ELEMENTS_HORDE = 11317

    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_CHAIN01 = 11321
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_CHAIN02 = 11322
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_CHAIN03 = 11323

    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN01 = 11331
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN02 = 11332
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN03 = 11333
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN04 = 11334
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN05 = 11335
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN06 = 11336
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN07 = 11337
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN08 = 11338
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN09 = 11339
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN10 = 11340
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN11 = 11341
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN12 = 11342
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN13 = 11343
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN14 = 11344
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN15 = 11345
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN16 = 11346
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN17 = 11347
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN18 = 11348
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN19 = 11349
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN20 = 11350
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN21 = 11351
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN22 = 11352
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN23 = 11353
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN24 = 11354
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN25 = 11355
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN26 = 11356
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN27 = 11357
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN28 = 11358
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN29 = 11359
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN30 = 11360
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN31 = 11361
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN32 = 11362
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN33 = 11363
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN34 = 11364
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN35 = 11365
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN36 = 11366
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN37 = 11367
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN38 = 11368
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN39 = 11369
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN40 = 11370
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN41 = 11371
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_EMBED_CHAIN42 = 11372

    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_OTHER_ALLIANCE = 11397
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_OTHER_HORDE = 11398
    BTWQUESTS_CHAIN_CLASSIC_ASHENVALE_OTHER_BOTH = 11399

    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_AZURELODEMINE = 11401
    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_SLUDGEFIELDS = 11402
    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_STORMPIKE = 11403
    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_EASTPOINTTOWER = 11404
    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_SOUTHSHORE = 11405
    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_TARREN_MILL = 11406
    BTWQUESTS_CHAIN_CLASSIC_HILLSBRAD_FOOTHILLS_BRAZIE_FARMSTEAD = 11407

    BTWQUESTS_CHAIN_CLASSIC_REDRIDGE_MOUNTAINS_THEGNOLLOFFENSIVE = 11501
    BTWQUESTS_CHAIN_CLASSIC_REDRIDGE_MOUNTAINS_KEESHANSRAIDERS = 11502
    BTWQUESTS_CHAIN_CLASSIC_REDRIDGE_MOUNTAINS_FIRSTBLOOD = 11503
    BTWQUESTS_CHAIN_CLASSIC_REDRIDGE_MOUNTAINS_CHAIN1 = 11504

    BTWQUESTS_CHAIN_CLASSIC_DUSKWOOD = 11601
    BTWQUESTS_CHAIN_CLASSIC_DUSKWOOD_STALVAN = 11602
    BTWQUESTS_CHAIN_CLASSIC_DUSKWOOD_HERMIT = 11603
    BTWQUESTS_CHAIN_CLASSIC_DUSKWOOD_MORBENT_FEL = 11604
    BTWQUESTS_CHAIN_CLASSIC_DUSKWOOD_MORLADIM = 11605

    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_CLEARING_A_PATH = 11701
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_SLAY_THE_WARLORD = 11702
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_SELDARRIA = 11703
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_AN_UNCONVENTIONAL_ALLY = 11704

    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_A_SHORTLIVED_VICTORY = 11711
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_LEGIONNAIRE = 11712
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_DA_VOODOO = 11713
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_HONOR_NEVER_FORSAKE_IT = 11714

    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_OTHER_ALLIANCE = 11797
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_OTHER_HORDE = 11798
    BTWQUESTS_CHAIN_CLASSIC_STONETALON_MOUNTAINS_OTHER_BOTH = 11799

    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_FALDIRS_COVE = 11901
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_GALENS_FALL = 11902
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_HAMMERFALL = 11903
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_REFUGE_POINT = 11904
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_MYZRAELS_POINT = 11905
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_CHAIN1 = 11906
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_CHAIN3 = 11907
    BTWQUESTS_CHAIN_CLASSIC_ARATHI_HIGHLANDS_CHAIN2 = 11908

    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_SLABCHISEL_SURVEY = 11801
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_THE_FLOODING_OF_MENETHIL = 11802
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_ENGINEERS_AND_ARCHAEOLOGISTS = 11803
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_WARDENS_OF_THE_WETLANDS = 11804
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_CHAIN1 = 11805
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_CHAIN2 = 11806
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_CHAIN3 = 11807
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_CHAIN4 = 11808
    BTWQUESTS_CHAIN_CLASSIC_WETLANDS_CHAIN5 = 11809

    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_STRANGLETHORN_OHGANANKA = 12001
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_STRANGLETHORN_REBEL_CAMP = 12002
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_STRANGLETHORN_NESINGWARY = 12003
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_STRANGLETHORN_HATCHLING_ALLIANCE = 12004
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_STRANGLETHORN_HATCHLING_HORDE = 12005
    BTWQUESTS_CHAIN_CLASSIC_NORTHERN_STRANGLETHORN_YENNIKU = 12006

    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_HUNTERS_HILL = 12101
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_CAMP_UNAFE = 12102
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_LIFE_FROM_THE_DREAM_HORDE = 12103
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_VENDETTA_POINT = 12104
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_DESOLATION_HOLD = 12105
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_FIRESTONE_POINT_HORDE = 12106
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_SPEARHEAD = 12107

    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_HONORS_STAND = 12111
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_NORTHWATCH_HOLD = 12112
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_TEEGANS_EXPEDITION = 12113
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_LIFE_FROM_THE_DREAM_ALLIANCE = 12114
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_FORWARD_COMMAND = 12115
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_FIRESTONE_POINT_ALLIANCE = 12116
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_FORT_TRIUMPH = 12117

    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_CHAIN01 = 12121
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_CHAIN02 = 12122
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN01 = 12131
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN02 = 12132
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN03 = 12133
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN04 = 12134
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN05 = 12135
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN06 = 12136
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN07 = 12137
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN08 = 12138
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN09 = 12139
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN10 = 12140
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN11 = 12141
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN12 = 12142
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN13 = 12143
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN14 = 12144
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN15 = 12145
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN16 = 12146
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN17 = 12147
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN18 = 12148
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN19 = 12149
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN20 = 12150
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN21 = 12151
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN22 = 12152
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_EMBED_CHAIN23 = 12153
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_OTHER_ALLIANCE = 12197
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_OTHER_HORDE = 12198
    BTWQUESTS_CHAIN_CLASSIC_SOUTHERN_BARRENS_OTHER_BOTH = 12199

    BTWQUESTS_CHAIN_CLASSIC_CAPE_OF_STRANGLETHORN_ZULGURUB = 12201
    BTWQUESTS_CHAIN_CLASSIC_CAPE_OF_STRANGLETHORN_PIRATES = 12202
    BTWQUESTS_CHAIN_CLASSIC_CAPE_OF_STRANGLETHORN_BOOTY_BAY = 12203
    BTWQUESTS_CHAIN_CLASSIC_CAPE_OF_STRANGLETHORN_BLOODSAIL = 12204

    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_THE_NAGA_THREAT = 12301
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_KARNUMS_GLADE = 12302
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_THREATS_FROM_SARTHERIS_STAND_ALLIANCE = 12303
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_THREATS_FROM_SARTHERIS_STAND_HORDE = 12304
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_UNITING_THE_TRIBES = 12305
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_ALLIANCE = 12306
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_ON_BEHALF_OF_THE_HORDE = 12307
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN01 = 12311
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN02 = 12312
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN03 = 12323
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN04 = 12324
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN05 = 12325
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN06 = 12326
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN07 = 12327
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_CHAIN08 = 12328
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN01 = 12331
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN02 = 12332
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN03 = 12333
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN04 = 12334
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN05 = 12335
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN06 = 12336
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN07 = 12337
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN08 = 12338
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN09 = 12339
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN10 = 12340
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_EMBED_CHAIN11 = 12341
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_OTHER_ALLIANCE = 12397
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_OTHER_HORDE = 12398
    BTWQUESTS_CHAIN_CLASSIC_DESOLACE_OTHER_BOTH = 12399

    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_STORMFEATHER_OUTPOST = 12401
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_JINTHAALOR_ALLIANCE = 12402
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_QUELDANIL_LODGE = 12403
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_JINTHAALOR_HORDE = 12404
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_HIRIWATHA = 12405
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_REVANTUSK_VILLAGE = 12406
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_CHAIN1 = 12407
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_CHAIN2 = 12408
    BTWQUESTS_CHAIN_CLASSIC_HINTERLANDS_CHAIN3 = 12409

    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_WILD_THREATS = 12501
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_WORK_LEFT_UNDONE = 12502
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_SWAMP_EYE_STORY_HORDE = 12503
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_CONNECTION_TO_THE_GRIMTOTEM = 12504
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_ONYXIAS_BROOD = 12505
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_CHALLENGING_THE_OVERLORD = 12506
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_THE_CHALLENGE_OF_THE_STONEMAUL_HORDE = 12507

    BTWQUESTS_CHAIN_CLASSIC_FERALAS_THE_FATE_OF_TAERAR_HORDE = 12601
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_THE_TWILIGHT_SERMON_HORDE = 12602
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_MUISEK = 12603
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_FREED_HORDE = 12604
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_THE_DRAGONS_OF_NIGHTMARE_HORDE = 12605

    BTWQUESTS_CHAIN_CLASSIC_FERALAS_THE_FATE_OF_TAERAR_ALLIANCE = 12611
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_THE_TWILIGHT_SERMON_ALLIANCE = 12612
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_FREED_ALLIANCE = 12613
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_FORCES_OF_NATURE = 12614
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_THE_DRAGONS_OF_NIGHTMARE_ALLIANCE = 12615

    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN01 = 12627
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN02 = 12628
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN03 = 12638
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN04 = 12639
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN05 = 12640
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN06 = 12642
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_CHAIN07 = 12643

    BTWQUESTS_CHAIN_CLASSIC_FERALAS_EMBED_CHAIN01 = 12641
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_EMBED_CHAIN02 = 12637

    BTWQUESTS_CHAIN_CLASSIC_FERALAS_OTHER_ALLIANCE = 12697
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_OTHER_HORDE = 12698
    BTWQUESTS_CHAIN_CLASSIC_FERALAS_OTHER_BOTH = 12699

    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_DISGRACE_THE_DEFECTORS = 12511
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_SWAMP_EYE_STORY_ALLIANCE = 12512
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_THE_TERROR_OF_THERAMORE = 12513
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_DEFIAS_IN_DUSTWALLOW = 12514
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_PRISONERS_OF_THE_GRIMTOTEM = 12515
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_THE_HYAL_FAMILY = 12516
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_THE_CHALLENGE_OF_THE_STONEMAUL_ALLIANCE = 12517

    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_CHAIN01 = 12521
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_CHAIN02 = 12522
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_CHAIN03 = 12523
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_CHAIN04 = 12524

    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN01 = 12531
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN02 = 12532
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN03 = 12533
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN04 = 12534
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN05 = 12535
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN06 = 12536
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN07 = 12537
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN08 = 12538
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN09 = 12539
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN10 = 12540
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN11 = 12541
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN12 = 12542
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN13 = 12543
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN14 = 12544
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN15 = 12545
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_EMBED_CHAIN16 = 12546

    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_OTHER_ALLIANCE = 12597
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_OTHER_HORDE = 12598
    BTWQUESTS_CHAIN_CLASSIC_DUSTWALLOW_MARSH_OTHER_BOTH = 12599

    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_FIRST_ALLIANCE = 12701
    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_PEACE_ALLIANCE = 12702
    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_SECOND_ALLIANCE = 12703
    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_STEAD = 12704
    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_FIRST_HORDE = 12705
    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_PEACE_HORDE = 12706
    BTWQUESTS_CHAIN_CLASSIC_WESTERN_PLAGUELANDS_SECOND_HORDE = 12707

    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_RHEA = 12801
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_THE_FATE_OF_A_DRAGONFLIGHT_ALLIANCE = 12802
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_THE_FATE_OF_A_DRAGONFLIGHT_HORDE = 12803
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_THE_TITANS_KNOWLEDGE_ALLIANCE = 12804
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_THE_TITANS_KNOWLEDGE_HORDE = 12805
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_THE_DAY_THAT_DEATHWING_CAME = 12806
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN04 = 12814
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN09 = 12819
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN10 = 12820
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN11 = 12821
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN12 = 12822
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN13 = 12823
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN14 = 12824
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_TEMP_CHAIN15 = 12825
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_OTHER_ALLIANCE = 12897
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_OTHER_HORDE = 12898
    BTWQUESTS_CHAIN_CLASSIC_BADLANDS_OTHER_BOTH = 12899

    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_RAZELIKH_ALLIANCE = 12901
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_RAZELIKH_HORDE = 12902
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_THE_TAINTED_FOREST_ALLIANCE = 12903
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_THE_TAINTED_FOREST_HORDE = 12904
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_AVENGING_THE_ROCKPOOL = 12905

    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_CHAIN01 = 12911

    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_EMBED_CHAIN01 = 12921
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_EMBED_CHAIN02 = 12922
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_EMBED_CHAIN03 = 12923

    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_OTHER_ALLIANCE = 12997
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_OTHER_HORDE = 12998
    BTWQUESTS_CHAIN_CLASSIC_BLASTED_LANDS_OTHER_BOTH = 12999

    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_PREPARATION_ALLIANCE = 13001
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_PREPARATION_HORDE = 13002
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_ANNIHILATION_ALLIANCE = 13003
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_ANNIHILATION_HORDE = 13004
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_INFILTRATION_ALLIANCE = 13005
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_INFILTRATION_HORDE = 13006
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_ANTICIPATION_ALLIANCE = 13007
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_ANTICIPATION_HORDE = 13008
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_OTHER_ALLIANCE = 13097
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_OTHER_HORDE = 13098
    BTWQUESTS_CHAIN_CLASSIC_BURNING_STEPPES_OTHER_BOTH = 13099

    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_PALADIN_PALS = 13101
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_REDPATH = 13102
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_TYRS_HAND = 13103
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_CRUSADE = 13104
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_JOURNEYS_END = 13105
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_LIGHTS_SHIELD_TOWER = 13106
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_LIGHTS_HOPE_CHAPEL = 13107
    BTWQUESTS_CHAIN_CLASSIC_EASTERN_PLAGUELANDS_PLAGUEWOOD = 13108

    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMERALD_SANCTUARY = 13201
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_RUINS_OF_CONSTELLAS = 13202
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_WILDHEART_POINT = 13203
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_BLOODVENOM_POST = 13204
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_WHISPERWIND_GROVE = 13205
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_REJOINING_THE_FOREST = 13206
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_A_DESTINY_OF_FLAME_AND_SORROW = 13207
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_WAR_IN_THE_FOREST_ALLIANCE = 13208
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_WAR_IN_THE_FOREST_HORDE = 13209
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_THE_TIMBERMAWS_ALLY = 13210

    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN01 = 13211
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN02 = 13212
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN03 = 13213
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN04 = 13214
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN05 = 13215
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN06 = 13216
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN07 = 13217
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN08 = 13218
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_EMBED_CHAIN09 = 13219
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_OTHER_ALLIANCE = 13297
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_OTHER_HORDE = 13298
    BTWQUESTS_CHAIN_CLASSIC_FELWOOD_OTHER_BOTH = 13299

    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_THORIUM_ADVANCE = 13301
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_THE_SEAT_OF_THE_BROTHERHOOD = 13302
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_IN_THE_HALL_OF_THE_MOUNTAINLORD = 13303
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_INTO_THE_GORGE = 13304
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_EMBED_CHAIN01 = 13311
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_EMBED_CHAIN02 = 13312
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_EMBED_CHAIN03 = 13313
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_OTHER_ALLIANCE = 13397
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_OTHER_HORDE = 13398
    BTWQUESTS_CHAIN_CLASSIC_SEARING_GORGE_OTHER_BOTH = 13399

    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_TWILIGHTS_RUN = 13401
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_MISTRESS_NATALIA_MARALITH = 13402
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_UNRAVELING_THE_MYSTERY = 13403
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_A_TERRIBLE_PURPOSE = 13404
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_TWILIGHT_LEXICON = 13405
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_CHAIN01 = 13411
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_CHAIN02 = 13412
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_CHAIN03 = 13413
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_CHAIN04 = 13414
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_CHAIN05 = 13415
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_CHAIN06 = 13416
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_OTHER_ALLIANCE = 13497
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_OTHER_HORDE = 13498
    BTWQUESTS_CHAIN_CLASSIC_SILITHUS_OTHER_BOTH = 13499

    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_BOGPADDLE = 13501
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_THE_BLOODMIRE_ALLIANCE = 13502
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_THE_BLOODMIRE_HORDE = 13503
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_THE_SHIFTING_MIRE_ALLIANCE = 13504
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_THE_SHIFTING_MIRE_HORDE = 13505
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_THE_SUNKEN_TEMPLE = 13506
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_CHAIN01 = 13511
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_CHAIN02 = 13512
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_EMBED_CHAIN01 = 13513
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_OTHER_ALLIANCE = 13597
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_OTHER_HORDE = 13598
    BTWQUESTS_CHAIN_CLASSIC_SWAMP_OF_SORROWS_OTHER_BOTH = 13599

    BTWQUESTS_CHAIN_CLASSIC_TANARIS_SOUTHSEA_PIRATES_ALLIANCE = 13601
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_SOUTHSEA_PIRATES_HORDE = 13602
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_BUG_FREE = 13603
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_ADVANCING_OUR_INTERESTS_ALLIANCE = 13604
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_ADVANCING_OUR_INTERESTS_HORDE = 13605
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_GRUDGE_MATCH = 13607
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_THE_TITANS_ALLIANCE = 13608
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_THE_TITANS_HORDE = 13609
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_CHAIN01 = 13626
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_CHAIN02 = 13627
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_CHAIN03 = 13623
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_EMBED_CHAIN01 = 13611
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_EMBED_CHAIN02 = 13617
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_EMBED_CHAIN03 = 13618
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_EMBED_CHAIN04 = 13619
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_EMBED_CHAIN05 = 13625
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_OTHER_ALLIANCE = 13697
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_OTHER_HORDE = 13698
    BTWQUESTS_CHAIN_CLASSIC_TANARIS_OTHER_BOTH = 13699

    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_THE_TREASURE_TROVE_ALLIANCE = 13701
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_THE_TREASURE_TROVE_HORDE = 13702
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_BUGS_IN_THE_ICE_CREAM = 13703
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_THE_CHIEF_OF_CHIEFS_ALLIANCE = 13704
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_THE_CHIEF_OF_CHIEFS_HORDE = 13705
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_MIND_THE_DROP = 13706
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_THE_EVIL_YOU_KNOW = 13707

    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_CHAIN01 = 13711
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_CHAIN02 = 13712
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_CHAIN04 = 13713
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_CHAIN03 = 13714
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_CHAIN05 = 13715
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_EMBED_CHAIN01 = 13716

    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_OTHER_ALLIANCE = 13797
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_OTHER_HORDE = 13798
    BTWQUESTS_CHAIN_CLASSIC_THOUSAND_NEEDLES_OTHER_BOTH = 13799

    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_THE_PYLONS_OF_UNGORO = 13801
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_OBSERVE_THE_WORLD = 13802
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_THE_BALLAD_OF_MAXIMILLIAN = 13803
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN1 = 13811
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN2 = 13812
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN3 = 13813
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN4 = 13814
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN5 = 13815
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN6 = 13816
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN7 = 13817
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN8 = 13818
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_CHAIN9 = 13819
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_OTHER_ALLIANCE = 13897
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_OTHER_HORDE = 13898
    BTWQUESTS_CHAIN_CLASSIC_UNGORO_CRATER_OTHER_BOTH = 13899

    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_THE_WINTERFALL_FURBOLG = 13901
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_RUINS_OF_KELTHERIL = 13902
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_SUPERIOR_WEAPONS = 13903
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_SPRAY_IT_AND_SLAY_IT = 13904
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_THE_HUB_OF_GOODGRUBS_GRUB = 13905
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_YETI_SURPRISE = 13906
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_JADRAGS_FATE = 13907
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_UMBRANSES_DELIVERANCE = 13908
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN1 = 13911
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN2 = 13912
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN3 = 13913
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN4 = 13914
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN5 = 13915
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN6 = 13916
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN7 = 13917
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN8 = 13918
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_CHAIN9 = 13919
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_OTHER_ALLIANCE = 13997
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_OTHER_HORDE = 13998
    BTWQUESTS_CHAIN_CLASSIC_WINTERSPRING_OTHER_BOTH = 13999
end

do
    BtWQuests.Constant.Expansions.Cataclysm = LE_EXPANSION_CATACLYSM or 3;
    BtWQuests.Constant.Category.Cataclysm = BtWQuests.Constant.Category.Cataclysm or {};
    BtWQuests.Constant.Chain.Cataclysm = BtWQuests.Constant.Chain.Cataclysm or {};
    local Category = BtWQuests.Constant.Category.Cataclysm;
    local Chain = BtWQuests.Constant.Chain.Cataclysm;

    Category.MountHyjal = 401
    Category.Vashjir = 402
    Category.Deepholm = 403
    Category.Uldum = 404
    Category.TwilightHighlands = 405

    Chain.MountHyjal = {}
    Chain.Vashjir = {}
    Chain.Deepholm = {}
    Chain.Uldum = {}
    Chain.TwilightHighlands = {}

    BtWQuests.Database:AddExpansion(BtWQuests.Constant.Expansions.Cataclysm, {
        background = {
            texture = "Interface\\EncounterJournal\\UI-EJ-CATACLYSM"
        },
        image = {
            texture = "Interface\\AddOns\\BtWQuestsCataclysm\\UI-Expansion",
            texCoords = {0, 0.90625, 0, 0.8125}
        }
    })
end