-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Baron Aquanis Discovery", {
	[404806] = {"blue","yellow"},
	[405953] = "blue",
	[413664] = "orange",
})

BigWigs:AddSounds("Baron Aquanis Discovery", {
	[404806] = "warning",
	[405953] = "underyou",
	[413664] = "long",
})

BigWigs:AddColors("Ghamoo-ra Discovery", {
	[406970] = "orange",
	[407025] = {"red","yellow"},
	[407077] = "purple",
	[407095] = {"blue","purple"},
})

BigWigs:AddSounds("Ghamoo-ra Discovery", {
	[406970] = "warning",
	[407025] = {"info","long"},
	[407095] = "alert",
})

BigWigs:AddColors("Lady Sarevess Discovery", {
	[367741] = {"blue","green","red"},
	[407568] = {"blue","orange"},
	[407653] = {"blue","yellow"},
	[407791] = {"blue","green","red"},
})

BigWigs:AddSounds("Lady Sarevess Discovery", {
	[367741] = "alarm",
	[407568] = {"alert","underyou"},
	[407653] = "warning",
	[407791] = "alarm",
})

BigWigs:AddColors("Gelihast Discovery", {
	[411956] = {"blue","yellow"},
	[411959] = {"blue","red"},
	[412072] = {"blue","purple"},
	[412456] = "cyan",
})

BigWigs:AddSounds("Gelihast Discovery", {
	[411956] = "alert",
	[411959] = "alert",
	[412072] = "warning",
	[412456] = "long",
})

BigWigs:AddColors("Lorgus Jett Discovery", {
	[22883] = {"green","orange"},
	[414691] = "yellow",
	[414763] = "red",
	[419636] = "orange",
	[419649] = "cyan",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Lorgus Jett Discovery", {
	[22883] = "alert",
	[414691] = "alert",
	[414763] = "warning",
	[419636] = "info",
})

BigWigs:AddColors("Twilight Lord Kelris Discovery", {
	[423135] = {"blue","yellow"},
	[425265] = {"blue","green","orange","red"},
	[425460] = "blue",
	[426489] = {"blue","cyan"},
	["stages"] = "cyan",
})

BigWigs:AddSounds("Twilight Lord Kelris Discovery", {
	[425265] = {"alert","info"},
	[425460] = "warning",
	["stages"] = "long",
})

BigWigs:AddColors("Aku'mai Discovery", {
	[427625] = {"blue","green"},
	[428482] = {"blue","green"},
	[429168] = "red",
	[429356] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Aku'mai Discovery", {
	[427625] = "alarm",
	[428482] = "alarm",
	[429168] = "warning",
	[429356] = "warning",
	["stages"] = {"info","long"},
})
