-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Azuregos Season of Discovery", {
	[21097] = "orange",
	[21099] = "orange",
	[21147] = "yellow",
	[22067] = {"green","red"},
})

BigWigs:AddSounds("Azuregos Season of Discovery", {
	[21097] = "alert",
	[21099] = "alert",
	[21147] = "alarm",
	[22067] = {"info","warning"},
})
