-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Apocron", {
	[241458] = "orange",
	[241498] = "yellow",
	[241518] = {"blue","green","red"},
})

BigWigs:AddSounds("Apocron", {
	[241458] = "warning",
	[241498] = "long",
	[241518] = {"alarm","info"},
})

BigWigs:AddColors("Brutallus", {
	[233484] = "orange",
	[233515] = "red",
	[233566] = "yellow",
})

BigWigs:AddSounds("Brutallus", {
	[233484] = "warning",
	[233515] = "alert",
	[233566] = "info",
})

BigWigs:AddColors("Calamir", {
	[217877] = {"blue","yellow"},
	[217893] = "red",
	[217925] = {"blue","yellow"},
	[217966] = "red",
	[217986] = "red",
	[218012] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Calamir", {
	[217877] = "alert",
	[217893] = "alarm",
	[217925] = {"alarm","long"},
	[217966] = "warning",
	[217986] = "alert",
	[218012] = "long",
	["stages"] = "info",
})

BigWigs:AddColors("Drugon the Frostblood", {
	[219493] = "red",
	[219542] = "yellow",
	[219602] = {"blue","green","orange"},
	[219803] = {"blue","green"},
})

BigWigs:AddSounds("Drugon the Frostblood", {
	[219493] = "alert",
	[219542] = "warning",
	[219602] = {"alarm","long"},
})

BigWigs:AddColors("Flotsam", {
	[220295] = {"blue","green"},
	[220340] = "yellow",
	[223317] = "red",
	[223373] = "orange",
})

BigWigs:AddSounds("Flotsam", {
	[220295] = "alarm",
	[220340] = "warning",
	[223317] = "alert",
	[223373] = "long",
})

BigWigs:AddColors("Humongris", {
	[216428] = {"blue","yellow"},
	[216430] = "orange",
	[216432] = {"blue","red"},
	[216467] = "green",
	[216476] = "blue",
	[216817] = {"blue","red"},
})

BigWigs:AddSounds("Humongris", {
	[216428] = "alarm",
	[216430] = "info",
	[216432] = "alert",
	[216467] = "long",
	[216476] = "alert",
	[216817] = "warning",
})

BigWigs:AddColors("Levantus", {
	[217206] = "blue",
	[217235] = "orange",
	[217249] = "yellow",
	[217344] = "green",
})

BigWigs:AddSounds("Levantus", {
	[217206] = "alarm",
	[217235] = "warning",
	[217249] = "long",
	[217344] = "alert",
})

BigWigs:AddColors("Malificus", {
	[233570] = "yellow",
	[233614] = "orange",
	[233850] = "blue",
	[234452] = "orange",
})

BigWigs:AddSounds("Malificus", {
	[233570] = "info",
	[233614] = "warning",
	[233850] = "alert",
	[234452] = "alarm",
})

BigWigs:AddColors("Na'zak the Fiend", {
	[219349] = "orange",
	[219591] = "yellow",
	[219813] = "red",
	[219861] = "green",
})

BigWigs:AddSounds("Na'zak the Fiend", {
	[219349] = "info",
	[219591] = "alert",
	[219813] = "long",
	[219861] = "warning",
})

BigWigs:AddColors("Nithogg", {
	[-13327] = "red",
	[212836] = "yellow",
	[212852] = "orange",
	[212867] = "red",
	[212887] = {"blue","green"},
})

BigWigs:AddSounds("Nithogg", {
	[-13327] = "alarm",
	[212836] = "alert",
	[212852] = "warning",
	[212867] = "info",
	[212887] = "warning",
})

BigWigs:AddColors("Shar'thos", {
	[215806] = "blue",
	[215821] = "red",
	[215876] = "blue",
	[216043] = {"blue","yellow"},
	[216044] = "orange",
})

BigWigs:AddSounds("Shar'thos", {
	[215806] = "alert",
	[215821] = "info",
	[215876] = "alert",
	[216043] = "alarm",
	[216044] = "warning",
})

BigWigs:AddColors("Si'vash", {
	[233968] = "orange",
	[233996] = "orange",
	[241433] = "yellow",
})

BigWigs:AddSounds("Si'vash", {
	[233968] = "long",
	[233996] = "warning",
	[241433] = "alarm",
})

BigWigs:AddColors("The Soultakers", {
	[213420] = "green",
	[213532] = "red",
	[213588] = {"blue","red"},
	[213606] = "yellow",
	[213625] = "blue",
	[213665] = "orange",
})

BigWigs:AddSounds("The Soultakers", {
	[213420] = "long",
	[213532] = "warning",
	[213588] = "alert",
	[213606] = "warning",
	[213625] = "alarm",
	[213665] = "info",
})

BigWigs:AddColors("Withered J'im", {
	[223614] = "orange",
	[223623] = "yellow",
	[223715] = "cyan",
})

BigWigs:AddSounds("Withered J'im", {
	[223614] = "alert",
	[223623] = "alarm",
	[223715] = "info",
})
