-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lord Kazzak Season of Discovery", {
	[21056] = {"blue","green","red","yellow"},
	[21063] = {"blue","green","orange"},
})

BigWigs:AddSounds("Lord Kazzak Season of Discovery", {
	[21056] = {"long","warning"},
	[21063] = "alarm",
})
